### ISSUE TITLE
Not generating C\C++Code from a simple Python source code file 

### ISSUE THREAD

**Issue by developeralgo8888** [Nuitka/Nuitka#848] opened 2020-10-02 23:49 UTC
Trying to generate C\C++  code from a small python source code ou_model.py file but it has been running for nearly 5 hours and no source code results . All the python packages imported are installed .

On Linux Machine: 
OS = UBUNTU 20.04 with Anaconda 3(Latest) for Linux 
CPython = 3.8 
GCC = 9.3 
All required Python modules and packages installed.

On Windows  Machine: 
OS = Windows 10 with Anaconda 3(Latest) for windows installed
CPython = 3.8 
GCC = 9.3
Visual C version | Redist Year | CPython =  14.2 | 2019 |  3.8
MinGW64:       9.0 | 2008 | 3.2
All required Python modules and packages installed.

[ou_model.py.txt](https://github.com/Nuitka/Nuitka/files/5320765/ou_model.py.txt)

I used the command below on both Ubuntu 20.04  and Windows 10  but both has been running for over 5 hours with no C source code generated in python-filename.build folder

python -m nuitka  --generate-c-only  --nofollow-import-to astropy  --follow-imports  --prefer-source-code  --assume-yes-for-downloads   --show-progress   --plugin-enable  pylint-warnings   ou_model.py

Please any help or assistance is appreciated

**Comment by kayhayen** [comment] 2020-10-03 16:51
Ok, on develop I have done a lot for scalability, but this mostly aims at the C compilation for now. Nuitka used to have endloos loops in some cases, but 0.6.9 ought to no longer show that. But then you didn't say what version you were using.

**Comment by kayhayen** [comment] 2020-10-03 16:56
In terms of smallness... numpy, scipy, pandas, tensorflow, dash, ipython, llvmlite, numba, .... my pip install is still running while I am typing this.

**Comment by kayhayen** [comment] 2020-10-03 18:27
So this is a duplicate of other issues, that complain about scalability and lack of caching, which is the most prudent solution probably. So far Nuitka caches nothing, makes programs with this many dependencies unpracticable. Not sure when I will get to solve this. Right now I am not even optimizing Nuitka run time generally all that much yet, but this issue adds nothing really, so I am closing it.

**Closed by kayhayen** 2020-10-03 18:27 UTC
Labels: needs_example
