### ISSUE TITLE
Error on Backend C - "fatal error: error writing to -: Invalid argument | } | ^ on .c file"

### ISSUE THREAD

**Issue by rafaelgerges** [Nuitka/Nuitka#2699] opened 2024-02-07 19:46 UTC
```
2.0.1
Commercial: None
Python: 3.11.2 (tags/v3.11.2:878ead1, Feb  7 2023, 16:38:35) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\NR\LAEPI\Python-Compiler\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0)
```

Nuitka was installed via pip.

```
PyPI names and versions:
altgraph==0.17.4
bitarray==2.9.2
bitstring==4.1.4
cffi==1.16.0
contourpy==1.2.0
cryptography==42.0.0
cycler==0.12.1
Cython==3.0.8
ecdsa==0.18.0
esptool==4.7.0
fonttools==4.47.2
intelhex==2.3.0
kiwisolver==1.4.5
matplotlib==3.8.1
Nuitka==2.0.1
numpy==1.26.3
ordered-set==4.1.0
packaging==23.2
pefile==2023.2.7
pillow==10.2.0
pyarmor==8.4.6
pyarmor.cli.core==5.4.3
pycparser==2.21
pyinstaller==5.8.0
pyinstaller-hooks-contrib==2024.0
pyparsing==3.1.1
pyserial==3.5
python-dateutil==2.8.2
pywin32-ctypes==0.2.2
PyYAML==6.0.1
reedsolo==1.7.0
scipy==1.12.0
six==1.16.0
zstandard==0.22.0
```

The Nuitka command

```
python -m nuitka --standalone --follow-imports --enable-plugin=anti-bloat --enable-plugin=tk-inter,numpy D:\NR\LAEPI\Python-Compiler\src\__main__.py
```

The error occurs in Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0) as below

```
Nuitka-Options: Used command line options: --standalone --follow-imports --enable-plugin=anti-bloat --enable-plugin=tk-inter,numpy D:\NR\LAEPI\Python-Compiler\src\__main__.py
Nuitka-Options: Following all imports is the default for standalone mode and need not be specified.
Nuitka-Plugins:WARNING: anti-bloat: Plugin is defined as always enabled, no need to enable it.
Nuitka-Plugins:WARNING: numpy: This plugin has been deprecated, do not enable it anymore.
Nuitka: Starting Python compilation with Nuitka '2.0.1' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:delvewheel: Detected usage of 'delvewheel' version '1.5.2' in module 'numpy'.          
Nuitka-Plugins:delvewheel: Detected usage of 'delvewheel' version '1.5.1' in module 'matplotlib'.
Nuitka-Plugins:delvewheel: Detected usage of 'delvewheel' version '1.5.1' in module 'mpl_toolkits'.
Nuitka-Plugins:options-nanny: Note, when using 'tkinter', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback and
Nuitka-Plugins:options-nanny: error information, so delay this until your program is working and remove once you find it non-working, and use '--enable-console' to make it explicit and not see this message.
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL will not be able to create Qt image objects.
Nuitka-Plugins:matplotlib: Using configuration file or default backend 'TkAgg'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                                               
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
module.PIL.ExifTags.c:8116:1: fatal error: error writing to -: Invalid argument
 8116 | }
      | ^
compilation terminated.

Backend C: 37.2%|█████████▎               | 181/487scons: *** [module.PIL.ExifTags.o] Error 1
module.PyInstaller.building.toc_conversion.c:7207:1: fatal error: error writing to -: Invalid argument
 7207 | }
      | ^
compilation terminated.

Backend C: 37.6%|█████████▍               | 183/487scons: *** [module.PyInstaller.building.toc_conversion.o] Error 1
module.__main__.c:9480:1: fatal error: error writing to -: Invalid argument
 9480 | }
      | ^
compilation terminated.

Backend C: 37.8%|█████████▍               | 184/487scons: *** [module.__main__.o] Error 1
module.PyInstaller.depend.utils.c:14049:1: fatal error: error writing to -: Invalid argument
14049 | }
      | ^
compilation terminated.

Backend C: 38.2%|█████████▌               | 186/487scons: *** [module.PyInstaller.depend.utils.o] Error 1
module.matplotlib._api.c:14161:1: fatal error: error writing to -: Invalid argument
14161 | }
      | ^
compilation terminated.
Backend C: 38.4%|█████████▌               | 187/487scons: *** [module.matplotlib._api.o] Error 1
module.matplotlib._api.deprecation.c:17159:1: fatal error: error writing to -: Invalid argument
17159 | }
      | ^
compilation terminated.

Backend C: 38.6%|█████████▋               | 188/487scons: *** [module.matplotlib._api.deprecation.o] Error 1
module.PyInstaller.depend.analysis.c:28824:1: fatal error: error writing to -: Invalid argument
28824 | }
compilation terminated.

Backend C: 38.8%|█████████▋               | 189/487scons: *** [module.PyInstaller.depend.analysis.o] Error 1
module.PyInstaller.utils.hooks.c:32739:1: fatal error: error writing to -: Invalid argument
32739 | }
      | ^
compilation terminated.

Backend C: 39.0%|█████████▊               | 190/487scons: *** [module.PyInstaller.utils.hooks.o] Error 1
module.PIL.TiffImagePlugin.c:94538:1: fatal error: error writing to -: Invalid argument
94538 | }
      | ^
compilation terminated.

Backend C: 39.2%|█████████▊               | 191/487scons: *** [module.PIL.TiffImagePlugin.o] Error 1
Nuitka-Reports: Compilation report written to file 'nuitka-crash-report.xml'.
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

Any ideia how about this error?

**Comment by KevinRodriguez777** [comment] 2024-02-07 19:53
please send a Minimal Reproducible Example, without one, it's hard to figure out the problem.
can you also trim down your enviroment by creating an venv without pyinstaller and pyarmor? unless they're needed, which pyinstaller shouldn't be.

**Comment by kayhayen** [comment] 2024-02-08 10:10
That's a strange one. I am currently annoyed, that I do not know if this is our MinGW64 during actual runtime or not, the version matches it of course. So that should indicate a low memory or some such situation. With 487 files, usually it doesn't happen, but in reality it depends on the worst performer. None of those files give huge line numbers.

The options used show a sign of old Nuitka usage. I wonder how PyInstaller ends up in a compilation, maybe I need to add it to the anti-bloat stuff, much like Cython, it sometimes sneaks it, not sure how widespread that is. I am not sure that PyInstaller has huge files though.

The low memory is going to help right away, because then it doesn't use `-pipe` with GCC, which for large files, means to use memory rather than temporary files, that is the `-` that is being talked of here.  The section of the user manual that is about this, probably needs examples added, such that Google can find them, adding it to the user manual now.

With no reproducer provided, and this being a C compiler issue in the end, I am closing it as invalid.

**Closed by kayhayen** 2024-02-08 10:10 UTC

**Comment by kayhayen** [comment] 2024-02-08 10:32
So I added that to the user manual:

```
These are example error messages, that are a sure sign of too low
memory, there is no end to them.

.. code::

   # gcc
   fatal error: error writing to -: Invalid argument
   # MSVC
   fatal error C1002: compiler is out of heap space in pass 2
```

I didn't find other messages now searching for low memory on the issue tracker, but I am pretty sure the list has to grow.

**Comment by rafaelgerges** [comment] 2024-02-08 11:28
> please send a Minimal Reproducible Example, without one, it's hard to figure out the problem. can you also trim down your enviroment by creating an venv without pyinstaller and pyarmor? unless they're needed, which pyinstaller shouldn't be.

Yes, so I create a new VENV without pyinstaller and pyarmor and with Pillow 10.0.0, clear all the temp and cache files used in the build and rerun the Nuitka. The problems disappear. Thanks for the insight.

**Comment by rafaelgerges** [comment] 2024-02-08 11:29
> That's a strange one. I am currently annoyed, that I do not know if this is our MinGW64 during actual runtime or not, the version matches it of course. So that should indicate a low memory or some such situation. With 487 files, usually it doesn't happen, but in reality it depends on the worst performer. None of those files give huge line numbers.
> 
> The options used show a sign of old Nuitka usage. I wonder how PyInstaller ends up in a compilation, maybe I need to add it to the anti-bloat stuff, much like Cython, it sometimes sneaks it, not sure how widespread that is. I am not sure that PyInstaller has huge files though.
> 
> The low memory is going to help right away, because then it doesn't use `-pipe` with GCC, which for large files, means to use memory rather than temporary files, that is the `-` that is being talked of here. The section of the user manual that is about this, probably needs examples added, such that Google can find them, adding it to the user manual now.
> 
> With no reproducer provided, and this being a C compiler issue in the end, I am closing it as invalid.

Yes, I think add pyinstaller and maybe pyarmor to the anti-bloab is a good way to avoid theses errors. Thanks.

**Comment by kayhayen** [comment] 2024-02-09 11:17
I believe pyarmor and Nuitka, I think are even incompatible, I am still surprised anything would import it, but I guess, we should see it. I do not like the anti-competitive looks of warning about those imports, not sure what to do about that.

**Comment by rafaelgerges** [comment] 2024-02-09 12:09
> I believe pyarmor and Nuitka, I think are even incompatible, I am still surprised anything would import it, but I guess, we should see it. I do not like the anti-competitive looks of warning about those imports, not sure what to do about that.

Pyarmor was not being used with Nuitka. This was an application that I made to deploy with Pyinstaller + Pyarmor and at the end of the day I preferred to switch to Nuitka.

Best regards.

**Comment by kayhayen** [comment] 2024-02-09 12:47
Yeah, was still in your venv config, but pyinstaller you managed to import through something somehow.

**Comment by KevinRodriguez777** [comment] 2024-02-09 17:01
> I believe pyarmor and Nuitka, I think are even incompatible, I am still surprised anything would import it, but I guess, we should see it. I do not like the anti-competitive looks of warning about those imports, not sure what to do about that.

people have had sucess using pyarmor and nuitka together, just food for thought if you care.

**Comment by kayhayen** [comment] 2024-02-10 13:57
> > I believe pyarmor and Nuitka, I think are even incompatible, I am still surprised anything would import it, but I guess, we should see it. I do not like the anti-competitive looks of warning about those imports, not sure what to do about that.
> 
> people have had sucess using pyarmor and nuitka together, just food for thought if you care.

I actually once lost a customer to pyarmor, due to him using a library that wouldn't work without being ran inside of pyarmor binary, so I care a little bit, but it seems an outlier. 

If they compile extension modules with Nuitka, I guess, they can use it with pyarmor, but protection will be so weak there, why would they. But lets decide I do not really care, because I do not have anything to learn from it really, because people make weird choices, and I cannot say this is overly documented. One day probably I am going to make an analysis of that or have somebody do it, to make a comparison.
