### ISSUE TITLE
Catching exception within co-routine and returning non-None cause a "RuntimeError: cannot reuse already awaited compiled_coroutine"

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#667] opened 2020-04-07 18:23 UTC
Python Version: 3.7.7
Nuitka Version: 0.6.7
OS/Arch: Linux x86_64

The following code raises the exception `RuntimeError: cannot reuse already awaited compiled_coroutine`. Make sure there is no web server on 127.0.0.1 otherwise just change the URL to something that does not work.
```
import aiohttp
import asyncio

async def http_call():
    async with aiohttp.ClientSession() as session:
        try:
            async with session.get("http://127.0.0.1"):
                pass
        except Exception:
            pass

    return True

async def run():
    await http_call()
    await http_call()

asyncio.get_event_loop().run_until_complete(run())
```

Stacktrace:
```
Traceback (most recent call last):
  File "/opt/app/main.dist/main.py", line 18, in <module>
  File "/opt/app/main.dist/asyncio/base_events.py", line 587, in run_until_complete
  File "/opt/app/main.dist/main.py", line 15, in run
RuntimeError: cannot reuse already awaited compiled_coroutine http_call
```

The issue is not present when removing `return True` at the end of `http_call()`.

**Comment by kayhayen** [comment] 2020-04-09 07:08
The last statement is very puzzling, and makes me wonder if this has anything to do with `aiohttp` and even `asyncio` at all.

**Comment by levesquejf** [comment] 2020-04-10 20:30
Here is another example without `aiohttp`. The issue is not prensent when removing `return False` at the end of `execute()`.

```
import asyncio
import shutil

async def rmtree(path):
    return await asyncio.get_event_loop().run_in_executor(None, sync_rmtree, path)

def sync_rmtree(path):
    return shutil.rmtree(path)

async def execute():
    try:
        await rmtree("/tmp/test1234.txt")
    except FileNotFoundError:
        pass

    return False

async def run():
    await execute()

asyncio.get_event_loop().run_until_complete(run())
```

**Comment by kayhayen** [comment] 2020-04-11 06:24
I made a difference of the generated code with and without the return change. Notice, that `return None` is implicit if not stated, and leads to only a very minor code change in generated C code.

I got then distracted by an unnecessary difference, which is a bug of the constant code generation, where unused constants are added, but these were of course harmless. Still a nice find.

My first theory about this bug is that somehow the exception handler restore of the current exception is not cleaning up values about previous exception or published exception attached to the coroutine. That these then get used, but why only in this one case, I am debugging this now. From the code I couldn't get that idea confirmed.

My first idea was that "None" return should have an optimization, that other cases do not, and that it would avoid creating the `StopIteration()` object. I falsified that just now (while adding a TODO to do just that). They are treated the same at return time, which is potentially wasteful, but certainly explains no difference.

So, what I now think, from traces, is that the `StopIteration(True)` is considered illegal response by the `throw` deeper implementation, when putting an exception into it. That explains the difference. A normal `StopIteration` is the only acceptable response there, or `GeneratorExit`, but not a `StopIteration` with a value. And I just noticed, that when Nuitka publishes this as an exception, the `None` is treated as no value typically, whereas `True` would create an exception value object when normalizing occurs.

So these might be two bugs. I believe #1 might be that we are sending the return value exception into ourselves at all. This could be triggered by the await enabling that mode, but failing to disable it, or be always done. I think I falsified the later, but you never know with coroutines control flow is hard to see.

And #2 might be, that `StopIteration(False)` would be a valid response, or allowed to be sent into a finished coroutine, and that we are being incompatible there.

Both should be easy to verify and fix. I hope to have more findings later today.

**Comment by kayhayen** [comment] 2020-04-11 07:44
On more thought, I came to realise that "2" must be what's going on. The coroutine code returns from the await of and got an exception there, which it throws into itself, and as a response gets a return with a value that is not None. That of course must be allowed and is all the issue. There is no chance for "1" to occur, we only ever enter it once, and do not consider these values.

**Comment by kayhayen** [comment] 2020-04-11 12:39
So, I think I have this maybe. I notice that the `StopIteration(True)` gets sent into `run` async method, which continues its `yield from` status, passing values through. That status is of course wrong, and stopping the yield from, seems to resolve the issue.

I have put this also through a quick `test_coroutines` check. It will be a moment, until I can prepare a factory build, as I really prefer to see my CI go over it first, but this seems caught.

So this was really about a compiled coroutine swallowing a non-exit exception into it and return a non-none value, while being awaited from another compiled coroutine, and then this was ignored and treated as an exit request, only if it's a plain stop iteration exception, but not the boolean value, we had there.

Therefore it can be expected, that the fix is pretty certainly non-invasive and non-regressive. I did however improve the tracing capabilities from manual prints, to more structured printing, so I could see through the mess easier.

I will keep you updated, when it's usable for you. I will now start investigating the reference count issue, hoping this one is resolved.

Yours,
Kay

**Comment by kayhayen** [comment] 2020-04-11 12:48
I just noted, and merged the fix to the asyncgen implementation as well. They should have had the same issue. Nuitka has separate implementation for coroutines and asyncgen, but of course they share much of logic, and in this instance, the same would apply, so compiled coroutine and compile asyncgen are interchangeable in the bug description.

**Comment by kayhayen** [comment] 2020-04-11 17:21
@levesquejf the fix is on the factory branch, you may give it a try. I have a pretty good feeling about it, should be only better now.

**Comment by kayhayen** [comment] 2020-04-11 17:22
Go here http://nuitka.net/doc/factory.html and the caveat is more real than normal, because factory also contains huge performance work, that seems stable to me, but might still have issues.

**Comment by levesquejf** [comment] 2020-04-11 17:32
@kayhayen Both examples are fixed with the factory build. 👍

**Comment by kayhayen** [comment] 2020-05-01 09:50
This is now in the latest pre-release, and will soon be released.

**Comment by kayhayen** [comment] 2020-05-11 14:57
The release 0.6.8 was just made and contains the correction.

**Closed by kayhayen** 2020-05-11 14:57 UTC
Labels: bug, develop
