### ISSUE TITLE
Using subprocess forward of stdout/stderr not working properly with "--windows-disable-console" option

### ISSUE THREAD

**Issue by Rajjco** [Nuitka/Nuitka#1693] opened 2022-07-22 16:24 UTC
My code runs fine in Pycharm IDE but after Compiling it with Nuitka it behaves differently and doesn't work as intended.

If I enable the console window It runs properly but not with --windows-disable-console.

Code runs fine when compiled using pyinstaller.

```
0.9.6
Commercial: None
Python: 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\Xen3\PycharmProjects\YoutubeDownloader\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

**Installed Nuitka using Pycharm Terminal in virtual environment.**

**Installed Packages:**
`altgraph==0.17.2
auto-py-to-exe==2.21.0
bottle==0.12.21
bottle-websocket==0.2.9
cffi==1.15.1
Eel==0.14.0
future==0.18.2
gevent==21.12.0
gevent-websocket==0.10.1
greenlet==1.1.2
imageio==2.19.5
Nuitka==0.9.6
numpy==1.23.1
ordered-set==4.1.0
pefile==2022.5.30
Pillow==9.2.0
pycparser==2.21
pyinstaller==5.2
pyinstaller-hooks-contrib==2022.8
pyparsing==3.0.9
pywin32-ctypes==0.2.0
tinyaes==1.0.3
whichcraft==0.6.1
zope.event==4.5.0
zope.interface==5.4.0
`

**Here is the command I ran In Pycharm Terminal with venv activated:**
`nuitka --standalone --follow-imports --enable-plugin=tk-inter --windows-icon-from-ico=Resources\logo.png --windows-disable-console main.py`

Link to source code:
https://github.com/Rajjco/Simple-Youtube-Downloader-GUI/blob/main/main.py

**Comment by kayhayen** [comment] 2022-07-23 08:52
So, that would be something, that is not supposed to happen, because Nuitka should create `NUL` file handles in case of disabled outputs, I guess, making a reproducer is now easy.

**Comment by kayhayen** [comment] 2022-07-23 09:17
Is this warning from Python, or from C code, I wonder. Because Python code works perfectly for me.

```
import sys
sys.stderr.write("HELLO")
sys.exit(27)
```

```
python3.9 bin/nuitka-run --disable-console Mini.py
Nuitka-Options:INFO: Used command line options: --disable-console Mini.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka:INFO: Starting Python compilation with Nuitka '1.0rc' on Python '3.9' commercial grade '1.0.0'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 9 files (no progress information available).
Nuitka-Scons:INFO: Compiled 9 C files using clcache with 8 cache hits and 1 cache misses.
Nuitka:INFO: Keeping build directory 'Mini.build'.
Nuitka:INFO: Successfully created 'Mini.exe'.
Nuitka:INFO: Launching 'Mini.cmd'.

kayha@anna MINGW64 ~/repos/Py2C (main)
$ echo $?
27
```

I am not entirely sure, that `multiprocessing` will not become an issue though. Is your software using that?

**Comment by kayhayen** [comment] 2022-07-23 10:46
I see, so, what you are saying is that, if you do not redirect stderr, the one from `--disable-console` will not work for this, and that might totally make sense. It is essentially created using `open()` on `NUL:` but it also wraps things with a `io._TextIOWrapper` such that it will not crash on things, that need encoding. 

I should be able to reproduce this with some form of cmd and echo I guess.

**Comment by kayhayen** [comment] 2022-07-23 10:59
Thanks for hanging in there, I believe I narrowed it down to this:
```
_winapi.GetStdHandle(_winapi.STD_ERROR_HANDLE)
```

That is `None` in case of the disabled console, and then a different code path will be taken. From what I see, it would be this:

```
            if stderr is None:
                errwrite = _winapi.GetStdHandle(_winapi.STD_ERROR_HANDLE)
                if errwrite is None:
                    _, errwrite = _winapi.CreatePipe(None, 0)
                    errwrite = Handle(errwrite)
                    _winapi.CloseHandle(_)
            elif stderr == PIPE:
                errread, errwrite = _winapi.CreatePipe(None, 0)
                errread, errwrite = Handle(errread), Handle(errwrite)

```

These branches look similar, but not identical. The solution will be to not go there, and have `_winapi.STD_ERROR_HANDLE` set to a proper file handle number, rather than None. It would surely be interesting to understand why the absence of errread is a difference, but who cares. I should have a fix for you to try soon.

**Comment by kayhayen** [comment] 2022-07-23 17:43
There is a fix for this on the factory branch: https://nuitka.net/doc/factory.html

Basically, it registers the new `sys.stdout` and stuff with the Windows API, and `subprocess` then ought to find it.

**Comment by kayhayen** [comment] 2022-07-24 09:49
This works though:

```
import subprocess
import os

if os.path.exists("output.txt"):
        os.unlink("output.txt")

try:
        subprocess.Popen(f'cmd /c "echo 20"', shell=True)
except Exception as e:
        with open("output.txt", "w") as output:
                output.write("NOT OK")
else:

        with open("output.txt", "w") as output:
                output.write("OK")
```

Now I need to figure out how to create a warning, such that we exercise stderr too.

**Comment by kayhayen** [comment] 2022-07-24 09:58
```
import subprocess
import os, sys

if os.path.exists("output.txt"):
        os.unlink("output.txt")

try:
        subprocess.Popen(f'cmd /c "xecho 20"', stdout=subprocess.PIPE, shell=True)
except Exception as e:
        with open("output.txt", "w") as output:
                output.write("NOT OK %s\n" % repr(e))
                output.write("stdin: %s\n" % sys.stdin)
                output.write("stdout: %s\n" % sys.stdout)
                output.write("stderr: %s\n" % sys.stderr)
else:
        with open("output.txt", "w") as output:
                output.write("OK\n")
                output.write("stdin: %s\n" % sys.stdin)
                output.write("stdout: %s\n" % sys.stdout)
                output.write("stderr: %s\n" % sys.stderr)
```

This reproduces things. Strangely, indeed stdout must be from a pipe, then it complains about `OSError(9, "Invalid handle", None, 6, None)`

**Comment by kayhayen** [comment] 2022-07-24 10:02
Of course, the handles look good to me:

```
stdin: <_io.TextIOWrapper name='NUL:' mode='r' encoding='utf-8'>
stdout: <_io.TextIOWrapper name='NUL:' encoding='utf-8'>
stderr: <_io.TextIOWrapper name='NUL:' encoding='utf-8'>
```

**Comment by kayhayen** [comment] 2022-07-24 10:59
I think, I have drilled this down to `stdin`. So i can run this:


```rm -f output.txt && python3.9 bin/nuitka-run --force-stderr=NUL: --force-stdout=NUL: Mini.py && cat output.txt``` without any issue.

**Comment by kayhayen** [comment] 2022-07-24 11:03
But once I redirect stdin from `NUL`, I am in trouble (there is no option to do it, I hard coded it for testing). I think, that was added, because code using `input` was not working otherwise. If you set `subprocess.NULLDEV` for stdin, it will work. I believe it is a good practice anyway, doing it for most of my subprocesses, but maybe it needs another factory update, since I also discovered that a compilation warning fix, may have corrupted the code correctness as well.

**Comment by kayhayen** [comment] 2022-07-24 11:09
Ah, ok, I got it, expect a fix soon. The `sys.stdin` is cherrished by Python, but if we don't expose that file to Windows API, it's all just fine.

**Comment by kayhayen** [comment] 2022-07-24 11:13
Updated, should be good to go.

For reference, the manual test I used, does this:
```
import os
import subprocess
import sys

import _winapi

if os.path.exists("output.txt"):
    os.unlink("output.txt")

sys.stdout.write("hey stdout\n")
sys.stdout.write("hey stderr\n")

try:
    subprocess.Popen(f'cmd /c "xecho 20"', stdout=subprocess.PIPE, shell=True)
except Exception as e:
    with open("output.txt", "w") as output:
        output.write("NOT OK %s\n" % repr(e))
        output.write(
            "stdin: %s\n" % (sys.stdin, _winapi.GetStdHandle(_winapi.STD_INPUT_HANDLE))
        )
        output.write(
            "stdout: %s %s\n"
            % (sys.stdout, _winapi.GetStdHandle(_winapi.STD_OUTPUT_HANDLE))
        )
        output.write(
            "stderr: %s %s\n"
            % (sys.stderr, _winapi.GetStdHandle(_winapi.STD_ERROR_HANDLE))
        )
else:
    with open("output.txt", "w") as output:
        output.write("OK\n")
        output.write(
            "stdin: %s\n" % (sys.stdin, _winapi.GetStdHandle(_winapi.STD_INPUT_HANDLE))
        )
        output.write(
            "stdout: %s %s\n"
            % (sys.stdout, _winapi.GetStdHandle(_winapi.STD_OUTPUT_HANDLE))
        )
        output.write(
            "stderr: %s %s\n"
            % (sys.stderr, _winapi.GetStdHandle(_winapi.STD_ERROR_HANDLE))
        )
```

**Comment by kayhayen** [comment] 2022-07-30 15:30
This is part of 1.0 release.

**Closed by kayhayen** 2022-07-30 15:30 UTC
Labels: bug, factory
