### ISSUE TITLE
Windows: Compiler PATH was regression on at least Windows

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Nuitka/Nuitka#1961] opened 2022-12-25 10:46 UTC
Starting with Nuitka 1.2 version (and newer) I get such error:
```
python -m nuitka --version

1.2
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\built\_testsoft\WinPython\WinPythonPortable\python-3.10.9.amd64\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

```
Nuitka-Options:INFO: Used command line options: --standalone --mingw64 ..\..\test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.2' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: D:\WebTools\WinLibs_x64\bin\gcc.exe (gcc.exe).
AssertionError: :
  File "D:\built\_test~1\WINPYT~1\MODULE~2\nuitka\build\BACKEN~1.SCO", line 1030:

    enableCcache(
  File "D:\built\_testsoft\WinPython\.modules_pip\nuitka\build\SconsCaching.py", line 212:
    return _injectCcache(
  File "D:\built\_testsoft\WinPython\.modules_pip\nuitka\build\SconsCaching.py", line 147:
    assert areSamePaths(
```

Nuitka installed through PiP. 
```
python -m pip freeze

msvc-runtime==14.34.31931
Nuitka==1.2
ordered-set==4.1.0
sqlite-bro==0.12.2
winpython==5.3.20221211
```

The problem does not occur with older versions (e.g. 1.1.8).

Log from last 1.3.2 version:
```
Nuitka-Options:INFO: Used command line options: --standalone --mingw64 ..\..\test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.3.2' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: D:\WebTools\WinLibs_x64\bin\gcc.exe (gcc.exe).
AssertionError: :
  File "D:\built\_test~1\WINPYT~1\MODULE~2\nuitka\build\BACKEN~1.SCO", line 984:
    enableCcache(
  File "D:\built\_testsoft\WinPython\.modules_pip\nuitka\build\SconsCaching.py", line 212:
    return _injectCcache(
  File "D:\built\_testsoft\WinPython\.modules_pip\nuitka\build\SconsCaching.py", line 147:
    assert areSamePaths(
```

**Comment by ArkadiuszMichalski** [comment] 2022-12-25 11:23
Hmm this line 984 from `Backend.scons` is:
```
# Check if ccache is installed, and complain if it is not.
if env.gcc_mode and not disable_ccache:
    enableCcache(
        env=env,
        source_dir=source_dir,
        python_prefix=python_prefix,
        target_arch=target_arch,
        assume_yes_for_downloads=assume_yes_for_downloads,
    )
```

But I have ccache, even if I don't have it, Nuitka downloads it.

**Comment by kayhayen** [comment] 2022-12-25 12:23
Have you left out any information, e.g. environment variables you have set?

**Comment by kayhayen** [comment] 2022-12-25 12:24
Also, I wonder why the flavor detection failed on WinPython there, maybe they changed something.

**Comment by ArkadiuszMichalski** [comment] 2022-12-25 12:54
>Have you left out any information, e.g. environment variables you have set?

Yes, I change the default folders in my bath file.

`set USERPROFILE=%~dp0_cache` << when I set `USERPROFILE` variable then Nuitka put all files here (downloaded, cache, etc). I don't use any space or strange chars here.

I also change where PiP instal modules and add this path when running Python:
```
set WINPY_DIR=%~dp0
set PYTHONPATH=%WINPY_DIR%.modules_pip;

set PIP_TARGET=%WINPY_DIR%.modules_pip
set PIP_CACHE_DIR=%PIP_TARGET%\.cache
```

This worked fine until Nuitka 1.2.

What I test more:
- add directly `Ccache` and  `DependencyWalker` folders to `Path` variable but same problem as above
- set `NUITKA_CCACHE_BINARY` to `ccache.exe` bin file, like:
`set NUITKA_CCACHE_BINARY=%USERPROFILE%\_Ccache_x64\ccache.exe`
but same problem as above.

But I noticed that when I use "":
`set NUITKA_CCACHE_BINARY="%USERPROFILE%\_Ccache_x64\ccache.exe"`
then work goes on. It's weird because I don't have spaces or other strange chars in the path.

But even then there are next errors:
```
Nuitka-Options:INFO: Used command line options: --standalone --mingw64 ..\..\test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.3.2' on Python '3.10' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: D:\WebTools\WinLibs_x64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, scalability problem.

Nuitka-Scons:WARNING: You are not using ccache.

Nuitka will make use of Dependency Walker (https://dependencywalker.com) tool
to analyze the dependencies of Python extension modules.

Is it OK to download and put it in '.\Nuitka\Nuitka\Cache\downloads\depends\x86_64'.

No installer needed, cached, one time question.
```

Hmm, still a problem with `depends` (even if I have it added in the `Path`). Is there any environment variable for  `depends` (same as we have for `ccache`)?

There is definitely some problem with getting the correct path for `ccache` and `depends`, which was not present in earlier Nuitka versions. I run 1.1.8 and all works fine.

**Comment by ArkadiuszMichalski** [comment] 2022-12-25 13:05
Btw, for test I just use simple paths:

`
set PATH=%PATH%;D:\_Ccache_x64;D:\_DependencyWalker_x64
`

and same problem as first post.

**Comment by ArkadiuszMichalski** [comment] 2022-12-25 13:44
@kayhayen
Something with `env.the_compiler` in `SconsCaching.py` is wrong.

In my setup I have added permanently in `Path` MinGW. But when working with Nuitka I set `CC` var to WinLibs in my bath files.

And now what I see:

Nuitka 1.3.2
`getExecutablePath(os.path.basename(env.the_compiler), env=env)` << return MinGW
`cc_path` << return WinLibs

Nuitka 1.1.8
`getExecutablePath(os.path.basename(env.the_compiler), env=env)` << return WinLibs
`cc_path` << return WinLibs

That's why this assertion not pass:
```
    if ccache_binary is not None and os.path.exists(ccache_binary):
        # Make sure the
        # In case we are on Windows, make sure the Anaconda form runs outside of Anaconda
        # environment, by adding DLL folder to PATH.
        assert areSamePaths(
            getExecutablePath(os.path.basename(env.the_compiler), env=env), cc_path
        )
```

**Comment by ArkadiuszMichalski** [comment] 2022-12-25 15:19
I check how `env._dict["ENV"]["PATH"]` and `os.environ["PATH"]` looks like. They are always the same in my case.

But:
- Nuitka > 1.1.8 << this versions don't add my path from `CC` to above places (to `PATH` variable).
- Nuitka == 1.1.8 << this version add my path from `CC` to `PATH` variable to above places (at the beginning).

That's what makes it different. It just omitted adding the path from the `CC` variable to the `PATH` variable (at the beginning). Need to find where.

**Comment by kayhayen** [comment] 2022-12-26 09:20
I get it, when I find the time, I will try and reproduce the situation. Nuitka may have increased the gcc version requirement for the compiler, and switches away to its own winlibs, but maybe not complete enough, such that in this situation the inconsistency is then detected by the assertion. The assertion may also be wrong, but I believe winlibs gcc should be added at the start of the PATH, if I am not mistaken.

**Comment by kayhayen** [comment] 2022-12-26 09:25
None of these holds a quick verification, the switch updates env["CC"]  which immediately after is used to set "env.the_compiler", but your finding with `setEnvironmentVariable` definitely holds some water.

**Comment by kayhayen** [comment] 2022-12-26 09:37
Nah, I think Nuitka tries to avoid polluting environment variables that are not yet set in its run time, the Scons is supposed to work fine from env, and when launching processes to use the other one. So "CC" would be updated in your case, but not generally, and ought to not have much of an effect anyway.

What I now think, is that the assertion is wrong. Your own winlibs is coming from PATH, and `cc_path` is the one for `PATH` already, unless it's absolute, which might be coming from CC or from gcc replacement. I think however, that it should have given a message. Can you provide unchanged code --show-scons output?

**Comment by ArkadiuszMichalski** [comment] 2022-12-26 11:21
@kayhayen 
I described the reason for this behavior in the last post https://github.com/Nuitka/Nuitka/issues/1961#issuecomment-1364697397. You change `setEnvironmentVariable` https://github.com/Nuitka/Nuitka/commit/f289042cf27d0ad406b7a2f4eda5af19db3d6cd8, but probably wrong. Why use such line?
https://github.com/Nuitka/Nuitka/blob/4d54b1fba3274724980686e02a933661a8659268/nuitka/build/SconsUtils.py#L328-L329
Why check `value` in `os.environ`?

Rather, it should be:
```
     else: 
         os.environ[key] = value 
```

Because of this change you newer add value from `CC` to `Path`, but you want to do this (and that's how it was done before):
https://github.com/Nuitka/Nuitka/blob/4d54b1fba3274724980686e02a933661a8659268/nuitka/build/SconsUtils.py#L157-L161
https://github.com/Nuitka/Nuitka/blob/4d54b1fba3274724980686e02a933661a8659268/nuitka/build/SconsUtils.py#L339-L351

And we finish with this wrong/changed `setEnvironmentVariable`:
https://github.com/Nuitka/Nuitka/blob/4d54b1fba3274724980686e02a933661a8659268/nuitka/build/SconsUtils.py#L325-L329

So all happens because of this one line:
https://github.com/Nuitka/Nuitka/blob/4d54b1fba3274724980686e02a933661a8659268/nuitka/build/SconsUtils.py#L328

**Comment by kayhayen** [comment] 2022-12-26 14:16
Ah, that is a typo, it was indeed supposed to check with the `key` of course. In this way, indeed updates to "PATH" have become not visible, and some of them might be necessary, yes. Ok, this i then fixable. I didn't see the mistake even when looking closely at the code, my bad. Thanks for your research.

**Comment by kayhayen** [comment] 2022-12-26 14:40
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. Recently factory is more unstable than usual, due to scalability work, but it might be good enough already. I will release it with the next hotfix anyway.

**Comment by ArkadiuszMichalski** [comment] 2022-12-26 14:54
@kayhayen 

Yes, using `key` instead of `value` fix my problem. Thx.

**Comment by kayhayen** [comment] 2022-12-30 19:31
Part of the 1.3.4 release I just made.

**Closed by kayhayen** 2022-12-30 19:31 UTC
Labels: bug, factory
