### ISSUE TITLE
Missing support for importing things from ".egg" files in sys.path

### ISSUE THREAD

**Issue by pranavj** [Nuitka/Nuitka#89] opened 2018-05-22 09:14 UTC
*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
Nuitka 0.5.30
Python 2.7.12
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)
Platform Ubuntu Linux 

I installed Nuitka by downloading source tar and doing `python setup.py install`
I'm trying to convert py-webrtcvad module to C

Steps to test the issue

```
git clone https://github.com/wiseman/py-webrtcvad
cd py-webrtcvad/
python example.py
```
If you get any import errors, do `pip install webrtcvad`

You should see the output 

` Usage: example.py <aggressiveness> <path to wav file>`

Now, I try to convert example.py to C using following command

`python -m nuitka --show-progress --show-modules --standalone --portable  --recurse-all --python-version=2.7 example.py >& nuikta.build.log &`

The [build log is kept here](https://gist.github.com/pranavj/7c105717b9e7663699d7d9714128ef46) 

Main warnings from log are 

```
Nuitka:WARNING:/home/user/code/python/webrtc_vad/testing/py-webrtcvad/webrtcvad.py:3: Cannot find '_webrtcvad' as relative or absolute import.
Nuitka:WARNING:/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/appdirs.py:484: Cannot find 'com' in package 'pkg_resources._vendor' as relative or absolute import (tried pkg_resources._vendor.com,com).
Nuitka:WARNING:/usr/local/lib/python2.7/dist-packages/pkg_resources/_vendor/pyparsing.py:89: Cannot find 'ordereddict' in package 'pkg_resources._vendor' as relative or absolute import (tried pkg_resources._vendor.ordereddict,ordereddict).
```

Then, when I try to run examle.dist/example.exe I get following error
./example.exe
```
Traceback (most recent call last):
  File "/home/user/code/python/webrtc_vad/testing/py-webrtcvad/example.dist/example.py", line 6, in <module>
  File "/home/user/code/python/webrtc_vad/testing/py-webrtcvad/example.dist/webrtcvad.py", line 3, in <module webrtcvad>
ImportError: No module named _webrtcvad
```

How do I fix these WARNINGS and ERROR?

**Comment by kayhayen** [comment] 2018-05-22 13:15
Do not use "--python-version" with the "-m nuitka" style of invocation. Best case not needed, worst case destroy the effect. I am not sure if that messed things up for you.

**Comment by priyankakendrekar** [comment] 2018-05-22 13:28
@kayhayen Thanks for comment. I had run the command without --python-version argument before. It caused the same warnings.

**Comment by pranavj** [comment] 2018-05-22 13:30
@kaykayen Thanks for comment. I had run the command without --python-version argument, it had given same warnings.

**Comment by pranavj** [comment] 2018-05-23 00:17
Yes, 

`python -c "import _webrtcvad"`

works without any issues. I also tried to use `--include-package=webrtcvad` flag, but no improvement in warnings.

**Comment by kayhayen** [comment] 2018-05-23 09:11
Sorry for being stubborn to not try myself, usually these kinds of reports all have been invalid, but this one is likely not:

Following your instructions, I did NOT see the warning, after running pip without a virtualenv, so it probably installed in my home directory. Normally I do that with "sudo" even to the system, which may or may not make a difference.

But at run time, I am getting this:

pkg_resources.DistributionNotFound: The 'webrtcvad' distribution was not found and is required by the application

I did not get any error about the module and I see "_webrtcvad.so" in the dist folder. Maybe I am not even reproducing your issue then. I am doing this on Debian, your Ubuntu should be same absolutely, but I will investigate, and maybe there is odd things about pkg_resources to be seen.

The other two warnings will go away in the next release btw, as they are handled by Nuitka properly.

**Comment by kayhayen** [comment] 2018-05-26 09:45
I edited the subject as it suggests that Nuitka converts Python to C. It does not. The C code is not for use.

**Comment by kayhayen** [comment] 2018-05-26 09:50
So this is the minimal reproducer of what I am seeing:

```
import pkg_resources
pkg_resources.get_distribution('webrtcvad')
```

**Comment by kayhayen** [comment] 2018-05-26 09:55
I noticed, that I do have a pip installed pkg_resources. Might well be that you are not. In that case, some of the hacks Nuitka does for pkg_resources may not work with what you have. Can you obtain some kind of version information.

Yours,
Kay

**Comment by kayhayen** [comment] 2018-05-26 11:12
I am assuming the minimal import of `"import _webrtcvad"` failing for you, can you post the output of that compilation with --explain-imports option, it will allow me to check things. Also please determind the _webrtcvad.__file__ when using CPython with print.

**Comment by pranavj** [comment] 2018-05-28 03:38
> Might well be that you are not. In that case, some of the hacks Nuitka does for pkg_resources may not work with what you have. Can you obtain some kind of version information.

I didn't get you. Which command to use to find the version information? I provided pip version in OP.

>where does pkg_resources.__file__ point to for you? Into "/usr/local" ?

```
>>> print pkg_resources.__file__
/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.pyc
```

> can you post the output of that compilation with --explain-imports option

Ok, I have uploaded the compilation log with this option here https://gist.github.com/pranavj/a02ce61bdd03717ddcacaabdb8d0b900

> please determine the _webrtcvad.file when using CPython with print.

Sorry, didn't understand what to do.

**Comment by kayhayen** [comment] 2018-05-28 07:35
The log looks really good. I want to see, where normal CPython loads the _webrtcvad from, I think this code will do it, run it uncompiled:

```
import _webrtcvad
print(_webrtcvad.__file__)
```

Then I can compare that to what places Nuitka looks in your log. Also if you can, use "locate _webrtcvad" and check if there is something wrapping it.

Yours,
Kay

**Comment by pranavj** [comment] 2018-05-28 07:51
> I want to see, where normal CPython loads the _webrtcvad from


```
user$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import _webrtcvad
>>> print(_webrtcvad.__file__)
/home/user/.cache/Python-Eggs/webrtcvad-2.0.11.dev0-py2.7-linux-x86_64.egg-tmp/_webrtcvad.so
```

> Also if you can, use "locate _webrtcvad"

```
$ locate _webrtcvad
/home/user/.cache/Python-Eggs/webrtcvad-2.0.11.dev0-py2.7-linux-x86_64.egg-tmp/_webrtcvad.so
/home/user/code/python/webrtc_vad/testing/py-webrtcvad/test_webrtcvad.py
/home/user/code/python/webrtc_vad/webrtcvad-2.0.10/test_webrtcvad.py
/home/user/code/python/webrtc_vad/webrtcvad-2.0.10/build/lib.linux-i686-2.7/_webrtcvad.so
/usr/local/lib/python3.5/dist-packages/_webrtcvad.cpython-35m-x86_64-linux-gnu.so

```

**Comment by pranavj** [comment] 2018-05-28 09:39
>  Please attach your /usr/lib/python2.7/site.py any case.

https://gist.github.com/pranavj/407c6d73799e33c1b1cd1a83d2ebb900

`python "import sys;print(sys.path)"`

do you mean `python -c "import sys;print(sys.path)"`?

None of the three commands work on my machine. They all give "[Errno 2] No such file or directory" 

The output of 
`python -c "import sys;print(sys.path)"`

is

```
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old
', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/auditok-
0.1.6-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/regex-2017.7.28-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/nltk-3.2.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/swig_decoders-1.1-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/pip-9.0.3-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/webrtcvad-2.0.11.dev0-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/Nuitka-0.5.30-py2.7.egg', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0']
```

**Comment by pranavj** [comment] 2018-05-29 03:32
>  can you upload that this:
> 
> /usr/local/lib/python2.7/dist-packages/webrtcvad-2.0.11.dev0-py2.7-linux-x86_64.egg
It's uploaded here https://github.com/pranavj/filesharing/blob/master/webrtcvad-2.0.11.dev0-py2.7-linux-x86_64.egg

sys.meta_path is empty!

$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys; print(sys.meta_path)
[]
>>> print(sys.path)
['', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/local/lib/python2.7/dist-packages/auditok-0.1.6-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/six-1.10.0-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/regex-2017.7.28-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/nltk-3.2.4-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/swig_decoders-1.1-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/pip-9.0.3-py2.7.egg', '/usr/local/lib/python2.7/dist-packages/webrtcvad-2.0.11.dev0-py2.7-linux-x86_64.egg', '/usr/local/lib/python2.7/dist-packages/Nuitka-0.5.30-py2.7.egg', '/usr/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages/PILcompat', '/usr/lib/python2.7/dist-packages/gtk-2.0']

> Did you manually enter it to PYTHONPATH 
No, that variable is empty for me.

> Check with ls /usr/lib/python2.7/dist-packages/*.pth
No, none of the pth files are related to webrtcvad
```
$ ls /usr/lib/python2.7/dist-packages/*.pth
/usr/lib/python2.7/dist-packages/PILcompat.pth               /usr/lib/python2.7/dist-packages/pygtk.pth
/usr/lib/python2.7/dist-packages/matplotlib-1.5.1-nspkg.pth  /usr/lib/python2.7/dist-packages/zope.interface-4.1.3-nspkg.pth

```

**Comment by kayhayen** [comment] 2018-05-29 08:16
There we go, egg files are zip files:

>  Length      Date    Time    Name
> ---------  ---------- -----   ----
>       536  2018-05-22 09:49   _webrtcvad.pyc
>      1709  2018-05-22 09:49   webrtcvad.pyc
>       976  2018-05-11 15:42   webrtcvad.py
>       286  2018-05-22 09:49   _webrtcvad.py
>     163080  2018-05-22 09:49   _webrtcvad.so
>        21  2018-05-22 09:49   EGG-INFO/top_level.txt
>      2055  2018-05-22 09:49   EGG-INFO/SOURCES.txt
>         1  2018-05-22 09:49   EGG-INFO/dependency_links.txt
>        14  2018-05-22 09:49   EGG-INFO/native_libs.txt
>         1  2018-05-22 09:49   EGG-INFO/zip-safe
>      3739  2018-05-22 09:49   EGG-INFO/PKG-INFO
>        74  2018-05-22 09:49   EGG-INFO/requires.txt

This is probably dealt with zipimporter, which might cache things in ".cache", where you will then find it. In Nuitka there currently is nothing to support it, but it seems feasible to add.

These eggs are likely out of fashion, precisely because they require each user to privately extract on the fly. To check if an update is needed, some processing of the zip file will be needed each time, for every program you run, and that does an import not satisfied by earlier elements of the path. That will make your Python only slower.

So, no trick there inside the zip luckily. Please allow for some time to implement this. At least I now have an .egg file to test with. Hopefully it's as easy as to ask zipimporter to do its thing. But could also be that it's not possible to decouple searching from actual importing, then I get to implement the caching part myself. Ideally the cache hit is the normal case, and then it's only about replacing the egg with a cache directory, and maybe complain if it's not cached yet. Nuitka may not have to be the first to unpack an egg into a cache. But that is speculation, need to check what is there fore use.

Yours,
Kay

**Comment by pranavj** [comment] 2018-06-15 09:00
Hi, any update?

**Comment by kayhayen** [comment] 2018-09-22 08:34
So I just pushed this to factory. However, in your example there is also something that causes an error, and has been reported elsewhere. The pkg_resources is used to require "webrtcvad" and cannot find it in standalone mode. This is a separate issue. Egg files work now at least. 

It will be in 0.6.0 release that I hope to make this weekend.

I am now turning towards the "pkg_resources" issue with your egg, because so far I only had un-reproducible (for me) reports, so this is actually very nice and small reproducer your egg.

**Comment by kayhayen** [comment] 2018-09-23 04:52
So this is in the new pre-release now, closing now as release is immanent and not hotfixes will happen for 0.5.33 anymore.

For the pkg_resources issue I create #146 which seems possible, but will also not immediately be dealt with.

**Closed by kayhayen** 2018-09-23 04:52 UTC
Labels: bug, factory
