### ISSUE TITLE
Use Github actions for Windows and macOS CI

### ISSUE THREAD

**Issue by jayvdb** [Nuitka/Nuitka#551] opened 2019-10-11 18:28 UTC
Has there been an attempt to add Windows CI?

Travis CI for Windows is quite good, and there is a reasonable support base able to help at https://travis-ci.community/c/environments/windows

I was able to make it almost like AppVeyor for the coala-bears CI; see e.g. Windows icon on https://travis-ci.org/coala/coala-bears/builds/581997859 for a 30min job setting up lots of chocolatey packages.

Azure also has Linux, macOS and Windows , so switching to that is also an option.

**Comment by jayvdb** [comment] 2019-10-16 09:12
ping @kayhayen , do you have any preference for how I proceed with this?

**Comment by kayhayen** [comment] 2019-10-16 09:24
Sorry for the late reply, @jayvdb things are busy for me privately. However, I have lots of response to this, and didn't take the time yet.

I had started to use AppVeyor for Nuitka, but noticed early on, they were not giving too many cycles to build jobs. However, their offering is of course attractive. What I preferred Travis for is deep integration with Github that was fully automatic. I never got that to work with AppVeyor, which is why I recently disabled that one job I had, where it produces the MSI files. I am not even sure, how useful those even are, and I never managed to automate the download of the MSI artifacts from the webhooks.

Basically all lack of time. We have a Linux only public CI of our own, nightshift.nuitka.net, that has fallen into disrepair, since Buildbot failed to work with Apache and only Nginx, but that works less well with the SSL certificate renewal. I will turn to that this weekend I hope. There we can burn as many cycles as we want. But it's ugly since it's not automatically adding branches, i.e. PRs do not get built. But for many, that is also far from needed to run the whole suite of compilations.

If you want to take this on, very well. I also mean to invite you to the Nuitka organisation, if you are interested, which I hope. Esp. if you are interested in that 3.8 work with test suites, and other stuff, you are more than welcome.

Again sorry for the late reply.

Yours,
Kay

**Comment by jayvdb** [comment] 2019-10-16 12:09
Ok, I'll make a start on Travis CI, and let you know how I go.
I have had fairly deep integration with AppVeyor, including artifacts.
AppVeyor provides more variation of Windows environments - different images, but I havent used the non-default ones much.

We can have both operational in order to spread the load, if needed.

Yes I am interested in joining the org.

**Comment by kayhayen** [comment] 2019-10-17 08:45
Feel free to have your own branch in the central repository. That way I will see it easier. I added you to the pushers as part of the invite.

I indeed had very good experience with AppVeyor, but I didn't use the `.yml` file in their instance, that's actually pretty annoying to try out things that way, isn't it. But it also is the only way to share stuff. 

They have VMs with all Python's installed, etc. and it seems even WSL was added recently. I think AppVeyour still has access to Nuitka, if you want to go there as well. I think starting with Travis is a good idea. I can lookup what is still on AppVeyor, I might have deleted it 2 months ago though, when it failed to build MSIs and I noticed it still existed and only wasted energy.

**Comment by brendanator** [comment] 2019-10-23 20:34
I recommend using Github actions for this (which should be available for everyone sometime in November, or you can sign up to get early access)

1. Deep integration with GitHub, obviously
2. Has Windows, Mac and Linux VMs

We've created a build for our project that runs on all OSes and it's been fantastic. Here's a slimmed down example that would belong in `.github/workflows/test_nuitka.yml`

```yml
name: Nuitka tests

on:
  pull_request: {}
  push:
    branches: master
    tags: '*'

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Python 3.7.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.4

    - name: Install dependencies
      run: |
        pip install nuitka

    - name: Build with nuitka
      run: python -m nuitka

    - name: Run tests
      run: ...

  mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1

    - name: Install Python 3.7.4 using Conda
      run: |
        sudo chown -R $USER $CONDA
        $CONDA/bin/conda install python=3.7.4

    - name: Install dependencies
      run: |
        pip install nuitka

    - name: Build with nuitka
      run: python -m nuitka

    - name: Run tests
      run: ...

  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1

    - name: Use Python 3.7.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.7.4

    - name: Install MinGW using Conda
      shell: bash
      run: $CONDA/Scripts/conda install m2w64-gcc libpython

    - name: Install dependencies with pipenv
      shell: bash
      run: |
        pip install nuitka

    - name: Build with nuitka
      shell: bash
      run: CC=$CONDA/Library/mingw-w64/bin/gcc.exe pipenv run build

    - name: Run tests
      shell: bash
      run: ...
```

**Comment by kayhayen** [comment] 2019-12-28 08:53
@jayvdb @brendanator any news on this, I really would want to use Github actions, is there anything I need to do to enable it?

**Comment by brendanator** [comment] 2019-12-30 11:27
@kayhayen All you need to do to enable it is create a `.yml` file in the `.github/workflows/` directory. The template that I've included above runs 3 jobs on each os and installs the dependencies. You just need to fill in the `...`s with whatever you want to run.

The property `on` which is at the top means that the jobs will be run on each PR, commit to master and tag.

Here's the main docs: https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions

**Comment by kayhayen** [comment] 2020-01-01 18:51
Since macOS is currently broken, I will give it a shot myself now.

All public CI is limited in what it can do for us. Nuitka wants too much CPU to be tested, that is for sure, but the basics, they should be covered reliably. These public CIs are going to better integrated on any given day.

**Comment by kayhayen** [comment] 2020-01-06 07:26
I managed to get things up and running for only Python 3.7, and on factory branch right now. I need to figure out the matrix next up.

The use of Anaconda on macOS doesn't fit into setup-python, so it's more manual. Also there was a problem executing the installed scons from Nuitka, which I think i will react to by making the inline copy of scons the default. It has optimizations for faster startup and often is newer than installed stuff anyway, and means better control over what is actually going on. I think the PYTHONHOME, PYTHONPATH is wrong for scons, but that worry should go away. Nuitka deletes those variables when it executes scons, hoping for them to not be necessary, as they often proved to be counter productive. But there is no right or wrong here.

For Windows, I had to whitelist a few paths from PATH, which precede system DLLs, but that wasn't so big.

For Linux, all went relatively smooth. 

So this is poised to remove the need for Travis almost entirely. It seems more flexible, and I might figure out how to actually use secrets. With that happening, I might be able to move release jobs from my private CI to this public one, which will be great. Maybe Travis was/is also capable of that, maybe I won't do it immediately, but e.g. putting the MSI build and deployment or OBS upload on Github actions seems like a relief, and it allows for others to enhance on it.

That way, my private CI can focus on CPU heavy stuff. I doubt we can run massive test suites on Github actions, but this looks very promising as it stands. The final switch is probably something I will do, once I got working cron jobs on Nuitka master too.

But first the matrix, and maybe in a way that it uses variables so the macOS which needs to give the concrete binary version to use, `python3.7` rather than just `python` will work fine. Before adding 3.8, I need to fixup a missing 3.8 feature still.

I hope to resolve this issue over the week.

**Comment by kayhayen** [comment] 2020-01-06 07:30
Ah, for Windows, the --assume-yes-for-downloads needed to be added to the main test runner, so it can forward it, to download `depends.exe`.

Which reminds me that we ought to make sure we got good caching going on for this one as well, because it would be a shame to not preserve the `ccache` or the `nuitka` cache files for CPython outputs here too.

**Comment by kayhayen** [comment] 2020-01-06 08:26
So, the inline scons is now the default, and on Windows, we use short filenames for robustness. This should avoid regressions with unicode paths like we had issues with in the past.

**Comment by kayhayen** [comment] 2020-01-14 14:00
Windows and macOS CI are operational. I think I need to do something to make it work on normal PRs too. But I will close this is it's solved.

**Closed by kayhayen** 2020-01-14 14:00 UTC
Labels: enhancement
