### ISSUE TITLE
Scons: Filename or extension is too long

### ISSUE THREAD

**Issue by peterjoo** [Nuitka/Nuitka#267] opened 2019-02-20 14:38 UTC
I'm constantly failing to produce a standalone .exe and it kicks out with the message:
 'Filename or extension is too long'
I'm completely lost at this point as I've exhausted all the options I know. I've shorted the filename. Uninstalled and reinstalled Anaconda3 (this is how I got python). Moved the program closer to the root at c:\main. None resolved the issue.

I'm using Win10, Anaconda3, Spyder, nuitka 062. Installed nuitka using MSI. 

Ran nuitka from the Anaconda Prompt:
python -m nuitka --standalone --show-progress --mingw64 1_nuitka.py

**Comment by kayhayen** [comment] 2019-02-20 14:46
This is a scons issue, that I am helpless about too. It would be great if anybody with Windows debugging skills would attach some form of tracing to Scons which will even tell us what filename it is talking about.

In my mind, it's not too strange. It should only see filenames from your `1_nuitka.build` directory, and ought to use relative paths.

**Comment by michaeljamesdavies** [comment] 2019-02-22 22:31
I too have the same issue. In addition to all your steps (I used 'C;\t\' as my project directory) I enabled filepaths longer than 260 using regedit ( https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/ ). 

This did not work.

I checked the build directory and all the gcc cmd line and the longest filepath is 

'main_gui.build\\module.scipy.optimize._trustregion_constr.minimize_trustregion_constr.o'

Which is 86 characters long. And its just  C;\t\ before that in the full path. So less than 100 characters in total length.

I have noticed that the gcc cmd line call is very long. In fact it is 126k characters long for my full project. I will start to shrink it down. Nuitka runs fine when I run it on smaller projects with different permutations of the same libraries being imported (I have not robustly tested this though it is just the pattern I have seen). 

 I ran everything on Powershell (less line length constraints) in addition cmd.exe and they get the same error message
     'scons: *** [main_gui.dist\main_gui.exe] The filename or extension is too long'. 

I use Anaconda64 and MinGW64 in all cases. I also did it with and without clcache though that shouldn't matter and didn't.

I have noticed on Google that in other projects where 'scons ***: The filename or extension is too long' is coming up everyone seems to be using MinGW. Then some discussion with issues regarding issues with MinGW and scons came up:

Interesting parts from:  https://github.com/SCons/scons/wiki/LongCmdLinesOnWin32

1.) "MingW had some problems during the link phase of the build process. It turned out our link lines were in excess of 10000 characters, and this was causing some major grief with python calling spawn().
After some investigation, it turns out this is not a limitation of Windows, but a limitation of the C Runtime that MSVC uses (which Python was compiled with). "

2.) "The maximum command line length that you can pass to CreateProcess is 32766. Past that limit you get an error msg saying 'parameter incorrect' (but not which parameter and not why is it incorrect). You still need the TempFileMunge trick to deal with lines longer than that."

I will test the Visual Studio 2017 compiler and see if they work and report back here.

I hope some of what I've written is of use. I am new to Windows and scons but might attempt to learn the debuggers.

**Comment by kayhayen** [comment] 2019-02-23 09:58
We did something for `mslink` which I think gets the list of files from an input file anyway. There we have trouble with space separated arguments, and had to put new lines instead, so the MSVC parser doesn't hit line length limits.

Put all of `gcc` object file names on the command line seems wrong. We probably just need to hack the linker invocation to go through a file too.

**Comment by kayhayen** [comment] 2019-02-23 09:59
What's curious for me is that I never had a reproducer for this so far. But I guess, it's not needed, just should do this all the time.

**Comment by kayhayen** [comment] 2019-02-23 10:56
My google- and my `--help` fu" are letting me down right now. I think linker scripts are not what we are talking about here, are they.

**Comment by kayhayen** [comment] 2019-02-23 11:08
Stupid me:

`  @FILE                       Read options from FILE`

So `-Wl,@filename` may all the have to add to the gcc command line right there. 

Any takers? I would appreciate a PR that tries to hack Scons inline copies for Nuitka? One would probably be enough, 3.0.4 if you use Python3, the other if you use Python 2.7, and I would cross port it myself. Currently I have no clue where that command line is even coming from. I think it's not `mingw.py` but it also seemed not to be `cc.py`, some digging would be required.

Yours,
Kay

**Comment by michaeljamesdavies** [comment] 2019-02-23 14:22
Quick update: I ran it on MSVC (2017) and got the same error but with a little more information:

    scons: warning: MSVC_USE_SCRIPT set to False, assuming environment set correctly.
    File "C:\Users\44793\Anaconda3\lib\site-packages\nuitka\build\SingleExe.scons", line 462, in createEnvironment
    scons: *** [main_gui.dist\main_gui.exe] The filename or extension is too long

I am just about to head out.  I will attempt to 'import pdb; pdb.set_trace()' around there when I get back. I haven't fully understood your comments yet either so sorry if I haven't addressed anything I should have yet.

-------------
Note on my installation of Visual Studio 2017 to get MSCV compiler. nuitka successfully built a small project using msvc after following these steps.
1. When installing, in addition to default C++ build tools, I followed advice of others and checked boxes for 
- Windows XP support for C++
- Support for C++/CLI
- VC++ 2015.3 v140 toolset
2. Run cmd/Powershell as admin then run this script to set environment variables 
      C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat
3. create include environment variable
      set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt\
4. set cc to cl.exe.
      set CC=C:\msvc\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86\cl.exe

**Comment by kayhayen** [comment] 2019-02-25 10:37
Actually Nuitka should be able to pick up 2017 without you doing anything, so the last 3 steps should be unnecessary. Simply installing MSVC should be enough, and shamefully it ought to be the simplest way of getting a working compiler except maybe AnaConda with conda-cc.

As for steps 1, I think I didn't add Windows XP support, nor 2015 toolset, I don't think either should be necessary, unless of course you build on Windows XP, which I think is not working for sure.

**Comment by kayhayen** [comment] 2019-02-28 07:21
So it seems that #279 found the very same thing even on Linux, probably with an even larger code base to compile. We have a scalability issue here.

This should be easy to find, any takers? I described how to do it on Linux in the other issue that I closed as a duplicate.

**Comment by kayhayen** [comment] 2019-04-12 13:01
Well, on closer reading, I am not longer convinced this is actually different from #279 since the original report was for MinGW64, then MSVC was called into doubt, but ultimately turned out working, which it is due to code that we have added (using `\n` as a separator over ` `).

So I guess, I am now closing this one, and making it a duplicate, if only because the other issue is cleaner. I expect over the weekend to make this land on factory branch at least.

**Closed by kayhayen** 2019-04-12 13:01 UTC
Labels: bug, duplicate
