### ISSUE TITLE
Not supported: The Cygwin, TDM, MinGW compiler, help to change that or use MinGW64 with 32/64 bits.

### ISSUE THREAD

**Issue by wolfamongus2** [Nuitka/Nuitka#35] opened 2017-10-30 07:24 UTC
*UPDATE*./  Can you guys PLEASE state that you do not support 3.6.  I've spent half the day only to realise you guys do not support it yet state you do on your website.

C:\Users\Bain3>Nuitka --exe 123.py
Nuitka:WARNING:Not recursing to 'selenium' (C:\Users\Bain3\Anaconda3\Lib\site-packages\selenium), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=selenium (ignore it), --recurse-to=selenium (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'selenium.webdriver.support.ui' (C:\Users\Bain3\Anaconda3\Lib\site-packages\selenium\webdriver\support\ui.py), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=selenium.webdriver.support.ui (ignore it), --recurse-to=selenium.webdriver.support.ui (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'selenium.webdriver.support' (C:\Users\Bain3\Anaconda3\Lib\site-packages\selenium\webdriver\support), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=selenium.webdriver.support (ignore it), --recurse-to=selenium.webdriver.support (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'selenium.webdriver.common.by' (C:\Users\Bain3\Anaconda3\Lib\site-packages\selenium\webdriver\common\by.py), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=selenium.webdriver.common.by (ignore it), --recurse-to=selenium.webdriver.common.by (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'requests' (C:\Users\Bain3\Anaconda3\Lib\site-packages\requests), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=requests (ignore it), --recurse-to=requests (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'selenium.common.exceptions' (C:\Users\Bain3\Anaconda3\Lib\site-packages\selenium\common\exceptions.py), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=selenium.common.exceptions (ignore it), --recurse-to=selenium.common.exceptions (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'retrying' (C:\Users\Bain3\Anaconda3\Lib\site-packages\retrying.py), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=retrying (ignore it), --recurse-to=retrying (recurse to it) to change.
Error, cannot find "gendef.exe" which is required though.

**Comment by ThomasLecocq** [comment] 2017-10-31 08:18
The current develop version is working fine with Python 3.6 on win10. The only thing is to try to manage to install gendef.exe.

**Comment by Haydeman** [comment] 2017-10-31 10:07
By Gendef.exe you mean Mingw?  Could you provide the direct links for download or  maybe a more in depth tutorial?  I spent the whole day trying to get this work yesterday.  To my knowledge I have Mingw installed.  I tried Pyinstaller which worked great.  Just add cython and you're app is good as gold.  I also reinstalled it on laptop and a virtual machine and had major issues getting it to recognise visual studio, mingw which were installed when using Nuitka.  I believe someone had same issue years ago but I resolved it with Pyinstaller + cython.  A damn shame I couldn't get this working but still a viable workaround if others have this issue.  Of course, maybe they can get Nuitka to recognise Mingw and Visual Studio but good luck with that one!   There is a bit more documentation with Cython too.

**Comment by ThomasLecocq** [comment] 2017-10-31 10:59
My case: install is:

- Windows 10
- Anaconda Python 3.6 
- TDM-GCC-64
- Visual Studio Build Tools 2017
- Nuitka from github source (pip installed)

gendef.exe downloaded from a probably not so safe location ([here](https://www.pconlife.com/viewfileinfo/gendef-exe)) and added to the tdmgcc/bin folder.

And it works fine.

**Comment by ThomasLecocq** [comment] 2017-10-31 11:06
Well, ... 

I'm just not using mingw64 ... the rest, obviously, looks like windows to me...

**Comment by Haydeman** [comment] 2017-10-31 11:09
Very well.  So GCC http://tdm-gcc.tdragon.net/download as well as https://sourceforge.net/projects/mingw/files/MinGW/Extension/gendef/gendef-1.0.1346/gendef-1.0.1346-1-mingw32.RELEASE_NOTES/download  . I'm not even sure I have a tdmgcc/bin folder.  The first link is an executable so should be no problem.  The gendef I cannot find that folder.  I assumed downloading mingw that it installed the gendef automatically...

**Comment by Haydeman** [comment] 2017-10-31 11:21
re-tested same issue.  Pyinstaller + cython is a viable workaround for others who have this issue

**Comment by ThomasLecocq** [comment] 2017-10-31 11:38
As usual, ... "please provide a reproducible example" would be a good suggestion.

And, about the tdmgcc/bin, that's what I meant: ``C:\TDM-GCC-64\bin`` it's where you actually install the TDM....

**Comment by Haydeman** [comment] 2017-10-31 13:39
Thanks but I've done all of that.  Mark as resolves as it was resolved with Cython and Pyinstaller. I appreciate the help but it just does not work for me :)

**Comment by ThomasLecocq** [comment] 2017-10-31 13:42
Wow... For what I can tell (and I'm not a nuitka dev, just "another dev"), I don't appreciate your help in making the package better. No reproducible example, no details. Just an "it doesn't work, so I used something else". How rude.

**Comment by Haydeman** [comment] 2017-10-31 13:49
It is resolved.  I also don't like someone attacking me for stating what I found helpful.   I used Cython + pyinstaller.  I'm not trying to be rude I'm trying to be sensible.  I spent one whole day trying to get it work.  I poured over stackoverflow questions and found another with the same question unresolved.  I have other stuff to get done and might look into this when I have time but sadly, I do not right now.  I don't want the stress of futility getting this app to work when it just does not want to run on any windows pc.  I have tried REinstalling pc 3 seperate times.  I think that the concept is great and I hope others can use it but its just not user friendly enough for me.  I like a quick install, a command that works.  Pyinstaller + Cython do this for me.  I am sorry I offended you but I hope you can use this as feedback so that you can make it more detailed so others do not get frustrated and just use a program that works for them.  Also the errors speak for themselves.  I don't know how much more detailed I can be.  Also, I don't get how it is rude do go with a program that works.  This works for some but not for me.

**Comment by ThomasLecocq** [comment] 2017-10-31 13:55
Anyway, thanks again for your feedback on that matter, it really will help nuitka devs make the project better.

**Comment by kayhayen** [comment] 2017-10-31 14:00
@ThomasLecocq If you want to use TDM, you have work in front of yourself, it's not supported. The gendef.exe is part of MinGW and used to generate an import library to use the PythonXY.DLL 

@Haydeman The Python 3.6 is fully supported and I think it says so on the web site.

@Haydeman Please get "other stuff" done. I am sure you can contribute elsewhere even more.

BTW: This issue is a perfect example of why using the Github issue tracker is generally a bad idea. It's too easy to report and people are quick to start fights that gain nothing.

If someone were so productive as to provide the output of --show-scons and potentially others as I request, I might add a warning about using TDM. As it stands, specifically standalone mode is very demanding about the C runtime, standalone for other GCC variants might not even be feasible. I clearly am not interested in doing it myself.

@ThomasLecocq I put this on needs_volunteer, you are welcome to try and figure out, if gendef.exe is needed with TDM in the first place, and how to support it. Ought to be fiddling mostly. And maybe the shell APIs do not work as needed. If you work on that and get stuck, I might decide to help. Otherwise I am out of this issue.

**Comment by ThomasLecocq** [comment] 2017-10-31 14:05
@kayhayen TDM was just installed and working for me, only reason I advertised for it. I should definitively switch to MINGW (mingw64?). 

The OP didn't use TDM, but mingw, it seems. But the OP didn't provide much details, at all. So no, the title shouldn't be changed to TDM-related AFAIK.

One option for avoiding that github issue tracker frenzy is to use github templates for issues, as done for  obspy for example: https://github.com/obspy/obspy/issues/new

You can close the issue, TDM works for me but I'll follow your advice and switch to mingw !

Cheers from Brussels,

**Comment by kayhayen** [comment] 2017-11-01 20:39
@ThomasLecocq The MinGW and MinGW64 are two different beasts. One is supported, the other is not. I put a prominent note in the user manual about it. But who reads that anyway.

@ThomasLecocq I don't mind using TDM if it works. I do know that Cygwin does not. And surely you can imagine that I can for the life of it not be bothered to make every Windows compiler work and bother with its shortcomings.

@ThomasLecocq I will definitely look into that template issue. It's a good point to bring up typical issues, like e.g. using MinGW over MinGW64. However I would prefer for Nuitka to be able to detect all those, and warn/error about not supporting it directly.

**Comment by ThomasLecocq** [comment] 2017-11-02 07:43
@kayhayen hehe, yep, I actually read it :) but you know, memory... :-) So yep, I have MINGW64 now and it works fine for my --module case. I tried a simple --standalone, all OK (as with my TDM-GCC+gendef install before, but seems faster). Then a very complex one (including obspy == lots of dependencies (matplotlib, scipy, etc), that fails. Now time to read the doc and understand more what's under the hood and how to debug properly.

**Comment by kayhayen** [comment] 2021-12-15 19:06
I am in fact so happy with MinGW64 and winlibs, I won't consider the other C compiler variants of gcc on Windows to be worth the effort.

**Closed by kayhayen** 2021-12-15 19:06 UTC
Labels: help wanted, unsupported

**Comment by ThomasLecocq** [comment] 2021-12-16 07:47
eheh, someone's cleaning old issues here :-) 👍

**Comment by kayhayen** [comment] 2021-12-16 12:05
It was in fact kept open on purpose, as a landing spot for people that would want to add support for Cygwin or TDM, however, since now LTO is supported on Windows with gcc from MinGW64, and the integration with the automatic download is so easy with winlibs, I am letting go of this idea forever.
