### ISSUE TITLE
Asyncio tasks still active after cancellation causing memory leak

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#588] opened 2019-12-15 15:14 UTC
I am having a new issue with asyncio tasks and exceptions on Nuitka 0.6.5 (reproduced with Python 3.6.9 and 3.7.5 on Docker containers). When using websockets module (version >=8.0) and my reader task is cancelled, there are 3 websockets tasks that are correctly finished or cancelled but they are still present in the `asyncio.Task.all_tasks()` even if `gc.collect()` is run manually. The issue only occurs when the code is compiled with nuitka, not with native python.

A full reproducer is available at https://github.com/levesquejf/nuitka-websockets-bug.

**Comment by levesquejf** [comment] 2019-12-21 21:24
The memory leak explained in #593 is also present in this issue. The reproducer has been updated to print the memory usage. The number of object is increasing by 1852 when run with Nuitka compared to 351 with native Python.

**Comment by levesquejf** [comment] 2020-04-21 12:57
@kayhayen The current factory build fixes the tasks being leaked as done or cancelled. However, there are 362 more objects after the nuitka run compared to the native run with 356 objects.

**Comment by kayhayen** [comment] 2020-04-22 07:26
We would have to look at their types. I believe the Nuitka related bugs should all be gone for coroutines (I still need to port fixes to asyncgen, this is ongoing) . 

Can you try out Python3.8 as I suggested, @levesquejf ? In my mind, `asyncio` is leaking at least references, not sure about memory. I will update my example with Nuitka's to measure memory consumption, and then make a comparison.

In the asyncio code, there are various attempts to break reference cycles as I have seen. Seems that until 3.8 they fail badly. But it could also be relative harmless, therefore the measurement. In my example, the leaks were smaller. But I also modified relativ to your code, to not use local functions, which makes me thing, a frame might be involved in the leak, which automatically made it bad.

I will also revisit your original examples myself once I have the time.

**Comment by levesquejf** [comment] 2020-04-22 11:01
With Python 3.8.2:

Native: No more objects
Nuitka Factory: 6

**Comment by kayhayen** [comment] 2020-04-22 11:05
Ok, I will research that. Thanks for the report.

**Comment by kayhayen** [comment] 2020-04-23 12:47
I managed to reproduce a remaining issue with adding this to my reference checker, and it leaks a single reference. Using the `print()` in the reader function made CPython 3.8.1 leak two references, which is strange.  For the record, this is what I am using now.

```
import websockets

from concurrent.futures import CancelledError


async def hello(text):
    uri = "wss://echo.websocket.org"
    async with websockets.connect(uri) as ws:

        reader_task = asyncio.ensure_future(reader(ws))
        writer_task = asyncio.ensure_future(writer(ws, text))
        await asyncio.wait(
            [reader_task, writer_task], return_when=asyncio.FIRST_COMPLETED,
        )

        for task in (reader_task, writer_task):
            if not task.done():
                task.cancel()
            try:
                await task
            except CancelledError:
                pass


async def reader(ws):
    while True:
        r = await ws.recv()


async def writer(ws, text):
    await ws.send(text)
    await asyncio.sleep(0.5)


async def run11():
    await hello(f"Test")

    for i in range(0, 20):
        await hello(f"Test {i}")


def simpleFunction11():
    loop = asyncio.get_event_loop()
    try:
        loop.run_until_complete(run11())
    except asyncio.exceptions.CancelledError:
        pass
```

**Comment by kayhayen** [comment] 2020-04-23 12:50
Since my reference count checker allows for warm up (often caching e.g. of frames, exceptions prepared, etc.) causes a first run to hold references even after the fact. My reference count checker therefore re-tries and waits for things to stabilize in a few rounds. And if that doesn't happen, the difference is reported. I believe I need to make some sort of interface that will allow this to be used on arbitrary module and function in it.

**Comment by kayhayen** [comment] 2020-04-23 12:52
Also, avoiding `print` matches my recollection of it leaking references and being bad for these kinds of tests.

**Comment by kayhayen** [comment] 2020-04-25 10:35
Taking a cue from the example code, I not only created a tool that is supposed to allow running unchanged test cases, but also imported the trick to avoid `sys.getotalrefcount` and therefore the need to use debug Python versions. That will be good for CI where it's not available, or e.g. for Windows and older Python versions.

However, I am confused now, first of all, the reference count leak that I was observing is now reported as gone by the tool. It could well be that there is something in the way the test case got changed and I will check your unmodified test case soon.

However, I am detracted by something strange. There is one test function, that is failing with the non-debug Python, and only there, and I didn't quite make out how it happens yet. There is a leak reported for CPython and Nuitka both, that when actually looking at the objects, does not manifest.

This is for CPython3.4 e.g:

> -simpleFunction77: FAILED 9159 9160 leaked 1
> +simpleFunction77: FAILED 9912 9913 leaked 1
>  REPORT of differences:

```
def simpleFunction77():
    class weirdstr(str):
        def __getitem__(self, index):
            return weirdstr(str.__getitem__(self, index))

    weirdstr("1234")
    # filter(lambda x: x >= "33", weirdstr("1234"))
```

The filter usage was disabled many years ago, because that was found to be leaking for CPython itself. So what remains is the weird string. I guess, the issue is here, that it inherits from a `str` and maybe that then would not work well with the `str` I am doing to key objects, but I would be pretty sure such instance gets deleted. So this is a weirdness that I am not understanding right now and what's worse, is that with the debug Python it doesn't happen. So maybe a weird (pun intended) CPython bug of some sorts. 

The overloading of `__getitem__` is not it, happens with this renamed as well.

**Comment by kayhayen** [comment] 2020-04-25 10:54
Ah yes, long time ago:

I reported this against Python2.6 already:
https://bugs.python.org/issue9366

If my memory serves well, turns out that new style classes were reference leaking, therefore the tests shared for Python2 are careful to avoid them as local declarations. It seems that they fixed one case, but not another, because inheriting from `object` locally started to work at one point, but from `str` does not (anymore).

And then there is also: 
https://bugs.python.org/issue9417

That seems to indicate that the problem exists in 3.5 or higher. I would say, I my testing confirms 3.4 or higher. Why it's not observed with the debug Python I don't know, but that explains that part of my confusion.

Obviously that's something to keep in mind. Leaking classes is not a good idea.

**Comment by kayhayen** [comment] 2020-04-25 13:10
So, when I use my reference count checker tool, on the original code, with only objdump usage commented out, I see this:

> /c/Python38_64/python bin/check-reference-counts MiniCoroutineLeak2.py
> Using <function main at 0x00000291D405EF70>
> main: PASSED
> Using <compiled_function main at 0x00000291D40AC040>
> main: PASSED

I think, in the algorithm for reference counting, used in your example, you miss out on `obj_start`  from the loop. The second call to `gc.collect()` may therefore have a new integer object, that was not there before.

Makes me realize, that `gc.get_objects` checks only for object presence, and not about leaking a reference, to say `None` or small integers, and that it really should give inferior results therefore, and building a replacement wouldn't be so easy, because a sum will change the result potentially, which could be worked around by e.g. using a float value, and ignoring floats, then switching to a long, and ignoring everything but floats.

But with the debug version, same result:

> /c/Python38_64/python_d bin/check-reference-counts MiniCoroutineLeak2.py
> Using <function main at 0x0000021CFCB8AD70>
> main: PASSED
> Using <compiled_function main at 0x0000021CFCBD0050>
> main: PASSED

**Comment by kayhayen** [comment] 2020-05-01 10:10
This is now in the latest pre-release, and will soon be released.

**Comment by kayhayen** [comment] 2020-05-11 15:01
The release 0.6.8 was just made and contains the correction.

**Closed by kayhayen** 2020-05-11 15:01 UTC
Labels: bug
