### ISSUE TITLE
ImportError: cannot import name 'DataFrame' from 'pandas'

### ISSUE THREAD

**Issue by lexxish** [Nuitka/Nuitka#615] opened 2020-01-31 21:53 UTC
At execution time my exe fails on `from pandas import DataFrame`. I can build and run a hello world example.

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

0.6.7
Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\lexxish\AppData\Local\Programs\Python\Python37\python3.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

Installed via pip3

**Comment by gabrieldp** [comment] 2020-02-02 12:54
This may have something to do with the recently released Pandas 1.0.0.
I managed to compile a script which used numpy and matplotlib (two plugins which are used by pandas), but failed when I imported pandas itself (version 1.0.0). Then I downgraded to pandas 0.25, which compiled correctly.

What is your version of pandas? Check by running the following:
```
import pandas as pd
print(pd.__version__)
```

**Comment by lexxish** [comment] 2020-02-03 06:04
> This may have something to do with the recently released Pandas 1.0.0.
> I managed to compile a script which used numpy and matplotlib (two plugins which are used by pandas), but failed when I imported pandas itself (version 1.0.0). Then I downgraded to pandas 0.25, which compiled correctly.
> 
> What is your version of pandas? Check by running the following:
> 
> ```
> import pandas as pd
> print(pd.__version__)
> ```

Thank you for the suggestion. I was using pandas 1.0 and I tried with pandas 0.25.2, but same error. Any other ideas?

**Comment by kayhayen** [comment] 2020-02-03 07:18
Can you try and make a minimal reproducer, so we can look at it? I don't want to spend time guessing what it takes.

**Comment by lexxish** [comment] 2020-02-03 08:03
> Can you try and make a minimal reproducer, so we can look at it? I don't want to spend time guessing what it takes.

I tried running `python3 -m nuitka --follow-imports --show-progress --enable-plugin=numpy test.py` on
`from pandas import DataFrame
df = DataFrame({})`

And got:
`File "C:\Users\lexxish\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\__init__.py", line 34, in <module pandas>
    raise ImportError(
ImportError: C extension: 'hashtable' from 'pandas._libs' (C:\Users\lexxish\AppData\Local\Programs\Python\Python37\lib\site-packages\pandas\_libs\__init__.py) not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.`

I don't even have a setup.py - just a script. Do I need one?

**Comment by kayhayen** [comment] 2020-02-03 08:27
No. That is probably another big that nuitka is affected by without hinted compilation. I will look into it later today

**Comment by kayhayen** [comment] 2020-02-03 19:03
I believe this might be a duplicate of #616 which is a much better report.

**Comment by lexxish** [comment] 2020-02-05 23:33
I'm not sure if it is the exact same issue or not. But I realized that Nuitka doesn't seem to be able to package an exe to run on another computer which I need for my use case. Is that correct? https://github.com/Nuitka/Nuitka/issues/230

**Comment by JorjMcKie** [comment] 2020-02-06 06:13
@lexxish - the trouble exists with the pandas 1.x version. You should be fine with the previous one: I have been successful using pandas 0.25.x.

I am currently trying to find a way compiling pandas 1.0.0 scripts, which is unfortunately not as easy as I had hoped.

**Comment by lexxish** [comment] 2020-02-06 06:49
Are you saying I would need to distribute a folder with multiple files to another computer rather than just a single .exe file?

**Comment by JorjMcKie** [comment] 2020-02-06 09:33
> Are you saying I would need to distribute a folder with multiple files to another computer rather than just a single .exe file?

Yes, absolutely! **_Provided_** that the compile was successful, and that a test execution of the resulting binary inside the ``dist`` folder was successful, too, you then can take that ``dist`` folder and distribute it to other machines. It can be executed there without any other prerequisites - i.e. no Python needs to be installed there ...
If you find this cumbersome, you can also wrap that folder in one big executable instead. On the target machine, this big exe will unpack itself under the hood into a temporary folder and then invoke the original binary ...

**Closed** 2020-05-13 14:37 UTC
Labels: bug, duplicate
