### ISSUE TITLE
Import of `matplotlib.pyplot` may cause segfault

### ISSUE THREAD

**Issue by grgi** [Nuitka/Nuitka#3209] opened 2024-11-19 15:09 UTC
- [X] Not reported yet.
- [X] Issue does not appear running directly with the Python interpreter.
- [X] Develop version has the same problem (and also 2.5.1).
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
```
2.4.11
Commercial: 2.6.4
Python: 3.11.2 (main, Sep 14 2024, 03:00:30) [GCC 12.2.0]
Flavor: Debian Python
Executable: /tmp/matplotlibbug/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 12
Version C compiler: /usr/bin/gcc (gcc 12).
```

- How did you install Nuitka and Python

Python from Debian 12 and Nuitka from Github's Nuitka-commercial

- The specific PyPI names and versions

  > python -m pip list -v

```
Package         Version     Location                                        Installer
--------------- ----------- ----------------------------------------------- ---------
contourpy       1.3.1       /tmp/matplotlibbug/lib/python3.11/site-packages pip
cycler          0.12.1      /tmp/matplotlibbug/lib/python3.11/site-packages pip
fonttools       4.55.0      /tmp/matplotlibbug/lib/python3.11/site-packages pip
kiwisolver      1.4.7       /tmp/matplotlibbug/lib/python3.11/site-packages pip
matplotlib      3.9.2       /tmp/matplotlibbug/lib/python3.11/site-packages pip
Nuitka          2.4.11      /tmp/matplotlibbug/lib/python3.11/site-packages pip
numpy           2.1.3       /tmp/matplotlibbug/lib/python3.11/site-packages pip
ordered-set     4.1.0       /tmp/matplotlibbug/lib/python3.11/site-packages pip
packaging       24.2        /tmp/matplotlibbug/lib/python3.11/site-packages pip
pillow          11.0.0      /tmp/matplotlibbug/lib/python3.11/site-packages pip
pip             23.0.1      /tmp/matplotlibbug/lib/python3.11/site-packages pip
pyparsing       3.2.0       /tmp/matplotlibbug/lib/python3.11/site-packages pip
python-dateutil 2.9.0.post0 /tmp/matplotlibbug/lib/python3.11/site-packages pip
setuptools      66.1.1      /tmp/matplotlibbug/lib/python3.11/site-packages pip
six             1.16.0      /tmp/matplotlibbug/lib/python3.11/site-packages pip
zstandard       0.23.0      /tmp/matplotlibbug/lib/python3.11/site-packages pip
```

- Also supply a Short, Self Contained, Correct, Example

Consider `matplotlib-fail.py`:
```python
# nuitka-project: --standalone
# nuitka-project: --plugin-enable=no-qt

import matplotlib.pyplot
```
If non-existing, above import automatically creates a font cache file `~/.cache/matplotlib/fontlist-v390.json`.
In general this works fine in many instances, but in many instances (up to 50%) a segfault occurs:
```
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
Segmentation fault
```

In order to reproduce the following loop helps:
```
for i in `seq 10`; do rm -rf ~/.cache/matplotlib; sync; ./matplotlib-fail.dist/matplotlib-fail.bin; done
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
Segmentation fault
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
Segmentation fault
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
Segmentation fault
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
Segmentation fault
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
Segmentation fault
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
Segmentation fault
```

I tried to compile it with `--debug` as suggested in above URL (and using `--experimental=allow-c-warnings` from #2917), but the result is the same.

**Comment by kayhayen** [comment] 2024-11-20 09:58
Does it work when you don't disable Qt imports?

**Comment by grgi** [comment] 2024-11-20 10:49
No, it's the same.

**Comment by kayhayen** [comment] 2024-11-20 11:08
Ok, these sporadic errors are very annoying of course, and thanks for narrowing it down this much. I am trying for myself now, lets see if it crashes for me too. And yeah, I managed to reproduce it. Not sure if the `sync` can cause sporadic failures of some sorts, temporarily blocking some actions while others are not completed, so that would be the first thing I remove, but checking with --debug of course now first.

**Comment by kayhayen** [comment] 2024-11-21 10:21
So, I managed to get backtraces from 2 crashes, one was a garbage collection during a module import, where Nuitka was allocating a loader object, at which time these can trigger. And another one was at program exit. In both cases, visiting the dictionary during gc collection, and during module release at program exit, triggered a crash.

So, if the program runtime is too short for a GC to trigger, it may not crash, and deleting the files may just make it so. Or it may in fact be the thing that triggers it. Running inside the debugger made it crash a lot less, so timing seems to be indeed of the essence for this to occur. I will try and run it with a debug version of Python, where maybe also we get better information due to assertions of Python triggering maybe.

This could be a module doing funny things to its dictionary, replacing it and releasing an old one improperly, something that Nuitka tends to hate on. This won't be easy to find I fear.

**Comment by grgi** [comment] 2024-11-21 11:43
I think I found the culprit: I always thought it had to do with some file locking but you are right about the `dict`: `matplotlib` has a customized default for JSONEncoder (`matplotlib.font_manager._JSONEncoder`) where a dictionary is cloned and updated at the same time (I had not seen this undocumented invocation of `dict` before but it works):
```python
return dict(o.__dict__, __class__='FontManager')
```

If I change those statements to
```python
d = o.__dict__.clone()
d.update(__class__='FontManager')
return d
```
the segfaults do not occur anymore. It seems that with `d = dict(o.__dict__)` rather than `d = o.__dict__.copy()` the matplotlib code still produces segfaults.

**Comment by grgi** [comment] 2024-11-21 12:00
Yes:

https://github.com/matplotlib/matplotlib/blob/dcce48041b5df511b553f34a3d713d01082bd96a/lib/matplotlib/font_manager.py#L975 
and 
https://github.com/matplotlib/matplotlib/blob/dcce48041b5df511b553f34a3d713d01082bd96a/lib/matplotlib/font_manager.py#L977

I tried to get it to segfault without the bulky matplotlib but no look so far. Maybe I have to create larger dicts.

**Comment by kayhayen** [comment] 2024-11-21 12:25
This might come down to `DICT_COPY` of Nuitka working wrongly somehow for this type of dictionary somehow. I will have to make a careful audit of it against 3.12 code it seems. Dictionaries can be in various states dependending how they were created, and this might be 3.12 specific bug there, I can take it from there.

**Comment by grgi** [comment] 2024-11-21 12:40
Actually, I was using Python 3.11.

**Comment by kayhayen** [comment] 2024-11-21 12:44
Hm, ok reproduced it with 3.12 I believe, so that's making this less likely. I will investigate what paths exactly are taken for that dict builtin call, and find what's wrong with it.

**Comment by kayhayen** [comment] 2024-11-21 15:11
Thanks for your report. This is fixed on the staging and factory branches, which are a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome.

That said, current staging ought to be very good in comparison, I am still stabilizing 2.5 and will put in out as commercial baseline once the 2.5.2 hotfix containing this will be made, hopefully tomorrow.

**Comment by grgi** [comment] 2024-11-21 16:17
Thanks a lot for this quick fix and very soon release! With Nuitka from tha factory branch I don't see any segfaults anymore.

**Comment by kayhayen** [comment] 2024-11-24 09:27
Part of the 2.5.2 release I just made.

**Closed by kayhayen** 2024-11-24 09:27 UTC
Labels: bug, excellent_report
