### ISSUE TITLE
Plugin: Copy data files for lib2to3

### ISSUE THREAD

**Issue by VictoryWangCN** [Nuitka/Nuitka#2319] opened 2023-07-11 06:31 UTC
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

  1.7.3
  Commercial: None
  Python: 3.11.3 (main, Apr  7 2023, 21:05:46) [Clang 14.0.0 (clang-1400.0.29.202)]
  Flavor: Homebrew Python
  Executable: /opt/homebrew/Cellar/python@3.11/3.11.3/bin/python3.11
  OS: Darwin
  Arch: arm64
  Version C compiler: /usr/bin/clang (clang).

* How did you install Nuitka and Python
* 
   install python3.9 with brew
   pip3 install Nuitka without virtualenv or conda

* The specific PyPI names and versions
  > python -m pip freeze

  Nuitka==1.7.3
  ordered-set==4.1.0
  zstandard==0.21.0

When I use the command `nuitka --standalone --onefile --static-libpython=yes --follow-import-to=src --output-dir=out root.py` to build my project that includes `lib2to3`, the build completes successfully, but executing it throws an exception 
> No such file or directory: '/tmp/onefile_88085_1689056692_821052/lib2to3/Grammar3.9.17.final.0.pickle'. 

Then I rolled back to version 1.0.8, and it runs normally. 
After some simple testing, I suspect that it is caused by https://github.com/Nuitka/Nuitka/commit/3514be9f6588dd4b2e5032457644061a5082be2f , which changes the second argument of os.path.join from 'Grammar3.9.17.final.0.pickle' to '../Grammar3.9.17.final.0.pickle'.

 Can you please help me investigate this issue?

**Comment by kayhayen** [comment] 2023-07-11 06:36
A minimal reproducer would be nice, then I can see it more clearly.

**Comment by kayhayen** [comment] 2023-07-11 06:53
By looking at things though, I think I can deduce what happened. At some point the pattern collected files to put into dest_path, but now the original relative directory path is considered, so that providing `dest_path` is no more necessary to put it one level up, that still works now.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by VictoryWangCN** [comment] 2023-07-11 07:00
main.py

```python
import sys
from lib2to3.refactor import get_fixers_from_package, RefactoringTool


def run(path):
    fixers = get_fixers_from_package('lib2to3.fixes')
    fixers.extend([
        "lib2to3.fixes.fix_buffer",
        "lib2to3.fixes.fix_idioms",
        "lib2to3.fixes.fix_set_literal",
        "lib2to3.fixes.fix_ws_comma",
    ])
    refactoring_tool = RefactoringTool(fixer_names=fixers)
    refactoring_tool.write_unchanged_files = True

    refactoring_tool.refactor_file(path, write=True)

    with open(path) as file:
        for line in file:
            print(line)


if __name__ == '__main__':
    run(sys.argv[1])

```

nuitka --standalone --onefile --output-dir=out main.py

**Comment by kayhayen** [comment] 2023-07-11 07:17
Works on factory now. Also need the fixers as dependencies of `lib2to3.refactor` since Nuitka won't include these parts of stdlib anymore.

**Comment by VictoryWangCN** [comment] 2023-07-11 07:34
Works for me, Thank you for your support

**Comment by kayhayen** [comment] 2023-07-12 07:27
This is part of the hotfix release 1.7.4 that I just made.

**Closed by kayhayen** 2023-07-12 07:27 UTC
Labels: bug, factory
