### ISSUE TITLE
Standalone: Doesn't include the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by dark-penguin** [Nuitka/Nuitka#299] opened 2019-03-18 08:12 UTC
I'm building a "hello world" with PyQt5 with options:
```
nuitka3 test.py --show-progress --recurse-stdlib --standalone
```
The resulting binary does not work:
```
This application failed to start because it could not find or load the Qt
platform plugin "xcb".
Reinstalling the application may fix this problem.
Aborted (core dumped)
```
This happens even on the system where I built it.

Adding `--plugin-enable=qt-plugins` does not help.

Also, my application includes a "test mode": if I run it with "--test", it
prints a line "Test passed" and exits before importing anything PyQt-related.
And launching it this way works!

Actually, I just had the same issue with PyInstaller, but then I updated it to
the latest version, and now it's fixed. (I thought this information may be valuable.)

I tried this on Debian Jessie, Debian Stretch and Ubuntu Cosmic, with stable
Nuitka (from pip) and with development Nuitka (from sources), with whatever Python versions they have in the repos (IIRC that's 3.4, 3.5 and 3.6). So basically, it happens "always".

Here is my test.py :
```
import sys
if '--test' in sys.argv:
    print("Test passed")
    sys.exit(0)

from PyQt5.QtWidgets import QApplication, QMainWindow, QTextEdit
app = QApplication(sys.argv)
mw = QMainWindow()
textedit = QTextEdit(mw)
textedit.show()
mw.setCentralWidget(textedit)
mw.show()
sys.exit(app.exec_())
```

**Comment by kayhayen** [comment] 2019-03-18 09:21
Hello,

it works for me though. I am definitely positive, that PyQt works on Stretch and current Buster both.

It seems "xcb" platform plugin might be needed on Linux under some circumstances. 

```
                # Seems platforms is required on Windows.
                if os.name == "nt":
                    plugin_options.add("platforms")
```

I think we also have `--enable-plugin-qt-plugins=all` as a solution for now. 

Make that `or True` for the if statement, and report if it's working there. I think, what we ought to do is have a set of minimal chroots (`debootstrap`) in the standalone tests and run the resulting binary there as well. It seems that if python-qt5 is installed on the target machine, it works. But that is besides the point of standalone distribution.

On Windows, it always failed due to not having PyQt installed system wide and my Linuxes all have PyQt installed I guess, and probably most systems do. It may also be the case that the platform plugins actually are supposed to come from system installation, but I am not sure of that at all, I doubt it, but it could be.

Assuming this is your issue, I would look into improving the testing, so we can find these dirt effects.

Yours,
Kay

**Comment by dark-penguin** [comment] 2019-03-18 11:04
> I think we also have --enable-plugin-qt-plugins=all as a solution for now.

I guess you mean `--enable-plugin=qt-plugins=all` . :)

Both solutions helped! I guess it's better to include "platforms" by default, until you figure out in which cases is it _not_ needed?

By the way, is there a way to see all available qt-plugins and enable them selectively? I never even knew there was this additional option, otherwise I would have probably figured it out from the error message.

**Comment by kayhayen** [comment] 2019-03-18 13:55
You are correct about platforms, should be part of "sensible" for all platforms. Your chance of making a PR.

**Comment by dark-penguin** [comment] 2019-03-18 14:50
OK, it's a good opportunity to figure out how to do that. :)

**Comment by dark-penguin** [comment] 2019-03-18 15:50
I confirmed that having python3-pyqt5 installed does not help this at all. The problem lies elsewhere.

**Comment by kayhayen** [comment] 2019-03-18 17:07
I will try with chroot, @dark-penguin in the testing first, and see if it reproduces the issue. Maybe also you can `strace` it, and it does read some system wide Qt configuration files, that it probably should not, otherwise it's very strange what makes it work for me and probably many others. My `strace` based testing ought to reveal it it:

```
        # PyQt5 seems to do this, but won't use contents then.
        if loaded_filename in (
            "/usr/lib/x86_64-linux-gnu/qt5/plugins",
            "/usr/lib/x86_64-linux-gnu/qt5",
            "/usr/lib/x86_64-linux-gnu",
            "/usr/lib",
        ):
            continue

```

So it accesses directories for me. Can you run `tests/standalone/run_all.py search PyQt5Plugins` and see if it catches it for you? But then again, on your system it fails to load, and I believe in mine it does not attempt to do it.

Maybe if you remove all white listing like this one:

```
        if loaded_filename.startswith("/etc/"):
            continue
```

Then it ought to report us the accessed files. Could be that we need to set some environment variables on the fly that make it e.g. not use config files or not find them, or find them inside the distribution.

**Comment by dark-penguin** [comment] 2019-03-19 01:55
I'm doing all that in Docker containers instead of chroots. That's why I always post after having tried on at least two or three different systems.

I have Debian Jessie on my system (no time to upgrade...), and two containers with Debian Stretch and Ubuntu Cosmic. This way, I'm testing for both extremities - the oldest one worth supporting, and the newest and most popular one.

I guess if you try this with chroots, you must get this issue.

**Comment by dark-penguin** [comment] 2019-03-19 01:57
I wrote that this was recently fixed in PyInstaller.
https://github.com/pyinstaller/pyinstaller/issues/1906
This is _probably_ about this issue.

**Comment by dark-penguin** [comment] 2019-03-19 02:54
I've ran the tests you suggested. Attached the output files.

On Ubuntu Cosmic, I have PyQt5 v5.12 from pip, and... I don't seem to have either python3-pyqt5 or qt5-default, but the version of qt5-default in the repos is 5.11.1, so apparently I have some parts of Qt5 installed... which is why the test complains about it, to the best of my understanding.

On Debian Stretch, the situation seems to be the same, except the Qt version in the repos is 5.7.1 . I have no idea why is the test output different. I'm not exactly a guru of Python or Qt, so my understanding of what's going on is pretty limited at this point..
[cosmic.txt](https://github.com/Nuitka/Nuitka/files/2981329/cosmic.txt)
[stretch.txt](https://github.com/Nuitka/Nuitka/files/2981330/stretch.txt)

.

**Comment by dark-penguin** [comment] 2019-03-19 02:59
I've removed all the `if loaded_filename.startswith...` lines, and here are the new output files.
[cosmic.txt](https://github.com/Nuitka/Nuitka/files/2981341/cosmic.txt)
[stretch.txt](https://github.com/Nuitka/Nuitka/files/2981342/stretch.txt)

**Comment by kayhayen** [comment] 2019-03-21 20:48
Merged the PR to develop, will be in a release soon.

**Comment by kayhayen** [comment] 2019-04-04 08:39
Released as 0.6.3

**Closed by kayhayen** 2019-04-04 08:39 UTC
Labels: bug

**Comment by MurdochRav** [comment] 2019-08-12 00:08
I had the 'This application failed to start because it could not find or load the Qt
platform plugin "xcb" '  problem. In my case installing the package libxkbcommon solved things.

**Comment by kayhayen** [comment] 2019-08-12 06:33
Please raise a new issue @MurdochRav
