### ISSUE TITLE
ctypes.CDLL winmode parameter not supported

### ISSUE THREAD

**Issue by mvtec-bergdolll** [Nuitka/Nuitka#1880] opened 2022-11-10 12:55 UTC
Nuitka==1.2 installed via pip.

Python 3.9.5

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

I'm not sure how to provide a small example. You will require a dynamic library, for example compiled from C code and try to load that. You could probably reuse an existing system library.

The parameter winmode was introduced in Python 3.8 and I guess was not added to whatever nuitka transforms the CDLL call into. The relevant documentation https://docs.python.org/3/library/ctypes.html?highlight=cdll#ctypes.CDLL

 The error I get is:

```
TypeError: 'winmode' is an invalid keyword argument for ctypes.CDLL()
```

The issue only arises when using the `--standalone` option.

**Comment by kayhayen** [comment] 2022-11-10 18:10
This was handled, but the version criterion was messed up. Rather than >= 3.8 if was adding it for py2, sloppy stuff, but I don't quite get why it's useful anyway.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html

**Comment by mvtec-bergdolll** [comment] 2022-11-11 08:26
Thanks for the quick reply and fix!

Here is the comment next to our call of `CDLL`:

```
# Python 3.8 added the winmode parameter. If it is not specified, Python
# will attempt to open the DLL using LoadLibraryEx's
# LOAD_LIBRARY_SEARCH_DEFAULT_DIRS mode, which does not take the PATH
# environment variable into account. Since we expect the user to specify
# the location of the HALCON libraries to load via the PATH environment
# variable, that is not what we want, and we must specify winmode=0. Note
# the Python 3.8 documentation is incorrect and claims winmode=0 is the
# default; it is not.
```

**Comment by kayhayen** [comment] 2022-11-11 08:32
Interesting pointer. The reason we have `CDLL` is that for static optimization, we can then search the DLL at compile time, and if found, include it automatically. I guess, by reproducing whatever `winmode` is though, we would be compatible, but we may also mess with `PATH`, which would then have an effect I guess, something to take note of.

This is going into 1.2.1 hotfix release once I make it.

**Comment by kayhayen** [comment] 2022-11-20 16:09
This is part of the hotfix release 1.2.1 and also 1.2.2 that I just made.

**Closed by kayhayen** 2022-11-20 16:09 UTC
Labels: factory
