### ISSUE TITLE
transformers (4.30.2) unable to find PyTorch

### ISSUE THREAD

**Issue by 32h3basfl2** [Nuitka/Nuitka#2320] opened 2023-07-11 10:01 UTC
The issue was mentioned in #2193 and closed as fixed, but still result with same error. Due to locked conversation, a new issue is filed.

* Nuitka version, full Python version, flavor, OS, etc. as output by *this* command.

  > python -m nuitka --version

```
1.7.3
Commercial: None
Python: 3.8.17 (default, Jul  5 2023, 20:44:21) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

Additionally, I also tried with MSVC 14.2 compiler (using option `--msvc=14.2`) and get the same failure result, although it is not supported compiler so may not worth to be considered.

* How did you install Nuitka and Python

```
conda create --name packing python=3.8 --no-default-packages   # this ensure environment is clean
pip install transformers torch torchvision nuitka
```

* The specific PyPI names and versions

  > python -m pip freeze

```
certifi==2023.5.7
charset-normalizer==3.2.0
colorama==0.4.6
filelock==3.12.2
fsspec==2023.6.0
huggingface-hub==0.16.4
idna==3.4
Jinja2==3.1.2
MarkupSafe==2.1.3
mpmath==1.3.0
networkx==3.1
Nuitka==1.7.3
numpy==1.24.4
ordered-set==4.1.0
packaging==23.1
Pillow==10.0.0
PyYAML==6.0
regex==2023.6.3
requests==2.31.0
safetensors==0.3.1
sympy==1.12
tokenizers==0.13.3
torch==2.0.1
torchvision==0.15.2
tqdm==4.65.0
transformers==4.30.2
typing_extensions==4.7.1
urllib3==2.0.3
zstandard==0.21.0
```

* Example source code for reproduce:

It is actually same as #2151.

```python
import transformers
import torch
print('hello world')
print(transformers.__version__, torch.__version__)
```

And the output response:
```
None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.
hello world
4.30.2 2.0.1+cpu
```

Although it seems introduce no error and just a warning, nothing is actually called from the example source code. 

Instead if you add this to the example source above:

```python
from transformers.generation import GenerationMixin
```

will result this:

```
ImportError: cannot import name 'GenerationMixin' from 'transformers.generation'
```

*  Nuitka options used
```
python -m nuitka --follow-imports pytorch_test.py --standalone --noinclude-pytest-mode=nofollow --noinclude-IPython-mode=nofollow --noinclude-setupt
ools-mode=nofollow --enable-plugin=transformers
```

As the previous issue is fixed in v1.6, I am not sure if the issue is from 1.7, or newer version of `transformers` (the closed one at 4.27). Due to very slow to build (3 hours+ on my machine), previous versions are not yet tested.

**Comment by lechwolowski** [comment] 2023-07-11 10:42
I have the exact same problem

**Comment by kayhayen** [comment] 2023-07-12 07:29
The reason I am locking issues, is that the same symptom can have different root causes. In your cases, I now suspect that Anaconda and pip might be an issue there. We shall see.

**Comment by 32h3basfl2** [comment] 2023-07-12 08:21
Confirmed cannot reproduce on transformers 4.28.1 with nuitka 1.6.6 (as of the version for previous closed issue).

Now I am trying on 4.28.1 with nuitka 1.7.3. If success, the issue is come from the transformer version upgrade. Otherwise, it may be regression from v1.6 to v1.7. As I don't find the hotfix release note for version 1.7.x (maybe drafting until 1.8 release since 1.7 release mostly implemented in 1.6.x?), I cannot conclude until the build complete or finish reviewing nuitka changes.

Will update once the build complete, although it takes long.

**Comment by 32h3basfl2** [comment] 2023-07-12 10:36
Confirmed it is **NOT** regression from Nuitka as 1.7.3 build succeed on transformers 4.28.1.

So to fix the issue, either we need a more robust plugin for transformer, or per version which can be extremely hard to manage. The former solution need to dig deep on how transformers update themselves. 

Referring the previous fix, you may be interested on [how they check it](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/import_utils.py#L137):
```python
_torch_version = "N/A"
_torch_available = False
if USE_TORCH in ENV_VARS_TRUE_AND_AUTO_VALUES and USE_TF not in ENV_VARS_TRUE_VALUES:
    _torch_available, _torch_version = _is_package_available("torch", return_version=True)
else:
    logger.info("Disabling PyTorch because USE_TF is set")
    _torch_available = False
```

And now that `importlib_metadata` is moved to [here](https://github.com/huggingface/transformers/blob/main/src/transformers/utils/import_utils.py#L41).
```python
# TODO: This doesn't work for all packages (`bs4`, `faiss`, etc.) Talk to Sylvain to see how to do with it better.
def _is_package_available(pkg_name: str, return_version: bool = False) -> Union[Tuple[bool, str], bool]:
    # Check we're not importing a "pkg_name" directory somewhere but the actual library by trying to grab the version
    package_exists = importlib.util.find_spec(pkg_name) is not None
    package_version = "N/A"
    if package_exists:
        try:
            package_version = importlib.metadata.version(pkg_name)
            package_exists = True
        except importlib.metadata.PackageNotFoundError:
            package_exists = False
        logger.debug(f"Detected {pkg_name} version {package_version}")
    if return_version:
        return package_exists, package_version
    else:
        return package_exists
```

Seems logic remains same, but the exact term `importlib_metadata.version("torch")` no longer exist because it moved to a function now. See if this information help.

**Comment by kayhayen** [comment] 2023-07-12 11:27
I see, Nuitka will one day soon gain the ability to mark functions for inlining cross module. We have also a new feature in the Yaml that can deal with it.

Most probably we can use that, it goes like this:

```
- module-name: 'opentelemetry.propagate'
  data-files:
    include-metadata:
      - 'opentelemetry-api'
```

It will be more robust for sure, and will probably be able to make that part of the plugin obsolete.

The list in `_import_structure_modules` was derived by greping, it may also easily fall out of date. Maybe we could refer to the source code from within the plugin to tell. Then it should be more robust indeed.

**Comment by kayhayen** [comment] 2023-07-14 11:57
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-07-14 13:51
This is part of the hotfix release 1.7.5 that I just made.

**Closed by kayhayen** 2023-07-14 13:51 UTC
Labels: bug

**Comment by kayhayen** [comment] 2023-07-14 13:53
In the end, for the example given at least, it was enough to do this:

```
- module-name: 'transformers'
  data-files:
    include-metadata:
      - 'torch'
      - 'flax'
      - 'tensorflow'
```

With sufficient annotations for compile time inlining, this could be avoided, but still. Notice, that these are embedded objects, not separate files as with standard Python, but these distribution objects work well with standalone mode.
