### ISSUE TITLE
Panda3D Dylib Bug

### ISSUE THREAD

**Issue by Carlisle03** [Nuitka/Nuitka#2675] opened 2024-01-29 00:32 UTC
While I was compiling my Panda3D python file, I had a problem 

### THE ERROR :
```zsh
FATAL: Error, failed to find path @loader_path/../lib/libp3interrogatedb.1.10.dylib (resolved DLL to /opt/homebrew/lib/python3.11/site-packages/lib/libp3interrogatedb.1.10.dylib) for /opt/homebrew/lib/python3.11/site-packages/panda3d/libp3interrogatedb.1.10.dylib from 'panda3d', please report the bug.
```

My OS was MacOS 14.2

and my command was this 

```zsh
nuitka3 --macos-create-app-bundle game.py
```

It worked on the normal ***python3 game.py***
But not on nuitka3.

# About My Nuitka3

```zsh
2.0
Commercial: None
Python: 3.11.7 (main, Dec  4 2023, 18:10:11) [Clang 15.0.0 (clang-1500.1.0.2.5)]
Flavor: Homebrew Python
Executable: /opt/homebrew/Cellar/python@3.11/3.11.7_1/bin/python3.11
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang 15.0.0).
```

**Comment by kayhayen** [comment] 2024-01-30 07:46
@Maxwell175 any idea on this one?

**Comment by kayhayen** [comment] 2024-01-30 07:47
This seems to lack a minimal reproducer, please provide it.

**Comment by gabeklavans** [comment] 2024-02-03 19:53
Chiming in to add that I'm also building a panda3d game with nuitka. The exact same codebase builds with nuitka fine on windows, but on my mac, I get the same error as @Carlisle03. Looks like the path added an extraneous "../lib". Not sure why.

I can try to make a minimal reproducer if needed.

**Comment by gabeklavans** [comment] 2024-02-03 22:59
@kayhayen Here is a minimal example, see the README for more instruction

https://github.com/gabeklavans/p3d-nuitka-lib-bug

**Comment by kayhayen** [comment] 2024-02-04 11:42
@gabeklavans I wonder why you didn't encounter this

> FATAL: options-nanny: Error, package 'wx' requires '--macos-create-app-bundle' to be used or else it cannot work.

Or is using wx optional in Panda3D?

**Comment by kayhayen** [comment] 2024-02-04 11:43
Anyway, I indeed managed to reproduce the issue.

**Comment by kayhayen** [comment] 2024-02-04 11:46
This is yet another malformed dependency of a DLL on itself, `@loader_path/../lib/libp3interrogatedb.1.10.dylib` probably only existed during build time, if ever, there is no `lib` folder after the pip install in sight.

**Comment by kayhayen** [comment] 2024-02-04 12:00
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2024-02-04 12:02
The Panda3D not only depends DLLs on themselves in different folders, but sometimes also does it with versioned DLL names, and what's new there as well, is that it is using multiple digits, added handling for all of those as well. From what I hear, Panda3D is one of the worst build systems, so if that's working now, we got a lot more robust I guess.

**Comment by gabeklavans** [comment] 2024-02-04 16:07
> @gabeklavans I wonder why you didn't encounter this
> 
> 
> 
> > FATAL: options-nanny: Error, package 'wx' requires '--macos-create-app-bundle' to be used or else it cannot work.
> 
> 
> 
> Or is using wx optional in Panda3D?

Ah that may have been because of my build cache. I was trying to use a minimal set of options. Glad you were able to reproduce and create a patch, though!

**Comment by gabeklavans** [comment] 2024-02-05 05:33
@kayhayen  the bug does appear to be fixed in my minimal reproduction repo, however when I run my full build on my actual panda3d application, now I'm getting this error:
```
FATAL:     Error, problem with dependency scan of '<home>/Library/Caches/pypoetry/virtualenvs/<venv>/lib/python3.11/site-packages/panda3d/libpandaexpress.1.11.dylib' with '/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib' please report the bug.
```

Using nuitka version `2.1rc2`.

I can try to make a reproducable repo for this as well but it's less clear to me what the issue is.


> @gabeklavans I wonder why you didn't encounter this
> 
> > FATAL: options-nanny: Error, package 'wx' requires '--macos-create-app-bundle' to be used or else it cannot work.
> 
> Or is using wx optional in Panda3D?

Also with regards to this, I cleared my build cache and still didn't encounter this error when only using `--standalone`, not sure why that is.

**Comment by kayhayen** [comment] 2024-02-05 09:24
The error message should indeed output a "report path", then you wouldn't have to edit it, at least for the home directory. Your issue seems unrelated though, please open a new issue @gabeklavans as this fix is going to get released independent of solving and reproducing that.

**Comment by Carlisle03** [comment] 2024-02-05 09:37
> @kayhayen the bug does appear to be fixed in my minimal reproduction repo, however when I run my full build on my actual panda3d application, now I'm getting this error:
> 
> ```
> FATAL:     Error, problem with dependency scan of '<home>/Library/Caches/pypoetry/virtualenvs/<venv>/lib/python3.11/site-packages/panda3d/libpandaexpress.1.10.dylib' with '/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib' please report the bug.
> ```
> 
> Using nuitka version `2.1rc2`.
> 
> I can try to make a reproducable repo for this as well but it's less clear to me what the issue is.
> 
> > @gabeklavans I wonder why you didn't encounter this
> > > FATAL: options-nanny: Error, package 'wx' requires '--macos-create-app-bundle' to be used or else it cannot work.
> > 
> > 
> > Or is using wx optional in Panda3D?
> 
> Also with regards to this, I cleared my build cache and still didn't encounter this error when only using `--standalone`, not sure why that is.

**Comment by Carlisle03** [comment] 2024-02-05 09:38
> @kayhayen the bug does appear to be fixed in my minimal reproduction repo, however when I run my full build on my actual panda3d application, now I'm getting this error:
> 
> ```
> FATAL:     Error, problem with dependency scan of '<home>/Library/Caches/pypoetry/virtualenvs/<venv>/lib/python3.11/site-packages/panda3d/libpandaexpress.1.10.dylib' with '/opt/homebrew/opt/openssl@1.1/lib/libssl.1.1.dylib' please report the bug.
> ```
> 
> Using nuitka version `2.1rc2`.
> 
> I can try to make a reproducable repo for this as well but it's less clear to me what the issue is.
> 
> > @gabeklavans I wonder why you didn't encounter this
> > > FATAL: options-nanny: Error, package 'wx' requires '--macos-create-app-bundle' to be used or else it cannot work.
> > 
> > 
> > Or is using wx optional in Panda3D?
> 
> Also with regards to this, I cleared my build cache and still didn't encounter this error when only using `--standalone`, not sure why that is.

Maybe, you need to install openssl

**Comment by kayhayen** [comment] 2024-02-05 10:04
Closing issues only when in stable release or not of general relevance.

**Comment by kayhayen** [comment] 2024-02-09 13:32
Part of the 2.0.2 release I just made.

**Closed by kayhayen** 2024-02-09 13:32 UTC
Labels: bug, factory

**Comment by Carlisle03** [comment] 2024-02-11 01:06
I saw another problem 

``` zsh
Nuitka-Options: Used command line options: main.py --macos-create-app-bundle
Nuitka-Options: Detected static libpython to exist, consider '--static-libpython=yes' for better performance, but errors may happen.
Nuitka: Starting Python compilation with Nuitka '2.0.2' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 15.0.0).
Nuitka will make use of ccache to speed up repeated compilation.

Is it OK to download and put it in '/Users/carlisledelosreyes/Library/Caches/Nuitka/downloads/ccache/v4.2.1'.

Fully automatic, cached. Proceed and download? [Yes]/No : y
Nuitka: Downloading 'https://nuitka.net/ccache/v4.2.1/ccache-4.2.1.zip'.
Nuitka: Extracting to '/Users/carlisledelosreyes/Library/Caches/Nuitka/downloads/ccache/v4.2.1/ccache'
Nuitka-Scons: Backend linking program with 152 files (no progress information available for this stage).
Nuitka-Scons: Compiled 152 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 152
Nuitka-Plugins:data-files: Included data file 'etc/Confauto.prc' due to package data directory 'etc' for 'panda3d'.
Nuitka-Plugins:data-files: Included data file 'etc/Config.prc' due to package data directory 'etc' for 'panda3d'.
Nuitka-Plugins:dll-files: Found 7 files DLLs from panda3d installation.
Nuitka:WARNING: Report writing was prevented by exception AssertionError((<importlib.metadata.PathDistribution object at 0x10cc1ecd0>, None,
Nuitka:WARNING: PosixPath('/opt/homebrew/lib/python3.11/site-packages/numpy-1.26.4.dist-info'))), use option '--experimental=debug-report-traceback' for full traceback.
Detecting used DLLs: 56.6%|██████████████▏          | 30/53, _tkinter.soTraceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/__main__.py", line 172, in <module>
    main()
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/__main__.py", line 158, in main
    MainControl.main()
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/MainControl.py", line 1130, in main
    _main()
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/MainControl.py", line 1022, in _main
    detectUsedDLLs(
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/freezer/Standalone.py", line 335, in detectUsedDLLs
    _detectUsedDLLs(
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/freezer/Standalone.py", line 282, in _detectUsedDLLs
    allow_outside_dependencies = Plugins.decideAllowOutsideDependencies(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/plugins/Plugins.py", line 1391, in decideAllowOutsideDependencies
    value = plugin.decideAllowOutsideDependencies(module_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/plugins/standard/DllFilesPlugin.py", line 411, in decideAllowOutsideDependencies
    distribution = getDistributionFromModuleName(module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/utils/Distributions.py", line 217, in getDistributionFromModuleName
    distributions = getDistributionsFromModuleName(module_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/utils/Distributions.py", line 196, in getDistributionsFromModuleName
    _package_to_distribution = _initPackageToDistributionName()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/utils/Distributions.py", line 162, in _initPackageToDistributionName
    distribution_name = getDistributionName(distribution)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/nuitka/utils/Distributions.py", line 382, in getDistributionName
    assert isValidDistributionName(result), (
AssertionError: (<importlib.metadata.PathDistribution object at 0x12d7d0ad0>, None, PosixPath('/opt/homebrew/lib/python3.11/site-packages/numpy-1.26.4.dist-info'))
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
```
My nuitka version is now updated
