### ISSUE TITLE
Nuitka can't import "Python3.x/tcl/tcl8/8.5/msgcat-1.6.1.tm" with option --enable-plugin=tk-inter

### ISSUE THREAD

**Issue by funchan24** [Nuitka/Nuitka#1440] opened 2022-02-23 13:46 UTC
Nuitka can't import "Python3.x/tcl/tcl8/8.5/msgcat-1.6.1.tm" and some other files with option --enable-plugin=tk-inter, which will cause some problems when use ttkbootstrap-a supercharged theme extension for tkinter https://github.com/israel-dryer/ttkbootstrap/issues/184

OS: Windows 11 x64
Python: 3.7.6 x86
Nuitka: 0.6.19.7
ttkbootstrap: 1.7.2

**Comment by kayhayen** [comment] 2022-02-25 08:52
That is not having anything having any useful reproducer, do you provide one? Also, use latest Nuitka please.

**Comment by funchan24** [comment] 2022-02-25 16:23
I used [ttkbootstrap](https://github.com/israel-dryer/ttkbootstrap)-a supercharged theme extension for tkinter, the script work well, but I got a error when compile it to exe use nuitka. ttkbootstrap's author do much work and found nuitka can't import "Python3.x/tcl/tcl8/8.5/msgcat-1.6.1.tm"

main.py:
```
from ttkbootstrap import *

root = Window()
Label(root, text='工号').pack(side=LEFT)
Entry(root).pack(side=LEFT)
root.mainloop()
```

compile command:
`nuitka --standalone --plugin-enable=tk-inter main.py`

My Envrinment:
OS: Windows 11 x64
Python: 3.7.6 x86, use venv
Nuitka: 0.7.1
ttkbootstrap: 1.7.2

**Comment by funchan24** [comment] 2022-03-07 12:33
Nuitka 0.7.3 the same

**Comment by funchan24** [comment] 2022-03-09 05:40
Copy dir "tcl/tcl8" to root dir of compiled application could avoid the error. Maybe  improve the code at here https://github.com/Nuitka/Nuitka/blob/02e8d59a275cd7fe482cbc8100e753ff5abe39d7/nuitka/plugins/standard/TkinterPlugin.py#L136
@kayhayen

**Comment by kayhayen** [comment] 2022-03-10 12:26
@funchan24 in what way?

**Comment by funchan24** [comment] 2022-03-11 04:09
@kayhayen Because Nuitka does not copy all tkinter files，I copy "sys.base_prefix//tcl /tcl8" to the target directory then solved this error.Now I've written a packaging script. It's best if Nuitka  solve this problem.

**Comment by kayhayen** [comment] 2022-03-11 08:30
Are some of these files stemming from the installation of `ttkbootstrap ` maybe? Also, report what `python -m nuitka --version` gives on latest develop version. I haven't seen this path on Windows before.

**Comment by funchan24** [comment] 2022-03-11 10:15
I am using python venv and pretty sure these files are from python itself. On my computer, It's here.
![image](https://user-images.githubusercontent.com/42088233/157847655-7d549db4-885b-4aae-86a6-3169770ff7a5.png)



```0.7.3
Commercial: None
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 18 2019, 23:46:00) [MSC v.1916 32 bit (Intel)]
Flavor: Unknown
Executable: C:\Users\funchan\Documents\App\DomainTools\.venv\Scripts\python.exe
OS: Windows
Arch: x86
WindowsRelease: 10```

**Comment by kayhayen** [comment] 2022-03-11 15:03
I wonder if Windows 11 is detected as Windows 10 now. Is this code giving the wrong number:

```
    import platform

    return platform.release()
```

**Comment by kayhayen** [comment] 2022-03-11 15:04
Otherwise, yes, that is my folder structure too, I believe it must be CPython. Note that 32 bits Python might cause issues unless using MSVC for compilation, and even then. So you are saying it might be two folders to copy?

**Comment by kayhayen** [comment] 2022-03-11 15:08
I have these:

```
ls /c/Python37_32/tcl/tcl8/
8.4/  8.5/  8.6
```

And in 8.6, and in each, there is a different set of `.tm` things.

  /c/Python37_32/tcl/tcl8/
  /c/Python37_32/tcl/tcl8/8.4
  /c/Python37_32/tcl/tcl8/8.4/platform
  /c/Python37_32/tcl/tcl8/8.4/platform/shell-1.1.4.tm
  /c/Python37_32/tcl/tcl8/8.4/platform-1.0.14.tm
  /c/Python37_32/tcl/tcl8/8.5
  /c/Python37_32/tcl/tcl8/8.5/msgcat-1.6.1.tm
  /c/Python37_32/tcl/tcl8/8.5/tcltest-2.5.0.tm
  /c/Python37_32/tcl/tcl8/8.6
  /c/Python37_32/tcl/tcl8/8.6/http-2.9.0.tm

**Comment by kayhayen** [comment] 2022-03-11 15:17
So, what confused me about your report also, is the fact, that with a Tcl 8.6 using Python, you get a missing file report with a name that includes 8.5, but maybe that is some sort of minimum language level or something. But you are saying, you just copied them, and it works. I think, you merged the two folders that way, because by default, Nuitka strips it from a Tcl version number.

I also noticed, that Python 3.10 has the same files. Not including them might be a bug that has nothing to do with [ttkbootstrap](https://github.com/israel-dryer/ttkbootstrap) at all. I am also trying to map this to Linux installations now.

**Comment by kayhayen** [comment] 2022-03-11 17:43
So, I managed to reproduce the issue:

> _tkinter.TclError: invalid command name "::msgcat::mcmset"

I think you never gave the actual error message you saw, but you thankfully did instead find out what it means, which I would have been really stomped I guess.

**Comment by kayhayen** [comment] 2022-03-12 09:09
I fixed this by including the files, indeed. Currently, only on Windows, I have yet to try the example on Linux and macOS.

**Comment by kayhayen** [comment] 2022-03-12 09:10
Get it from here: https://nuitka.net/doc/factory.html

**Comment by funchan24** [comment] 2022-03-12 09:24
The  factory branch has solved this problem. Thanks for your great work！

**Comment by kayhayen** [comment] 2022-03-12 12:39
On Linux it works without this, seems to be a Windows only problem then.

**Comment by kayhayen** [comment] 2022-03-12 12:40
We keep issues where it's technically done, still open to track their release status.

**Comment by kayhayen** [comment] 2022-05-15 07:40
This is on develop for a while now

**Comment by kayhayen** [comment] 2022-05-20 14:36
Part of 0.8 release that I just made.

**Closed by kayhayen** 2022-05-20 14:36 UTC
Labels: bug, develop, excellent_report
