### ISSUE TITLE
Attempted to compile packages by compiled individual python files went wrong

### ISSUE THREAD

**Issue by joaopfg** [Nuitka/Nuitka#1638] opened 2022-06-28 13:37 UTC
I'm having an issue when running main entry points located in sub packages of regular packages. Seems to be related to the compilation of  `__init__.py` files of sub packages.

My output of `python -m nuitka --version` is:

```
0.8.4
Commercial: None
Python: 3.9.5 (default, Mar 28 2022, 18:48:27) 
Flavor: pyenv
Executable: /home/eyepick/.pyenv/versions/3.9.5/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.4
```

I installed Nuitka using `python -m pip install nuitka`, as recommended in the readme.

My output of `python -m pip freeze` is empty (the issue can be reproduced with no external dependency).

In order to reproduce the issue, download the [zip](https://drive.google.com/file/d/1AZzNccgKnkG4ercn_ZpJ3cIIsgCa9KTR/view?usp=sharing). It contains:

1) a bash script that does a depth-first search in the directory given as argument and compile each python module with Nuitka (skipping the black listed folders and directories given as arguments). It's use is like:

`bash nuitkize.sh package-name -f package-name/dir1/file1.py package-name/dir1/file2.py ... -d  package-name/dir3 package-name/dir4 ...`

It will compile each file of the package named `package-name` while skipping the files `package-name/dir1/file1.py`, `package-name/dir1/file2.py`, ... and the directories `package-name/dir3`, `package-name/dir4`, ...

2) A test package to reproduce the issue.

To reproduce the issue, unzip the zip, cd into the folder and run `bash nuitkize.sh test-package -d test-package/scripts`. Then, run `python -B -m scripts.script1` to get the error:

`ImportError: dynamic module does not define module export function (PyInit_dir1) `

Repeat the procedure but now compilng it by running `bash nuitkize.sh test-package -f test-package/__init__.py test-package/dir1/__init__.py -d test-package/scripts`. When running `python -B -m scripts.script1` it should now run normally and print `Entry f1`.

**Comment by kayhayen** [comment] 2022-06-29 07:33
That is already wrong: Successfully created '__init__.cpython-39-x86_64-linux-gnu.so'

**Comment by kayhayen** [comment] 2022-06-29 07:36
To compile packages, you compile the directory, and not the file. Arguably, this is a more or less obvious user error, that Nuitka can catch. Then there is also the issue, I think that mixed loading of Python modules below extension modules, may not be working all that well. I forgot what the exact status of that is, but I think I added it at some point, not sure now, but for the init files to be packages and still import below them, that is nothing extension modules usually do. However, like I said, I may have forgotten it.

**Comment by kayhayen** [comment] 2022-06-29 08:16
When you provide a directory, the `__main__.py` is used, if it exists, otherwise a `__init__.py` is used. I don't think I can easily just strip the filename part, so instead I am going to make it an error in options parsing.

**Comment by kayhayen** [comment] 2022-06-29 08:29
Part of factory now, will be in next hotfix release too, https://nuitka.net/doc/factory.html

**Comment by joaopfg** [comment] 2022-06-29 09:17
@kayhayen Sorry if it was unclear. Actually, it was not my intention to bother you looking at my bash script. I put it there so that you could reproduce quickly the behavior I am getting when compiling each module separately file by file: when compiling the `__init__.py` files, it gives the error I mentioned when running the python script `script1` in the sub package `script`. When not  compiling  the `__init__.py` files, it doesn't give these errors.

If it's worth to mention, I am actually using Nuitka as a obfuscation tool for the code the company I work for produces. So, if the approach I was using doesn't have serious performance issues, it's ok..

Having said that, I am currently using this approach of compiling file by file because I couldn't figure out how to do what I wanted with Nuitka CLI (probably because I didn't dig deeper in the docs) and it was faster for me to write the bash script I put here (time constraints at work). I saw that I can compile a whole package with `python -m nuitka --module some_package --include-package=some_package`. But in my case, I actually have some python scripts supposed to be run (in some sub packages), like in the minimal reproducible example I put. I don't want to compile those and I want to keep them inside the sub packages (respecting the structure of the package). How it can be done with Nuitka CLI ?

**Comment by kayhayen** [comment] 2022-06-29 10:10
Like I said, when it's easy to reproduce, it can also save a 1000 words. It seemed however, that you figured out the solution. Also a nice enhancement came out of it, that catches your error/wrong assumption at compile time.

It is considered impossible to get the python code back from the extension module. The data used in there, without Nuitka commercial that should be easy, with it, requires a skilled attacker.

Do you execute your scripts by filename or by name, i.e. `python some_package/sub_package/script.py` or "python -m some_package.sub_package.script`? In the first case, you are not executing them from within your package, and they could exist everywhere, in the second case, given `some_package` as an extension module in your `PYTHONPATH` should work.

However, I sort of remembered something, and that is that data files are going to have trouble in this world, we recently added this:

```
        if Options.shallMakeModule():
            base_path = OutputDirectories.getResultBasePath(onefile=False)

            if os.path.isdir(base_path):
                general.warning(
                    """The compilation result is hidden by package directory '%s'. Importing will not use compiled code."""
                    % base_path
                )

```

That is just because of what CPython does.  So when `some_package` uses data files, and tries to look it im in the `some_package` folder right next to it, well, not going to use the compiled code anymore, but a namespace directory. Of course commercial has file embedding that solves this, but now I wonder if this is really true, or if it does not also require a `__init__.py` to remain present. I need to convince myself of that I guess.

**Comment by kayhayen** [comment] 2022-06-29 10:12
Ok, actually that warning is wrong, it would indeed have to be a real package directory, with `__init__.py` and a mere directory works well for data files.

**Comment by joaopfg** [comment] 2022-06-29 12:03
Sorry, but what are you referring as data files ? Is it everything that does not have a `.py` extension ?

**Comment by kayhayen** [comment] 2022-06-30 07:09
The new warning is part of the 0.9.2 hotfix release I just made. Nothing to do here really anymore.

**Closed by kayhayen** 2022-06-30 07:09 UTC
Labels: enhancement, factory

**Comment by joaopfg** [comment] 2022-06-30 08:37
@kayhayen Is it available on PyPI ?
