### ISSUE TITLE
Nuitka 0.6.19rc5: Link fails due to undefined reference to IMPORT_HARD__FROZEN_IMPORTLIB

### ISSUE THREAD

**Issue by kamgha** [Nuitka/Nuitka#1332] opened 2021-12-21 01:28 UTC
Nuitka 0.6.19rc5 (from source)
CPython 3.7.12 on Windows 7 SP1
GCC+MinGW64: 11.2.0 with MinGW64 master from mid december 2021

Running Nuitka with `..\path\to\python.exe -m nuitka --standalone --mingw64 --disable-ccache --show-scons --lto=no --prefer-source-code --follow-stdlib --python-flag=no_site,no_randomization,no_warnings,no_asserts,no_docstrings ..\t\test.py`

Removing `--follow-stdlib` makes the build run through. Also, Nuitka 0.6.18.4 works fine as well.

During compilation the following warning appears:

```
gcc -o module.optparse.o -c -std=c11 -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -ftrack-macro-expansion=0 -Wno-deprecated-declarations -fno-var-tracking -Wno-misleading-indentation -Wno-deprecated-declarations -fno-var-tracking -fcompare-debug-second -O3 -D_WIN32_WINNT=0x0501 -D_NUITKA_STANDALONE -D__NUITKA_NO_ASSERT__ -DMS_WIN64 -D_NUITKA_CONSTANTS_FROM_RESOURCE -D_NUITKA_FROZEN=168 -D_NUITKA_EXE -ID:\ntest\panda3d\python\include -I. -ID:\ntest\NUITKA~1.19R\nuitka\build\include -ID:\ntest\NUITKA~1.19R\nuitka\build\static_src module.optparse.c
module.importlib.abc.c: In function 'modulecode_importlib$abc':
module.importlib.abc.c:5547:31: warning: implicit declaration of function 'IMPORT_HARD__FROZEN_IMPORTLIB'; did you mean 'IMPORT_HARD_IMPORTLIB'? [-Wimplicit-function-declaration]
 5547 |         tmp_assign_source_7 = IMPORT_HARD__FROZEN_IMPORTLIB();
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                               IMPORT_HARD_IMPORTLIB
module.importlib.abc.c:5547:29: warning: assignment to 'PyObject *' {aka 'struct _object *'} from 'int' makes pointer from integer without a cast [-Wint-conversion]
 5547 |         tmp_assign_source_7 = IMPORT_HARD__FROZEN_IMPORTLIB();
      |                             ^
```

And the build fails at linking:

```
gcc -o D:\ntest\NUITKA~1.19R\TEST~1.DIS\test.exe -Wl,--exclude-all-symbols -Wl,--out-implib,.\import.lib -Wl,--stack,9863168 -Wl,--enable-auto-import -s -static-libgcc @".\@link_input.txt" -LD:\ntest\panda3d\python\libs -lm -lpython37
d:/ntest/wingcc64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: ./module.importlib.abc.o:module.importlib.abc.c:(.text+0x65de): undefined reference to `IMPORT_HARD__FROZEN_IMPORTLIB'

collect2.exe: error: ld returned 1 exit status
scons: building terminated because of errors.
```

A "Hello World" program works fine.

Reproducer (you'll need `panda3d`, e. g. installed trough `pip`):

```
from direct.showbase.ShowBase import ShowBase


class MyApp(ShowBase):

    def __init__(self):
        ShowBase.__init__(self)


app = MyApp()
app.run()
```

**Comment by kayhayen** [comment] 2021-12-21 15:42
For `--follow-stdlib` there is still not a lot of test coverage, it might be better or worse on develop or even factory branch, as I have worked on the `anti-bloat` plugin to remove stdlib modules a lot, and static optimization has probably not done this one before, since now function level module variables are used for hard import tracing. I will check this when I find the time to resume work on stdlib. Mid term it's a goal to make it the default.

**Comment by kayhayen** [comment] 2021-12-21 22:48
Why are you not using anti-bloat, it also removes a lot for stdlib.

**Comment by kayhayen** [comment] 2021-12-21 22:55
The `import importlib.abc` is all it takes. I believe the version guards in the C code as generated are from which versions Nuitka used it in its own import logic, whereas the import optimization works off actual availability. So this is easy to fix, but probably not too relevant, little code is importing that.

**Comment by kamgha** [comment] 2021-12-21 23:24
> Why are you not using anti-bloat, it also removes a lot for stdlib.

I wasn't for this report, but I'd move on with that for now. `--enable-plugin=anti-bloat --noinclude-custom-mode=importlib.abc:nofollow` does work, as long as nothing is actually using it.

I've opened up this issue because this issue is not visible in Nuitka 0.6.18.4, so a change may have introduced this.

**Comment by kayhayen** [comment] 2021-12-22 09:06
It did, and I am very grateful for these reports of yours, keep them going. Regressions discovered only later are very expensive to me in terms of time.I am closing the issue now, since I rebased the develop change and made a new pre-release with it the other day.

**Closed by kayhayen** 2021-12-22 09:06 UTC

**Comment by kayhayen** [comment] 2021-12-22 14:14
@kamgha if `importlib.abc` is not used, find out what pulls it in, and make a anti-bloat change in a PR, that would be very useful thing to do.

**Comment by kayhayen** [comment] 2021-12-22 14:15
Finding out works if you put `error` rather than `nofollow`, it will then output the source location that does the bad thing.

**Comment by kamgha** [comment] 2021-12-22 16:59
I wasn't too precise in my comment: `importlib.abc` gets imported via `shutil<-zipfile<-importlib.util<-importlib.abc` and also via `pkg_resources<-...<-importlib.util<-importlib.abc`. So the question is, whether this codepath https://github.com/python/cpython/blob/3.7/Lib/importlib/util.py#L266 is actually being used at some point in the resulting binary. Perhaps it's something that Nuitka-PGO will be able to find out automatically? Or perhaps it can be forced not to be translated to C but to be included "frozen" if pulled in, like some other modules are.

**Comment by kayhayen** [comment] 2021-12-23 10:36
It sees that the base class from `importlib.abc` has actually code to contribute and is not purely abstract, otherwise I would have suggest to inherit from object instead.

The zipfile module uses it, in what is very unlikely to get used. The `PyZipFile` would be caught to not do it easily with PGO, I think the whole class methods with `self` in there ought to later be removed based on non-instantiation, but we are not there yet. Same for `shutil` and `zipfile`, that will be module level PGO detected. There are however possibilities to use it for programs.

For `pkg_resources`, the goal probably should be to get rid of it at compile time, but I guess it's going to also want to offer a loader for some things. And I think I saw it do it always, not just when necessary.
