### ISSUE TITLE
Inheritance is disordered and does not follow the source code logic (use PySide6)

### ISSUE THREAD

**Issue by needones** [Nuitka/Nuitka#1988] opened 2023-01-09 09:49 UTC
* env~
  nuitka:1.3.3
  full Python: python 3.9.13 with Anaconda, 
  Flavor: CPython Official
  Executable: C:\tools\Anaconda3\envs\visage\python.exe
  OS: Windows
  Arch: x86_64
  WindowsRelease: 10
  Version C compiler: C\tools\Nuitka\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe

* pip~
  addict==2.4.0
altgraph==0.17.3
asteval==0.9.27
async-generator==1.10
attrs==22.1.0
boltons==21.0.0
Brotli==1.0.9
cairocffi==1.4.0
CairoSVG==2.5.2
certifi @ file:///C:/b/abs_ac29jvt43w/croot/certifi_1665076682579/work/certifi
cffi==1.15.1
chardet==3.0.4
charset-normalizer==2.1.1
click==7.1.2
colorama==0.4.5
commonmark==0.9.1
contourpy==1.0.6
cssselect2==0.7.0
cx-Freeze==6.13.1
cx-Logging==3.1.0
cycler @ file:///C:/Users/need/Downloads/cycler-0.11.0-py3-none-any.whl
Cython==0.29.32
defusedxml==0.7.1
dill==0.3.6
exceptiongroup==1.0.0rc9
Flask-SQLAlchemy==2.5.1
fonttools==4.37.4
funcsigs==1.0.2
future==0.18.2
gevent==22.10.2
grade==3.0.1
greenlet==2.0.1
h11==0.14.0
html2text==2020.1.16
html5lib==1.1
iconify==0.0.103
idna==2.10
importlib-metadata==5.0.0
Jinja2==3.1.2
joblib==1.2.0
jsonschema==4.16.0
kids.cache==0.0.7
kiwisolver==1.4.4
libsass==0.21.0
lief==0.12.3
lmfit==1.0.3
loguru==0.6.0
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.2
minio==7.1.12
mongoengine==0.23.1
mpmath==1.2.1
multiprocess==0.70.14
networkx==2.8.7
Nuitka @ file:///C:/%E8%BF%85%E9%9B%B7%E4%B8%8B%E8%BD%BD/Nuitka-1.3.3.tar.gz
numpy==1.19.5
ordered-set==4.1.0
outcome==1.2.0
packaging==21.3
pandas==1.4.4
pdfkit==1.0.0
pefile==2022.5.30
Pillow==9.2.0
pycparser==2.21
pydyf==0.5.0
Pygments==2.13.0
pyhtml2pdf==0.0.5
pyinstaller==5.0
pyinstaller-hooks-contrib==2022.13
pymongo==3.12.3
pyparsing==3.0.9
pyphen==0.13.0
pyrsistent==0.18.1
PySide6==6.4.0.1
PySide6-Addons==6.4.0.1
PySide6-Essentials==6.4.0.1
PySocks==1.7.1
python-dateutil==2.8.2
python-dotenv==0.21.0
pytz==2022.4
PyVISA==1.11.3
pywin32==305
pywin32-ctypes==0.2.0
PyYAML==6.0
pyzmq==24.0.1
QDarkStyle==3.1
qt-material==2.12
QtPy==2.3.0
qtsass==0.3.2
qutip==4.7.0
railroad==0.5.0
requests==2.28.1
rich==12.6.0
scikit-learn==1.0.2
scipy==1.7.3
selenium==4.5.0
shiboken6==6.4.0.1
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
sympy==1.11.1
threadpoolctl==3.1.0
tinyaes==1.0.4
tinycss2==1.1.1
toolz==0.12.0
tqdm==4.64.1
trio==0.22.0
trio-websocket==0.9.2
typing_extensions==4.4.0
uncertainties==3.1.7
urllib3==1.25.11
weasyprint==56.1
webdriver-manager==3.8.3
webencodings==0.5.1
win32-setctime==1.1.0
wincertstore==0.2
wsproto==1.2.0
zipp==3.8.1
zope.event==4.6
zope.interface==5.5.2
zopfli==0.2.1

* after compiling with this command

  nuitka --mingw64 --standalone --show-progress --show-memory "
              "--enable-plugin=pyside6 --nofollow-import-to=numpy,pandas,zmq,cffi,tkinter,"
              "sympy,scipy,minio,yaml,sklearn,jsonschema,pyvisa,lmfit,qutip,loguru,rich,tqdm,networkx,markdown,"
              "pdfkit,requests,pyrsistent,jinja2,urllib3,zopfli,qtpy,qt_material,pytz,PIL,idna,kiwisolver,"
              "dateutil,pyparsing,packaging,email,http,attr,qdarkstyle,typing_extensions,pymongo,mongoengine,"
              "*.tests,*.example,*.examples,*.__pycache__ --include-module=PySide6.QtOpenGL,bson "
              "--windows-icon-from-ico=./package_data/favicon.ico "
              "--output-dir=build2 ./main_gui.py
* run main_gui.exe
  It can be started normally, no exception is thrown, but the execution logic is incorrect.

* example
```
from PySide6.QtCore import QRect, QSize
from PySide6.QtGui import QAction, QIcon
from PySide6.QtWidgets import QMainWindow, QMenu, QMenuBar
from mpl_toolkits import mplot3d, axisartist, axes_grid1
import bson

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 1358, 22))
        self.menubar.setBaseSize(QSize(0, 0))
        self.menuView = QMenu(self.menubar)
        self.menuView.setObjectName(u"menuView")

        self.actionFullScreen = QAction(MainWindow)
        self.actionFullScreen.setObjectName(u"actionFullScreen")
        icon6 = QIcon()
        icon6.addFile(u":/full-screen.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionFullScreen.setIcon(icon6)
        self.menuView.addAction(self.actionFullScreen)
        self.actionFullScreen.triggered.connect(MainWindow.showFullScreen)
        pass


class TitleLayout(QMainWindow):

    def __init__(self, *args, **kwargs):
        self.new_window = None
        super().__init__()

    def close(self):
        if self.new_window:
            if self.new_window.sub_window.__class__.__name__ == "VisageExtension":
                self.new_window.on_WindowClose_clicked()
            else:
                self.new_window.close()
            return True
        return False

    def show(self) -> None:
        if not self.new_window:
            self.new_window = TitleGUI(sub_window=self)
        self.new_window.show()
        self.new_window.activateWindow()

    def showFullScreen(self):
        """full screen"""
        if self.new_window:
            self.new_window.showFullScreen()
            return True
        return False


class TestMainWindow(TitleLayout):
    def __init__(self):
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        super().__init__()
        pass

```
Start the app normally, no exception is thrown. If `show()` is triggered, the page can be displayed normally; If `close()` is triggered, it does not call the close method of the parent class, but calls its own closeEvent method; If `showFullScreen()` is triggered, it does not respond, but it confirms that the parent method is not called. The above problems do not exist in the source code.
So I suspect that nuitka leads to disordered inheritance relationships and does not follow the logic of the source code.

**Comment by kayhayen** [comment] 2023-01-09 10:11
Do you expect your example to do anything? Because I do not, but that might be my ignorance. However a minimal example is only minimal if it demostrates the issue.

**Comment by kayhayen** [comment] 2023-01-09 10:13
Note to self:

> Flavor: CPython Official
> Executable: C:\tools\Anaconda3\envs\visage\python.exe

That is wrong, maybe you installed Anaconda to the system, which makes it accepted as CPython, which of course it is not, but Anaconda it seems.

**Comment by needones** [comment] 2023-01-10 05:44
> 
I try to install a new python environment on a new computer, but it still has this problem

**Comment by needones** [comment] 2023-01-10 05:45
> Do you expect your example to do anything? Because I do not, but that might be my ignorance. However a minimal example is only minimal if it demostrates the issue.



> Do you expect your example to do anything? Because I do not, but that might be my ignorance. However a minimal example is only minimal if it demostrates the issue.

This example just shows the inheritance relationship between them. It uses PySide6 and rewrites some method logic.

**Comment by needones** [comment] 2023-01-16 06:14
I have found the cause of this problem and determined the problem between nuitka and pyside6.    I still need you to conduct further investigation.   I write a complete reproducible demo of the problem.

demo.py
```
# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'title_window_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.3.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################
import sys
from abc import abstractmethod

from PySide6 import QtGui
from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
                            QMetaObject, QObject, QPoint, QRect,
                            QSize, QTime, QUrl, Qt, Slot)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient, QCursor,
                           QFont, QFontDatabase, QGradient, QIcon,
                           QImage, QKeySequence, QLinearGradient, QPainter,
                           QPalette, QPixmap, QRadialGradient, QTransform, QEnterEvent, QPaintEvent, QMouseEvent)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QLabel,
                               QPushButton, QSizePolicy, QSpacerItem, QWidget, QMainWindow, QMenu, QMenuBar,
                               QSizePolicy, QTabWidget, QToolBar, QStatusBar, QLineEdit, QVBoxLayout, QMessageBox)


class Ui_TitleWindow(object):
    def setupUi(self, TitleWindow):
        if not TitleWindow.objectName():
            TitleWindow.setObjectName(u"TitleWindow")
        TitleWindow.resize(780, 347)
        TitleWindow.setStyleSheet(u"")
        self.gridLayoutTitle = QGridLayout(TitleWindow)
        self.gridLayoutTitle.setSpacing(0)
        self.gridLayoutTitle.setObjectName(u"gridLayoutTitle")
        self.gridLayoutTitle.setContentsMargins(2, 2, 2, 2)
        self.TitleWidget = QWidget(TitleWindow)
        self.TitleWidget.setObjectName(u"TitleWidget")
        self.TitleWidget.setEnabled(True)
        self.TitleWidget.setMaximumSize(QSize(16777215, 50))
        self.TitleWidget.setCursor(QCursor(Qt.ArrowCursor))
        self.TitleWidget.setStyleSheet(u"")
        self.TitleWidget.setInputMethodHints(Qt.ImhNone)
        self.horizontalLayoutTitle = QHBoxLayout(self.TitleWidget)
        self.horizontalLayoutTitle.setSpacing(5)
        self.horizontalLayoutTitle.setObjectName(u"horizontalLayoutTitle")
        self.horizontalLayoutTitle.setContentsMargins(5, 5, 5, 5)
        self.IconLabel = QLabel(self.TitleWidget)
        self.IconLabel.setObjectName(u"IconLabel")
        self.IconLabel.setMinimumSize(QSize(20, 20))
        self.IconLabel.setMaximumSize(QSize(20, 20))
        self.IconLabel.setTextFormat(Qt.AutoText)
        # self.IconLabel.setPixmap(QPixmap(u":/login-logo.png"))
        self.IconLabel.setScaledContents(True)
        self.IconLabel.setWordWrap(False)
        self.IconLabel.setOpenExternalLinks(True)
        self.IconLabel.setTextInteractionFlags(Qt.NoTextInteraction)

        self.horizontalLayoutTitle.addWidget(self.IconLabel)

        self.TitleLabel = QLabel(self.TitleWidget)
        self.TitleLabel.setObjectName(u"TitleLabel")
        self.TitleLabel.setTextFormat(Qt.AutoText)

        self.horizontalLayoutTitle.addWidget(self.TitleLabel)

        self.horizontalSpacer_3 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.horizontalLayoutTitle.addItem(self.horizontalSpacer_3)

        self.WindowMin = QPushButton(self.TitleWidget)
        self.WindowMin.setText("min")
        self.WindowMin.setObjectName(u"WindowMin")
        self.WindowMin.setMinimumSize(QSize(35, 20))
        self.WindowMin.setMaximumSize(QSize(35, 20))
        self.WindowMin.setCursor(QCursor(Qt.PointingHandCursor))
        # self.WindowMin.setIconSize(QSize(10, 10))
        self.WindowMin.setAutoDefault(True)


        self.horizontalLayoutTitle.addWidget(self.WindowMin)

        self.WindowMax = QPushButton(self.TitleWidget)
        self.WindowMax.setText("max")
        self.WindowMax.setObjectName(u"WindowMax")
        self.WindowMax.setMinimumSize(QSize(35, 20))
        self.WindowMax.setMaximumSize(QSize(35, 20))
        self.WindowMax.setCursor(QCursor(Qt.PointingHandCursor))

        icon = QIcon()
        iconThemeName = u"1"
        if QIcon.hasThemeIcon(iconThemeName):
            icon = QIcon.fromTheme(iconThemeName)
        else:
            icon.addFile(u".", QSize(), QIcon.Normal, QIcon.Off)

        self.WindowMax.setIcon(icon)

        self.horizontalLayoutTitle.addWidget(self.WindowMax)

        self.WindowClose = QPushButton(self.TitleWidget)
        self.WindowClose.setObjectName(u"WindowClose")
        self.WindowClose.setMinimumSize(QSize(35, 20))
        self.WindowClose.setMaximumSize(QSize(35, 20))
        self.WindowClose.setCursor(QCursor(Qt.PointingHandCursor))
        self.WindowClose.setText("close01")

        self.horizontalLayoutTitle.addWidget(self.WindowClose)

        self.horizontalLayoutTitle.setStretch(0, 1)
        self.horizontalLayoutTitle.setStretch(1, 3)
        self.horizontalLayoutTitle.setStretch(2, 5)
        self.horizontalLayoutTitle.setStretch(3, 1)
        self.horizontalLayoutTitle.setStretch(4, 1)
        self.horizontalLayoutTitle.setStretch(5, 1)

        self.gridLayoutTitle.addWidget(self.TitleWidget, 0, 0, 1, 1)

        self.RealWidget = QWidget(TitleWindow)
        self.RealWidget.setObjectName(u"RealWidget")
        self.RealWidget.setEnabled(True)
        self.RealWidget.setMinimumSize(QSize(35, 30))

        self.gridLayoutTitle.addWidget(self.RealWidget, 1, 0, 1, 1)

        self.retranslateUi(TitleWindow)

        QMetaObject.connectSlotsByName(TitleWindow)

    # setupUi

    def retranslateUi(self, TitleWindow):
        TitleWindow.setWindowTitle(QCoreApplication.translate("TitleWindow", u"Demo-001", None))
        self.TitleLabel.setText(QCoreApplication.translate("TitleWindow", u"Test inheritance with PySide6", None))
        # if QT_CONFIG(tooltip)
        self.WindowMin.setToolTip(QCoreApplication.translate("TitleWindow", u"min", None))
        # endif // QT_CONFIG(tooltip)
        # if QT_CONFIG(tooltip)
        self.WindowMax.setToolTip(QCoreApplication.translate("TitleWindow", u"max", None))
        # endif // QT_CONFIG(tooltip)
        # if QT_CONFIG(tooltip)
        self.WindowClose.setToolTip(QCoreApplication.translate("TitleWindow", u"close", None))
        # endif // QT_CONFIG(tooltip)
        self.WindowClose.setText(QCoreApplication.translate("TitleWindow", u"close", None))
        self.WindowMin.setText(QCoreApplication.translate("TitleWindow", u"min", None))
        self.WindowMax.setText(QCoreApplication.translate("TitleWindow", u"max", None))
    # retranslateUi


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(779, 586)
        self.actionClose_window = QAction(MainWindow)
        self.actionClose_window.setObjectName(u"actionClose_window")
        self.actionFull_Screen = QAction(MainWindow)
        self.actionFull_Screen.setObjectName(u"actionFull_Screen")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.widget = QWidget(self.centralwidget)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(0, 0, 234, 44))
        self.horizontalLayout_2 = QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.pushButton = QPushButton(self.widget)
        self.pushButton.setObjectName(u"pushButton")

        self.horizontalLayout.addWidget(self.pushButton)

        self.lineEdit = QLineEdit(self.widget)
        self.lineEdit.setObjectName(u"lineEdit")

        self.horizontalLayout.addWidget(self.lineEdit)

        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 779, 22))
        self.menuDevice = QMenu(self.menubar)
        self.menuDevice.setObjectName(u"menuDevice")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuDevice.menuAction())
        self.menuDevice.addAction(self.actionClose_window)
        self.menuDevice.addAction(self.actionFull_Screen)
        self.menuDevice.addSeparator()

        self.retranslateUi(MainWindow)
        self.actionClose_window.triggered.connect(MainWindow.close)
        self.actionFull_Screen.triggered.connect(MainWindow.showFullScreen)

        QMetaObject.connectSlotsByName(MainWindow)

    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionClose_window.setText(QCoreApplication.translate("MainWindow", u"Close window", None))
        self.actionFull_Screen.setText(QCoreApplication.translate("MainWindow", u"Full Screen", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"PushButton", None))
        self.menuDevice.setTitle(QCoreApplication.translate("MainWindow", u"Device", None))
    # retranslateUi


# endif // QT_CONFIG(whatsthis)
# retranslateUi

class TitleGUI(QWidget):
    sub_windows = []
    main_window = []

    def __init__(self, sub_window=None, icon_path=None, title=None, parent=None):
        super().__init__(parent)
        self._ui = Ui_TitleWindow()
        self._ui.setupUi(self)
        self.setWindowFlags(Qt.FramelessWindowHint)  # Remove the border of window
        self.icon_path = icon_path
        self.title = title
        self.icon_and_title()
        self.setMouseTracking(True)  # Set widget mouse tracking
        self._ui.TitleWidget.installEventFilter(self)  # Initializes the event filter
        self._ui.RealWidget.installEventFilter(self)
        self.setWindowFlags(Qt.Window | Qt.FramelessWindowHint | Qt.WindowSystemMenuHint | Qt.WindowMinimizeButtonHint)

        if sub_window:
            self.sub_window = sub_window
            self.resize(self.sub_window.width(), self.sub_window.height() + self._ui.TitleWidget.height())
            self.insert_widget()
        if self.sub_window.__class__.__name__ not in ["MainWindow"]:
            TitleGUI.sub_windows.append(self)
        else:
            TitleGUI.main_window.append(self)

    @property
    def is_resize(self):
        return self.m_bResizeable

    @is_resize.setter
    def is_resize(self, option: bool):
        self.m_bResizeable = option

    def insert_widget(self):
        # Initialize and create a vertical layout, QVBoxLayout
        self.main_vBoxLayout = QVBoxLayout(self._ui.RealWidget)
        self.main_vBoxLayout.setSpacing(0)
        self.main_vBoxLayout.setObjectName("RealWidgetBoxLayout")
        # self.main_vBoxLayout.setAlignment(QtCore.Qt.Alignment)
        self._ui.RealWidget.setLayout(self.main_vBoxLayout)
        self.main_vBoxLayout.addWidget(self.sub_window)  # add sub widget

    def icon_and_title(self):
        self._ui.IconLabel.setAlignment(Qt.AlignCenter)
        if self.icon_path:
            self._ui.IconLabel.setPixmap(QPixmap(self.icon_path))
            self._ui.TitleLabel.setScaledContents(True)
        if self.title:
            self._ui.TitleLabel.setText(self.title)

    @Slot()
    def on_WindowMin_clicked(self):
        # minimization of window
        self.showMinimized()

    @Slot()
    def on_WindowMax_clicked(self):
        # Maximization and recovery
        if self.isMaximized():
            self.showNormal()
            self._ui.WindowMax.setToolTip("<html><head/><body><p>max</p></body></html>")
        else:
            self.showMaximized()
            self._ui.WindowMax.setToolTip("<html><head/><body><p>recover</p></body></html>")

    @staticmethod
    def close_sub_windows():
        for window in TitleGUI.sub_windows:
            window.close()

    @Slot()
    def on_WindowClose_clicked(self):
        # close window and process
        if self.sub_window.__class__.__name__ == "MainWindow":
            self.sub_window.closeEvent(QtGui.QCloseEvent)
            if self.sub_window.close_status:
                self.close_sub_windows()
                for win in TitleGUI.main_window:
                    if win != self:
                        win.close()
                self.close()
        else:
            self.close()


class TitleWindow(QMainWindow):

    def __init__(self, *args, **kwargs):
        super().__init__()
        self.new_window = None

    def close(self):
        if self.new_window:
            if self.new_window.sub_window.__class__.__name__ == "MainWindow":
                self.new_window.on_WindowClose_clicked()
            else:
                self.new_window.close()
            return True
        return False

    def hide(self):
        if self.new_window:
            self.new_window.hide()

    def show(self) -> None:
        if not self.new_window:
            self.new_window = TitleGUI(sub_window=self)
            self.new_window._ui.TitleLabel.setText(self.windowTitle())
        self.new_window.show()
        self.new_window.activateWindow()

    def isMinimized(self):
        if self.new_window:
            return self.new_window.isMinimized()

    def showNormal(self):
        if self.new_window:
            return self.new_window.showNormal()

    def activateWindow(self):
        if self.new_window:
            return self.new_window.activateWindow()

    def showFullScreen(self):
        """full screen"""
        if self.new_window:
            self.new_window.showMaximized()
            return True
        return False

    def keyPressEvent(self, event: QtGui.QKeyEvent):
        """Esc to exit full screen."""
        key = event.key()
        if key == int(Qt.Key_Escape):
            if self.new_window:
                self.new_window.showNormal()
                return True
        return False

    def ask_ok(self, msg: str, title: str = None):
        title = title or 'PyQCat: Quantum Chip Calibration'
        reply = QMessageBox().question(
            self, title, msg,
            QMessageBox.Yes | QMessageBox.No | QMessageBox.Cancel
        )
        if reply == QMessageBox.Yes:
            return True


class MainWindow(TitleWindow):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._ui = Ui_MainWindow()
        self._ui.setupUi(self)
        self.close_status = False

    def closeEvent(self, event):
        """whenever a window is closed.

        Passed an event which we can choose to accept or reject.
        """

        will_close = self.ok_to_close()
        if will_close:
            self.close_status = True
        else:
            event.ignore()

    def ok_to_close(self):
        """Determine if it is ok to continue.

        Returns:
            bool: True to continue, False otherwise
        """
        reply = QMessageBox.question(
            self, "Demo", "Save unsaved changes to system?",
            QMessageBox.Yes | QMessageBox.No | QMessageBox.Cancel)

        if reply == QMessageBox.Cancel:
            return False
        elif reply == QMessageBox.Yes:
            pass

        return True


if __name__ == '__main__':
    app = QApplication(sys.argv)
    win = MainWindow()

    win.show()

    sys.exit(app.exec())

```
* pip ~
```
Nuitka==1.3.7
orderedset==2.0.3
PySide6==6.4.0
PySide6-Addons==6.4.0
PySide6-Essentials==6.4.0
shiboken6==6.4.0
wincertstore==0.2
```
* Version C compiler
` C\tools\Nuitka\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe`
* compiling with this command
```
nuitka --mingw64 --standalone --show-progress --show-memory --enable-plugin=pyside6 --nofollow-import-to=http,email,http,attr --include-module=PySide6.QtOpenGL --output-
dir=build2 ./demo.py
```
* Demo description
Focus on the top left corner of the page after executing the script, `Device -> Close window -> yes `  and  `Device -> Full Screen`. Run source code, these two functions are normal.  Running the compiled demo.exe will disable both functions.
**Slot function correspondence**
"Close window" -> `self.actionClose_window.triggered.connect(MainWindow.close)`  ->  `def close(self):`
"Full Screen"  ->  `self.actionFull_Screen.triggered.connect(MainWindow.showFullScreen)`   ->  `def showFullScreen(self):`
* solve this problem
**Change function name**
`self.actionClose_window.triggered.connect(MainWindow.close2)`  ->  `def close2(self):`
`self.actionFull_Screen.triggered.connect(MainWindow.showFullScreen2)`   ->  `def showFullScreen2(self):`

after change it, and run source code or the compiled demo.exe,  It has none of the problems described above.
So I suspect nuitka doesn't have the proper transformation inheritance, maybe just doesn't handle pyside6's inheritance properly.

**Comment by kayhayen** [comment] 2023-01-16 09:44
I think this is then a duplicate. Somehow the slots are ignored if they are overloading a base class method. This is a PySide6 bug, that we will have to investigate indeed. I think your demo is great, thanks for providing it. It would be great if Nuitka at least was aware of the issue. These names are easy to pick, and impossible to know.

My suspect is that the signature doesn't match with the base method or something. I will get in touch with Qt company about this.

**Comment by kayhayen** [comment] 2023-03-14 12:47
Did not have the time to look into this, however it seems 6.5 of PySide contains fixes that will help address this.

**Comment by needones** [comment] 2023-04-10 02:33
Thanks for your help, I used version 6.5.0 to run this demo and still have the bugs mentioned above.  I also had multiple inheritance issues with my project code after the upgrade (unrelated to nutika).  I will feedback the pyside6 official, thank you all the same.

**Comment by kayhayen** [comment] 2023-11-14 11:15
This "demo.py" issue even an issue with PySide6.6 which I just confirmed. These name collisions are not properly resolved by PySide6. We should boil this down further to a minimal example and report it to them. If somebody were to produce that, it would be great. Also if somebody identified the duplicates, and reference them here, that would also be helpful, probably there is more minimal code in there already. It shouldn't have to involve a window, I assume a timer on a slot of some object would be good enough already to demonstrate it.

**Comment by KevinRodriguez777** [comment] 2024-03-22 06:24
This works correctly nowadays

**Closed by KevinRodriguez777** 2024-03-22 06:24 UTC
Labels: bug, duplicate, help wanted
