### ISSUE TITLE
matplotlib.backends.backend_tkagg  is not work

### ISSUE THREAD

**Issue by stgfeng** [Nuitka/Nuitka#884] opened 2020-11-18 02:22 UTC
Build OK,  but runtime error。
similar to: [https://github.com//issues/598]
### TraceBack
```
Missing colon in file WindowsPath('C:/work/python/LINEAR~1/build/LINEAR~1.DIS/matplotlib/mpl-data/matplotlibrc'), line 1 (" modified by Nuitka plugin 'numpy'")
Traceback (most recent call last):
  File "C:\work\python\LINEAR~1\build\LINEAR~1.DIS\LinearityMeasure.pyw", line 139, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\work\python\LINEAR~1\build\LINEAR~1.DIS\matplotlib\__init__.py", line 926, in <module matplotlib>
  File "C:\work\python\LINEAR~1\build\LINEAR~1.DIS\matplotlib\__init__.py", line 929, in <dictcontraction>
  File "C:\work\python\LINEAR~1\build\LINEAR~1.DIS\matplotlib\__init__.py", line 708, in __getitem__
KeyError: 'backend_fallback'
```

### Build environment
> nuitka 0.6.9.6
Python: 3.7.7 (default, May  6 2020, 11:43:10) [MSC v.1916 32 bit (Intel)]
Executable: C:\Users\Administrator\miniconda3\python.exe
OS: Windows
Arch: x86
gcc version 8.1.0 (i686-win32-sjlj-rev0, Built by MinGW-W64 project)

### Compiling with:
>nuitka --assume-yes-for-downloads^
	--mingw64^
	--recurse-all^
	--standalone^
	--show-progress^
	--show-scons^
	--plugin-enable=tk-inter^
	--plugin-enable=numpy^ 
	--recurse-not-to=jinja2,sip,Ipython,cx_Freeze,h5py,nose^
	--include-plugin-directory=%~dp0..\Common^
	--windows-icon=%~dp0..\image\stats_lines.ico^
	--output-dir=build^
	LinearityMeasure.pyw

**Comment by kayhayen** [comment] 2020-11-18 11:40
Are you saying, the comments that the plugin adds, are causing the file to be unreadable? How are comments to look like in this file?

**Comment by kayhayen** [comment] 2020-11-21 08:52
Ok, I managed to reproduce it. Seem matplotlib 3 has done changes in the input file, but this may also be a bug in the parsing code of matplotlib. I need to check what it does that.

**Comment by kayhayen** [comment] 2020-11-21 12:56
So, it seems that the config file format has changed, and what we put there as default parameters, is now used in actual code, with the comment sign removed, and expected to be all comments, so it uses those. How ridicoulous that is.

Copying the matplotlib file unchanged, I get to #883 which is reproduced now too. It might be a consequence of not having all backends available in the standalone, but I am not sure of that. I will first want to achieve the correct handling of the config file of course, to exclude that possibility.

**Comment by kayhayen** [comment] 2020-11-21 13:09
Ok, it seems the backend is set to something, so I only add the detection of matplotlib3 and preserve comments in that case. That should give the correct config file, i.e. it's practically the original one.

**Comment by kayhayen** [comment] 2020-12-07 16:42
Released as part of 0.6.10

**Closed by kayhayen** 2020-12-07 16:42 UTC
Labels: bug, develop

**Comment by noonchen** [comment] 2020-12-12 19:14
This issue can still be seen in 0.6.10, but I am using backend_qt5agg.
```
Missing colon in file WindowsPath('W:/STDF~VKM.DIS/matplotlib/mpl-data/matplotlibrc'), line 1 (" modified by Nuitka plugin 'numpy'")
Traceback (most recent call last):
  File "W:\STDF~VKM.DIS\STDF Viewer.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "W:\STDF~VKM.DIS\matplotlib\__init__.py", line 917, in <module matplotlib>
  File "W:\STDF~VKM.DIS\matplotlib\__init__.py", line 920, in <dictcontraction>
  File "W:\STDF~VKM.DIS\matplotlib\__init__.py", line 708, in __getitem__
KeyError: 'backend_fallback'
```

Nuitka version:

> 0.6.10
> Python: 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)]
> Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe
> OS: Windows
> Arch: x86_64

Python & Modules:

> Python 3.8.4
> matplotlib 3.3.2
> PyQt5 5.15.1

**Comment by kayhayen** [comment] 2020-12-13 18:36
The output you are giving is indicative of you not using 0.6.10 as the comment it stumbles over is not in the Nuitka code anymore.

**Comment by noonchen** [comment] 2020-12-13 18:55
Hi kayhayen,

Just to make sure I'm not misunderstood, did you mean this issue is raised because I built the code using a version other than 0.6.10? If that's the case, I'd reinstall the latest nuitka and try again. If you have any other suggestions please share with me, thanks!

**Comment by kayhayen** [comment] 2020-12-13 19:01
Yes, that output is definitely not from a Nuitka 0.6.10 compiled program @noonchen

**Comment by noonchen** [comment] 2020-12-13 19:51
@kayhayen You're right, this issue is not reproduced after reinstalling nuitka, but I encountered another error😂 when I run the executable, I would post the detail in a related issue.
