### ISSUE TITLE
List comprehension fails with segmentation fault

### ISSUE THREAD

**Issue by Aksem** [Nuitka/Nuitka#2243] opened 2023-05-25 06:16 UTC
**Problem:** loop comprehension fails on second iteration of loop in which it is executed with segmentation fault. The same code works well in CPython.

**Nuitka version**(tested 1.5.8, factory, develop on linux, windows, macos) installed via poetry in pyenv environment:

```
1.5.8
Commercial: None
Python: 3.10.10 (main, Mar 01 2023, 21:10:14) [GCC]
Flavor: Unknown
Executable: /home/user/.cache/pypoetry/virtualenvs/nuitka-async-iterator-bug-VeE5b6c1-py3.10/bin/python
OS: Linux
Arch: x86_64
Distribution: Opensuse-Tumbleweed (based on opensuse suse) None
Version C compiler: /usr/bin/gcc (gcc).
```

**Options:**
```
--clang \
--standalone \
--assume-yes-for-downloads \
--plugin-enable=pylint-warnings \
--warn-unusual-code \
--warn-implicit-exceptions \
--show-memory \
--show-modules \
```

**Minimal example:**
```python
for changes in (((1, 'path11'),), ((2, 'path2'),), ((2, 'path3'),)):
        print('Iteration', changes)
        filtered_items = set(
            [
                change
                for change in changes
                if any(
                    change[1].endswith(suffix)
                    for suffix in [".txt", ".toml"]
                )
            ]
        )
```

Full example: [repository with code and CI](https://github.com/Aksem/nuitka_async_iterator_bug/blob/master/nuitka_async_iterator_bug/main.py)

Execution of code from repository with `--trace-execution` ends with:
```
Iteration ((2, 'path2'),)
Execute: nuitka_async_iterator_bug/main.py:4 <Node 'STATEMENT_ASSIGNMENT_VARIABLE_GENERIC' with {'variable_name': 'filtered_items', 'is_temp': False, 'var_type': 'object', 'owner': '__main__'}>
Execute: nuitka_async_iterator_bug/main.py:5 <Node 'STATEMENT_TRY' with {'aborting': True}>
Execute: nuitka_async_iterator_bug/main.py:5 <Node 'STATEMENT_ASSIGNMENT_VARIABLE_GENERIC' with {'variable_name': 'listcomp_1__.0', 'is_temp': True, 'var_type': 'object', 'owner': '__main__'}>
Execute: nuitka_async_iterator_bug/main.py:5 <Node 'STATEMENT_ASSIGNMENT_VARIABLE_CONSTANT_MUTABLE' with {'variable_name': 'listcomp_1__contraction', 'is_temp': True, 'var_type': 'object', 'owner': '__main__'}>
Execute: nuitka_async_iterator_bug/main.py:5 <Node 'STATEMENTS_FRAME_FUNCTION' with {'co_name': '<listcomp>', 'co_kind': 'Function', 'co_varnames': 'change', 'co_freevars': '', 'co_argcount': 1, 'co_posonlyargcount': 0, 'co_kwonlyargcount': 0, 'co_has_starlist': False, 'co_has_stardict': False, 'co_filename': 'main.py', 'co_lineno': 5, 'co_new_locals': True, 'co_is_optimized': False, 'code_flags': ''}>
Execute: nuitka_async_iterator_bug/main.py:5 <Node 'STATEMENT_TRY' with {'aborting': True}>
Execute: nuitka_async_iterator_bug/main.py:5 <Node 'STATEMENT_LOOP'>
Execute: nuitka_async_iterator_bug/main.py:5 <Node 'STATEMENT_TRY' with {'aborting': False}>
Execute: nuitka_async_iterator_bug/main.py:5 <Node 'STATEMENT_ASSIGNMENT_VARIABLE_FROM_TEMP_VARIABLE' with {'variable_name': 'change', 'is_temp': False, 'var_type': 'object', 'owner': '__main__$$$outline__1_listcomp'}>
Segmentation fault (core dumped)
```

**Comment by kayhayen** [comment] 2023-05-27 15:49
Thanks for updating this further, I will look into this.

**Comment by kayhayen** [comment] 2023-06-19 19:41
Duplicate of #1178

**Comment by kayhayen** [comment] 2023-06-19 19:42
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Closed** 2023-06-20 13:28 UTC
Labels: bug, duplicate, factory, excellent_report
