### ISSUE TITLE
Nutika not working with Polars Error : No module named numpy.core.multiarray

### ISSUE THREAD

**Issue by rodyrahi** [Nuitka/Nuitka#3140] opened 2024-10-03 07:18 UTC
hi there ,
I am getting this issue "No module named numpy.core.multiarray" when i am trying to compile polars application 

> nuitka --enable-plugin=pyqt6 --standalone --windows-icon-from-ico=icon.ico test_gui.py

![Screenshot 2024-10-03 123724](https://github.com/user-attachments/assets/b2ca6b40-f657-4019-860d-fc1d7759e528)

This the code
```
import sys
import numpy as np
import polars as pl
from PyQt6.QtWidgets import QApplication, QMainWindow, QTableView, QVBoxLayout, QWidget
from PyQt6.QtCore import Qt, QAbstractTableModel
import traceback

class PolarsTableModel(QAbstractTableModel):
    def __init__(self, data):
        super().__init__()
        self._data = data

    def rowCount(self, parent=None):
        return len(self._data)

    def columnCount(self, parent=None):
        return len(self._data.columns)

    def data(self, index, role=Qt.ItemDataRole.DisplayRole):
        if role == Qt.ItemDataRole.DisplayRole:
            # Accessing data properly with Polars
            return str(self._data.row(index.row())[index.column()])
        return None

    def headerData(self, section, orientation, role=Qt.ItemDataRole.DisplayRole):
        if role == Qt.ItemDataRole.DisplayRole:
            if orientation == Qt.Orientation.Horizontal:
                return str(self._data.columns[section])
            if orientation == Qt.Orientation.Vertical:
                return str(section + 1)
        return None

class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.setWindowTitle("Polars and NumPy Data Viewer")
        self.setGeometry(100, 100, 600, 400)


        try:

            np_data = np.random.rand(10, 5)
            columns = ['A', 'B', 'C', 'D', 'E']
            pl_data = pl.DataFrame({col: np_data[:, i] for i, col in enumerate(columns)})
        except Exception as e:
            log_error_to_file(f"Error creating Polars DataFrame: {str(e)}")
            pl_data = pl.DataFrame()  # Fallback to an empty DataFrame

        # Create table view
        table_view = QTableView()
        model = PolarsTableModel(pl_data)
        table_view.setModel(model)

        # Set up layout
        layout = QVBoxLayout()
        layout.addWidget(table_view)

        container = QWidget()
        container.setLayout(layout)
        self.setCentralWidget(container)

def log_error_to_file(error_message):
    """Logs error messages to a file."""
    with open('error_log.txt', 'a') as error_file:
        error_file.write(f"{error_message}\n")




if __name__ == "__main__":
    try:
        app = QApplication(sys.argv)
        window = MainWindow()
        window.show()

        app.exec()
        pass
    except Exception as e:
        print("An error occurred:", str(e))
        print(traceback.format_exc())
        input("Press Enter to exit...")  
```

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

    2.4.8
    Commercial: None
    Python: 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
    Flavor: Anaconda Python
    Executable: f:\pivott\pivott\.conda\python.exe
    OS: Windows
    Arch: x86_64
    WindowsRelease: 10

  > python -m pip list -v

  Package              Version
  -------------------- -------
  cachetools           5.3.3  
  gast                 0.4.0  
  google-auth          2.30.0 
  google-auth-oauthlib 1.0.0  
  keras                2.13.1 
  Nuitka               2.4.8  
  numpy                2.1.1  
  ordered-set          4.1.0  
  pip                  24.2   
  polars               1.9.0  
  pyasn1_modules       0.4.0  
  PyQt6                6.7.1  
  PyQt6-Qt6            6.7.3  
  PyQt6_sip            13.8.0 
  requests-oauthlib    2.0.0  
  rsa                  4.9    
  setuptools           75.1.0 
  tensorboard          2.13.0 
  tensorflow           2.13.1
  tensorflow-intel     2.13.1
  wheel                0.44.0
  zstandard            0.23.0

**Comment by kayhayen** [comment] 2024-10-03 11:37
I was first assuming, it's maybe newer numpy, but that seems fine. The traceback you gave and the source code do not align, probably a hidden dependency of polars then.

**Comment by kayhayen** [comment] 2024-10-03 11:41
And also the code is missing an `import sys` at least and doesn't run.

**Comment by rodyrahi** [comment] 2024-10-03 11:42
i do not get any error my i run it directly from vscode but after i create a standalone exe it's giving me numpy.core.multiarray module not named error can you please try it

**Comment by rodyrahi** [comment] 2024-10-03 11:44
> And also the code is missing an `import sys` at least and doesn't run.

sorry for the code its actually my mistake while copy pasting the code

**Comment by kayhayen** [comment] 2024-10-03 11:46
So, I reproduced the error after fixing it. It seems some garbage rust package has hidden dependencies on numpy parts, I will be able to add them I guess.

**Comment by rodyrahi** [comment] 2024-10-03 11:48
> So, I reproduced the error after fixing it. It seems some garbage rust package has hidden dependencies on numpy parts, I will be able to add them I guess.

thank you @kayhayen please do it will help me out a lot

**Comment by rodyrahi** [comment] 2024-10-04 04:38
@kayhayen any updates?

**Comment by kayhayen** [comment] 2024-10-04 09:24
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by rodyrahi** [comment] 2024-10-04 09:49
@kayhayen still giving me same error 

![image](https://github.com/user-attachments/assets/078afd1e-12e5-491c-a9a0-8af28143abb2)

> nuitka --version
2.5rc6
Commercial: None
Python: 3.10.14 | packaged by Anaconda, Inc. | (main, May  6 2024, 19:44:50) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: c:\Users\Raj\Desktop\polars_test\.conda\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).

**Comment by kayhayen** [comment] 2024-10-07 10:01
Given that your reproducer worked for me, I am hoping this is because you didn't properly follow instructions how to update Nuitka from factory. Make sure it contains this part:

```
- module-name: 'polars' # checksum: d072aa03
  implicit-imports:
    - depends:
        - 'numpy.core.multiarray'
```

in its yaml configuration, and then report back if that didn't help. I might have also forgotten to push, but it ought to be there now.

**Comment by rodyrahi** [comment] 2024-10-07 17:23
@kayhayen thanks it worked for me after i changed yml file 👍

**Comment by kayhayen** [comment] 2024-10-14 07:37
Part of the 2.4.9 release.

**Closed by kayhayen** 2024-10-14 07:37 UTC
Labels: bug, factory, excellent_report
