### ISSUE TITLE
Very weird bug relating to Redis?

### ISSUE THREAD

**Issue by smathieson** [Nuitka/Nuitka#3212] opened 2024-11-21 01:50 UTC
Hello.

I seem to have found a "weird" bug with Nuitka.

In order to reproduce all that is needed is a redis server.

This compiles correctly up to Nuitka 2.4.11, fails on 2.5 and above (python 3.11.2).
`python3 -m nuitka example.py`

Working code:
```
#!/usr/bin/env python3.11
import asyncio
from redis.asyncio.client import Redis as AsyncRedis

async def start():
    async with AsyncRedis.from_url("redis://localhost:6379/0") as conn:
        async with conn.pubsub() as pubsub:
            await pubsub.subscribe("fileManager")
            while True:
                await pubsub.get_message(timeout=1)

asyncio.run(start())
```

This code fails:
```
#!/usr/bin/env python3.11
import asyncio
from redis.asyncio.client import Redis as AsyncRedis

async def get_pubsub_message(pubsub):
    await pubsub.get_message(timeout=1)

async def start():
    async with AsyncRedis.from_url("redis://localhost:6379/0") as conn:
        async with conn.pubsub() as pubsub:
            await pubsub.subscribe("fileManager")
            while True:
                await get_pubsub_message(pubsub)

asyncio.run(start())
```

Both are almost identical, but for some reason it fails with "Nuitka_PyGen_FetchStopIterationValue: Assertion `HAS_ERROR_OCCURRED(tstate)' failed."

It is worth noting perhaps that the sync equivalent seems to work:
```
#!/usr/bin/env python3.11
from redis.client import Redis

def get_pubsub_message(pubsub):
    pubsub.get_message(timeout=1)

def start():
    with Redis.from_url("redis://localhost:6379/0") as conn:
        with conn.pubsub() as pubsub:
            pubsub.subscribe("any")
            while True:
                get_pubsub_message(pubsub)

start()
```

Thanks for all the work on Nuitka!

**Comment by kayhayen** [comment] 2024-11-21 09:28
This is a duplicate of #3211 that is already fixed in factory branch.

**Closed by kayhayen** 2024-11-21 09:28 UTC
Labels: duplicate, factory

**Comment by kayhayen** [comment] 2024-11-24 09:28
Part of the 2.5.2 release I just made.
