### ISSUE TITLE
The --onefile mode ignores --output-dir 

### ISSUE THREAD

**Issue by interseba5** [Nuitka/Nuitka#1878] opened 2022-11-09 13:25 UTC
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command
1.2
Commercial: None
Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

* How did you install Nuitka and Python

Installed using pip

* The specific PyPI names and versions

pip 22.0.4 from c:\python39\lib\site-packages\pip (python 3.9)

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
```Python
print('hello world')
```

* Provide in your issue the Nuitka options used
```
python -m nuitka --onefile --output-filename=test.exe --output-dir=.\bin\Release --remove-output main.py
```
### Explanation
When i build main.py with this options, it simply ignore the specified output dir and create the onefile exe in the current directory.

**Comment by kayhayen** [comment] 2022-11-10 09:37
I totally fail to reproduce this, so much so that I think you are confusing it with a previous compilation result.

**Comment by interseba5** [comment] 2022-11-10 10:17
Sorry i have noticed only now after your comment that i have missed an option in the command use(--output-filename=test.exe). With this option you can reproduce the issue

**Comment by kayhayen** [comment] 2022-11-10 10:51
Well, of course, that is what the option does, it specifies where the onefile binary goes to, so I am not surprised. Question of course then becomes, if your expectation that it should be relative to the output directory. Those code does this:

```
        output_filename = Options.getOutputFilename()

        if Options.isOnefileMode() and output_filename is not None:
            if onefile:
                result = output_filename
            else:
                result = os.path.join(
                    getStandaloneDirectoryPath(),
                    os.path.basename(output_filename),
                )
```

So, output directory is not used at all there, but an `os.path.join` may well make sense, indeed. But for `-o` we also so far allow specifying a directory and even check if it exists. This is still kind of messy. I need to think some about this.

**Comment by kayhayen** [comment] 2022-11-10 10:57
I think I might settle on disallowing `os.path.sep` in `-o` and indeed require giving both options if you wanted to have it in a specific folder. Kind of breaking change, but I guess, that's the only way to keep the sanity, otherwise it will behave differently for the final output of only onefile, which is pretty bad.

**Comment by interseba5** [comment] 2022-11-10 11:02
Thanks for the answer. I think that forcing both option is a good solution also because the --output-filename don't create the folder tree if don't exists. Instead -o does. So if you use both option in this way -o .\bin\Release --output-filename .\bin\Release\test.exe you obtain an error if .\bin\Release dont exists

**Comment by kayhayen** [comment] 2022-11-10 11:14
Yes, I saw that, and it's much more shy there, for what is probably no good reason. The filename option was added later only, and generally in some cases is not even allowed, or changes behavior, and came late to the party. I guess there will be a breaking change then. I will plan it for the next live stream, where I want to do quality of life improvements.

**Comment by kayhayen** [comment] 2023-02-01 15:42
Streams are being delayed probably until march.

**Comment by interseba5** [comment] 2023-02-06 16:24
The 4fb72469 commit have broken the workaround for this issue. In fact before 1.4.3 i simply used `--output-dir=.\bin\Release --output-filename=.\bin\Release\C-Link_PredictiveMaintenance.exe` to obtain the onefile exe in .\bin\Release. But now i obtain this error:
`FATAL: Error, output filename for standalone cannot contain a directory part.`

**Comment by kayhayen** [comment] 2023-02-06 16:45
That is kind of correct, should probably not have been applied for onefile mode. Dang these things are complex.

**Comment by kayhayen** [comment] 2023-02-06 16:47
Although, I think the issue is still the same. Ignoring `--output-dir` seems to be the relevant issue in the first place, going to look at this now, how hard can it be.

**Comment by kayhayen** [comment] 2023-02-06 16:51
So, --output-filename now incluences the name of the standalone binary, which is good, and then the onefile binary is created inside the current folder, which is the original issue.

**Comment by kayhayen** [comment] 2023-02-06 17:23
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-02-06 17:23
I will make it part of the 1.4.4 hotfix release.

**Comment by interseba5** [comment] 2023-02-06 21:05
Tested and worked, thank you very much!

**Comment by kayhayen** [comment] 2023-02-08 12:24
This is part of the hotfix release 1.4.4 that I just made.

**Closed by kayhayen** 2023-02-08 12:24 UTC
Labels: bug, factory
