### ISSUE TITLE
cefpython:  bundle-mode: success,  standalone-mode: error 

### ISSUE THREAD

**Issue by psytron** [Nuitka/Nuitka#536] opened 2019-09-29 05:21 UTC
Running this simple Test Example: 
https://raw.githubusercontent.com/cztomczak/cefpython/master/examples/snippets/javascript_bindings.py

Everything works great without --standalone,  but when I add --standalone it gives below error: 

(venv) psys-MacBook-Pro:ceftester psy$ python --version
Python 3.7.4
(venv) psys-MacBook-Pro:ceftester psy$ python -m nuitka --version
0.6.5
Python: 3.7.4 (default, Sep  7 2019, 18:27:02)
Executable: /Users/psy/1m/apps/ceftester/venv/bin/python
OS: Darwin
Arch: x86_64
(venv) psys-MacBook-Pro:ceftester psy$ ls
blob_storage		main.bin		main.build		main.py			webrtc_event_logs

:::::::WORKING:::::::
(venv) psys-MacBook-Pro:ceftester psy$ python -m nuitka --follow-imports --run main.py

DevTools listening on ws://127.0.0.1:51397/devtools/browser/332d1e6d-1b37-4d0b-9b9e-7ec16cee00ca
Value sent from Javascript: I am a Javascript string #1
Value sent from Javascript: I am a Javascript string #2

:::::::NOT WORKING::::::   ( same command with --standalone )
(venv) psys-MacBook-Pro:ceftester psy$ python -m nuitka --follow-imports --run --standalone main.py
Traceback (most recent call last):
  File "/Users/psy/1m/apps/ceftester/ceftester/main.dist/main.py", line 6, in <module>
  File "/Users/psy/1m/apps/ceftester/ceftester/main.dist/cefpython3/__init__.py", line 62, in <module cefpython3>
ImportError: dlopen(/Users/psy/1m/apps/ceftester/ceftester/main.dist/cefpython3/cefpython_py37.so, 2): Library not loaded: @rpath/Chromium Embedded Framework.framework/Chromium Embedded Framework
  Referenced from: /Users/psy/1m/apps/ceftester/ceftester/main.dist/cefpython3/cefpython_py37.so
  Reason: image not found

**Comment by kayhayen** [comment] 2019-09-30 09:52
Very likely this is better on the develop version.

**Comment by psytron** [comment] 2019-10-01 02:43
Thanks @kayhayen 
I tried dev version and got different error: 

ATTEMPT:  
(venv) psys-MacBook-Pro:ceftester psy$ python -m nuitka --verbose --follow-imports --standalone --run main.py
...
Nuitka:DEBUG:internal:1 : new_statements : Original parameter variable value parameter variable 'bases' is not released.
Nuitka:DEBUG:internal:1 : new_statements : Original parameter variable value parameter variable 'bases' is not released.
Nuitka:DEBUG:main.py:64 : new_statements : Original parameter variable value parameter variable 'self' is not released.
Nuitka:DEBUG:main.py:64 : new_statements : Original parameter variable value parameter variable 'browser' is not released.
Nuitka:DEBUG:main.py:64 : new_statements : Original parameter variable value parameter variable '_' is not released.
Nuitka:DEBUG:main.py:64 : new_statements : Original parameter variable value parameter variable 'self' is not released.
Nuitka:DEBUG:main.py:64 : new_statements : Original parameter variable value parameter variable 'browser' is not released.
Nuitka:DEBUG:main.py:64 : new_statements : Original parameter variable value parameter variable '_' is not released.
Nuitka:DEBUG:main.py:64 : new_statements : Removed useless try, all handlers removed.
[0930/194043.584650:ERROR:icu_util.cc(114)] icudtl.dat not found in bundle
[0930/194043.584727:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.
Trace/BPT trap: 5


(venv) psys-MacBook-Pro:ceftester psy$ pip list
Package    Version
---------- --------
cefpython3 66.0
Nuitka     0.6.6rc7
pip        19.0.3
setuptools 40.8.0
You are using pip version 19.0.3, however version 19.2.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

(venv) psys-MacBook-Pro:ceftester psy$ python --version
Python 3.7.4

**Comment by jayvdb** [comment] 2019-10-01 04:26
@psytron , you might want to try moving/copying the icu data directly beside the standalone exe.  See https://github.com/Nuitka/Nuitka/issues/521

**Comment by psytron** [comment] 2019-10-01 18:45
@jayvdb Thanks for your suggestion. Isn't --standalone flag intended to solve exactly this use case?  so that users of your app can just click without worrying about dependencies ?

**Comment by jayvdb** [comment] 2019-10-02 04:46
@psytron , yes, `--standalone` should do that, but it doesnt at the moment, and #521 and https://github.com/Nuitka/Nuitka/issues/493 and other issues exist about this.  So after compilation, some fiddling with the artifacts is sometimes necessary, if you want to use Nuitka now without fixing all of those outstanding problems ;-).

**Comment by psytron** [comment] 2019-10-02 19:48
Thanks @jaybdb . I see. So if user must fiddle with dependencies after compile that defeats the purpose of using --standalone... Is there a way to pass parameter to Nuitka like --plugin-directory or something so that it will copy and include the dependencies ?

**Comment by psytron** [comment] 2019-10-02 22:49
I also noticed that for non-standalone using "--run" works: 
( python -m nuitka --verbose --follow-imports --run main.py )

But when I click the main app file it produces same error:
[1002/154238.805393:ERROR:icu_util.cc(114)] icudtl.dat not found in bundle

I am not sure why  '--run' works,  but clicking to run app doesn't work. 

Either way  --standalone  is THE killer feature everyone wants. The marvelous ability to create 1 file that just works when users click it :)

**Comment by kayhayen** [comment] 2019-12-27 10:13
@psytron it does create a distribution folder, we need examples with reproducers to enhance it, where it fails. Some of the issues mentioned were fixed in the 0.6.6 release, please retry and provide the output, also, tracing file accesses would be nice, I assume there is an `strace` on macOS? We would need where the file normally lives, and where it is accessed (and not found).

**Comment by kayhayen** [comment] 2019-12-27 10:14
btw, I wish somebody will create proper macOS apps out of those folders one day, seems to be just some tooling needed?

**Comment by kayhayen** [comment] 2020-02-23 08:08
Closing for lack of feedback, without the traces, we don't know what's going on.

**Closed by kayhayen** 2020-02-23 08:08 UTC
Labels: needs_example
