### ISSUE TITLE
[PySide2] QObject.sender() not working

### ISSUE THREAD

**Issue by RESP3CT88** [Nuitka/Nuitka#1021] opened 2021-03-12 11:38 UTC
0.6.13rc6 **(Factory)**
Python: 3.8.5 (default, Jul 28 2020, 12:59:40) 
OS: Linux | Arch: x86_64

QObject.sender() is returning "None" instead of a pointer to the object which sent the signal.

> QObject.sender() returns a pointer to the object that sent the signal, if called in a slot activated by a signal; otherwise it returns nullptr. The pointer is valid only during the execution of the slot that calls this function from this object's thread context.
https://doc.qt.io/qt-5/qobject.html#sender

Minimal Example:
```
import sys
from PySide2.QtWidgets import QApplication
from PySide2.QtCore import Slot, Signal, QProcess, QObject


class Main(QObject):

    def __init__(self):
        QObject.__init__(self)

    def ping(self):
        proc = QProcess(self)
        proc.readyReadStandardOutput.connect(self.ping_read)
        proc.start('ping', ['8.8.8.8', '-c', '4'])

    def ping_read(self):
        proc = self.sender() // <---- "None" is returned by self.sender()
        data = bytearray(proc.readAllStandardOutput()).decode()
        print(data, end='')


if __name__ == "__main__":
    app = QApplication([])
    main = Main()
    main.ping()
    sys.exit(app.exec_())

```

Output:
```
Traceback (most recent call last):
  File "main.py", line 24, in ping_read
    data = bytearray(proc.readAllStandardOutput()).decode()
AttributeError: 'NoneType' object has no attribute 'readAllStandardOutput'
```

Compilation:
```
ubuntu@ubuntu:~/$ sudo python3 -m nuitka --enable-plugin=pyside2 main.py
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.                                           
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 12 C files using ccache.                                                        
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 10
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'disabled': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
Nuitka:INFO: Keeping build directory 'main.build'.
Nuitka:INFO: Successfully created 'main.bin'.
```

**Comment by kayhayen** [comment] 2021-03-16 11:51
I can confirm the issue to be valid and still there with current factory code. 

My PySide knowledge is lacking there. I have no idea, what `self.sender()` could be adversely impacted by. It's not in the example code at all.

**Comment by kayhayen** [comment] 2021-03-16 12:05
There is something fishy going one, it would seem that the only way the `proc` could be available to the PySide2 code there is by checking the call stack bytecode, stack, or method call to find it. I will have to investigate PySide2 code there in order to figure that one out. But I am not hopeful in terms of an easy solution.

**Comment by kayhayen** [comment] 2021-03-16 12:06
This is very much impossible to make it into the 0.6.13 release, sorry about that.

**Comment by kayhayen** [comment] 2021-03-17 09:25
Ok, I am investigating this, and it seems that there is a builtin method object, but Nuitka ends up calling not that as a method call, but the built-in function with a single argument, so definitely incorrectly, there probably is a way to call these. There is an optimization not done, when call arguments have side effects, because of a reordering of code.

```
a.something_with_side_effect(another_side_effect())
```

In our case, the lookup of `connect` is not known to not have a side effect, esp. not on another attribute of the proc object, so that explains it. However, the bound objects should be good enough.

In these cases, we have to do the calling manual. But I think the `self` of the method object should get passed and be correct, so it's still not explained, and I actually verified that. Also even if I wrap all functions, including the ping ones, they become proper method objects as an argument, and should allow the lookup, so this must be a case of `sender` using something else.

**Comment by RESP3CT88** [comment] 2021-03-17 16:54
Good investigation @kayhayen. This would be great to have working. My project uses QProcess quite heavily and having a pointer to the sender's object really cleans up my code.

**Comment by kayhayen** [comment] 2021-03-22 12:42
I have been working on PySide for the past 2.5 days and produced this: https://bugreports.qt.io/browse/PYSIDE-1523

With that patch set, your test case is working.

**Comment by kayhayen** [comment] 2021-03-22 12:43
This is however delayed by them merging the patches, or me providing wheels with it included, which I would if the release with it doesn't happen.

**Comment by RESP3CT88** [comment] 2021-03-22 17:19
@kayhayen That's great! Thank you for those patches, I appreciate the time you spent on this. Hopefully they will merge your patches soon.

**Comment by kayhayen** [comment] 2023-07-10 08:19
So, in PySide6 this is merged, and PySide2 there is this: https://nuitka.net/pages/pyside2.html

**Closed by kayhayen** 2023-07-10 08:19 UTC
Labels: bug, delayed
