### ISSUE TITLE
torch.jit.save fail in runtime

### ISSUE THREAD

**Issue by ys9617** [Nuitka/Nuitka#2235] opened 2023-05-20 04:11 UTC
**Environment:**
  Nuitka: 1.5.7
  Python: 3.9.13
  OS: Windows
  Arch: x86_64
  WindowsRelease: 10

**sample code:**
```
import torch
import torch.nn as nn

class MyModel(nn.Module):
    # Define your model here
    pass

model = MyModel()  # Assuming you have a model instance

traced_model = torch.jit.trace(model, torch.zeros(1, 3, 224, 224))  # Trace the model

torch.jit.save(traced_model, 'model.pt')
```

**Error**
`AttributeError: 'MyModel' object has no attribute 'save'
`

**Nuitka command:**
`nuitka --standalone --mingw64 --follow-imports app.py`

Nuitka compile works but if i run torch.jit.save it shows above error. How can i solve it?

**Comment by kayhayen** [comment] 2023-05-21 18:19
Duplicate of #2189

**Closed by kayhayen** 2023-05-21 18:19 UTC
