### ISSUE TITLE
Compilation Error When Using Newest Version of Nuitka for IPython

### ISSUE THREAD

**Issue by thesct22** [Nuitka/Nuitka#2015] opened 2023-01-27 03:48 UTC
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
1.4
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Soultion-Applications\test\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl.exe (cl 14.2).
```

* How did you install Nuitka and Python

Tried the latest version of stable and factory version of nuitka. Installed using pip in a venv.

* The specific PyPI names and versions

Did a "pip install IPython" inside venv

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
import IPython

print(IPython.sys_info())
print(IPython.__version__)

```

* Provide in your issue the Nuitka options used

Works fine for Nuitka==1.3.8

Does not work for 1.4 or factory version.

```
nuitka --standalone .\test_IP.py
```

```
Nuitka-Options:INFO: Used command line options: --standalone .\test_IP.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.4' on Python '3.8' commercial grade 'not installed'.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'IPython' at '.\test_IP.py:1' encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
PASS 1: 46.2%|███████████▌             | 319/691, IPython.core.magics.scriptProblem with statement at C:\Soultion-Applications\test\.venv\lib\site-packages\IPython\core\magics\script.py:98:
->     def _script_magics_default(self):

Problem with statement at C:\Soultion-Applications\test\.venv\lib\site-packages\IPython\core\magics\script.py:98:
->     def _script_magics_default(self):

Problem with statement at C:\Soultion-Applications\test\.venv\lib\site-packages\IPython\core\magics\script.py:70:
-> class ScriptMagics(Magics):

Problem with statement at C:\Soultion-Applications\test\.venv\lib\site-packages\IPython\core\magics\script.py:70:
-> class ScriptMagics(Magics):

Problem with statement at C:\Soultion-Applications\test\.venv\lib\site-packages\IPython\core\magics\script.py:70:
-> class ScriptMagics(Magics):

Problem with statement at C:\Soultion-Applications\test\.venv\lib\site-packages\IPython\core\magics\script.py:70:
-> class ScriptMagics(Magics):

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\Soultion-Applications\\test\\.venv\\lib\\site-packages\\IPython\\core\\magics\\script.py', 'module_name': <ModuleName IPython.core.magics.script>, 'code_flags': ''}>'.
PASS 1: 46.2%|███████████▌             | 319/691, IPython.core.magics.scriptTraceback (most recent call last):
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\__main__.py", line 151, in <module>
    main()
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\__main__.py", line 137, in main
    MainControl.main()
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\MainControl.py", line 942, in main
    main_module = _createMainModule()
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\MainControl.py", line 243, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 344, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 300, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 191, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\Optimization.py", line 100, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 552, in computeModule
    result = module_body.computeStatementsSequence(
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 157, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\FrameNodes.py", line 189, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 159, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 347, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 619, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 3762, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 619, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 5741, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 619, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\OutlineNodes.py", line 249, in computeExpressionRaw
    result = body.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 159, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 159, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 157, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\FrameNodes.py", line 189, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\LocalsDictNodes.py", line 415, in computeStatement
    result, change_tags, change_desc = self.computeStatementSubExpressions(
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\NodeBases.py", line 733, in computeStatementSubExpressions
    expression = trace_collection.onExpression(expression)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 619, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 3762, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 619, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 5741, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 619, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 4639, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 619, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 1157, in computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 341, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 495, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 511, in computeFunction
    result = statements_sequence.computeStatementsSequence(
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\StatementNodes.py", line 159, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 635, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Soultion-Applications\test\.venv\lib\site-packages\nuitka\nodes\TryNodes.py", line 127, in computeStatement
    raise NuitkaOptimizationError(
nuitka.Errors.NuitkaOptimizationError:
This statement does raise but didn't annotate an exception exit.

    <node kind="StatementsFrameFunction" line="98" co_name="_script_magics_default" co_kind="Function" co_varnames="self,defaults" co_freevars="" co_argcount="1" co_posonlyargcount="0" co_kwonlyargcount="0" co_has_starlist="False" co_has_stardict="False" co_filename="IPython\core\magics\script.py" co_lineno="98" co_new_locals="True" co_is_optimized="True" code_flags="">
      <role name="statements" type="list">
        <node kind="StatementExpressionOnly" line="112" expression="EXPRESSION_LIST_OPERATION_EXTEND">
          <role name="expression">
            <node kind="ExpressionListOperationExtend" line="112">
              <role name="list_arg">
                <node kind="ExpressionVariableRef" line="112" variable_name="defaults" owner="IPython$core$magics$script$$$function__2__script_magics_default" />       
              </role>
              <role name="value">
                <node kind="ExpressionConstantListRef" line="112" constant="['cmd']" user_provided="True" />
              </role>
            </node>
          </role>
        </node>
      </role>
    </node>



The above information should be included in a bug report.
```

**Comment by kayhayen** [comment] 2023-01-28 14:25
Thanks, indeed a regression. I will provide a hotfix in 1.4.1 soon.

**Comment by kayhayen** [comment] 2023-01-28 14:29
What is strange to me, is that I failed to reproduce it, but I can see in the code that the issue is real, and I tried Linux and 3.10, maybe I will see it on 3.8 and Windows if I true, could also change the IPython version, in case they stopped support at some point.

**Comment by kayhayen** [comment] 2023-01-28 14:40
Anyway, the code is already done.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-01-28 17:44
I reproduced the error on Windows with Python3.8 indeed, so that is good, and indeed there is some version dependency. I must say however, that I rarely compile IPython due to the anti-bloat fight. But on the other hand it is of course great to do it for coverage of a lot code, so I am taking your test case into my release tests.

**Comment by kayhayen** [comment] 2023-01-28 17:55
Seems at least on this config, Yaml package configuration is needed for it to work

```
- module-name: 'IPython.core.oinspect'
  implicit-imports:
    - depends:
        - 'pygments.lexers.python'
```

**Comment by kayhayen** [comment] 2023-02-01 15:33
Part of the 1.4.2 hotfix.

**Closed by kayhayen** 2023-02-01 15:33 UTC
Labels: factory
