### ISSUE TITLE
Environment variable CC had no effect for --onefile bootstrap build and --version output

### ISSUE THREAD

**Issue by horta** [Nuitka/Nuitka#3190] opened 2024-11-12 12:20 UTC
Bug: https://github.com/Nuitka/Nuitka/blob/ccfd060d23e7eac52f8869c063bf6fc1f6152baf/nuitka/build/SconsUtils.py#L224

SCons's Environment constructor: https://github.com/SCons/scons/blob/b4d72c716aa98d3cefcf9fcb358429b08ac58114/SCons/Environment.py#L1193

ENV is treated as an environment variable itself.

Solutions: https://scons-cookbook.readthedocs.io/en/latest/

**Comment by kayhayen** [comment] 2024-11-13 08:32
I don't get what you are trying to say here at all. Without a demonstration of a bug, or even version information, I don't think this is going anywhere.

**Comment by horta** [comment] 2024-11-13 09:51
I will post one later but just explaining the problem for now: If we want to pass the environment variables into Environment constructor, we need ```Environment(**os.environ)``` instead of ```Environment(ENV=os.environ)``` as per line https://github.com/SCons/scons/blob/b4d72c716aa98d3cefcf9fcb358429b08ac58114/SCons/Environment.py#L1259C1-L1263C35.

**Comment by kayhayen** [comment] 2024-11-13 13:04
I am not sure, I really want arbitrary environment variables to impact the Nuitka build process. We support some specific ones, but I don't think I want to deal with even more unknown impacts.

https://nuitka.net/user-documentation/tips.html#providing-extra-options-to-nuitka-c-compilation

**Comment by horta** [comment] 2024-11-13 16:49
The problem with me happens when I set CC to, lets say, clang. The first stage of nuitla uses it, but then SCons doent because it simply cannot. I will post it with an example later today...

**Comment by kayhayen** [comment] 2024-11-13 21:24
Not sure what you are talking about, there is --clang and it's working for both ClangCL and Clang from MinGW64 and of course on non-Windows anyway.

**Comment by horta** [comment] 2024-11-13 23:15
```
$ system_profiler SPSoftwareDataType
...
      System Version: macOS 15.2 (24C5079e)
      Kernel Version: Darwin 24.2.0
...

$ /Library/Frameworks/Python.framework/Versions/Current/bin/python3 --version
Python 3.12.7

$ /Library/Frameworks/Python.framework/Versions/Current/bin/python3 -m pip uninstall -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
...
Successfully installed Nuitka-2.5rc14


$ export CC=/usr/bin/clang
$ /Library/Frameworks/Python.framework/Versions/Current/bin/python3 -m nuitka --onefile --show-scons script.py
Nuitka-Options: Used command line options: --onefile --show-scons script.py
Nuitka: Starting Python compilation with Nuitka '2.5rc14' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Scons command: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 -W ignore
Nuitka-Scons: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/inline_copy/bin/scons.py -f
Nuitka-Scons: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/Backend.scons --jobs 8 --warn=no-deprecated --no-site-dir --debug=stacktrace
Nuitka-Scons: source_dir=. nuitka_python=false debug_mode=false debugger_mode=false python_debug=false module_mode=false full_compat=false experimental= trace_mode=false
Nuitka-Scons: file_reference_mode=runtime module_count=299 gil_mode=true result_exe=/Users/horta/tmp/bug/script.dist/script.bin
Nuitka-Scons: static_libpython=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/config-3.12-darwin/libpython3.12.a standalone_mode=true onefile_mode=true
Nuitka-Scons: onefile_temp_mode=true frozen_modules=153 python_sysflag_no_site=true nuitka_src=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build
Nuitka-Scons: python_version=3.12 python_prefix=/Library/Frameworks/Python.framework/Versions/3.12 debug_modes= no_deployment= clang_mode=true show_scons=true noelf_mode=true
Nuitka-Scons: macos_min_version=11.0 macos_target_arch=arm64 target_arch=arm64
scons: Reading SConscript files ...
Nuitka-Scons: CC='/usr/bin/clang'
Nuitka-Scons: CC '/usr/bin/gcc' version check gives (16, 0, 0)
Nuitka-Scons: Initial CC: 'gcc'
Nuitka-Scons: Initial CCVERSION: (16, 0, 0)
Nuitka-Scons: Overridden with environment CC: '/usr/bin/clang'
Scons: Compiler used /usr/bin/clang
Nuitka-Scons: CC '/usr/bin/clang' version check gives (16, 0, 0)
Nuitka-Scons: Backend C compiler: /usr/bin/clang (clang 16.0.0).
Nuitka-Scons: LTO mode auto was resolved to mode: 'no' (might to be too slow 299 (>= 250 threshold), force with --lto=yes).
Nuitka-Scons: Using C11 mode: True
Nuitka-Scons: Using resource mode: 'mac_section' (default for macOS).
Nuitka-Scons: Told to run compilation on 8 CPUs.
Nuitka-Scons: Checking if ccache is at '/Library/Frameworks/Python.framework/Versions/3.12/bin/ccache' guessed path.
Nuitka-Scons: Checking if ccache is at '/usr/local/opt/ccache' guessed path.
Nuitka-Scons: Checking if ccache is at '/opt/homebrew/bin/ccache' guessed path.
Nuitka-Scons: Found ccache '/Users/horta/Library/Caches/Nuitka/downloads/ccache/v4.2.1/ccache' to cache C compilation result.
Nuitka-Scons: Providing real CC path '/usr/bin/clang' via PATH extension.
Nuitka-Scons: Launching Scons target: ['/Users/horta/tmp/bug/script.dist/script.bin']
scons: done reading SConscript files.
scons: Building targets ...
"/.../ccache" "/usr/bin/clang" -o __constants.o ...
...
scons: done building targets.
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 5
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 1
Nuitka-Postprocessing: Creating single file from dist folder, this may take a while.
Nuitka-Onefile: Running bootstrap binary compilation via Scons.
Nuitka-Onefile: Using compression for onefile payload.
Nuitka-Onefile: Onefile payload compression ratio (23.87%) size 16652165 to 3974473.
Nuitka-Scons: Scons command: /Library/Frameworks/Python.framework/Versions/3.12/bin/python3 -W ignore
Nuitka-Scons: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/inline_copy/bin/scons.py -f
Nuitka-Scons: /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/Onefile.scons --jobs 8 --warn=no-deprecated --no-site-dir --debug=stacktrace
Nuitka-Scons: result_exe=/Users/horta/tmp/bug/script.bin source_dir=. debug_mode=false trace_mode=false onefile_splash_screen=false
Nuitka-Scons: nuitka_src=/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build python_version=3.12
Nuitka-Scons: python_prefix=/Library/Frameworks/Python.framework/Versions/3.12 experimental= debug_modes= no_deployment= clang_mode=true show_scons=true noelf_mode=true
Nuitka-Scons: macos_min_version=11.0 macos_target_arch=arm64 target_arch=arm64
scons: Reading SConscript files ...
Nuitka-Scons: CC='/usr/bin/clang'
Nuitka-Scons: CC '/usr/bin/gcc' version check gives (16, 0, 0)
Nuitka-Scons: Initial CC: 'gcc'
Nuitka-Scons: Initial CCVERSION: (16, 0, 0)
Nuitka-Scons: Overridden with environment CC: 'gcc'
Scons: Compiler used /usr/bin/gcc
TypeError: 'NoneType' object is not iterable:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/Onefile.scons", line 323:
    reportCCompiler(env, "Onefile", output_func=scons_logger.info)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/SconsCompilerSettings.py", line 999:
    ".".join(str(d) for d in env.gcc_version),
FATAL: Error, onefile bootstrap binary build failed.
```

Notice the following two lines:

- Nuitka-Scons: Overridden with environment CC: '/usr/bin/clang'
- Nuitka-Scons: Overridden with environment CC: 'gcc'

It first uses clang, that I provided via CC, and then tries to use gcc.

**Comment by horta** [comment] 2024-11-14 09:47
By the way, if I use the `--clang` flag without setting CC, I obtain Clang from my Homebrew installation:

```
Nuitka-Scons: Providing real CC path '/opt/homebrew/opt/llvm/bin/clang' via PATH extension.
```

I suppose that is not a problem in itself, but setting CC and then not having it consistently utilised by the workflow does appear to be an issue.

**Comment by kayhayen** [comment] 2024-11-14 11:00
Seems like it would be bug of how CC is not picking up that it's clang that you passed in. Nuitka actually wants to use the GCC (which is a clang for all I know) on macOS

```
gcc --version
Apple clang version 16.0.0 (clang-1600.0.26.3)
Target: arm64-apple-darwin24.0.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

This may only happen if you have Xcode installed though, but I thought it's always there, just other tools requiring Xcode, for signing, etc.

**Comment by kayhayen** [comment] 2024-11-14 11:01
Looks like a hard link to me:

```
hayen@kaymac Py2C % ls -l /usr/bin/clang 
-rwxr-xr-x  78 root  wheel  118848 Sep 30 21:10 /usr/bin/clang
hayen@kaymac Py2C % ls -l /usr/bin/gcc   
-rwxr-xr-x  78 root  wheel  118848 Sep 30 21:10 /usr/bin/gcc
```

**Comment by horta** [comment] 2024-11-14 11:03
Yes, gcc does indeed point to Clang. I will trace back where this CC check occurs and investigate the behaviour at that point.

**Comment by kayhayen** [comment] 2024-11-14 11:05
I reproduced it, seems the onefile build scons file has an issue there. Seems some still duplicated code is acting stupid.

Please note that for macOS onefile is for command line programs only and for GUIs you would use app bundles, and combining that will be wrong for many uses actually.

**Comment by horta** [comment] 2024-11-14 11:16
This:

```
env = createEnvironment(
    mingw_mode=mingw_mode,
    msvc_version=msvc_version,
    target_arch=target_arch,
    experimental=experimental,
    no_deployment=no_deployment,
    debug_modes=debug_modes,
)
```

from `Onefile.scons` is setting CC to gcc:

```
> /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/Onefile.scons(151)<module>()
-> clang_mode = getArgumentBool("clang_mode", False)
(Pdb) 
> /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/Onefile.scons(155)<module>()
-> clangcl_mode = False
(Pdb) p clang_mode
True
...
(Pdb) 
> /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/Onefile.scons(233)<module>()
-> env = createEnvironment(
(Pdb) 
Nuitka-Scons: CC '/usr/bin/gcc' version check gives (16, 0, 0)
> /Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/nuitka/build/Onefile.scons(242)<module>()
-> scons_details_logger.info("Initial CC: %r" % env.get("CC"))
(Pdb) n
Nuitka-Scons: Initial CC: 'gcc'
```

**Comment by horta** [comment] 2024-11-14 11:21
Within createEnvironment, we have the following code:

```python
    env = Environment(
        # We want the outside environment to be passed through.
        ENV=os.environ,
        # Extra tools configuration for scons.
        tools=tools,
        # The shared libraries should not be named "lib...", because CPython
        # requires the filename "module_name.so/pyd" to load it, with no
        # prefix at all, spell-checker: ignore SHLIBPREFIX
        SHLIBPREFIX="",
        # Under windows, specify the target architecture is needed for Scons
        # to pick up MSVC.
        TARGET_ARCH=target_arch,
        # The MSVC version might be fixed by the user.
        MSVC_VERSION=msvc_version if msvc_version != "latest" else None,
        **args
    )
```

This is why I believe you intended to pass CC directly into the Environment constructor. When I modify the code as follows:

```python
    env = Environment(
        # We want the outside environment to be passed through.
        # ENV=os.environ,
        CC=os.environ['CC'],
        # Extra tools configuration for scons.
        tools=tools,
        # The shared libraries should not be named "lib...", because CPython
        # requires the filename "module_name.so/pyd" to load it, with no
        # prefix at all, spell-checker: ignore SHLIBPREFIX
        SHLIBPREFIX="",
        # Under windows, specify the target architecture is needed for Scons
        # to pick up MSVC.
        TARGET_ARCH=target_arch,
        # The MSVC version might be fixed by the user.
        MSVC_VERSION=msvc_version if msvc_version != "latest" else None,
        **args
    )
```

it does indeed function correctly, although it still reports gcc (with clang's version):

```
Nuitka-Scons: CC '/usr/bin/gcc' version check gives (16, 0, 0)
```

**Comment by kayhayen** [comment] 2024-11-14 11:27
Nah, it's just missing cruicial lines. Only the backend did this: `env["CC"] = os.environ["CC"]` and that's the fix actually. Backend was already doing it correct. Note that --clang is enforced already.

```
def isClang():
    """:returns: bool derived from ``--clang`` or enforced by platform, e.g. macOS or FreeBSD some targets."""

    return (
        options.clang
        or isMacOS()
        or isOpenBSD()
        or (isFreeBSD() and getArchitecture() != "powerpc")
        or isTermuxPython()
    )
```

This is overridden, and you cannot pass a gcc in. The macOS gcc seems to have some gcc defaults, so e.g. deprecations in system header files are warned, etc. and cannot be used. Enforcing `/usr/bin/clang` works now however.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-11-14 11:30
This also had negative effect on `--version` output, which is always good to find. On other platforms, not adhering to CC ought to have little effect for onefile bootstrap builds, since it's so undemanding as a build, but of course not good. These is still a bunch of code duplicating going on unfortunately. We cleaned up some of that, but often fixes are in one place and not all 3 which is then harming us.

**Comment by horta** [comment] 2024-11-14 14:10
It is functioning correctly and has detected the CC value in both stages. Thank you.

**Closed** 2024-11-16 12:40 UTC
Labels: bug, factory
