### ISSUE TITLE
TypeError: unhashable type: 'slice' 

### ISSUE THREAD

**Issue by David-Worboys** [Nuitka/Nuitka#1648] opened 2022-07-01 02:45 UTC
First use of **kwargs in this program and Nuitka and I was surprised by the result...Nuitka compile failed!

**Nuitka version**

python -m nuitka --version
0.9.2
Commercial: None
Python: 3.10.5 (main, Jun 11 2022, 09:39:24) [GCC 10.2.1 20210110]
Flavor: Unknown
Executable: /home/david/Dev/python/dev_venv3.10.4/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian 11

**How did you install Nuitka and Python**
Installed Python via download and compile
I use a virtual environment - venv - with Pycharm
Installed Nuitka with Pycharm

Example script (test.py):

```
def _checkget_values(db_obj: object, kwargs: dict[str:any]) -> dict[str:any]:
    print(f"DBG {kwargs}")

class test():
    def __init__(self,**kwargs):
        _checkget_values(self,kwargs)


test(parm1="test",pamr2=12,parm3= True, parm4 = 12.2)
```

**Run from command line**
 ```
python3 test.py
DBG {'parm1': 'test', 'pamr2': 12, 'parm3': True, 'parm4': 12.2}
```

**Nuitka compile**
```
nuitka3 test.py

Nuitka-Options:INFO: Used command line options: test.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka-Options:INFO: Detected static libpython to exist, consider '--static-libpython=yes' for better performance, but errors may happen.
Nuitka:INFO: Starting Python compilation with Nuitka '0.9.2' on Python '3.10' commercial grade 'not installed'.
PASS 1: 0.0%|                         | 0/1, __main__Problem with statement at test.py:1:
-> def _checkget_values(db_obj: object, kwargs: dict[str:any]) -> dict[str:any]:

Nuitka:INFO: Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': 'test.py', 'module_name': <ModuleName __main__>, 'main_added': False, 'mode': 'compiled', 'code_flags': ''}>'.
PASS 1: 0.0%|                         | 0/1, __main__Traceback (most recent call last):
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/__main__.py", line 138, in <module>
    main()
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/__main__.py", line 124, in main
    MainControl.main()
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/MainControl.py", line 935, in main
    main_module = _createNodeTree(filename=filename)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/MainControl.py", line 202, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/Optimization.py", line 329, in optimizeModules
    finished = makeOptimizationPass()
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/Optimization.py", line 291, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/Optimization.py", line 187, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/Optimization.py", line 98, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/ModuleNodes.py", line 892, in computeModule
    CompiledPythonModule.computeModule(self)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/ModuleNodes.py", line 536, in computeModule
    result = module_body.computeStatementsSequence(
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/VariableAssignNodes.py", line 314, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/TraceCollections.py", line 624, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/ExpressionBases.py", line 1203, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/TraceCollections.py", line 624, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/ExpressionBases.py", line 1411, in computeExpressionRaw
    expression = trace_collection.onExpression(expression=sub_expression)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/TraceCollections.py", line 624, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/ExpressionBases.py", line 1263, in computeExpressionRaw
    expression = trace_collection.onExpression(expression=value)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/TraceCollections.py", line 624, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/ExpressionBases.py", line 1222, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/SubscriptNodes.py", line 118, in computeExpression
    return self.subnode_expression.computeExpressionSubscript(
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/ConstantRefNodes.py", line 1305, in computeExpressionSubscript
    return trace_collection.getCompileTimeComputationResult(
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/optimizations/TraceCollections.py", line 928, in getCompileTimeComputationResult
    new_node, change_tags, message = getComputationResult(
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/NodeMakingHelpers.py", line 282, in getComputationResult
    new_node = makeCompileTimeConstantReplacementNode(
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/NodeMakingHelpers.py", line 231, in makeCompileTimeConstantReplacementNode
    return makeConstantReplacementNode(
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/NodeMakingHelpers.py", line 40, in makeConstantReplacementNode
    return makeConstantRefNode(
  File "/home/david/Dev/python/dev_venv3.10.4/lib/python3.10/site-packages/nuitka/nodes/ConstantRefNodes.py", line 1493, in makeConstantRefNode
    elif constant in builtin_anon_values:
TypeError: unhashable type: 'slice
```

**Note if this is a regression**
* Unknown

**Comment by kayhayen** [comment] 2022-07-02 09:09
Thanks for the report, I managed to reproduce this. This is very strange, because right before, there is code light this:

```
    elif constant_type is slice:
        return ExpressionConstantSliceRef(
            constant=constant,
            source_ref=source_ref,
        )
```

That should catch this, but something strange must be going on here.

**Comment by kayhayen** [comment] 2022-07-02 09:15
I see, this is creating a `GenericAlias` with an argument, that is not hashable, which is OK, but for `GenericAlias` the check is done only later, and should be done before, to avoid this crash.

**Comment by kayhayen** [comment] 2022-07-02 16:42
A fix for it is on the factory branch and will be in 0.9.3 as well: https://nuitka.net/doc/factory.html

**Comment by David-Worboys** [comment] 2022-07-02 19:30
Thank you Kay, I will pull from factory and check it later today.  

I am a bit surprised I tripped over this bug as I thought **kwargs would be widely used, even if I think there is a pox on using this as a method/function argument in code (first time I used it as it fit the problem!).

**Comment by David-Worboys** [comment] 2022-07-02 20:19
And I can confirm your fix Kay...appreciated!

**Comment by kayhayen** [comment] 2022-07-03 15:49
Release as part of 0.9.3.

**Closed by kayhayen** 2022-07-03 15:49 UTC
Labels: factory
