### ISSUE TITLE
2.3.4 regression

### ISSUE THREAD

**Issue by sullivan50909** [Nuitka/Nuitka#2935] opened 2024-06-19 19:13 UTC
This is a preliminary report. I'm hoping you will recognize the issue before I can create an easy-to-reproduce example. I'll keep working on an example worth sharing. 

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

WORKING VERSION:
2.3.3
 Commercial: None
 Python: 3.9.18 (main, Jan 24 2024, 00:00:00) 
 Flavor: Fedora Python
 Executable: /usr/bin/python3
 OS: Linux
 Arch: x86_64
 Distribution: Rhel (based on Fedora) 9.4
 Version C compiler: /usr/bin/gcc (gcc 11)

NON-WORKING VERSION:
 2.3.7
 Commercial: None
 Python: 3.9.18 (main, Jan 24 2024, 00:00:00) 
 Flavor: Fedora Python
 Executable: /usr/bin/python3
 OS: Linux
 Arch: x86_64
 Distribution: Rhel (based on Fedora) 9.4
 Version C compiler: /usr/bin/gcc (gcc 11)

Note: I tested on Monday with version 2.3.4 and it did not work, either.

- How did you install Nuitka and Python
yum install gcc python3-devel
pip3 install  nuitka
pip3 install patchelf 
No venv. 

- The specific PyPI names and versions

I did not make any pypi changes between the working and non-working versions, so I don't think this is relevant. 

- Also supply a Short, Self Contained, Correct, Example

I have been using Nuitka for a while with no issues. I compile my code with onefile, then move the compiled code to a new environment and run it there. Starting Monday, when I try to run my compiled code in a clean environment, I get this error:

ImportError: attempted relative import with no known parent package

I know this is not a very useful example. I'll put something together in the next few days to allow you to reproduce the issue. 

- Provide in your issue the Nuitka options used
python3 -m nuitka --follow-imports --onefile --python-flag=no_docstrings myFile.py

No changes to my code or my Nuitka options between working and non-working version
 
- Note if this is a regression

YES. Working fine in 2.3.3 and earlier. Fails in 2.3.4 and 2.3.7. (I didn't test 2.3.5 or 2.3.6.)

**Comment by sullivan50909** [comment] 2024-06-19 19:29
How to reproduce:
Using Nuitka 2.3.7
Create hello.py with the following content:
import pydantic.tools
print("hello world")

python3 -m nuitka --follow-imports --onefile hello.py
./hello.bin
Traceback (most recent call last):
  File "/tmp/onefile_2836_1718824987_615073/hello.py", line 1, in <module>
    import pydantic.tools
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
ImportError: attempted relative import with no known parent package

pip3 install nuitka==2.3.3
Repeat steps above, now it works.

**Comment by KRRT7** [comment] 2024-06-19 19:30
does it also happen with the latest nuitka version?

**Comment by sullivan50909** [comment] 2024-06-19 19:32
I tested 2.3.4 and 2.3.7 and they both fail. Is there another version you would like me to test?

**Comment by KRRT7** [comment] 2024-06-19 20:29
thanks, that's enough, the MRE compiles fine for me on windows, at least on the latest pydantic version, going to try it under linux now

**Comment by sullivan50909** [comment] 2024-06-19 20:33
I am using pydantic==1.9.2 in all my test cases (both working and non-working).

**Comment by KRRT7** [comment] 2024-06-19 20:49
> I am using pydantic==1.9.2 in all my test cases (both working and non-working).

thanks, that was missing from your report.
i managed to reproduce it on ubuntu linux, however this is an very old version of pydantic, im not sure if we want to support it.
@kayhayen if you do. it seems to be an issue with a compiled init, you might want to support that however.

**Comment by kayhayen** [comment] 2024-06-20 12:28
@KRRT7 you mean a `__init__.so` that I have done a lot for recently, develop/factory did you try that?

**Comment by KRRT7** [comment] 2024-06-20 12:46
> @KRRT7 you mean a `__init__.so` that I have done a lot for recently, develop/factory did you try that?

Yes precisely, I tried factory for this.

**Comment by kayhayen** [comment] 2024-06-20 16:03
So, the support for `__init__.so` files to be detected causes breakage because if used, these files hide the `__init__.py` previously used, something you can now activate with the `--prefer-source-code` option.

This then causes hidden dependencies, which can be fixed by adding them to our yaml configuration, something I completed doing. However, I think that's not too useful.

Instead, we should treat the .py files as if they were .pyi files and take imports from them. Now that of course strains the .pyi parser, which allows for non-Python syntax, since it's allowed there and it currently crashes. I am looking into fixing it.

**Comment by kayhayen** [comment] 2024-06-20 16:21
So, I think it found a bug in the `.pyi` parser that I have addressed, and now it won't crash, lets see if I can remove the new dependencies added.

**Comment by kayhayen** [comment] 2024-06-20 16:27
Indeed, with the new .pyi parser, no new hidden dependencies are needed, and probably generally the ones previously added, will have become unnecessary too. This should fix the regression there, but has of course potential to exhibit more bugs in the parser, but I am willing to take that risk for the bettering of Nuitka.

**Comment by kayhayen** [comment] 2024-06-20 16:27
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-06-20 16:32
I don't get why it would work change for the hotfixes, they do not contain anything of my latest changes related to using the `__init__.so` files, specifically the `ImportError: attempted relative import with no known parent package` makes no sense to me really, I got to check myself.

**Comment by kayhayen** [comment] 2024-06-20 16:48
I think `pydantic` has actually been working for a longer time, the dependencies in the yaml configuration are probably for an even older version. I managed to see it not work for 2.3.7 indeed and for 2.3.3, so git bisect to the rescue:

```
commit 9c2a97948cb9a9514205da6e9115b4dfd2077a0b (refs/bisect/bad)
Author: Kay Hayen <kay.hayen@gmail.com>
Date:   Wed Jun 12 18:54:28 2024 +0200

    Fix, the package filename should prefer extension modules

diff --git a/nuitka/utils/Importing.py b/nuitka/utils/Importing.py
index dae945373..12334faad 100644
--- a/nuitka/utils/Importing.py
+++ b/nuitka/utils/Importing.py
@@ -322,7 +322,7 @@ def hasPackageDirFilename(path):
 def getPackageDirFilename(path):
     assert os.path.isdir(path)
 
-    for suffix in (".py",) + getSharedLibrarySuffixes():
+    for suffix in getSharedLibrarySuffixes() + (".py",):
         candidate = os.path.join(path, "__init__" + suffix)
```

That basically strikes us here, when packages have both python and extension module installed, I am going to revert it with a fixup commit, for a 2.3.8 release to be made with it.

This causes the `__init__.so` to be used but before the code that loads them was ready. These things (extension modules) were e.g. never packages before, that was added in steps only recently. I thought this only had an impact on locating files properly, but it also influences the selection I see now. I suspect, the new code also prevents --prefer-source-code from having an effect maybe now.

**Comment by sullivan50909** [comment] 2024-06-20 18:21
I did some basic tests with 2.4rc6 on the factory branch and it looks quite promising. I'll work on more complex tests today.

**Comment by kayhayen** [comment] 2024-06-24 06:55
This has been release as part of a hotfix since.

**Closed by kayhayen** 2024-06-24 06:55 UTC
Labels: bug, factory, excellent_report
