### ISSUE TITLE
ImportError: `libpyside6.abi3.so.6.4`: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2116] opened 2023-03-15 19:03 UTC
- Bug not reported or fixed as far as I can see (apart from #2114)
- Same bug in `develop`
- ```
  1.6rc2
  Commercial: None
  Python: 3.11.2 (main, Feb 12 2023, 13:27:53) [GCC 11.3.0]
  Flavor: pyenv
  Executable: /home/bers/.pyenv/versions/3.11.2/bin/python3
  OS: Linux
  Arch: x86_64
  Distribution: Ubuntu (based on Debian) 22.04.1
  Version C compiler: /usr/bin/gcc (gcc).
  ```
- Installed via `pip install https://github.com/Nuitka/Nuitka/archive/refs/heads/develop.zip`

- Short, Self Contained, Correct, Example: `bug2.py`
```python
  # python -m pip install nuitka PySide6-Essentials
  # python -m nuitka bug2.py
  # bug2.dist/bug2.bin
  
  # nuitka-project: --quiet
  # nuitka-project: --standalone
  # nuitka-project: --static-libpython=no
  # nuitka-project: --enable-plugin=pyside6
  
  from PySide6.QtCore import QCoreApplication
  
  application = QCoreApplication()
  print("Done.")
  ```
- Using `PySide6-Essentials==6.4.2`
- Regression: 1.5 works, 1.5.1 fails

**Comment by kayhayen** [comment] 2023-03-15 19:13
So, this is pyenv, which may not be a good idea to use. Their PySide6 may not be all that portable. Also apparently you didn't even care to make the static linking work, but that won't be the issue.

And this is Python3.11, of which I am not entirely sure it works for PySide6. I was just confirming PySide6 still works on Windows with 3.10, didn't try 3.11 yet. Also going to try my self compiled 3.11 on Debian. You seem to suggest you used PyPI to install PySide6, that ought to work. Something from pyenv I would be a lot more sceptic, but it's not clear from your report. Going to checkout 3.10/3.11 on Linux too.

This being a regression is indeed interesting. If possible it would be nice if you used git bisect to pin point it, but it's likely that I reproduce it too apparently.

**Comment by bersbersbers** [comment] 2023-03-15 19:45
> If possible it would be nice if you used git bisect to pin point it, but it's likely that I reproduce it too apparently.

Sure. 09ac64b5fb750b309197cdd1173f39315ff4b1f8 works, a899b82df3dfa28ca0835961aa5bce6298ff40f5 fails. (I mentioned that commit in #2114, so I am not sure deleting that issue was a net positive.)

**Comment by bersbersbers** [comment] 2023-03-15 19:48
> So, this is pyenv, which may not be a good idea to use. Their PySide6 may not be all that portable.

Out of curiosity, how is "`pyenv`'s" `PySide6` different from other `PySide6`s? Don't they use the same wheels? Note that I am not necessarily using virtual environments, I mainly use `pyenv` as a convenience tool to download and switch between Python versions.

**Comment by kayhayen** [comment] 2023-03-15 19:50
I am sure it was, for the reasons I gave. It mentioned the commit, but didn't say you if actually bisected it. Also you mentioned Windows to stop working, which I wonder if this could be due to an unrelated issue that I fixed on the factory branch maybe. If you want to try that, and see it work, that would be great. I am currently waiting for the 3.11 on Windows to succeed before turning to Linux. I think you have been victim to distinct issues.

**Comment by kayhayen** [comment] 2023-03-15 19:55
So, 3.11 on Windows is running too for me as well. I do not think said commit plays a role there at all. On Linux, this might be different, lets see.

**Comment by kayhayen** [comment] 2023-03-15 20:48
So, yes indeed, the moving of the DLL along side its user, for shiboken that breaks things.

```
LANG=C diff -r PySideQmlPolarchartTest.dist PySideQmlPolarchartTest.bad.dist/
Only in PySideQmlPolarchartTest.bad.dist/PySide6: libpyside6.abi3.so.6.4
Only in PySideQmlPolarchartTest.bad.dist/PySide6: libpyside6qml.abi3.so.6.4
Binary files PySideQmlPolarchartTest.dist/PySideQmlPolarchartTest.bin and PySideQmlPolarchartTest.bad.dist/PySideQmlPolarchartTest.bin differ
Only in PySideQmlPolarchartTest.dist: libpyside6.abi3.so.6.4
Only in PySideQmlPolarchartTest.dist: libpyside6qml.abi3.so.6.4
Only in PySideQmlPolarchartTest.bad.dist/shiboken6: libshiboken6.abi3.so.6.4
```

I believe the shiboken usage of PySide6 is relatively special. I need to investigate what is loading it precisely.

**Comment by kayhayen** [comment] 2023-03-15 20:51
Something strange, I had an error from `patchelf` due to a json file being treated as a DLL. The Qt plugins list the data file types, and so far json was not among it. I wonder if that is because I install the addons, and as such have more plugins to Qt maybe than you do, although "sensible" should not be among them. I trust you are using the wheel too. But because of that, at least the 6.4.2 was not working, not sure how old it is. I probably last tries this with 6.4.0 from what I had installed on machines.

**Comment by kayhayen** [comment] 2023-03-15 21:01
So, two DLLs got moved, but `libshiboken6` is duplicated in `shiboken6` and top level. That may actually be preventing its load, and definitely is very unwelcome. It is what I saw with `openvino` which lead me to make this fix. But apparently it can cause the same issue elsewhere. I will revert it for a 1.5.2 later, until it is assessed what the impact of this is. Everything tensorflow, scipy, etc. works still, but PySide6 breaking is not acceptable at all.

**Comment by bersbersbers** [comment] 2023-03-16 07:07
> So, 3.11 on Windows is running too for me as well.

I agree, with the above repro code it works on Windows for me as well. So the fact that my main application does not launch on Windows must be related to something else, which I will report separately when I can isolate it.

**Comment by kayhayen** [comment] 2023-03-16 09:18
> Update: That Windows issue was due to me using `nuitka-project: --force-stdout-spec="%NONE%"` on a pre-factory version of Nuitka without a console attached, so I did not see the error that was raised. No further issue to be reported at this point in time :)

Yes, and these values are also only checked in the new version, so that error went unnoticed. Sorry about that.

**Comment by kayhayen** [comment] 2023-03-16 10:52
I have rebased main and develop, and 1.5.2 will release it with a change that restores PySide6, and only does the new thing for openvino, so I am closing this early, because I do not track it through factory now.

**Closed by kayhayen** 2023-03-16 10:52 UTC
Labels: bug, excellent_report

**Comment by bersbersbers** [comment] 2023-03-17 08:45
> PySide6 breaking is not acceptable at all.

I guess so - v1.5.1 even made it to their developer notes ;)
https://wiki.qt.io/Qt_for_Python_Development_Notes

> 1.5.2 will release it with a change that restores PySide6

Thanks :)
