### ISSUE TITLE
Duplicate KeyboardInterrupt exception delivered in onefile mode

### ISSUE THREAD

**Issue by JamesOldfield** [Nuitka/Nuitka#1477] opened 2022-03-17 14:20 UTC
## Summary

When I build an executable on Windows in onefile mode, exiting the program with a Ctrl+C seems to generate *two* `KeyboardInterrupt` events. It only happens in onefile mode - **NOT** in standalone mode.

## Reproducing

Here is a simple test program:

    import time

    print("Started")
    try:
        time.sleep(20)
    except KeyboardInterrupt:
        print("Got first KeyboardInterrupt")

    for sleep_time in (0.001, 0.01, 0.1):
        try:
            print()
            print("About to sleep for", sleep_time)
            time.sleep(sleep_time)
            print("Completed sleep of", sleep_time)
        except KeyboardInterrupt:
            print("Got another KeyboardInterrupt while sleeping for", sleep_time)

    print("Exiting")

I build it with this command:

    c:\src\nuitka_test>python -m nuitka --mingw64 --onefile nuitka_keyboardinterrupt_test.py
    Nuitka-Options:INFO: Used command line options: --mingw64 --onefile nuitka_keyboardinterrupt_test.py
    Nuitka:INFO: Starting Python compilation with Nuitka '0.7.5' on Python '3.8' commercial None.

Then run it like this (I only press Ctrl+C once):

    c:\src\nuitka_test>nuitka_keyboardinterrupt_test.exe
    Started
    Got KeyboardInterrupt while waiting for input

    About to sleep for 0.001Got another KeyboardInterrupt while sleeping for 0.001

    About to sleep for 0.01
    Completed sleep of 0.01

    About to sleep for 0.1
    Completed sleep of 0.1
    Exiting

I sometimes get slightly different results:

* As above, sometimes the second event happens during the first `sleep()` in the loop.
* Sometimes the "About to sleep for 0.001" message does not appear, suggesting that the second `KeyboardInterrupt` triggered during the call to `print()`.
* On one occasion, I didn't even see "Got KeyboardInterrupt while waiting for input", suggesting that the second `KeyboardInterrupt` was delivered while still in the `except:` branch of the first.
* I found this problem as part of a much larger program, notably with threads that are shut down and joined from the main thread. In that, the second `KeyboardInterrupt` is delivered a little later, not even in the `sleep(0.01)`. So far, `sleep(0.1)` seems to work.

## Workaround

It's possible to use a sleep like above and catch the second exception but that's not very reliable - it might get delivered afterwards if the sleep is too short, and it's even possible that the second exception could be delivered early. I think the safest thing is probably a custom signal handler:

    keyboard_interrupt_count = 0
    def keyboard_interrupt_handler(signum, frame):
        global keyboard_interrupt_count
        keyboard_interrupt_count += 1
        if keyboard_interrupt_count == 1:
            raise KeyboardInterrupt()
    signal.signal(signal.SIGINT, keyboard_interrupt_handler)

**Comment by kayhayen** [comment] 2022-03-17 16:43
Hello James,

the onefile bootstrap binary is passing on a CTRL-C it receives to the compiled Python program. Not sure if this has anything to do with MSVC vs. MinGW64, because there was, at some point, a report that CTRL-C was not passed to a compiled Python program. It might be some sort of default handling of MinGW64 that is happening here, otherwise I am confused now.

Would it be possible for you to try MSVC with your test easily?

Yours,
Kay

**Comment by kayhayen** [comment] 2022-03-17 16:50
Forget my last request, I reproduced it with MSVC just the same.

**Comment by kayhayen** [comment] 2022-03-18 12:24
Actually, according to docs, all processes of the terminal should receive the CTRL-C signal. I wonder, how I ever had that report then, maybe it's possible to detach from the console, e.g. by replacing standard outputs, or something, I will need to revisit this issue first, to see if it was only in our hears. But I think the first CTRL-C is from the terminal, and the second from onefile, but this is all a bit hard to trace naturally. Adding traces though.

**Comment by JamesOldfield** [comment] 2022-03-20 12:02
Thanks for the quick response Kay. I should note this issue is no longer affecting me thanks to the workaround I included. (In a sense, that signal handler is probably a good idea anyway for my program, even if this bug didn't exist.) But I thought it best to make it publically know.

**Comment by kayhayen** [comment] 2023-07-10 09:44
This has been fixed in another issue indeed, and works on Windows perfectly now.

**Closed** 2023-07-10 09:47 UTC
Labels: bug
