### ISSUE TITLE
macOS: Fatal error when compiling PySide6 app: failed to resolve DLL path

### ISSUE THREAD

**Issue by ThatNerdSquared** [Nuitka/Nuitka#1556] opened 2022-05-05 02:35 UTC
Whenever I try to compile any file that imports PySide6, I get the following error:

```
FATAL: Error, failed to resolve DLL path @rpath/QtPdf.framework/Versions/A/QtPdf (for /Users/nathanyeung/h4ck3r/lento/.venv/lib/python3.10/site-packages/PySide6/Qt/plugins/imageformats/libqpdf.dylib), please report the bug.
```

My project is [here](https://github.com/lentoapp/lento) but the test example provided below is so basic that the problem is unlikely to be caused by a configuration error.

* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

```
$ python -m nuitka --version
0.8rc9
Commercial: None
Python: 3.10.2 (main, Feb  2 2022, 05:51:25) [Clang 13.0.0 (clang-1300.0.29.3)]
Flavor: Unknown
Executable: /Users/nathanyeung/h4ck3r/lento/.venv/bin/python
OS: Darwin
Arch: arm64
```

* How did you install Nuitka and Python

```
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip3 install Nuitka
```

* The specific PyPI names and versions

```
$ python -m pip freeze
...
Nuitka==0.7.7
PySide6==6.3.0
PySide6-Addons==6.3.0
PySide6-Essentials==6.3.0
...
```

* Many times when you get an error from Nuitka, your setup may be special

(Nuitka works for compiling another part of my project that does not rely on PySide6)

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```py
import sys
from PySide6.QtWidgets import QApplication, QWidget
app = QApplication(sys.argv)

window = QWidget()
window.show()

app.exec_()
```

* Provide in your issue the Nuitka options used

Build command:
```
$ python3 -m nuitka --follow-imports --enable-plugin=pyside6 --standalone --onefile app.py
```

* Note if this is a regression

Unknown.

**Comment by kayhayen** [comment] 2022-05-07 16:32
Ok, this must be a regression by new PySide6, since that code is known to work. The "Unknown" flavor for macOS is a bit suspicious, what kind of Python is it?

**Comment by ThatNerdSquared** [comment] 2022-05-07 17:37
Should just be standard CPython, I installed it from Homebrew via `brew install python@3.10`. Is there a good way to double-check this?

**Comment by kayhayen** [comment] 2022-05-09 05:55
Homebrew is something that Nuitka tries to detect, apparently fails for your setup. Can you tell why this code doesn't work for you?

```
def isHomebrewPython():
    if not isMacOS():
        return False

    if "HOMEBREW_PREFIX" not in os.environ:
        return False

    if isPathBelowOrSameAs(
        path=os.environ["HOMEBREW_PREFIX"], filename=getSystemPrefixPath()
    ):
        return True
```

I don*t know what language will help people to understand, but standard CPython is a download from python.org, homebrew is supported by Nuitka for a while now, but there are differences. That said, this might even happen with CPython as this appears to be a PySide6 issue of the dependency resolution that would remain inside the PyPI package. Likely older PySide6 will work then.

**Comment by ThatNerdSquared** [comment] 2022-05-10 01:03
For some reason `HOMEBREW_PREFIX` wasn't set on my system; I've set it in my `.zshrc` so that should no longer be a problem.

You are correct that the bug persists even with this fix — do you know of a specific version of older PySide6 that is known to work with Nuitka?

**Comment by kayhayen** [comment] 2022-05-10 09:09
I was assuming that Homebrew somehow sets it, but I guess running directly is still somehow possible without having that, I need to check that out occasionally. And yes, I have used PySide6 no problem with previous versions, but I am not good with numbers and I much rather would spend my time figuring the bug out.

**Comment by kayhayen** [comment] 2022-05-12 09:06
Nah, I doubt upstream has anything to do it. PySide6 has been stretching the limits of the dependency parser. It's just strange to me that it is supposed to never have worked, when I recall testing it successfully. Ah wait, you are not building an app, and maybe that is the different. Nuitka can and does insist on this e.g. with `wx`. Not sure, but that might be the reason.

**Comment by kbrowser** [comment] 2022-05-15 01:14
On macOS I meet the same error (0.7.7 and the latest 0.8 rc version), so that the compiling always fails for an app with PySide6.

**Comment by kayhayen** [comment] 2022-05-15 22:02
I managed to reproduce this now, not sure, but I believe I had PySide6 working before, but probably the dependency parser got more strict in the meantime.

What's going on is that `PySide6` unlike `PySide2`, doesn't contain the `QtPdf` support. From a quick Google, it seems it is in their commercial offering, which I guess is a valid limitation for the free offering. However, the imageformat plugin is there, but will fail to load.

Absolutely no idea how to handle this. 

I guess, deleting the qt plugin file from your Python installation will be a valid workaround, which I am not testing myself though. 

I do not want to inhibit their commercial offering from working, by ignoring the file outright, maybe we need to ask plugins what to do when a file cannot be resolved, and allow the Qt bindings to remove well known trouble makers like this.

**Comment by kayhayen** [comment] 2022-05-15 22:07
I last tested this successfully with CPython 3.10 and PySide 6.2.2.1 it seems, that still worked just fine btw, I now used 3.9 and 6.3 which do not work.

**Comment by kayhayen** [comment] 2022-05-15 22:09
Ah yes, no such imageformat plugin `libqpdf.dylib` existed for that version of PySide6.

**Comment by kayhayen** [comment] 2022-05-15 22:34
I pushed to the factory branch a change that will make it into 0.8 and should make it work. I hard coded the name for now, please test it. With that the error should be gone.

https://nuitka.net/doc/factory.html

**Comment by ThatNerdSquared** [comment] 2022-05-15 23:13
I installed factory with this command:
```
pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"
```
Then used this command: 
```
python3 -m nuitka --follow-imports --enable-plugin=pyside6 --standalone --onefile test.py
```
With the same test example given above, I get the same error.

Looking into the commit a bit, I see that the [line that checks for the hardcoded name](https://github.com/Nuitka/Nuitka/commit/26b84ab1a49eb9d71f41882af7528142c8eb3785#diff-beb43024d97aca39850af546b9dcc2f4c4f4a5b2046d0b838981443d02196c30R829) checks for `libqtpdf.dylib`, when the problematic file is `libqpdf.dylib` (without the t).

Fixing this on my end locally and running again, the command crashes with the following output:
```
Nuitka-Inclusion:INFO: Not including forbidden DLL '/Users/nathanyeung/h4ck3r/peregrine/.venv/lib/python3.10/site-packages/PySide6/Qt/plugins/imageformats/libqpdf.dylib'.
Traceback (most recent call last):
  File "/Users/nathanyeung/h4ck3r/peregrine/.venv/lib/python3.10/site-packages/nuitka/__main__.py", line 137, in <module>
    main()
  File "/Users/nathanyeung/h4ck3r/peregrine/.venv/lib/python3.10/site-packages/nuitka/__main__.py", line 123, in main
    MainControl.main()
  File "/Users/nathanyeung/h4ck3r/peregrine/.venv/lib/python3.10/site-packages/nuitka/MainControl.py", line 978, in main
    copyDllsUsed(
  File "/Users/nathanyeung/h4ck3r/peregrine/.venv/lib/python3.10/site-packages/nuitka/freezer/Standalone.py", line 1385, in copyDllsUsed
    _fixupBinaryDLLPathsMacOS(
  File "/Users/nathanyeung/h4ck3r/peregrine/.venv/lib/python3.10/site-packages/nuitka/freezer/Standalone.py", line 1176, in _fixupBinaryDLLPathsMacOS
    had_self, rpath_map = _detectBinaryPathDLLsMacOS(
  File "/Users/nathanyeung/h4ck3r/peregrine/.venv/lib/python3.10/site-packages/nuitka/freezer/Standalone.py", line 770, in _detectBinaryPathDLLsMacOS
    had_self, resolved_result = _resolveBinaryPathDLLsMacOS(
  File "/Users/nathanyeung/h4ck3r/peregrine/.venv/lib/python3.10/site-packages/nuitka/freezer/Standalone.py", line 830, in _resolveBinaryPathDLLsMacOS
    raise NuitkaForbiddenDLLEncounter(binary_filename, "pyside6")
nuitka.Errors.NuitkaForbiddenDLLEncounter: ('/Users/nathanyeung/h4ck3r/peregrine/.venv/lib/python3.10/site-packages/PySide6/Qt/plugins/imageformats/libqpdf.dylib', 'pyside6')
```

**Comment by kayhayen** [comment] 2022-05-16 06:18
Seems the shortcut I was going to take, is not all that workable, by the time the file got copied, I was going to ignore it, but it will remain there, and never should have been there, as it's exposed to bad things. I guess, I can only make this an error exit, but not handle it. The PySide6 plugin will have to detect itself if the `QtPdf` framework needed for the plugin is available, and then not include it in the first place.

**Comment by kayhayen** [comment] 2022-05-16 06:26
On macOS, we seem to tolerate this one `libQt6Pdf.so.6 => not found` which is a bit of bug hiding.

**Comment by kayhayen** [comment] 2022-05-16 06:48
So, for the 0.8 release, I am just ignoring the plugin name unless `--experimental=qt-force-qpdf` is being used. I do not want to delay things until such time that the plugin can actually check if a provided dependency would resolve, and then only add the ones, that will or error out on unknown cases.

That way, we can solve this one for good. Also the bug hiding for Linux and potentially Windows too, has to stop. We must not include DLLs that have missing dependencies without noticing it. But that might be a very breaking change for many things, so that is delayed.

**Comment by kayhayen** [comment] 2022-05-16 06:49
Please update factory and try again, ought to work now.

**Comment by ThatNerdSquared** [comment] 2022-05-16 06:56
I can now successfully compile and run the test example. Compilation is successful with my actual project as well, although I get this error on running the binary:
```
Traceback (most recent call last):
  File "/var/folders/jn/79_mcs3903j_bb7g3gshtq5m0000gn/T//onefile_21365_1652683956_48168/__main__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/var/folders/jn/79_mcs3903j_bb7g3gshtq5m0000gn/T//onefile_21365_1652683956_48168/darkdetect/__init__.py", line 14, in <module darkdetect>
  File "/var/folders/jn/79_mcs3903j_bb7g3gshtq5m0000gn/T//onefile_21365_1652683956_48168/distutils/version.py", line 52, in __lt__
  File "/var/folders/jn/79_mcs3903j_bb7g3gshtq5m0000gn/T//onefile_21365_1652683956_48168/distutils/version.py", line 339, in _cmp
AttributeError: 'LooseVersion' object has no attribute 'version'
```

I suspect that this is probably a problem with my system though. Thanks for your work on this issue!

**Comment by kayhayen** [comment] 2022-05-16 11:01
Great news, will be in 0.8 really soon now. Closing issues when they hit stable.

**Comment by kayhayen** [comment] 2022-05-20 14:41
Part of the 0.8 release I just made.

**Closed by kayhayen** 2022-05-20 14:41 UTC
Labels: bug, factory
