### ISSUE TITLE
Compile error for a two module python file run in Command-prompt

### ISSUE THREAD

**Issue by xytsrm** [Nuitka/Nuitka#2455] opened 2023-09-21 22:22 UTC
Attempted a Nuitka compilation two different ways; each returned errors and failed to create an .exe file.
I followed the directions in the user-guide.
Verified the installation of Nuitka.
Verified that the target python program runs successfully.
The command-prompt path was set to the folder containing the target python file.

(I know screenshots aren't preferred, but I was running from the command-prompt)
![Run1](https://github.com/Nuitka/Nuitka/assets/92377239/958f74ae-4c60-4549-91fd-e9dca4554946)
![Run2](https://github.com/Nuitka/Nuitka/assets/92377239/a924c1e7-a8fc-4c32-b8fd-9c25d72035e4)

It seems to reference an issue linking a program with 7 files; there are only  two modules and no references to external files. However, there are 5 print statements that launches the command-prompt window; could the 2 .py modules and the 5 print statements be the issue?

The target python file has a main module and imports a second that contains functions; it runs in Idle, runs from the command-prompt, and pyinstaller was able to create an exe distribution that also runs.

As I am trying Nuitka for the first time; can anyone suggest why it failed to create the .exe file?

X.
 
UPDATE: Removed the print statements, while it made a difference regarding cache hits (from 0 to 6) and misses (from 7 to 1); it still failed to create an exe file.

![Run3](https://github.com/Nuitka/Nuitka/assets/92377239/17dcc7fe-8533-4d60-bad8-ddc6e3329893)

UPDATE 2:

May have found the problem:
import ctypes, sys
def Mbox(title, text, style):
    return ctypes.windll.user32.MessageBoxW(0, text, title, style)
This imports a "MsgBox" type widget for user interaction. Looks like Nuitka can't handle it.

**Comment by kayhayen** [comment] 2023-09-22 09:51
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by kayhayen** [comment] 2023-09-22 09:54
It seems your MSVC setup is entirely broken and or different from what I have seen, anything else you are writing just is pointless, not creating a binary is the issue. And command prompts support copy and past of course. Just google how they do it.

**Closed** 2023-09-22 10:05 UTC

**Comment by xytsrm** [comment] 2023-09-22 13:09
The application compiles as is, without modification using PyInstaller; so the issues are not with the application.
X.

**Comment by Maxwell175** [comment] 2023-09-22 14:15
It could be caused by some anti virus getting triggered somehow. Try whitelisting the folder you are working in. Check the inside of the .dist folder yourself and see if there are any executables generated there.
