### ISSUE TITLE
Pandas 1.0.0 ImportError: cannot import name 'generic' from 'pandas.core.groupby'

### ISSUE THREAD

**Issue by gabrieldp** [Nuitka/Nuitka#616] opened 2020-02-02 21:41 UTC
* **Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)**
Nuitka 0.6.7
Python: 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
Executable: C:\Anaconda3\envs\pandas_nuitka\python.exe
OS: Windows
Arch: x86_64

* **How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.**
Anaconda python, conda enviroment. Used pip to install nuitka and pandas.
`conda list` shows:

```
# packages in environment at C:\Anaconda3\envs\pandas_nuitka:
#
# Name                    Version                   Build  Channel
certifi                   2019.11.28               py37_0
nuitka                    0.6.7                    pypi_0    pypi
numpy                     1.18.1                   pypi_0    pypi
pandas                    1.0.0                    pypi_0    pypi
pip                       20.0.2                   py37_1
python                    3.7.0                hea74fb7_0
python-dateutil           2.8.1                    pypi_0    pypi
pytz                      2019.3                   pypi_0    pypi
setuptools                45.1.0                   py37_0
six                       1.14.0                   pypi_0    pypi
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.34.1                   py37_0
wincertstore              0.2                      py37_0

```

* **If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.**

Performed hinted compilation (using files from [Nuitka Utilities](https://github.com/Nuitka/NUITKA-Utilities/tree/master/hinted-compilation)) of the following code with `pandas` version 1.0.0 (this was in file "mwe.py"):
```
import pandas as pd
df = pd.DataFrame({'a': [1, 2, 3]})
print(df)
```

To perform compilation, used the following commands in a Windows batch file:
```
:: Activate the environment
call conda activate pandas_nuitka
:: Get hints and compile
python get-hints.py mwe.py
python nuitka-hints.py mwe.py
:: Deactivate the environment
call conda deactivate
```

Compilation worked, but when running the executable we get the following error:

```
C:\Users\<my_user>\Documents\python_projects\pandas_nuikta>mwe.dist\mwe.exe
Traceback (most recent call last):
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\mwe.py", line 1, in <module>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\__init__.py", line 54, in <module pandas>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\api.py", line 29, in <module pandas.core.api>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\groupby\__init__.py", line 1, in <module pandas.core.groupby>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\groupby\generic.py", line 60, in <module pandas.core.groupby.generic>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\frame.py", line 105, in <module pandas.core.frame>
ImportError: cannot import name 'generic' from 'pandas.core.groupby' (C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\groupby\__init__.py)
```

When downgrading `pandas` to version 0.25.0 with `pip install pandas==0.25.0`, the compilation worked and the code executed correctly:

```
C:\Users\<my_user>\Documents\python_projects\pandas_nuikta>mwe.dist\mwe.exe
   a
0  1
1  2
2  3
```

**Comment by kayhayen** [comment] 2020-02-03 07:24
Ah, this looks like the report I just looked at, except with a reproducer. Maye you can you try non-hinted compilation, to exclude bugs in that part just for our sanity, but it seems like we got some implicit import missing there.

**Comment by JorjMcKie** [comment] 2020-02-03 07:26
> seems like we got some implicit import missing there

Right, I am currently checking what those panda buddies have changed this time ...

**Comment by kayhayen** [comment] 2020-02-03 10:26
Trying to reproduce it with whatever my Debian has, gave me this kind of error:

```
  File "./nuitka/freezer/Standalone.py", line 1538, in copyDataFiles
    for source_desc, target_filename in data_files:
ValueError: not enough values to unpack (expected 2, got 0)

```

So first of all, I am distracting myself with moving the data files collection into `copyDataFiles` itself, so there is a better chance at knowing the guilty plugin, I'm assigning you @JorjMcKie if you don't mind.

**Comment by kayhayen** [comment] 2020-02-03 19:39
Did that, and now I am distracting myself with nicer logging, per plugin with plugin name added automatically. I think my bug is a Debian only bug about timezone files, so don't worry about me.

**Comment by gabrieldp** [comment] 2020-02-03 22:15
> Ah, this looks like the report I just looked at, except with a reproducer. Maye you can you try non-hinted compilation, to exclude bugs in that part just for our sanity, but it seems like we got some implicit import missing there.

I tried it without the hinted compilation by running the bat file:
```
:: Activate the environment
call conda activate pandas_nuitka
:: Compile unhinted
python -m nuitka --standalone --enable-plugin=numpy mwe.py 
:: Deactivate the environment
call conda deactivate
```
Both with `pandas 0.25.0` and `pandas 1.0.0` I got the same output during compilation (not sure how to use the `--include-plugin-directory` or `--include-plugin-files` options, but compilation worked nevertheless despite the warnings so let me know if this is something you'd like me to test):
```
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\envs\pandas_nuitka\lib\site-packages\numpy\core\function_base.py:506' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\envs\pandas_nuitka\lib\site-packages\numpy\lib\utils.py:393' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\envs\pandas_nuitka\lib\site-packages\numpy\lib\utils.py:887' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\envs\pandas_nuitka\lib\site-packages\numpy\lib\utils.py:945' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Anaconda3\envs\pandas_nuitka\lib\site-packages\pandas\__init__.py:11' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:INFO:Copied 1 file from 'numpy' installation.
```

For `pandas 1.0.0` I got the same error as before, with the hinted compilation:
```
C:\Users\<my_user>\Documents\python_projects\pandas_nuikta>mwe.dist\mwe.exe
Traceback (most recent call last):
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\mwe.py", line 1, in <module>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\__init__.py", line 54, in <module pandas>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\api.py", line 29, in <module pandas.core.api>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\groupby\__init__.py", line 1, in <module pandas.core.groupby>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\groupby\generic.py", line 60, in <module pandas.core.groupby.generic>
  File "C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\frame.py", line 105, in <module pandas.core.frame>
ImportError: cannot import name 'generic' from 'pandas.core.groupby' (C:\Users\<my_user>\Documents\python_projects\pandas_nuikta\mwe.dist\pandas\core\groupby\__init__.py)
```
For `pandas 0.25.0` it worked as expected.

By the way, great work with Nuitka, you guys are rockstars, hope I can help it get even better. Any plans to include hinted compilation into vanilla Nuitka, without requiring external utilities?

**Comment by lexxish** [comment] 2020-02-04 17:37
call `conda activate pandas_nuitka`

Can this be done without conda?

**Comment by gabrieldp** [comment] 2020-02-04 20:39
> call `conda activate pandas_nuitka`
> 
> Can this be done without conda?

This is me activating a `conda` environment called `pandas_nuitka` (could be called `foo`, or whatever else), there's nothing special about it, the rest of the commands should work the same whether it's within an environment or not. 
I suppose one could use `virtualenv` or even no environments at all, therefore not relying on `conda`.

**Comment by TBWarrington** [comment] 2020-02-10 23:57
I'm having the same problem. Following in hopes of a solution.

**Comment by kayhayen** [comment] 2020-02-11 12:50
So this seems to be the same as #618 at the heart, Nuitka does not currently handle the importing compatible enough to allow recursive imports as well as CPython does right now.

**Comment by manukgitn** [comment] 2020-07-15 07:11
Hello,
Does this bug with cyclic imports solved?

In #618 it seems solved, but meet similar problem on standalone binary built by nuitka(0.6.9rc5):
Traceback (most recent call last):
  File "somepath/my_staff.dist/mo_staff.py", line 10, in <module>
  File "somepath/my_staff.dist/pandas/__init__.py", line 55, in <module pandas>
  File "somepath/my_staff.dist/pandas/core/api.py", line 29, in <module pandas.core.api>
  File "somepath/my_staff.dist/pandas/core/groupby/__init__.py", line 1, in <module pandas.core.groupby>
  File "somepath/my_staff.dist/pandas/core/groupby/generic.py", line 60, in <module pandas.core.groupby.generic>
  File "somepath/my_staff.dist/pandas/core/frame.py", line 105, in <module pandas.core.frame>
ImportError: cannot import name 'generic' from 'pandas.core.groupby' (somepath/my_staff.dist/pandas/core/groupby/__init__.py)

Used version of nuitka:
python3.8 -m nuitka --version
0.6.9rc5
Python: 3.8.4rc1 (default, Jul 14 2020, 21:15:24) 
Executable: /usr/local/bin/python3.8
OS: Linux
Arch: x86_64

Command creating binary:
python3.8 -m nuitka -j 2 --standalone --follow-imports --show-modules --output-dir=my_bin mo_staff.py

**Comment by kayhayen** [comment] 2020-07-15 07:45
A minimal reproducer would be fine. I have not looked into this since, but given one, this could be trivial to fix now.

**Comment by manukgitn** [comment] 2020-07-15 08:02
Minimal reproducing example
[toy2.zip](https://github.com/Nuitka/Nuitka/files/4923734/toy2.zip)

**Command to build:**
python3.8 -m nuitka -j 2 --standalone --follow-imports --show-modules --output-dir=my_bin_2 toy2.py

**Comment by kayhayen** [comment] 2020-07-15 08:07
That's really minimal indeed.

**Comment by manukgitn** [comment] 2020-07-15 08:19
Yep, thought it would be harder splitting original program into reproducible one, but...
Got lucky

**Comment by oli71** [comment] 2020-07-15 13:48
I think i have the same issue as reported here, on a quite different Setup so this is checked. - Hoping for help.

I have a **32Bit pip setup of Python on Windows**.
Using 32Bit mingw:
CC=C:\Program Files (x86)\mingw-w64\i686-8.1.0-posix-dwarf-rt_v6-rev0\mingw32\bin\gcc.exe

Checking on nuitka hello.py, but added a _import pandas_

**>**python -m nuitka --standalone --mingw64 --follow-imports --plugin-enable=numpy --plugin-enable=tk-inter hello.py
Nuitka-Plugins:INFO: Injecting plug-in based pre load code for module 'tkinter':
Nuitka-Plugins:INFO:     Need to make sure we set environment variables for TCL.
Nuitka-Plugins:INFO: numpy: Copied 1 file from 'numpy' installation.

closes correctly.
When starting hello.py:
Traceback (most recent call last):
  File "D:\Daten\OPC-Client\HelloNuitka\hello.dist\hello.py", line 1, in <module>
  File "D:\Daten\OPC-Client\HelloNuitka\hello.dist\pandas\__init__.py", line 54, in <module pandas>
  File "D:\Daten\OPC-Client\HelloNuitka\hello.dist\pandas\core\api.py", line 29, in <module pandas.core.api>
  File "D:\Daten\OPC-Client\HelloNuitka\hello.dist\pandas\core\groupby\__init__.py", line 1, in <module pandas.core.groupby>
  File "D:\Daten\OPC-Client\HelloNuitka\hello.dist\pandas\core\groupby\generic.py", line 60, in <module pandas.core.groupby.generic>
  File "D:\Daten\OPC-Client\HelloNuitka\hello.dist\pandas\core\frame.py", line 105, in <module pandas.core.frame>
ImportError: cannot import name 'generic' from 'pandas.core.groupby' (D:\Daten\OPC-Client\HelloNuitka\hello.dist\pandas\core\groupby\__init__.py)


**>**python -m nuitka --version
0.6.8.4
Python: 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 18 2019, 23:46:00) [MSC v.1916 32 bit (Intel)]
Executable: c:\users\...\appdata\local\programs\python\python37-32\python.exe
OS: Windows
Arch: x86

**>**pip list
Package         Version
--------------- ------------
aiofiles        0.4.0
aiosqlite       0.11.0
altgraph        0.17
asn1crypto      1.3.0
asyncua         0.8.2
cffi            1.14.0
cryptography    2.8
cycler          0.10.0
et-xmlfile      1.0.1
Events          0.3
future          0.18.2
h5py            2.10.0
idlex           1.18
jdcal           1.4.1
joblib          0.14.1
kiwisolver      1.1.0
lxml            4.5.0
matplotlib      3.2.0
mpi4py          3.0.3
mpmath          1.1.0
Nuitka          0.6.8.4
numpy           1.18.1
opcda           1.0
openpyxl        3.0.3
packaging       20.3
pandas          1.0.1
pefile          2019.4.18
pip             20.1.1
pip-review      1.0
plotly          4.5.3
psutil          5.7.0
pycparser       2.20
pyinstaller     4.0.dev0
pykalman        0.9.5
pyparsing       2.4.6
Pyro4           4.79
python-dateutil 2.8.1
pytz            2019.3
pywin32         227
pywin32-ctypes  0.2.0
retrying        1.3.3
scikit-learn    0.22.2.post1
scipy           1.4.1
serpent         1.30.2
setuptools      46.0.0
six             1.14.0
sklearn         0.0
sympy           1.5.1
tornado         6.0.4

**Comment by kayhayen** [comment] 2020-08-01 09:35
Turns out, not a duplicate at all, but a separate bug in the importing mechanism for Python3, that should now be yet again more compatible, and works for me now.

**Comment by kayhayen** [comment] 2020-08-01 09:36
The fix has been on factory for a while, and is now in the latest pre-release on develop.

**Comment by kayhayen** [comment] 2020-10-02 10:59
This is the last release 0.6.9 already for a while.

**Closed by kayhayen** 2020-10-02 10:59 UTC
Labels: bug
