### ISSUE TITLE
package seedir is missing datafiles without datafile inclusion options

### ISSUE THREAD

**Issue by Justaus3r** [Nuitka/Nuitka#1140] opened 2021-06-22 15:55 UTC
Nuitka version:
```
$ python -m nuitka --version
0.6.15
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
Executable: C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
```
Python version:
```
$ python --version
Python 3.8.3
```
Minimal reproducer(needs [seedir](https://pypi.org/project/seedir/))
```
import os 
import seedir as sdir
while True:
    usr_input = input(">>")
    if usr_input == 'help':
        print("help")
    elif usr_input == 'treelist':
        sdir.seedir(os.getcwd())
    else:
        print("other")              

```
running the executable results in 
```
C:\Users\Administrator\Desktop\penta.buildd\Penta\minimal_ex.dist>minimal_ex.exe
Traceback (most recent call last):
  File "C:\Users\ADMINI~1\Desktop\PENTA~1.BUI\Penta\MINIMA~1.DIS\minimal_ex.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\ADMINI~1\Desktop\PENTA~1.BUI\Penta\MINIMA~1.DIS\seedir\__init__.py", line 24, in <module seedir>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\ADMINI~1\Desktop\PENTA~1.BUI\Penta\MINIMA~1.DIS\seedir\realdir.py", line 15, in <module seedir.realdir>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\ADMINI~1\Desktop\PENTA~1.BUI\Penta\MINIMA~1.DIS\seedir\folderstructure.py", line 10, in <module seedir.folderstructure>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\ADMINI~1\Desktop\PENTA~1.BUI\Penta\MINIMA~1.DIS\seedir\folderstructurehelpers.py", line 11, in <module seedir.folderstructurehelpers>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\Users\ADMINI~1\Desktop\PENTA~1.BUI\Penta\MINIMA~1.DIS\seedir\printing.py", line 67, in <module seedir.printing>
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\Desktop\\PENTA~1.BUI\\Penta\\MINIMA~1.DIS\\seedir\\words.txt'

```
i have to manually add a directory called ```seedir``` and words.txt ,after which the executable runs fine..

**Comment by kayhayen** [comment] 2021-06-23 08:33
There are datafile inclusion options for that, consider the user manual. This could be made automatic, but I guess I want to defer it. For onefile to work, that would be required even, as there is no file copy.

**Comment by kayhayen** [comment] 2021-12-16 15:05
Since we adding yaml config for data files, I have tried your example and added a small config snippet that makes it work out of the box to factory branch, will be in next release or maybe even hotfix.

**Comment by kayhayen** [comment] 2021-12-16 15:06
https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment] 2021-12-16 16:03
Let me know if there is more datafiles to add with other reproducers.

**Comment by Justaus3r** [comment] 2021-12-16 20:09
Thanks!,and yeah these are the only data files needed for this package.

**Comment by kayhayen** [comment] 2021-12-20 17:14
Part of the current hotfix release.

**Closed by kayhayen** 2021-12-20 17:14 UTC
Labels: enhancement
