### ISSUE TITLE
Generate compile_commands.json (Bump scons version to 4.x)

### ISSUE THREAD

**Issue by n-bes** [Nuitka/Nuitka#2901] opened 2024-06-05 12:51 UTC
I would like to analyze generated *.c files. Scons 4.x [can produce](https://scons.org/doc/production/HTML/scons-user/ch27.html) `compile_commands.json` which works with most tools. 

Could you update scons and enable `env.CompilationDatabase()`? 

```shell
# nuitka3 --version
2.3
Commercial: None
Python: 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
Flavor: Unknown
Executable: /usr/bin/python3
OS: Linux
Arch: aarch64
Distribution: Ubuntu (based on Debian) 24.04
Version C compiler: /usr/bin/gcc (gcc 13).
```

```shell
# python3 /usr/local/lib/python3.12/dist-packages/nuitka/build/inline_copy/bin/scons.py -v
SCons by Steven Knight et al.:
	engine: v3.1.2.bee7caf9defd6e108fc2998a2520ddb36a967691, 2019-12-17 02:07:09, by bdeegan on octodog
	engine path: ['/usr/local/lib/python3.12/dist-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons']
Copyright (c) 2001 - 2019 The SCons Foundation
```

**Comment by kayhayen** [comment] 2024-06-08 12:22
On Windows, we use 4.3 from the inline copy, I think older ones for non-Windows, mostly to not have the version count explode, but you can just install whatever scons you want and it will get used.

**Comment by kayhayen** [comment] 2024-06-08 12:24
I am not using newer Scons with Linux because it has dropped support for older Python without adding anything meaningful to me and I don't want to apply our hacks to multiple inline copies and deal with their regressions unless absolutely necessary. The inline copy is going to be fastest to use for all I know.

**Comment by n-bes** [comment] 2024-06-08 14:32
> you can just install whatever scons you want and it will get used.

I tried without success. How can I override path to scons?

**Comment by kayhayen** [comment] 2024-06-08 17:52
Seems you have to delete the inline copy, which is e.g. done for Debian packages. I will add an experimental option to force using the system scons path.

**Comment by kayhayen** [comment] 2024-06-08 17:56
Use `--experimental=force-system-scons` and use factory version.

**Comment by kayhayen** [comment] 2024-06-08 17:56
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by n-bes** [comment] 2024-06-09 18:54
> Use --experimental=force-system-scons and use factory version.
## Scons 4.3
Without flag: 
```
Nuitka-Scons: Scons command: /usr/local/bin/scons ...
```

With flag:
```
Nuitka-Scons: Scons command: /usr/bin/python3 -W ignore /usr/local/lib/python3.10/dist-packages/nuitka/build/inline_copy/bin/scons.py
```

I patched `Backend.scons`:
```
sed -i '320i env.Tool("compilation_db")' /usr/local/lib/python3.10/dist-packages/nuitka/build/Backend.scons
sed -i '321i env.CompilationDatabase()' /usr/local/lib/python3.10/dist-packages/nuitka/build/Backend.scons
```
And `compiles_command.json` is not generated... Probably, i missed something

## Scons 4.7
Failed with flag:

```
scons: Reading SConscript files ...
AttributeError: module 'SCons.dblite' has no attribute 'dblite':
	File "/usr/local/lib/python3.10/dist-packages/nuitka/build/Backend.scons", line 102:
		initScons()
	File "/usr/local/lib/python3.10/dist-packages/nuitka/build/SconsUtils.py", line 45:
		SCons.dblite.dblite.sync = no_sync
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.

```

**Comment by kayhayen** [comment] 2024-06-10 11:42
Nuitka is trying to monkey patch the dblite usage away:

```
    # Avoid scons writing the scons database at all, spell-checker: ignore dblite
    import SCons.dblite  # pylint: disable=I0021,import-error

    SCons.dblite.dblite.sync = no_sync
```

Probably, it moved some other place or got renamed. I don't look at newer Scons myself, please figure it out.

**Comment by kayhayen** [comment] 2024-06-12 08:26
So, the part I did for allowing your experiments is on develop now.

**Comment by kayhayen** [comment] 2024-07-20 13:06
This is part of the stable release 2.4 that I just made.

**Closed by kayhayen** 2024-07-20 13:06 UTC
Labels: enhancement, help wanted, develop
