### ISSUE TITLE
Pyside6 App Builds and Runs Ok With Nuitka 1.86 But Builds and Fails To run On Nuitka 1.9 through to 2.01 - Now has MRE

### ISSUE THREAD

**Issue by David-Worboys** [Nuitka/Nuitka#2690] opened 2024-02-04 08:15 UTC
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
**1.9
Commercial: None
Python: 3.11.7 (main, Feb  4 2024, 09:52:17) [GCC 11.4.0]
Flavor: Unknown
Executable: /home/david/PycharmProjects/pydev3117_noshare/bin/python
OS: Linux
Arch: x86_64
Distribution: Linuxmint (based on Ubuntu) 21.3
Version C compiler: /usr/bin/gcc (gcc 11).**

- How did you install Nuitka and Python
**I use the Pycharm Python Package Tools To Install Nuitka And Python into a virtual environment setup with venv**

- The specific PyPI names and versions
**Note this is the the freeze from the Nuitka 1.9 install. For The Nutika 1.86 build I delete Nuitka 1.9 and install Nuitka 1.86 - This is the only difference in the freeze list**

`appdirs==1.4.4
asyncio~=3.4.3
attrs==23.2.0
certifi==2024.2.2
charset-normalizer==3.3.2
fs==2.4.16
idna==3.6
netifaces==0.11.0
**Nuitka==1.9**
numpy==1.26.3
ordered-set==4.1.0
pathvalidate==3.2.0
platformdirs==4.1.0
psutil==5.9.8
pycryptodome==3.20.0
PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
python-dateutil==2.8.2
pytz==2023.3
PyYAML==6.0.1
regex==2023.8.8
requests==2.31.0
shellescape==3.8.1
shiboken6==6.6.1
six==1.16.0
titlecase==2.4.1
typing==3.7.4.3
tzlocal==5.2
urllib3==2.2.0
xmltodict==0.13.0
zstandard==0.22.0`

- Many times when you get an error from Nuitka, your setup may be special

**When compiled with Nuitka 1.86 the program installed on a minimal, clean install of Mx Linux  produces this output as it launches the program:**

**Note the programs runs correctly and passes all tests**

```
$ ./black-dvd-archiver_1_86
qt.multimedia.ffmpeg.libsymbolsresolver: Couldn't load VAAPI library

```  

**When compiled with Nuitka 1.9 and above the program installed on a minimal, clean install of Mx Linux produces this output and the program never starts:**

**Note the programs never starts after the below error**

```

$ ./black-dvd-archiver_1_9
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vkkhrdisplay, wayland, eglfs, minimal, offscreen, xcb, minimalegl, wayland-egl, vnc, linuxfb.

```

- Also supply a Short, Self Contained, Correct, Example

```
import sys

from PySide6.QtCore import QPoint, QTimer, QTime, Qt
from PySide6.QtGui import (QGuiApplication, QPainter, QPalette, QPolygon, QRasterWindow)

class AnalogClockWindow(QRasterWindow):

    def __init__(self):
        super().__init__()
        self.setTitle("Analog Clock")
        self.resize(200, 200)

        self._timer = QTimer(self)
        self._timer.timeout.connect(self.update)
        self._timer.start(1000)

        self._hour_hand = QPolygon([QPoint(5, 14), QPoint(-5, 14),
                                    QPoint(-4, -71), QPoint(4, -71)])
        self._minute_hand = QPolygon([QPoint(4, 14), QPoint(-4, 14),
                                      QPoint(-3, -89), QPoint(3, -89)])
        self._seconds_hand = QPolygon([QPoint(1, 14), QPoint(-1, 14),
                                       QPoint(-1, -89), QPoint(1, -89)])

        palette = qApp.palette()
        self._background_color = palette.color(QPalette.Window)
        self._hour_color = palette.color(QPalette.Text)
        self._minute_color = palette.color(QPalette.Text)
        self._seconds_color = palette.color(QPalette.Accent)

    def paintEvent(self, e):
        with QPainter(self) as painter:
            self.render(painter)

    def render(self, painter):
        width = self.width()
        height = self.height()

        side = min(width, height)

        painter.fillRect(0, 0, width, height, self._background_color)
        painter.setRenderHint(QPainter.Antialiasing)
        painter.translate(width / 2, height / 2)
        painter.scale(side / 200.0, side / 200.0)

        time = QTime.currentTime()

        painter.setPen(Qt.NoPen)
        painter.setBrush(self._hour_color)

        painter.save()
        painter.rotate(30.0 * ((time.hour() + time.minute() / 60.0)))
        painter.drawConvexPolygon(self._hour_hand)
        painter.restore()

        for i in range(0, 12):
            painter.drawRect(73, -3, 16, 6)
            painter.rotate(30.0)

        painter.setBrush(self._minute_color)

        painter.save()
        painter.rotate(6.0 * time.minute())
        painter.drawConvexPolygon(self._minute_hand)
        painter.restore()

        painter.setBrush(self._seconds_color)

        painter.save()
        painter.rotate(6.0 * time.second())
        painter.drawConvexPolygon(self._seconds_hand)
        painter.drawEllipse(-3, -3, 6, 6)
        painter.drawEllipse(-5, -68, 10, 10)
        painter.restore()

        painter.setPen(self._minute_color)

        for j in range(0, 60):
            painter.drawLine(92, 0, 96, 0)
            painter.rotate(6.0)


if __name__ == "__main__":
    app = QGuiApplication(sys.argv)
    clock = AnalogClockWindow()
    clock.show()
    sys.exit(app.exec())
```
Freeze
```
Nuitka==1.8.6
ordered-set==4.1.0
PySide6==6.6.1
PySide6-Addons==6.6.1
PySide6-Essentials==6.6.1
shiboken6==6.6.1
zstandard==0.22.0

```
Compile Command - Nuitka==1.8.6 works on a clean Mx install, Nuitka==1.9 and above fails
```
python -m nuitka                                                                            \
--report=build_report                                                                       \
--show-anti-bloat-changes                                                                   \
--assume-yes-for-downloads                                                                  \
--follow-imports                                                                            \
--lto=yes                                                                                   \
--python-flag=-OO                                                                           \
--python-flag=no_warnings                                                                   \
--python-flag=isolated                                                                      \
--verbose                                                                                   \
--verbose-output=./release/verbose.txt                                                      \
--disable-console                                                                           \
--static-libpython=yes                                                                      \
--standalone                                                                                \
--onefile                                                                                   \
--prefer-source-code                                                                        \
--include-qt-plugins=sensible,multimedia                                                    \
--enable-plugin=pyside6                                                                     \
--output-filename=ana_clock                                                        \
--output-dir=./release                                                                      \
 main.py

```

On a clean minimal Mx install the results are

Result - Nuitka 1.9 and above

```
$ ./ana_clock
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vkkhrdisplay, wayland, eglfs, minimal, offscreen, xcb, minimalegl, wayland-egl, vnc, linuxfb.

```

Result - Nuitka 1.86 
No errors:
`./ana_clock_1_86`

- Provide in your issue the Nuitka options used
**This is the Nuitka command to build the app - aside from report/verbose options all the other options are required**
```
python -m nuitka                                                                            \
--report=build_report                                                                       \
--show-anti-bloat-changes                                                                   \
--assume-yes-for-downloads                                                                  \
--lto=yes                                                                                   \
--python-flag=-OO                                                                           \
--python-flag=no_warnings                                                                   \
--python-flag=isolated                                                                      \
--verbose                                                                                   \
--verbose-output=./release/verbose.txt                                                      \
--disable-console                                                                           \
--static-libpython=yes                                                                      \
--standalone                                                                                \
--onefile                                                                                   \
--prefer-source-code                                                                        \
--include-module=dbm                                                                        \
--include-module=dbm.gnu                                                                    \
--include-module=dbm.ndbm                                                                   \
--include-module=dbm.dumb                                                                   \
--include-qt-plugins=sensible,multimedia                                                    \
--show-anti-bloat-changes                                                                   \
--enable-plugin=pyside6                                                                     \
--output-filename=black-dvd-archiver                                                        \
--output-dir=./release                                                                      \
--linux-icon=/home/david/PycharmProjects/dvdarch/pycode/logo.jpg                            \
--include-data-files=*.svg=./                                                               \
--include-data-files=*.jpg=./                                                               \
--include-data-files=LICENSE.md=./                                                          \
--include-data-dir=/home/david/PycharmProjects/dvdarch/pycode/tool_apps=./tool_apps         \
--include-data-dir=/home/david/PycharmProjects/dvdarch/pycode/icons=./icons                 \
--include-data-dir=/home/david/PycharmProjects/dvdarch/pycode/IBM-Plex-Mono=./IBM-Plex-Mono \
 dvdarchiver.py

```
- Note if this is a regression

 **This is a regression - Nuitka 1.8 series compiles and runs successfully on a minimal, clean install of Mx Linux. Nuitka 1.9 and above compiles but does not run on a minimal, clean install of Mx Linux**

**Note in the Nuitka 1.8 series I had to add the following to get a successful compile**

```
--include-module=dbm.gnu                                                                    \
--include-module=dbm.ndbm                                                                   \
--include-module=dbm.dumb                                                                   \

```

- Consider getting commercial support

- The files might help
[build_report_1_9.xml.txt](https://github.com/Nuitka/Nuitka/files/14156016/build_report_1_9.xml.txt)
[build_report_1_86.xml.txt](https://github.com/Nuitka/Nuitka/files/14156017/build_report_1_86.xml.txt)

**The problem is not with the *-package.config.yml files as I copied the Nuitka 1.9 versions to Nuitka 1.86 and Nuitka 1.86 still compiled and ran correctly on a minimal, clean install of Mx Linux**

**I will note that the Nuikta 1.9 build is missing 149  lfiles compared to Nuitaka 1.86**

**Comment by KevinRodriguez777** [comment] 2024-02-04 08:20
it's hard to test regressions with MWE / MRE,  can you please provide one?

**Comment by David-Worboys** [comment] 2024-02-04 08:22
The attached build_report files might be the most useful in determining the regression cause - I am still studying them

**Comment by kayhayen** [comment] 2024-02-04 10:37
There were regressions long fixed with later 1.9 hotfix releases, and 2.0 is the current release, so this is probably just not following what the template was asking for.

**Comment by David-Worboys** [comment] 2024-02-04 11:08
Ok, Included a minimal example in my original post - I can get this problem on all versions of Nuitka from 1.9 to latest 2.01.  I would expect this minimal example to work on any clean Linux install but it certainly does not on Mx

**Comment by David-Worboys** [comment] 2024-02-04 11:15
And the results from a 2.01 with my minimal example on a clean Mx install is the same as with 1.9. Nuitka 1.86 works

./ana_clock_2_01
qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: vkkhrdisplay, wayland, eglfs, minimal, offscreen, xcb, minimalegl, wayland-egl, vnc, linuxfb

**Comment by David-Worboys** [comment] 2024-02-04 11:27
Kay I think this is a live issue and should be re-opened

**Comment by kayhayen** [comment] 2024-02-04 11:37
> qt.qpa.plugin: From 6.5.0, xcb-cursor0 or libxcb-cursor0 is needed to load the Qt xcb platform plugin.

So this will be a DLL issue purely, your code is probably irrelevant, since you got a kind of hello Qt world issue going on. I am assuming that e.g. `tests/standalone/PySide6Using.py` is not going to work for you either. A report from 2.0.x would be great, since it's going to include details which PySide6 installation method you are attempting to distribute, and an improved picture on DLLs.

As of 1.9 the Linux standalone got a lot better by not including system DLLs as much. Your inability to run it though, seems to imply that those DLls may either have to be installed for Qt programs to work, or were failed to include.

**Comment by David-Worboys** [comment] 2024-02-04 12:07
Your wish is my command Kay, a 2.01 build report for the minimal example is attached: 

[build_report.xml.txt](https://github.com/Nuitka/Nuitka/files/14156626/build_report.xml.txt)

I was kind of wondering if this was related to anti-bloat as  I noted in my original post that the Nuikta 1.9 build is missing 149 files compared with Nuitaka 1.86. 2.01 is kind of similar.

**Comment by kayhayen** [comment] 2024-02-04 12:15
The portability of builds on Linux is limited, which is described in the user manual. Same machine ought to work. I understand you are having issues with same machine.

**Comment by kayhayen** [comment] 2024-02-04 12:17
Your report doesn't contain any references to any DLL names "cursor", so if the expectation of Qt as expressed need to be met, then we need to find out where it should come from.

**Comment by kayhayen** [comment] 2024-02-04 12:18
```
  <distributions>
    <distribution name="PySide6" version="6.6.1" installer="pip" />
    <distribution name="PySide6-Addons" version="6.6.1" installer="pip" />
    <distribution name="PySide6-Essentials" version="6.6.1" installer="pip" />
    <distribution name="shiboken6" version="6.6.1" installer="pip" />
  </distributions>
```

So indeed, pip installed, and not Debian installed, that ought to be pretty portable by itself.

**Comment by David-Worboys** [comment] 2024-02-04 23:10
I can confirm, comparing 1.86 and 1.9 that the cursor files are missing  in 1.9 and - therefore - likely  missing in 2.01

**From my missing file list:**
/home/david/PycharmProjects/dvdarch/pycode/1_9_Missing/libXcursor.so.1
/home/david/PycharmProjects/dvdarch/pycode/1_9_Missing/libwayland-cursor.so.0
/home/david/PycharmProjects/dvdarch/pycode/1_9_Missing/libxcb-cursor.so.0

**Comment by kayhayen** [comment] 2024-02-05 08:58
So, Qt programs can only run if a few OS dependencies are installed. X11 or wayland seem to be among them. Nuitka no longer includes OS dependencies like these ones, the reason is simply that they conflict easily with other OS parts from the native system. I seem to remember the list of things required for PySide6 to be able to run is listed on their site somewhere, but I didn't immediately find it.

This was previously discussed in other issues, and other solutions were attempted, like making this optional.

```
-  Linux: Standalone builds with PyPI packages no longer include system
   DLLs unless a new Yaml configuration for DLLs called
   ``package-system-dlls`` is configured, which will be necessary for
   GTK bindings probably. With this the included DLLs will more often be
   only ones suitable for use on other OSes. This should make Linux
   standalone somewhat easier, but still need to compile on old OS.
```

You would have to add for PySide6 and/or shiboken6 these settings, if you you desire to do it. Currently GTK is not done like that yet, so there is no example yet, and the docs are also not updated.

For PyPI packages however, this is not the default. If you used Ubuntu PySide6, it will gladly create a dist folder that will work with that specific OS version of Ubuntu, if that is what you want. These are not too portable. Your OS libraries however are no more portable than that. With GTK there is an exception needed, because they do not contain anything GTK at all unless you provide it youself, so it has to be bad. Luckily for Qt bindings, we have a better situation.

One previous issue linked the list of requirements, but I am not looking it up now.

**Comment by kayhayen** [comment] 2024-02-05 09:00
At this point, it's mainly a documentation issue to add these things. I will probably do it once I deal with the other issues that occured with using system libraries, that are probably lingering or closed already, not sure now.

**Closed** 2024-02-05 09:00 UTC
Labels: invalid

**Comment by David-Worboys** [comment] 2024-02-05 21:58
Thank you the update Key. and providing the details of your investigation. 

I will try and get 2.01 working after my next release and let you know if I do.

As an aside,  I aim to have my Linux builds work out of the box on the Distrowatch top 3 and  Unbuntu . Hopefully they work on more than that!

**Comment by David-Worboys** [comment] 2024-02-27 03:18
Just in case it helps anyone, 

Adding these 3 files manually gets my python (3.11.7) Qt (6.6.3) app compiled with Nutika 2.05 working on a minimal Mx Linux install:
 
libwayland-cursor.so.0
libxcb-cursor.so.0
libXcursor.so.1

I put them in a folder called add_lib and added them via this line in my compile script

--include-data-files=/home/david/PycharmProjects/dvdarch/pycode/add_lib/*.*=./              \

**Comment by kayhayen** [comment] 2024-02-27 09:58
The OS would have to bring these files, it's not for applications to include them though @David-Worboys so it's a bit of an extreme case, esp. as these DLLs can easily conflict with the system DLLs they need. You are on your own there indeed.

**Comment by David-Worboys** [comment] 2024-02-27 20:24
I guess I am not on my own as Nuitka prior to 1.9 copied these files into the build. In fact the versions I am using came from a Nuitka 1.86 (IIRC) build just in case you did patchelf magic! Given they are unpacked into the app tmp folder when the app starts and deleted when the app closes there is little to no risk these files will bother anything else.

**Comment by kayhayen** [comment] 2024-02-28 08:41
Yes, you can use the version with the old behaviour for as long as you want, or you can make yaml configuration that will make the new one do it. I am considering it a grave bug to include these DLLs into a distribution that is intended to run on different OSes, esp. ones with these DLLs available.

**Comment by David-Worboys** [comment] 2024-02-28 21:47
I agree with you Kay, it got me over the hump but it is not the long term solution as libraries that use the cursor so files might change their API and cause a crash. I will look at the yaml configuration and see if I can make it work with that.

I notice on web searches more than a few Qt users have met these problem e.g https://forum.qt.io/topic/145196/could-not-load-the-qt-platform-plugin-xcb-in-even-though-it-was-found/6

**Comment by kayhayen** [comment] 2024-02-29 18:49
Well, yes, Qt has requirements for systems supported, and Nuitka's task cannot be to fulfil them, although it may have appeared to work in the past.

**Comment by bersbersbers** [comment] 2024-06-24 08:35
I have been bitten by this a number of times, and I always wondered why `pyinstaller` worked while `nuitka` would not. Turns out, they have had exactly the observations and discussions, the only difference being that they have not (yed) decided to not include system DLLs.
https://github.com/pyinstaller/pyinstaller/issues/6993

This is just an fyi for other people coming across this issue via Google, not meant to start a discussion how `nuitka` should behave.
