### ISSUE TITLE
opencv videoCaputure doesn't work; TypeError: Incorrect type of self (must be 'VideoCapture' or its derivative)

### ISSUE THREAD

**Issue by danielj-genesis** [Nuitka/Nuitka#1871] opened 2022-11-05 16:51 UTC
Nuitka version installed with pip:
```
1.1.8
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\dan\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
opencv-python==4.5.5.64

breaking line:
`if not cap.isOpened():
`
Simple example:
```
import numpy as np
import cv2 as cv


cap = cv.VideoCapture('demo.mp4)
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
```
build command: 
`python -m nuitka --standalone --enable-plugin=numpy --include-data-files=demo.mp4=demo.mp4 entry.py`

Error:
```
Traceback (most recent call last):
  File "C:\Users\dan\Desktop\label\democv\ENTRY~1.DIS\entry.py", line 6, in <module>
TypeError: Incorrect type of self (must be 'VideoCapture' or its derivative)
```
I get no issues running the python file or using cv2 to read an image, but videoCapure always gives that type error, is there a problem with the capture backend/ffmpeg?

**Comment by ioctl-user** [comment] 2022-11-06 06:34
nuitka version 1.1.6
opencv-python  4.5.5.64
Python 3.10.8

The same problem.

**Comment by kayhayen** [comment] 2022-11-06 09:08
Same on a machine with a camera, so i don't know if I can reproduce it like this. Can you give me some kind of instructions, or does upgrading to 4.6 fix it for you too? In which case I would have to downgrade to reproduce, but I somehow doubt that is the problem.

**Comment by kayhayen** [comment] 2022-11-06 09:15
I find it suspicious that it is for video capture, maybe a DLL problem that makes it lack support. I wonder what `cap` gives for `type`.

**Comment by kayhayen** [comment] 2022-11-06 09:36
Trying to reproduce it, pure Python gives me "cannot open camera" which I understand is kind of the expected output there, is it? With 4.6 I cannot reproduce the issue right now though. Makes me assume that the machine needs a camera for this to fail, which I can try as well.

**Comment by kayhayen** [comment] 2022-11-06 09:47
Checking if I can find it in the source, the 4.6 changed fundamentally how the extension module is loaded. Seems 4.6 is more healthy. I am adding a warning for using before 4.6, because I don't see myself spending time on old OpenCV2 now, definitely outside of Nuitka commercial: https://nuitka.net/doc/commercial.html so I recommend you just downgrade on get in touch with me to purchase a day of my time to investigate.

For now, I think this should trigger the adding of a package configuration, that warns about usage before 4.6 and recommends using 4.6 or higher instead.

**Comment by kayhayen** [comment] 2022-11-06 10:24
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by ioctl-user** [comment] 2022-11-06 13:08
So, here is my example:

```
#!/usr/bin/python3

import numpy as np
import cv2 as cv
cap = cv.VideoCapture(0)
print (type(cap))
if not cap.isOpened():
    print("Cannot open camera")
    exit()
while True:
    # Capture frame-by-frame
    ret, frame = cap.read()
    # if frame is read correctly ret is True
    if not ret:
        print("Can't receive frame (stream end?). Exiting ...")
        break
    # Our operations on the frame come here
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    # Display the resulting frame
    cv.imshow('frame', gray)
    if cv.waitKey(1) == ord('q'):
        break
# When everything done, release the capture
cap.release()
cv.destroyAllWindows()
```

Type of cap is ` <class 'cv2.VideoCapture'>` in python interpretation and in nuitka-built binary. The same type in python interpretation with non-existing camera number, and the same type in nuitka-built binary with non-existing camera number. And in both cases binary file returns the same error.

Upgrading opencv and opencv-python to 4.6 solves the problem in my case.

**Comment by kayhayen** [comment] 2022-11-06 13:13
Thanks, I am closing this early, because you don't really 1.2 for this, and 4.5 debugging is very unlikely at this point.

**Closed by kayhayen** 2022-11-06 13:13 UTC
Labels: enhancement, factory

**Comment by kayhayen** [comment] 2022-11-07 12:10
This is now on the develop branch, part of the current pre-release and should be part of the immanent 1.2 release.

**Comment by kayhayen** [comment] 2022-11-22 17:09
Part of the 1.2 release that was made a while ago.
