### ISSUE TITLE
Asking for static libpython with Anaconda on Windows, and then failing to link with MSVC

### ISSUE THREAD

**Issue by monkeycc** [Nuitka/Nuitka#1361] opened 2022-01-06 06:47 UTC
```
python -m nuitka --standalone --show-progress --plugin-enable=tk-inter --nofollow-imports --output-dir=OUT --windows-icon-from-ico=favicon.ico  paddle2.py
```

**FATAL: Error, usable static libpython is not found for this Python installation. You might be missing required '-dev' packages. Disable with --static-libpython=no" if you don't want to install it.**

--------------------------------
`conda install libpython`

```

Nuitka-Progress:INFO: Optimizing module 'encodings.cp1250', 31 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.cp1250':
Nuitka-Progress:INFO: Optimizing module 'encodings.cp1140', 30 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.cp1140':
Nuitka-Progress:INFO: Optimizing module 'encodings.cp1125', 29 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.cp1125':
Nuitka-Progress:INFO: Optimizing module 'encodings.cp1026', 28 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.cp1026':
Nuitka-Progress:INFO: Optimizing module 'encodings.cp1006', 27 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.cp1006':
Nuitka-Progress:INFO: Optimizing module 'encodings.cp037', 26 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.cp037':
Nuitka-Progress:INFO: Optimizing module 'encodings.charmap', 25 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.charmap':
Nuitka-Progress:INFO: Optimizing module 'encodings.bz2_codec', 24 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.bz2_codec':
Nuitka-Progress:INFO: Optimizing module 'encodings.big5hkscs', 23 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.big5hkscs':
Nuitka-Progress:INFO: Optimizing module 'encodings.big5', 22 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.big5':
Nuitka-Progress:INFO: Optimizing module 'encodings.base64_codec', 21 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.base64_codec':
Nuitka-Progress:INFO: Optimizing module 'encodings.ascii', 20 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.ascii':
Nuitka-Progress:INFO: Optimizing module 'encodings.aliases', 19 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings.aliases':
Nuitka-Progress:INFO: Optimizing module 'encodings', 18 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'encodings':
Nuitka-Progress:INFO: Optimizing module 'dis', 17 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'dis':
Nuitka-Progress:INFO: Optimizing module 'copyreg', 16 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'copyreg':
Nuitka-Progress:INFO: Optimizing module 'collections.abc', 15 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'collections.abc':
Nuitka-Progress:INFO: Optimizing module '_collections_abc', 14 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for '_collections_abc':
Nuitka-Progress:INFO: Optimizing module 'collections', 13 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'collections':
Nuitka-Progress:INFO: Optimizing module 'codecs', 12 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'codecs':
Nuitka-Progress:INFO: Optimizing module 'bz2', 11 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'bz2':
Nuitka-Progress:INFO: Optimizing module 'base64', 10 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'base64':
Nuitka-Progress:INFO: Optimizing module 'abc', 9 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'abc':
Nuitka-Progress:INFO: Optimizing module '_weakrefset', 8 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for '_weakrefset':
Nuitka-Progress:INFO: Optimizing module '_compression', 7 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for '_compression':
Nuitka-Progress:INFO: Optimizing module 'threading', 6 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'threading':
Nuitka-Progress:INFO: Optimizing module 'inspect', 5 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'inspect':
Nuitka-Progress:INFO: Optimizing module 'ctypes', 4 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'ctypes':
Nuitka-Progress:INFO: Optimizing module '_ctypes', 4 more modules to go after that.
Nuitka-Progress:INFO: Optimizing module 'json', 3 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'json':
Nuitka-Progress:INFO: Optimizing module 'os', 2 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'os':
Nuitka-Progress:INFO: Optimizing module 'datetime', 1 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'datetime':
Nuitka-Progress:INFO: Optimizing module 'site', 0 more modules to go after that.
Nuitka-Progress:INFO: Doing module dependency considerations for 'site':
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Total memory usage before generating C code: 47.49 MB (49795072 bytes):
Nuitka:INFO: Total memory usage before running scons: 52.39 MB (54931456 bytes):
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl).
Unexpected output from this command:
link /nologo /LTCG /INCREMENTAL:NO /STACK:9863168 /OUT:F:\paddle_V2\OUT\paddle_Dan.dist\paddle_Dan.exe /LIBPATH:E:\anaconda3\envs\paddleAI\libs Shell32.lib python37.lib "__constants.obj" "__helpers.obj" "__loader.obj" "module.__main__.obj" "module.tkinter-preLoad.obj" "static_src\MainProgram.obj" "static_src\CompiledCellType.obj" "static_src\CompiledFunctionType.obj" "static_src\CompiledGeneratorType.obj" "static_src\InspectPatcher.obj" "static_src\MetaPathBasedLoader.obj"
__constants.obj : error LNK2001: Unresolved external symbol _Py_FalseStruct
__constants.obj : error LNK2001: Unresolved external symbol _Py_TrueStruct
__helpers.obj : error LNK2001: Unresolved external symbol PyBaseObject_Type
__helpers.obj : error LNK2001: Unresolved external symbol PyCFunction_Type
__helpers.obj : error LNK2001: Unresolved external symbol PyFunction_Type
__helpers.obj : error LNK2001: Unresolved external symbol _Py_NoneStruct
__helpers.obj : error LNK2001: Unresolved external symbol PyExc_AttributeError
__helpers.obj : error LNK2001: Unresolved external symbol PyExc_TypeError
__helpers.obj : error LNK2001: Unresolved external symbol PyExc_SystemError
__helpers.obj : error LNK2001: Unresolved external symbol PyType_Type
module.__main__.obj : error LNK2001: Unresolved external symbol PyExc_ValueError
module.__main__.obj : error LNK2001: Unresolved external symbol PyExc_BaseException
module.__main__.obj : error LNK2001: Unresolved external symbol PySeqIter_Type
module.__main__.obj : error LNK2001: Unresolved external symbol PyUnicode_Type
module.__main__.obj : error LNK2001: Unresolved external symbol PyExc_StopIteration
module.__main__.obj : error LNK2001: Unresolved external symbol PyList_Type
module.__main__.obj : error LNK2001: Unresolved external symbol PyExc_IndexError
MainProgram.obj : error LNK2001: Unresolved external symbol Py_NoSiteFlag
MainProgram.obj : error LNK2001: Unresolved external symbol Py_NoUserSiteDirectory
MainProgram.obj : error LNK2001: Unresolved external symbol Py_DontWriteBytecodeFlag
MainProgram.obj : error LNK2001: Unresolved external symbol Py_DebugFlag
MainProgram.obj : error LNK2001: Unresolved external symbol Py_BytesWarningFlag
MainProgram.obj : error LNK2001: Unresolved external symbol Py_VerboseFlag
MainProgram.obj : error LNK2001: Unresolved external symbol PyImport_FrozenModules
MainProgram.obj : error LNK2001: Unresolved external symbol Py_HasFileSystemDefaultEncoding
MainProgram.obj : error LNK2001: Unresolved external symbol Py_OptimizeFlag
MainProgram.obj : error LNK2001: Unresolved external symbol Py_FileSystemDefaultEncoding
MainProgram.obj : error LNK2001: Unresolved external symbol Py_UTF8Mode
MainProgram.obj : error LNK2001: Unresolved external symbol Py_InteractiveFlag
MainProgram.obj : error LNK2001: Unresolved external symbol Py_InspectFlag
MainProgram.obj : error LNK2001: Unresolved external symbol Py_IgnoreEnvironmentFlag
MainProgram.obj : error LNK2001: Unresolved external symbol Py_FrozenFlag
CompiledCellType.obj : error LNK2001: Unresolved external symbol _Py_NotImplementedStruct
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyFrozenSet_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyExc_ImportWarning
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyDictItems_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyDictKeys_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyExc_KeyError
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PySlice_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PySuper_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyExc_RuntimeError
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyExc_UnboundLocalError
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol _Py_EllipsisObject
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyFrame_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyDictValues_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyExc_ZeroDivisionError
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyDict_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyBool_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyTuple_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyCoro_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyFloat_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyMethod_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyLong_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyExc_OverflowError
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyCallIter_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyCode_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyBytes_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PySet_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyEllipsis_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyComplex_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyExc_NameError
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol _PyByteArray_empty_string
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyModule_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyExc_ImportError
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyGen_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyAsyncGen_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyRange_Type
CompiledFunctionType.obj : error LNK2001: Unresolved external symbol PyByteArray_Type
CompiledGeneratorType.obj : error LNK2001: Unresolved external symbol _PyAsyncGenWrappedValue_Type
CompiledGeneratorType.obj : error LNK2001: Unresolved external symbol PyExc_StopAsyncIteration
CompiledGeneratorType.obj : error LNK2001: Unresolved external symbol PyTraceBack_Type
CompiledGeneratorType.obj : error LNK2001: Unresolved external symbol PyExc_GeneratorExit
MetaPathBasedLoader.obj : error LNK2001: Unresolved external symbol _Py_PackageContext
MetaPathBasedLoader.obj : error LNK2001: Unresolved external symbol PyModuleDef_Type
Backend C:   9%|██████████████████████▋                          

```
-----------------------------------------------------
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

```
python -m nuitka --version
0.6.18.6
Commercial: None
Python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: E:\anaconda3\envs\paddle\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python
`pip install nuitka`

```

python -m pip freeze
0.6.18.6
Commercial: None
Python: 3.7.11 (default, Jul 27 2021, 09:42:29) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: E:\anaconda3\envs\paddle\python.exe
OS: Windows
Arch: x86_64
python -m pip freeze
altgraph==0.17.2
astor==0.8.1
atomicwrites==1.4.0
attrs==21.4.0
Babel==2.9.1
bce-python-sdk==0.8.64
certifi==2021.10.8
cfgv==3.3.1
chardet==4.0.0
charset-normalizer==2.0.10
click==8.0.3
colorama==0.4.4
cycler==0.11.0
Cython==0.29.26
decorator==5.1.0
distlib==0.3.4
et-xmlfile==1.1.0
filelock==3.4.2
flake8==4.0.1
flake8-import-order==0.18.1
Flask==2.0.2
Flask-Babel==2.0.0
Flask-Cors==3.0.10
fonttools==4.28.5
future==0.18.2
identify==2.4.1
idna==3.3
importlib-metadata==4.2.0
iniconfig==1.1.1
itsdangerous==2.0.1
Jinja2==3.0.3
joblib==1.1.0
kiwisolver==1.3.2
lap==0.4.0
MarkupSafe==2.0.1
matplotlib==3.5.1
mccabe==0.6.1
motmetrics==1.2.0
nodeenv==1.6.0
Nuitka==0.6.18.6
numpy==1.19.3
opencv-python==4.5.5.62
openpyxl==3.0.9
packaging==21.3
paddlepaddle-gpu==2.2.1.post112
paddleslim==2.2.1
paddlex==2.1.0
pandas==1.3.5
pefile==2021.9.3
Pillow==9.0.0
platformdirs==2.4.1
pluggy==1.0.0
pre-commit==2.16.0
protobuf==3.19.1
py==1.11.0
py-cpuinfo==8.0.0
pycocotools @ git+https://gitee.com/jiangjiajun/philferriere-cocoapi.git@de7d8ccefd3beb34030aee8e3612adf58b018fc3#subdirectory=PythonAPI
pycodestyle==2.8.0
pycryptodome==3.12.0
pyflakes==2.4.0
pyinstaller==4.7
pyinstaller-hooks-contrib==2021.4
pyparsing==3.0.6
PySimpleGUI==4.55.1
pytest==6.2.5
pytest-benchmark==3.4.1
python-dateutil==2.8.2
pytz==2021.3
pywin32-ctypes==0.2.0
PyYAML==6.0
pyzmq==22.3.0
QPT==1.0b2.dev7
requests==2.27.0
scikit-learn==0.23.2
scipy==1.7.3
Shapely==1.8.0
shellcheck-py==0.8.0.3
six==1.16.0
threadpoolctl==3.0.0
toml==0.10.2
tqdm==4.62.3
ttkbootstrap==1.3.1
typing_extensions==4.0.1
urllib3==1.26.7
virtualenv==20.13.0
visualdl==2.2.2
Werkzeug==2.0.2
wget==3.2
wincertstore==0.2
xmltodict==0.12.0
zipp==3.7.0

```

**Comment by kayhayen** [comment] 2022-01-06 07:51
I think on Windows, it's potentially wrong to suggest to use it, because we reject CondaCC for which it is usable anyway with Nuitka due to too old gcc. I think you need to disable it. I will later check on my Anaconda installations what happens when it is installed on Windows. I didn't see why the MSVC link would freak out, but apparently it did. so `--static-libpython=no` is probably needed for Anaconda on Windows, and it would be a regression due to optimizing Anaconda on Linux somewhat.

**Comment by kayhayen** [comment] 2022-01-08 10:49
I just pushed a change to factory that disables this need, it will be part of the next release 0.6.19, but it probably would be a good idea to use it, but honestly I would have to compare using it vs. not using it to actually know.

**Comment by kayhayen** [comment] 2022-01-09 16:12
Part of the 0.6.19 release I just made.

**Closed by kayhayen** 2022-01-09 16:12 UTC
Labels: bug, factory
