### ISSUE TITLE
Memprocfs error vmm.init

### ISSUE THREAD

**Issue by matheusbranhan** [Nuitka/Nuitka#2498] opened 2023-10-14 18:12 UTC
python file:

`import memprocfs`

```
    vmm_args = ['-memmap', 'mmap.txt', '-device', 'fpga']
    if os.path.isfile('mmap.txt'):
        vmm_args = ['-memmap', 'mmap.txt', '-device', 'fpga']
        print("--- MMAP LOADED ---")
    vmm = memprocfs.Vmm(vmm_args)
    print("--- SUCCESS INI FPGA ---")
    procd = vmm.process('explorer.exe')
```

runing nuitka:

```
python -m nuitka --onefile basepymeow.py
Nuitka-Options:INFO: Used command line options: --onefile basepymeow.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.4' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: options-nanny: Using module 'trio._core._ki' (version 0.22.2) with incomplete support: Disabled careful handling of KeyboardInterrupt in 'trio'
Nuitka-Plugins:INFO: options-nanny: Note, when using 'pygame', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback and error information, so delay this until your program working and remove once you find it non-working.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 753 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 753 C files using clcache with 352 cache hits and 401 cache misses.
Nuitka-Plugins:INFO: data-files: Included data file 'Crypto\Util\.keep_dir.txt' due to empty dir needed for 'Crypto.Util._raw_api'.
Nuitka-Plugins:INFO: data-files: Included data file 'certifi\cacert.pem' due to package data for 'certifi'.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from numpy installation.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 1 C files using clcache with 1 cache hits and 0 cache misses.
Nuitka-Onefile:INFO: Using compression for onefile payload.
Nuitka-Onefile:INFO: Onefile payload compression ratio (22.62%) size 129255822 to 29233079.
Nuitka-Onefile:INFO: Keeping onefile build directory 'basepymeow.onefile-build'.
Nuitka:INFO: Keeping dist folder 'basepymeow.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'basepymeow.build'.
Nuitka:INFO: Successfully created 'basepymeow.exe'.
```

got error:

```
.\basepymeow.exe
--- CS2 ESP - BRAIA ---
--- MMAP LOADED ---
Exception in thread Thread-4 (main):
Traceback (most recent call last):
  File "C:\Users\braia2\AppData\Local\Temp\ONEFIL~1\threading.py", line 1038, in _bootstrap_inner
  File "C:\Users\braia2\AppData\Local\Temp\ONEFIL~1\threading.py", line 975, in run
  File "C:\Users\braia2\AppData\Local\Temp\ONEFIL~1\basepymeow.py", line 79, in main
    vmm = memprocfs.Vmm(vmm_args)

TypeError: Vmm.init(): Initialization of vmm failed.
```

python -m nuitka --version
```
1.8.4
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\braia2\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).
```

python -m pip freeze
```
altgraph==0.17.4
api==0.0.7
apy==0.2.3
attrs==23.1.0
base==0.0.0
beautifulsoup4==4.12.2
bidict==0.22.1
blinker==1.6.2
bs4==0.0.1
by==0.0.4
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
click==8.1.6
colorama==0.4.6
dearpygui==1.8.0
dnspython==2.4.2
docutils==0.20.1
easyocr==1.7.1
EasyProcess==1.1
ec==0.2.5
entrypoint2==1.1
eventlet==0.33.3
exceptiongroup==1.1.3
filelock==3.12.4
Flask==2.3.2
Flask-SocketIO==5.3.5
fsspec==2023.9.2
future==0.18.3
gevent==23.7.0
glfw==2.5.6
greenlet==2.0.2
h11==0.14.0
httplib2==0.22.0
idna==3.4
imageio==2.31.5
iso8601==2.0.0
itsdangerous==2.1.2
Jinja2==3.1.2
jsonify==0.5
keyauth==1.0.3
keyboard==0.13.5
lazy_loader==0.3
leechcorepyc==2.16.5
lockfile==0.12.2
lxml==4.9.3
MarkupSafe==2.1.3
memprocfs==5.8.12
mouse==0.7.1
MouseInfo==0.1.3
mpmath==1.3.0
mss==9.0.1
networkx==3.1
ninja==1.11.1
nose==1.3.7
Nuitka==1.8.4
numpy==1.25.2
oauth2==1.9.0.post1
opencv-python-headless==4.8.1.78
opv==200
ordered-set==4.1.0
outcome==1.2.0
ov==0.0.4
packaging==23.1
pefile==2023.2.7
pid==3.0.4
Pillow==10.0.1
psutil==5.9.5
pyarmor==8.3.10
pyarmor.cli.core==4.3.6
PyAutoGUI==0.9.54
pyclipper==1.3.0.post5
pycparser==2.21
pycryptodome==3.19.0
pygame==2.5.1
pygame-ce==2.3.2
pygame-gui==0.6.9
pygame-menu==4.4.3
PyGetWindow==0.0.9
pyinstaller==6.0.0
pyinstaller-hooks-contrib==2023.9
Pymem==1.12.0
pyMeow @ file:///C:/Users/braia2/Desktop/pyMeow-1.43.25.zip#sha256=dd84058fbdc6070a8bb5db59627fb70930cf28325c66ea6898cbda25e42e1a53
PyMsgBox==1.0.9
PyOpenGL==3.1.6
pyparsing==3.1.1
pyperclip==1.8.2
PyRect==0.2.0
pyscreenshot==3.1
PyScreeze==0.1.29
PySocks==1.7.1
python-bidi==0.4.2
python-daemon==3.0.1
python-dotenv==1.0.0
python-engineio==4.5.1
python-i18n==0.3.9
python-socketio==5.8.0
pytweening==1.0.7
pywin32==305
pywin32-ctypes==0.2.2
PyYAML==6.0.1
requests==2.31.0
scikit-image==0.22.0
scipy==1.11.3
selenium==4.11.2
serial==0.0.97
service==0.6.0
setproctitle==1.3.2
shapely==2.0.1
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4.1
struc==0.2
sympy==1.12
tabulate==0.9.0
tifffile==2023.9.26
tk==0.1.0
torch==2.2.0.dev20231006+cu121
torchaudio==2.2.0.dev20231006+cu121
torchvision==0.17.0.dev20231006+cu121
trio==0.22.2
trio-websocket==0.10.3
typing_extensions==4.7.1
urllib3==2.0.4
utils==1.0.1
webdriver-manager==4.0.0
websocket==0.2.1
websocket-client==1.6.1
Werkzeug==2.3.6
wsproto==1.2.0
zope.event==5.0
zope.interface==6.0
zstandard==0.21.0
```

with python -m nuitka --follow-imports basepymeow.py

```
Nuitka-Options:INFO: Used command line options: --follow-imports basepymeow.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.8.4' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: options-nanny: Using module 'trio._core._ki' (version 0.22.2) with incomplete support: Disabled careful handling of KeyboardInterrupt in 'trio'
Nuitka-Plugins:INFO: options-nanny: Note, when using 'pygame', consider using '--disable-console' option. Otherwise a terminal window will open. However for debugging, terminal output is the easiest way to see informative traceback and error information, so delay this until your program working and remove once you find it non-working.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 739 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 739 C files using clcache with 351 cache hits and 388 cache misses.
Nuitka:INFO: Keeping build directory 'basepymeow.build'.
Nuitka:INFO: Successfully created 'basepymeow.exe'.
Nuitka:INFO: Execute it by launching 'basepymeow.cmd', the batch file needs to set environment.
```

got error:

```
Traceback (most recent call last):
  File "C:\Users\braia2\AppData\Roaming\Python\Python311\site-packages\memprocfs\memprocfs.py", line 21, in <module memprocfs.memprocfs>
    from .vmmpyc import Vmm

ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\braia2\Desktop\client\basepymeow.py", line 4, in <module>
    import memprocfs

  File "C:\Users\braia2\AppData\Roaming\Python\Python311\site-packages\memprocfs\__init__.py", line 1, in <module memprocfs>
    from .memprocfs import *

  File "C:\Users\braia2\AppData\Roaming\Python\Python311\site-packages\memprocfs\memprocfs.py", line 23, in <module memprocfs.memprocfs>
    from vmmpyc import Vmm

ModuleNotFoundError: No module named 'vmmpyc'
```

**Comment by kayhayen** [comment] 2023-10-14 18:49
The script you give behaves the same with Python, the error doesn't seem to be from the code given. Is checks for a file existence, which I don't know how I would have it. Not too minimal or complete.

The module you want to compile there unfortunately needs to be excluded for accelerated mode, being a duplicate of the inability to mix compiled and uncompiled code in a. package

**Closed** 2023-10-14 18:56 UTC
Labels: needs_example
