### ISSUE TITLE
Infinite "loop_analysis" optimization

### ISSUE THREAD

**Issue by Kenrick0** [Nuitka/Nuitka#901] opened 2020-12-12 08:27 UTC
Minimal example that demonstrates the issue: (if I remove any of the seemingly useless lines the problem disappears)
```
def func_a(var_a):
    inventory = {}
    if var_a:
        pass
    elif var_a:
        pass
    elif var_a:
        inventory = {}

    for _ in ():
        inventory = {}

    for _ in ():
        if var_a:
            for _ in ():
                inventory = {}
        elif var_a:
            for _ in ():
                inventory = {}
```

The output from nuitka with `--verbose` is the following lines repeated forever:
```
Nuitka-Optimization:INFO: test3.py:13 : loop_analysis : Loop has incomplete variable types after 1 attempts for 'inventory'.
Nuitka-Optimization:INFO: test3.py:13 : loop_analysis : Loop has complete variable types after 1 attempts.
Nuitka-Optimization:INFO: test3.py:13 : loop_analysis : Loop has incomplete variable types after 1 attempts for 'inventory'.
Nuitka-Optimization:INFO: test3.py:13 : loop_analysis : Loop has complete variable types after 1 attempts.
```

The infinite loop occurs on nuitka >= 0.6.10 with python 2.7.
Nuitka installed from pip both with and without a virtualenv, python from apt.
Reproduced on:
```
0.6.11rc1 (develop branch)
Python: 2.7.17 (default, Sep 30 2020, 13:38:04) 
Executable: /home/kenrick/nuitka_tests/VENV_develop/bin/python
OS: Linux
Arch: x86_64

0.6.10
Python: 2.7.17 (default, Sep 30 2020, 13:38:04) 
Executable: /home/kenrick/nuitka_tests/VENV_0_6_10/bin/python
OS: Linux
Arch: x86_64

0.6.10
Python: 2.7.13 (default, Aug 22 2020, 10:03:02)
Executable: /usr/bin/python
OS: Linux
Arch: armv7l
```

This appears to be a regression because the above sample compiles successfully with:
- nuitka 0.6.10, python 3
- nuitka 0.6.10rc5, python 2.7
- nuitka 0.6.9.6, python 2.7

**Comment by kayhayen** [comment] 2020-12-13 10:59
Reproduced it, thanks for the report!

**Comment by kayhayen** [comment] 2020-12-13 11:12
So, this is of course `inventory` causing it. Nuitka compares for loop tracing, the previous optimization run state at loop entry with the current one, and then can decide to restart it if the pre-conditions changed:

> <ValueTraceMerge of (<ValueTraceAssign at Mini.py:2 of <Node EXPRESSION_CONSTANT_DICT_EMPTY_REF value {} at Mini.py:2 True>>, 
> <ValueTraceMerge of (<ValueTraceAssign at Mini.py:2 of <Node EXPRESSION_CONSTANT_DICT_EMPTY_REF value {} at Mini.py:2 True>>, 
> <ValueTraceMerge of (<ValueTraceAssign at Mini.py:2 of <Node EXPRESSION_CONSTANT_DICT_EMPTY_REF value {} at Mini.py:2 True>>, 
> <ValueTraceAssign at Mini.py:8 of <Node EXPRESSION_CONSTANT_DICT_EMPTY_REF value {} at Mini.py:8 True>>)>)>)>, 

This is a bit tedious to read, but the `repr` are the same, but somehow our comparison function fails find attest that the traces are equivalent.

**Comment by kayhayen** [comment] 2020-12-13 11:34
Ok, I was confusing myself by tracing in the wrong spot, comparing a value basically to itself.

What's really going on, is that in the next run, that a trace merge is compared with a non-merge trace. It could be the case, that later merging removes an unnecessary merge of identical stuff. I will need to add a big of debugging aids for these traces to become better in display. Esp. nested merge traces are barely readable to me right now.

**Comment by kayhayen** [comment] 2020-12-13 18:01
Ok, I got this I think. Nuitka is using a `set` object when merging branches, therefore making the order of branches random on Python2 and I think probably up until 3.6 where I know that the `dict` got ordered.

In fact, if sets are ordered after some version, Nuitka can stop using `OrderedSet` as its own implementation and instead use the standard set.

And I'd like to thank for your thorough report, the fact that you saw a Python3/Python2 difference is what made me go right to the merging of the branches and made this easy to find.

**Comment by kayhayen** [comment] 2020-12-13 18:16
What I said about Python3 is untrue. For new set objects it's hard to demonstrate that they are not ordered, this is only actually happening, if I clear them before deleting them, otherwise they seem to be always big enough and to retain ordered. But when I do that, all Python versions show this. Since it's relatively random, there probably has to be some bad luck to be involved to reorder branches in value's merge traces.

The comparison of these merge traces also could do a comparison that would compare all branches with all branches to see if one is a match for every other one, but that's too much overhead.

Unfortunately the `OrderedSet` is going to make the merging of branches in tracing yet again more expensive, but what can we do, correctness wins.

**Comment by kayhayen** [comment] 2020-12-13 18:53
This is on factory now https://nuitka.net/doc/factory.html and will be in the next hotfix 0.6.10.1 once released.

**Comment by kayhayen** [comment] 2021-01-10 13:11
Long released.

**Closed by kayhayen** 2021-01-10 13:11 UTC
Labels: bug, factory
