### ISSUE TITLE
PySide6.1.0 and PySide6.1.1 still doesn't work, PySide 6.1.2 will be needed

### ISSUE THREAD

**Issue by LarsK1** [Nuitka/Nuitka#1097] opened 2021-05-15 07:41 UTC
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
0.6.15rc6
Python: 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)]
Executable: D:\Programme\Python\Kanzlei\Contacts4Snom\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python

  pip, virtualenc

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

Not shure where it comes from

I wroten an application (with pyside6 6.1.0) that uses multiple event-slots:
```
		self.actionBeenden.triggered.connect(self.MainWindow.close)
		self.pushButton.clicked.connect(self.KonfigurationSpeichern)
		self.comboBox.currentIndexChanged.connect(self.GeanderterDienst)
		self.actionLizenz.triggered.connect(self.Lizenzdialog.show)
		self.Lizenz_Deaktivieren.clicked.connect(self.deactivateLicense)
		self.pushButton_3.clicked.connect(self.GoogleLogin)
		self.pushButton_4.clicked.connect(self.GoogleLogin)
		self.pushButton_2.clicked.connect(self.KontakteErzeugen)
		self.statusBar.messageChanged.connect(self.KontaktErzeugenStatus)
		self.pushButton_5.clicked.connect(self.Microsoft365Login)
		self.lineEdit.textChanged.connect(self.RequierementCheck)
```
There seem to multiple issues with them:
- they seem to call random functions:
my setup codes calls a function `KonfigurationLesen()`, which doesn't call `KonfigurationSpeichern(`), but in compiled mode it does?
- the function `RequierementCheck` calls `self.KonfigurationSpeichern(silent=True)` , but the paramter silent=True will not be handed over, instead the default parameter silent=false is used

**Comment by kayhayen** [comment] 2021-05-15 08:02
Lars, without example code, I cannot investigate this.

**Comment by LarsK1** [comment] 2021-05-15 08:18
I'm sorry it's a pretty heavy example, but it needs a lot of requierments to happen:
```
# -*- coding: utf-8 -*-
################################################################################

from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
import sys


class Ui_MainWindow:
    def __init__(self):
        self.MainWindow = QMainWindow()

    def setupUi(self):
        self.MainWindow.resize(800, 429)
        self.MainWindow.setToolButtonStyle(Qt.ToolButtonTextBesideIcon)
        self.MainWindow.setDocumentMode(False)
        self.MainWindow.setDockNestingEnabled(False)
        self.MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QWidget(self.MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.gridLayout = QGridLayout()
        self.gridLayout.setObjectName(u"gridLayout")
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setTabPosition(QTabWidget.North)
        self.tabWidget.setTabShape(QTabWidget.Rounded)
        self.tabWidget.setIconSize(QSize(16, 16))
        self.tabWidget.setUsesScrollButtons(False)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab = QWidget()
        self.tab.setObjectName(u"tab")
        self.gridLayout_3 = QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(u"gridLayout_3")
        self.gridLayout_2 = QGridLayout()
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.tabWidget_2 = QTabWidget(self.tab)
        self.tabWidget_2.setObjectName(u"tabWidget_2")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.gridLayout_7 = QGridLayout(self.tab_4)
        self.gridLayout_7.setObjectName(u"gridLayout_7")
        self.gridLayout_6 = QGridLayout()
        self.gridLayout_6.setObjectName(u"gridLayout_6")
        self.horizontalSpacer_2 = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_6.addItem(self.horizontalSpacer_2, 0, 2, 1, 1)

        self.horizontalSpacer = QSpacerItem(40, 20, QSizePolicy.Expanding, QSizePolicy.Minimum)

        self.gridLayout_6.addItem(self.horizontalSpacer, 0, 0, 1, 1)

        self.lineEdit = QLineEdit(self.tab_4)
        self.lineEdit.setObjectName(u"lineEdit")
        self.lineEdit.setAlignment(Qt.AlignCenter)
        self.lineEdit.setReadOnly(True)

        self.gridLayout_6.addWidget(self.lineEdit, 0, 1, 1, 1)

        self.pushButton_3 = QPushButton(self.tab_4)
        self.pushButton_3.setObjectName(u"pushButton_3")

        self.gridLayout_6.addWidget(self.pushButton_3, 1, 1, 1, 1)


        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)

        self.tabWidget_2.addTab(self.tab_4, "")

        self.gridLayout_2.addWidget(self.tabWidget_2, 2, 0, 1, 1)

        self.comboBox = QComboBox(self.tab)
        icon7 = QIcon()
        icon7.addFile(u":/Icons/images/google.png", QSize(), QIcon.Normal, QIcon.Off)
        self.comboBox.addItem(icon7, "")
        icon8 = QIcon()
        icon8.addFile(u":/Icons/images/googlecontacts.png", QSize(), QIcon.Normal, QIcon.Off)
        self.comboBox.addItem(icon8, "")
        icon9 = QIcon()
        icon9.addFile(u":/Icons/images/exchange.png", QSize(), QIcon.Normal, QIcon.Off)
        self.comboBox.addItem(icon9, "")
        icon10 = QIcon()
        icon10.addFile(u":/Icons/images/office365.png", QSize(), QIcon.Normal, QIcon.Off)
        self.comboBox.addItem(icon10, "")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setFrame(True)

        self.gridLayout_2.addWidget(self.comboBox, 1, 0, 1, 1)

        self.label = QLabel(self.tab)
        self.label.setObjectName(u"label")
        self.label.setFrameShadow(QFrame.Plain)
        self.label.setLineWidth(9)
        self.label.setMargin(2)
        self.label.setTextInteractionFlags(Qt.NoTextInteraction)

        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)


        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        icon11 = QIcon()
        icon11.addFile(u":/Icons/images/cross.png", QSize(), QIcon.Normal, QIcon.Off)
        self.tabWidget.addTab(self.tab, icon11, "")

        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)


        self.verticalLayout.addLayout(self.gridLayout)

        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")

        self.verticalLayout.addWidget(self.pushButton)

        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setCheckable(False)

        self.verticalLayout.addWidget(self.pushButton_2)

        self.MainWindow.setCentralWidget(self.centralwidget)
        QWidget.setTabOrder(self.tabWidget, self.comboBox)
        QWidget.setTabOrder(self.comboBox, self.tabWidget_2)

        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)

        self.MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Contacts4Snom", None))
        self.lineEdit.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Google API-Token", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Jetzt authentifizieren", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Google Workspace", None))
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"Google Workspace", None))
        self.comboBox.setItemText(1, QCoreApplication.translate("MainWindow", u"Google Contacts", None))
        self.comboBox.setItemText(2, QCoreApplication.translate("MainWindow", u"Microsoft Exchange", None))
        self.comboBox.setItemText(3, QCoreApplication.translate("MainWindow", u"Office 365", None))

        self.comboBox.setCurrentText("")
        self.comboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Quelle:", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:700;\">Einstellungen zum Kontaktimport</span></p></body></html>", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QCoreApplication.translate("MainWindow", u"Eingabe", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Einstellungen speichern", None))
        self.pushButton.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+S", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Kontaktdatei generieren", None))
        self.pushButton.clicked.connect(self.KonfigurationSpeichern)
        self.comboBox.currentIndexChanged.connect(self.GeanderterDienst)
        self.pushButton_3.clicked.connect(self.GoogleLogin)
        self.pushButton_2.clicked.connect(self.KontakteErzeugen)
        self.lineEdit.textChanged.connect(self.RequierementCheck)
        QMetaObject.connectSlotsByName(self.MainWindow)
    def KonfigurationSpeichern(self, ausgabe=False):
        print("Save config")
        if not ausgabe:
            print("Show windows")
    def KonfigurationLesen(self):
        print("Read config")
        self.RequierementCheck()
    def GoogleLogin(self):
        print("Google Login")
    def RequierementCheck(self):
        print("Check")
    def GeanderterDienst(self):
        print("Change")
    def KontakteErzeugen(self):
        print("Create Contacts")

if __name__ == "__main__":
    app = QApplication(sys.argv)
    UI = Ui_MainWindow()
    UI.setupUi()
    UI.MainWindow.show()
    sys.exit(app.exec())
```

When running the programm uncompiled, clicking the button "Jetzt authentifizieren" just prints Google Login, when running in compiled mode it prints "Save config, show windows"?

**Comment by LarsK1** [comment] 2021-05-15 08:20
It's compiled with: `nuitka --standalone --enable-plugin=pyside6 sample.py`

**Comment by LarsK1** [comment] 2021-05-17 14:11
@kayhayen managed it to produce a even smaller example:
```
# -*- coding: utf-8 -*-
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
import sys

class Ui_MainWindow:
	def __init__(self):
		self.MainWindow = QMainWindow()
		self.MainWindow.resize(800, 600)

	def setupUi(self):
		self.centralwidget = QWidget(self.MainWindow)
		self.pushButton = QPushButton(self.centralwidget)
		self.pushButton.setGeometry(QRect(170, 200, 75, 24))
		self.pushButton_2 = QPushButton(self.centralwidget)
		self.pushButton_2.setGeometry(QRect(410, 210, 75, 24))
		self.MainWindow.setCentralWidget(self.centralwidget)
		self.pushButton.setText("Button 1")
		self.pushButton_2.setText("Button 2")
		self.pushButton.clicked.connect(self.Button1)
		self.pushButton_2.clicked.connect(self.Button2)

	def Button1(self):
		print("Button 1")

	def Button2(self):
		print("Button 2")

if __name__ == "__main__":
	app = QApplication(sys.argv)
	UI = Ui_MainWindow()
	UI.setupUi()
	UI.MainWindow.show()
	app.exec()
```
When running in normal python mode, it prints "Button 1", when clicking on push
Button, and "Button 2", when clicking on pushButton_2

**Comment by kayhayen** [comment] 2021-05-17 14:22
Sadly, this is reproducible, I fear there is a regression. I have modified the example to use PySide2, and my https://nuitka.net/pages/pyside2.html support is working fine. The PySide6 dev branch at one point was working, but might have regressed the Nuitka support it seems. I will have to look into this, but I don't know when I find the time honestly.

**Comment by kayhayen** [comment] 2021-05-19 07:20
Ok, I am bisecting this on the side, and I found that the code works well with my original patch merged. I will find out when it regressed and see if it's something I can repair.

**Comment by ctismer** [comment] 2021-05-19 10:41
Well, it is possible that some later change broke something. Unfortunately we did not add specific tests for Nuitka, yet.

**Comment by LarsK1** [comment] 2021-05-31 19:00
Hey Kay,
could you just give me a hint, which commit you mean, for a working PySide6-Enviroment, I didn't find it, but would like to help you find the issue.

**Comment by kayhayen** [comment] 2021-05-31 19:26
@LarsK1 this has never worked, not even after my patch was merged into PySide6 dev at the time, so the commit is irrelevant. This needs PySide6 debugging. It seems the test cases I executed happened to work all with my patch, but not this one. However, funny enough they do work with the patch backported to PySide2, but that doesn't help here.

This is very ugly corruption issue. I was going to trace the PySide 1523 code (search for that), and see how the code paths differ. Somethings seems to be confused as identical here, which is not.

Yours,
Kay

**Comment by kayhayen** [comment] 2021-06-03 14:14
I have the issuse, and I am attaching the patch here for reference. @LarsK1 can you create a PySide issue, and get this merged?

[0001-Nuitka-Fix-slot-keys-did-not-work-for-compiled-metho.zip](https://github.com/Nuitka/Nuitka/files/6592238/0001-Nuitka-Fix-slot-keys-did-not-work-for-compiled-metho.zip)

**Comment by LarsK1** [comment] 2021-06-03 14:55
@kayhayen sure, I'll do it. Inform you, when done ...

**Comment by LarsK1** [comment] 2021-06-03 19:53
Added ticket see 1589, @kayhayen mentioned you already as author.
Let's see and wait

**Comment by LarsK1** [comment] 2021-06-06 19:48
@kayhayen issue is merged

**Comment by kayhayen** [comment] 2021-06-06 19:50
Do we know what release will it be in?

**Comment by LarsK1** [comment] 2021-06-07 04:13
Not exactly. But the commit, was merged to the repository of 6.1

**Comment by kayhayen** [comment] 2021-06-07 07:10
Ok, I modified the warning to ask for 6.1.1 which is unreleases. I too saw it was cherry-picked on that branch of theirs, and that's the next release, so that should happen eventually. Thanks @LarsK1 

This will be in a hotfix soon.

**Comment by kayhayen** [comment] 2021-06-19 07:55
This was released and 6.1.1 too, should be all good now.

**Comment by bearsh** [comment] 2021-06-19 08:09
@kayhayen are you sure this is fixed in 6.1.1? looking at https://code.qt.io/cgit/pyside/pyside-setup.git/log/?h=6.1.1 the last commit is from 31.05.2021. I fear we have to wait for 6.1.2...

**Comment by kayhayen** [comment] 2021-06-19 12:25
I have to change my mind, thanks for pointing it out, it's on the 6.1 branch, but in no tag yet, so it's probably not part of the release yet, I am reopening it then.

**Comment by bearsh** [comment] 2021-07-01 14:37
pyside6.1.2 has been released today...

**Comment by kayhayen** [comment] 2021-07-01 14:48
@LarsK1 you can give it a spin and report if the bug is fixed with the pip installed version for you?

**Comment by LarsK1** [comment] 2021-07-01 16:11
In my test, everything now works as expected - even the large program where I encountered the error, works absolutely smoothly!

**Comment by kayhayen** [comment] 2021-07-01 17:06
Thanks for helping with this, I am closing it then.

**Closed by kayhayen** 2021-07-01 17:06 UTC
Labels: bug
