### ISSUE TITLE
EXE asks for allow Windows Firewall access EVERYTIME

### ISSUE THREAD

**Issue by mzy2240** [Nuitka/Nuitka#1276] opened 2021-11-17 20:56 UTC
Forgive me if it is a dumb question!
I have a python program which serves as a socketio server. Compilation is smooth, it could also work without any issues. However, the only problem is **everytime** when I open the exe, the Windows Firewall will pop up and ask the users to allow access. Normally this will not happen if you have granted the access once (at least for other commercialized software and some exe I generated using pyinstaller). I have already assigned product name, company name and product version, but still the Windows Firewall requests the user to allow access everytime. Please advise at your convenience. Thanks!

**Comment by mzy2240** [comment] 2021-11-17 21:20
This problem only occurs when --onefile is enabled.

**Comment by kamgha** [comment] 2021-11-17 22:45
Try `--windows-onefile-tempdir-spec=%TEMP%\yourappname`

**Comment by kamgha** [comment] 2021-11-17 22:47
Try `--windows-onefile-tempdir-spec=%TEMP%\yourappname` to fix the location of the executable.

**Comment by mzy2240** [comment] 2021-11-17 23:00
Wow it works! Thank you so much!
Do you mind if I ask why setting up this tempdir solves the issue?

**Comment by kamgha** [comment] 2021-11-17 23:10
> Do you mind if I ask why setting up this tempdir solves the issue?

The default location for `--onefile` under Windows is `--windows-onefile-tempdir-spec=%TEMP%\onefile_%PID%_%TIME%`. This will be a different path each time you start your executable, since %PID% and %TIME% will change. Windows Firewall will probably store the location of the executable to whitelist, so in this case each time you run your program it will treat it as a yet unknown program.

**Comment by mzy2240** [comment] 2021-11-17 23:19
That makes sense a lot! Thank you so much for the help and explanation!

**Comment by kayhayen** [comment] 2021-11-18 11:07
This very interesting. I would have to reproduce this and checkout what others might be doing better there. Maybe it's wrong to have a second executable, and the onefile bootstrap should be both the onefile, and the program, and only use the temporary directory to run stuff. I am pretty sure others do have unique temporary folders, but likely there is no exe in there.

**Comment by kayhayen** [comment] 2022-05-15 15:06
I am currently implementing the cached onefile execution mode, where the binary lives in the same place and is kept there, which should help with the firewall issues. I think this is a duplicate of some sorts, but this goal is specific enough.

**Comment by kayhayen** [comment] 2022-06-23 07:25
Sorry, didn't make it for 0.9 release that I just made. This is a high priority issue for 1.0 and I hope to have it for develop soon.

**Comment by kayhayen** [comment] 2022-08-04 15:07
The cached mode, which is unlocked by using a only values in the onefile temp spec that are static, solved the issue, and release was done.

**Closed by kayhayen** 2022-08-04 15:07 UTC
Labels: bug
