### ISSUE TITLE
Access violation/segmentation fault connecting signal (with `QFileSystemWatcher`/`QTimer`)

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2499] opened 2023-10-14 22:38 UTC
Good things come in threes. #2086, #2492, and now this. Note this code likely doesn't do anything useful anymore, it is highly reduced to reproduce the segmentation fault.

`crash.py`
```python
# nuitka-project: --onefile
# nuitka-project: --static-libpython=no
# nuitka-project: --enable-plugin=pyside6
# nuitka-project: --nofollow-import-to=tkinter
# possibly remove the above since 1.7
# nuitka-project: --noinclude-default-mode=error
# nuitka-project-if: {OS} == "Windows":
#    nuitka-project: --output-filename=crash.exe
# nuitka-project-if: {OS} == "Linux":
#    nuitka-project: --output-filename=crash.bin
# nuitka-project: --output-dir=dist-nuitka
# nuitka-project: --assume-yes-for-downloads

# With tests:
# nuitka-project: --noinclude-pytest-mode=allow
# nuitka-project: --noinclude-unittest-mode=allow
# nuitka-project: --include-package=_pytest
# nuitka-project: --include-package=pytestqt
# nuitka-project: --include-module=PySide6.QtTest
# nuitka-project: --include-module=test_crash
# nuitka-project: --nofollow-import-to=doctest
# nuitka-project: --include-data-file=test_crash.py=.

from pathlib import Path

import pytest

if __name__ == "__main__":
    pytest.main([Path(__file__).parent, "-s"], ["pytestqt.plugin"])
```

`test_crash.py`
```python
from contextlib import contextmanager, nullcontext

from window import Window


def test_crash(qtbot, tmp_path):
    tmp_file = tmp_path / "tmp_file.raw"

    window = Window(tmp_file)
    qtbot.addWidget(window)

    def write(contents):
        with tmp_file.open("wb") as file:
            file.write(contents.encode("utf-8"))

    @contextmanager
    def wait(fixed=0):
        signal_wait = qtbot.waitSignal(window.signal, timeout=5000)
        with nullcontext() if fixed else signal_wait:
            yield
        if fixed:
            qtbot.wait(fixed)

    write("1")

    with wait():
        window.start()

    with wait(fixed=200):
        write("12")

    with wait():
        qtbot.wait(300)
```

`window.py`
```python
from PySide6.QtCore import QFileSystemWatcher, QTimer, Signal
from PySide6.QtWidgets import QMainWindow


class Window(QMainWindow):
    signal = Signal()

    def __init__(self, path):
        super().__init__()
        self.path = path
        self.fsize = self.get_fsize()
        self.watcher = QFileSystemWatcher()
        self.watcher.fileChanged.connect(self.file_changed)

    def get_fsize(self):
        try:
            return self.path.stat().st_size
        except FileNotFoundError:
            return 0

    def file_changed(self):
        if (new_size := self.get_fsize()) != self.fsize:
            self.fsize = new_size
            QTimer.singleShot(300, self.file_changed)
            return
        self.start()

    def start(self):
        self.signal.emit()
        self.watcher.addPath(str(self.path))
```

Setup:
```
Python=3.11.6
Nuitka==1.9rc5  # 11a3d44ab12c706a54e85c21d5161e2983e1bc01
PySide6-Essentials==6.5.3
pytest==7.4.2
pytest-qt==4.2.0
```

Run
```shell
pytest  # works
python -m nuitka crash.py
dist-nuitka/crash.bin  # segfaults
```

Output
```
====================================================================================== test session starts ======================================================================================platform linux -- Python 3.11.6, pytest-7.4.2, pluggy-1.3.0
PySide6 6.5.3 -- Qt runtime 6.5.3 -- Qt compiled 6.5.3
rootdir: /tmp/onefile_11874_1697322110_687089
collected 1 item

../../../../tmp/onefile_11874_1697322110_687089/test_crash.py Fatal Python error: Segmentation fault

Current thread 0x00007f34dcefab80 (most recent call first):
  File "/tmp/onefile_11874_1697322110_687089/pytestqt/wait_signal.py", line 193 in connect
  File "/tmp/onefile_11874_1697322110_687089/pytestqt/qtbot.py", line 289 in waitSignal
  File "/tmp/onefile_11874_1697322110_687089/test_crash.py", line 18 in wait
  File "/tmp/onefile_11874_1697322110_687089/contextlib.py", line 137 in __enter__
  File "/tmp/onefile_11874_1697322110_687089/test_crash.py", line 32 in test_crash
  File "/tmp/onefile_11874_1697322110_687089/_pytest/python.py", line 194 in pytest_pyfunc_call
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_11874_1697322110_687089/_pytest/python.py", line 1792 in runtest
  File "/tmp/onefile_11874_1697322110_687089/_pytest/runner.py", line 169 in pytest_runtest_call
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_11874_1697322110_687089/_pytest/runner.py", line 262 in <lambda>
  File "/tmp/onefile_11874_1697322110_687089/_pytest/runner.py", line 341 in from_call
  File "/tmp/onefile_11874_1697322110_687089/_pytest/runner.py", line 261 in call_runtest_hook
  File "/tmp/onefile_11874_1697322110_687089/_pytest/runner.py", line 222 in call_and_report
  File "/tmp/onefile_11874_1697322110_687089/_pytest/runner.py", line 133 in runtestprotocol
  File "/tmp/onefile_11874_1697322110_687089/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_11874_1697322110_687089/_pytest/main.py", line 350 in pytest_runtestloop
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_11874_1697322110_687089/_pytest/main.py", line 325 in _main
  File "/tmp/onefile_11874_1697322110_687089/_pytest/main.py", line 271 in wrap_session
  File "/tmp/onefile_11874_1697322110_687089/_pytest/main.py", line 318 in pytest_cmdline_main
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_11874_1697322110_687089/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_11874_1697322110_687089/_pytest/config/__init__.py", line 169 in main
```

**Comment by kayhayen** [comment] 2023-11-27 12:24
Can you retry this one, I am pretty sure ultimately #2492 is a duplicate of this one, and let me know if it needs a re-open.

**Comment by bersbersbers** [comment] 2023-11-27 22:28
I can still reproduce this:

```
1.9.2
Commercial: None
Python: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
Flavor: Unknown
Executable: c:\Build\project\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Build\NuitkaCache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

```
===================================================================================== test session starts ======================================================================================
platform win32 -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0
PySide6 6.6.0 -- Qt runtime 6.6.0 -- Qt compiled 6.6.0
rootdir: C:\Users\bers\AppData\Local\Temp\ONEFIL~1
collected 1 item

..\..\..\Users\bers\AppData\Local\Temp\ONEFIL~1\test_crash.py Windows fatal exception: access violation

Current thread 0x00004634 (most recent call first):
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pytestqt\wait_signal.py", line 193 in connect
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pytestqt\qtbot.py", line 289 in waitSignal
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\test_crash.py", line 18 in wait
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\contextlib.py", line 137 in __enter__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\test_crash.py", line 29 in test_crash
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\python.py", line 194 in pytest_pyfunc_call
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\python.py", line 1792 in runtest
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 169 in pytest_runtest_call
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 262 in <lambda>
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 341 in from_call
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 261 in call_runtest_hook
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 222 in call_and_report
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 133 in runtestprotocol
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 114 in pytest_runtest_protocol
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\main.py", line 350 in pytest_runtestloop
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\main.py", line 325 in _main
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\main.py", line 271 in wrap_session
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\main.py", line 318 in pytest_cmdline_main
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\config\__init__.py", line 169 in main
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\crash.py", line 1 in <module>
```

**Comment by kayhayen** [comment] 2023-11-29 09:06
Hm, very strange, maybe 6.6 didn't really fix it after all, it surely disables the workaround. Can you try with a 6.5 downgrade?

**Comment by bersbersbers** [comment] 2023-11-30 07:21
> Can you try with a 6.5 downgrade?

Yes, same thing. Using nuitka 1.9.2 from `pip`:

```
=========================== test session starts ===========================
platform win32 -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0
PySide6 6.5.3 -- Qt runtime 6.5.3 -- Qt compiled 6.5.3
rootdir: C:\Users\bers\AppData\Local\Temp\ONEFIL~1
collected 1 item

..\..\Users\z004j05c\AppData\Local\Temp\ONEFIL~1\test_crash.py Windows fatal exception: access violation
```

**Comment by kayhayen** [comment] 2023-11-30 13:47
Thanks, looks like there is more to find. It's strange since this is also the code that triggered me to realize that `disconnect` is the actual problem, and that seemed to solve some things.

**Comment by kayhayen** [comment] 2024-01-19 09:19
I recently did another fix that is maybe on factory only right now, that revives a fix that I made. Does look to me like you bottom posted supposely fixed issues? I don't track those at all.

**Comment by bersbersbers** [comment] 2024-01-20 07:00
> Does look to me like you bottom posted supposely fixed issues? I don't track those at all.

That's a pity because you may miss out on people thanking you :) but also, how else are people expected to tell you a fix is not actually fixing the issue?

> I recently did another fix that is maybe on factory only right now, that revives a fix that I made. 

Will re-test reproductions in both #2492 and #2499.

**Comment by bersbersbers** [comment] 2024-01-20 07:37
Both #2492 and #2499 are working on Windows now!
> platform win32 -- Python 3.11.7, pytest-7.4.4, pluggy-1.3.0
> PySide6 6.6.1 -- Qt runtime 6.6.1 -- Qt compiled 6.6.1

**Comment by bersbersbers** [comment] 2024-01-20 07:50
On Linux now, too!

> platform linux -- Python 3.11.7, pytest-7.4.4, pluggy-1.3.0
> PySide6 6.6.1 -- Qt runtime 6.6.1 -- Qt compiled 6.6.1

Both are using d6ae88493988b9391c4ac1ee941134eedb2cd997 from factory, by the way.

Interested in seeing if my full app works now, too!

**Comment by bersbersbers** [comment] 2024-01-20 09:04
> Interested in seeing if my full app works now, too!

It does! Thanks a lot!

**Comment by kayhayen** [comment] 2024-01-20 09:24
I think we are saying, this is fixed with 2.0 then, aren't we. And bottom posting is bad, because after I decided it's fixed, an issue can resurface indeed, but it can be a different one, with a similar symptom but often in a different setup, so I hate that. 

One of my PySide fixes seems to have caused crashes for other cases, due to not being allowed to set __name__ on some Qt methods without a crasher, and once that code was reverted, other problems resurface. I always need a full new report to stay sane and not spend time needlessly. My time in the project is limited. If I spend it on managing bottom posts, that might not be the most effective use of my time, and there is not enough time available.

**Comment by bersbersbers** [comment] 2024-01-20 09:38
> I think we are saying, this is fixed with 2.0 then, aren't we.

I'd say yes - assuming current `factory` will be included there. I haven't check `develop` (and am not planning to, to be honest).

**Comment by kayhayen** [comment] 2024-01-22 16:02
This is now on the develop and the commercial staging branch and part of the latest pre-release, will be part of the 2.0 release that will eventually follow.

**Comment by kayhayen** [comment] 2024-01-26 13:27
This is part of the stable release 2.0 that I just made.

**Closed by kayhayen** 2024-01-26 13:27 UTC
Labels: bug, develop
