### ISSUE TITLE
SystemError when using --include-distribution-metadata for a distribution package, and importlib.metadata.distributions() used in code

### ISSUE THREAD

**Issue by jaustinpage** [Nuitka/Nuitka#2454] opened 2023-09-21 18:54 UTC
### Basic issue:

When the `--include-distribution-metadata` flag is used, code that includes a `importlib.metadata.distributions() call will fail with a SystemError.

### Test program:
metadata_debug.py
```python
# ./metadata_debug.py
from importlib import metadata

def main():
    print("In: main()")
    for dist in metadata.distributions():
        print("Before: dist.metadata.get()")
        print(dist.metadata.get("name"))  # type: ignore
        print("After: dist.metadata.get()")

if __name__ == "__main__":
    print("Before: main()")
    main()
    print("Done")
```

example output:
```sh
+ ./.venv/bin/python3 metadata_debug.py
Before: main()
In: main()
Before: dist.metadata.get()
setuptools
After: dist.metadata.get()
Before: dist.metadata.get()
pip
After: dist.metadata.get()
Before: dist.metadata.get()
zstandard
After: dist.metadata.get()
Before: dist.metadata.get()
ordered-set
After: dist.metadata.get()
Before: dist.metadata.get()
Nuitka
After: dist.metadata.get()
Done
+ echo 0
0
```
binary output:
```sh
+ ./.venv/bin/python3 -m nuitka --standalone --include-distribution-metadata=nuitka metadata_debug.py
Nuitka-Options:INFO: Used command line options: --standalone --include-distribution-metadata=nuitka metadata_debug.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9rc3' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:INFO: anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka-Plugins:INFO: anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 7 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 6 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 6
Nuitka:INFO: Keeping build directory 'metadata_debug.build'.
Nuitka:INFO: Successfully created 'metadata_debug.dist/metadata_debug.bin'.
+ ./metadata_debug.dist/metadata_debug.bin
Before: main()
In: main()
Traceback (most recent call last):
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 981, in distribution
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 563, in from_name
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 580, in discover
RecursionError: maximum recursion depth exceeded while calling a Python object

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 981, in distribution
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 563, in from_name
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 582, in <genexpr>
SystemError: <built-in method find_distributions of type object at 0xc51d60> returned a result with an exception set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 981, in distribution
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 563, in from_name
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 582, in <genexpr>
SystemError: <built-in method find_distributions of type object at 0xc51d60> returned a result with an exception set

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 981, in distribution
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 563, in from_name
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 582, in <genexpr>
SystemError: <built-in method find_distributions of type object at 0xc51d60> returned a result with an exception set

<previous 8 lines repeated about 240 more times, redacted>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/metadata_debug.py", line 12, in <module>
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/metadata_debug.py", line 5, in main
  File "/home/<redacted>/scratchpad/metadata-debug/metadata_debug.dist/importlib/metadata/__init__.py", line 582, in <genexpr>
SystemError: <built-in method find_distributions of type object at 0xc51d60> returned a result with an exception set
+ echo 1
1
```

### Reproduction Steps:
test.sh
```sh
#!/bin/bash
# ./test.sh
python3.11 -m venv .venv
./.venv/bin/python3 -m pip install nuitka==1.8.2
./.venv/bin/python3 -m nuitka --version
# show normal python execution
./.venv/bin/python3 metadata_debug.py
echo $?
# compile 
./.venv/bin/python3 -m nuitka --standalone --include-distribution-metadata=nuitka metadata_debug.py
# test binary
./metadata_debug.dist/metadata_debug.bin
echo $?
```

### Discovered workaround:
When adding the option `--include-package=nuitka` in addition to the `--include-distribution-metadata=nuitka`, the problem appears fixed.

```sh
+ ./.venv/bin/python3 -m nuitka --standalone --include-package=nuitka --include-distribution-metadata=nuitka metadata_debug.py
Nuitka-Options:INFO: Used command line options: --standalone --include-package=nuitka --include-distribution-metadata=nuitka metadata_debug.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.9rc3' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'doctest' (intending to avoid 'unittest') in 'nuitka.tools.testing.Common' (at
Nuitka-Plugins:WARNING: '/home/<redacted>/scratchpad/metadata-debug/.venv/lib/python3.11/site-packages/nuitka/tools/testing/Common.py:965') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'setuptools' (intending to avoid 'setuptools') in 'nuitka.distutils.Build' (at
Nuitka-Plugins:WARNING: '/home/<redacted>/scratchpad/metadata-debug/.venv/lib/python3.11/site-packages/nuitka/distutils/Build.py:23') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:INFO: anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:INFO: anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 513 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 512 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 2
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 510
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/Grammar3.11.4.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/PatternGrammar3.11.4.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka:INFO: Keeping build directory 'metadata_debug.build'.
Nuitka:INFO: Successfully created 'metadata_debug.dist/metadata_debug.bin'.
+ ./metadata_debug.dist/metadata_debug.bin
Before: main()
In: main()
Before: dist.metadata.get()
Nuitka
After: dist.metadata.get()
Done
+ echo 0
0
```

### Troubleshooting steps attempted:
1. Tried python 3.9 and 3.11
2. Tried Nuitka 1.7.10, 1.8.2, and 1.9rc3 (develop branch).
3. Tried `-clang`
4. Tried `--include-distribution-metadata=Nuitka` (uppercase)

### Nuitka version output
```
./.venv/bin/python3 -m nuitka --version
1.9rc3
Commercial: None
Python: 3.11.4 (main, Jun 13 2023, 16:07:53) [GCC 8.5.0 20210514 (Red Hat 8.5.0-16)]
Flavor: Unknown
Executable: /home/<redacted>/scratchpad/metadata-debug/.venv/bin/python3
OS: Linux
Arch: x86_64
Distribution: Rhel (based on Fedora) 8.7
Version C compiler: /usr/bin/gcc (gcc).
```

### How Nuitka was installed:

In a virtual environment, using either the pypi packages or the "https://github.com/Nuitka/Nuitka/archive/develop.zip" for the develop branch install test. See the Reproduction Steps for exact details.

### Packages installed

```
./.venv/bin/python3 -m pip freeze
Nuitka @ file:///home/<redacted>/scratchpad/metadata-debug/Nuitka-develop.zip#sha256=0df360570d20e0d8adda9e5e32856829af0797869320fe1e2acde83ba5adc03e
ordered-set==4.1.0
zstandard==0.21.0
```

**Comment by kayhayen** [comment] 2023-09-30 12:11
With `--debug` it triggers an assertion for me, so this is an unhandled error somehow too.

**Comment by kayhayen** [comment] 2023-09-30 12:14
So, handling that error removes the `SystemError` I guess, because the `RecursionError: maximum recursion depth exceeded` was not causing the function to not return the distribution list, but with NULL values contained, never too healthy.

**Comment by kayhayen** [comment] 2023-09-30 12:23
So, I changed the case, where the entry is not found in the meta path based loader to not fallback to other mechanisms (there is no point), but to raise an error.

> RuntimeError: cannot locate package 'lxml' associated with metadata

In that way, the error is not fully understood of course. I will now try and avoid it by including the module entry needed by making it `--include-module` effectively, but I believe I want to first make sure it's working like that from the command line too.

**Comment by kayhayen** [comment] 2023-09-30 12:24
Case in point:

```
uitka-Plugins:WARNING: anti-bloat: Undesirable import of 'doctest' (intending to avoid 'unittest') in
Nuitka-Plugins:WARNING: 'lxml.doctestcompare' (at
Nuitka-Plugins:WARNING: '/home/hayen/.local/lib/python3.10/site-packages/lxml/doctestcompare.py:41')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at
Nuitka-Plugins:WARNING: https://nuitka.net/info/unwanted-module.html
```

**Comment by kayhayen** [comment] 2023-09-30 16:15
Ok, this now works as intended, i.e. if you `--include-module` on a package, it does only that top level module, and whatever it uses, getting rid of above warning.

**Comment by kayhayen** [comment] 2023-09-30 17:09
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-09-30 17:10
I still intend to warn or make it automatic, to include the module that way if it is not being included.

**Comment by kayhayen** [comment] 2023-10-02 12:55
So, that warning was added in the form of an error. This will be good now, however, I won't put that into the hotfix, but only 1.9 but not trace that really here, since 1.9 should come relatively soon anyway.

**Comment by jaustinpage** [comment] 2023-10-02 13:15
I tested factory, it is working as expected.

**Comment by kayhayen** [comment] 2023-10-12 06:44
This is now on the develop branch and part of the latest pre-release, will be part of the 1.9 release that will eventually follow.

**Comment by kayhayen** [comment] 2023-11-23 08:34
Part of the 1.9 release I just made.

**Closed by kayhayen** 2023-11-23 08:34 UTC
Labels: enhancement, develop
