### ISSUE TITLE
accessing TypeAliasType.__value__ attempts to call the value

### ISSUE THREAD

**Issue by Rooba** [Nuitka/Nuitka#3004] opened 2024-07-13 22:53 UTC
`Nuitka version, full Python version, flavor, OS, etc. as output by this exact command.`
```sh
% python3 -m nuitka --version
2.3.11
Commercial: None
Python: 3.12.4 (main, Jun 17 2024, 22:50:04) [GCC 13.2.0]
Flavor: pyenv
Executable: /home/ra/.venv/bin/python3
OS: Linux
Arch: x86_64
Distribution: Debian sid
Version C compiler: /usr/bin/gcc (gcc 13).
```

`How did you install Nuitka and Python`
```sh
% pyenv install 3.12.4
% pyenv local 3.12.4
% python3 -m venv .venv
% source .venv/bin/activate
% pip install nuitka
```

```py
from typing import TypeAliasType

type FeetType = "Feet"


class Bar(type):
    def __new__(cls, name, bases, namespace):
        for k, v in namespace["__annotations__"].items():
            if v.__class__ is TypeAliasType and isinstance(v.__value__, str) is False:
                ...
        return super().__new__(cls, name, bases, namespace)


class Foo(metaclass=Bar):
    foo: FeetType


class Feet: ...

```

The above should run without error, however 

```sh
% python3 -m nuitka --run test.py
Nuitka-Options: Used command line options: --run test.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.3.11' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13).
Nuitka-Scons: Backend linking program with 7 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 5
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 1
Nuitka: Keeping build directory 'test.build'.
Nuitka: Successfully created 'test.bin'.
Nuitka: Launching 'test.bin'.
Traceback (most recent call last):
  File "/home/ra/test.py", line 14, in <module>
    class Foo(metaclass=Bar):
    
  File "/home/ra/test.py", line 9, in __new__
    if v.__class__ is TypeAliasType and isinstance(v.__value__, str) is False:

TypeError: 'str' object is not callable
```

However, when the value of the TypeAliasType is set to `lambda: "Feet"` it works just fine:
```py
from typing import TypeAliasType

type FeetType = lambda: "Feet"


class Bar(type):
    def __new__(cls, name, bases, namespace):
        for k, v in namespace["__annotations__"].items():
            if v.__class__ is TypeAliasType and isinstance(v.__value__, str) is False:
                ...
        return super().__new__(cls, name, bases, namespace)


class Foo(metaclass=Bar):
    foo: FeetType


class Feet: ...

```

```sh
% python3 -m nuitka --run test.py
Nuitka-Options: Used command line options: --run test.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.3.11' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13).
Nuitka-Scons: Backend linking program with 7 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 5
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 1
Nuitka: Keeping build directory 'test.build'.
Nuitka: Successfully created 'test.bin'.
Nuitka: Launching 'test.bin'.
```

note: even with `--full-compat`, it still errors

**Comment by kayhayen** [comment] 2024-07-14 08:38
The `--full-compat` is never really doing meaningful things for compatibility, only bug compatibility like wrong line numbers, worse messages etc. so that's expected to not help. I am also critizing the use of pyenv, which I do not consider as well supported, but once Nuitka backend Python hits us, this will no longer be a worry. 

With Ubuntu Python, it's not happening for me, but I just noticed I only work around their specific libstatic-python bug in standalone mode, but with that fixed, it just works for me, which is what I expected, sort of when seeing the test case, since it's nothing special.

The main reason, pyenv is pronounced unsupported in the User Manual is so far related to it being not really unusable for standalone mode, this however looks really scary.

**Comment by kayhayen** [comment] 2024-07-14 08:45
I will be trying pyenv for myself now, just to see that it's not an issue that just cannot be reproduced. It seems they are doing an unoptimized build, do they, downloading the source and then finishing so fast, means they don't do PGO or anything good.

**Comment by kayhayen** [comment] 2024-07-14 08:50
Well, I cannot reproduce it at all, also not with the pyenv that I just installed, neither with git main nor my internal branch of what's going to be 2.4 soon. Maybe you shouldn't use Debian sid, and this is a build error of some sorts for Python and/or Nuitka created binaries. I will have to close it as invalid.

**Closed by kayhayen** 2024-07-14 08:50 UTC
Labels: bug, excellent_report

**Comment by Rooba** [comment] 2024-07-14 16:38
```py
from typing import TYPE_CHECKING

if TYPE_CHECKING:

    class Foo: ...  # Something we cannot actually import due to circular imports


type FooType2 = "Foo"


try:
    type FooType = Foo  # NameError: name 'Foo' is not defined
                        # gets evaluated before accessing FooType.__value__
except NameError:
    type FooType = object



print(FooType.__value__)  # returns an instance of object, whereas running this normally it returns the type
print(FooType2.__value__)  # TypeError: 'str' object is not callable
```

The problem occurs when a TypeAliasType is of a ForwardRef

**Comment by Rooba** [comment] 2024-07-14 16:40
Scratch that, running it normally it will evaluate `type FooType = Foo`, throw NameError, and exit, not allowing it to be caught
