### ISSUE TITLE
AttributeError: 'ExpressionRaiseException' object has no attribute 'getVariable'

### ISSUE THREAD

**Issue by ubmarco** [Nuitka/Nuitka#2710] opened 2024-02-13 10:35 UTC
I'm running `nuitka3 .venv/lib/python3.11/site-packages/sphinx/domains/javascript.py` on this file https://github.com/sphinx-doc/sphinx/blob/v7.2.6/sphinx/domains/javascript.py and it has a problem dealing with a code construct. It raises an exception and the handling routine then raises an `AttributeError`. So maybe these are actually 2 issues.
```
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/VariableAssignNodes.py", line 920, in computeStatement
    if not variable.isModuleVariable() and old_source.getVariable() is variable:
                                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ExpressionRaiseException' object has no attribute 'getVariable'
```

I stripped down the target file, removed all imports and found this snippet to still produce the problem:
```
def handle_signature(self, sig: str, signode) -> tuple[str, str]:
    sig = sig.strip()
    if '(' in sig and sig[-1:] == ')':
        member, arglist = sig.split('(', 1)
        member = member.strip()
        arglist = arglist[:-1].strip()
    else:
        member = sig
        arglist = None

    name = member
    try:
        _, member_name = member.rsplit('.', 1)
    except ValueError:
        member_name = name
    finally:
        name = member_name
```

Here is the full traceback for above snippet:
```
Problem with statement at .venv/lib/python3.11/site-packages/sphinx/domains/javascript.py:18:
->         name = member_name

Problem with statement at .venv/lib/python3.11/site-packages/sphinx/domains/javascript.py:13:
->     try:

Problem with statement at .venv/lib/python3.11/site-packages/sphinx/domains/javascript.py:13:
->     try:

Problem with statement at .venv/lib/python3.11/site-packages/sphinx/domains/javascript.py:2:
-> def handle_signature(self, sig: str, signode) -> tuple[str, str]:

Problem with statement at .venv/lib/python3.11/site-packages/sphinx/domains/javascript.py:2:
-> def handle_signature(self, sig: str, signode) -> tuple[str, str]:

Nuitka: Interrupted while working on '<Node 'PYTHON_MAIN_MODULE' with {'filename': '.venv/lib/python3.11/site-packages/sphinx/domains/javascript.py', 'module_name': <ModuleName '__main__'>, 'main_added': False, 'mode': 'compiled',
Nuitka: 'code_flags': ''}>'.
Nuitka-Reports: Compilation report written to file 'nuitka-crash-report.xml'.
PASS 1: 0.0%|                         | 0/1, __main__Traceback (most recent call last):
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/__main__.py", line 172, in <module>
    main()
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/__main__.py", line 158, in main
    MainControl.main()
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/MainControl.py", line 1130, in main
    _main()
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/MainControl.py", line 979, in _main
    main_module = _createMainModule()
                  ^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/MainControl.py", line 256, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 344, in optimizeModules
    finished = makeOptimizationPass()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 300, in makeOptimizationPass
    changed = optimizeModule(current_module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 176, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/Optimization.py", line 92, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/ModuleNodes.py", line 557, in computeModule
    result = module_body.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 149, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/FrameNodes.py", line 188, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/VariableAssignNodes.py", line 352, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/ChildrenHavingMixins.py", line 4870, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 643, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/FunctionNodes.py", line 1154, in computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 348, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/FunctionNodes.py", line 494, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/FunctionNodes.py", line 510, in computeFunction
    result = statements_sequence.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 151, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 149, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/FrameNodes.py", line 188, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/TryNodes.py", line 140, in computeStatement
    result = except_handler.computeStatementsSequence(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 151, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/StatementNodes.py", line 151, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/optimizations/TraceCollections.py", line 657, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marco/ub/ubdocs/.venv/lib/python3.11/site-packages/nuitka/nodes/VariableAssignNodes.py", line 920, in computeStatement
    if not variable.isModuleVariable() and old_source.getVariable() is variable:
                                           ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ExpressionRaiseException' object has no attribute 'getVariable'
```

I also tried the `develop` branch to no avail.

  > python -m nuitka --version

```
2.1rc3
Commercial: None
Python: 3.11.6 (main, Oct 24 2023, 12:53:42) [GCC 13.2.1 20230801]
Flavor: pyenv
Executable: /home/marco/ub/ubdocs/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch None
Version C compiler: /usr/sbin/gcc (gcc 13.2.1).
```

  > python -m pip freeze

```
alabaster==0.7.16
Babel==2.14.0
certifi==2024.2.2
charset-normalizer==3.3.2
docutils==0.20.1
idna==3.6
imagesize==1.4.1
Jinja2==3.1.3
MarkupSafe==2.1.5
Nuitka==2.0.2
ordered-set==4.1.0
packaging==23.2
Pygments==2.17.2
requests==2.31.0
snowballstemmer==2.2.0
Sphinx==7.2.6
sphinxcontrib-applehelp==1.0.8
sphinxcontrib-devhelp==1.0.6
sphinxcontrib-htmlhelp==2.0.5
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.7
sphinxcontrib-serializinghtml==1.1.10
urllib3==2.2.0
zstandard==0.22.0
```

**Comment by kayhayen** [comment] 2024-02-13 10:58
I can confirm this affects the current stable release and my current factory version, which has seen changes on assignment handling, that could have made it invisible.

The code in question is problematic, since it uses member_name which will be unassigned, if anything but a `ValueError` occurs, which is probably impossible, but Nuitka doesn't know that, so for at least some branch, it is OK to optimize it to a static raise, and then it hates that it's not a variable access anymore. Probably some form of check is missing there.

**Comment by kayhayen** [comment] 2024-02-13 10:59
```
        try:
            member_prefix, member_name = member.rsplit('.', 1)
        except ValueError:
            member_name = name
            member_prefix = ''
        finally:
            name = member_name
```

The trouble making part is this.

**Comment by kayhayen** [comment] 2024-02-13 11:00
The upstream, probably means this to not be `finally` just training code, as an aside, but these kinds of bugs must of course not trigger Nuitka to become incompatible.

**Comment by ubmarco** [comment] 2024-02-13 11:31
Thanks for the super quick reply and analysis.
Right, the code works unless there is something else than a `ValueError`.

Btw, thanks for this awesome project. With the exception of this single file, it could translate the whole [Sphinx](https://github.com/sphinx-doc/sphinx) project without any issues. Have to read more about the project. Also have to test how it works for multiprocessing and dill.

Gruß aus München.

**Comment by kayhayen** [comment] 2024-02-13 11:44
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2024-02-13 11:48
Since I recently touched this code, optimizing assignment statements for better scalability, I am not sure how thrilled I am at the idea of making this into a hotfix, but it seems a very valid issue, I will therefore have to do it twice, and now to avoid merge conflicts, and get this into a 2.0.3 release. For dill and multiprocessing, Nuitka should be fine like for just about everything. For non-working, non-good code, sometimes the test coverage is lacking. I am however surprised to see sphinx not working, maybe relatively new code. 

Are you doing a standalone build, or are you trying module by module, which is of course far from optimal?

**Comment by ubmarco** [comment] 2024-02-13 14:03
I can confirm your bugfix works, at least I don't see the crash anymore. Awesome user support.

> I am however surprised to see sphinx not working, maybe relatively new code.

Just checked `git blame`, the last change on this code part is 7 years ago. However an example project might not use the `javascript` domain at all as it depends on the input files. The only direct import of that file in Sphinx depends on the definition of `TYPE_CHECKING`.

**Comment by ubmarco** [comment] 2024-02-13 14:05
> Are you doing a standalone build, or are you trying module by module, which is of course far from optimal?

I'm doing a standalone build of a bigger scope. I only called `nuitka` directly on that file to reproduce the problem.

**Comment by kayhayen** [comment] 2024-02-14 12:18
So, I had a bit of regressions there on factory from this, and my special backport, which I will have to merge with, so this delays the hotfix for a bit.

**Comment by kayhayen** [comment] 2024-02-18 13:02
Part of the 2.0.3 hotfix that I just made.

**Closed by kayhayen** 2024-02-18 13:02 UTC
Labels: bug, factory, excellent_report
