### ISSUE TITLE
Doesn't include extension modules even if explicitly included

### ISSUE THREAD

**Issue by berzi** [Nuitka/Nuitka#1112] opened 2021-05-29 16:23 UTC
```
Nuitka: 0.6.15
Python: 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)]
OS: Windows
Arch: x86_64
```

Installed through pip in a venv.

Options used:
```
--standalone
--onefile
--assume-yes-for-downloads
--include-package-data=cnocr
--include-package-data=mxnet
--include-package-data=h5py
--include-package-data=h5py.defs
--include-package-data=pywordseg
--include-module=h5py
--include-module=h5py.defs
--include-data-file=venv\\Lib\\site-packages\\mxnet\\*.dll=mxnet/
--plugin-enable=multiprocessing
--plugin-enable=numpy
--plugin-enable=qt-plugins
--plugin-enable=torch
--windows-force-stderr-spec=%PROGRAM%_ERRORS.log
--windows-icon-from-ico=icon.ico
--windows-company-name=NAME
--windows-product-name=NAME
--windows-product-version=VERSION
```

The program is a PyQt application with a few important dependencies that use deep learning models internally.

**The problem:**
```
Nuitka:WARNING: Did not follow import to unused 'h5py.defs', consider include options.
```

To me, this reads as "I did not include h5py.defs because it's not used. Consider including it explicitly". If you look at the options I run nuitka with, this is exactly what I did, and in fact the warning isn't even there if I don't include this module, but the application crashes at runtime because of a ModuleNotFoundError related to this module—that's why I want to include it. And yet even though I explicitly include it, nuitka seems to refuse to do it. What am I supposed to do to include this module, ignoring the (absolutely incorrect) assumption by nuitka that it is not needed?

**Comment by kayhayen** [comment] 2021-05-30 09:04
I agree, this looks like a bug. However, when you say `--include-module=some_package` that limits the inclusion apparently and is not what is intended. I assume if you remove it, the issue is gone, because parent packages get included. For including a whole package, you put `--include-package`. But it seems I will need to have a look of my own and `h5py` could serve for that.

**Comment by kayhayen** [comment] 2021-05-30 09:31
This could also be because it's an extension module, and if these are used as root modules, but not as used modules, the code forgets to include that. Then this would affect all extension modules and probably has been reported before, but not understood.

**Comment by kayhayen** [comment] 2021-05-30 09:32
I could falsify my first assumptions, the code doesn't do that kind of limiting from inclusion options. Know however, that you probably meant `--include-package` which would have addressed the issue as well, but potentially includes too much. I think I have a fix for this to work as given in your example.

**Comment by kayhayen** [comment] 2021-05-30 10:20
The `--include-module|package' options are secretely implemented in terms of very much older code, which didn't include extension modules as being root modules, and therefore didn't have the intended effect. In standalone mode of course, this must be done though. I believe that code is older than standalone mode, originally created for plugin directories.

**Comment by kayhayen** [comment] 2021-05-30 10:21
This should be fixed on factory: https://nuitka.net/doc/factory.html

**Comment by berzi** [comment] 2021-05-30 19:17
Thank you, that was quick! I'm hesistant to use factory, but I'll try using --include-package=h5py and report back.

**Comment by berzi** [comment] 2021-05-30 21:11
I tried replacing the `--include-package-data` and `--include-module` options relating to h5py with `--include-package=h5py` but unfortunately it didn't work.

The options I tried, to be exact, are:
```
--standalone
--onefile
--assume-yes-for-downloads
--include-package-data=cnocr
--include-package-data=mxnet
--include-package-data=pywordseg
--include-package=h5py            r"--include-data-file=venv\Lib\site-packages\mxnet\*.dll=mxnet/",
            "--plugin-enable=multiprocessing",
            "--plugin-enable=numpy",
            "--plugin-enable=qt-plugins",
            "--plugin-enable=torch",
```

This is the result when I run the exe (and do the action that triggers the import of pywordseg, a dependency which evidently uses h5py under the hood. It's a local import (but not dynamic or anything)):
```
E:\Programming\myProject> .\main.exe
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\MYPROJ~1\MYPROJ~1\100~1.0\main.py", line 308, in translate_content
    import pywordseg
  File "C:\Users\user\AppData\Local\MYPROJ~1\MYPROJ~1\100~1.0\pywordseg\__init__.py", line 20, in <module pywordseg>
  File "C:\Users\user\AppData\Local\MYPROJ~1\MYPROJ~1\100~1.0\pywordseg\pywordseg.py", line 5, in <module pywordseg.pywordseg>
  File "C:\Users\user\AppData\Local\MYPROJ~1\MYPROJ~1\100~1.0\pywordseg\ELMoForManyLangs\elmo.py", line 20, in <module pywordseg.ELMoForManyLangs.elmo>
    from .src.modules.elmo import ElmobiLm
  File "C:\Users\user\AppData\Local\MYPROJ~1\MYPROJ~1\100~1.0\pywordseg\ELMoForManyLangs\src\modules\elmo.py", line 3, in <module pywordseg.ELMoForManyLangs.src.modules.elmo>
    import h5py
  File "C:\Users\user\AppData\Local\MYPROJ~1\MYPROJ~1\100~1.0\h5py\__init__.py", line 33, in <module h5py>
  File "C:\Users\user\AppData\Local\MYPROJ~1\MYPROJ~1\100~1.0\h5py\version.py", line 15, in <module h5py.version>
  File "h5py\h5.pyx", line 1, in init h5py.h5
ModuleNotFoundError: No module named 'h5py.defs'
```

I haven't tried `--include-package=h5py.defs` or `--include-package--data=h5py` yet. Unfortunately compilation lasts forever so I'll have to report back tomorrow for that, at the earliest.

**Comment by kayhayen** [comment] 2021-06-01 08:17
Part of 0.6.15.1 hotfix release.

**Closed by kayhayen** 2021-06-01 08:17 UTC
Labels: bug
