### ISSUE TITLE
OpenCV is missing DLL for video capture

### ISSUE THREAD

**Issue by zqbxx** [Nuitka/Nuitka#1908] opened 2022-11-24 08:17 UTC
Missing opencv_videoio_ffmpeg460_64.dll after compile.

Web camera has this problem. Local camera is ok.

Opencv needs this dll to decide file type when filename extension missing I guess.

```
nuitka --version
1.2.2
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: F:\python\venv\editor\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

```
pip list | findstr cv
opencv-contrib-python 4.6.0.66

```
opencvwebcam.py

```
import cv2

cap = cv2.VideoCapture('http://aaa:aaa@192.168.1.102:8081/video')
ret, frame = cap.read()
if ret:
    print('success')
else:
    print('error')
```

```
python opencvwebcam.py
success
```

compile
```
nuitka --show-progress --standalone --follow-imports --enable-plugin=numpy --mingw64  opencvwebcam.py
```

run 
```
opencvwebcam.exe
```

```
opencvwebcam.exe
[ERROR:0@0.212] global D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap.cpp (166) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.6.0) D:\a\opencv-python\opencv-python\opencv\modules\videoio\src\cap_images.cpp:253: error: (-5:Bad argument) CAP_IMAGES: can't find starting number (in the name of file): http://aaa:aaa@192.168.1.102:8081/video in function 'cv::icvExtractPattern'
```

**Comment by kayhayen** [comment] 2022-11-24 10:26
Hardware dependent reproducers are kind of a problem for me. Is there some public URL that I could use to reproduce this?

**Comment by zqbxx** [comment] 2022-11-24 12:05
> Hardware dependent reproducers are kind of a problem for me. Is there some public URL that I could use to reproduce this?

This is not a hardware dependent problem. Use `cv2.VideoCapture` open media file need `opencv_videoio_ffmpeg460_64.dll`

opencvwebcam.py
```
import sys
import cv2

cap = cv2.VideoCapture(sys.argv[1])
ret, frame = cap.read()
if ret:
    print('success')
else:
    print('error')
```

opencvwebcam.exe <your media file path>

**Comment by zqbxx** [comment] 2022-11-24 12:05
> Hardware dependent reproducers are kind of a problem for me. Is there some public URL that I could use to reproduce this?

This is not a hardware dependent problem. Use `cv2.VideoCapture` open media file need `opencv_videoio_ffmpeg460_64.dll`

opencvwebcam.py
```
import sys
import cv2

cap = cv2.VideoCapture(sys.argv[1])
ret, frame = cap.read()
if ret:
    print('success')
else:
    print('error')
```

opencvwebcam.exe your_media_file_path

**Comment by kayhayen** [comment] 2022-11-24 14:07
Ah, it seems you were saying the local camera was working, but a webcam was not?

> Web camera has this problem. Local camera is ok.

But since you identified the missing DLL, I don't think there is a problem to just include it.

**Comment by kayhayen** [comment] 2022-11-24 14:50
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2022-11-26 18:11
This is part of the hotfix release 1.2.3 that I just made.

**Closed by kayhayen** 2022-11-26 18:11 UTC
Labels: bug
