### ISSUE TITLE
Windows: The sys.stdin, sys.stdout, sys.stderr should not be none with --windows-disable-console

### ISSUE THREAD

**Issue by xbc922** [Nuitka/Nuitka#1339] opened 2021-12-24 06:02 UTC
when use uvicorn  run and asgiapp and  --windows-disable-console  is working,you must use:

uvicorn.run(app, host=host, port=port,  use_colors=use_colors)

**Comment by kayhayen** [comment] 2021-12-24 11:39
Hello,

not sure what you are suggesting here. Can you give a more complete example? If there is anything needed to get `uvicorn` working, I would appreciate to know and potentially even make a plugin of Nuitka do it automatically, but the line of code you gave seems very empty of information?

**Comment by xbc922** [comment] 2021-12-25 03:17
when i use uvicorn run an fastapi app,and nuitka package on windows;i use --windows-disable-console then python sys.stdout=None,but on uvicorn  don't  consider this situation,use_colors args is None uvicorn  will use sys.stdout.isatty()  get an Exception

**Comment by xbc922** [comment] 2021-12-25 03:19
It's not your fault, it's a bug solution. when use uvicorn and nuitka  --windows-disable-console

uvicorn.run(app, host=host, port=port, use_colors=use_colors)

 set the use_colors is True or False not None

**Comment by kayhayen** [comment] 2021-12-31 10:33
Ah, I see what you are saying. I seem to remember than it being `None` may not be the compatible thing. Which Python version are we talking about?

**Comment by xbc922** [comment] 2021-12-31 10:35
> 

python 3.6.8 windows 32bit

**Comment by kayhayen** [comment] 2021-12-31 10:38
This code is supposed to prevent it:

```
    /* At least on Windows, we support disabling the console via linker flag, but now
       need to provide the NUL standard file handles manually in this case. */
    {
        PyObject *nul_filename = Nuitka_String_FromString("NUL:");

        if (Nuitka_SysGetObject("stdin") == NULL) {
            PyObject *stdin_file = BUILTIN_OPEN_SIMPLE(nul_filename, "r", NULL);

            CHECK_OBJECT(stdin_file);
            Nuitka_SysSetObject("stdin", stdin_file);
        }

        if (Nuitka_SysGetObject("stdout") == NULL) {
            PyObject *stdout_file = BUILTIN_OPEN_SIMPLE(nul_filename, "w", NULL);

            CHECK_OBJECT(stdout_file);
            Nuitka_SysSetObject("stdout", stdout_file);
        }

        if (Nuitka_SysGetObject("stderr") == NULL) {
            PyObject *stderr_file = BUILTIN_OPEN_SIMPLE(nul_filename, "w", NULL);

            CHECK_OBJECT(stderr_file);

            Nuitka_SysSetObject("stderr", stderr_file);
        }

        Py_DECREF(nul_filename);
    }
```

In that way, it should always have the stdout, but as a text file. I wonder if it's the encoding. Can you print the `sys.stdout` to see if it's really `None` or if we have an encoding issue. This code checks unset value, but maybe that's not what is happening, and maybe a Python version sets it to None actually, then the check would fail, while I assume that looking it up for NULL gives not necessarily attribute error, but None in case it's NULL.

**Comment by xbc922** [comment] 2021-12-31 10:41
OK, I'll check whether it's really none later and feed back the results

**Comment by kayhayen** [comment] 2021-12-31 10:45
Thanks, also as an aside, you could force the output to a file, that would also work in all cases and need no terminal.

**Comment by xbc922** [comment] 2021-12-31 10:58
version: 
nuitka==0.6.16.4
Python 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] on win32

my code:
#!/usr/bin/env python
# -*- coding:utf-8 -*-
import datetime
import sys

from log import Logger

if __name__ == '__main__':
    Logger.info(f'cur date:{datetime.datetime.now()}')
    Logger.info(f'stdout：{sys.stdout}')


This is sys compiled with -- windows disable console args stdout:

[2021-12-31 18:55:25,453 PID:14628  17448 INFO]: [<module>()]: cur date:2021-12-31 18:55:25.453351
[2021-12-31 18:55:25,453 PID:14628  17448 INFO]: [<module>()]: stdout：None


This is sys compiled without -- windows disable console args stdout:

[2021-12-31 18:57:01,722 PID:12688  18396 INFO]: [<module>()]: cur date:2021-12-31 18:57:01.722254
[2021-12-31 18:57:01,723 PID:12688  18396 INFO]: [<module>()]: stdout：<_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>

**Comment by kayhayen** [comment] 2021-12-31 11:20
I managed to reproduce it, with a different program, not sure what log is:

```
import sys

import logging
logging.basicConfig(filename="output.txt",
                            filemode='a',
                            format='%(asctime)s,%(msecs)d %(name)s %(levelname)s %(message)s',
                            datefmt='%H:%M:%S',
                            level=logging.INFO)

if __name__ == '__main__':
    logging.info(repr(sys.stdout))
```

**Comment by kayhayen** [comment] 2021-12-31 11:34
This is fixed on the factory branch, https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment] 2021-12-31 11:36
These values were indeed `None`, I think I saw `NULL` before, now checking for both, this likely was true on Python2 or earlier Python3, doesn't matter really though, seems to be affecting at least 3.6

**Comment by kayhayen** [comment] 2022-01-05 12:04
This now part of the current pre-release and will be part of 0.6.19 which should arrive shortly.

**Closed** 2022-01-05 13:49 UTC
Labels: bug, develop

**Comment by kayhayen** [comment] 2022-01-09 16:15
Part of the 0.6.19 release I just made.
