### ISSUE TITLE
How to compile in pc for linux

### ISSUE THREAD

**Issue by iPurya** [Nuitka/Nuitka#648] opened 2020-03-11 17:46 UTC
Hey,
im trying to compile my script for linux and when im doing this i get exe file as output
so thats a question for me how can i compile for other os like Ubuntu..

thanks

**Comment by swedneck** [comment] 2020-03-12 21:17
i believe this a duplicate of #43

**Comment by kayhayen** [comment] 2020-03-13 20:18
Yes, that is true @swedneck thanks

**Closed by kayhayen** 2020-03-13 20:18 UTC
Labels: duplicate

**Comment by qiuwei** [comment] 2021-04-14 08:23
Use docker?
