### ISSUE TITLE
Dictionary function COPY_DICT_KW(PyObject *dict_value) asserts

### ISSUE THREAD

**Issue by erduotong** [Nuitka/Nuitka#2402] opened 2023-08-23 03:36 UTC
My running environment:  
requests 2.28.2  
nuitka 1.7.10  
python 3.11.3  
I wrote the following code to implement a simple API request:  
``````
import json  
import requests
url = 'https://api.github.com/repos/erduotong/Simple_Class_Information_Display/releases/latest'
print("start")
response = requests.get(url,verify=True)
print("after")
print(json.dumps(response.json(),indent=4,ensure_ascii=False))
``````
Then I compiled it with this command:  
> nuitka --standalone --mingw64 --show-memory --show-progress --remove-output --output-dir=../exe test.py  

On my environment, it can normally output 'start', 'after' and the results obtained from the API, and then exit.     
But in the exe processed by nuitka, it can only output 'start', and then there is nothing, no error, nothing at all.

**Comment by kayhayen** [comment] 2023-08-23 06:57
The version output really shouldn't be typed up manually but incomplete.

**Comment by erduotong** [comment] 2023-08-23 07:06
Sorry, the information provided is insufficient
1.7.10
Commercial: None
Python: 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\13568\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).

**Comment by kayhayen** [comment] 2023-08-23 07:36
I cannot reproduce it. The output contains what I believe to be chinese characters, I was wondering if it is that, but if you say you do not get the output after the request, then it's not chinese yet. I tried with MSVC and MinGW64 both working. I was one minor behind in requests with that, updating to yours also worked fine. 

As as cheap shot, can you run with `--debug` compilation enabled? If this is a crash, Nuitka has high chances of doing an assertion about it.

**Comment by erduotong** [comment] 2023-08-23 08:12
I tried using the same parameters, but now it can get and output normally again.   
However, during the last error, Nuitka told me:   
``````
Assertion failed: dict_mp->ma_keys->dk_kind == DICT_KEYS_GENERAL, file C:\Users\13568\AppData\Local\Programs\Python\PYTHON~2\Lib\SITE-P~1\nuitka\build\static_src/HelpersDictionariesGenerated.c, line 705
``````

**Comment by kayhayen** [comment] 2023-08-24 06:27
Oh wow, that's bad. We got to find that for sure, the dictionary kind is not what Nuitka expects in some place. Errors might very well be random and spurious when that happens. I do not reproduce it. Since it depends on an external query, that might be bad for reproducing it entirely. It seems related to a `DICT_COPY_KW` that is not in an expected mode during what is probably a call with star dict argument. I am trying to see if I can somehow reproduce it elsewise, or wrap my head around why the assertion might fire, and if it's even warranted.

**Comment by kayhayen** [comment] 2023-08-27 09:30
Running the test suite in debug mode, did not reveal anything like it.

**Comment by erduotong** [comment] 2023-08-27 09:44
I don't know what happened, but there's no problem in building it now. I can't reproduce this problem，too

(using the same procedures and commands)

**Comment by kayhayen** [comment] 2023-08-30 08:03
In this code the assertion triggers:

```
        if (_PyDict_HasSplitTable(dict_mp)) {
            Py_ssize_t size = DK_ENTRIES_SIZE(dict_mp->ma_keys);

            PyDictObject *result_mp = _Nuitka_AllocatePyDictObject();
            assert(result_mp != NULL);
            result = (PyObject *)result_mp;

            for (Py_ssize_t i = 0; i < size; i++) {
                PyDictKeyEntry *entry = &DK_ENTRIES(dict_mp->ma_keys)[i];

                if (entry->me_value != NULL) {
                    PyObject *key = entry->me_key;
                    if (unlikely(!checkKeywordType(key))) {
                        had_kw_error = true;
                    }
                }
            }

            PyDictValues *new_values = _Nuitka_PyDict_new_values(size);
            assert(new_values != NULL);
```

It needs to be investigated, if maybe something got added for 3.11 dictionaries besides split tables, that can make this trigger.

**Comment by kayhayen** [comment] 2024-05-05 11:52
This should be fixed by now, we have made corrections in the dictionary area. Please open the issue again should it happen all over, but I never reproduced it, so I cannot tell if it's current still.

**Closed by kayhayen** 2024-05-05 11:52 UTC
Labels: bug
