### ISSUE TITLE
Performance penalty for uncompiled code

### ISSUE THREAD

**Issue by k-sok** [Nuitka/Nuitka#177] opened 2018-10-16 17:39 UTC
```
$ pip3 install nuitka
$ python -m nuitka --version
0.6.0.3 
Python: 3.6.6 (default, Sep 12 2018, 18:26:19) 
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
```
(same behavior with 0.6.1rc6)

```
# test.py
import time
import re

start = time.time()
for i in range(2000000):
    re.match('xyz', 'asdf')    
print(time.time() - start)
```
```
$ python test.py
4.666041374206543
```
```
$ python -m nuitka --run  test.py
8.2843918800354
```

Similar performance penalty also with ``os.fspath`` for example.

**Comment by kayhayen** [comment] 2018-10-16 18:53
Very interesting. I need to find the different to this: http://speedcenter.nuitka.net/constructs/construct-calluncompiledfunctionposargs.html

The re.match is an uncompiled function in this case.

Calling with constant arguments is even faster with compiled functions.

http://speedcenter.nuitka.net/constructs/construct-callcompiledfunctionposargsconstant.html

So could this be the foreign module variable lookup, I need to check.

But definitely, if I can reproduce this, seems there is some important finding to be had.

Yours,
Kay

**Comment by kayhayen** [comment] 2018-10-16 19:12
On my laptop with Python2 with Nuitka 13-15s and CPython 13s, so also not better, although I was pretty sure, looping and uncompiled call, even module lookup, should all be faster there for sure, although if the majority of the CPU is spent inside "re", then equal would be justified.

With Python3, Nuitka is way slower, 11-12s and CPython 8-9s, so something happening.

When I eliminated the `re.match` lookup from the loop via `match = re.match` that didn't change much, so this should either be about the range loop or the uncompiled function call with constant arguments, maybe CPython is using a trick there, that Nuitka is not yet emulating.

I am very confused, because I also believe using module variable for the loop variable `i` should also allow Nuitka to be faster, but then it was not.

Checking the C code, this is probably happening:

`
    tmp_call_result_1 = CALL_FUNCTION_WITH_ARGS2( tmp_called_name_1, &PyTuple_GET_ITEM( const_tuple_str_plain_xyz_str_plain_asdf_tuple, 0 ) );
`
So Nuitka turns the constant tuple into a `PyObject **`, but I don't see it turn it into a tuple, which would be slow. It very probably is something about the function call. I will try and add a construct test, where "re.match" is used, and see how it compares in that environment.

Yours,
Kay

**Comment by k-sok** [comment] 2018-10-16 19:20
Btw: the same penalty occurs on Windows, too. But what's even stranger: it happens also with PyInstaller and cx_freeze

**Comment by k-sok** [comment] 2018-10-16 19:23
And in my real application it happened with non-constant arguments as well. When calling posixpath.join

**Comment by kayhayen** [comment] 2018-10-17 05:37
So I tried this for the uncompiled call construct test:

```
 exec("""
-def python_func(a,b,c,d,e,f):
+def python_func(a,b,c,d,e,f, g=0):
     pass
 """)

```

Speed difference for gain becomes 133% instead of 135% for Python2 and 120% instead of 129% for Python3, but nowhere near a reason to slow down. The default argument makes it take a slower path yes, but identical code at that point.

Now I will try with re.match, there must be something else that is special about it perhaps.

**Comment by kayhayen** [comment] 2018-10-17 05:41
So this diff changes a bit:

```
-exec("""
-def python_func(a,b,c,d,e,f):
-    pass
-""")
+import re
+python_func = re.match
 
 def calledRepeatedly():
     # This is supposed to make a call to a non-compiled function, which is
     # being optimized separately.
 # construct_begin
-    python_func("some", "random", "values", "to", "check", "call")
-    python_func("some", "other", "values", "to", "check", "call")
-    python_func("some", "new", "values", "to", "check", "call")
+    python_func("some", "random")

```

With this, gain becomes 92%, i.e. we see an actual slow down just by using another function and less arguments.

**Comment by kayhayen** [comment] 2018-10-17 05:44
When reducing the `exec` function and its calls to 2 arguments, things do down to 111% speed gain, but definitely a gain still. Seems large part of the speedup comes from better argument preparation for constant arguments, which skews the results somewhat, but probably will be less real with non-constants.

**Comment by kayhayen** [comment] 2018-10-17 07:30
This is very confusing, I am nearly convinced that Python's `fast_function` is doing exactly the same thing as what Nuitka's `callPythonFunction` is doing, except for irrelevant differences. I even commented out compiled type checks (for fast paths) and no change. Inlined the code that executes an uncompiled function, which for Nuitka goes for a API, and could be inlined for CPython.

Then I also disabled the loop tick counting, so GC cleanups cannot hit, inspect patching of isinstance, traceback patching, and I find nothing left, yet the real time test shows 2.1s to 2.4s with your benchmark still, which is very puzzling, as I don't see much left in terms of code paths.

I even checked if it reference leaks, it does not.

**Comment by kayhayen** [comment] 2018-10-17 09:02
I can chop of a few cycles by inlining the Python 3.5 (which is what I was using) code for calling a Python function. This brings the "exec" result to above 1.0 gain factor.

Not having keyword arguments is something to remove code for, as also we can delay the resolution of "name" and "qualname" for generators and coroutines only, which brings the "exec" above 100%, which the mere inline with optimization.

I am at loss, what makes the "re.match" behave different at this time. I checked the co_flags and it seemed identical to me, the flags drive the overhead, e.g. creating keyword arguments dictionary, etc. for un-compiled functions.

My expectation is actually that the more work is being done in `re.match` (although it caches results, and therefore will mostly be relatively little code) the gain should become closer to 100%, not further away. I am not getting how being called by Nuitka would make re.match slower. And I can validate that, if e.g. I have `return "a+b"` then I have 102% and for `pass` I have 111% gain.

I with try other code you mentioned too, `os.path.join` has the same issue?

**Comment by k-sok** [comment] 2018-10-17 09:08
Yes, at least ``posixpath.join``

Here is the complete original code I experienced the delay with:

```
def pathParents(path: str, includeComplete: bool=False) -> Generator[str, None, None]:
    stop = sys.maxsize if includeComplete else -1
    if path.endswith(posixpath.sep):
        path = path[:-1]
    resultPath = ''
    for pathComponent in path.split(posixpath.sep)[:stop]:
        if pathComponent == '':
            pathComponent = posixpath.sep
        resultPath = posixpath.join(resultPath, pathComponent)
        yield resultPath
```

**Comment by kayhayen** [comment] 2018-10-17 09:10
And yes, indeed also slower.

**Comment by kayhayen** [comment] 2018-10-17 10:07
My suspect that `os.path.join` calling `isinstance` which is affected by Nuitka makes a difference, was easy to eliminate, by disabling it, no difference.

I inlined the code of `posixpath.join` and will try to bisect it as to what makes it become negative gain.

**Comment by kayhayen** [comment] 2018-10-17 10:11
I am reminded of #150 now, because that is what has been observed too, but it might be the constant values used in the calls, somehow the unicode strings don't lend themselves as well as others, and there might be some minor difference in how Nuitka creates those unicode strings and then they perform worse for operations in some bizarre way.

**Comment by kayhayen** [comment] 2018-10-17 10:33
I tried making the strings come from eval, that didn't change a thing. I was thinking that Nuitka prefers to intern strings that could be used as names or attributes, and that could make it worse, but when I make it come from 'eval()' instead, and take care to use values that are not interned due to that, still no change, the constants wouldn't allow in-place shortcuts anyway.

However, using in-place string operations, I can make it flip. Otherwise calling the function is faster. Also bytes are faster with Nuitka. I am not getting behind that. 

This is driving me crazy. :)

**Comment by kayhayen** [comment] 2018-10-17 11:08
Ok, I think I have it.

With Nuitka, the code is run in dynamic link library `libpython` and with CPython it is run inside that static `python3.5` binary, which makes a difference for generated code. The library is very much slower, because it goes through `_PyUnicode_FastCopyCharacters` which is not inlined when compiling against the DLL, and could in fact be modified by some strange `dl` ways.

So for uncompiled code, there is going to be used a version of the code, that is slower in any case, and `PyUnicode_Append` is being used for in-place string operations, and tends to be slower therefore.

The proof would be to use Nuitka with a static Python, for which there is issue #95 which remains unsolved. This ought to then be faster.

For compiled code, Nuitka can in-line PyUnicode_Append code and not use the DLL one. The bytecode interpreter hard codes a check for unicode values and in-place add, will use the slow variant no matter what.

I am now thinking, I have resolved why Python3 is not as much faster with Nuitka than it could be in general. Obviously, if this was running under "python" as an extension module, no slow down would be incurred, so only accelerated and standalone mode are affected.

I will have to think of how to approach these issues. Seems static linking against Python got a huge priority boost right now.

**Comment by k-sok** [comment] 2018-10-17 12:17
Thanks for this deep investigation. I guess, the fact that the dynamic ``libpython`` is slower explains also why the same slowdown occurs also with PyInstaller and similar packaging approaches.

**Comment by kayhayen** [comment] 2018-10-17 12:51
Puh, so MiniConda for Python 3.6.5 gives me an error for the static link library, that requires to disable the "link time optimization" that apparently would be going on. My Debian Stretch has an too old gcc to understand the bytecode from the MiniConda library. And my Debian Testing gcc-8 is too new, and the gcc-7 is telling me invalid bytecode found there. So LTO from foreign static library, not going to happen.

However, after disabling LTO (which might degrade results probably in much the same way), I am getting this, tick numbers for the construct:

CPYTHON_CONSTRUCT=8761293 (minicoda 3.6.5)
NUITKA_CONSTRUCT=7846391 (nuitka static miniconda 3.6.5)
NUITKA_CONSTRUCT=8019981 (nuitka dynamic miniconda)
CPYTHON_CONSTRUCT=14321186 (CPython 3.6.3)
NUITKA_CONSTRUCT=19240186 (nuitka dynamic CPython 3.6.3)

What is noteworthy here is that Nuitka is much faster with MiniConda and even with dynamic linking, for this one construct. If I am not mistaken this is due to linking differently, even for the shared library case, where for CPython it's pretty dramatic. This one operation is then more than twice as slow, which is what your benchmark also observes.

**Comment by kayhayen** [comment] 2018-10-17 12:56
From Anaconda, I am getting this data point:

NUITKA_CONSTRUCT=8569981 (nuitka dynamic AnaConda 3.6.0)
CPYTHON_CONSTRUCT=9544613 (AnaConda 3.6.0 dynamic)

Again, Nuitka having a gain as it should be. So this means, actually CPython is doing something wrong there, and the workaround is to use AnaConda Python over CPython. I need to read up on what it is about MiniConda, that makes it yet faster, maybe there are compromises made.

**Comment by kayhayen** [comment] 2018-10-17 13:14
And updating Miniconda to 3.6.6 changes a lot:

NUITKA_CONSTRUCT=13870114 (nuitka dynamic AnaConda 3.6.6)
CPYTHON_CONSTRUCT=8761305 (AnaConda 3.6.6)

**Comment by kayhayen** [comment] 2018-10-17 13:15
So bad news right there, about Anaconda not being a solution really anymore.

**Comment by k-sok** [comment] 2018-10-17 13:33
Well. The fact that compiling as extension module solves the problem is actually good news for me. Just have tested that and it really works without a slowdown. Thank you very much!

**Comment by kayhayen** [comment] 2018-10-17 17:50
I will open another issue about the slow down that remains for this. I have made a speed up for compiled code and test it on factory. Not sure what to do with this issue. Static linking seems unnecessary, rather certain kinds of build options for CPython. I am terribly annoyed that `libpython.a` fails to be LTO friendly. 

I need to check how hard it is to build like MiniConda at user site. But due to the many compile time requirements for a fully working CPython, I am kind of sceptical it can ever be right to go into the business of making newbie Pythoneers build CPython on their own.

Ultimately I need to get rid of uncompiled standard library, it is a surface to slowness. A pre-compiled standard library would also fare better already.

**Comment by kayhayen** [comment] 2018-10-17 17:52
Oh and thanks for the report, this got me to the bottom on another issue that I had been looking at for many days already. Realizing that it's not at all about anything Nuitka does, well, kind of a big point in stopping to look at the wrong things.

**Comment by kayhayen** [comment] 2019-01-05 12:04
I think there is not a lot we can do about this, other than making static linking work and document it, the slow down of uncompiled code is otherwise unavoidable, and should be mentioned. I will close this, as soon as it is documented in the user manual how to achieve it.

**Closed** 2019-01-06 16:15 UTC
Labels: bug
