### ISSUE TITLE
Memory Leak when awaited async function in list comprehension 

### ISSUE THREAD

**Issue by sandra-93** [Nuitka/Nuitka#2336] opened 2023-07-16 18:26 UTC
I discovered a memory leak when awaiting an async function in the expression of a list comprehension.  

It works fine if the python script is executed directly but has a memory leak after compilation. 

Awaiting a function to provide a list seems not to be a problem.  

**I used:**

> python -m nuitka --version
1.4.1
Commercial: None
Python: 3.8.13 (default, Nov  2 2022, 16:11:39) 
Flavor: pyenv
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).

**Here is a short example:**  

_#Test 1_ 
```
async def funcTrace(): 
 return [await functionAsyncIO(i) for i in range(50)] 
```
 

_#Test 2_ 
```
async def funcTrace(): 
  lsTest = [] 
  for i in range(50): 
   lsTemp = await functionAsyncIO(i) 
   lsTest.append(lsTemp) 
  return lsTest 
```

```
async def functionAsyncIO(inVal: int) -> float: 
 returnVal = 30.5 * inVal 
 await asyncio.sleep(0.2) 
 return returnVal 


if __name__ == "__main__": 
 tracemalloc.start(15) 
 
 snap1 = tracemalloc.take_snapshot() 
 
 asyncio.run(funcTrace()) 
 
 snap2 = tracemalloc.take_snapshot() 
 
 stats = snap2.compare_to(old_snapshot=snap1, key_type="traceback") 
 print("Allocated memory size: ", stats[0].size / 1024, " KiB") 

 ```
 

**OutputTest 1: with list comprehension** 

 > python3 test_memory.py  

Allocated memory size:  _1.359375  KiB_ 

 

> python3 -m nuitka test_memory.py --output-dir=Test_nuitka/ --nofollow-imports --disable-cache=all --lto=no 

> ./Test_nuitka/test_memory.bin 

Allocated memory size:  **26.953125  KiB** 

 

**Output Test 2: without list comprehension** 

> python3 test_memory.py  

Allocated memory size:  _1.359375  KiB_ 

 

> python3 -m nuitka test_memory.py --output-dir=Test_nuitka/ --nofollow-imports --disable-cache=all --lto=no 

> ./Test_nuitka/test_memory.bin 

Allocated memory size:  _2.296875  KiB_ 

 

With the compilation there is around 24 KiB more memory allocated with list comprehension than without or directly executed as python script.  

Seems like there is a memory leak problem in the compiled version? 

EDIT:
I tested it again with the newest version of Nuitka, installed with: pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"

With another system, version of python and another compiler:

    python -m nuitka --version

1.8rc5
Commercial: None
Python: 3.9.7 (default, Sep 26 2021, 14:50:12) 
Flavor: Homebrew Python
Executable: /Users/sandra/TestNuitka/env/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).

and the memory leak is still there, with the compiled version.

#Test 1:
./Test_nuitka/test_memory.bin
Allocated memory size: 26.953125 KiB

#Test 2:
./Test_nuitka/test_memory.bin
Allocated memory size: 2.296875 KiB

**Comment by kayhayen** [comment] 2023-07-17 05:20
We have reference count tests for these things, I wil check out if they cover what you put there. I don't think `tracemalloc`  is working necessarily with Nuitka allocated objects all that well, but I am also not sure of that now. This difference however is striking, so this needs to be looked into.

**Comment by kayhayen** [comment] 2023-07-17 09:33
Not using most recent Nuitka makes this very much invalid as a report.

**Comment by sandra-93** [comment] 2023-07-17 10:29
> Not using most recent Nuitka makes this very much invalid as a report.

From which version on is this problem fixed?

**Comment by kayhayen** [comment] 2023-07-17 10:32
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing.

**Comment by sandra-93** [comment] 2023-07-17 11:23
> In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing.

I added the output of _python -m nuitka --version_
Can you now reproduce or reopen the issue?

here again the output:
1.4.1
Commercial: None
Python: 3.8.13 (default, Nov 2 2022, 16:11:39)
Flavor: pyenv
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).

**Comment by sandra-93** [comment] 2023-07-17 18:04
OK. So I tested it again with the newest version of Nuitka, installed with: `pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"`

With another system, version of python and another compiler:
> python -m nuitka --version
```
1.8rc5
Commercial: None
Python: 3.9.7 (default, Sep 26 2021, 14:50:12) 
Flavor: Homebrew Python
Executable: /Users/sandra/TestNuitka/env/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).
```

and the memory leak is still there, with the compiled version.

# Test 1:
./Test_nuitka/test_memory.bin
Allocated memory size:  **26.953125  KiB**

#Test 2:
./Test_nuitka/test_memory.bin                                                                             
Allocated memory size:  2.296875  KiB

Should I make some more tests? Maybe with another library then tracemalloc?

**Comment by kayhayen** [comment] 2023-07-18 06:38
I can confirm, the issue is real. When looking at them, I noticed that actually there is a reference loss for the value sent in, or so it appears.

Your two functions are not actually equivalent, I think the contraction does an `async for` which would explain the difference. It does an await and anext on the iterated and iterator maybe that does bad things (and it is even right to do it, the contract is not async for itself), and I found out when I ran them with this:

```
def run_async(coro):
    """Execute a coroutine until it's done."""

    values = []
    result = None
    while True:
        try:
            values.append(coro.send(None))
        except StopIteration as ex:
            result = ex.args[0] if ex.args else None
            break
    return values, result
```

I made it send non-None after the first iteration, and then i lost references to that, so that's actually a corruption bug if True. Not sending `None` is rare of course, but it hides things in my reference count tests potentially. But what I can tell for sure is that the coroutines do not get freed, for your contraction example. With `--experimental=report-refcounts` I can see that

```
active | allocated | released
Compiled Coroutines: 20 | 20 | 0
```

The 20 is the default attempt for my reference tests to try and run the test,  before it gives up. So what I am looking now is this:

```
@types.coroutine
def awaitable(*, throw=False):
    if throw:
        yield ("throw",)
    else:
        yield ("result",)

    return 277777

async def funcTrace1():
    return [await awaitable() for _i in range(150)]


def simpleFunction6():
    run_async(funcTrace1())
```

I would appear, that `funcTrace1` is not getting released.

It also may have to do with there being an extra frame in the contraction.  Python has it, and maybe it's value is arguable, but to be compatible it is there:

```
  File "/home/hayen/repos/Py2C/tests/basics/ReferencingTest36.py", line 48, in funcTrace1
    return [await awaitable() for _i in range(150)]
  File "/home/hayen/repos/Py2C/tests/basics/ReferencingTest36.py", line 48, in <listcomp>
    return [await awaitable() for _i in range(150)]
  File "/home/hayen/repos/Py2C/tests/basics/ReferencingTest36.py", line 43, in awaitable
    raise x
```

Maybe these two coroutine frames conflict with one another, and then end up not being released, that is also an option.

**Comment by kayhayen** [comment] 2023-07-18 06:47
I was wrong about the contraction doing async iteration, it does not do it, that cannot be it. This is not an async contaction, so it should be indeed closer to what you spelled out in the other function.

The frame inside the contraction however, is a `StatementsFrameFunction` which is not what I expected though. I was expecting a `StatementsFrameCoroutine` as on the outside as well.

**Comment by kayhayen** [comment] 2023-07-18 06:56
Yes, removing that frame from the coroutine, makes it no longer leak the coroutine.

Now, of course I need to figure out what's going on there, but I feel like that for these inline contactions, the frame handling overhead just to get the tracebacks duplicate the line as well, are totally not worth the effect, with them needed their own code object, and stack trace entry, that should be relegated to `--full-compat` which we use to compare stack traces from in CPython test suites, and where not being identical is painful.

I am pretty sure that for contractions in a coroutine, this was just wrong. Maybe we can even remove the await and still see it, but I think the context switch from the awaiting might be used a frame variant not prepared for it, and that's what's causing it.

**Comment by kayhayen** [comment] 2023-07-18 07:49
What's a  bit annoying, is that now every coroutine test is leaking one reference, which is something that was previously hidden by `.send()` loosing a reference, so my tests all fail due to that. Need to find out where that happens. Since it's independent of the number of iterations, it appears to be related to `.send()` as well. I already made sure, the return value is not it, but what can it be. Me being wrong on it loosing is definitely eradicated, so still need to hunt some more.

**Comment by kayhayen** [comment] 2023-07-18 08:52
So, the initial `send` uses coroutine code that will ignore `yield_return_value` when starting, and assume a reference after. That explains the off by one, which is coming from calling `send` with `Py_None`. It probably also explains, why this was overlooked before, only the second send makes a difference.

But with that solves, other issues are still poping up, the asyncgen code is also having similar issues, but it seems the coroutines are now fine at least.

**Comment by kayhayen** [comment] 2023-07-19 06:58
As a side note, I think tracemalloc compatibility of Nuitka is not fully there, so it may give you too low numbers, at least on newest Pythons potentially, but never too high numbers, and 3.8 should be still OK.

**Comment by kayhayen** [comment] 2023-07-19 07:04
So, asyncgen found a couple of issues as well, and now I am seeing that `yield from` with a generator behind that leaks the value sent into it. Now that is of course typically `None`, but there appears to be either some form of inconsistency with how coroutines and asyncgen do it, or that's a shared bug only visible in that way. I think `await` is mostly just the same as a `yield from`, so this is curious.

It's amazing to me how many bugs have covered each other up. My approach of checking reference counts is very susceptible to 2 bugs of inverse kind hiding each other. Like when the sent in value is leaking a reference, and something else looses a reference, this can remain hidden. In that way, tracemalloc can uncover bugs better. In this instance however, the example you can also had a reference count issue, but it just wasn't covered yet. But it's something to keep in mind, that actually long running of intense programs would need to be monitored for compared memory usage growth. What I typically don't like is that these will not point me to what's the cause.

Therefore, let me commend you on achieving to break this down for me to that contraction code. That said, I know it will be a bit more until I figure out why passing down the sent value is leaking references now, but it seems this is like a killer issue to find, and the test coverage was just below where I had to find many different bugs all at once.

**Comment by kayhayen** [comment] 2023-07-19 07:26
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by sandra-93** [comment] 2023-07-19 11:53
Thanks for the search and bugfix.

I tried the version of your factory branch which solves the problem :) 
Both test cases have now about the same memory allocation.
Can you tell which future version will probably include this bugfix?

I installed:
> pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"

I tried it with the following versions, system:
> python -m nuitka --version
1.8rc5
Commercial: None
Python: 3.8.13 (default, Jul 19 2023, 12:11:21) 
Flavor: pyenv
Executable: /home/sandra/Software/TestNuitka/.venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.2
Version C compiler: /usr/bin/gcc (gcc).

**Comment by kayhayen** [comment] 2023-07-20 07:17
I am aiming at the next hotfix, but since I am busy with tax filings for at least today, I may also decide to skip it, or only include the frame stuff, that is the root cause of what you see, it's not decided at all yet. I would like to get the nested generator yield from issue that is now remaining sorted out first. Since that's kind of a known issue with factory, my release process usually starts the hotfix only, when I can split my factory work to the hotfix and the develop branches in their entirety. 

Anyway, I will keep you posted. Hunting these issues is usally very involved.

**Comment by kayhayen** [comment] 2023-07-20 07:33
My CI found that this will be incompatible right now:

```
class T(object):
    def __init__(self, ident):
        self.ident = ident

    def __del__(self):
        print("T.__del__ %s" % self.ident)


def simpleFunction54():
    g = (x for x in range(9))
    next(g)

    try:
        g.send(T(9))
    except TypeError as _e:
        pass

simpleFunction54()
```

So, it's not even about nested generators at all, it's about everything that uses the `send` method of a generator. Somehow my fixes for ` coroutine` and `asyncgen` appear do not equally apply to generator expressions here. And I just checked, since we had this before, a generator function is equally leaking the reference to the sent object.

And since my refcount test gives a `-1`  for this, and a `+1`, probably something else is being released that better ought not to release.

**Comment by kayhayen** [comment] 2023-07-20 07:33
I would say, current state there is a total mess right now still, with something really bad going on.

**Comment by kayhayen** [comment] 2023-07-20 07:37
When I run the test right now, it's +1 though, maybe this was an intermediate state, so it's maybe not that terrible at all right now.

**Comment by kayhayen** [comment] 2023-07-20 08:46
I wish I was more disciplined and did my taxes, but instead I debugged that +1 down to where it happens. Part of the problem was that for normal generators, a part of the fix was done in tracing code, and that is why there was that, and so factory had that, since the tracing code remained in a git stash. The nested generator problem however was still real, and it affected generators, coroutines and asyncgen that were passing a sent in value down, but failed to release the reference, since in that code path, the send in value is not passed with a reference, these interfaces do not even allow for that.

But I think I just ran all my refcount tests with 3.9 and it just went fine, it's on factory now, but I will have to let the overall CI across versions be the judge of how good it is. I feel I also want to add behaviour tests using this `T` class for objects that are expected to be released, so as to cover the bases a little bit better there. Maybe my `run_async` etc. can be changed to fail the test if they do not all release. I used them very successfully to identify which objects had issues. Previously I was able to enable a "explain" mode, but for some reason, this is not working anymore. I know it never worked well to compare object snapshots, but not working at all was strange.

Anyway, this might come to a very happy end soon enough. With the amount of fixes this has though, I am baffled that the reference count tests ever passed. I mean, I saw bugs hiding each other before, but never in that dimension.

**Comment by kayhayen** [comment] 2023-07-20 09:53
Ok, so CI found another issue, with what I call "quick iteration" that has an optimization for generators, it was also loosing references now, crashing as a result with `None`  being deallocated. Kind of scary, I think I will want all of CI to settle before making that hotfix for sure.

**Comment by kayhayen** [comment] 2023-07-20 11:27
As for the frame, I have now decided that I do not want to maintain the extra frame even in full compatibility mode. I have had CI failing due to it still being done, and I must say, I hate to have a big behaviour difference there, and then generator frames are not designed to be nested with their own type in a function. That's of course going to be limiting for inlining them one day, but honestly, I don't care yet, and the argument is that the diff from normal to full compat should never be big. 

Getting rid of these code objects and frames will also help scalability, so I am doing that. Obviously I have to expect that the CPython test suite parts that deal with exception tracebacks and check them for length, or something like 3 levels up, are going to be failing now. I will however survive that somehow I bet better than having tests fail only in one of the modes.

**Comment by kayhayen** [comment] 2023-07-20 13:33
So, not a lot that has happened in the code when the crash happens.

```
MOD_INIT_DECL(AssertsTest) {
    if (_Py_PackageContext != NULL) {
        module_full_name = _Py_PackageContext;
    }

    mdef_AssertsTest.m_name = module_full_name;
    PyObject *module = PyModule_Create(&mdef_AssertsTest);
    CHECK_OBJECT(module);

    bool res = Nuitka_SetModuleString(module_full_name, module);
    assert(res != false);

```

I removed Python2 code from there, but basically an empty module object is created through official API, and then a private function of Nuitka tries to set that module in `sys.modules` and crashes.

This is implemented like this:

```
// Add a module to the modules dictionary from name C string
NUITKA_MAY_BE_UNUSED static bool Nuitka_SetModuleString(char const *module_name, PyObject *module) {
    PyObject *module_name_object = Nuitka_String_FromString(module_name);
    bool result = Nuitka_SetModule(module_name_object, module);
    Py_DECREF(module_name_object);

    return result;
}
```

Where `Nuitka_String_FromString` is just standard `PyUnicode_FromString` 

And then

```
return DICT_SET_ITEM(Nuitka_GetSysModules(), module_name, module);
```

crashing during `Nuitka_GetSysModules` which is this:

```
// Replacement for "PyImport_GetModuleDict"
NUITKA_MAY_BE_UNUSED static PyObject *Nuitka_GetSysModules(void) {
#if PYTHON_VERSION < 0x390
    return PyThreadState_GET()->interp->modules;
#else
    return _PyInterpreterState_GET()->modules;
#endif
}
```

I didn't immediately find where `PyThreadState_GET->interp->modules`  could go wrong, might be worth separating this into 2 lines, so the segfault becomes more clear.

**Comment by kayhayen** [comment] 2023-07-20 13:42
So, `PyThreadState_GET()->interp` is already segfaulting. I wonder how that can be. The structure is very small and definitely not dependent on sizes:

```
typedef struct _ts {
    /* See Python/ceval.c for comments explaining most fields */

    struct _ts *prev;
    struct _ts *next;
    PyInterpreterState *interp;

```

Maybe I need to look at the diff with this in mind again, this is crazy. We are of course using a shortcut to access the thread state, that normally works, I wonder if it can fail to work somehow.

**Comment by kayhayen** [comment] 2023-07-20 14:07
Ok, with that changed to the official API, `DROP_ERROR_OCCURRED()` crashes, which of course also goes through the shortcut for accessing thread state.

I need to figure out, if that `pyruntimestate` is changing the offset of `_PyRuntime.gilstate.tstate_current` because that would explain it, even if I do not immediately see it.

And I think, I found it:

```
struct gc_generation {
    PyGC_Head head;
    int threshold; /* collection threshold */
    int count; /* count of allocations or collections of younger
                  generations */
};

```

So, the offset of the values in PyRuntime are version dependent, which is fair enough, and Nuitka to blame for not using the API when it really should. Of course, for performance reasons, I would really like to keep on doing that. So, I think I will use some offsetof() magic, and a runtime check on the hosting Python version, if this should happen a lot, but it will also require our uses to be abstracted.

For now, we get away with defining `PyThreadState_GET` to `PyThreadState_Get` for the problematic version here.

We will need to monitor other major versions of Python as well. Hopefully this didn't happen a lot, but it could be.

**Comment by kayhayen** [comment] 2023-07-21 07:18
It seems I made a bunch of comments here, that in the wrong issue, going to move them over.

**Comment by kayhayen** [comment] 2023-07-24 07:03
This is part of the hotfix release 1.7.6 that I just made.

**Closed by kayhayen** 2023-07-24 07:03 UTC
Labels: bug, factory
