### ISSUE TITLE
Corrupt object files from clcache are not detected

### ISSUE THREAD

**Issue by alan0526** [Nuitka/Nuitka#1873] opened 2022-11-08 01:35 UTC
**version**
python: 3.9
nuitka: 1.1.8
reportlab: 3.6.12
svglib: 1.4.1
flask: 2.2.2

**command**
"C:\program files\python39\python" -m nuitka --follow-imports --follow-import-to=flask --enable-plugin=numpy iq_tool.py --standalone --show-scons --include-plugin-files="C:\Program Files\Python39\Lib\site-packages\reportlab\fonts\*"

**script**
from svglib.svglib import svg2rlg
from reportlab.graphics import renderPDF, renderPM
...
drawing = svg2rlg(self._output)
renderPDF.drawToFile(drawing, pdf_path)
renderPM.drawToFile(drawing, png_path, fmt="PNG", dpi=png_dpi)

**error messages:**
Unexpected output from this command:
link @C:\Users\lusteryu\AppData\Local\Temp\tmp7as48tyf.lnk
module.reportlab.pdfbase._fontdata_widths_helveticabold.obj : fatal error LNK1136: invalid or corrupt filescons: *** [F:\work\git_atg\iq_tool\iq_tool\iq_tool.dist\iq_tool.exe] Error 1136
scons: internal stack trace:
  File "C:\PROGRA~1\python39\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Job.py", line 262, in run
    task.execute()
  File "C:\PROGRA~1\python39\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Script\Main.py", line 193, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "C:\PROGRA~1\python39\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Taskmaster.py", line 235, in execute
    self.targets[0].build()
  File "C:\PROGRA~1\python39\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Node\__init__.py", line 755, in build
    self.get_executor()(self, **kw)
  File "C:\PROGRA~1\python39\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Executor.py", line 384, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\PROGRA~1\python39\lib\SITE-P~1\nuitka\build\INLINE~1\lib\scons-4.3.0\SCons\Executor.py", line 120, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed
scons: building terminated because of errors.

the module.reportlab.pdfbase._fontdata_widths_helveticabold.obj is empty from the cl command, but the module.reportlab.pdfbase._fontdata_widths_helveticabold.cpp is not emty, I don't know what's wrong with this file?

**source file generated by nuitka**
[module.reportlab.pdfbase._fontdata_widths_helveticabold.cpp.zip](https://github.com/Nuitka/Nuitka/files/9956831/module.reportlab.pdfbase._fontdata_widths_helveticabold.cpp.zip)

**Comment by kayhayen** [comment] 2022-11-08 06:54
Maybe some sort of clcache mishap. You can disable it temporarily by using `--disable-ccache` and then maybe it works?

**Comment by alan0526** [comment] 2022-11-08 07:53
OK, thanks, I am going to check it.

**Comment by alan0526** [comment] 2022-11-08 08:20
It works now, thank you very much. @kayhayen 
How can I figure out what's wrong with the clcache module?

**Comment by kayhayen** [comment] 2022-11-08 08:50
I don't think you can, in the app folder, there is a cache directory of Nuitka, one that is named `clcache`. I am going to add feature that will allow to disable or force refesh or the various caches now, so I could tell you to use `--clear-cache=clcache` now, but this may not happen immediately.

Also I think `corrupt file` is something we can attempt to parse out of the error, and exit more constructively pointing to this kind of option.

**Comment by kayhayen** [comment] 2022-11-08 08:52
I am going to use this to trace the implementation of said enhancement, however I guess you can otherwise ignore this issue, it's not going to reproducible I bet. Probably a CTRL-C at the wrong time, a crash or memory issue or cl.exe that left this behind. I may never know, but this appears to be rare.

**Comment by alan0526** [comment] 2022-11-08 08:57
OK, thanks, I just use --clear-cache=clcache flag now.

**Comment by kayhayen** [comment] 2022-11-10 11:18
This is on factory now, but since your issue is basically resolved, by adding a trace that we won't see again unless the situation repeats, lets close this now and not trace the path to release.

**Closed by kayhayen** 2022-11-10 11:18 UTC
Labels: enhancement
