### ISSUE TITLE
Issue with concurrent.futures.ProcessPoolExecutor on OSX

### ISSUE THREAD

**Issue by kotyache** [Nuitka/Nuitka#950] opened 2021-01-25 12:53 UTC
I'm using Python 3.8.5 and Nuitka 0.6.11 (installed with pip in Conda) on OSX Catalina 10.15.4 (19E287)

Trying to compile a script with ProcessPoolExecutor, but Nuitka produced executable fails to run with error "test.dist/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak."

I tried different scripts that use ProcessPoolExecutor but ran into the same error -- the simplest example of what I tried is below. I also did try to include freeze_support() right after if __name__ == '__main__': but was getting the same error

```python
import concurrent.futures
from time import sleep
 
def sleep_func(msg):
    sleep(1)
    print(msg)

if __name__ == '__main__':
    with concurrent.futures.ProcessPoolExecutor() as executor:
        msgArr = ["one", "two", "three"]
        executor.map(sleep_func, msgArr)
```
Nuitka's output 
$ python -m nuitka --follow-imports --standalone test.py
Nuitka-Options:INFO: Recursing all is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang (clang).
Nuitka-Scons:WARNING: You are not using ccache.
Nuitka:INFO: Keeping build directory 'test.build'.
Nuitka:INFO: Successfully created 'test.dist/test'.
$ 'test.dist/test'
/Users/kotyache/Desktop/nuitka_test_async/test.dist/multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.

Also tried running Nuitka in different setups --
Python 3.8, virtualenv, OSX Catalina, Nuitka 0.6.11
Python 3.9, conda, OSX Catalina, Nuitka 0.6.11
Python 3.8, conda, OSX High Sierra, Nuitka 0.6.11
Each time test.dist/test produced the same error I mentioned

**Comment by kayhayen** [comment] 2023-06-20 19:13
The `freeze_support` does nothing with Nuitka. The issue is still reproducible unfortunately, and it's before the process exit.

**Comment by kayhayen** [comment] 2023-06-20 21:32
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-06-25 13:57
This is part of the 1.6.5 hotfix release just made.

**Closed by kayhayen** 2023-06-25 13:57 UTC
Labels: bug, factory
