### ISSUE TITLE
Remove appimage support (was Add option to disable appimagelauncher or patch embedded .desktop file)

### ISSUE THREAD

**Issue by bearsh** [Nuitka/Nuitka#1130] opened 2021-06-18 10:05 UTC
[AppImageLauncher](https://github.com/TheAssassin/AppImageLauncher) is a nice thing for gui tools but not so nice for cli apps.
As nuitka uses AppImage for `--onefile ` it would be nice to have a option to disable AppImageLauncher.

According to https://github.com/TheAssassin/AppImageLauncher/issues/338 this can be done with an entry in the embedded .desktop file:
`X-AppImage-Integrate=false`

An option for nuitka to either set this value or a more generic one to patch/provide the .desktop file would be nice.

**Comment by kayhayen** [comment] 2021-06-19 07:19
Good find, thank you, this shall be added indeed.

**Comment by kayhayen** [comment] 2021-11-11 20:24
Unfortunately didn't make it in time. Part of my problem is that I don't know AppImageLauncher. So are we having a situation here, where you basically want to say it's a console program?

Note: If you don't like appimage, and very well you may not, you can use --onefile-tempdir and it will use the bootloader used on everything but Linux.

**Comment by kayhayen** [comment] 2021-11-12 15:34
It's secret, I only tell the best users about it @bearsh 

The issue is that the compression is better for Python before 3.5 with one, and not for the other. Too complicated to document, so this is sitting around until `zstd` compression is supported through a slave Python installation of some sorts. And I cannot decide how I want to manage these slave Pythons. I was thinking of having a Nuitka-Python installed for you, for which we know it can do these things. Sort of frontend/backend split of Nuitka, where only a part of it runs with say 2.7 or 3.7 or whatever your Python install is and the rest with Nuitka-Python 3.9 or whatever the latest version with all dependencies might be.

Grand plans prevent the good things sometimes. :)

**Comment by kayhayen** [comment] 2022-02-20 16:35
With `--onefile-tempdir` it is already disabled, and with caching for `--onefile` unpacking added, the `AppImage` usage becomes dubious, and this time I have reports of the Nuitka bootstrap being faster to run a binary. With caching, it will be invincible for repeated runs.

**Comment by kayhayen** [comment] 2022-06-22 07:12
The appimage usage is probably going to be removed for 1.0 entirely, once cached onefile becomes workable, it's just too limited in its application compared to the bootstrap.

**Comment by kayhayen** [comment] 2022-08-04 16:53
With 1.0 this was in fact removed, the Linux bootstrap has some actual problems, so update to 1.0 is strongly advised.

**Closed by kayhayen** 2022-08-04 16:53 UTC
Labels: enhancement
