### ISSUE TITLE
PySide6 QChart TypeError: EnumMeta.__call__() missing 1 required positional argument: 'value'

### ISSUE THREAD

**Issue by DrakeGladiator** [Nuitka/Nuitka#2111] opened 2023-03-14 21:46 UTC
Hello (Its my first issue post on Github, I tried to follow the guidelines, feedback will be appreciated.)

**Description:**
I use dynamic spline charts in a PySide6 GUI and could successfully compile my project with both Nuitka 1.5 and 1.6 RC2. (The GUI works flawlessly in Interpreter mode.)
However, when I try I run the .exe I always get this error message:
```
"QChart TypeError: EnumMeta.__call__() missing 1 required positional argument: 'value'"
```

**Reproduction:**
I tried the MSVC and MinGW64 compiler, with different compile settings but I always get the same error. So I went back just using the example provided on the PySide page: https://doc.qt.io/qtforpython/examples/example_charts__dynamicspline.html

```python    
import sys, random
from PySide6.QtCharts import QChart, QChartView, QSplineSeries, QValueAxis
from PySide6.QtCore import Qt, QTimer, Slot
from PySide6.QtGui import QPainter, QPen
from PySide6.QtWidgets import QApplication, QMainWindow

class Chart(QChart):
    def __init__(self, parent=None):
        super().__init__(QChart.ChartTypeCartesian, parent, Qt.WindowFlags())
        self._timer = QTimer()
        self._series = QSplineSeries(self)
        self._titles = []
        self._axisX = QValueAxis()
        self._axisY = QValueAxis()
        self._step = 0
        self._x = 5
        self._y = 1

        self._timer.timeout.connect(self.handleTimeout)
        self._timer.setInterval(1000)

        green = QPen(Qt.red)
        green.setWidth(3)
        self._series.setPen(green)
        self._series.append(self._x, self._y)

        self.addSeries(self._series)
        self.addAxis(self._axisX, Qt.AlignBottom)
        self.addAxis(self._axisY, Qt.AlignLeft)

        self._series.attachAxis(self._axisX)
        self._series.attachAxis(self._axisY)
        self._axisX.setTickCount(5)
        self._axisX.setRange(0, 10)
        self._axisY.setRange(-5, 10)

        self._timer.start()

    @Slot()
    def handleTimeout(self):
        x = self.plotArea().width() / self._axisX.tickCount()
        y = (self._axisX.max() - self._axisX.min()) / self._axisX.tickCount()
        self._x += y
        self._y = random.uniform(0, 5) - 2.5
        self._series.append(self._x, self._y)
        self.scroll(x, 0)
        if self._x == 100:
            self._timer.stop()

if __name__ == "__main__":

    a = QApplication(sys.argv)
    window = QMainWindow()
    chart = Chart()
    chart.setTitle("Dynamic spline chart")
    chart.legend().hide()
    chart.setAnimationOptions(QChart.AllAnimations)
    chart_view = QChartView(chart)
    chart_view.setRenderHint(QPainter.Antialiasing)
    window.setCentralWidget(chart_view)
    window.resize(400, 300)
    window.show()

    sys.exit(a.exec())

```

Using the same command as for the project, I can reproduce 1:1 the issue on the provided example:
nuitka --standalone --enable-plugin=pyside6 --nofollow-import-to=tkinter --msvc=latest main.py

The error message origins from super().__init__(QChart.ChartTypeCartesian, parent, Qt.WindowFlags()) that is called in the __init__() of the chart.

**nuitka --version:**
Python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\DrakeGladiator\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe (cl 14.3).

(actual) OS: Win 11 Pro 22H2, Build 22622.586
IDE: Visual Studio Code 1.76.1
I installed python with .exe Installer from python.org and Nuitka with pip install nuitka command, no virtualenv is used as it is the only project on Python 3.10, others are on 3.11.

**pip freeze:**
minimalmodbus==2.0.1
Nuitka==1.5
numpy==1.24.2
ordered-set==4.1.0
pandas==1.5.3
pdfrw==0.4
Pillow==9.4.0
pymodbus==3.2.0
pypdf==3.5.2
pyserial==3.5
PySide6==6.4.2
PySide6-Addons==6.4.2
PySide6-Essentials==6.4.2
python-dateutil==2.8.2
pytz==2022.7.1
reportlab==3.6.12
shiboken6==6.4.2
six==1.16.0
zstandard==0.20.0

**Comment by kayhayen** [comment] 2023-03-15 07:48
I wonder why people for Python level exceptions try different C compilers. Not a complaint. This report is very good. I will try and look into it, this is a new one for sure.

**Comment by kayhayen** [comment] 2023-03-15 08:00
This is not a regression, 1.5.8 and my current factory version both reproduce it. Seems something about either `super` or the metaclass of Qt there is handled wrong. Thanks for your report, this seems interesting, and also suprising, given how much code does not show this issue so far. Lets see what it turns out to be.

**Comment by DrakeGladiator** [comment] 2023-03-15 16:33
Thank you for the feedback! Would be really nice if this could be fixed.

Regarding the compiler: I was just curious how both perform and tought it helps to point out that the issue is certainly compiler independent. In the beginning it was not clear to me where the issue origins from. (:

**Comment by kayhayen** [comment] 2023-03-15 18:32
@DrakeGladiator yes, I agree, like in this story where a guy is looking for his keys under a lamp in the middle of the night, and when asked why he is looking there, he answers that is because he can search there, but not in the dark. Too much darkness in Nuitka there, in case it doesn't behave. That is input to the unexpected exception handler that I want to add at some point, to tell what the options are.

In this case, I need to look at it, and find out what on earth goes wrong. This is rare stuff, but Python level exceptions barely ever change at all, independent of OS, etc. unless they are packaging issues, and really never change due to C compiler. There have been segfaults that go away when switching compiler. Just wondering how to make options more clear. Maybe also a thing for the issue template.

**Comment by DrakeGladiator** [comment] 2023-03-15 20:15
Haha. As it is my first experience with compiling Python scripts I think the explanations are good enough and quite straightforward.

Nuitka actually helped me already to better understand why things are not working. So I could manage to create a .exe with pyinstaller in the meantime. But it lacks the --onefile option, as it is currently not supported with PySide6.

So having a solution for this issue is still of high interest.

**Comment by kayhayen** [comment] 2023-06-01 07:58
So, I reproduced this one recently, and I found that the code of PySide6 is looking `enum` up, probably to make this call. I added it as an implicit dependency, but naturally, that's not changing things, it was probably used due to something else already. I didn't look deeply enough into PySide6 code, to recognize what's wrong there, but I suspect, it's somehow making a call of what it things of as a Python function improperly, when it's a compiled function, something like that. I might have a workaround for that eventually.

**Comment by kayhayen** [comment] 2023-11-11 12:30
So I reduced this to the following code

```
from PySide6.QtCharts import QChart
from PySide6.QtCore import Qt

class Chart(QChart):
    def __init__(self):
        QChart.__init__(self, QChart.ChartTypeCartesian, None, Qt.WindowFlags())

Chart()
```

So that is not using `super` or anything complex, just a derived class with a compiled constructor, that I think doesn't even get a chance to make a difference. I am very confused where the EnumMeta class is coming from. I wonder if it is somehow related to the `QChart.ChartTypeCartesian` and there is being an attempt to covert something by the bindings.

**Comment by kayhayen** [comment] 2023-11-11 12:34
Ok, reduced it even further, to only this line:

```
from PySide6.QtCharts import QChart
from PySide6.QtCore import Qt
QChart(QChart.ChartTypeCartesian, None, Qt.WindowFlags())
```

The call that would fail, gives an error. I think it's pretty obvious that the calling of this object somehow exhibits a bug in some form of the call optimization of Nuitka, it's probably mishandling something about this class coming from an extension module.

**Comment by kayhayen** [comment] 2023-11-11 13:08
So, further down to this:

```
from PySide6.QtCore import Qt
flags=Qt.WindowFlags()
```

Our method call with no args, ends up calling WindowFlags with no args, and it doesn't like it. Something special done by `Qt` that we do not handle in this case.

**Comment by kayhayen** [comment] 2023-11-11 13:15
With pure Python, and this code, the same error can be seen:

```
from PySide6.QtCore import Qt
flags=Qt.WindowFlags()

WindowFlags=Qt.WindowFlags
flags=WindowFlags()
```

Only when called as a method, WindowsFlags is functional, however to Nuitka it appears as if it's not a method, need to see why there is a difference.

**Comment by kayhayen** [comment] 2023-11-12 08:58
So, this is what's going on, in PySide6 at least, there is code like this:

```
                auto *flagType = PyDict_GetItem(type_base->tp_dict, rename);
                if (currentOpcode_Is_CallMethNoArgs())
                    return replaceNoArgWithZero(flagType);
```

To no surprise of anybody, Nuitka doesn't have the bytecode for PySide6 to look at and therefore it fails when compiled. I am not sure why it's necessary to see if there is an argument from the bytecode for that code, but apparently that's what is going on. The plugin could patch the source code at compile time, if it knew the relevant enums, there appear to be quite a few.

**Comment by kayhayen** [comment] 2023-11-14 11:03
Actually I applied a workaround, that will be part of 1.9 that hacks the EnumMeta class to work for PySide6 without the value argument, which makes this work.

```
- module-name: 'enum'
  anti-bloat:
    - replacements_plain:
        'def __call__(cls, value,': 'def __call__(cls, value=None,'
        'return cls.__new__(cls, value)': 'return cls.__new__(cls, value if value is not None or cls.__module__ != "PySide6.QtCore" else 0)'
      when: 'plugin("pyside6")'
```

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Closed** 2023-11-23 08:26 UTC
Labels: bug, factory, excellent_report
