### ISSUE TITLE
Improving --plugin-list syntax

### ISSUE THREAD

**Issue by dark-penguin** [Nuitka/Nuitka#301] opened 2019-03-18 11:05 UTC
If you want to list available plugins, `nuitka --plugin-list` is not enough - you must run `nuitka --plugin-list anything`, otherwise it complains about the absence of a positional argument. Strictly speaking, this is in accordance with the documentation, but it really should not be necessary to provide a module name to list available plugins. :)

Also, I can never remember that the option is `--plugin-list` and not `--list-plugins` or `--plugins-list`, which would have been much more obvious. Maybe add that as an alternative syntax? Maybe even both of those, just for extra convenience?

**Comment by dark-penguin** [comment] 2019-03-19 01:49
Actually, besides `--plugin-list`, it would be very convenient to have a way to list a plugin's options. And document that plugins have options, which can be passed with a pretty non-obvious syntax.

**Comment by kayhayen** [comment] 2019-03-19 10:46
@dark-penguin I was thinking to use the opportunity to add something to that very output, and an automatic information that options are available when using the default.

**Comment by kayhayen** [comment] 2019-03-21 20:49
I fixed this on my factory branch, soon to become part of develop.

**Comment by kayhayen** [comment] 2019-04-04 08:37
I am closing this, as the issue is fixed with the release of 0.6.3, and we have to work out how to give help about plugins separately. I agree that plugins taking options need to work better.

**Closed by kayhayen** 2019-04-04 08:37 UTC
Labels: bug
