### ISSUE TITLE
Problem with setuptools on Python3.12 not finding distutils (was: Self-updating with tufup.client)

### ISSUE THREAD

**Issue by vincent-lg** [Nuitka/Nuitka#3110] opened 2024-09-06 14:28 UTC
### Summary

Upon building a simple script that uses `tufup.client`, I get an error with the use of `distutils` (module not found).

### Nuitka version

```
2.4.8
Commercial: None
Python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\...\pyenv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\DOWNLO~1\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

### Nuitka installation

Nuitka has been installed in a virtual environment on Windows 11 in Python 12 with poetry (`poetry add nuitka --dev`).

pip is version 24.0. The following package has been installed:

```
Package            Version   Location                                           Installer
------------------ --------- -------------------------------------------------- ------------
tuf                4.0.0     C:\Users\...\pyenv\Lib\site-packages Poetry 1.8.2
tufup              0.9.0     C:\Users\...\pyenv\Lib\site-packages Poetry 1.8.2
```

nuitka does work and did work for this project until `tufup` was tested. I've isolated this issue in a very small script (see below).

### To reproduce

1.  Write a very small script:
    
    ```python
    # hello.py
    from tufup.client import Client
    ```

2.  Build it using `python -m nuitka --standalone hello.py`.
3.  Go into the dist folder (`cd hello.dist`) and run it (`hello.exe`).

### Output

```
(pyenv) C:\Users\...\hello.dist>hello.exe
Traceback (most recent call last):
  File "C:\Users\...\HELLO~1.DIS\hello.py", line 1, in <module>
  File "C:\Users\...\HELLO~1.DIS\tufup\__init__.py", line 4, in <module tufup>
  File "C:\Users\...\HELLO~1.DIS\tufup\repo\__init__.py", line 10, in <module tufup.repo>
  File "C:\Users\...\HELLO~1.DIS\setuptools\__init__.py", line 24, in <module>
  File "C:\Users\...\HELLO~1.DIS\setuptools\logging.py", line 5, in <module>
  File "C:\Users\...\HELLO~1.DIS\setuptools\monkey.py", line 13, in <module>
ModuleNotFoundError: No module named 'distutils'
```

### Problem

I'm not 100% sure this is a problem with Nuitka itself. `distutils` has been deprecated, though it can still be installed as a third-party program. I would guess that Nuitka does not bundle `distutils` because it usually conflicts with its build process. But that's just a guess.

At this point, I would like to know if there's a solution to using `tufup` or if I should consider alternatives. Not that I found many.

Thank you for your answer,

**Comment by kayhayen** [comment] 2024-10-13 10:46
This is having a hard time with bloat, and maybe, the issue you see is caused by attempted anti-bloat measures, where something is missing a guard to not remove distutils or so. I managed to reproduce it.

```
+- module-name: bsdiff4
+  anti-bloat:
+    - description: 'remove unittest reference'
+      change_function:
+        'test': 'un-callable'
+
+- module-name: tufup.repo
+  anti-bloat:
+    - description: 'need to use setuptools'
+      bloat-mode-overrides:
+        'unittest': 'allow'
```

With that config it's already nicer.

**Comment by kayhayen** [comment] 2024-10-13 10:53
It seems, setuptools for 3.12, smuggles distutils back in and uses it for itself and exposes it globally too, so it's being found, despite not being found at compile time. For this, we got yaml configuration as well, that would appear to be important to have.

**Comment by kayhayen** [comment] 2024-10-13 11:11
So, the _vendor directory, is newly exposed for setuptools >= 71, and we were not yet compatible with that, but that's added, however, distutils is hacked into things, based on its existence , and we probably need to special treat this, and allow forcing a finding of a specific module by an alias. We surely have something there somewhere that is similar.

**Comment by kayhayen** [comment] 2024-10-14 06:57
I have tried a few forms of smuggling this in. I do think, it will be best if setuptools does make these modules "hard", i.e. they become pre-installed for the module location process, and then the whole module location process is avoided. This ought to be done for Python3.12 only of course, and only if setuptools is used, which should be rare, but sometimes is required, in fact for the tufp library there, I ignore listed it, and it's allowed to do that for simplicity, even though it's bloaty.

**Comment by kayhayen** [comment] 2024-10-29 12:42
It's pretty tough to smuggle in `distutils` from there, without duplicating it, I had so far not really succeeded and I don't know how to make this in a compatible fashion really. It has been seen in other context, where anti-bloat is outdated or not applied as well, so this is really more blocking for other things, than I would like it to be, I need an idea here.

**Comment by kayhayen** [comment] 2024-10-29 20:28
So, I did a lot of anti-bloat engine changes to setuptools in case of 3.12, that should do the trick, but it's ugly as hell of course.

**Comment by kayhayen** [comment] 2024-10-29 20:28
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-11-01 10:13
This is now part of the current pre-release and will be part of 2.5 release.

**Comment by kayhayen** [comment] 2024-11-16 12:47
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:47 UTC
Labels: bug, develop, excellent_report
