### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.compat'

### ISSUE THREAD

**Issue by pavlutom** [Nuitka/Nuitka#1744] opened 2022-08-22 12:26 UTC
### Description
Compiled code with imported tensorflow_probability package throws `ModuleNotFoundError`. The code works as expected if ran directly without nuitka.

### Environment
```
1.0.5
Commercial: None
Python: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: <project_path>\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
The same issue also occured on RHEL.
```
1.0.5
Commercial: None
Python: 3.9.2 (default, Mar  2 2021, 21:18:39)
Flavor: Unknown
Executable: <project_path>/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Rhel (based on Fedora) 7.9
```

requirements.txt:
```
nuitka==1.0.5
orderedset==2.0.3
tensorflow==2.9.1
tensorflow_probability==0.17.0
numpy==1.21.2
```

### Example code
```python
import numpy as np
import tensorflow as tf
import tensorflow_probability as tfp


print(f"numpy: {np.__version__}")
print(f"tensorflow: {tf.__version__}")
print(f"tensorflow_probability: {tfp.__version__}")
```

### Compilation command
```
venv\Scripts\python.exe -m nuitka --standalone --enable-plugin=numpy --show-progress --show-scons --lto=no test.py
```

### Compiled program output
```
2022-08-22 13:55:07.684946: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-08-22 13:55:07.687204: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


Failed to import TensorFlow. Please note that TensorFlow is not installed by default when you install TensorFlow Probability. This is so that users can decide whether to install the GPU-enabled TensorFlow package. To use TensorFlow Probability, please install the most recent version of TensorFlow, by following instructions at https://tensorflow.org/install.


Traceback (most recent call last):
  File "C:\Work\random\NUMPY_~1\TEST~1.DIS\test.py", line 3, in <module>
  File "C:\Work\random\NUMPY_~1\TEST~1.DIS\tensorflow_probability\__init__.py", line 20, in <module tensorflow_probability>
  File "C:\Work\random\NUMPY_~1\TEST~1.DIS\tensorflow_probability\substrates\__init__.py", line 17, in <module tensorflow_probability.substrates>
  File "C:\Work\random\NUMPY_~1\TEST~1.DIS\tensorflow_probability\python\__init__.py", line 138, in <module tensorflow_probability.python>
  File "C:\Work\random\NUMPY_~1\TEST~1.DIS\tensorflow_probability\python\internal\lazy_loader.py", line 57, in __dir__
  File "C:\Work\random\NUMPY_~1\TEST~1.DIS\tensorflow_probability\python\internal\lazy_loader.py", line 37, in _load
  File "C:\Work\random\NUMPY_~1\TEST~1.DIS\tensorflow_probability\python\__init__.py", line 38, in _validate_tf_environment
ModuleNotFoundError: No module named 'tensorflow.compat'
```

### What I tried
+ enable/disable the deprecated tensorflow plugin
+ enable/disable the anti-bloat plugin
+ `--include-package-data=tensorflow`

Neither of that helped

**Comment by pavlutom** [comment] 2022-08-22 12:54
BTW without the `tensorflow_probability` package, the compiled program works as expected:
```
2022-08-22 14:53:00.347575: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'cudart64_110.dll'; dlerror: cudart64_110.dll not found
2022-08-22 14:53:00.350148: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
numpy: 1.21.2
tensorflow: 2.9.1
```

**Comment by kayhayen** [comment] 2022-08-23 10:07
I see, tensorflow_probability will need some implicit dependency love, not done so far.

**Comment by PhorstenkampFuzzy** [comment] 2022-09-07 10:50
I have the same problem with tensoflow.compat without the use of tensorflow_probability.
I asue the problem is the protected _api package compat is part of.

**Comment by kayhayen** [comment] 2022-12-11 08:33
This indeed appears to not have to do directly with `tensorflow_probability` at all, it is somehow an incompatibility with the import mechanism, that I do not get.

This is sufficient to reproduce:

```
import tensorflow.compat.v1 as tf
```

It appears that `tensorflow` should have `tensorflow.compat` as a variable, that should serve to import `v1` from below that module. I could in theory see how the `v1` import is then not visible to Nuitka in all cases, but the error is given for the `compat` that gives this.

I am trying a few variations on the import, e.g. trying `.compat` on its own and see if that fails already, which would have to mean that something stupid is going on. From there I believe I can get a minimal reproducer. This may after all be a more general issue, although importing compatibility has not been questioned for quite a while now.

**Comment by kayhayen** [comment] 2022-12-12 11:57
Ok, even `tensorflow.compat` does't work. For once, people have not used a meta path based importer, to achieve strange behaviour, this time, they are extending `__path__` in switch `__path__` in subpackages depending on how they are loaded.

I think we only need to just set sys.modules["tensorflow.compat"]  for it to work.

**Comment by kayhayen** [comment] 2022-12-13 09:20
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

This is also going to be part of the next hotfix for 1.2

**Comment by kayhayen** [comment] 2022-12-14 06:31
I have been compiling for `tensorflow_probability` and it found more missing modules, and there are also a few hidden dependenies. So while the more API changes are part of 1.2.7 hotfix that I just made, more dependencies are to surface I fear, but with 4000+ modules, it will take a while until this finished I guess, hopefully in time for 1.3 or one of its hotfixes.

**Comment by kayhayen** [comment] 2022-12-16 19:13
I got quite a bit done, but this is not immediately obvious:

```
  File "C:\Users\kayha\repos\Py2C\MINITE~1.DIS\tensorflow_probability\python\distributions\__init__.py", line 161, in <module tensorflow_probability.python.distributions>
  File "C:\Users\kayha\repos\Py2C\MINITE~1.DIS\tensorflow_probability\python\distributions\kullback_leibler.py", line 269, in augment_kl_xent_docs
  File "C:\Users\kayha\repos\Py2C\MINITE~1.DIS\tensorflow_probability\python\distributions\kullback_leibler.py", line 261, in merge_doc
AttributeError: 'NoneType' object has no attribute 'split'
```

Apparently some doc strings are `None` which is not expected. Need to check what is going on there later.

**Comment by kayhayen** [comment] 2022-12-19 08:29
The `tensorflow.compat` work is part of the current pre-release.

**Comment by kayhayen** [comment] 2022-12-21 17:03
The 1.3 release has been made. However `tensorflow_probability` will need more work, still the original report is kind of addressed, so I am closing this and will work on that package offline when and if time permits.

**Closed by kayhayen** 2022-12-21 17:03 UTC
Labels: bug, develop
