### ISSUE TITLE
FATAL: dll-files: Plugin issue while working on 'module 'numpy''

### ISSUE THREAD

**Issue by JaegerStephan** [Nuitka/Nuitka#2113] opened 2023-03-15 13:09 UTC
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

<pre>
1.5
Commercial: None
Python: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:42:03) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\jaegeste\project\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
</pre>

* How did you install Nuitka and Python

<pre>
pip
</pre>

* The specific PyPI names and versions

<pre>
autopep8==2.0.1
click==7.1.2
Nuitka==1.5
numpy==1.24.2
opencv-python==4.7.0.72
ordered-set==4.1.0
paho-mqtt==1.6.1
Pillow==9.4.0
pycodestyle==2.10.0
PySide6==6.4.2
PySide6-Addons==6.4.2
PySide6-Essentials==6.4.2
python-dotenv==0.21.1
pytz==2022.7.1
PyYAML==6.0
qt6-applications==6.1.0.2.2
qt6-tools==6.1.0.1.2
shiboken6==6.4.2
tomli==2.0.1
VimbaPython==1.2.1
zstandard==0.20.0
</pre>

* Many times when you get an error from Nuitka, your setup may be special

when I run the main.py within the venv from VSCode or PowerShell, it works fine.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

* Provide in your issue the Nuitka options used

when I run `python -m nuitka --follow-imports --windows-disable-console --enable-plugin=pyside6 .\src\app_qml\main.py`, I can start it with main.cmd, but `python -m nuitka --follow-imports --windows-disable-console --standalone --enable-plugin=pyside6 .\src\app_qml\main.py` 

<pre>
Nuitka-Options:INFO: Used command line options: --follow-imports --windows-disable-console --standalone --enable-plugin=pyside6 .\src\app_qml\main.py
Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
Nuitka:INFO: Starting Python compilation with Nuitka '1.5' on Python '3.8' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pyside6: Injecting pre-module load code for module 'PySide6':
Nuitka-Plugins:INFO: pyside6:     Adding binary folder to runtime 'PATH' environment variable for proper Qt loading.
Nuitka-Plugins:INFO: pyside6: Injecting post-module load code for module 'PySide6.QtCore':
Nuitka-Plugins:INFO: pyside6:     Setting Qt library path to distribution folder. We need to avoid loading target
Nuitka-Plugins:INFO: pyside6:     system Qt plugins, which may be from another Qt version.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
Nuitka:INFO: Completed Python level compilation and optimization.             
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.                
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 158 files (no progress information available).
Nuitka-Scons:INFO: Compiled 407 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 112
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 46
Nuitka-Plugins:INFO: data-files: Included 602 data files due to package data directory 'zoneinfo' for 'pytz'.
Nuitka-Plugins:INFO: dll-files: Found 1 file DLLs from cv2 installation.
Traceback (most recent call last):
  File "C:\Users\jaegeste\project\venv\lib\site-packages\nuitka\plugins\Plugins.py", line 77, in withPluginProblemReporting
    yield
  File "C:\Users\jaegeste\project\venv\lib\site-packages\nuitka\plugins\Plugins.py", line 588, in considerExtraDlls
    for entry_point in _iterateExtraBinaries(
  File "C:\Users\jaegeste\project\venv\lib\site-packages\nuitka\plugins\Plugins.py", line 577, in _iterateExtraBinaries
    for val in value:
  File "C:\Users\jaegeste\project\venv\lib\site-packages\nuitka\plugins\standard\DllFilesPlugin.py", line 239, in getExtraDlls
    for dll_entry_point in self._handleDllConfig(
  File "C:\Users\jaegeste\project\venv\lib\site-packages\nuitka\plugins\standard\DllFilesPlugin.py", line 198, in _handleDllConfig
    for result in self._handleDllConfigByCode(
  File "C:\Users\jaegeste\project\venv\lib\site-packages\nuitka\plugins\standard\DllFilesPlugin.py", line 165, in _handleDllConfigByCode
    filename = self.queryRuntimeInformationMultiple(
  File "C:\Users\jaegeste\project\venv\lib\site-packages\nuitka\plugins\PluginBase.py", line 1011, in queryRuntimeInformationMultiple
    feedback = check_output([sys.executable, "-c", cmd])
  File "C:\Users\jaegeste\project\venv\lib\site-packages\nuitka\utils\Execution.py", line 135, in check_output
    raise NuitkaCalledProcessError(exit_code, cmd, output=output, stderr=stderr)
nuitka.utils.Execution.NuitkaCalledProcessError: Command '['C:\\Users\\jaegeste\\project\\venv\\Scripts\\python.exe', '-c', '\\\nfrom __future__ import print_function\nfrom __future__ import absolute_import\n\ntry:\n   import os, sys\n   library_path = os.path.join("Library", "bin") if os.name == "nt" else "lib"\n   library_prefix = "mkl_" if os.name == "nt" else "libmkl_"\nexcept ImportError:\n    import sys\n    sys.exit(38)\nprint(repr([os.path.join(sys.prefix, library_path, filename)\n for filename in os.listdir(os.path.join(sys.prefix, library_path))\n if filename.startswith(library_prefix)]\n))\nprint("-" * 27)\n']' returned non-zero exit status 1. Error was b'Traceback (most recent call last):\r\n  File "<string>", line 13, in <module>\r\nFileNotFoundError: [WinError 3] The system cannot find the path specified: \'C:\\\\Users\\\\jaegeste\\\\project\\\\venv\\\\Library\\\\bin\''.
FATAL: dll-files: Plugin issue while working on 'module 'numpy''. Please report the bug with the above traceback included.
</pre>

I have already tried to change to older numpy version (1.23.5) but without success.

**Comment by kayhayen** [comment] 2023-03-16 10:31
It seems for Anaconda, we hard coded a path for `numpy` libraries that you do not have. I wonder if this is maybe because numpy is not from Anaconda in your case. It looks like you may be using plain virtualenv and PyPI with Anaconda, and then the code crashes due to unmet expectations. In that case, we should of course check things in this code:

```
- module-name: 'numpy'
  dlls:
    - from_filenames:
        relative_path: '.libs'
        prefixes:
          - 'lib'
      when: 'win32'
    - by_code:
        setup_code: |
          import os, sys
          library_path = os.path.join("Library", "bin") if os.name == "nt" else "lib"
          library_prefix = "mkl_" if os.name == "nt" else "libmkl_"
        filename_code: |
          [os.path.join(sys.prefix, library_path, filename)
           for filename in os.listdir(os.path.join(sys.prefix, library_path))
           if filename.startswith(library_prefix)]
      dest_path: '.'
      when: 'anaconda'
```

**Comment by kayhayen** [comment] 2023-03-16 12:44
> Nuitka-Plugins:WARNING: dll-files: DLL configuration by filename code for 'numpy' did not give a result. Either conditions are missing, or
> Nuitka-Plugins:WARNING: this version of the module needs treatment added.

I am getting that for inside a conda environment.

**Comment by JaegerStephan** [comment] 2023-03-16 14:09
Yes, it is an venv, you are right.

**Comment by kayhayen** [comment] 2023-03-16 18:03
So I managed to reproduce it. The fix will be simple. I believe it will be in 1.5.3 if I am lucky.

**Comment by JaegerStephan** [comment] 2023-03-16 18:08
Great!
Thank your for that very fast solution.
Is there any way, I can solve it by myself? Unfortunately, I do not have many time for get it running.

**Comment by kayhayen** [comment] 2023-03-16 18:55
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-03-17 10:42
This is part of the hotfix release 1.5.3 that I just made. 

It will give a warning. When we are capable of distinguishing "Anaconda package" vs. "PyPI package", we will improve this further, for now it will do.

**Closed by kayhayen** 2023-03-17 10:42 UTC
Labels: bug, factory

**Comment by wangyexiang** [comment] 2023-04-04 12:15
I meet a similar issue. 
**nuitka version**
`python -m nuitka --version`
```
1.5.3
Commercial: None
Python: 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:28:38) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\abc\.virtualenvs\api\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC\14.35.32215\bin\HostX64\x64\cl.exe (cl 14.3).
```
**nuitka command**
`python -m nuitka --onefile --disable-console a.py`

I get the results:
```
Nuitka-Options:INFO: Used command line options: --onefile --disable-console a.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.5.3' on Python '3.9' commercial grade 'not installed'.
Nuitka-Plugins:INFO: delvewheel: Detected usage of 'delvewheel' version '1.3.3' in module 'matplotlib'.
PASS 1: 0.3%|                         | 1/344, appTraceback (most recent call last):
  File " C:\Users\abc\.virtualenvs\api\lib\site-packages\nuitka\plugins\Plugins.py", line 77, in withPluginProblemReporting
    yield
  File " C:\Users\abc\.virtualenvs\api\lib\site-packages\nuitka\plugins\Plugins.py", line 912, in onModuleSourceCode
    new_source_code = plugin.onModuleSourceCode(module_name, source_code)
  File " C:\Users\abc\.virtualenvs\api\lib\site-packages\nuitka\plugins\standard\DelvewheelPlugin.py", line 103, in onModuleSourceCode
    assert self.dll_directory is not None, module_name
AssertionError: matplotlib
FATAL: delvewheel: Plugin issue while working on 'module 'matplotlib''. Please report the bug with the above traceback included.
```
How to fix it? Thanks.

**Comment by kayhayen** [comment] 2023-04-05 13:25
@wangyexiang posting below closed issues is a sure fire way to get ignored, please open a new issue
