### ISSUE TITLE
Module from package scipy is not being included as expected and error when including explicitly

### ISSUE THREAD

**Issue by robguinness** [Nuitka/Nuitka#308] opened 2019-03-20 08:34 UTC
# Description of issue

When building a standalone application that utilizes the package scipy (included via the flag `--include-package=scipy`), I get a runtime `ModuleNotFoundError` for `scipy.special._ufuncs_cxx` when the application is run. In an attempt to fix this, I added the flag `--include-module="scipy.special._ufuncs_cxx"` on a subsequent run, but this results in a build time error of:

```
Error, '_ufuncs_cxx.cpython-36m-x86_64-linux-gnu.so' is not a proper python module name.
```
After looking at the source for `nuitka/tree/Building.py`, this error is thrown when there is a `.` in the module name. But `_ufuncs_cxx.cpython-36m-x86_64-linux-gnu.so` is the name of the actual file where this module resides, so perhaps this is a bug.

# Detailed version/environment info

```
$ python -m nuitka --version
0.6.2
Python: 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
Executable: /home/rob/anaconda3/bin/python
OS: Linux
Arch: x86_64
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
```

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

Nuitka installed via `conda install nuitka`
(Also tried installing system wide using `pip install nuitka`, but the above error is the same in either case)

# Short Example to Reproduce Issue

1. Install `scipy` using pip, anaconda, or build from source.

2. Create a short test script `scipy_test.py`

```
from scipy import special
kth_zero = special.jn_zeros(1, 1)
print(kth_zero)
```
(This is to just make sure that the above module is utilized in the application)

3. Build it into a standalone application using nuitka:

```
$ python -m nuitka --standalone --show-progress --show-modules \
        --python-flag=-S \
        --include-package=scipy \
        scipy_test.py
```

_Note this will pick up a lot of modules that aren't really needed for this simple example, so I recommend excluding them by adding --nofollow-import-to flags, e.g.:_

```
$ python -m nuitka --standalone --show-progress --show-modules \
        --python-flag=-S \
        --include-package=scipy \
	--nofollow-import-to=Cython \
	--nofollow-import-to=tornado \
	--nofollow-import-to=zmq \
	--nofollow-import-to=traitlets \
	--nofollow-import-to=yaml \
	--nofollow-import-to=sympy \
	--nofollow-import-to=distributed \
	--nofollow-import-to=mpmath \
	--nofollow-import-to=ipwidgets \
	--nofollow-import-to=ipkernel \
	--nofollow-import-to=toolz \
	--nofollow-import-to=setuptools \
	--nofollow-import-to=_pytest \
	--nofollow-import-to=pkg_resources \
	--nofollow-import-to=psutil \
	--nofollow-import-to=cffi \
	--nofollow-import-to=colorama \
	--nofollow-import-to=IPython \
	--nofollow-import-to=cryptography \
	--nofollow-import-to=dask \
	--nofollow-import-to=matplotlib \
	--nofollow-import-to=bokeh \
	--nofollow-import-to=PIL \
	--nofollow-import-to=pandas \
	--nofollow-import-to=jinja2 \
	--nofollow-import-to=sphinx \
	--nofollow-import-to=sqlalchemy \
	--nofollow-import-to=jupyter_core \
	--nofollow-import-to=jupyter_client \
	--nofollow-import-to=notebook \
	--nofollow-import-to=prometheus_client \
        scipy_test.py
```

4. Run the built executable:

```
$ ./scipy_test.dist/scipy_test 
Traceback (most recent call last):
  File "/home/rob/code_projects/scipy_test/scipy_test.dist/scipy_test.py", line 1, in <module>
  File "/home/rob/code_projects/scipy_test/scipy_test.dist/scipy/special/__init__.py", line 641, in <module scipy.special>
  File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs
ModuleNotFoundError: No module named 'scipy.special._ufuncs_cxx'
```

5. Try again to build the application but explicitly include that module:

```
python -m nuitka --standalone --show-progress --show-modules \
        --python-flag=-S \
        --include-package=scipy \
        --include-module=scipy.special._ufuncs_cxx \
        scipy_test.py
```
(Include `--nofollow-import-to` flags, as desired, to speed things up)

6. Note that the above step will fail with the following error:

```
Error, '_ufuncs_cxx.cpython-36m-x86_64-linux-gnu.so' is not a proper python module name.
```

**Comment by kayhayen** [comment] 2019-03-20 08:38
My first suspect is that `--include-package=scipy` is not needed, or ought to be not needed anyway, but is what causes the error. It's doing a file system scan below the package, and trips over that name right there. Not sure, what we are doing to get to its real name.

And surely, if you care about size of the result, including all of `scipy` is madness for sure. :)

Yours,
Kay

**Comment by robguinness** [comment] 2019-03-20 08:43
Ok, I will try again without that flag.

Yes, including all of `scipy` for this example is madness. In a real-world example, there would probably be other uses of `scipy`, but as explained in #305 there isn't really a good mechanism currently to include only the needed modules.

**Comment by JorjMcKie** [comment] 2019-03-20 08:43
I am a scipy user (working on Windows though).
On Windows, scipy needs numpy to work, and I'm assuming that's no different on other systems.
Can you confirm this and can you successfuly compile / run numpy scripts? Do you need to use the numpy plugin?

I can at least try your above mini script and see what happens on my Win 10.

**Comment by robguinness** [comment] 2019-03-20 08:47
Yes, this is true. You won't be able to install scipy without first having numpy installed. Sorry for omitting that in the description above. But I think this is unrelated to the error. I actually saw this error in another application that also used `--include-package=numpy` in the nuitka call.

**Comment by robguinness** [comment] 2019-03-20 08:48
@kayhayen , same result when not using `--include-package=numpy`:

```
$ python -m nuitka --standalone --show-progress --show-modules \
>         --python-flag=-S \
>         --include-module=scipy.special._ufuncs_cxx \
>         --nofollow-import-to=Cython \
>         --nofollow-import-to=tornado \
>         --nofollow-import-to=zmq \
>         --nofollow-import-to=traitlets \
>         --nofollow-import-to=yaml \
>         --nofollow-import-to=sympy \
>         --nofollow-import-to=distributed \
>         --nofollow-import-to=mpmath \
>         --nofollow-import-to=ipwidgets \
>         --nofollow-import-to=ipkernel \
>         --nofollow-import-to=toolz \
>         --nofollow-import-to=setuptools \
>         --nofollow-import-to=_pytest \
>         --nofollow-import-to=pkg_resources \
>         --nofollow-import-to=psutil \
>         --nofollow-import-to=cffi \
>         --nofollow-import-to=colorama \
>         --nofollow-import-to=IPython \
>         --nofollow-import-to=cryptography \
>         --nofollow-import-to=dask \
>         --nofollow-import-to=matplotlib \
>         --nofollow-import-to=bokeh \
>         --nofollow-import-to=PIL \
>         --nofollow-import-to=pandas \
>         --nofollow-import-to=jinja2 \
>         --nofollow-import-to=sphinx \
>         --nofollow-import-to=sqlalchemy \
>         --nofollow-import-to=jupyter_core \
>         --nofollow-import-to=jupyter_client \
>         --nofollow-import-to=notebook \
>         --nofollow-import-to=prometheus_client \
>         scipy_test.py
Error, '_ufuncs_cxx.cpython-36m-x86_64-linux-gnu.so' is not a proper python module name.
```

**Comment by JorjMcKie** [comment] 2019-03-20 09:35
Here are some intermediate results.

* The script runs successfully when interpreted
* Compile log of the script

```D:\jorj\Desktop\Develop\Nuitka>python nuitka-sa.py --enable-plugin=numpy-plugin scipy-test.py
NUITKA is compiling 'scipy-test.py' with these options:
 --standalone
 --mingw64
 --python-flag=nosite
 --remove-output
 --experimental=use_pefile
 --disable-dll-dependency-cache
 --enable-plugin=numpy-plugin

Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\cffi\verifier.py:151' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\core\function_base.py:453' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\utils.py:366' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\utils.py:865' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\numpy\lib\utils.py:923' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\_lib\_util.py:160' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at 'C:\Users\jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\_lib\six.py:74' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:INFO: Now copying extra binaries from 'numpy' installation:
Nuitka:INFO: c:\users\jorj\appdata\local\programs\python\python37\lib\site-packages\numpy\.libs\libopenblas.ipbc74c7kurv7cb2pkt5z5fnr3sibv4j.gfortran-win_amd64.dll
Nuitka:INFO: Copied 1 binary.

```
When then executing ``scipy-test.exe``, it fails with an import error coming from ``from ._ufuncs import *`` in ``__init__.py`` in scipy folder ``specials``.
I reacted by including this module actively and got a very similar error message like so:
```
D:\jorj\Desktop\Develop\Nuitka>python nuitka-sa.py --enable-plugin=numpy-plugin --include-module=scipy.special._ufuncs scipy-test.py
NUITKA is compiling 'scipy-test.py' with these options:
 --standalone
 --mingw64
 --python-flag=nosite
 --remove-output
 --experimental=use_pefile
 --disable-dll-dependency-cache
 --enable-plugin=numpy-plugin
 --include-module=scipy.special._ufuncs

Error, '_ufuncs.cp37-win_amd64.pyd' is not a proper python module name.
```

The reason for this admonition are the "." in the name, which ``Building.py`` does not like (function ``decideModuleTree``).

@kayhayen this is not a correct complaint, right?

**Comment by kayhayen** [comment] 2019-03-20 09:51
@JorjMcKie You are spot on there, indeed, but it should never get there. I think the file system scan ought to pick it up as `_ufuncs` and that would be correct then.

Cheout `checkPluginSinglePath` (let the name part Plugin not fool you, this is named that way, because originally the option was called --recurse-plugins=file_system_path and that is what --include-package is still using under the hood.

There is a function being called that is supposed to get at the module name from a filename, and it must be doing it wrong. In `imp` module there is a list of suffixes for extension modules, seems we are not using it there to detect what to strip.

**Comment by kayhayen** [comment] 2019-03-20 09:51
As an aside, I seem to be unable to create links to Nuitka source code on Github today. Annoying. :)

**Comment by JorjMcKie** [comment] 2019-03-20 10:21
you are alluding to ``getModuleNameAndKindFromFilename`` in ``Importing.py`` I think.
This guy (correctly) returns ``getModuleNameAndKindFromFilename: _ufuncs shlib``.
Keeping the search ...

**Comment by JorjMcKie** [comment] 2019-03-20 11:42
I am stuck.
Here is some part of ``Recursion.checkPluginSinglePath``:

```python
def checkPluginSinglePath(plugin_filename, module_package):
    # Many branches, for the decision is very complex, pylint: disable=too-many-branches

    debug("Checking detail plug-in path '%s' '%s':", plugin_filename, module_package)

    module_name, module_kind = Importing.getModuleNameAndKindFromFilename(
        plugin_filename
    )
    print("JM 1:", module_name, module_kind)
    if module_kind is not None:
        decision, reason = decideRecursion(
            module_filename=plugin_filename,
            module_name=module_name,
            module_package=module_package,
            module_kind=module_kind,
            extra_recursion=True,
        )
        print("JM 2:", decision, reason)
        if decision:
            module_relpath = relpath(plugin_filename)
            print(
                "JM 2.1:", plugin_filename, module_relpath, module_package, "py", reason
            )
            module, is_added = recurseTo( # dying here ("_recurseTo" actually upon invoking Building)
                module_filename=plugin_filename,
                module_relpath=module_relpath,
                module_package=module_package,
                module_kind="py", # <=== why?
                reason=reason,
            )
            print("JM 3:", module, is_added) # we never get here
```
With the above tracing prints, I get:
```
JM 1: _ufuncs shlib
JM 2: True Shared library for inclusion.
JM 2.1: C:\Users\jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\special\_ufuncs.cp37-win_amd64.pyd C:\Users\jorj\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\special\_ufuncs.cp37-win_amd64.pyd scipy.special py Shared library for inclusion.
Error, '_ufuncs.cp37-win_amd64.pyd' is not a proper python module name.
```

**Comment by JorjMcKie** [comment] 2019-03-21 00:51
@robguinness - still investigating your case.
Current state:
* It seems we need to extend Nuitka standard plugin ``ImplicitImports.py`` to support ``scipy.special`` (and other ``scipy`` modules). I am still finding out which "implicit imports" we may need (trial-and-error mode unfortunately). I am fairly certain, that we need to import implicitely ``scipy.special._ufuncs_cxx``. This is also noted in the PyInstaller package. ``scipy.special._ufuncs`` is found no problem. With this change I am compiling successfully already.
* My scipy installation has a folder call ``extra-dll``. With the changes from previous points, and when I **manually copy** the extra DLLs over to the compiled ``dist`` folder, I am getting other errors, but they indicate progress, e.g. I am now missing shared Python libraries from the ``linalg`` subfolder ...

Does your installation also have these extra DLLs / shared libraries?

**Comment by JorjMcKie** [comment] 2019-03-21 01:10
New status: **success!**

@robguinness, @kayhayen with the following changes, @robguinness mini script works:

1. Extend ``ImplicitImports.py`` with the following (I suspect more entries will be required when using other scipy components - which wouldn't be a problem though):

```python
        elif full_name == "scipy.special":
            yield "scipy.special._ufuncs_cxx", False
        elif full_name == "scipy.linalg":
            yield "scipy.linalg.cython_blas", False
            yield "scipy.linalg.cython_lapack", False
```

2. Copy scipy subfolder ``extra-dll`` over as a dist/scipy subfolder (54 MB!)

Together with using the numpy-plugin, compile and run works:

```
D:\Jorj\Desktop\Develop\Nuitka\scipy-test.dist>scipy-test
[3.83170597]

D:\Jorj\Desktop\Develop\Nuitka\scipy-test.dist>
```
If these findings consolidate, we will need another plugin, similar to the numpy one, which copies any extra-dll libraries.

**Comment by JorjMcKie** [comment] 2019-03-21 12:51
@robguinness: once the above PR has entered the development branch, you might want to re-execute your test script.
You no longer should need using ``--include-module=scipy.special._ufuncs_cxx``.
Also, in any similar case, the error complaining about "." in the module name should be gone.

On Windows, a complete sub folder of shared libraries is in addition required to compile/run scipy scripts, whether they use the ``special`` subpackage or not. For Nuitka support, this will require an additional plugin.

Whether on Linux you would need a similar precaution, remains to be seen.

**Comment by JorjMcKie** [comment] 2019-03-21 13:19
This Windows sub-folder of extra shared libraries corresponds to the "madness" of the plethora of functions you have been discussing with @kayhayen.
This seems to be different on Linux: if I understood correctly, these functions are **compiled** every time by Nuitka and not provided as libraries.
Most of this seems caused by the ``from ._ufuncs import *`` statement in the ``scipy.special`` package.

**Comment by kayhayen** [comment] 2019-03-21 20:46
So I merged this into develop, and it will be part of a release soon.

**Comment by robguinness** [comment] 2019-03-22 08:59
Thanks @kayhayen and @JorjMcKie for the fast fix! I will checkout develop today and try it out.

**Comment by kayhayen** [comment] 2019-04-04 08:36
Released as 0.6.3

**Closed by kayhayen** 2019-04-04 08:36 UTC
Labels: bug, develop

**Comment by Freds-Turn** [comment] 2023-03-10 13:37
Hey folks, I'm getting the same ImportError that others toiled with `above:"\operability.dist\scipy\special\_ufuncs.pyd" failed: The specified module could not be found.`  I tried running the following commands:
`python -m nuitka --onefile operability.py --enable-plugin=numpy `
or:
`python -m nuitka --onefile operability.py --enable-plugin=numpy --include-package=scipy`

I assume that I need to manually put the files into that special folder.  But when I follow the instructions of @JorjMcKie I can't seem to find the folder he refers to:
`extra-dll`

I know this is an old thread but I still don't see an enable plugin command that cleanly takes care of this on windows yet so now I'm completely stuck.

**Comment by kayhayen** [comment] 2023-03-10 13:46
@Freds-Turn posting below closed issues is a sure-fire way to get ignored.
