### ISSUE TITLE
Is it necessary to load all temporary files into memory? (onefile mode, windows)

### ISSUE THREAD

**Issue by kiseki999** [Nuitka/Nuitka#1493] opened 2022-03-26 12:01 UTC
* Nuitka version, full Python version, flavor, OS, etc.:
  ```  
  0.7.6
  Commercial: None
  Python: 3.10.3 (tags/v3.10.3:a342a49, Mar 16 2022, 12:53:06) [MSC v.1929 32 bit (Intel)]
  Flavor: Unknown
  Executable: D:\Python\Python310-32\python.exe
  OS: Windows
  Arch: x86
  WindowsRelease: 10
  ```

* How did you install Nuitka and Python
  pip without virtualenv and python from python.org

* Issue/Question
  When running the Nuitka onefile mode compiled executable, all files (identical to the contents of the `*.dist` directory) are extracted to a temporary directory.
  Is it necessary to have all those files also loaded into memory?
  
  Maybe this is not really a problem for projects with small `*.dist` directory sizes.
  However, if the size is large enough (e.g. > 500 MB) of course it will greatly increase the memory usage.
  Tested on Windows 8.1, 10, and 11.
  
Thank you.

**Comment by kayhayen** [comment] 2022-03-31 07:58
Hello,

are you saying, that if there is say a 1 GB data file included, that the onefile executable shows this as allocated? This would have to be a memory leak. The decompression and extraction is I think allocating buffers for `zstd` and then writes the files to disk, and that should not keep it in memory. What you are saying would indicate a memory leak. Since you have the setup already, can you provide evidence, maybe in the form of screenshots, how you measured it, before I try to reproduce it.

Yours,
Kay

**Comment by kiseki999** [comment] 2022-04-01 02:41
Sorry, I've made the wrong assumption, because at the time I had not tried directly for a large `*.dist` directory.

I've tried again for fairly large sized data. It turns out that not all temporary data is loaded into memory, but there is still a memory usage of about 129 MB.

<details>
  <summary>What I'm trying is a simple program with this structure:</summary>

  ```
  - data
    - mydata.dat
  - main.py
  ```
  and `main.py` source code:
  ```
  import tkinter as tk

  root = tk.Tk()
  root.mainloop()
  ```
  then run Nuitka with this command:
  ```
  python -m nuitka --onefile --prefer-source-code --include-data-dir=data=data --enable-plugin=tk-inter --python-flag=-OO --python-flag=-S --output-dir=_build/win10_msvc143 main.py`
  ```

  Note:
  - `mydata.dat` is just a fairly large dummy data, for example a binary about 300 MB in size is renamed to `mydata.dat`.
  - This is not an ideal example, but sufficient to demonstrate the issue.
</details>

---

When the onefile executable (`main.exe`) is run, the Task Manager reads that the memory usage is about 129 MB.
<details>
  <summary>Screenshot:</summary>

  ![taskmanager_ss](https://user-images.githubusercontent.com/102393549/161184460-aefe128d-a569-446f-9f94-e8994103f511.png)
  The first `main.exe` is the onefile executable.
</details>

**Comment by kayhayen** [comment] 2022-04-01 10:01
That's OK, thanks for following up. I have a suspect what this should be.

**Comment by kiseki999** [comment] 2022-04-01 10:57
Thank you. I have tried the updated factory version of Nuitka using `venv`.
It works great now.

<details>
  <summary>Screenshot</summary>
  ![taskmanager-ss-2](https://user-images.githubusercontent.com/102393549/161250344-ef12ed6c-6f40-449f-a36c-30691411fa80.png)
</details>

**Comment by kayhayen** [comment] 2022-04-01 12:00
Quite a significant "optimization" then. :-)

**Comment by kayhayen** [comment] 2022-04-04 13:33
This is part of the current pre-release and will be in 0.8 release.

**Comment by kayhayen** [comment] 2022-05-20 14:31
Part of 0.8 release that I just made.

**Closed by kayhayen** 2022-05-20 14:31 UTC
Labels: develop
