### ISSUE TITLE
Problem with distribution name

### ISSUE THREAD

**Issue by nastiliano** [Nuitka/Nuitka#2656] opened 2024-01-20 20:15 UTC
Hello,

Sorry I'm newbe in Nuitka and I followed all steps in manual.
I installed "ccache" too but I'm not able to compile my Python code:

Nuitka-Options: Used command line options: --standalone
Nuitka-Options: --linux-icon=./images/icona.png main.py
Nuitka: Starting Python compilation with Nuitka '2.0rc9' on Python '3.11'
Nuitka: commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL will not be able to create Qt image objects.
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                                           
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13).
Nuitka-Scons: Backend linking program with 191 files (no progress information available for this stage).
Nuitka-Scons: Compiled 190 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 161
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 29
Nuitka:WARNING: Report writing was prevented by exception AssertionError(<importlib_metadata.PathDistribution object at 0x7f46a2c9c250>), use option '--experimental=debug-report-traceback'
Nuitka:WARNING: for full traceback.
Detecting used DLLs: 7.1%|█▊                       | 2/28, PIL/_imaging.soTraceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/nuitka/__main__.py", line 172, in <module>
    main()
  File "/usr/local/lib/python3.11/dist-packages/nuitka/__main__.py", line 158, in main
    MainControl.main()
  File "/usr/local/lib/python3.11/dist-packages/nuitka/MainControl.py", line 1120, in main
    _main()
  File "/usr/local/lib/python3.11/dist-packages/nuitka/MainControl.py", line 1012, in _main
    detectUsedDLLs(
  File "/usr/local/lib/python3.11/dist-packages/nuitka/freezer/Standalone.py", line 335, in detectUsedDLLs
    _detectUsedDLLs(
  File "/usr/local/lib/python3.11/dist-packages/nuitka/freezer/Standalone.py", line 282, in _detectUsedDLLs
    allow_outside_dependencies = Plugins.decideAllowOutsideDependencies(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/plugins/Plugins.py", line 1391, in decideAllowOutsideDependencies
    value = plugin.decideAllowOutsideDependencies(module_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/plugins/standard/DllFilesPlugin.py", line 411, in decideAllowOutsideDependencies
    distribution = getDistributionFromModuleName(module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/utils/Distributions.py", line 216, in getDistributionFromModuleName
    distributions = getDistributionsFromModuleName(module_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/utils/Distributions.py", line 196, in getDistributionsFromModuleName
    _package_to_distribution = _initPackageToDistributionName()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/utils/Distributions.py", line 162, in _initPackageToDistributionName
    distribution_name = getDistributionName(distribution)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/utils/Distributions.py", line 381, in getDistributionName
    assert isValidDistributionName(result), distribution
AssertionError: <importlib_metadata.PathDistribution object at 0x7f46a2c95510>
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.

Thank you.

**Comment by kayhayen** [comment] 2024-01-21 10:28
Neither did you fill out the issue template, not did you include the 'nuitka-crash-report.xml', really bad as it's literally the last thing it told you. If you are not going to read, I wonder if I should write you at all.

In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

**Comment by nastiliano** [comment] 2024-01-21 11:09
Hello,

I know, I didn't include a report either followed the instructions BECAUSE THERE'S NO REPORT.

It crashes and I have no more information and I thought that possible is a little thing and BEFORE pay for comercial version I wondered If I was doing some little thing wrong that's all.

How can I fill the template or obtain more information about this crash???

Thank you, and sorry

**Comment by kayhayen** [comment] 2024-01-21 13:58
It told you also how to get a stack trace of the bug leading to that. These are not yet reliable, since when interrupted, the reporting can be arbitrarily confused by incomplete states, so I also do not demand them. It's probably a mistake that it outputs the message even if the report writing failed, I should fix that too.

You need to always fill out the issue template, and it told you the commands to do it, but you graciously deleted it. If you manage to run factory version, and give the result of the assertion that tells us the name that is problematic, I will give you a pass on this.

You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by nastiliano** [comment] 2024-01-21 18:16
Hello, sorry If I do wrong... I'm gonna start:

- Please check whether the bug was already reported or fixed.
I didn't see it, even "googleing"

- Please check out if the develop version of Nuitka works better for you.
Nope, the crash is exactly the same in "1.9.7" version or in "2.0rc9" version

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
2.0rc9
Commercial: None
Python: 3.11.6 (main, Oct  8 2023, 05:06:43) [GCC 13.2.0]
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 23.10
Version C compiler: /usr/bin/gcc (gcc 13).

- How did you install Nuitka and Python
sudo pip install nuitka --break-system-packages

- The specific PyPI names and versions
pip 23.3.2
attrs==23.2.0
Babel==2.14.0
bcrypt==4.1.2
beautifulsoup4==4.12.3
blinker==1.7.0
Brlapi==0.8.4
certifi==2023.11.17
cffi==1.16.0
chardet==5.2.0
click==8.1.7
cloud-init==23.3.3
colorama==0.4.6
command-not-found==0.3
configobj==5.0.8
cryptography==41.0.7
cupshelpers==1.0
dbus-python==1.3.2
defer==1.0.6
distro==1.9.0
distro-info==1.5+ubuntu0.23.10.1
docutils==0.20.1
duplicity==2.1.5
fasteners==0.19
future==0.18.3
gnupg==2.3.1
html5lib==1.1
httplib2==0.22.0
idna==3.6
importlib-metadata==7.0.1
jaraco.classes==3.3.0
jeepney==0.8.0
Jinja2==3.1.3
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.21.1
jsonschema-specifications==2023.7.1
keyring==24.3.0
Kivy==2.2.1
Kivy-Garden==0.1.5
kivymd==1.1.1
language-selector==0.1
launchpadlib==1.11.0
lazr.restfulclient==0.14.6
lazr.uri==1.0.6
lockfile==0.12.2
louis==3.26.0
lxml==5.1.0
Mako==1.3.0
mariadb==1.1.9
markdown-it-py==3.0.0
MarkupSafe==2.1.4
mdurl==0.1.2
monotonic==1.6
more-itertools==10.2.0
netifaces==0.11.0
Nuitka @ https://github.com/Nuitka/Nuitka/archive/factory.zip#sha256=972a0f892b3f3bda0ff5ddad848871537d7b8756afdfc71d77bd50296e6e22bc
oauthlib==3.2.2
olefile==0.47
ordered-set==4.1.0
packaging==23.2
paho-mqtt==1.6.1
paramiko==3.4.0
pexpect==4.9.0
pillow==10.2.0
protobuf==4.25.1
psutil==5.9.8
ptyprocess==0.7.0
pycairo==1.25.1
pycparser==2.21
pycups==2.0.1
Pygments==2.17.2
PyGObject==3.46.0
PyJWT==2.8.0
PyNaCl==1.5.0
pyparsing==3.1.1
pyrsistent==0.20.0
pyserial==3.5
python-apt==2.6.0+ubuntu1
python-dateutil==2.8.2
python-debian==0.1.49+ubuntu2
pytz==2023.3.post1
pyxdg==0.28
PyYAML==6.0.1
referencing==0.30.2
requests==2.31.0
rich==13.7.0
rpds-py==0.12.0
SecretStorage==3.3.3
setuptools-scm==8.0.4
six==1.16.0
soupsieve==2.5
sqlcipher3-binary==0.5.2.post2
systemd-python==235
tkinter-tooltip==2.1.0
ttkthemes==3.2.2
typing_extensions==4.8.0
ubuntu-advantage-tools==8001
ubuntu-cleaner==1.1.4
ubuntu-drivers-common==0.0.0
ufw==0.36.2
unattended-upgrades==0.1
urllib3==2.1.0
usb-creator==0.3.16
wadllib==1.3.6
webencodings==0.5.1
xdg==6.0.0
xkit==0.0.0
zipp==3.17.0
zstandard==0.22.0

- Many times when you get an error from Nuitka, your setup may be special
just putting "nuitka3 --standalone main.py"

- Provide in your issue the Nuitka options used
- Avoid unnecessary options
just putting  "nuitka3 --standalone main.py"  or  "nuitka3 --onefile main.py"  is the same

- Consider getting commercial support
I will need nuitka in a commercial version to protect my code in Windows, Mac and Linux, but obviously first I need to certatin that works in the 3 platforms

- Output
Nuitka-Options: Used command line options: --standalone main.py
Nuitka: Starting Python compilation with Nuitka '2.0rc9' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including 'PIL.ImageQt' automatically in order to avoid bloat, but this may cause: PIL will not be able to create Qt image objects.
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                                           
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 13).
Nuitka-Scons: Backend linking program with 191 files (no progress information available for this stage).
Nuitka-Scons: Compiled 190 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 190
Nuitka:WARNING: Report writing was prevented by exception AssertionError((<importlib_metadata.PathDistribution object at 0x7fd0eedfbd50>, None)), use option
Nuitka:WARNING: '--experimental=debug-report-traceback' for full traceback.
Detecting used DLLs: 7.1%|█▊                       | 2/28, PIL/_imaging.soTraceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/nuitka/__main__.py", line 172, in <module>
    main()
  File "/usr/local/lib/python3.11/dist-packages/nuitka/__main__.py", line 158, in main
    MainControl.main()
  File "/usr/local/lib/python3.11/dist-packages/nuitka/MainControl.py", line 1120, in main
    _main()
  File "/usr/local/lib/python3.11/dist-packages/nuitka/MainControl.py", line 1012, in _main
    detectUsedDLLs(
  File "/usr/local/lib/python3.11/dist-packages/nuitka/freezer/Standalone.py", line 335, in detectUsedDLLs
    _detectUsedDLLs(
  File "/usr/local/lib/python3.11/dist-packages/nuitka/freezer/Standalone.py", line 282, in _detectUsedDLLs
    allow_outside_dependencies = Plugins.decideAllowOutsideDependencies(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/plugins/Plugins.py", line 1391, in decideAllowOutsideDependencies
    value = plugin.decideAllowOutsideDependencies(module_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/plugins/standard/DllFilesPlugin.py", line 411, in decideAllowOutsideDependencies
    distribution = getDistributionFromModuleName(module_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/utils/Distributions.py", line 216, in getDistributionFromModuleName
    distributions = getDistributionsFromModuleName(module_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/utils/Distributions.py", line 196, in getDistributionsFromModuleName
    _package_to_distribution = _initPackageToDistributionName()
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/utils/Distributions.py", line 162, in _initPackageToDistributionName
    distribution_name = getDistributionName(distribution)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/nuitka/utils/Distributions.py", line 381, in getDistributionName
    assert isValidDistributionName(result), (distribution, result)
AssertionError: (<importlib_metadata.PathDistribution object at 0x7fd0d5a3bc50>, None)
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.


I can't find more than this nor find a report in xml.
Thanks and sorry If I did it wrong
Best regards.

**Comment by kayhayen** [comment] 2024-01-21 19:41
Thanks a lot better. Doesn't make me guess as much. 

I think I can tell now, that importlib.metadata.distributions() provides at least one thing, which maybe has metadata, but for some reason, within that, no "Name" metadata maybe. If you redo it, with current factory (make sure to use the proper command), it will tell the path of the distribution, from which we can infer the package that is causing it. Do not change it, let us investigate this please, this is something that ideally is handled properly. Maybe a new way of building packages is allowed to skip the name in the metadata.

**Comment by kayhayen** [comment] 2024-01-21 19:42
Thanks for your report, this is on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by nastiliano** [comment] 2024-01-21 20:34
Hello again,

Sorry, but I didn't understand...
I've already installed the "factory" version and the error is the same and no more information appears.

Which command I must agregate to figure out what package is failing??

"nuitka3 --?????? main.py"

Thank you.

**Comment by kayhayen** [comment] 2024-01-22 08:57
The factory version has since changed and will output 3 things in the assertion. You should read and understand the factory instructions. And calling `nuitka3` is not the recommended way to execute Nuitka, but use `python -m nuitka` which the Python your program is ran with normally.

**Comment by nastiliano** [comment] 2024-01-22 18:14
No way...

I've updated the factory version to last version: 2rc10

I've executed:

    python3 -m nuitka --experimental=debug-report-traceback main.py

    python3 -m nuitka --experimental=debug-report-traceback  --standalone main.py


There's no any .xml in my computer to see anything...

**Comment by kayhayen** [comment] 2024-01-23 07:41
I was looking more to the exception. I have not worked on the report side of things yet. I will once I reproduce it. But for that I probably need to know what distribution does that to us. So the assertion error has changed, and I want its output. Simple as that.

**Comment by nastiliano** [comment] 2024-01-23 10:20
Ok, then... I'll waiting for. If I could do anythong tell me please.
Yesterday I tried to compile with Windows 11 and Python 3.12, but Nuitka informed me that Python 3.12 is no compatible yet...

Best regards.

**Comment by kayhayen** [comment] 2024-01-24 08:05
Closing for lack of feedback.

**Closed by kayhayen** 2024-01-24 08:05 UTC
Labels: bug, invalid, factory
