### ISSUE TITLE
Trying to create Radis-Gui

### ISSUE THREAD

**Issue by StijnHelsl98t** [Nuitka/Nuitka#2230] opened 2023-05-16 13:48 UTC
I'm trying to create an ftir-gui. One of the main modules I'm using for this is radis. I have been able to create a working gui, which works in the way that I want it. The next step for me, would be to turn that GUI into and .exe file, so that it can just be handed to my colleague who will also need to use it. This is where the problems arise.

It seems that (and I have a hard time figuring out where the problem comes from) Nuitka and Radis don't want to work together. I have now tried it in multiple ways, including trying to include all the directories it needs for data. However, it still seems to not work.

The error given, when trying to create the .exe file is the following:

PASS 1: 95.4%|███████████████████████▊ | 7644/8009, radis.spectrum.rescaleProblem with statement at C:\Users\P70085588\Python\Python39\lib\site-packages\radis\spectrum\rescale.py:354:
->     activated = dict().fromkeys(ordered_keys, False)

Problem with statement at C:\Users\P70085588\Python\Python39\lib\site-packages\radis\spectrum\rescale.py:336:
-> def get_redundant(spec):

Problem with statement at C:\Users\P70085588\Python\Python39\lib\site-packages\radis\spectrum\rescale.py:336:
-> def get_redundant(spec):

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_MODULE' with {'filename': 'C:\\Users\\P70085588\\Python\\Python39\\lib\\site-packages\\radis\\spectrum\\rescale.py', 'module_name': <ModuleName radis.spectrum.rescale
>, 'code_flags': ''}>'.
PASS 1: 95.4%|███████████████████████▊ | 7644/8009, radis.spectrum.rescaleTraceback (most recent call last):
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\__main__.py", line 151, in <module>
    main()
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\__main__.py", line 137, in main
    MainControl.main()
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 1090, in main
    _main()
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 950, in _main
    main_module = _createMainModule()
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\MainControl.py", line 244, in _createMainModule
    optimizeModules(main_module.getOutputFilename())
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\Optimization.py", line 337, in optimizeModules
    finished = makeOptimizationPass()
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\Optimization.py", line 293, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\Optimization.py", line 180, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\Optimization.py", line 92, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 546, in computeModule
    result = module_body.computeStatementsSequence(
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\StatementNodes.py", line 157, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\FrameNodes.py", line 192, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 632, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 351, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 616, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 4870, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 616, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 1158, in computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 339, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 495, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 511, in computeFunction
    result = statements_sequence.computeStatementsSequence(
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\StatementNodes.py", line 159, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 632, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\TryNodes.py", line 79, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\StatementNodes.py", line 157, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\FrameNodes.py", line 192, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 632, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\VariableAssignNodes.py", line 351, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 616, in onExpression
    new_node, change_tags, change_desc = expression.computeExpressionRaw(self)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\ChildrenHavingMixins.py", line 3970, in computeExpressionRaw
    return self.computeExpression(trace_collection)
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\CallNodes.py", line 108, in computeExpression
    return called.computeExpressionCall(
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\AttributeNodesGenerated.py", line 2870, in computeExpressionCall
    return self._computeExpressionCall(
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\nodes\AttributeNodesGenerated.py", line 2863, in _computeExpressionCall
    return trace_collection.computedExpressionResult(
  File "C:\Users\P70085588\Python\Python39\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 684, in computedExpressionResult
    new_expression = expression.computeExpression(self)
AttributeError: 'ExpressionSideEffects' object has no attribute 'computeExpression'

As my own background is very much not really python related (and this was supposed to be an easy side project, where I should have only needed to run 1 line), I'm finding it hard to understand the shown errors, nor do I feel trully comfortable to fully change the radis code. Any advice?

With kind regards,
Stijn

**Comment by gdementen** [comment] 2023-05-16 17:57
@StijnHelsl98t : please **read** and **fill** the issue template instead of deleting it !!! It is there for a reason. It looks like a bug in Nuitka, but we do not even know what version you are using, how to reproduce your error, etc.

**Comment by StijnHelsl98t** [comment] 2023-05-16 18:00
my appologies... I have fully missed the issue template... I did however maybe find the problem. It seems that Nuitka does not handle the following python code very well: lvl_index = dict().fromkeys(list(vib_levels.index))

However, when this code is changed to: lvl_index = {key: None for key in list(vib_levels.index)}, it can actually get past this AttributeError. 

However, I will for certainty also fill in the issue template, so that people with more python knowledge can take a look at it!

**Comment by gdementen** [comment] 2023-05-17 08:38
Sorry for being a bit harsh in my first message. It's just that given the amount of issues the project gets, it is very time-consuming for Kay (the author of the project) to always ask the same questions to get all the information needed to solve issues, time that could be used to develop the product instead. Could you provide us the missing bits? Most importantly the version of Nuitka you are using (so that we know you are not running an old version of Nuitka when the issue is potentially already fixed in the latest version) and some /minimal/ Python code which still reproduces the error. In this case I have the feeling that this code could be very small. Something like:

```python
ordered_keys = something_you_need_to_fill  # <-- probably need to experiment a bit to see if a simple list triggers the issue or if it needs another type
activated = dict().fromkeys(ordered_keys, False)
```

**Comment by StijnHelsl98t** [comment] 2023-05-17 14:02
Hereby hopefully following the correct template.

**python -m nuitka --version**
1.5.7
Commercial: None
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\P70085588\Python\Python39\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.33.31629\bin\HostX64\x64\cl.exe (cl 14.3).

**How did you install Nuitka and Python**
Everything was installed by using PyCharm. I am also working in PyCharm, where I created a venv which I use for all of my modules. This module list is quite large, however, for this problem only 1 module seems to be the problem:
- Radis

**Provide in your issue the Nuitka options used**
The way I ran Nuitka was as followed: python -m nuitka --standalone Gui_v1.py, which I run in the Pycharm Terminal (with my chosen venv)

**Also supply a Short, Self Contained, Correct, Example**
The full error is shown in my first message. This error however has since disappeared, as I have removed code like this:
ordered_keys = something_you_need_to_fill  # <-- probably need to experiment a bit to see if a simple list triggers the issue or if it needs another type
activated = dict().fromkeys(ordered_keys, False)

I also experimented a bit with differenent ordered_keys (strings, list, sets and dictionaries), but all seems to make it crash in the exact way. However, when I go to code like: activated = {key: False for key in ordered_keys}, the error has since disappeared.

**Comment by kayhayen** [comment] 2023-05-21 18:27
I actually managed to reproduce it with the snipped you provided, looking into this now.

**Comment by kayhayen** [comment] 2023-05-21 18:33
Thanks @gdementen for taking care of this one, turned this into some very quick for me now. Makes me day. It will be on factory and in the 1.6 release.

**Comment by kayhayen** [comment] 2023-05-30 09:51
This is part of the stable release 1.6 that I just made.

**Closed by kayhayen** 2023-05-30 09:51 UTC
Labels: factory
