### ISSUE TITLE
KeyError: 'style' while building the application

### ISSUE THREAD

**Issue by tbhaxor** [Nuitka/Nuitka#640] opened 2020-03-04 19:09 UTC
Python Version: Python 3.7.1

Nuitka Version: 0.6.8rc3

Installation Method: PIP

Command: `nuitka --standalone --recurse-all --show-progress --include-package=numpy --show-modules app.py`

Error: 
```
Nuitka:INFO: Included compiled module 'zmq.sugar.socket'.
Nuitka:INFO: Included compiled module 'zmq.sugar.stopwatch'.
Nuitka:INFO: Included compiled module 'zmq.sugar.tracker'.
Nuitka:INFO: Included compiled module 'zmq.sugar.version'.
Nuitka:INFO: Included compiled module 'zmq.utils'.
Nuitka:INFO: Included compiled module 'zmq.utils.constant_names'.
Nuitka:INFO: Included compiled module 'zmq.utils.interop'.
Nuitka:INFO: Included compiled module 'zmq.utils.jsonapi'.
Nuitka:INFO: Included compiled module 'zmq.utils.sixcerpt'.
Nuitka:INFO: Included compiled module 'zmq.utils.strtypes'.
Traceback (most recent call last):
  File "C:\Users\deven\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 186, in <module>
    main()
  File "C:\Users\deven\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\__main__.py", line 179, in main
    MainControl.main()
  File "C:\Users\deven\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 749, in main
    result, options = compileTree(main_module=main_module)
  File "C:\Users\deven\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\MainControl.py", line 650, in compileTree
    frozen_code = generateBytecodeFrozenCode()
  File "C:\Users\deven\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\freezer\BytecodeModuleFreezer.py", line 64, in generateBytecodeFrozenCode
    general.info("Embedded as frozen module '%s'.", module_name)
  File "C:\Users\deven\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\Tracing.py", line 132, in info
    my_print(message, style=style)
  File "C:\Users\deven\AppData\Local\Programs\Python\Python37\lib\site-packages\nuitka\Tracing.py", line 98, in my_print
    % kwargs["style"]
KeyError: 'style'
```

Type of Application: Simple Selenium Driven Application

**Comment by kayhayen** [comment] 2020-03-11 09:40
The tracing is currently broken, but this got fixed on develop in the mean time. This is considered a duplicate of another report, where this was found too.

**Closed by kayhayen** 2020-03-11 09:40 UTC

**Comment by jtran** [comment] 2020-04-01 18:14
@kayhayen, what issue is this a duplicate of?  I was unable to find it.  I'm running into this error also, and I'm trying to find where it was fixed.  Any help would be appreciated.  Thanks.

**Comment by tbhaxor** [comment] 2020-04-01 20:46
@jtran  So do i

**Comment by jtran** [comment] 2020-04-20 18:09
Just to clarify, I'm running on the latest `develop`, and I still have this issue using python 3.7.7.

**Comment by jtran** [comment] 2020-04-20 19:09
I confirmed that 2be3d0a77203808980f908b62f6bbeb5468d2242 introduces the error.  Unfortunately, when I build with the commit before it, I get a different error, but that's a different issue.

**Comment by jtran** [comment] 2020-04-21 21:02
@tbhaxor, I made a pull request.  Hopefully it'll get merged soon. 🤞
