### ISSUE TITLE
Support for newer scikit-image is needed

### ISSUE THREAD

**Issue by pauljurczak** [Nuitka/Nuitka#2103] opened 2023-03-11 21:35 UTC
Tested with Docker (Docker version 23.0.1, build a5ee5b1) on Ubuntu 22.04.2 built with this file:
```
FROM python:3.11-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y build-essential patchelf && rm -rf /var/lib/apt/lists/*
RUN pip install scikit-image numpy Nuitka
ADD so-3.py /
RUN python -m nuitka so-3.py --standalone --onefile
CMD ["./so-3.bin"]
```
and this script (so-3.py):
```
import sys
import numpy as np
from skimage.measure import label, regionprops

print(sys.executable, sys.version, sys.version_info)

image = np.zeros((8, 8), dtype='i1')
image[2:4, 2:4] = 1
labels, _ = label(image, background=0, return_num=True, connectivity=2)

for prop in regionprops(labels, image, cache=True):
  print(prop.coords)
```
I'm getting this output:
```
Traceback (most recent call last):                                                                                              
  File "/tmp/onefile_1_1678566288_604959/so-3.py", line 3, in <module>
    from skimage.measure import label, regionprops
    
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/tmp/onefile_1_1678566288_604959/skimage/__init__.py", line 74, in <module skimage>
  File "/tmp/onefile_1_1678566288_604959/lazy_loader/__init__.py", line 243, in attach_stub
ValueError: Cannot load imports from non-existent stub '/tmp/onefile_1_1678566288_604959/skimage/__init__.pyi'
```
The script itself runs fine, i.e. Docker image build with:
```
FROM python:3.11-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y build-essential patchelf && rm -rf /var/lib/apt/lists/*
RUN pip install scikit-image numpy Nuitka
ADD so-3.py /
CMD ["python", "so-3.py"] 
```
produces:
```
/usr/local/bin/python 3.11.2 (main, Mar  1 2023, 14:56:17) [GCC 10.2.1 20210110] sys.version_info(major=3, minor=11, micro=2, releaselevel='final', serial=0)
[[2 2]
 [2 3]
 [3 2]
 [3 3]]
```
as expected.

**Comment by kayhayen** [comment] 2023-03-12 07:37
Make your docker output what reports need, `python -m nuitka --version`  and the compilation report for better reports.

**Comment by kayhayen** [comment] 2023-03-12 07:58
This is really ugly, but admittedly clever by them, to use `.pyi` files. This must be a newer `skimage` version that added it. I imagine this trick will get copied over time, since it kind of makes sense to avoid the duplication.

Now, Nuitka is not including `.pyi` files as data files on purpose, because they are supposedly unused. We will need a new annotation in the Yaml configuration that does cause the inclusion of the `.pyi` file for a given more, since I want to stay firm on that. As a bonus, for the commercial version, these `.pyi` files could be embedded automatically. I have to assume it's pretty easy to modify a deployed program by modifying these `.pyi` files otherwise. Compare with https://nuitka.net/doc/commercial/protect-data-files.html

**Comment by pauljurczak** [comment] 2023-03-12 08:01
Do you still need more logs from Docker image building? What is the flag to get them? They disappear from the terminal after each line of `Dockerfile` is processed.

**Comment by kayhayen** [comment] 2023-03-12 08:22
Docker is really a bad tool to debug apparently. But reports are written to a file, surely you can get that artifact, and it will contain the version outputs too. I have however managed to reproduce it, and will have a fix soon, nothing needed from you here. I will however add it to the report template, that I want these informations even and esp. from container builds.

**Comment by kayhayen** [comment] 2023-03-12 10:04
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-03-12 10:05
This is neither a regression of 1.5 nor related to using 3.11 for all I know.

**Comment by pauljurczak** [comment] 2023-03-12 18:38
The test runs fine with a factory branch of Nuitka. Thank you for very fast response.

**Comment by kayhayen** [comment] 2023-03-14 11:36
This is part of the hotfix release 1.5.1 that I just made.

**Closed by kayhayen** 2023-03-14 11:36 UTC
Labels: bug, factory

**Comment by pauljurczak** [comment] 2023-03-14 21:24
Is release 1.5.1 going to be available on PyPI? It's not there yet.

**Comment by kayhayen** [comment] 2023-03-15 07:27
Should be now, the CI failed to upload indeed.
