### ISSUE TITLE
AttributeError: module 'pandas._libs.tslibs.c_timestamp' has no attribute '_Timestamp'

### ISSUE THREAD

**Issue by nrarom** [Nuitka/Nuitka#775] opened 2020-07-02 12:07 UTC
python -m nuitka --version

0.6.9rc5
Python: 3.7.7 (default, May  7 2020, 21:25:33)
Executable: /home/dev/anaconda3/envs/py37/bin/python
OS: Linux
Arch: x86_64

ISSUE: 
`import pandas as pd`

This produces the following when executing the compiled file (compilation is completed successfully)
```
  File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/MySQLClient_P.py", line 3, in <module MySQLClient_P>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/pandas/__init__.py", line 30, in <module pandas>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/pandas/_libs/__init__.py", line 3, in <module pandas._libs>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/pandas/_libs/tslibs/__init__.py", line 3, in <module pandas._libs.tslibs>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "pandas/_libs/tslibs/c_timestamp.pxd", line 7, in init pandas._libs.tslibs.conversion
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "pandas/_libs/tslibs/c_timestamp.pyx", line 1, in init pandas._libs.tslibs.c_timestamp
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "pandas/_libs/tslibs/tzconversion.pyx", line 1, in init pandas._libs.tslibs.tzconversion
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "pandas/_libs/tslibs/c_timestamp.pxd", line 7, in init pandas._libs.tslibs.timedeltas
AttributeError: module 'pandas._libs.tslibs.c_timestamp' has no attribute '_Timestamp'

```

The result above is from using pandas 0.25.0 as I've seen similar questions around here and they seemed to have been fixed by them downgrading their version of pandas.

I first tried with pandas 1.0.3 and stable version of nuitka (0.6.8.4) but it failed with a different error (again the compilation ran fine but when running it failed):

```
File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/MySQLClient_P.py", line 3, in <module MySQLClient_P>
  File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/pandas/__init__.py", line 55, in <module pandas>
  File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/pandas/core/api.py", line 29, in <module pandas.core.api>
  File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/pandas/core/groupby/__init__.py", line 1, in <module pandas.core.groupby>
  File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/pandas/core/groupby/generic.py", line 60, in <module pandas.core.groupby.generic>
  File "/home/dev/Build_lambda_package/predictor_py/Predictor.dist/pandas/core/frame.py", line 105, in <module pandas.core.frame>
ImportError: cannot import name 'generic' from 'pandas.core.groupby' (/home/dev/Build_lambda_package/predictor_py/Predictor.dist/pandas/core/groupby/__init__.py)
```

**Comment by kayhayen** [comment] 2020-07-28 08:17
This might be a duplicate of an importing problem that I am about to fix.

**Comment by kayhayen** [comment] 2020-08-01 09:33
Can you retry with the develop version? This may be the importing issue, or a hidden dependency, I can't really tell now.

**Comment by kayhayen** [comment] 2020-11-15 12:02
Closing for lack of feedback.

**Closed by kayhayen** 2020-11-15 12:02 UTC
Labels: bug, needs_example
