### ISSUE TITLE
Windows and MinGW64: Error: ld.exe: cannot find ltrans0.ltrans.o: No such file or directory

### ISSUE THREAD

**Issue by babaloveyou** [Nuitka/Nuitka#1768] opened 2022-08-29 07:20 UTC
im trying to pack my file with:
"python -m nuitka  --onefile test.py"

but it always error:
collect2.exe: error: ld returned 1 exit status
scons: *** [D:\all_tools\Mycode\windows\myproject.exe] Error 1
scons: internal stack trace:

```
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'orderedset' PyPI package for best Python compile time performance.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing': installed'.
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.      
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.  
Nuitka:INFO: Completed Python level compilation and optimization.                  
Nuitka:INFO: Generating source code for C backend compiler.       
Nuitka:INFO: Running data composer tool for optimal constant value handling.       
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program with 12 files (no progress information available).
File not found - C:\Users\abc\AppData\Local\Temp\.msr-cmd-alias.doskeys
c:/users/abc/appdata/local/nuitka/nuitka/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\b
abal\AppData\Local\Temp\cc85rsjH.ltrans0.ltrans.o: No such file or directory
c:/users/abc/appdata/local/nuitka/nuitka/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\b
abal\AppData\Local\Temp\cc85rsjH.ltrans1.ltrans.o: No such file or directory
c:/users/abc/appdata/local/nuitka/nuitka/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\b
abal\AppData\Local\Temp\cc85rsjH.ltrans2.ltrans.o: No such file or directory
c:/users/abc/appdata/local/nuitka/nuitka/gcc/x86_64/11.3.0-14.0.3-10.0.0-msvcrt-r3/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find C:\Users\b
abal\AppData\Local\Temp\cc85rsjH.ltrans3.ltrans.o: No such file or directory
collect2.exe: error: ld returned 1 exit status
```

 

**please help me solve my problems. i cannot fix it

my Nuitka version**
1.0.6
Commercial: None
Python: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 23:11:46) [MSC v.1916 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\all_tools\Mycode\windows\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

i found this issues,but can not fix this error
https://github.com/Nuitka/Nuitka/issues/1469

**Comment by kayhayen** [comment] 2022-08-29 11:53
Sadly I have to agree with you there, this is the same error. I wonder if you have an idea where `File not found - C:\Users\abc\AppData\Local\Temp\.msr-cmd-alias.doskeys` could stem from.

**Comment by babaloveyou** [comment] 2022-08-29 12:30
This is not the key reason, I have added this file, the error is the same, also I have used the latest version of mingw

**Comment by kayhayen** [comment] 2022-08-29 14:11
That's brilliant. This is reproducible for you, is that correct, or is it intermittent? I would love to get to to the bottom of it.

**Comment by kayhayen** [comment] 2022-08-29 14:12
Dumb question, `abc` is your user name, or is it potentially one with special characters, aka unicode?

**Comment by kayhayen** [comment] 2022-08-29 14:13
The next thing I was going to do is to update gcc to 12.2, are you saying you did that manually already?

**Comment by babaloveyou** [comment] 2022-08-30 01:09
I have downloaded the latest version of mingw including gcc12.2.0,  but the same error

## download url 
[winlibs-x86_64-posix-seh-gcc-12.2.0-llvm-14.0.6-mingw-w64ucrt-10.0.0-r2.zip](https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-14.0.6-10.0.0-ucrt-r2/winlibs-x86_64-posix-seh-gcc-12.2.0-llvm-14.0.6-mingw-w64ucrt-10.0.0-r2.zip)

## Extract the files to this folder
C:\Users\myaccount\AppData\Local\Nuitka\Nuitka\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3

**Comment by babaloveyou** [comment] 2022-08-30 01:11
> Dumb question, `abc` is your user name, or is it potentially one with special characters, aka unicode?

This is a fake username to prevent private information from leaking

**Comment by babaloveyou** [comment] 2022-08-30 01:26
> That's brilliant. This is reproducible for you, is that correct, or is it intermittent? I would love to get to to the bottom of it.

I installed the new Windows 10 x64 operating system and nuitika 1.0.6  in the virtualbox, and there was no problem in compiling, but I tested various combinations on my host for 10 hours, and I couldn't solve the problem, which has a great impact on my work.


### combination


 installs mingw through choco +nuitka 1.1rc7 
 installs mingw through choco +nuitka 1.1rc7 
nuitka 1.1rc7  +[winlibs-x86_64-posix-seh-gcc-12.2.0-llvm-14.0.6-mingw-w64ucrt-10.0.0-r2.zip] 
nuitka 1.1rc7  +11.3.0-14.0.3-10.0.0-msvcrt-r3     
nuitka 1.0.6  +11.3.0-14.0.3-10.0.0-msvcrt-r3   
nuitka 1.0.6  +[winlibs-x86_64-posix-seh-gcc-12.2.0-llvm-14.0.6-mingw-w64ucrt-10.0.0-r2.zip] 
nuitka 1.0.5 +11.3.0-14.0.3-10.0.0-msvcrt-r3   
nuitka 1.0.4  +11.3.0-14.0.3-10.0.0-msvcrt-r3

**Comment by kayhayen** [comment] 2022-08-30 04:45
I am suspecting it might be something about your user name there, maybe contains a space, maybe something unicode trips it up, you can send it to me via private email if you want to, or if you can think of what makes it special, express that.

That said, maybe we can make gcc pick the temporary directory as the one that we decide, or set %TEMP% to a short path, if that is what gcc uses there, to avoid your home directory path being exposed at all.

**Comment by kayhayen** [comment] 2022-08-30 04:47
Nuitka already uses a short path to scons to avoid issus with non encodable paths to MSVC and gcc. Pretty much possible that this is another variant of the issue. You can test that by adding a `abc` user, and have it work on your machine.

**Comment by babaloveyou** [comment] 2022-08-30 05:09
> I am suspecting it might be something about your user name there, maybe contains a space, maybe something unicode trips it up, you can send it to me via private email if you want to, or if you can think of what makes it special, express that.
> 
> That said, maybe we can make gcc pick the temporary directory as the one that we decide, or set %TEMP% to a short path, if that is what gcc uses there, to avoid your home directory path being exposed at all.

Spaces and special unicode characters do not exist in my path and username,The problem is most likely the version of gcc

**Comment by kayhayen** [comment] 2022-08-30 06:27
The version of gcc if pretty much enforced, and the same for all users, but only very few do have this issue. If you were familiar with such technology, it would be interesting to trace while files gcc create, deletes, and access there, but I don't know myself. And as you demonstrated, if it is a gcc bug, and it has to be, updating gcc won't help us here. I searched their bug tracker the othr day to find a report about this, but there is nothing.

The issue I mentioned does in principle exist however. I am therefore tempted into making that fix, even if you don't have hope of it affecting you. You didn't try setting TEMP and HOME variable to something short, did you? Nuitka would probably download gcc again, and run it from there. It also strikes me that the command line is long there. I do not have reason to suspect a truncation to be going on, but maybe it would be possible somehow still.

**Comment by kayhayen** [comment] 2022-08-30 07:37
I used `LDFLAGS=-v` and I try getting output the command it runs for linking, and I think I can see that it uses mixed temporary paths, sometimes the Windows one, sometimes the ones from environment variables. Mixing it is not our problem, if what you state is correct, but not going to make things more clear, to partially use one form of the path, than in other places, so I am droping that attempt. I also believe, I knew if Chinese people had the issue more often. I think it was enough to change the PWD there.

So question remains, what's different on that machine. Just some sort of race in gcc maybe. Then, what's left to do is to use `--mingw64 --clang` and use the Clang in MinGW64, or to use `--lto=no`, or to use MSVC. Since you are keeping information private, which is your right, there is nothing I have an idea about what Nuitka could be causing this with (although it seems very unlikely that only Nuitka has it), so I guess, what we need would be an option to make it output what commands it is running, but if I read it correctly, the old gcc not using `make` yet, we don't see them, because maybe they are not even there, maybe with gcc 12, that's a thing, so if I eventually update, we can revisit, or you can try with your gcc 12 setup right now.

**Comment by babaloveyou** [comment] 2022-08-30 13:19
I solved the problem by replacing this mingw version

## download url

https://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win64/Personal%20Builds/mingw-builds/8.1.0/threads-posix/seh/x86_64-8.1.0-release-posix-seh-rt_v6-rev0.7z/download

**Comment by kayhayen** [comment] 2022-08-30 14:39
gcc 8.1, I guess you also had to disarm a version check in Nuitka. Probably indeed some sort of gcc LTO bug. I am closing it, because I have no hope of this being fixable in Nuitka.

**Closed** 2022-09-04 08:54 UTC
Labels: bug
