### ISSUE TITLE
missing module with cryptography.hazmat

### ISSUE THREAD

**Issue by BrannonKing** [Nuitka/Nuitka#645] opened 2020-03-07 00:51 UTC
Nuitka seems to compile my project fine, but it fails at runtime with this error:
```
Traceback (most recent call last):
  File "/.../demo_crypt/main.py", line 1, in <module>
    from cryptography.hazmat.primitives.kdf.scrypt import Scrypt
  File "/.../demo_crypt/venv/lib/python3.7/site-packages/cryptography/hazmat/primitives/kdf/scrypt.py", line 14, in <module cryptography.hazmat.primitives.kdf.scrypt>
    from cryptography.hazmat.primitives import constant_time
  File "/.../demo_crypt/venv/lib/python3.7/site-packages/cryptography/hazmat/primitives/constant_time.py", line 11, in <module cryptography.hazmat.primitives.constant_time>
    from cryptography.hazmat.bindings._constant_time import lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._constant_time'
```
Here are the commands to reproduce it:
1. Make a virtualenv: `python3.7 -m venv demo_crypt/venv`
2. `cd demo_crypt`
3. `pip install wheel cryptography`
4. `pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"`
5. Create a main.py that contains:
```python
from cryptography.hazmat.primitives.kdf.scrypt import Scrypt
from cryptography.hazmat.backends import default_backend

def scrypt(passphrase, salt, scrypt_n=1<<12, scrypt_r=12, scrypt_p=1):
    kdf = Scrypt(salt, length=32, n=scrypt_n, r=scrypt_r, p=scrypt_p, backend=default_backend())
    return kdf.derive(passphrase)

print(scrypt(b"junk", b"sea"))
```
6. Run `python main.py` to ensure that there are no errors.
7. `python -m nuitka --follow-imports -j 10 --plugin-enable=pylint-warnings main.py`
8. `./main.bin`

**Comment by JorjMcKie** [comment] 2020-03-07 10:07
There are just a few implicit imports missing. I have added them, so your test script works for me now.
next version of nuitka should have it.

**Comment by BrannonKing** [comment] 2020-03-09 15:36
Excellent. Is there a "develop.zip" for the current code?

**Comment by JorjMcKie** [comment] 2020-03-09 16:24
I currently cannot access the repo for whatever reason. What you can do is replacing ``.../nuitka/plugins/standard/ImplcitImports.py`` of your installation with the one contained in here: [ImplicitImports.zip](https://github.com/Nuitka/Nuitka/files/4307771/ImplicitImports.zip). It contains three add'l imports one of which is your missing one.

**Comment by BrannonKing** [comment] 2020-03-09 17:11
You ImplicitImports.zip matched what I already had. Which branch has the updated file?

**Comment by JorjMcKie** [comment] 2020-03-09 18:04
> Your ImplicitImports.zip matched what 

Can't be! The four lines marked yellow shouldn't be in your version:

![Anmerkung 2020-03-09 135410](https://user-images.githubusercontent.com/8290722/76242689-80030580-620d-11ea-857d-e56c55ed4426.jpg)

Your test script failed w/o these and succeeded once I had added them. The file is based on this version:

```bash
python -m nuitka --version
0.6.8rc5
Python: 3.7.5 (tags/v3.7.5:5c02a39a0b, Oct 15 2019, 00:11:34) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\Jorj\AppData\Local\Programs\Python\Python37\python.exe
OS: Windows
Arch: x86_64
```

**Comment by Torxed** [comment] 2020-03-17 16:47
@JorjMcKie Will this fix the issue below as well:

```python
Traceback (most recent call last):
  File "/tmp/archinstall_gui/archinstall_gui/webgui.py", line 11, in <module>
    from lib.loghandler import LOG_LEVELS # log() gets imported automatically.
  File "/tmp/archinstall_gui/archinstall_gui/lib/loghandler.py", line 3, in <module lib.loghandler>
    from systemd.journal import JournalHandler
  File "/usr/lib/python3.8/site-packages/systemd/journal.py", line 34, in <module systemd.journal>
    from ._journal import __version__, sendv, stream_fd
ModuleNotFoundError: No module named 'systemd._journal'
```

Or am I going to far off the traditional way of doing things that I break any possibility to getting my libraries imported? *(I'm aware that my methods aren't recommended)*

Relevant code *(I assume)*: https://github.com/Torxed/archinstall_gui/blob/master/lib/loghandler.py

**Comment by milos-korenciak** [comment] 2020-07-06 12:19
I have the similar problem /w cryptography:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".../examples/nuitka_3141/__init__.py", line 1, in <module nuitka_3141>
  File ".../examples/nuitka_3141/jwe_test.py", line 235, in <module nuitka_3141.jwe_test>
  File ".../examples/authlib/jose/rfc7516/jwe.py", line 81, in serialize_compact
  File ".../examples/authlib/jose/rfc7516/jwe.py", line 165, in _prepare_alg_enc_key
  File ".../examples/authlib/jose/util.py", line 13, in prepare_algorithm_key
  File ".../examples/authlib/jose/rfc7518/_backends/_key_cryptography.py", line 28, in prepare_public_key
  File ".../examples/cryptography/hazmat/backends/__init__.py", line 15, in default_backend
  File ".../examples/cryptography/hazmat/backends/openssl/__init__.py", line 7, in <module cryptography.hazmat.backends.openssl>
  File ".../examples/cryptography/hazmat/backends/openssl/backend.py", line 75, in <module cryptography.hazmat.backends.openssl.backend>
  File ".../examples/cryptography/hazmat/bindings/openssl/binding.py", line 16, in <module cryptography.hazmat.bindings.openssl.binding>
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._openssl'
```
But now I am using cryptography package from (patched) authlib. (But the cryptography itself is untouched.)
Probably the problem /w embedding venv/lib/python3.7/site-packages/cryptography/hazmat/bindings/_openssl.abi3.so . (I am on Lin.)

**Comment by nixargh** [comment] 2020-07-14 14:52
Looks like I'm having some similar issue:
```  
    from cryptography.fernet import Fernet, InvalidToken
  File "/usr/lib/python3/dist-packages/cryptography/fernet.py", line 17, in <module cryptography.fernet>
    from cryptography.hazmat.primitives import hashes, padding
  File "/usr/lib/python3/dist-packages/cryptography/hazmat/primitives/padding.py", line 13, in <module cryptography.hazmat.primitives.padding>
    from cryptography.hazmat.bindings._padding import lib
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._padding'
```
I've got this trying to run my app after compilation.

I've checked **nuitka/plugins/standard/ImplicitImports.py** and it includes:
``` 
          elif full_name in (
              "cryptography.hazmat.bindings._openssl",
              "cryptography.hazmat.bindings._constant_time",
              "cryptography.hazmat.bindings._padding",
          ):
              yield "_cffi_backend", True
```
Any thoughts?

**Comment by calmh** [comment] 2020-09-21 15:26
Same here, have tried various patches on ImplicitImports but not getting it, so far...

**Comment by Thomatn** [comment] 2020-09-22 12:03
Same here,

Test file only contains:
`
from OpenSSL import crypto as sslCheck                                                      # SSL Lib
`

With pyopenssl==19.1.0 (depends on cryptography)

With cryptography==2.9:
`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import testo
  File "/root/testo.py", line 1, in <module testo>
  File "/root/OpenSSL/__init__.py", line 8, in <module OpenSSL>
  File "/root/OpenSSL/crypto.py", line 12, in <module OpenSSL.crypto>
  File "/root/cryptography/x509/__init__.py", line 8, in <module cryptography.x509>
  File "/root/cryptography/x509/base.py", line 18, in <module cryptography.x509.base>
  File "/root/cryptography/x509/extensions.py", line 20, in <module cryptography.x509.extensions>
  File "/root/cryptography/hazmat/primitives/constant_time.py", line 11, in <module cryptography.hazmat.primitives.constant_time>`

With cryptography==3.1:
`Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import testo
  File "/root/testo.py", line 26, in <module testo>
  File "/root/OpenSSL/__init__.py", line 8, in <module OpenSSL>
  File "/root/OpenSSL/crypto.py", line 15, in <module OpenSSL.crypto>
  File "/root/OpenSSL/_util.py", line 6, in <module OpenSSL._util>
  File "/root/cryptography/hazmat/bindings/openssl/binding.py", line 15, in <module cryptography.hazmat.bindings.openssl.binding>
ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._openssl'`

**Comment by milos-korenciak** [comment] 2021-03-15 08:35
Working solution if you are compiling just a module. (No standalone exe solution here!)
Circumvent cryptography at all by --nofollow-import-to=cryptography . Then install / require given version of cryptography in virtualenv you are using to import your compiled module.
If you need cryptography anyway (I can imagine security reasons only), then you probably need to patch cryptography:

- Move all .so / .pyd files into path where it can be loadable (consider site-packages directly).
- Fix imports of e.g. _openssl. E.g.: from cryptography.hazmat.bindings._openssl import blah --> from _openssl import blah
- You need to ensure _openssl in site-packages is not spoofed someway. (How to do it secure / ensure unspoofed version?)

**Comment by astevko** [comment] 2021-07-15 23:43
I'm suffering from this ModuleNotFoundError too.

>   File "/private/var/folders/fs/7qvh4tmn5t92fs68m60y65cw0000gn/T/_MEIDE7DxV/cryptography/fernet.py", line 16, in <module cryptography.fernet>
>   File "/private/var/folders/fs/7qvh4tmn5t92fs68m60y65cw0000gn/T/_MEIDE7DxV/cryptography/hazmat/primitives/padding.py", line 11, in <module cryptography.hazmat.primitives.padding>
> ModuleNotFoundError: No module named 'cryptography.hazmat.bindings._padding'
>

**Comment by kayhayen** [comment] 2021-07-16 05:49
Closing this, to me the issue is failed, because I don't have a reproducer, I don't know what parts are fixed, please open new issues with full description. The things posted here are probably all different ones, but it's unclear how relevant they are now.

**Closed by kayhayen** 2021-07-16 05:49 UTC
