### ISSUE TITLE
standalone binary takes 1 minute to start on windows 10

### ISSUE THREAD

**Issue by frankyifei** [Nuitka/Nuitka#917] opened 2021-01-04 02:18 UTC
Platform: windows 10, official python 3.8.1, nuitka  0.6.10.4 installed through pip
The program is a small test and nothing too complex. The standard generated binary works normally but with '--standalone' the binary takes about 1 minutes to start, it takes 1 cpu core to work 100% for 1 minute and then start to give result. CPython would take 1 second to give results. Standard binary takes about 1 second as well.
The full source is here
```python
from pypinyin import  pinyin, Style
accept_pinyin={'bō','bāo','bān','bēn','bāng','bēng','biāo','bīn','bīng','bái','bǒ','bǎi','běi','bǎo','bǎn','běn','běng','bǐng','bǔ','bào','bì','biàn','bìn','bìng','pēng',\
'piān','péng','pín','píng','pú','pǐn','pǔ','pài','pàn','pù','méi','móu','mén','máng','méng','miáo','mín','míng','mǎ','mǒ','měi','mǎn','mǎng','měng','mǐ','miǎn',\
'mǐn','mò','mào','mèng','mì','mù','fā','fēi','fān','fēn','fāng','fēng','fū','fó','fán','fáng','féng','fú','fǎ','fěi','fàn','fàng','fèng','fù','dōu','dān','dāng','dēng','duō',\
'duān','dōng','dá','dé','dí','dǎo','dǎn','dǎng','dǐ','dǒng','dà','dài','dào','dòu','dì','diàn','dìng','dù','duàn','dòng','tā','tāi','tāo','tī','tiān','tīng','tuān','tōng','tái',\
'táng','téng','tí','tián','tíng','tú','tuán','tóng','tǎ','tǎn','tǐ','tiǎo','tǐng','tǒng','tè','tài','tàn','tiào','tuò','né','nán','néng','níng','nóng','nǎi','nǔ','nuǎn','nài','nèi',\
'niàn','nuò','nòng','lái','láo','lóu','lán','láng','lí','liáo','liú','lián','lín','liáng','líng','lú','luán','lún','lóng','lěi','lǎn','lǎng','lěng','lǐ','liǔ','lǐn','lǐng','lǔ','lǒng','lǚ','lè',\
'làng','lì','liào','liàn','lìn','liàng','lìng','lù','luò','luàn','lùn','lǜ','lüè','gē','gāo','gēn','gāng','gēng','guō','guī','guān','guāng','gōng','guó','gě','gǎn','gěng','gǔ',\
'guǎn','guǎng','gǒng','gài','gèng','gù','guì','guàn','gòng','kāi','kāng','kuā','kuān','kūn','kōng','kuí','kǎ','kě','kǎi','kǎo','kěn','kuǎn','kè','kài','kòu','kàn','kuò',\
'kuài','kuàng','kòng','hēng','hū','huā','huī','huān','hé','háo','hán','háng','héng','hú','huó','huái','huí','huán','hóng','hǎi','hǎo','hǎn','hǔ','huǒ','hè','hào','hòu',\
'hàn','hù','huà','huò','huì','huàn','jī','jiā','jiē','jiāo','jiū','jīn','jiāng','jīng','jū','jūn','jí','jié','jú','jué','jǐ','jiǔ','jǐn','jǐng','jǔ','jì','jià','jiè','jiù','jìn','jiàng','jìng','jù',\
'jùn','qī','qiē','qiū','qiān','qīn','qiāng','qīng','qū','qí','qié','qiáo','qiú','qián','qín','qiáng','qíng','qú','quán','qún','qǐ','qiě','qiǎn','qǐng','qì','qià','qiè','qiàn','qìn',\
'qìng','qù','què','xī','xiāo','xiū','xiān','xīn','xiāng','xīng','xū','xuān','xūn','xí','xiá','xián','xiáng','xíng','xú','xué','xuán','xún','xióng','xǐ','xiě','xiǎo','xiǎn',\
'xiǎng','xǐng','xǔ','xì','xià','xiào','xiù','xiàn','xìn','xiàng','xìng','xù','xuàn','xùn','zhī','zhāi','zhāo','zhōu','zhān','zhēn','zhāng','zhēng','zhuī','zhuān','zhōng',\
'zhí','zhé','zhái','zháo','zhuó','zhǐ','zhě','zhěn','zhǎng','zhǔn','zhǒng','zhì','zhào','zhàn','zhèn','zhèng','zhuàn','zhuàng','zhòng','chē','chāo','chāng','chū',\
'chuān','chūn','chōng','chí','chá','chái','cháo','chán','chén','cháng','chéng','chuán','chún','chóng','chǎn','chǎng','chuǎng','chì','chè','chèn','chàng','chèng',\
'chuàng','shī','shē','shōu','shān','shēn','shāng','shēng','shū','shuō','shuāng','shí','shén','shú','shě','shǒu','shěn','shǎng','shěng','shǔ','shuǐ','shǔn','shì','shào',\
'shèn','shàng','shèng','shù','shuò','shuài','shùn','ráo','rán','rén','ráng','réng','rú','róng','rǎn','rǔ','ruǐ','rǒng','rì','rèn','ràng','ruì','rùn','zēng','zūn','zōng','zé',\
'zǐ','zǎi','zǎo','zěn','zuǒ','zǒng','zì','zè','zài','zào','zuò','zòng','cā','cān','cāng','cōng','cí','cái','cáo','cáng','céng','cún','cóng','cǐ','cǎi','cuǒ','cuǐ','cè','càn','cù','cuì'\
,'cùn','sī','sān','sēn','sēng','sū','suī','sūn','sōng','sú','suí','sǎ','sǎn','suǒ','suǐ','sǔn','sì','sài','sù','suì','suàn','sòng','ōu','ān','ēn','yī','yōu','yān','yāng','yīng','wēi',\
'wēn','yuē','yuān','yōng','áng','yí','yáo','yóu','yán','yáng','yíng','wú','wéi','wán','wén','wáng','yú','yuán','yún','ǒu','yǒu','yǎn','yǐn','yǐng','wǔ','wǒ','wěi',\
'wǎn','wěn','yǔ','yuǎn','yǔn','yǒng','ài','ào','àng','yì','yà','yè','yào','yòu','yàn','yìn','yàng','yìng','wài','wèi','wàn','wèn','wàng','yù','yuè','yùn','yòng'}
if __name__ == '__main__':
	name1=''
	name2=''
	input = pinyin('运昌', style=Style.FINALS_TONE, strict=False)
	print(u'韵母:',input)
	shengmu=['b','p','m','f','d','t','n','l','g','k','h','j','q','x','zh','ch','sh','r','z','c','s','y','w','']
	list=[]
for i in shengmu:
	name1 = i + input[0][0]
	if name1 in accept_pinyin:
		for j in shengmu:
			name2= j+input[1][0]
			if name2 in accept_pinyin:
				fullname =name1+'-' + name2
				list.append(fullname)
print(list)
```

**Comment by kayhayen** [comment] 2021-01-05 11:07
I wish this had at least a minimal English documentation. I have reproduced this with only the import, maybe there is something wrong about it, I also had it crash with my development version, maybe missed implicit dependencies and attempts to make up for it.

**Comment by kayhayen** [comment] 2021-01-05 11:30
Woah, it has `pypinyin.pinyin_dict` which opening in `vi` and jumping to the end of the file takes a long time already. That is a file with a 41k entries dictionary, apparently generated. So I am suspecting that the constants loading code of Nuitka is the one to blame here, probably because it attempts to compress usage of constants. 

Before the change, the C compilation would have killed it on this one, now the data composer blob seems to be the trouble when loading it. I will have to profile what it is there.

These are the offenders, found with `PYTHONPROFILEIMPORTTIME=1`

import time:  26343225 |   26343225 |     pypinyin.pinyin_dict
import time: 319718612 |  319718612 |     pypinyin.phrases_dict

The phrases dict is probably equally worse.

I can easily suspect that a quadratic thing is going on when trying to load the constant strings and then checking in a kind of all constants dictionary, if they are already existing. Right now per module one blob is created, and this is the supposed way to make sure they do reuse memory. Also for the `int` objects, the same thing is attempted.

**Comment by frankyifei** [comment] 2021-01-05 11:50
the import pypinyin is actually a prounciation dictionary for Chinese.

**Comment by kayhayen** [comment] 2021-01-05 17:06
so, I changed the interning of constant ints, longs, etc to use dictionaries as well, but the strings were already using it, but the keys were many int values, so this could have been that, but probably wasn't after all, since it feels equally slow. Still a scalability improvement I guess, but it seems that comparing lists, dicts, etc. is still slow, even thought that compares only the memory used for a list, not the list items, more like a deep `is` comparing on all the list data at once.

**Comment by kayhayen** [comment] 2021-01-05 17:09
I think for non-hashable data, I need to finde a way to make them hashable on the fly, with probably an illegal hack, e.g. setting `tp_hash` temporarily, so we can hash the compared data and have the lists in a dictionary for when we need them, that should allow using a dictionary for these as well, and still be fast.

**Comment by kayhayen** [comment] 2021-01-10 13:04
So this was a bunch of work, `tp_hash` and `tp_richcompare` are overloaded for everything, and therefore dictionaries can be used to cache all kinds of values, which using a hash function, will be extremely quick for lookups.

This is part of the current pre-release, due to its regressive potential, it will be in the next release only, no hotfix planned.

**Comment by kayhayen** [comment] 2021-01-23 09:56
Release as part of 0.6.11 just now.

**Closed by kayhayen** 2021-01-23 09:56 UTC
Labels: bug, develop
