### ISSUE TITLE
rich.pretty without ipython yields SyntaxError during source generation

### ISSUE THREAD

**Issue by chrisy** [Nuitka/Nuitka#1816] opened 2022-09-28 14:36 UTC
```console
$ python -m nuitka --version
1.2rc1
Commercial: None
Python: 3.9.14 (main, Sep  6 2022, 23:29:09) 
Flavor: Unknown
Executable: /.../venv/bin/python
OS: Darwin
Arch: x86_64
```

For this issue, Nuitka was installed from source into a venv. Python 3.9 from Homebrew. Same issue is apparent on 1.1 installed using pip. Also observed on Windows and Linux.

```
rich==12.5.1
```

Nuitka's antibloat module contains this optimization for `rich.pretty`:

https://github.com/Nuitka/Nuitka/blob/e12789463dd4da1c279d515c8345258936ea0fb9/nuitka/plugins/standard/standard.nuitka-package.config.yml#L1818-L1823

Unfortunately, `rich.pretty` contains this block of code:

https://github.com/Textualize/rich/blob/13dd9c2c2ebee5409368d5494f4712f52a073b93/rich/pretty.py#L250-L252
```python
    try:  # pragma: no cover
        ip = get_ipython()  # type: ignore[name-defined]
        from IPython.core.formatters import BaseFormatter
```

The effect of the optimization is to yield the line:
```python
        ip = raise NameError  # type: ignore[name-defined]
```

Which in turns causes a `SyntaxError` during processing.

Test script, `t.py`:

```python
from rich.pretty import Pretty

if __name__ == "__main__":
        a = Pretty("hello")
```

Trimmed output of building:

```console
$ python -m nuitka --standalone t.py
...
Nuitka-Inclusion:WARNING: Cannot follow import to module 'rich.pretty' because of 'SyntaxError'.
...
```

And, naturally, the resulting binary doesn't work, yielding a complaint about the above syntactic problem.

```console
$ ./t.dist/t
Traceback (most recent call last):
  File "/.../t.dist/t.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "/.../t.dist/rich/pretty.py", line 1, in <module rich.pretty>
  File "/.../venv/lib/python3.9/site-packages/rich/pretty.py", line 246
    ip = get_ipython()  # type: ignore[name-defined]
         ^
SyntaxError: invalid syntax
```

As a workaround, I can include the option `--noinclude-IPython-mode=allow` so it does not optimize that line; there is no ipython in the venv and this is not an ipython interpreter, so the result is still a `NameError` once that line is reached.

**Comment by pavlutom** [comment] 2022-09-29 09:09
The exact same thing is happening with Python 3.9.12 and Nuitka 1.1 from pip on both Windows 10 and RHEL

**Comment by kayhayen** [comment] 2022-09-29 11:59
A fix is coming in 1.1.1, thanks for your report.

**Comment by kayhayen** [comment] 2022-10-02 07:54
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

I intend to push 1.1.1 today if everything else goes fine.

**Comment by kayhayen** [comment] 2022-10-02 07:56
And as a reminder to myself, a `SyntaxError` raised for a module that has the source code changed by a plugin, should be aborting the compilation with an error, and there needs to be a test, which checks out for a given compilation mode, all the anti-bloat config related to a module, so this is caught in regression testing, and to generally have more coverage. This was not happening here, but imagine upstream differences cause it, we wouldn't notice now until a user encounters it.

**Comment by kayhayen** [comment] 2022-10-02 07:57
In the specific case, the better feature would be to force `get_ipython` to be a `NameError`, and never look it up from builtins, then we wouldn't need a source code patch and be automatically robust for similar code.

**Comment by kayhayen** [comment] 2022-10-02 08:32
Reverting it, and improving the interfaces, now this is happening. It checks if the code gave a `SyntaxError` in the original form, and if not, it complains like this. This of course is also useful during development if there is a diff, which I am going to add next.

> FATAL: anti-bloat: Making changes to 'rich.pretty' that cause SyntaxError 'invalid syntax (pretty.py, line 246)'

**Comment by kayhayen** [comment] 2022-10-02 08:40
Ok, this is much nicer now.

```
Nuitka-Plugins:WARNING: --- original
Nuitka-Plugins:WARNING: +++ modified
Nuitka-Plugins:WARNING: @@ -243,7 +243,7 @@
Nuitka-Plugins:WARNING:              builtins._ = value  # type: ignore[attr-defined]

Nuitka-Plugins:WARNING:      try:  # pragma: no cover
Nuitka-Plugins:WARNING: -        ip = get_ipython()  # type: ignore[name-defined]
Nuitka-Plugins:WARNING: +        ip = raise NameError  # type: ignore[name-defined]
Nuitka-Plugins:WARNING:          from IPython.core.formatters import BaseFormatter

Nuitka-Plugins:WARNING:          class RichFormatter(BaseFormatter):  # type: ignore[misc]
FATAL: anti-bloat: Making changes to 'rich.pretty' that cause SyntaxError 'invalid syntax (pretty.py, line 246)'
```

**Comment by kayhayen** [comment] 2022-10-02 08:41
So, I guess, with 1.2 this part of the lessons learned is done, this would make it a lot more obvious what is going on, because while @chrisy found this out on their own, I don't think that should be needed.

**Comment by kayhayen** [comment] 2022-10-02 09:24
This is part of the 1.1.1 hotfix release. The commercial update will follow suite right after I see that all packages and release tests work fine.

**Closed by kayhayen** 2022-10-02 09:24 UTC
Labels: bug, factory
