### ISSUE TITLE
Nuitka doesn't work with the dipy package.

### ISSUE THREAD

**Issue by dscarmo** [Nuitka/Nuitka#1664] opened 2022-07-08 01:16 UTC
0.9.3
Commercial: None
Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\Diedre\miniconda3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

I installed Nuitka and Python with the following steps

Install with miniconda3 windows installer.

    pip install nuitka

There is no other version of Python in the computer.

The versions of the involved packages are:

    dipy==1.5.0
    numpy==1.22.3

The hello world example works for me. However, trying to run a simple dipy.__version__ gives the following output:

    ImportError: cannot import name 'assert_array_equal' from 'numpy.testing'

Coming from inside the dipy.testing module. 
The following simple code should reproduce it:

    import dipy

    print(dipy.__version__)

Compiled with:

    python -m nuitka --standalone --enable-plugin=numpy dipy_test.py

**Comment by gdementen** [comment] 2022-07-08 10:12
I think this is caused by the antibloat plugin which removes testing* from numpy, but I don't remember if you can deactivate that plugin (disclaimer: I am not Nuitka's author)

**Comment by kayhayen** [comment] 2022-07-08 11:51
You are correct @gdementen, coincidentally we added proper tag support on factory branch, but we do not yet have the "allow" flags for `numpy.testing`, which however ought to come at some point soon now. However, this is probably a case of a module with a test framework imported no matter what, so it will get its own anti-bloat treatment and be good.

**Comment by kayhayen** [comment] 2022-07-08 11:55
This does the trick, can be put into a user yaml file (develop), or well, into the main one (stable) as a hack:

```
- module-name: "dipy"
  anti-bloat:
    - description: "remove dipy and numpy testing framework"
      replacements_plain:
        "from .testing import setup_test" : ""
```

**Comment by kayhayen** [comment] 2022-07-08 12:00
The solution is now on https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment] 2022-07-08 12:01
I do not plan any more hotfixes for 0.9, so this will be in 1.0 only.

**Comment by kayhayen** [comment] 2022-07-14 16:55
This is currently on the develop branch.

**Comment by kayhayen** [comment] 2022-07-30 15:32
This is part of 1.0 release.

**Closed by kayhayen** 2022-07-30 15:32 UTC
Labels: bug, develop
