### ISSUE TITLE
Nuitka needs support for "importlib_metadata.entry_points()" and "importlib.metadata.entry_points()" hard imports

### ISSUE THREAD

**Issue by djkcyl** [Nuitka/Nuitka#1955] opened 2022-12-22 15:03 UTC
* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

```
(venv) PS C:\Users\djkcyl\Desktop\BBot-Graia> python -m nuitka --version
1.3.1
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\djkcyl\Desktop\BBot-Graia\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe (gcc).
```

* How did you install Nuitka and Python

pip

* The specific PyPI names and versions

```
aiohttp==3.8.3
aiosignal==1.3.1
anyio==3.6.2
async-timeout==4.0.2
attrs==22.1.0
bcrypt==4.0.1
bilireq==0.2.3.post0
black==22.12.0
certifi==2022.9.24
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.6
commonmark==0.9.1
creart==0.2.2
creart-graia==0.1.5
croniter==1.3.8
cryptography==38.0.3
ecdsa==0.18.0
fastapi==0.86.0
frozenlist==1.3.3
graia-amnesia==0.6.0
graia-ariadne==0.9.8
graia-broadcast==0.19.0
graia-saya==0.0.17
graia-scheduler==0.0.10
graiax-playwright==0.2.1
greenlet==2.0.1
grpcio==1.50.0
h11==0.14.0
httpcore==0.16.1
httpx==0.23.1
idna==3.4
importlib-metadata==5.0.0
launart==0.6.1
loguru==0.6.0
multidict==6.0.2
mypy-extensions==0.4.3
Nuitka==1.3.1
ordered-set==4.1.0
passlib==1.7.4
pathspec==0.10.3
peewee==3.15.4
Pillow==9.3.0
platformdirs==2.6.0
playwright==1.28.0
protobuf==4.21.9
psutil==5.9.4
pyasn1==0.4.8
pycparser==2.21
pydantic==1.10.2
pyee==9.0.4
Pygments==2.13.0
python-dateutil==2.8.2
python-jose==3.3.0
python-multipart==0.0.5
PyYAML==6.0
qrcode==7.3.1
rfc3986==1.5.0
rich==12.6.0
richuru==0.1.1
rsa==4.9
sentry-sdk==1.11.1
six==1.16.0
sniffio==1.3.0
starlette==0.20.4
statv==0.3.2
tomli==2.0.1
typing_extensions==4.4.0
urllib3==1.26.12
uvicorn==0.19.0
websockets==10.4
win32-setctime==1.1.0
yarl==1.8.1
zipp==3.10.0
```

* Provide in your issue the Nuitka options used

```
nuitka --standalone --show-progress --output-dir=build --user-package-configuration-file=nuitka.yml .\main.py
```

**Comment by djkcyl** [comment] 2022-12-22 15:04
like **.\venv\Lib\site-packages\pydantic-1.10.2.dist-info**

**Comment by thesct22** [comment] 2022-12-22 15:08
--include-package=pydantic or --include-package-data=pydantic.
I use both.

**Comment by djkcyl** [comment] 2022-12-22 15:11
Okay, let me try that.

> --include-package=pydantic or --include-package-data=pydantic. I use both.

**Comment by djkcyl** [comment] 2022-12-22 15:23
> --include-package=pydantic or --include-package-data=pydantic. I use both.

It doesn't look like he's working.
![image](https://user-images.githubusercontent.com/59153990/209166501-e2337750-8945-4f90-bb08-b1c0413027f3.png)

**Comment by djkcyl** [comment] 2022-12-22 15:27
In the folder they look like this

![image](https://user-images.githubusercontent.com/59153990/209167206-633e61ed-3342-41f8-9cfe-b036475c8982.png)
![image](https://user-images.githubusercontent.com/59153990/209167299-ffcb19fe-3a18-4f54-90f1-b57adfa75d1f.png)

**Comment by djkcyl** [comment] 2022-12-22 15:35
If I use `graia.broadcast` it works, but it doesn't copy the metadata

**Comment by kayhayen** [comment] 2022-12-22 17:38
The metadata is not necessary with Nuitka, it tries to resolved everything at compile time. It seems that might have bugs with your packages, but I don't think I can be bothered to copy text from screenshots. Please report in a usable fashion.

**Comment by djkcyl** [comment] 2022-12-23 03:24
> The metadata is not necessary with Nuitka, it tries to resolved everything at compile time. It seems that might have bugs with your packages, but I don't think I can be bothered to copy text from screenshots. Please report in a usable fashion.

This is my project > [BBot](https://github.com/djkcyl/BBot-Graia/tree/nuitka)

The `graia-ariadne` SDK I'm using requires metadata, and in pyinstaller the `--copy-metadata` parameter makes it work properly. nuitka I couldn't find a similar function, so much so that my program didn't work properly. Here is the test command line I used.
```
nuitka --standalone --show-progress --output-dir=build --include-package-data=graia-broadcast --include-package-data=graia-ariadne --include-package-data=graiax-playwright --include-package-data=creart-graia --include-package-data=graia-scheduler --include-package-data=graia-saya --include-package-data=graia-amnesia . \test.py
```

When I run the above command and the output completes successfully, running the program gives me these errors
```
PS C:\Users\djkcyl\Desktop\BBot-Graia\build\test.dist> .\test.exe
Traceback (most recent call last):
  File "C:\Users\djkcyl\Desktop\BBOT-G~1\build\TEST~1.DIS\test.py", line 4, in <module>
  File "C:\Users\djkcyl\Desktop\BBOT-G~1\build\TEST~1.DIS\graia\ariadne\app.py", line 201, in __init__
  File "C:\Users\djkcyl\Desktop\BBOT-G~1\build\TEST~1.DIS\graia\ariadne\app.py", line 127, in _ensure_config
  File "C:\Users\djkcyl\Desktop\BBOT-G~1\build\TEST~1.DIS\graia\ariadne\service.py", line 79, in __init__
  File "C:\Users\djkcyl\Desktop\BBOT-G~1\build\TEST~1.DIS\creart\__init__.py", line 60, in create
  File "C:\Users\djkcyl\Desktop\BBOT-G~1\build\TEST~1.DIS\creart\__init__.py", line 48, in _assert_supported
TypeError: current environment does not contain support for graia.broadcast:Broadcast
PS C:\Users\djkcyl\Desktop\BBot-Graia\build\test.dist>
```

After asking the developer of the SDK, I learned that the SDK requires metadata to run, so I was able to add the metadata of these required packages with the `--copy-metadata` parameter when using pyinstaller, and the program ran fine after adding the metadata

**Comment by kayhayen** [comment] 2022-12-23 07:25
I am assuming this is some kind of version check of something and/or a hidden dependency combined.

The warnings you were getting from Nuitka about failure to locate package data, is because it expects Python module names, and not PyPI names. They won't include meta data though, because that is not package data.

Can you check out the code of creart and graia as indicated by the lines on the call stack and see what it actually wants to do, usually this will be a version check. I am assuming that there is a bug hiding going on, where the package meta data exception is converted to a "helpful" TypeError to obstruct us from seeing the original error, and also it's dropping the cause it seems if that is true.

**Comment by djkcyl** [comment] 2022-12-23 07:38
The source code for the two error traces is as follows

https://github.com/GraiaProject/creart/blob/master/creart/__init__.py#L60
```python3
def _signature(target: type) -> str:
    return f"{target.__module__}:{target.__name__}"


def supported(target: type):
    return _signature(target) in _mapping


def _assert_supported(target: type):
    if not supported(target):
        raise TypeError(f"current environment does not contain support for {_signature(target)}")


def create(target_type: type[T], *, cache: bool = True) -> T:
    sig = _signature(target_type)
    if cache and sig in _created:
        return _created[sig]
    _assert_supported(target_type)
    creator = _get_creator(target_type)
    result = creator.create(target_type)
    if cache:
        _created[sig] = result
    return result
```

https://github.com/GraiaProject/Ariadne/blob/dev/src/graia/ariadne/service.py#L114

I tried to look at the code of the library, and since I don't have a good understanding of Python, I don't really understand what the code is trying to achieve, but it might be some kind of internal association of the family

**Comment by kayhayen** [comment] 2022-12-23 08:38
The cruicial code porting is this:

```
from importlib_metadata import entry_points
def _env_scan():
    for entry in entry_points().select(group="creart.creators"):
        creator = entry.load()
        if creator.available():
            add_creator(creator)
```

So far Nuitka only supports `pkg_resources.iter_entry_points`, group would be usable as well, but this is of course the more modern interface. When Nuitka recognizes `pkg_resources.iter_entry_points` it includes it as a run time constant, without the full meta data available. So that option of this other tool, will indeed not be necessary. I however apparently need to add support for it.

**Comment by kayhayen** [comment] 2022-12-23 08:41
If you migrated this by hand backwards in time, chances are it will work for you with this, but I think adding this won't take forever, and also there was a wart, namely that packages for which entry points are scanned, are not automatically included, this is because there is e.g. no point to load them, just to find out if they are `.available()` and this seems similar.

**Comment by kayhayen** [comment] 2022-12-23 09:06
That's what it does:

```
>>> type(importlib.metadata.entry_points())
<class 'dict'>
>>> importlib.metadata.entry_points().keys()
dict_keys(['array_api', 'babel.checkers', 'babel.extractors', 'console_scripts', 'devpi_client', 'distutils.commands', 'distutils.setup_keywords', 'egg_info.writers', 'flake8.extension', 'hypothesis', 'keyring.backends', 'markdown.extensions', 'pandas_plotting_backends', 'pipx.run', 'pygments.lexers', 'pylama.linter', 'pytest11', 'setuptools.finalize_distribution_options', 'sphinx.html_themes', 'tensorboard_plugins', 'twine.registered_commands', 'virtualenv.activate', 'virtualenv.create', 'virtualenv.discovery', 'virtualenv.seed'])
```

So I guess, this need requires all entry points to be included until such time, where we become able to optimize dictionary iteration with compile time constants well enough to ignore the unused ones, probably not happening soon, but that is just a thought on the side. I have waste and including all of those is of course wasteful. 

Also I will need to figure out, if these `EntryPoints` can use similar code to what we already have for pkg_resources, or if this becomes a new type be added, which will make it also more work.

**Comment by djkcyl** [comment] 2022-12-23 10:19
I used a dumb way to get this library to work properly after being packaged by nuitka
![code](https://user-images.githubusercontent.com/59153990/209318192-c29eb059-ed65-4250-86dd-2942ab5b31e4.png)

**Comment by kayhayen** [comment] 2022-12-23 12:29
Whatever floats your boat. I guess, this can also be used as a cue to which nodules need to be included.

**Comment by kayhayen** [comment] 2022-12-24 18:35
Interestingly the variant of `importlib.metadata` returns a dictionary, where as the backport does not, and returns a mere dictionary. The real thing will therefore be relatively easy, where as the backport will be more difficult it seems.

**Comment by kayhayen** [comment] 2022-12-24 20:22
```
from importlib_metadata import entry_points
print(inspect.signature(entry_points))
from importlib.metadata import entry_points
print(inspect.signature(entry_points))
```

gives:

```
(**params) -> Union[importlib_metadata.EntryPoints, importlib_metadata.SelectableGroups]
()
```

**Comment by kayhayen** [comment] 2022-12-24 20:23
I figured that one out, parameters are added with 3.10 which also introduced `SelectableGroups`. I guess, we maybe start out by doing the one without arguments first.

**Comment by kayhayen** [comment] 2022-12-26 14:42
The changes for `importlib.metadata.entry_points` are on factory branch now. For the backport to work, like I said, it's more tedious, but for Python3.10 it will be needed anyway even for the stdlib code of course.

**Comment by kayhayen** [comment] 2022-12-30 07:16
As has been pointed out, the `entry_points` built-in with arguments is broken by this on 3.10, it wouldn't work in standalone, but it will work for accelerated mode normally, so this is kind of a regression for that narrow but relevant use case. My generation of hard imports does not support verion specifcs yet, also a reason why the ctypes.CDLL and another one I forgot are still manual.

I might add a workaround for 3.10 to remove the support temporarily.

**Comment by kayhayen** [comment] 2022-12-31 07:16
This has driven a lot of improvements, with the generated hard import nodes as a detour which made me generate all child expression nodes, and at first without the version dependent specs, but after finding that `entry_points` changed in 3.10 totally, also adding that.

The `SelectableGroups` and `EntryPoints` are derived from dicts and lists, so I made the code generation for dictionaries reusable, and the container creations get their beef from a mixin that can be used in these, while also adding the copy to reconstruct from the dict and list, so we can generate a list of entry points first and then convert it to the needed type.

With all of that, it seems `importlib.metadata.entry_points()` works for standalone and accelerated mode with both 3.9 and 3.10 on factory, where I just updated it. The changes I did so far were pretty breaking, and I even reverted develop back to not have the parts of them I thought were good, after finding issues with default value having hard imports from specs.

I now hardened the nodes against wasteful tuple conversions inside the tree, and added more auto compute to nodes, such that giving up on optimization (entry points are pretty much totally not going to change) was now much easier.

I need to now stabilize this, it's pretty likely to trigger compile time assertions with some code forms, but it will be healthy to get rid of late conversions from lists to tuples for compile time speed.

**Comment by kayhayen** [comment] 2022-12-31 07:24
I will first want to see how this works out before adding the backport support, this usually only involves some abstractions, but I only want to do it with proven code.

**Comment by kayhayen** [comment] 2022-12-31 09:34
Looking good, so factory ought to now work for the code you quoted. The deprecated forms where args are given, are not yet working, but they must be more rare, and will be added too in time.

**Comment by kayhayen** [comment] 2023-01-01 13:38
This is now on the develop branch and part of the latest pre-release. It also covers many variations of both cases, even down to Python2 variants. Arguments ought to work, since some versions behave like others with arguments, but I didn't care to check that now. For me this is done. Will be part of 1.4 release.

**Comment by kayhayen** [comment] 2023-03-11 17:49
This is part of the stable release 1.5 that I just made.

**Closed by kayhayen** 2023-03-11 17:49 UTC
Labels: enhancement, develop
