### ISSUE TITLE
--macos-create-app-bundle renders the app without a dock icon or menubar

### ISSUE THREAD

**Issue by random-developer** [Nuitka/Nuitka#1838] opened 2022-10-11 22:48 UTC
Running `Nuitka==1.1.3` on macOS 12.5.1, against a PySide6 app, I'm seeing a problem when using --macos-create-app-bundle.

```
% cat test.py
import sys
from PySide6 import QtWidgets

if __name__ == '__main__':
    app = QtWidgets.QApplication(sys.argv)

    w = QtWidgets.QWidget()
    w.resize(200, 200)
    w.setWindowTitle('Hello World')
    w.show()

    app.exec()
```

When running the above program through python3, things work exactly as expected.

If I compile with `python3 -m nuitka --standalone --plugin-enable=pyside6 test.py` and then run `test.dist/test`, things still work correctly.

The problem is that if I compile with `python3 -m nuitka --standalone --plugin-enable=pyside6 --macos-create-app-bundle test.py`, when I run the resulting `test.app` (`open test.app`, or `./test.app/Contents/MacOS/test`, my application runs but there is no icon on the dock and there is no menu bar.

```
% python -m nuitka --version
1.1.3
Commercial: None
Python: 3.10.4 (v3.10.4:9d38120e33, Mar 23 2022, 17:29:05) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: Unknown
Executable: /Users/randomdeveloper/.virtualenvs/python-3.10.4-pyside6/bin/python
OS: Darwin
Arch: arm64
```

```
% pip3 freeze
altgraph==0.17.3
certifi==2021.10.8
charset-normalizer==2.1.1
decorator==5.1.1
greenlet==1.1.3
gssapi==1.8.1
idna==3.4
macholib==1.16.2
modulegraph==0.19.3
Nuitka==1.1.3
ordered-set==4.1.0
packaging==21.3
ply==3.11
Pygments==2.13.0
pyinstaller-hooks-contrib==2022.10
pyparsing==3.0.9
Pypubsub==4.0.3
PySide6==6.3.2
PySide6-Addons==6.3.2
PySide6-Essentials==6.3.2
pytz==2022.4
requests==2.28.1
requests-negotiate==1.5
shiboken6==6.3.2
sip==6.7.1
SQLAlchemy==1.4.41
toml==0.10.2
urllib3==1.26.12
www-authenticate==0.9.2
```

**Comment by kayhayen** [comment] 2022-10-12 07:19
Ok, thanks for the report, this is probably a setting, that relates to command line usage. This should have warning you to disable the console:

```
- module-name: 'PySide6'
  options:
    checks:
      - description: 'PySide6 is a GUI framework'
        console: 'recommend'
```

Did you choose to ignore that warning? We can also add missing dock and menubar, to the list. The thing is, PySide6 could e.g. only be used to do network stuff in a program, where this would be fine.

**Comment by roniemartinez** [comment] 2022-10-12 07:27
For MacOS app bundle, you need a separate icon.

```--macos-app-icon=con.png```

> there is no menu bar.

AFAIK, there is no menu bar by default (QtCreator creates this for you if you are coming from C++). You have to add it on your own.
`QWidget` also does not have a menu bar. You have to use `QMainWindow` but you still have to explicitly add the menu bar.

As I see it, these are not issues related to Nuitka. Also using `pyside6` here.

**Comment by kayhayen** [comment] 2022-10-12 09:47
With pure Python however, the Python icon is used. I am not sure if it was ever a good idea to use the Python icon with old style onefile on Linux by default. This must be Python binary doing it. Also has a menu bar, even if a very basic one.

But menu bar is present and same as for Python by default, and an icon is present too, and for app bundle menu is also present, but icon is empty, and that's because I did not give the icon, if I give it, it's in the dock.

So, I guess when disabling the console, which remove the default for console programs, we need to also suggest the user to provide the icon strongly. 

Also I was able to execute with `--disable-console` which has no effect unless it is a bundle, there should be an error check there, that I recall adding, but it seems it became ineffective.

**Comment by kayhayen** [comment] 2022-10-12 10:10
So I added the error exit for disabling console without app mode, and the warning for not having an icon. I do not get the menu bar topic, it's absolutely compatible in that regard. I might include these changes in hotfixes, because why not, it's small only.

**Comment by random-developer** [comment] 2022-10-12 14:34
> Ok, thanks for the report, this is probably a setting, that relates to command line usage. This should have warning you to disable the console:
> ...
> Did you choose to ignore that warning? We can also add missing dock and menubar, to the list. The thing is, PySide6 could e.g. only be used to do network stuff in a program, where this would be fine.

I just double checked; no warning there (for that; I do have red font warnings about anti-bloat removals and that I don't have cache).

> So I added the error exit for disabling console without app mode, and the warning for not having an icon.
Thanks!

Adding `--disable-console` fixed the problem!

**Comment by kayhayen** [comment] 2022-10-12 15:31
Damn, that is a regression. I need to repair that warning to be shown too, it is intended to keep you out of this trap.

**Comment by kayhayen** [comment] 2022-10-13 10:07
That last thing is part of the current hotfix, the other warnings, I will let them slip to 1.2 likely. I am closing them, because it turns out to be largely user error.

**Closed by kayhayen** 2022-10-13 10:07 UTC
Labels: enhancement, factory
