### ISSUE TITLE
wxpython Mac Cannot run after compilation

### ISSUE THREAD

**Issue by duolabmeng6** [Nuitka/Nuitka#1136] opened 2021-06-21 04:14 UTC
```
This program needs access to the screen. Please run with a
Framework build of python, and only when you are logged in
on the main display of your Mac.

```

请问一下如何解决这个问题

How to solve this problem

**Comment by kayhayen** [comment] 2021-06-21 09:41
Duplicate of #799

**Closed by kayhayen** 2021-06-21 09:41 UTC
Labels: duplicate
