### ISSUE TITLE
Windows: Created binaries do not contain a manifest file that allows Windows API to work properly

### ISSUE THREAD

**Issue by chianjin** [Nuitka/Nuitka#1346] opened 2021-12-28 13:17 UTC
I'm trying use ctypes to get windows ScaleFactor using the code as below:

```
# main.py
import ctypes
scale_factor = ctypes.windll.shcore.GetScaleFactorForDevice(0)
print(scale_factor)

```
run it as `python main.py`, it print 125
if compile it with `nuitka --mingw64 main.py` with nuitka auto download gcc, and then run main.exe, it print 100.
if compile it with msys2 64bits mingw64 gcc, it print 125 the same as run the script with python.

I alse test it, with python 3.8, 3.9, 3.10 on Windows 10 and 11, using a clean virtualenv only installing nuitka with `pip`.  The same as above.

```
> python -m nuitka --version
0.6.18.5
Commercial: None
Python: 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: D:\GitHub\pTest\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
> python -m pip freeze
Nuitka==0.6.18.5
```

The gcc in msys2 64bits is "mingw-w64-x86_64-gcc 11.2.0-2"
```
$ which gcc
/mingw64/bin/gcc
$ gcc --version
gcc.exe (Rev2, Built by MSYS2 project) 11.2.0
```

The gcc auto downloaded by nuitka is "winlibs-x86_64-posix-seh-gcc-11.2.0-llvm-12.0.1-mingw-w64-9.0.0-r1.zip"
```
>gcc --version
gcc (MinGW-W64 x86_64-posix-seh, built by Brecht Sanders) 11.2.0

```

I think it may be the gcc auto downloaded having some bugs.

**Comment by kayhayen** [comment] 2021-12-29 16:50
This is hinting at something related to target platform. It will be inconvinient, since you won't see the output, but I guess disabling the window console may help. Can you try that out, writing the output to a file instead, so you can still see it.

**Comment by chianjin** [comment] 2021-12-30 15:21
> This is hinting at something related to target platform. It will be inconvinient, since you won't see the output, but I guess disabling the window console may help. Can you try that out, writing the output to a file instead, so you can still see it.

With disabled windows console, still the same resulte.

**Comment by kayhayen** [comment] 2021-12-30 17:56
I managed to reproduce this, I am adding tracing as to what DLL is getting used, this is very strange.

**Comment by kayhayen** [comment] 2021-12-30 18:07
I am kind of suspecting that this is because Nuitka by default doesn't require very high Windows API level, and has a workaround to make MinGW64 work with Python headers at all. That may not be needed or healthy at all with newer Python. I need to find that one definition.

**Comment by kayhayen** [comment] 2021-12-30 18:09
```
    # The 32 bits MinGW does not default for API level properly, so help it.
    if env.mingw_mode:
        # Windows XP
        env.Append(CPPDEFINES=["_WIN32_WINNT=0x0501"])
```

This is very old stuff.

**Comment by kayhayen** [comment] 2021-12-30 18:32
Removing it doesn't change anything, nor does another MinGW related define. I checked with https://github.com/petoolse/petools/releases and the PE headers are identical for targeted versions. That was my suspect, that somehow there could be a difference generated this way.

I managed to reproduce the issue with both MSVC and winlibs gcc on CPython though, so we are kind of on the wrong track entirely maybe, esp the MSVC feels more trustworthy in terms of correctness for these things, doesn't it. But all that's happening is a ctypes call into a DLL, and that's not done in compiled code really.

**Comment by kayhayen** [comment] 2021-12-30 19:18
Ok, I got this, it seems there is a manifest in the created binary from MSYS2 gcc, and it contains this:

```
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <!--The ID below indicates application support for Windows Vista -->
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
      <!--The ID below indicates application support for Windows 7 -->
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
      <!--The ID below indicates application support for Windows 8 -->
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <!--The ID below indicates application support for Windows 8.1 -->
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <!--The ID below indicates application support for Windows 10 -->
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    </application>
  </compatibility>
```

The MSVC adds nothing like that by default, nor does winlibs gcc, and how would they know. That obviously depends on the API you use, which in MSYS2 is more controlled than elsewhere maybe.

**Comment by kayhayen** [comment] 2021-12-30 19:25
So, what I can do, and should do maybe, is to query the Windows release, and handle Windows 7 and Windows 10, and MSYS2 gets Windows 7 set there. However, funnily CPython 3.9 and even CPython 3.10 which explicitely removed the Windows 7 code from its core, claim the same. Without the comments btw, every MSYS2 is larger than necessary due to them. But so is the whitespace...

**Comment by kayhayen** [comment] 2021-12-30 19:28
I didn't mention it, but with that it works fine.

**Comment by kayhayen** [comment] 2021-12-30 19:48
Python2 is not affected, I guess it would be an incompatible change to make it work there.

**Comment by kayhayen** [comment] 2021-12-30 19:54
This is now on factory branch and should be part of 0.6.19 which is going to be released soon, https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment] 2021-12-30 19:55
For bonus points, I implemented a dedenting function, removing whitespace from the XML. Now it's not only added when UAC modes are needed, but always, making binaries a bit larger.

**Comment by kayhayen** [comment] 2022-01-05 12:02
This now part of the current pre-release and will be part of 0.6.19 which should arrive shortly.

**Comment by kayhayen** [comment] 2022-01-09 16:11
Part of the 0.6.19 release I just made.

**Closed by kayhayen** 2022-01-09 16:11 UTC
Labels: bug, develop
