### ISSUE TITLE
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

### ISSUE THREAD

**Issue by botspot3d** [Nuitka/Nuitka#1407] opened 2022-02-03 14:58 UTC
Windows 10
Python 3.9.5 installed by setup programme
numpy 1.22.1 installed by pip3
opencv-python-headless 4.5.5.62 installed by pip3
Nuitka 0.6.19.4 installed by pip3

Test case:
```
import cv2
if len(sys.argv) > 1:
	src = sys.argv[1]
	dst = os.path.splitext(src)[0] + '-copy' + os.path.splitext(src)[1]
	img = imread(src)
	if img: imwrite(dst, img)
```

Built command:
```
D:\cv2test>python3 -m nuitka --standalone --plugin-enable=numpy --python-flag=no_site cv2test.py
```

The issue #1275 still appears even after a stanza for opencv-python-headless analogous to the opencv stanza has been added to `data-files.yml`:
```
D:\cv2test>cv2test.dist\cv2test.exe test.jpg
Traceback (most recent call last):
  File "D:\cv2test\cv2test.dist\cv2test.py", line 1, in <module>
  File "D:\cv2test\cv2test.dist\cv2\__init__.py", line 190, in <module cv2>
  File "D:\cv2test\cv2test.dist\cv2\__init__.py", line 120, in bootstrap
  File "D:\cv2test\cv2test.dist\cv2\__init__.py", line 118, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.
```

Copying `config.py` and `config-3.py` to `cv2test.dist\cv2` or adding the option `--include-data-file="C:\Program Files\Python39\Lib\site-packages\cv2\config*.py"=cv2/` as proposed in [comment to #1275](https://github.com/Nuitka/Nuitka/issues/1275#issuecomment-983200547) results in:
```
D:\cv2test>cv2test.dist\cv2test.exe test.jpg
Traceback (most recent call last):
  File "D:\cv2test\cv2test.dist\cv2test.py", line 1, in <module>
  File "D:\cv2test\cv2test.dist\cv2\__init__.py", line 190, in <module cv2>
  File "D:\cv2test\cv2test.dist\cv2\__init__.py", line 162, in bootstrap
  File "D:\cv2test\cv2test.dist\cv2\__init__.py", line 190, in <module cv2>
  File "D:\cv2test\cv2test.dist\cv2\__init__.py", line 85, in bootstrap
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.
```

**Comment by kayhayen** [comment] 2022-02-04 11:39
As an aside, nuitka --version is going to output more precise information for some of these things.

This is a duplicate of #1366 that is not yet solved.

**Comment by projectintel-anon** [comment] 2022-02-05 02:40
I hate to be an annoyance, but to add to this issue (which I also got the exact same error for): When compiling a .py with CV2 and PySide6 **together** as a `--onefile`, it results in an infinite progress bar at 
`Nuitka-Scons:INFO:` Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
Backend C: 100% 842/842`

Command: `nuitka --onefile main.py --follow-imports --plugin-enable=pyside6 --plugin-enable=numpy --nofollow-import-to=PyQt5,PySide2 --windows-disable-console --windows-icon-from-ico=icon.ico`

**Comment by kayhayen** [comment] 2022-02-05 11:00
The develop version is making the linking stage explicit. Doing LTO on ever large programs takes ever longer. You might want to try e.g. --lto=no or a capable compiler, e.g. MSVC, since gcc on Windows is not too good at it yet.

**Comment by botspot3d** [comment] 2022-02-07 09:13
Compiling with Nuika and MinGW does fine. It may take some extra minutes but it comes to an end within reasonable time.

Nethertheless it may can give a clue why openCV's initialization routine detects an recursion.

```
def bootstrap():
    import sys

    import copy
    save_sys_path = copy.copy(sys.path)

    if hasattr(sys, 'OpenCV_LOADER'):
        print(sys.path)
        raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')

(snip)
```

**Comment by kayhayen** [comment] 2022-02-07 12:41
The code of `openCV` is very messy with how it does load some modules. This will have to be resolved with a lot of debugging time to be spent, which is why it's not being done right away. Currently, no customer with priority has this requested. Eventually I might do it, but at this time it looked very time-consuming, and there is more important stuff to do. It is masquerading some packages behind others it seems. Were this to be resolved, we might be able to do something about it.

The bug of which this is a duplicate is therefore on delayed and funding wanted. I will keep you informed. Hopefully later there will be time for this kind of (crazy) manual import messing.

**Comment by botspot3d** [comment] 2022-02-07 12:49
You're right. It seems the openCV python wrapper uses self-modifying code. But don't mind. It isn't urgent anymore. I've switched to C++.

**Comment by projectintel-anon** [comment] 2022-02-07 16:08
Time to start a GoFundMe for priority

**Comment by rikuru-to865** [comment] 2022-02-14 13:26
Is there a solution?

**Comment by kayhayen** [comment] 2022-02-14 18:07
Closing, as this is getting comments while being only a duplicate of #1366

**Closed by kayhayen** 2022-02-14 18:07 UTC
Labels: duplicate
