### ISSUE TITLE
Compilng with MSVC Build Tools 14.41.34120, too much warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char' is occurred. in Windows.

### ISSUE THREAD

**Issue by Choonholic** [Nuitka/Nuitka#3068] opened 2024-08-14 12:22 UTC
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.
```
2.4.7
Commercial: None
Python: 3.12.4 | packaged by Anaconda, Inc. | (main, Jun 18 2024, 15:03:56) [MSC v.1929 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\ProgramData\anaconda3\envs\nlive\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).
```

- How did you install Nuitka and Python
Because nuitka of PyPI does not updated from 2.4.5, installed like below:
```
python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/main.zip"
```

- The specific PyPI names and versions
```
Package            Version     Location                                                           Installer
------------------ ----------- ------------------------------------------------------------------ ---------
attrs              23.2.0      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
certifi            2024.7.4    C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
cffi               1.16.0      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
charset-normalizer 3.3.2       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
exceptiongroup     1.2.1       C:\Users\Choonholic\AppData\Roaming\Python\Python312\site-packages pip
ffmpeg-python      0.2.0       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
future             1.0.0       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
h11                0.14.0      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
idna               3.7         C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
isodate            0.6.1       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
lxml               5.2.2       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
Nuitka             2.4.7       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
ordered-set        4.1.0       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
outcome            1.3.0.post0 C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
packaging          24.1        C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
pip                24.2        C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              conda
pycountry          24.6.1      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
pycparser          2.22        C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
pycryptodome       3.20.0      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
PySocks            1.7.1       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
python-dateutil    2.9.0.post0 C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
requests           2.32.3      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
setuptools         72.1.0      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages
six                1.16.0      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
sniffio            1.3.1       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
sortedcontainers   2.4.0       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
streamlink         6.9.0       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
trio               0.26.0      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
trio-websocket     0.11.1      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
typing_extensions  4.12.2      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
urllib3            2.2.2       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
websocket-client   1.8.0       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
wheel              0.43.0      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages
wsproto            1.2.0       C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
zstandard          0.23.0      C:\ProgramData\anaconda3\envs\nlive\Lib\site-packages              pip
```

- Many times when you get an error from Nuitka, your setup may be special
Everytime

- Also supply a Short, Self Contained, Correct, Example
Today, I've updated Visual Studio BuildTools 2022 to 17.11.0 by winget (Previously 17.10.0)
```
Name                          Id                                     Version       Source
------------------------------------------------------------------------------------------
Visual Studio BuildTools 2022 Microsoft.VisualStudio.2022.BuildTools 17.11.0       winget
```

Then too much warnings displayed as follows:
```
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Unexpected output from this command:
<clcache> /Fo__constants.obj /c "__constants.c" /nologo /std:c11 /wd5105 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=155 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\PROGRA~3\ANACON~1\envs\nadlr\include /I. /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\include /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\static_src /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
Backend C: 3.1%|▊                        | 3/96Unexpected output from this command:
<clcache> /Fo__helpers.obj /c "__helpers.c" /nologo /std:c11 /wd5105 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=155 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\PROGRA~3\ANACON~1\envs\nadlr\include /I. /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\include /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\static_src /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
Unexpected output from this command:
<clcache> /Fomodule.aiohappyeyeballs.obj /c "module.aiohappyeyeballs.c" /nologo /std:c11 /wd5105 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=155 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\PROGRA~3\ANACON~1\envs\nadlr\include /I. /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\include /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\static_src /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
Unexpected output from this command:
<clcache> /Fomodule.adlrversion.obj /c "module.adlrversion.c" /nologo /std:c11 /wd5105 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=155 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\PROGRA~3\ANACON~1\envs\nadlr\include /I. /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\include /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\static_src /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
Unexpected output from this command:
<clcache> /Fomodule.__parents_main__.obj /c "module.__parents_main__.c" /nologo /std:c11 /wd5105 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=155 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\PROGRA~3\ANACON~1\envs\nadlr\include /I. /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\include /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\static_src /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
Unexpected output from this command:
<clcache> /Fomodule.__main__.obj /c "module.__main__.c" /nologo /std:c11 /wd5105 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=155 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\PROGRA~3\ANACON~1\envs\nadlr\include /I. /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\include /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\static_src /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
Unexpected output from this command:
<clcache> /Fomodule.aiohappyeyeballs.types.obj /c "module.aiohappyeyeballs.types.c" /nologo /std:c11 /wd5105 /Ox /GF /Gy /EHsc /J /Gd /bigobj /MT /D__NUITKA_NO_ASSERT__ /D_NUITKA_STANDALONE /D_NUITKA_ONEFILE_MODE /D_NUITKA_ONEFILE_TEMP_BOOL /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=155 /D_NUITKA_EXE /D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\zlib /IC:\PROGRA~3\ANACON~1\envs\nadlr\include /I. /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\include /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\static_src /IC:\PROGRA~3\ANACON~1\envs\nadlr\Lib\SITE-P~1\nuitka\build\inline_copy\libbacktrace
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1008): warning C4391: 'char _sat_add_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.41.34120\include\intrin.h(1016): warning C4391: 'char _sat_sub_i8(char,char)': incorrect return type for intrinsic function, expected 'unsigned char'
......
```
 
- Provide in your issue the Nuitka options used
```
python -m nuitka --onefile --msvc=latest --output-filename=product.exe --remove-output product.py

**Comment by kayhayen** [comment] 2024-08-15 05:52
Due to licensing constraints of what you can compile with Buildtools, I don't normally look into it. This looks like an issue with the Windows SDK. There are good reasons, to not support arbitrary compiler setups. If you use --show-scons you can identify the Windows SDK used.

**Comment by Choonholic** [comment] 2024-08-15 08:34
I've tested with some configurations:

Build Tools 17.11.0 (MSVC 14.41) With SDK 22000: SAME
Build Tools 17.11.0 (MSVC 14.41) With SDK 22621: SAME
Build Tools 17.11.0 (MSVC 14.41) With SDK 26100: SAME

**Comment by HAL9000COM** [comment] 2024-08-15 11:57
Similar issue here.  
Environment:
```
2.4.5
Commercial: None
Python: 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Luke\Documents\PicFinder\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Seems related to MSVC version, build with following environment does not have this issue.
```
2.4.5
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\HAL\Documents\PicFinder\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).
```

**Comment by Choonholic** [comment] 2024-08-16 08:16
@HAL9000COM, I agree with you that the issue is caused by a compiler update from Microsoft. 

@kayhayen, I'm going to wait it out, because even though I'm getting a lot of messages, the compilation itself isn't broken, and it's possible that a future update will fix it.

**Comment by kayhayen** [comment] 2024-08-16 14:38
The Windows SDK itself not being the issue is strange, so I updated my Visual Studion 2022 and indeed, I get the same error..

So ignoring that warning seems to be needed, from the text it seems they are talking to themselves about requirements for compiler intrinsic functions. Probably because we use C11 which must be rare.

**Comment by kayhayen** [comment] 2024-08-16 14:38
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by Choonholic** [comment] 2024-08-16 16:34
@kayhayen, With factory version `2.5rc5` with `/wd4391` options, compilation stage passed without any warnings.

Thank you.

**Comment by kayhayen** [comment] 2024-09-28 09:14
This is part of the 2.4.8 release for a while already.

**Closed by kayhayen** 2024-09-28 09:14 UTC
Labels: bug, factory
