### ISSUE TITLE
pyqt5 fails with matplotlib.  KeyError: 'backend_fallback'

### ISSUE THREAD

**Issue by wisdom-2021** [Nuitka/Nuitka#2533] opened 2023-11-07 02:20 UTC
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

when my code contains the above two sentences，build ok,  but runtime error.

### Traceback
Traceback (most recent call last):
  File "/Users/zhangsan/test/out/zhangsantest.dist/zhangsantest.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/zhangsan/test/out/zhangsantest.dist/test.py", line 392, in <module test>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/zhangsan/test/out/zhangsantest.dist/testFigure.py", line 2, in <module testFigure>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/zhangsan/test/out/zhangsantest.dist/matplotlib/__init__.py", line 982, in <module matplotlib>
  File "/Users/zhangsan/test/out/zhangsantest.dist/matplotlib/__init__.py", line 762, in __getitem__
  File "/Users/zhangsan/test/out/zhangsantest.dist/matplotlib/__init__.py", line 709, in _get
KeyError: 'backend_fallback'

### Build environment
nuitka: 1.8.5
Commercial: None
Python: 3.10.0 (v3.10.0:b494f5935c, Oct  4 2021, 14:59:20) [Clang 12.0.5 (clang-1205.0.22.11)]
Flavor: CPython Official
Executable: /Users/zhangsan/ENV310/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).

PyQt5==5.15.9
numpy==1.26.1
matplotlib==3.8.0
matplotlib-inline==0.1.6

### Compile command
python -m nuitka --standalone --onefile --enable-plugin=pyqt5  --output-dir=out --disable-console --macos-create-app-bundle zhangsantest.py

**Comment by wisdom-2021** [comment] 2023-11-07 02:24
The python310 environment is created using virtualenv

**Comment by wisdom-2021** [comment] 2023-11-07 11:42
> I cannot even run this combination on my machine anymore, PyQt5 fails to load inside of matplotlib. I am also not sure your callstack matches your example for real.

Here's a simple example：Once import the matplotlib, although we did not use it. 
build ok, but runtime error

from PyQt5.QtWidgets import QWidget, QProgressBar, QApplication
import sys
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.figure import Figure

class Example(QWidget):
    def __init__(self):
        super().__init__()
        self.pbar = QProgressBar(self)
        self.pbar.setGeometry(30, 40, 200, 25)
        self.setGeometry(300, 300, 280, 170)
        self.setWindowTitle('QProgressBar')
        self.show()

if __name__ == '__main__':
    app = QApplication(sys.argv)
    ex = Example()
    sys.exit(app.exec_())

Traceback (most recent call last):
  File "/Users/zhangsan/test/out_tmp/tmp.dist/tmp.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/zhangsan/test/out_tmp/tmp.dist/matplotlib/__init__.py", line 895, in <module matplotlib>
  File "/Users/zhangsan/test/out_tmp/tmp.dist/matplotlib/__init__.py", line 674, in __getitem__
KeyError: 'backend_fallback'
Deleting expired sessions...none found.

**Comment by wisdom-2021** [comment] 2023-11-07 11:45
`Traceback (most recent call last):
  File "/Users/zhangsan/test/out_tmp/tmp.dist/tmp.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/Users/zhangsan/test/out_tmp/tmp.dist/matplotlib/__init__.py", line 895, in <module matplotlib>
  File "/Users/zhangsan/test/out_tmp/tmp.dist/matplotlib/__init__.py", line 674, in __getitem__
KeyError: 'backend_fallback'
Deleting expired sessions...none found.`

**Comment by kayhayen** [comment] 2023-11-07 13:20
Like I said, I cannot pip install PyQt5 and get matplotlib to accept it on my arm machine, and trying to lookup the lines of code in matplotlib doesn't work either, they are also different from what you originally posted.

**Comment by kayhayen** [comment] 2023-11-07 13:25
The error should trigger for you with only doing `import matplotlib` which should be unusual. I assume something about the config file handling goes wrong. You might want to try the current `develop` branch. I improved some things there and I would like to be sure it's not already avoided.

**Comment by wisdom-2021** [comment] 2023-11-08 06:24
> The error should trigger for you with only doing `import matplotlib` which should be unusual. I assume something about the config file handling goes wrong. You might want to try the current `develop` branch. I improved some things there and I would like to be sure it's not already avoided.

The same problem happened when I used the current `develop` branch.
nuitka: 1.9rc6

I found that the backend of matplotlibrc in the generated dist directory is TkAgg. Qt5Agg is set before buildling. Why TkAgg here?  Is there a problem

**Comment by kayhayen** [comment] 2023-11-08 11:44
What do you mean with "is set before building", how do you do it exactly, in the config file, via environment, or what

**Comment by wisdom-2021** [comment] 2023-11-08 11:55
> What do you mean with "is set before building", how do you do it exactly, in the config file, via environment, or what

in the config file, via environment. I have tried both ways.

**Comment by kayhayen** [comment] 2023-11-08 15:40
Just because I am not an expert for every PyPI package, or know if you made a mistake, I would appreciate to know what you put exactly, so I don't have to figure out myself.

**Comment by wisdom-2021** [comment] 2023-11-09 01:55
Sorry, I did this by setting MPLBACKEND=Qt5Agg via environment，and I also tried to add `backend:Qt5Agg` in the matplotlibrc file, but the same problem still happened.
The above is my attempt to solve the problem, If I don't try, the same error also happend by using the default configuration.I don't know why I get `KeyError: 'backend_fallback'` just for importing the matplotlib.

**Comment by kayhayen** [comment] 2023-11-10 07:59
I have reproduced this actually. 

> Nuitka-Plugins:INFO: matplotlib: Using as per 'MPLBACKEND' environment variable backend 'TkAgg'.

but then

`
./Mini.dist/Mini.bin 
agg
`

So, it seems the code is trying to compile time detect, if `MPLBACKEND` etc. variables are needed, or if the config file manipulation would be sufficient. That's not working for 3.8.0 at least, and instead than patching this up, we should just make it unconditional, there is no point in being optimal about that, we can just set `MATPLOTLIBDATA` , `MATPLOTLIBRC` , and `MPLBACKEND` and `QT_API` no matter what.

Only `MPLBACKEND` has a compile time effect on what will be 1.9 though, the config file is found by code that will be impacted by `MATPLOTLIBDATA`  and that should have worked. I have yet to check if updating the config file really has no impact.

**Comment by kayhayen** [comment] 2023-11-11 11:19
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Closed** 2023-11-23 08:26 UTC
Labels: bug, factory
