### ISSUE TITLE
Memory Leak: Issues with Nuitka in Conjunction with Textualize/Rich

### ISSUE THREAD

**Issue by kaidaniel82** [Nuitka/Nuitka#2593] opened 2023-12-07 08:45 UTC
**Problem Description:**
A memory leak occurs when using the Rich module in a terminal dashboard on MacOS 14.1.2 with an Apple M1 Pro chip. The memory usage continuously increases, scaling with the complexity of the user interface. This issue specifically arises **only** when the code is compiled using Nuitka.

**Steps to Reproduce:**
- Use the second example from the Rich documentation page: [Rich Live Example](https://rich.readthedocs.io/en/latest/live.html).
- Compile this example using the command: `python -m nuitka --onefile --output-dir="./V1" --remove-output test.py`
- Run the compiled program. 

**Expected vs. Actual Behavior:**
- **Expected:** Memory usage should remain stable.
- **Observed:** Memory usage continuously increases the longer the program runs.

**Environment Information:**
- Operating System: MacOS 14.1.2
- Chip: Apple M1 Pro
- Python Version: 3.11
- Libraries Used: rich==13.7.0, nuitka==1.9.3

Attached Code:
```
import random
import time
from rich.live import Live
from rich.table import Table

def generate_table() -> Table:
    """Make a new table."""
    table = Table()
    table.add_column("ID")
    table.add_column("Value")
    table.add_column("Status")

    for row in range(random.randint(2, 50)):
        value = random.random() * 100
        table.add_row(f"{row}", f"{value:3.2f}", "[red]ERROR" if value < 50 else "[green]SUCCESS")
    return table

with Live(generate_table(), refresh_per_second=10) as live:
    for _ in range(4000):
        time.sleep(0.4)
        live.update(generate_table())
```

**Comment by kayhayen** [comment] 2023-12-07 09:34
Interesting, these all look like things we should have covered with tests to not leak, but I will look at it. I don't know how `Live` works, I would of course want to first make sure the `generate_table` is not to blame.

**Comment by kayhayen** [comment] 2023-12-07 10:33
So, I made sure that with reference count based test, generate_table is not to blame.

```
import random
import time
from rich.live import Live
from rich.table import Table

def generate_table() -> Table:
    """Make a new table."""
    table = Table()
    table.add_column("ID")
    table.add_column("Value")
    table.add_column("Status")

    for row in range(random.randint(2, 50)):
        value = random.random() * 100
        table.add_row(f"{row}", f"{value:3.2f}", "[red]ERROR" if value < 50 else "[green]SUCCESS")
    return table

# with Live(generate_table(), refresh_per_second=10) as live:
#     for _ in range(4000):
#         time.sleep(0.4)
#         live.update(generate_table())

from nuitka.tools.testing.Common import checkReferenceCount

checkReferenceCount(generate_table)
```

Neither purely the module, neither with --follow-import-to=rich nor with --standalone did this cause any issues, output is PASSED, which is pretty neat validation generally. So the issue may well be with `rich.live` which seems to do some very absurd stunts, which may or may not be good. Need to try and make this less interactive. Buffers, etc. are of course going to be appearing as memory leaks when they are not, so it's not clear how to see it. I wonder how many threads to expect, maybe just a second one, shall see.

**Comment by kayhayen** [comment] 2023-12-08 10:25
I managed to track this down, with removing all rows, etc. to 10 empty compiled cells per column in the table. This is with a very manually edited version of `rich` where I tried to get rid of as much code as possible. Not sure when which function leaks them, trying to find out what holds a reference to them.

**Comment by kayhayen** [comment] 2023-12-08 15:16
I have trimmed this down, adding a bunch of additional debugging tools we previously had for functions to generators and compiled cells in the process. The problem is that a cell variable is optimized away for an early return in that generator, and then the cell storage is already allocated, but never freed in that branch, which seems to happen a lot. On factory this is worked around for `rich` and show not happen anymore and this will also come to a hotfix 1.9.4 soon. The real fix is more involved and will be 2.0 or 2.1 material probably.

**Comment by kayhayen** [comment] 2023-12-08 15:17
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kaidaniel82** [comment] 2023-12-08 19:58
The HotFix seems to work!

**Comment by kayhayen** [comment] 2023-12-11 08:21
Part of the 1.9.4 hotfix release.

**Closed by kayhayen** 2023-12-11 08:21 UTC
Labels: bug, factory
