### ISSUE TITLE
FATAL: Error, failed to find path @rpath/QtQuickEffects.framework/Versions/A/QtQuickEffects

### ISSUE THREAD

**Issue by dryarullin** [Nuitka/Nuitka#2215] opened 2023-05-03 15:24 UTC
**Error description:**

FATAL: Error, failed to find path @rpath/QtQuickEffects.framework/Versions/A/QtQuickEffects (resolved DLL to /Users/dryarullin/miniconda3/envs/pyqt_new/lib/python3.11/site-packages/PySide6/Qt/qml/QtQuick/Effects/QtQuickEffects.framework/Versions/A/QtQuickEffects) for /Users/dryarullin/miniconda3/envs/pyqt_new/lib/python3.11/site-packages/PySide6/Qt/qml/QtQuick/Effects/libeffectsplugin.dylib, please report the bug.

**nuitka3 --version**

1.5.7
Commercial: None
Python: 3.11.0 (main, Mar 1 2023, 12:49:28) [Clang 14.0.6 ]
Flavor: Anaconda Python
Executable: /Users/dryarullin/miniconda3/envs/pyqt_new/bin/python
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).

pip freeze
PySide6==6.5.0

**Answer:**
libeffectsplugin.dylib refers to a non-existent QtQuickEffects. PySide6 is installed from pip without QtQuickEffects.framework. I don't know why it's not included in the package. Perhaps this is a developer error. How can I tell Nuitka not to use it? I tried to use `--noinclude-dlls=libpdfquickplugin.dylib` or `--noinclude-dlls=Pyside6/libpdfquickplugin.dylib` or `--noinclude-dlls=*QtQuickEffects*`, but no one helped me. I also don't use this plugin in my project, but it is still detected by Nuitka.

**Comment by dryarullin** [comment] 2023-05-03 17:49
**main.py:**

import sys

```
from PySide6.QtGui import QGuiApplication
from PySide6.QtQml import QQmlApplicationEngine


app = QGuiApplication(sys.argv)

engine = QQmlApplicationEngine()
engine.quit.connect(app.quit)
engine.load('main.qml')

sys.exit(app.exec())
```

**main.qml:**
```
import QtQuick
import QtQuick.Controls

ApplicationWindow {
    visible: true
    width: 600
    height: 500
    title: "HelloApp"

    Text {
        anchors.centerIn: parent
        text: "Hello World"
        font.pixelSize: 24
    }
}
```

**Command:**

`nuitka3 --standalone --follow-imports --plugin-enable=pyside6 --include-qt-plugins=qml  main.py`

**Comment by kayhayen** [comment] 2023-05-03 18:13
I wonder if this is related:

```
        if not os.path.exists(resolved_path):
            # TODO: Make this a plugin decision, to move this from here to PySide6 plugin:
            if os.path.basename(binary_filename) == "libqpdf.dylib":
                raise NuitkaForbiddenDLLEncounter(binary_filename, "pyside6")

            inclusion_logger.sysexit(
                "Error, failed to find path %s (resolved DLL to %s) for %s, please report the bug."
                % (path, resolved_path, binary_filename)
            )
```

They might have renamed the library, or another one like it got added. The DLL resolution mechanism has currently no mercy, it wants everything to exist that is referenced. That TODO would be nice to solve, then you could solve it through a plugin, for now I guess, you can change the code in Nuitka, and assuming that older PySide6 works, can you make a PR that tests for both filenames?

**Comment by kayhayen** [comment] 2023-05-04 08:15
Nuitka is not really built, you can run it from source directly. I think, the plugin code just disables the qpdf plugin, which cannot work. Similarily, I think the absence of the DLL would have to break the DLL. If it does not fine, we can ignore it in the second source location. I honestly forgot why there are two places. Not having a plugin that wouldn't work might be only an optimization. I think you only need to do it in the first one. I doubt that the whole of QtQuickEffects hard depends on a DLL not present, so maybe that is more optional there too.

Nuitka is strict with dependency existance checks. Not finding stuff is more often than not, a bug of Nuitka rather than an upstream. I can only guess what PySide commercial and PySide free are different. But maybe it is just omitting selected files in packages, and that is why that happens for them.

That said, QML worked, we might have to go back further, but there is little to gain. Lets make 6.5 work, hoping for your PR here.

**Comment by kayhayen** [comment] 2023-05-08 09:59
it seems, the section `import-hacks` is not found, which has to be a regression of some sorts.

**Comment by kayhayen** [comment] 2023-05-08 10:12
The config for the import-hacks accidentally shifted from `PySide6` to `PySide6.QtCore` but the later is not a package name, and therefore it never has any effect, although it's mostly for that module.

**Comment by kayhayen** [comment] 2023-05-08 13:47
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-05-08 13:48
I will make a hotfix out of this once I complete other things.

**Comment by kayhayen** [comment] 2023-05-30 09:54
This is probably due to other issues, that also got fixed. I am assuming it should be good now, since I had it working myself doing more PySide fixes.

This is part of the stable release 1.6 that I just made.

**Closed by kayhayen** 2023-05-30 09:54 UTC
Labels: bug, factory
