### ISSUE TITLE
Python3.7: Generator expressions falsely become 'asyncgen' and then are not iterable

### ISSUE THREAD

**Issue by demty** [Nuitka/Nuitka#631] opened 2020-02-27 19:48 UTC
Hello, encountered a bug related to a compiled_async_generator.
Example:

```python
# test.py
import asyncio


async def test():
    return (a for a in [1, 2, 3])


async def main_f():
    dict((x, x) for x in await test())

if __name__ == "__main__":
    asyncio.run(main_f())
```
```
python -m nuitka test.py
./test.bin 
```
Produces: 
```
Traceback (most recent call last):
  File "/home/demty/code/projects/huntflow/downloads/test.py", line 12, in <module>
    asyncio.run(main_f())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/demty/code/projects/huntflow/downloads/test.py", line 9, in main_f
    dict((x, x) for x in await test())
TypeError: 'compiled_async_generator' object is not iterable
```
Bug can be reproduced on nuitka versions 0.6.5, 0.6.7 installed via pip

------

Environment:

0.6.7
Python: 3.7.3 (default, Aug 20 2019, 17:04:43) 
Executable: /home/demty/code/venvs/huntflow/bin/python
OS: Linux
Arch: x86_64

P.S:
```python
import asyncio


async def test():
    return (a for a in [1, 2, 3])


async def main_f():
    {x: x for x in await test()}

if __name__ == "__main__":
    asyncio.run(main_f())
```
Works well.

**Comment by kayhayen** [comment] 2020-03-01 10:37
I reproduced the issue, hopefully it's very minor.

**Comment by kayhayen** [comment] 2020-03-01 10:43
So this is also triggering it:

```
async def main_f():
    x = tuple(x for x in await test())
```

This removes the unpacking of `x`, which was unclear to me, if it wasn't the trouble maker, but it is not it, but it seems this one does work:

```
async def main_f():
    x = [x for x in await test()]
    print(x)
```

So the generator expression inside of the tuple call seems to be different in terms of iterator taking that the list contraction, which could be about asyncgen vs. normal generator.

**Comment by kayhayen** [comment] 2020-03-01 10:59
I guess, that explains, why your dictionary contraction works as well, it's a normal contraction.

**Comment by kayhayen** [comment] 2020-03-01 17:52
So a fix for this is on the factory branch: http://nuitka.net/doc/factory.html

**Comment by chistyakov** [comment] 2020-04-21 18:19
Unfortunately, the problem is still reproducible.

Setup:
* the latest nuitka from the `factory` branch. Currently the latest commit is [`3f1a0de5b227ad93872ceca41633419bf0dd60f4` ](https://github.com/Nuitka/Nuitka/commit/3f1a0de5b227ad93872ceca41633419bf0dd60f4)
* the same code sample

```bash
➜  ~ mkvirtualenv --python=python3.7 nuitka_factory
Running virtualenv with interpreter /usr/bin/python3.7
Already using interpreter /usr/bin/python3.7
Using base prefix '/usr'
New python executable in /home/achistyakov/virtualenvs/nuitka_factory/bin/python3.7
Also creating executable in /home/achistyakov/virtualenvs/nuitka_factory/bin/python
Installing setuptools, pip, wheel...
done.
virtualenvwrapper.user_scripts creating /home/achistyakov/virtualenvs/nuitka_factory/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/achistyakov/virtualenvs/nuitka_factory/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/achistyakov/virtualenvs/nuitka_factory/bin/preactivate
virtualenvwrapper.user_scripts creating /home/achistyakov/virtualenvs/nuitka_factory/bin/postactivate
virtualenvwrapper.user_scripts creating /home/achistyakov/virtualenvs/nuitka_factory/bin/get_env_details

(nuitka_factory) ➜  ~ pip install https://github.com/Nuitka/Nuitka/archive/factory.zip
Collecting https://github.com/Nuitka/Nuitka/archive/factory.zip
  Using cached https://github.com/Nuitka/Nuitka/archive/factory.zip
Building wheels for collected packages: Nuitka
  Building wheel for Nuitka (setup.py) ... done
  Created wheel for Nuitka: filename=Nuitka-0.6.8rc5-py3-none-any.whl size=2255854 sha256=1d12ff234948cd26b009c30bcfd7158ec475c01f379c3f41791747a0a16af627
  Stored in directory: /tmp/pip-ephem-wheel-cache-wa9boxyb/wheels/de/46/13/fcfaa4724ae6fc8ff27c10cdcd5da079b0a20a219757a62b02
Successfully built Nuitka
Installing collected packages: Nuitka
Successfully installed Nuitka-0.6.8rc5

(nuitka_factory) ➜  ~ python -m nuitka --version
0.6.8rc5
Python: 3.7.7 (default, Mar 10 2020, 15:16:38) 
Executable: /home/achistyakov/virtualenvs/nuitka_factory/bin/python
OS: Linux
Arch: x86_64


(nuitka_factory) ➜  ~ cat nuitka_test.py 
# test.py
import asyncio


async def test():
    return (a for a in [1, 2, 3])


async def main_f():
    dict((x, x) for x in await test())

if __name__ == "__main__":
    asyncio.run(main_f())


(nuitka_factory) ➜  ~ python -m nuitka nuitka_test.py                      

(nuitka_factory) ➜  ~ ./nuitka_test.bin 
Traceback (most recent call last):
  File "/home/achistyakov/nuitka_test.py", line 13, in <module>
    asyncio.run(main_f())
  File "/usr/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/achistyakov/nuitka_test.py", line 10, in main_f
    dict((x, x) for x in await test())
TypeError: 'compiled_async_generator' object is not iterable

```

**Comment by kayhayen** [comment] 2020-05-01 10:01
I managed, to reproduce it, again, seems my fix addresses only part of the issue, I will look into this some more. I claim my fix improved something, but sometimes isolating an issue can make you oversee it's more than one thing.

**Comment by kayhayen** [comment] 2020-05-01 14:58
Ok, seems unnoticed of me there was `ast.comprehension` added and used in the parser, which I could swear wasn't the case before. There are lots of changes in code paths, where I put a "assert False" now, that doesn't trigger. Maybe because it's 3.7.3 being used. I will try and remove them though, and see what my CI has to say about that.

First my private one, these things might change a lot of stuff, this is always messy, but if I am right, maybe I patched up things in the wrong spot.

**Comment by kayhayen** [comment] 2020-05-01 15:34
Ah nah, that's two different things intended actually. One is to detect `def` to be `async def` for functions, where it can be caused by a genexp doing an await in its iterated, and only that, where something is an asyncgen if anything buts its iteration is async only. Just two different things that are both necessary.

**Comment by kayhayen** [comment] 2020-05-04 05:53
The fix for this is on factory, and will make it to the next release due to delay happening there.

**Comment by kayhayen** [comment] 2020-05-11 15:07
The release 0.6.8 was just made and contains the correction.

**Closed by kayhayen** 2020-05-11 15:07 UTC
Labels: bug, factory
