### ISSUE TITLE
Msys64 Nuitka FATAL: Error, cannot add data file with 'foldr1/folder2/text.txt' path, as 'contains illegal character '/''

### ISSUE THREAD

**Issue by noeldiviney** [Nuitka/Nuitka#3148] opened 2024-10-14 07:11 UTC
Issue Description, Examples and Instructions
  I am developing Python and wxPython Embedded Systems software for Windows 10  using the msys64 Environment.
  I would like to use Nuitka for the distribution of the software.
  I am experiencing the following problems in doing this 👎 
      1.    See Issue #3112 for the details.
             This example is a very minimal wxPython GUI "Hello World" called wxhello.py and demonstrated with wxhello.sh Bash Script
             This Issue is now fixed with nuitka version 2.5rc6.
             I would like to contribute it as  another Nuitka Test example

      2.    This New New issue which occurs when I include sub folders with the " --include-data-dir=folder1=foldr1/" option
             Nuitka is rejecting the forward clash folder separator "/" as illegal.
             My understanding of "msys64" Environment is that a Forward Slash "/" is the default and as such should be legal

  To demonstrate things I have created three Bash Scripts 👎 
      1    msys64setup.sh
            This Bash Script sets up a msys64 Development Environment and installs Nuitka 2.5rc6.
      2    wxhello.sh
            This Bash Script creates whhello.py test program, builds wxhello,exe and the executes wxhello.exe.
            It is using the command "nuitka --standalone wxhello.py --python-flag=-O"
            This should display a wxPython GUI  as Issue #3112 problem has been resolved. Thank you.
      3    include-data-dir.sh
            This Bash Script creates wxhello.py test program and tries to build wxhello.exe, but fails.
            It is using the command "nuitka --standalone --include-data-dir=folder1=folder1/ wxhello.py --python-flag=-O"

  The problem is demonstrate as follows :-
  extract the attached Nuitka.zip below to "C:\"
      This creates the following folder structure
       c:\Nuitka
           |____msys64nuitkatest
           |             |____folder1
           |             |          |____folder2
           |             |                     |____text.txt
           |             |____ include-data-dir.sh
           |             |____ wxhello.py
           |             |____wxhello.sh
           |____msys64setup
           |             |____msys64setup.sh
           |____NuitkaTest-Output-Log.txt

  Install msys64 as follows 👎 
       Goto https://www.msys2.org   and download the installer by clicking "msys2-x86_64-20240727.exe" link.
       Install "msys2-x86_64-20240727.exe" to C:\Nuitka\msys64.
       When the msys64 terminal runs execute the following Bash commands to initialise msys64👎 
           $ cd /c/Nuitka
           $ ./msys64setup/msys64setup.sh
       Restart the msys64 terminal by executing "c:\Nuitka\msys64\ucrt.exe"
       When the msys64 terminal runs execute the following Bash commands to setup the Environment and install Nuitka 2.5rc6 👎 
           $ cd /c/Nuitka
           $ ./msys64setup/msys64setup.sh

  All is now ready to do the Nuitka testing
       Test 1 create and execute wxhello.py by using the following commands 👎
              Nuitka commandline     "nuitka --standalone wxhello.py --python-flag=-O"
               Restart the msys64 terminal by executing "c:\Nuitka\msys64\ucrt.exe"
               When the msys64 terminal runs execute the following Bash commands to setup msys64 and install Nuitka 2.5rc6 👎 
               $ cd /c/Nuitka
               $ ./msys64nuitkatest/wxhello.sh
               A wxPython GUI should be successfully displayed.

       Test 2 create and execute wxhello.py by using the following commands 👎 
              Nuitka commandline    "nuitka --standalone --include-data-dir=folder1=folder1/ wxhello.py --python-flag=-O"
               Restart the msys64 terminal by executing "c:\Nuitka\msys64\ucrt.exe"
               When the msys64 terminal runs execute the following Bash commands to setup msys64 and install Nuitka 2.5rc6 👎 
               $ cd /c/Nuitka
               $ ./msys64nuitkatest/wxhello.sh
               A wxPython GUI should be successfully displayed.
    See    NuitkaTest-Output-Log.txt  whis my output log from using the attached  zipfile.    

  Attachment:-
  [Nuitka.zip](https://github.com/user-attachments/files/17359674/Nuitka.zip)

**Comment by kayhayen** [comment] 2024-10-14 08:19
Your understanding might be wrong, though. I think some MSYS2 programs might be doing stuff. Trailing slashes are not necessary as an aside. Using the MinGW variant of MSYS2, for Nuitka, this is Win32 and the forward slash is not allowed in file paths. However, I am not sure, if we don't normalize paths for other options, in which case forward slashes would work on other platforms. I am usually using git bash, which converts slashes for me, so some testing will be needed here.

**Comment by kayhayen** [comment] 2024-10-14 08:19
I am pretty sure this works: 

# nuitka-project: --include-data-file={MAIN_DIRECTORY}/example.avi=example.avi

**Comment by kayhayen** [comment] 2024-10-14 08:23
And this works with standard Python: 

> python3.12 bin/nuitka --standalone --include-data-dir=doc/=doc/ tests/basics/AssertsTest.py
> Nuitka-Options: Used command line options: --nofollow-imports --standalone --include-data-dir=doc/=doc/ tests/basics/AssertsTest.py

As can be seen, my git bash doesn't handle those trailing slashes as an error, so is this MSYS2 specific?

**Comment by kayhayen** [comment] 2024-10-14 08:26
Indeed it is, which is very strange, since that is the `Flavor: MSYS2 MinGW` according to my help output and honestly, I find that very confusing, how this could be handled differently somewhere. Does it patch normpath to not do things, I am confused now.

**Comment by kayhayen** [comment] 2024-10-14 08:31
So, I feel MSYS2 Python is doing it wrong, very wrong, to be incompatible with Windows there, apparently trying hard to avoid legal filenames to be used inside of Python.

**Comment by kayhayen** [comment] 2024-10-14 08:34
Should Nuitka really have a replacement for this:

```
    # This changes the '/' to '\' on Windows at least.
    value = os.path.normpath(value)
```

I don't know, but a couple of places in Nuitka expect normalized paths to be easy for comparison. So, e.g. this one:

```
def areSamePaths(path1, path2):
    """Decide if two paths the same.

    Args:
        path1: First path
        path2: Second path

    Returns:
        Boolean value indicating if the two paths point to the
        same path.

    Notes:

        Case differences ignored on platforms where that is the
        norm, and with it normalized, and turned absolute paths, and
        even short paths, it then becomes a mere string compare after that.
    """

    if path1 == path2:
        return True

    path1 = os.path.abspath(os.path.normpath(path1))
    path2 = os.path.abspath(os.path.normpath(path2))

    if os.path.exists(path1) and os.path.exists(path2):
        path1 = getExternalUsePath(path1)
        path2 = getExternalUsePath(path2)

    path1 = os.path.normcase(path1)
    path2 = os.path.normcase(path2)

    return path1 == path2
```

**Comment by kayhayen** [comment] 2024-10-14 08:43
Be my guest if anybody wants to create a `getNormPath` in `nuitka.utils.FileOperations` and make Nuitka code use in appropriate places. Until such time, with MSYS2, congratulations on using such a crappy platform. I will only consider it myself after a 2.5 release which is overdue, but still far away and 3.13 perfection.

**Comment by kayhayen** [comment] 2024-10-14 12:38
I added said function and make use of it in the places I noticed, but it would have to be done everywhere to be sure it doesn't cause other issues.

**Comment by kayhayen** [comment] 2024-10-14 12:38
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by noeldiviney** [comment] 2024-10-15 03:43
Hello Kay.
I have installed nuitka version 2.5rc8 and ran my build again .
Command line is  "nuitka --standalone --include-data-dir=folder1=folder1/  wxhello.py --python-flag=-O"
Sadly the results are the same. Nuitka is rejecting the forward slash "/".

The build output is a follows
Quote:-
Creating wxhello.py
Creating msys64nuitkatest/wxhellp.py
Building wxhello.exe
changing directory to /c/Nuitka/msys64nuitkatest
Nuitka-Options: Used command line options: --standalone --include-data-dir=folder1=foldr1/ wxhello.py --python-flag=-O
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time
Nuitka:WARNING: performance.
Nuitka: Starting Python compilation with Nuitka '2.5rc8' on Python '3.11' commercial grade 'not installed'.
FATAL: Error, cannot add data file with 'foldr1/text.txt' path, as 'contains illegal character '/''
Unquote.

Regards Noel

**Comment by kayhayen** [comment] 2024-10-15 08:02
Seems I noticed a problem in my testing and then forgot to push it, should be good now.

**Comment by kayhayen** [comment] 2024-10-15 08:50
The fix for your usage is part of the 2.4.10 hotfix I just made, the wider change, that probably means to audit other os.path.normpath usages or to replace them is not done and needs help.

**Comment by noeldiviney** [comment] 2024-10-15 09:44
Hello Kay.
I have installed nuitka version 2.5rc9 and ran my build again .
Command line is "nuitka --standalone --include-data-dir=folder1=folder1/ wxhello.py --python-flag=-O"
Almost there !! Attaching nuitka-crash-report.xml as a zip file
[nuitka-crash-report.zip](https://github.com/user-attachments/files/17376005/nuitka-crash-report.zip)

The build output is a follows
Quote:-
Creating wxhello.py
file wxhello.py does not exist
Creating msys64nuitkatest/wxhellp.py
Building wxhello.exe
changing directory to /c/Nuitka/msys64nuitkatest
Nuitka-Options: Used command line options: --standalone --include-data-dir=folder1=foldr1/ wxhello.py --python-flag=-O
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time
Nuitka:WARNING: performance.
Nuitka: Starting Python compilation with Nuitka '2.5rc9' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using
Nuitka-Plugins:anti-bloat: fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of
Nuitka-Plugins:anti-bloat: 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Non downloaded winlibs-gcc 'C:/Nuitka/msys64/ucrt64/bin/gcc.exe' is being ignored, Nuitka is very dependent on the precise
Nuitka-Scons: one.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 15 files (no progress information available for this stage).
Nuitka-Scons: Compiled 15 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 14
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 1
Traceback (most recent call last):
  File "C:/Nuitka/Nuitka/nuitka/__main__.py", line 206, in <module>
    main()
  File "C:/Nuitka/Nuitka/nuitka/__main__.py", line 188, in main
    MainControl.main()
  File "C:/Nuitka/Nuitka/nuitka/MainControl.py", line 1159, in main
    _main()
  File "C:/Nuitka/Nuitka/nuitka/MainControl.py", line 1056, in _main
    copyDataFiles(standalone_entry_points=getStandaloneEntryPoints())
  File "C:/Nuitka/Nuitka/nuitka/freezer/IncludedDataFiles.py", line 629, in copyDataFiles
    _handleDataFile(
  File "C:/Nuitka/Nuitka/nuitka/freezer/IncludedDataFiles.py", line 582, in _handleDataFile
    _checkPathConflict(included_datafile.dest_path, standalone_entry_points)
  File "C:/Nuitka/Nuitka/nuitka/freezer/IncludedDataFiles.py", line 542, in _checkPathConflict
    assert os.path.normpath(dest_path) == dest_path
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'. Please include it in your bug report.
Line  108   msys2.bash    All done              Nuitka test is complete
Unquote.
Hope this helps 
Noel

**Comment by kayhayen** [comment] 2024-10-15 10:03
Yes, I guess, you found another spot, where that function is expected to produce proper "native" paths.

**Comment by noeldiviney** [comment] 2024-10-15 10:24
Now time ti test version 2.4.9.
First I will build the simple wxPython "Hello World" with "nuitka --standalone wxhello.py --python-flag=-O"

Quote:-
Building wxhello.exe
changing directory to /c/Nuitka/msys64nuitkatest
Nuitka-Options: Used command line options: --standalone wxhello.py --python-flag=-O
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time performance.
Nuitka: Starting Python compilation with Nuitka '2.4.9' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Non downloaded winlibs-gcc 'C:/Nuitka/msys64/ucrt64/bin/gcc.exe' is being ignored, Nuitka is very dependent on the precise one.
Nuitka-Scons: Backend C compiler: gcc (gcc 13.2.0).
Nuitka-Scons: Backend linking program with 15 files (no progress information available for this stage).
Nuitka-Scons: Compiled 15 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 1
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 14
Nuitka: Keeping build directory 'wxhello.build'.
Nuitka: Successfully created 'wxhello.dist/wxhello.exe'.
Unquote.

Success !! I am looking at a nice wxPython "Hello World" GUI'

Now for the big test "nuitka --standalone --include-data-dir=folder1=folder1/ wxhello.py --python-flag=-O"
Quote
Creating wxhello.py
file wxhello.py does not exist
Creating msys64nuitkatest/wxhellp.py
Building wxhello.exe
changing directory to /c/Nuitka/msys64nuitkatest
Nuitka-Options: Used command line options: --standalone --include-data-dir=folder1=foldr1/ wxhello.py --python-flag=-O
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'ordered-set' PyPI package for best Python compile time performance.
Nuitka: Starting Python compilation with Nuitka '2.4.9' on Python '3.11' commercial grade 'not installed'.
FATAL: Error, cannot add data file with 'foldr1/text.txt' path, as 'contains illegal character '/''
Line  108   msys2.bash    All done              Nuitka test is complete
Unquote.

Alas a forward slash "/"   problem is still here .

Hope this helps .
Noel

**Comment by kayhayen** [comment] 2024-10-15 11:20
I do not recall claiming that 2.4.9 has it fixed, but 2.4.10, you probably misread that.

**Comment by noeldiviney** [comment] 2024-10-15 12:42
how do I download hotfix/2.4.10 ??
I have failed so far
Thanks Noel

**Comment by kayhayen** [comment] 2024-10-15 13:20
I had seen that one before, and it's actually on factory already. I do of course not reproduce these things, but I found this and another similar assertion, so your chances are increasing.

**Comment by kayhayen** [comment] 2024-10-29 17:12
Part of the current pre-release and will be in 2.5 once released.

**Comment by noeldiviney** [comment] 2024-10-31 07:48
Hello Kay.
I see quite a lot of activity but sadly I cannot run Nuitka in a Windows 10 msys64 environment.
I would very much to help in resolving this issue as I want to be able to use your commercial version for 
my Embedded Systems Development Environment.
So I have created the following  bash scripts to create a msys64 test environment and tests as follows 👎 
    nuitka-2.4.10.sh                         For testing nuitka version 2.4.10
    nuitka-2.4.11.sh                          For testing nuitka version 2.4.11
    nuitka-2.5rc11.sh                        For testing nuitka version 2.5rc11 factory dev 
    nuitka-msys64-setup.sh              For setting up a suitable msys64 test environment
    nuitka-msys64-user-manual.txt   How to setup and use the scripts

When the scripts are executed a failure will generate a "nuitka-crash-report,xml"
I am unable to attach ".xml" files
 
I am attaching the above scripts and the User Manual as  "nuitka.zip"
Extract "nuitka.zip"  to "C:\"
[nuitka.zip](https://github.com/user-attachments/files/17584628/nuitka.zip)

I hope this helps
Cheers Noel Diviney

**Comment by kayhayen** [comment] 2024-10-31 11:24
While I appreciate the scripts, I think I can do without. I have doubts about `--python-flag=-O` working for your software necessarily, you ought to remove them first thing when reporting and checking without them, to make sure it's not causing issues. If found, we fix them, but e.g. numpy used to crash with it on occasions in new releases, a lot of software doesn't like it and has no testing coverage for that mode.

**Comment by kayhayen** [comment] 2024-10-31 11:30
As an aside, XML files fit in zip files too, you can attach them that way.

**Comment by kayhayen** [comment] 2024-10-31 11:33
I am not sure, but are you expecting data files to be included magically, without specifying anything like that? I am very confused about that. I will try to compile wx hello world with MSYS2, but this leaves me very puzzled, what you actually mean to show.

**Comment by noeldiviney** [comment] 2024-11-01 12:12
Hello Kay.
Thank you for responding. Wit reference to the scripts I am just trying to ensure that we are on the same wavelength.
The scripts allow one to do everything in a Posix environment on Windows 10. That entails that Python,, Pip, Ide's and
all pogramming tools operate in the msys64 environment. I have taken your advice and stopped using the 
"--python-flag=-O" and the results are the same. I have also run the same scripts for building and executing the nuitka
executeables on Linux with successful results. The build command lines I am using are 👎 
"nuitka --standalone wxhello.py" to test that a very simple "Hello Word" GUI can be built and executed successfully.
"nuitka --standalone --include-data-dir=folder=folder/ wxhello-data.py" to test the inclusion of a data file located in a subfolder.
I notice that in msys64 nuitka version 2.4.10 the GUI is built correctly using both command lines but I get a "crash report"
using "nuitka --standalone --include-data-dir=folder=folder/ wxhello-data.py, whereas, I get a "crash report" when using
both command lines and version 2.4.11 and version 2.5rc11. 
So as far as msys64 environment is concerned nuitka has taken a backward step.

I will do some more testing tomorrow and upload the resulting build logs. Delayed today due to family commitments.
As an aside it is my belief that the problem is associated with the proverbial "\" backward slash folder separator in paths.

Cheers Noel Diviney.

**Comment by kayhayen** [comment] 2024-11-01 12:20
The scripts are still great for reference, don't get me wrong. And reproducibility is a great trait of them. 

I think my tests of including data files with MSYS2 were working, your example looks trivial, but of course, you lacked those options, so I assume your script doesn't actually reproduce an error at all?

I am totally convinced I might have "overseen" more slash issues in more cases, or maybe in some packages, data files via yaml config could trigger it too.

I think within the fact of having those script, the point of the report may have been missed though.

**Comment by kayhayen** [comment] 2024-11-01 18:03
I decided to change the strategy on this one. Until proven otherwise, I will assume it works properly, which of course it may not, but nobody is going to do the work of auditing all of Nuitka for MSYS2 corner cases.

**Comment by kayhayen** [comment] 2024-11-16 12:45
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:45 UTC
Labels: enhancement, develop
