### ISSUE TITLE
SystemError: unknown opcode

### ISSUE THREAD

**Issue by bphillips-exos** [Nuitka/Nuitka#1209] opened 2021-09-14 00:56 UTC
I am encountering a `SystemError: unknown opcode` when trying to use a nuitka compiled library in a distributed [Dask](https://github.com/dask/dask) cluster. There are no issues when running the source code directly in the cluster, or when running the compiled code outside of the cluster. I am using the same docker image across all of these tests and for all nodes in the cluster so I don't believe it is a version mismatch issue. Please let me know if there is other information or debugging that would be helpful, I'm aware this isn't much to go on, but I'm not sure how to proceed. 

Source code:
```python3
def clean_spac_research_data(df: dd.DataFrame) -> dd.DataFrame:
    symbology_columns = ['cusip', 'isin', 'symbol', 'type']
    symbols_meta = [(type_, str) for type_ in symbology_columns]

    def to_series(symbols):
        return pd.Series(dict(sorted(symbols.items())))

    df[symbology_columns] = df['symbols'].apply(to_series, meta=symbols_meta)
    df = df.drop(columns=['symbols'])
    ...
```

Traceback:

> 20:32:10
ERROR
CloudTaskRunner
Task 'write_result': Exception encountered during task execution!
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/dist-packages/prefect/engine/task_runner.py", line 859, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/usr/local/lib/python3.9/dist-packages/prefect/utilities/executors.py", line 445, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "<string>", line 92, in write_result
  File "/usr/local/lib/python3.9/dist-packages/dask/base.py", line 285, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/dask/base.py", line 567, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/distributed/client.py", line 2666, in get
    results = self.gather(packed, asynchronous=asynchronous, direct=direct)
  File "/usr/local/lib/python3.9/dist-packages/distributed/client.py", line 1975, in gather
    return self.sync(
  File "/usr/local/lib/python3.9/dist-packages/distributed/client.py", line 843, in sync
    return sync(
  File "/usr/local/lib/python3.9/dist-packages/distributed/utils.py", line 353, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/dist-packages/distributed/utils.py", line 336, in f
    result[0] = yield future
  File "/usr/local/lib/python3.9/dist-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.9/dist-packages/distributed/client.py", line 1840, in _gather
    raise exception.with_traceback(traceback)
  File "/usr/local/lib/python3.9/dist-packages/dask/optimization.py", line 963, in __call__
    return core.get(self.dsk, self.outkey, dict(zip(self.inkeys, args)))
  File "/usr/local/lib/python3.9/dist-packages/dask/core.py", line 151, in get
    result = _execute_task(task, cache)
  File "/usr/local/lib/python3.9/dist-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/usr/local/lib/python3.9/dist-packages/dask/utils.py", line 34, in apply
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/dask/dataframe/core.py", line 5673, in apply_and_enforce
    df = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/dask/utils.py", line 900, in __call__
    return getattr(obj, self.method)(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/series.py", line 4357, in apply
    return SeriesApply(self, func, convert_dtype, args, kwargs).apply()
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/apply.py", line 1043, in apply
    return self.apply_standard()
  File "/usr/local/lib/python3.9/dist-packages/pandas/core/apply.py", line 1099, in apply_standard
    mapped = lib.map_infer(
  File "pandas/_libs/lib.pyx", line 2859, in pandas._libs.lib.map_infer
    val = f(arr[i])
  File "/usr/local/lib/python3.9/dist-packages/exos_equity_research/spac_research.py", line 50, in to_series
SystemError: unknown opcode

Versions:
- nuitka 0.6.16.4 (installed with pip)
- python 3.9.4
- pandas 1.3.3
- numpy 1.21.2
- dask 2021.4.1
- distributed 2021.4.1

**Comment by kayhayen** [comment] 2021-09-14 07:17
There are solutions for compiled function to be pickled, e.g. with dill, and multiprocessing, with the respective plugin. What technology is used by dask?

The bytecode object of compiled functions is empty, and as such will be very difficult to execute. It looks as if that's what's happening here.

**Comment by bphillips-exos** [comment] 2021-09-14 13:53
Dask is using [cloudpickle](https://github.com/cloudpipe/cloudpickle) to pickle functions sent between nodes. I have tried to reproduce the issue locally by creating `cloudpickle.loads(cloudpickle.dumps(clean_spac_research_data))`, but didn't encounter any error. 

I was able to pull `XXX lineno: 50, opcode: 0` out of a different log destination, but I don't think that provides any additional information. 

I suspect it may have something to do with pickling the nested compiled functions, I will try to create a small, reproducible example.

**Comment by bphillips-exos** [comment] 2021-09-14 15:32
Update: removing all nested functions did allow the compiled code to run on the cluster.

**Comment by kayhayen** [comment] 2021-09-14 16:07
Let me know if you have something reproducible, ideally with only cloudpickle.

**Comment by bphillips-exos** [comment] 2021-09-16 21:22
Hi @kayhayen after some effort I was able to create a reproducible example, the issue exists only when using a Dask cluster. I plan to raise this issue on the Dask github page and continue investigating, but wanted to see if you had any additional thoughts based on this example. 

`dev.py`

```python3
def process_df(df):
    def f(arg):
        return arg

    df['a'] = df['a'].apply(f, meta=('a', int))
    return df
```

Compiled with the following on Ubuntu 16.04.7
`nuitka3 --no-pyi-file --module dev.py`

Example:
```python3
import pandas as pd
import dask.dataframe as dd
from distributed import Client

df = dd.from_pandas(pd.DataFrame({'a': [1]}), npartitions=1)

from dev import process_df

print('Without Cluster:')
print(process_df(df).compute())

# this will create a local process-based Dask cluster and use it for subsequent dask dataframe operations
client = Client()  
print()

print('With Cluster:')
print(process_df(df).compute())
```

Output:
> Without Cluster:
   a
0  1

>With Cluster:
XXX lineno: 2, opcode: 0
distributed.worker - WARNING - Compute Failed
Function:  subgraph_callable-6a3708df-626b-4826-b785-71208e5d
args:      (   a
0  1)
kwargs:    {}
Exception: SystemError('unknown opcode')
SystemError                               Traceback (most recent call last)
/tmp/ipykernel_1446/3196535699.py in <module>
     12 print()
     13 print('With Cluster:')
---> 14 print(process_df(df).compute())
...
/usr/local/lib/python3.9/dist-packages/pandas/core/apply.py in apply_standard()
   1097                 # List[Union[Callable[..., Any], str]]]]]"; expected
   1098                 # "Callable[[Any], Any]"
-> 1099                 mapped = lib.map_infer(
   1100                     values,
   1101                     f,  # type: ignore[arg-type]
/usr/local/lib/python3.9/dist-packages/pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()
   2857             result[i] = arr[i]
   2858             continue
-> 2859         val = f(arr[i])
   2860 
   2861         if cnp.PyArray_IsZeroDim(val):
/exos/dev.cpython-39-x86_64-linux-gnu.so in f()
SystemError: unknown opcode

**Comment by kayhayen** [comment] 2021-10-17 13:13
So, it seems cloudpickle want's to transfer function code to where it doesn't exist, that's not going to be supported with compiled functions, you need the extension module to load things from. So cloudpickle will be a problem.

Your example doesn't run for me at all, I am getting:

```
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.
````

with pure Python already. I believe the issue is not well broken down enough and will close it until a better case is presented.

**Closed by kayhayen** 2021-10-17 13:13 UTC
Labels: needs_example
