### ISSUE TITLE
The default --enable-console behavior on macOS breaks PySide6 and potentially other things, users should actually select background apps actively instead

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1911] opened 2022-11-28 21:29 UTC
**Environment:**
python3.7 -m nuitka --version
Nuitka-Options:INFO: Used command line options: --version
1.3rc3
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21)
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3.7
OS: Darwin
Arch: x86_64
scons: warning: Calling missing SConscript without error is deprecated.
Transition by adding must_exist=0 to SConscript calls.
Missing SConscript '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/CCompilerVersion.scons'
File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/build/inline_copy/bin/scons.py", line 44, in
NOTE:
Somehow I got an error for "python3.7 -m nuitka --version" command, as you see above. But my comment is not related with this warning

**How did you install Nuitka and Python**
pip

**Provide in your issue the Nuitka options used**
python3.7 -m nuitka --run --standalone --enable-plugin=numpy,pyside6  --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site  --macos-app-icon=/Users/license_lock_photo.png --macos-create-app-bundle **--macos-disable-console** test.py

**Content of test.py:**

```
import os
import time
from Foundation import NSUserNotification
from Foundation import NSUserNotificationCenter
_title = "title"
message = "message"
notification = NSUserNotification.alloc().init()
notification.setTitle(title)
notification.setInformativeText(message)
center = NSUserNotificationCenter.defaultUserNotificationCenter()
center.deliverNotification(notification)
time.sleep(2)
```

Description:
If --disable-console mode is used then alerts are not shown by NSUserNotificationCenter. No exception occurs either(the output is printed into txt file) additionally it does not look like that NSUserNotificationCenter cannot be initialised as issue #1907 

PS:Actually I do not need to use "--disable-console" mode necessarily(Even I could not get the functionality of it), but the problem is if I want to use QLineEdits from PySide6 lib in my app, it is not possible to enter any text inside the GUI QLineEdit object without "--disable-console" mode. Somehow it is not editable without this mode. If this behaviour is a bug, then I can also open another issue for it and we can close this one.

Thanks a lot in advance.

**Comment by kayhayen** [comment] 2022-11-29 09:20
Without that disabling console mode, many GUI features will not be available, no hi DPI, etc. so that is why it is preferrable. I am wondering right now if on pure Python High DPI works. I think I read they gave up on a `pythonw` at some point.

**Comment by kayhayen** [comment] 2022-11-29 11:29
Strangely, I found that even 2.7 did have it for its python.app definitions. It seems it makes the difference mostly towards dock, it will be flashing when started there, or not. Makes me wonder, if not `--disable-console` is a misnomer in that way, since a console window is never opened, it means something very different on macOS, namely just the fact if you are going to have a Window or not, i.e. GUI mode.

Regarding your claim that it prevents the notification if given. Being a background process should not make the difference, and definitely what makes it work. But your example code doesn't even run. The usage of `title` is wrong, and the API mismatches. I assume you are claiming a minimal reproducer without actually making it run once? That is bad style. I also saw that code before.

After I made it run, it didn't show a notification in CPython. That said, I have had pending notifications from previous runs of a similar thing. Probably when I checked it out last time. Seems I disabled notifications for "Python" and "Mini" (my compiled app name) when I clicked on them. Enabling them back also never gave me one again, not sure why. I am at this point not convinced if an app can send a notification without any efforts. I definitely would need working code, or know what my macOS is wrong about. I do not have focus mode or anything, so what is it?

**Comment by emre84** [comment] 2022-11-29 19:47
Hi Kay,

I am sorry for that but somehow all "_" chars were deleted from method names.
I fixed the code so you can just copy paste following code part, I guess it should work fine:

import time
from Foundation import NSUserNotification
from Foundation import NSUserNotificationCenter
title = "title"
message = "message"
notification = NSUserNotification.alloc().init()
notification.setTitle_(title)
notification.setInformativeText_(message)
notification.setSoundName_("Ping")
center = NSUserNotificationCenter.defaultUserNotificationCenter()
center.deliverNotification_(notification)
time.sleep(2)

**By the way, after laptop restart, both nuitka commands(with --disable-console and without --disable-console started to work fine either. So I can send the macOS notifications via nuitka app.** 

You can see the video below:
https://www.dropbox.com/s/1w1wa0onwfk85nd/IMG_2661.MOV?dl=0

1.Part with pycharm(Works fine)

2.Part with nuitka app with following command(without --disable-console):(works fine)
sudo python3.7 -m nuitka --run --standalone --enable-plugin=numpy,pyside6  --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site  --macos-app-icon=/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/icons/license_lock_photo.png --macos-create-app-bundle test_kay.py;

3.Part with nuitka app with following command(with --disable-console):(works fine)
date > log.txt;sudo python3.7 -m nuitka --run --standalone --enable-plugin=numpy,pyside6  --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site  --macos-app-icon=/Users/emre/Documents/Tensorflow1/models/research/object_detection/object_detection/icons/license_lock_photo.png --macos-create-app-bundle **--macos-disable-console** test_kay_disable_console.py; date >> log.tx

Also do not forget to enable the macOS notifications for your apps, if you want to retest it on your Mac:
Please see the screenshots below:
https://www.dropbox.com/s/w1zv0vbgb37tp45/Kay1.png?dl=0
https://www.dropbox.com/s/z6a09r0bt0tdmuy/Kay2.png?dl=0
https://www.dropbox.com/s/qgcrttr4pswy88q/Kay3.png?dl=0

PS:
1-Please do not close the issue yet. I just want to compile my whole app with new notification feature to be sure if it works fine.
2-I hope you have access rights for the screenshots and videos. 

Thanks a lot for your support.

**Comment by kayhayen** [comment] 2022-11-30 08:54
Ah, you need to use GitHub quoting, then. Otherwise markup may have a different idea about leading and trailing whitespaces, the tripe backtick is for that. Thanks for providing the information. I will try and reproduce it myself as well,

Regarding the PySide6 issue you mentioned, can you come up with some sort of minimal reproducer for me as well? I would love to see it too.

**Comment by emre84** [comment] 2022-11-30 20:06
Hi Kay, 

Thanks for the tips. If you mention about following issue:
"Actually I do not need to use "--disable-console" mode necessarily(Even I could not get the functionality of it), but the problem is if I want to use QLineEdits from PySide6 lib in my app, it is not possible to enter any text inside the GUI QLineEdit object without "--disable-console" mode."

**this is the code to reproduce:**
from PySide6.QtWidgets import QWidget, QApplication, QLineEdit
class QLineEditExample(QWidget):
    def __init__(self):
        super().__init__()
        self.btn = QLineEdit('Hi', self)
        self.show()
app = QApplication([])
button = QLineEditExample()
app.exec()

**This is nuitka command:**
sudo python3.7 -m nuitka --run --standalone --enable-plugin=numpy,pyside6 --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site --macos-app-icon=/Users/license_lock_photo.png --macos-create-app-bundle  test.py;

**This is the video:**
https://www.dropbox.com/s/naong13v4wjteuy/IMG_2667.MOV?dl=0
In video, I started the app via terminal but if I double click the app file, it has the same behaviour. I can't see any text in QlabelEdit box.

**Comment by kayhayen** [comment] 2022-12-01 08:13
Wow, that is gross indeed. Unfortunately, from a Nuitka perspective, it's hard to tell if a PySide user wants to have a Window open at all anyway, could just import it to do network stuff, or run in a mode, where the GUI is highly optional, that kind of thing. That said, the effect it currently has, namely setting the graphics mode required as opposed to background service, is entirely unrelated to console.

This is a bigger change, but I believe I will make it a noop on macOS too, and have `--macos-app-background` instead, with then is the current default, but as an option, not the default. Because I guess it's rare to want that.

This is one of the rare cases, where a video was actually warranted. For pasting code, just make sure to use the backtick quoting, with triple quotes, markdown lets you past code here just fine. I often go and edit reports, like I just did not with yours, so they become readable. It also has a nice copy button. But not using indentation, which is often the issue, I just took the rendered text. Sorry for misinterpreting it. Let me just relabel this one, because I think my machine also needs a reboot and the notifications will show again, that was kind of invalid. But the bigger picture of --disable-console being non-sense on macOS is still valid and I want to keep track of it.

**Comment by emre84** [comment] 2022-12-02 20:23
Hi Kay, 

Everything looks fine till now but I have one more problem. I recognised that if I change anything in info.plist file, I cannot get any notification anymore. It does not matter what I change or add into plist, it prevents my notifications.

**Comment by kayhayen** [comment] 2022-12-03 09:10
There is an option to add entitlements, you should use that. Let me know if it can do what you want it to do. My goal is for nobody to have to edit this file in any way.

Yours,
Kay

**Comment by emre84** [comment] 2022-12-12 19:41
Hi Kay, if you want, you can close this issue from my side. I have no questions or requests. Everything works fine. Thanks a lot.

**Comment by kayhayen** [comment] 2022-12-13 10:12
This is currently on the develop branch, we will close the issue once it's part of a stable release, which will be 1.3 and probably soon, although I was thinking to make at least one more hotfix before, while will push it back.

**Comment by kayhayen** [comment] 2022-12-21 13:42
This is part of the stable release 1.3 that I just made.

**Closed by kayhayen** 2022-12-21 13:42 UTC
Labels: enhancement, develop
