### ISSUE TITLE
Failed to compile scripts using pillow

### ISSUE THREAD

**Issue by XJF2332** [Nuitka/Nuitka#3181] opened 2024-11-04 11:38 UTC
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

```
2.4.11
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).
```

- How did you install Nuitka and Python

use pip, global env

- The specific PyPI names and versions

  > python -m pip list -v

```
pillow                    10.4.0       C:\Program Files\Python311\Lib\site-packages pip
Send2Trash                1.8.3        C:\Program Files\Python311\Lib\site-packages pip
# python 3.11.9
```

- Also supply a Short, Self Contained, Correct, Example

simply open and save an image
```python
import PIL.Image

img = PIL.Image.open('test.png')
# save as jpg
img.save('test.jpg', 'JPEG')
```
then run
```commandline
python -m nuitka --standalone --remove-output --main="test.py" 
```
and you should get a failure
```commandline
Unexpected output from this command:
link @C:\Users\xujia\AppData\Local\Temp\tmp672kuki_.lnk
LINK : fatal error LNK1104: 无法打开文件“C:\_FILES~1\PYTHON~1\娴嬭瘯\TEST~1.DIS\_nuitka_temp.exe”
scons: *** [C:\_FILES~1\PYTHON~1\测试\TEST~1.DIS\_nuitka_temp.exe] Error 1104
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

- Provide in your issue the Nuitka options used

```commandline
python -m nuitka --standalone --remove-output --main="test.py" 
```

- Note if this is a regression

  I don't know because it's my first time in nuitka

**Comment by kayhayen** [comment] 2024-11-04 16:37
This is probably a hello world problem, and the develop branch and 2.5 which is to come soon, won't show it. The Chinese path doesn't shorten well there. I am confused to see `[C:\_FILES~1\PYTHON~1\测试\TEST~1.DIS\_nuitka_temp.exe]` being used, maybe a workaround I am attempting (naming the binary ASCII and renaming it later) is applied wrongly.

**Comment by XJF2332** [comment] 2024-11-04 17:09
Well, yes, the problem was solved after I changed the path of the script to ASCII. Original path is `C:\[FILES]\Python脚本\测试\test.py` and new path is `C:\Test\test.py`. However, I hope to see the Chinese path is supported.
By the way, I am also confused to see `[C:\_FILES~1\PYTHON~1\测试\TEST~1.DIS\_nuitka_temp.exe]` being used.

**Comment by kayhayen** [comment] 2024-11-04 17:37
There is this code:

```
# Workaround for MinGW64 not supporting unicode result paths for "-o" basename.
if os.name == "nt" and not isFilesystemEncodable(result_exe):
    result_exe = os.path.join(
        os.path.dirname(result_exe),
        "_nuitka_temp.pyd" if module_mode else "_nuitka_temp.exe",
    )

    deleteFile(result_exe, must_exist=False)
```

The result_exe should be more in your home directory there, but maybe you were compiling inside your Python installation, at least that is what it looks like. Check out if the develop branch of Nuitka fares better please.

**Comment by XJF2332** [comment] 2024-11-05 05:35
I am not compiling inside my python installation, my python is installed in `C:\Program Files\Python311\python.exe`, and both `C:\[FILES]\Python脚本\测试\test.py` and `C:\Test\test.py` are not in it.
I tried the develope branch by `python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"` in venv, and if there are Chinese characters in the path, same error occurred.
```
Unexpected output from this command:
link @C:\Users\xujia\AppData\Local\Temp\tmpyvqg8dg8.lnk
LINK : fatal error LNK1104: 无法打开文件“C:\_FILES~1\PYTHON~1\娴嬭瘯\TEST~1.DIS\_nuitka_temp.exe”
scons: *** [C:\_FILES~1\PYTHON~1\测试\TEST~1.DIS\_nuitka_temp.exe] Error 1104
FATAL: Failed unexpectedly in Scons C backend compilation.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```
```
(testenv) C:\[FILES]\Python脚本\测试>python -m nuitka --version
2.5rc12
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\[FILES]\Python脚本\testenv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.41.34120\bin\Hostx64\x64\cl.exe (cl 14.3).
```
```
(testenv) C:\[FILES]\Python脚本\测试>python -m pip list -v
Package     Version Location                                      Installer
----------- ------- --------------------------------------------- ---------
Nuitka      2.5rc12 C:\[FILES]\Python脚本\testenv\Lib\site-packages pip
ordered-set 4.1.0   C:\[FILES]\Python脚本\testenv\Lib\site-packages pip
pillow      11.0.0  C:\[FILES]\Python脚本\testenv\Lib\site-packages pip
pip         24.0    C:\[FILES]\Python脚本\testenv\Lib\site-packages pip
setuptools  65.5.0  C:\[FILES]\Python脚本\testenv\Lib\site-packages pip
zstandard   0.23.0  C:\[FILES]\Python脚本\testenv\Lib\site-packages pip
```

**Comment by kayhayen** [comment] 2024-11-05 19:22
Ah, Ok, I was making guesses based on the shortpath, that do not hold to be true. I think it's using an absolute path for the result binary, and that may be without need. You are using a path that is Chinese, but short, and then Windows doesn't create a short path, which is then ASCII for use to use. But we could try and use a relative path, and avoid the issue that way somewhat. Of course in theory, it could always introduce it that way. I will make an experiment and prepare a fix for this.

**Comment by XJF2332** [comment] 2024-11-06 06:03
Maybe I have to mention that I compiled some other scripts that have Chinese names and paths, and compiling was successful, this only happened when I used pillow.

**Comment by kayhayen** [comment] 2024-11-07 13:00
I was under the assumption, the last bit but be a mistake and that a project name like `娴嬭瘯` triggers it, can you confirm or deny that?

**Comment by XJF2332** [comment] 2024-11-07 17:31
I don't know the reason why it appears, `娴嬭瘯` is probably an error because it is compilicated and has no meaning in Chinese. And I didn't use it in any of the paths. Maybe it's an encoding/decoding error. (I tried `chcp 65001` before compiling and the error still happens)
I also checked `C:\_FILES~1\PYTHON~1\娴嬭瘯\TEST~1.DIS\_nuitka_temp.exe` - maybe it means `C:\[FILES]\Python脚本\测试\test.dist` and this folder is empty.

**Comment by kayhayen** [comment] 2024-11-11 13:52
The `chcp` program doesn't inluence compilers at all for all I can tell, I have tried it in the past to avoid non-English output by them, no success at all.

**Comment by kayhayen** [comment] 2024-11-11 14:03
I made a change that should make it try the relative path if it is not encodable even after changing the basename, this may well be enough for many users with absolute paths that contain Chinese short paths as I would refer to them. I think the same workaround also needs to be applied for onefile. Can you try if standalone works with current factory branch for you? And then try if --onefile errors out again.

**Comment by XJF2332** [comment] 2024-11-12 06:03
Thank you for your work, both --standalone and --onefile work.

**Comment by kayhayen** [comment] 2024-11-13 08:34
Interesting, I think depending on the output exe filename, the same kind of workaround would be needed, but you didn't have that issue to begin with I guess, it's just something to keep in mind on my side, to make this workaround general too for my fellow Asian users.

**Comment by XJF2332** [comment] 2024-11-13 09:17
Well, I got something interesting after seeing your comment. For the factory branch, I tested it in virtual machine, which is Windows10 LTSC 2021, and everything goes fine. However, after seeing it, I switched back to Windows11 and tested it again, the problem is still here. Sorry for the confusion I made.

**Comment by kayhayen** [comment] 2024-11-13 13:27
The changes I made are now on the develop branch and will be part of the 2.5 release. I will try and reproduce your issues with the Chinese strings I find here, but I am not sure, I can do it before 2.5 release, but it will be a hotfix maybe.

**Comment by kayhayen** [comment] 2024-11-16 12:43
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:43 UTC
Labels: bug, excellent_report
