### ISSUE TITLE
FATAL: glfw: Undetected OS specific glfw plugin '"nt"', please report bug for.

### ISSUE THREAD

**Issue by biaogeng** [Nuitka/Nuitka#2394] opened 2023-08-18 00:34 UTC
I was trying to pack an official OpenGL [example](https://doc.qt.io/qtforpython-6/examples/example_opengl_hellogl2.html) using PySide6, and got the error in the title. The bug seemed to be OpenGL related, because another non-opengl example was packed successfully.

The building command was
```
nuitka --standalone --plugin-enable=pyside6 gl2.py
```

So far I have tried different versions of nuitka, but all gave the same error:
- default used by pyside6-deploy, which is 1.5.4
- factory version from [here ](https://nuitka.net/doc/factory.html), which is 1.8rc9
- default version using `pip install -U --force-reinstall nuitka`, which is 1.7.10
- develop version, using `pip install -U F:\Download\Nuitka-develop.zip`, which appears to be the same as the factory version.

It seems to be a similar bug reported in another issue #1531 , where the system was "wayland". It was fixed by the factory version. But no luck for me.

A crash report generated from the develop version of nuitka is attached.

Versions
```
1.7.9
Commercial: None
Python: 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Python310\envs\qt6\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\bin\Hostx64\x64\cl.exe (cl 14.1).
```

All installed packages
```
cx-Freeze==6.15.5
cx-Logging==3.1.0
lief==0.13.2
Nuitka @ file:///F:/Download/Nuitka-develop.zip#sha256=c4bf330ea948fcb8205d20639fb1f6cce326596fff559fb64a63954354f2a35b
ordered-set==4.1.0
PyOpenGL==3.1.7
PyOpenGL-accelerate==3.1.7
PySide6==6.5.2
PySide6-Addons==6.5.2
PySide6-Essentials==6.5.2
shiboken6==6.5.2
zstandard==0.21.0
```
[nuitka-crash-report.zip](https://github.com/Nuitka/Nuitka/files/12374287/nuitka-crash-report.zip)

**Comment by kayhayen** [comment] 2023-08-18 06:33
I have a `GlfwUsingTest.py` that shows no error, which it should do, neither with stable nor develop. Your glfw version is missing from the report curiously, I wonder why the "glfw" module is not in the report, maybe because it was interrupted, the unfinished modules, and thus their distributions are not included, so I cannot tell from the report. That too is probably something to fix. I think the `ReportingSystemExit` should not lead to a traceback, but it may only be on factory at this time.

Develop and factory ought to still be different, but not for very much longer. :)

**Comment by kayhayen** [comment] 2023-08-18 06:42
Strangely with your example, I do reproduce it, now I am very confused, why the plugin could behave differently.

**Comment by kayhayen** [comment] 2023-08-18 07:36
Ah, I get it, my bad, I added PyOpenGL plugin handling to the Glfw plugin, which has confused me now, because it doesn' get to glfw yet, but crashes before that is used, maybe as a dependency, but maybe not at all. Hosting that code in the plugin seemed to make some sense, but I guess not a good idea for knowing what module causes the issue.

**Comment by kayhayen** [comment] 2023-08-18 07:44
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by biaogeng** [comment] 2023-08-19 00:25
Thank you for the fix! I just tried the 1.8rc10 factory version. The build was successful. But unfortunately, the executable got runtime errors. But I'm not sure if this is due to my environment or something else.


```
Unable to import OpenGL.platform.win32.Win32Platform: cannot import name 'util' from 'ctypes' (C:\Users\gbb\CodePlay\python\Qt\test\GL2~1.DIS\ctypes\__init__.py)
Traceback (most recent call last):
  File "C:\Users\gbb\CodePlay\python\Qt\test\GL2~1.DIS\gl2.py", line 23, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\gbb\CodePlay\python\Qt\test\GL2~1.DIS\OpenGL\GL\__init__.py", line 3, in <module OpenGL.GL>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\gbb\CodePlay\python\Qt\test\GL2~1.DIS\OpenGL\error.py", line 12, in <module OpenGL.error>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\gbb\CodePlay\python\Qt\test\GL2~1.DIS\OpenGL\platform\__init__.py", line 56, in <module OpenGL.platform>
  File "C:\Users\gbb\CodePlay\python\Qt\test\GL2~1.DIS\OpenGL\platform\__init__.py", line 50, in _load
TypeError: 'NoneType' object is not callable
```

**Comment by kayhayen** [comment] 2023-08-19 07:56
I believe we should have seen this too, I didn't immediately see what is using it, but the PySide6 might be bug hiding it, this must be some sort of hidden dependency on `ctypes.util` which is strange to see.

**Comment by kayhayen** [comment] 2023-08-19 08:12
What I can extract from this is only `import OpenGL.GL` as a test case, and that works fine for me. I also don't even see, where this could come from, but `from OpenGL.platform import ctypesloader` looks suspicious. Somehow my code example maybe doesn't trigger a lazy decorated function, and it appears `ctypesloader` comes from that, but I cannot trigger it, e.g. not with a pygame example, and really I hate to be guessing. Please open a new report with a reproducer. This seems relevant, but I won't research more for non-commercial users unfortunately, this was even far more than I ask myself to limit to.

**Comment by kayhayen** [comment] 2023-08-31 08:05
Part of the 1.8 release I just made.

**Closed by kayhayen** 2023-08-31 08:05 UTC
Labels: bug, factory, excellent_report

**Comment by FangliangBai** [comment] 2023-10-24 09:06
Hi @biaogeng , I just had the same error as yours: `Unable to import OpenGL.platform.win32.Win32Platform`. Have you managed to solve this error?
