### ISSUE TITLE
Pyside2 method overriding doesn't work

### ISSUE THREAD

**Issue by epsilon-phase** [Nuitka/Nuitka#1023] opened 2021-03-13 19:17 UTC
0.6.13rc6
Python: 3.9.2 (default, Feb 20 2021, 18:40:11) 
OS: Linux
Arch: x86_64

installed by `pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"`, since looking for extant issues turned up a bunch related to PySide2

So far, I've noticed that it fails in at least 2 different places when overriding methods on Qt objects, `event`, `paintEvent`.

This is the smallest example I care to try and replicate for now.

Compiled with `nuitka3 --follow-imports --enable-plugin=pyside2 test.py`

```python
from PySide2.QtWidgets import *

class CustomEvent(QDialog):
    def event(self, event):
          print("Hello")
          return super(CustomEvent,self).event(event)


app = QApplication([])
testDialog = CustomEvent()
testDialog.show()
app.exec_()
```

**Comment by kayhayen** [comment] 2021-03-14 07:46
This is a duplicate I assume, as it's working after a fix for an unpushed correction of #1022 that is coming soon. My CI is busy with a pre-release of the state you tested.

**Comment by epsilon-phase** [comment] 2021-03-14 15:02
The one difference I saw there is that this doesn't result in an error, it results in the event function never getting called. Is it the same cause?

Anyway, thanks for addressing my issue :)

**Comment by kayhayen** [comment] 2021-03-14 18:48
I don't know that @epsilon-phase you can retry with current factory branch if you want to: https://nuitka.net/doc/factory.html

**Comment by epsilon-phase** [comment] 2021-03-14 19:36
Yeah, the events still aren't being handled by that method.

Also, elsewhere, I'm having issues with the slots still having trouble with discarding additional arguments, which is troubling.

Anywho, for thoroughness, here's the version string

```
0.6.13rc7
Python: 3.9.2 (default, Feb 20 2021, 18:40:11) 
OS: Linux
Arch: x86_64
```

**Comment by kayhayen** [comment] 2021-03-15 05:35
Ok, I will look into that, maybe not before release though, but clearly soonish.

**Comment by kayhayen** [comment] 2021-03-15 08:45
I managed to reproduce this.

**Comment by kayhayen** [comment] 2021-03-26 14:54
This will need the PySide6 I have doing upstream. Once PYSIDE-1523 is merged, it will work.

**Comment by kayhayen** [comment] 2021-03-27 08:33
I think I closed this accidentally. PYSIDE-1523 is merged, and should be in 6.0.3 which is unknown when that happens, and Nuitka need a pyside6 plugin as well.

**Comment by jan-tosovsky-cz** [comment] 2021-04-10 19:36
Does this apply also for PySide6? I am facing similar problem when using custom GraphicsView with overridden events. After Nuitka compiling any custom events (arrow key press or mouse wheel zooming) are ignored. Tested on newly published PySide 6.0.3. The complete code is here https://github.com/drifted-in/jet-browser-qt-for-python/blob/main/jetbrowser.py
Nuitka 0.6.13
Python 3.9.2
OS: Windows
Arch: x86_64

**Comment by kayhayen** [comment] 2021-04-11 07:34
Unfortunately it seems my patch of PySide will only be released as 6.1, so that version currently doesn't even employ the workarounds I am doing for PySide2.

**Comment by jan-tosovsky-cz** [comment] 2021-05-20 12:35
I've tested my project on PySide 6.1 and it finally works for me (compiled using Nuitka 0.6.14.7). Cool !!!

**Comment by kayhayen** [comment] 2021-05-25 09:15
Thanks for the feedback.

**Closed by kayhayen** 2021-05-25 09:15 UTC
Labels: bug, delayed
