### ISSUE TITLE
python setup.py bdist_nuitka FAILS if there is previous build

### ISSUE THREAD

**Issue by freemanix** [Nuitka/Nuitka#2172] opened 2023-04-14 10:25 UTC
If I use `python setup.py bdist_nuitka`, the compilation fails when run again, i.e. when there is already built .so module in the `build` directory. It reports:

```
Nuitka-Options:INFO: Used command line options: --module --enable-plugin=pylint-warnings
--output-dir=/home/test/src/nuittest/build/lib --nofollow-import-to=*.tests --remove-output 
--include-package=nuittest --python-flag=no_docstrings 
/home/test/src/nuittest/build/lib/nuittest.cpython-38-x86_64-linux-gnu.so

SyntaxError: invalid or missing encoding declaration for 
'/home/test/src/nuittest/build/lib/nuittest.cpython-38-x86_64-linux-gnu.so'
```
Tested with minimal `nuittest` package containing just `__init__.py` with:
```
__version__ = '0.1.0'
```
The minimal `setup.py` file:

```
from setuptools import setup

setup(
    name='nuittest',
    version='0.1.0',
    description='Nuitka tooling test',
    packages=['nuittest'],
    command_options = {'nuitka': {'--python-flag': 'no_docstrings'}}
)
```

If I remove the invalid file (or whole `build` directory) prior to call to `python setup.py bdist_nuitka`, the build succeeds. 

Tested with Python 3.8 and Nuitka 1.5.x. Repeated building works fine in Nuitka 1.4.8.

**Comment by kayhayen** [comment] 2023-04-17 07:13
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-04-17 07:16
The root cause is that the scan for build tasks may lead to locating the built package rather than the source code. This situation is now recognized. Another situation, there being an extension module provided, and used in the package lists, should also have been trouble, and these will be kept intact. It depends on if there is source code found for the extension module in the build folder.

That said, plenty of warnings to always clean the folder populate packaging recommendations. But at least Nuitka should be clean now again.

**Comment by freemanix** [comment] 2023-04-17 09:04
I've just used the factory branch, which installed me `Nuitka-1.6rc7-cp38-cp38-linux_x86_64.whl`, and I can confirm that the fix is working for me. Thank you.

**Comment by kayhayen** [comment] 2023-04-25 08:17
This is part of the hotfix release 1.5.7 that I just made.

**Closed by kayhayen** 2023-04-25 08:17 UTC
Labels: bug, factory, excellent_report
