### ISSUE TITLE
Missing support for "win32com.server.register"

### ISSUE THREAD

**Issue by OmniaGit** [Nuitka/Nuitka#1942] opened 2022-12-16 19:02 UTC
Nuitka version
PS C:\Users\uomnia\Desktop\Workspace\AllTest> python -m nuitka --version
1.2.7
Commercial: None
Python: 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\uomnia\AppData\Local\Programs\Python\Python38\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

this is my code

```
import win32com.server.register

class HelloWorld(object):
    _reg_clsid_ = "{c1110833-3315-42b8-abb8-658dd459f9d9}"
    _reg_desc_ = "Pytho Test COM Server"
    _reg_progid_ = "nuitka.TestComServer"
    _public_methods_ = ["Hello"]
    
    def Hello(self):
        return "Hello"

if __name__=="__main__":
    win32com.server.register.UseCommandLine(HelloWorld
```

**This is how to compile it:**

PS C:\Users\uomnia\Desktop\Workspace\AllTest> python -m nuitka .\com_server.py
Nuitka-Options:INFO: Used command line options: .\com_server.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure
Nuitka-Options:WARNING: that is intended.
Nuitka:WARNING: Using very slow fallback for ordered sets, please install 'orderedset' PyPI package for best Python
Nuitka:WARNING: compile time performance.
Nuitka:INFO: Starting Python compilation with Nuitka '1.2.7' on Python '3.8' commercial grade 'not installed'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: cl (cl 14.3).
Nuitka-Scons:INFO: Backend linking program with 9 files (no progress information available).
Nuitka-Scons:INFO: Compiled 9 C files using clcache with 7 cache hits and 2 cache misses.
Nuitka:INFO: Keeping build directory 'com_server.build'.
Nuitka:INFO: Successfully created 'com_server.exe'.
Nuitka:INFO: Execute it by launching 'com_server.cmd', the batch file needs to set environment.

**this is the error the i get after the compile process**

PS C:\Users\uomnia\Desktop\Workspace\AllTest> .\com_server.cmd
Requesting elevation and retrying...
Error: registration failed (exit code 1).
  File "C:\Users\uomnia\Desktop\Workspace\AllTest\.\com_server.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file C:\Users\uomnia\Desktop\Workspace\AllTest\.\com_server.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
Before submitting an Issue, please review the [Issue Guidelines](https://github.com/kayhayen/Nuitka/blob/develop/CONTRIBUTING.md#submitting-an-issue).

* Please check whether the bug was already reported or fixed.

* Please check out if the develop version of Nuitka works better for you.

  Download source, packages [from here](https://nuitka.net/doc/download.html)
  where you will also find instructions how to do it via pip or git.

If you want to post a problem/bug, to help us understand and resolve your issue
please check that you have provided at least the information below, and discard
up to here:

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

  If you are not providing the full output. The issue cannot be solved and will
  be considered `invalid`. It does more than you think, and we are adding more
  all the time. We do not want to left guessing or trying things out to
  reproduce your issue.

* How did you install Nuitka and Python
python -m pip  install nuitka
pip version 22-3-1

  > python -m pip freeze
appdirs==1.4.4
certifi==2022.9.24
charset-normalizer==2.1.1
cssselect2==0.7.0
Cython==0.29.32
docutils==0.19
idna==3.4
lxml==4.9.1
Nuitka==1.2.7
OdooPLM-CCE @ file:///Z:/OdooPLMDist/OdooPLM_CCE-0.0.2-py38-none-any.whl
OdooPLM-CLientUtils @ file:///Z:/OdooPLMDist/OdooPLM_CLientUtils-0.0.1-py38-none-any.whl
OdooPLMClient @ file:///Z:/OdooPLMDist/OdooPLMClient-0.0.1-py38-none-any.whl
OdooPLMClientUtils @ file:///Z:/OdooPLMDist/OdooPLMClientUtils-0.0.2-py38-none-any.whl
OdooQtUi==0.0.5
Pillow==9.2.0
PyPDF2==2.11.0
PySide2==5.15.2.1
python-dateutil==2.8.2
pywin32==305
reportlab==3.6.11
requests==2.28.1
shiboken2==5.15.2.1
six==1.16.0
svglib==1.4.1
tinycss2==1.1.1
typing_extensions==4.3.0
urllib3==1.26.12
webencodings==0.5.1

Thanks in advance
regards

**Comment by kayhayen** [comment] 2022-12-16 19:20
Make sure you read the output:

> Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure
> Nuitka-Options:WARNING: that is intended.

However, the code in pywin32 does not support Nuitka apparently. If you are a commercial user, go here and purchase priority, otherwise, I will consider this delayed. https://nuitka.net/doc/commercial.html

**Comment by Avasam** [comment] 2024-03-17 21:35
Possibly relevant pywin32 issue: https://github.com/mhammond/pywin32/issues/1639

**Comment by kayhayen** [comment] 2024-03-18 18:26
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by KRRT7** [comment] 2024-07-03 05:40
```
Nuitka: Launching 'main.dist\main.exe'.
Traceback (most recent call last):
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\test\MAIN~1.DIS\main.py", line 15, in <module>
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\test\MAIN~1.DIS\win32com\server\register.py", line 642, in UseCommandLine
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\test\MAIN~1.DIS\win32com\server\register.py", line 457, in RegisterClasses
  File "C:\Users\NUITKA~1\Desktop\NUITKA~2\test\MAIN~1.DIS\win32com\server\register.py", line 213, in RegisterServer
AttributeError: module 'sys' has no attribute 'frozen'
``` is what it raises nowadays

**Comment by kayhayen** [comment] 2024-07-08 12:24
Seems they changed the code, I have made it more robust, but I didn't test it, can you do it @KRRT7 ?

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-07-18 10:16
That should be impossible with the config:

```
- module-name: 'win32com.server.register' # checksum: cb126a6d
  anti-bloat:
    - replacements_plain:
        'pythoncom.frozen': '1'
        'sys.frozen': 'True'
      change_function:
        'ReExecuteElevated': "'''raise (RuntimeError('Nuitka: Needs to be elevated already, use --windows-uac-admin'))'''"
  implicit-imports:
    - depends:
        - 'win32timezone'
`````

This could would have to change over to `True` references and not do those things anymore.

**Comment by kayhayen** [comment] 2024-07-18 10:20
I saw it also when I use `--show-source=win32com` so I guess you might have used the wrong version of Nuitka like stable, which it is not yet a part of.

**Comment by kayhayen** [comment] 2024-07-20 13:07
I am going to pretend this is solved, I think you were mistaken. Should it be observed untrue, please open a new issue.

**Comment by KRRT7** [comment] 2024-07-22 04:32
i indeed was on an old stable, however nowadays we get this
```
Traceback (most recent call last):
  File "C:\Users\NUITKA~1\AppData\Local\Temp\ONEFIL~1\main.py", line 13, in <module>
    win32com.server.register.UseCommandLine(HelloWorld)

  File "C:\Users\NUITKA~1\AppData\Local\Temp\ONEFIL~1\win32com\server\register.py", line 665, in UseCommandLine
  File "C:\Users\NUITKA~1\AppData\Local\Temp\ONEFIL~1\win32com\server\register.py", line 469, in RegisterClasses
  File "C:\Users\NUITKA~1\AppData\Local\Temp\ONEFIL~1\win32com\server\register.py", line 267, in RegisterServer
pywintypes.error: (2, 'GetShortPathNameW', 'The system cannot find the file specified.')
```

**Comment by kayhayen** [comment] 2024-10-29 20:47
I managed to reproduce it, turns out, it's not easy to see the actual output, it seemingly gave no error to me, but that was untrue. It's using `sys.executable` which we point to a python.exe that won't exist on purpose. And we need to also change that over to `sys.argv[0]` in a replacement, then it actually works.

**Comment by kayhayen** [comment] 2024-11-01 10:14
This is now part of the current pre-release and will be part of 2.5 release.

**Closed by kayhayen** 2024-11-01 10:14 UTC
Labels: enhancement, factory

**Comment by kayhayen** [comment] 2024-11-16 12:42
Part of the 2.5 release I just made.
