### ISSUE TITLE
Setup fails due to chinese characters

### ISSUE THREAD

**Issue by afeser** [Nuitka/Nuitka#2591] opened 2023-12-06 11:01 UTC
Hi, firstly thanks for the project.

This might be a problem with nuitka, or with the other libraries.
Sorry if duplicate or some other library problem.

### Issue
I'm having issues installing nuitka because of this error (long output below):
```
(my_venv)$ pip3 install nuitka
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 59-60: ordinal not in range(256)
```
I printed the wrong variable:
```
PATH=b'/tmp/pip-req-build-o66w3kq_/tests/programs/chinese_names38/\xe6\xb5\x8b\xe8\xaf\x95/'
```
which ChatGPT explains as:
```
\xe6\xb5\x8b\xe8\xaf\x95 represents Unicode characters encoded in UTF-8. When decoded, these bytes correspond to the Chinese characters for "测试" which means "test" in English.
```

### Which version?
This happens any version starting with 1.9.x.
I also tried with older versions, and 1.8.x seems to be fine, and it stops working after version 1.9.0.
Develop also produces the same error:
```
$ python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 59-60: ordinal not in range(256)
```

### Other packages
I use virtual environment, and python 3.11:
```
$ python3 --version
Python 3.11.2
```
<details>
<summary>
$ pip freeze
</summary>
anyio==4.1.0
asgiref==3.7.2
asteval==0.9.31
attrs==23.1.0
blinker==1.7.0
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
colorlog==6.8.0
colorzero==2.0
connexion==3.0.3
contourpy==1.2.0
cycler==0.12.1
dill==0.3.7
docopt==0.6.2
Flask==3.0.0
Flask-Cors==4.0.0
fonttools==4.46.0
future==0.18.3
getmac==0.9.4
greenlet==3.0.1
h11==0.14.0
httpcore==1.0.2
httpx==0.25.2
idna==3.6
inflection==0.5.1
itsdangerous==2.1.2
Jinja2==3.1.2
jsonschema==4.20.0
jsonschema-specifications==2023.11.2
kiwisolver==1.4.5
lmfit==1.2.2
MarkupSafe==2.1.3
matplotlib==3.8.2
netifaces==0.11.0
numpy==1.26.2
ordered-set==4.1.0
packaging==23.2
picamerax==21.9.8
Pillow==10.1.0
pipreqs==0.4.13
pyparsing==3.1.1
pyserial==3.5
pytesseract==0.3.10
python-dateutil==2.8.2
python-multipart==0.0.6
python-slugify==8.0.1
PyYAML==6.0.1
referencing==0.31.1
requests==2.31.0
rpds-py==0.13.2
scipy==1.11.4
six==1.16.0
sniffio==1.3.0
SQLAlchemy==2.0.23
starlette==0.33.0
text-unidecode==1.3
typing_extensions==4.8.0
uncertainties==3.1.7
urllib3==2.1.0
waitress==2.1.2
websockets==12.0
Werkzeug==3.0.1
yarg==0.1.9
zstandard==0.22.0
</details>

### Other info
I use Raspberry Pi 4:
```
6.1.0-rpi6-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 12 (bookworm)
Release:	12
Codename:	bookworm
```

### Full error report
<details>
  <summary>
    Full error
  </summary>
<code>
  ERROR: Exception:
Traceback (most recent call last):
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
    status = run_func(*args)
             ^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 419, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 73, in resolve
    collected = self.factory.collect_root_requirements(root_reqs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 491, in collect_root_requirements
    req = self._make_requirement_from_install_req(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 453, in _make_requirement_from_install_req
    cand = self._make_candidate_from_link(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
    super().__init__(
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
    dist = self._prepare_distribution()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
    local_file = unpack_url(
                 ^^^^^^^^^^^
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/operations/prepare.py", line 176, in unpack_url
    unpack_file(file.path, location, file.content_type)
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/utils/unpacking.py", line 240, in unpack_file
    unzip_file(filename, location, flatten=not filename.endswith(".whl"))
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/utils/unpacking.py", line 132, in unzip_file
    ensure_dir(fn)
  File "/opt/diaxxo/venv_diaxxo/lib/python3.11/site-packages/pip/_internal/utils/misc.py", line 107, in ensure_dir
    os.makedirs(path)
  File "<frozen os>", line 225, in makedirs
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 59-60: ordinal not in range(256)
</code>
</details>

Thanks for the great project!

**Comment by kayhayen** [comment] 2023-12-06 11:38
First and foremost, you found a Python bug there, since it seems to falsely assume latin1 encoding, or maybe that is due to your system, I think pip installing that way was done a lot since these files got added. Trying now with `LANG=C` didn't show any error, so not sure what's going on there, or what flavor of Python this is, the 1.8 output would have been good there. I don't think I use Debian 12, only 11, maybe it's pip gotten worse.

But for `install` including the tests is always kind of wrong, but I believe the RPM build might get the tests to run from there, but I am now not sure at all of that. Only excluding the chinese files might be a good idea it seems. I have seen them getting warnings in other instances before.

**Comment by kayhayen** [comment] 2023-12-06 11:39
The tests of Nuitka are not actually installed with a pip install, so it's strange to see that error at all.

**Comment by kayhayen** [comment] 2024-01-26 13:55
Closing for lack of feedback, I just don't know what the environment is.

**Comment by afeser** [comment] 2024-01-26 14:57
@kayhayen thanks for the response.

I did not answer because I thought this was a python bug, and no further action is required.

I cannot try with the initial setup because I replaced the machine images with old 32-bit raspian, but I tried on:
- Debian 13 + python3.11.5
- 32-bit Raspberry Pi image with debian 10 and python3.7.3
- 32-bit Raspberry Pi image with debian 10 and python3.11.1 (compiled from source)
- Debian12 + python3.11 + nuitka==1.9.0 and it did not work (on VM).
- Fedora 39 + Python 3.11.7
- Fedpra 39 + Python 3.12.1

All of them finished successfully.

I think we can keep the issue closed for now since it works fine on all machines.
I can try with the old configuration (Pi-64bit image) when I'm back to office next week.

**Comment by krawalli** [comment] 2024-02-27 10:24
I can reproduce the error within a "special environment" (wine) for every nuitka version after 1.8.6

For me the error message is:
`ERROR: Could not install packages due to an OSError: [WinError 2] File not found: 'C:\\users\\root\\Temp\\pip-install-r7nlwwgb\\nuitka_8d7b7a446e2044308fdd0fb4b261e747\\tests/programs/chinese_names38/\u6d4b\u8bd5'`

The environment might look strange, but i use a docker image to compile to windows in wine - but with the old versions it is working.

Since the installation is in a docker, I can reproduce it and can provide the docker config if its helpful for you to hunt the bug. For me it seems the path building is mixed up "\\" and "/" for that subdir in the tests folder. It should be complete in the windows notation (because its inside wine).

**Comment by kayhayen** [comment] 2024-02-27 10:37
I see, you might want to get in touch with your wine support, I would say, it appears it's not compatible there.

I might change this test into a "generated" test, to avoid it, or remove the test maybe from the public Nuitka, as a workaround, but I don't like that.

**Comment by krawalli** [comment] 2024-02-27 10:42
I don't think the path mixup like `\\tests/programs/` is caused from wine. They might improve the handling. Or its python tests causing the mix?

**Comment by kayhayen** [comment] 2024-02-27 10:46
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Closed** 2024-02-27 10:46 UTC
Labels: bug

**Comment by krawalli** [comment] 2024-02-27 10:54
its working with the factory "release".

Thank you.
