### ISSUE TITLE
ImportError: dlopen failed: library "libz.so.1" not found

### ISSUE THREAD

**Issue by Kry9toN** [Nuitka/Nuitka#2585] opened 2023-11-30 10:47 UTC
### I try compiled my python program with nuitka it success but if i running the `.bin`

```
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/main.py", line 18, in <module>
    from utils.text import *

  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/utils/_init_.py", line 1, in <module utils>
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/utils/function.py", line 5, in <module utils.function>
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/requests/_init_.py", line 43, in <module requests>
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/urllib3/_init_.py", line 13, in <module urllib3>
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/urllib3/exceptions.py", line 7, in <module urllib3.exceptions>
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/http/client.py", line 71, in <module>
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/email/parser.py", line 12, in <module>
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/email/feedparser.py", line 27, in <module>
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/email/_policybase.py", line 7, in <module>
  File "/data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/email/header.py", line 14, in <module>
ImportError: dlopen failed: library "libz.so.1" not found: needed by /data/data/com.termux/files/usr/tmp/onefile_32080_1701340682_372613/binascii.so in namespace (default)
```

### I compiled with command
`python -m nuitka --standalone --onefile --jobs=6 --lto=yes main.py`

**Comment by Kry9toN** [comment] 2023-11-30 18:11
i check with `ldd` in main.dist

```
$ ldd binascii.so
        libandroid-support.so => /data/data/com.termux/files/home/klik/out/main.dist/libandroid-support.so
        libz.so.1 => not found
        libpython3.11.so.1.0 => /data/data/com.termux/files/home/klik/out/main.dist/libpython3.11.so.1.0
        libc.so => /system/lib64/libc.so
        ld-android.so => /system/lib64/ld-android.so
        libdl.so => /system/lib64/libdl.so
        libm.so => /system/lib64/libm.so 
```

**Comment by Kry9toN** [comment] 2023-11-30 18:12
but i have solved with include manuali with this command

`nuitka3 --jobs=6 --lto=yes --standalone --onefile --output-filename=klik --output-dir=out --show-progress --include-data-files=/data/data/com.termux/files/usr/lib/libz.so.1.3=libz.so.1 main.py`

I hope it will be added automatically if needed that libs

**Comment by kayhayen** [comment] 2023-11-30 20:33
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-12-02 10:10
Part of the 1.9.3 release I just made.

**Closed by kayhayen** 2023-12-02 10:10 UTC
Labels: bug, factory

**Comment by dlueth** [comment] 2023-12-05 19:26
@kayhayen is this fixed only for this specific case or in general? Had the same libz issue trying to run an 1.9 binary in a scratch docker container. 1.8 works though. Build step is issued under debian.

**Comment by kayhayen** [comment] 2023-12-06 09:33
@dlueth The libz from a specific Debian/Ubuntu system is not usable on other systems generally. The issue is that e.g. drivers, X11, things that are supposed to come from the OS depend on very specifically their own OS libz version, rendering it non-portable, since only one can be loaded, which is why it was removed. For Android as a target OS that's not true, for Linux it is.

As an aside, building on latest Linux is not recommended for many reasons, not the least being that the Python library is not going to like older systems a lot. In Nuitka commercial I have a tool to build inside an old container with a dedicated Python build so it works on old systems too: https://nuitka.net/doc/commercial.html which does this automatically. But basically you ought to build on CentOS 7 or very old Debian, but for later I am not entirely sure how good it is I fear not as portable.

**Comment by dlueth** [comment] 2023-12-06 10:17
@kayhayen OK, got it - but what about when running a nuitka binary requiring libz in a docker container based on scratch where there is only very limited (or should I say no) OS and, more importantly, no libs?

**Comment by kayhayen** [comment] 2023-12-06 15:16
Without glibc I think it wasn't working very well before, or was it? There is a bunch of libraries actively excluded already now, e.g. `libstdc++.so` or `libdrm.so`, and there is a kind of delicate split of things you can bring to an OS and things you cannot. For me it's more important to target Fedora 38 und Ubuntu 23.10 than that container, that apparently is not a Linux in terms of OS.

**Comment by dlueth** [comment] 2023-12-07 04:54
It did work for me, building the binaries in a Python 3.9 Buster-Slim Container and moving them to scratch in the next buildstep with some additional lib-copying (which is fine) but this did not work for libz for some reason I have not found yet.
