### ISSUE TITLE
Nuitka recursion error on Mac python 3.9 with pygame_ce

### ISSUE THREAD

**Issue by JustRedTTG** [Nuitka/Nuitka#3161] opened 2024-10-21 07:35 UTC
I followed the template best I can

- Please check whether the bug was already reported or fixed. **found similar issue, not the same**

- Please check out if the develop version of Nuitka works better for you. **tried factory**
**nuitka was build from source by nuitka-action**

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

Best I can give you is this:
**nuitka-2.5rc9**
Macos 14 *according to https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources*

>  If you are not providing the full output.

It's in an action, I can't provide the full output

- How did you install Nuitka and Python
Python 3.9, nuitka is from source
GitHub actions

- The specific PyPI names and versions
https://github.com/JustRedTTG/moss-desktop/blob/main/requirements-macOS.txt

- Many times when you get an error from Nuitka, your setup may be special
**no plugins, and the issue is only from nuitka....**

- Also supply a Short, Self Contained, Correct, Example
**It finished the build.**

**Build for Mac using the nuitka action, I used the example**

- Provide in your issue the Nuitka options used
`Nuitka-Options: Used command line options: --standalone --onefile --macos-create-app-bundle --report=compilation-report.xml --include-data-dir=assets=assets --include-data-files=LICENSE=LICENSE --assume-yes-for-downloads --output-dir=build --script-name=run_gui.py`

- Avoid unnecessary options
**I don't think I have anything unnecessary**

- Do *not* report against factory version
**I tested both 🙃**

I'd like to again mention this issue is entirely coming straight from nuitka, with very **obvious log** of the issue  https://pastebin.com/BcvMm831

Very likely an issue due to the python version I believe, but only on Mac

**Comment by kayhayen** [comment] 2024-10-21 08:22
I don't see any reproducer at all, your call stack makes no sense to me, since `RecursionError` is not supposed to happen with small size like that. You are most definitely leaving out crucial information.

**Comment by JustRedTTG** [comment] 2024-10-21 08:27
> I don't see any reproducer at all, your call stack makes no sense to me, since `RecursionError` is not supposed to happen with small size like that. You are most definitely leaving out crucial information.

Take a close look where the recursion occured
```  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nuitka/freezer/DllDependenciesMacOS.py", line 95, in detectBinaryPathDLLsMacOS
    _, sub_result = detectBinaryPathDLLsMacOS(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/nuitka/freezer/DllDependenciesMacOS.py", line 95, in detectBinaryPathDLLsMacOS
    _, sub_result = detectBinaryPathDLLsMacOS(
  [Previous line repeated 981 more times]```
  
981+ times repeated doesn't sound like a small sized recursion

**Comment by kayhayen** [comment] 2024-10-21 09:24
Ah, indeed, now with a reproducer, it's probably easy to fix. You can probably reduce it to a specific package import that we haven't seen apparently yet.

**Comment by JustRedTTG** [comment] 2024-10-21 11:10
I gave you the requirements.txt, hope it's enough

**Comment by KRRT7** [comment] 2024-10-21 11:15
> I gave you the requirements.txt, hope it's enough

you haven't given us the code that we need in order to reproduce this.

**Comment by JustRedTTG** [comment] 2024-10-21 11:16
https://github.com/JustRedTTG/moss-desktop

**Comment by kayhayen** [comment] 2024-10-21 11:26
The most effective way is probably for the `detectBinaryPathDLLsMacOS` to tell us what it was used for when things crash. I don't see myself trying to compile this on macOS with `CPython` as opposed to `GitHub Python` which may well be the culprit.

**Comment by KRRT7** [comment] 2024-10-21 11:40
```
python -m nuitka --standalone --onefile --macos-create-app-bundle --report=compilation-report.xml --include-data-dir=assets=assets --include-data-files=LICENSE=LICENSE --assume-yes-for-downloads --output-dir=build --run moss.py
Nuitka-Options: Used command line options: --standalone --onefile --macos-create-app-bundle --report=compilation-report.xml --include-data-dir=assets=assets
Nuitka-Options: --include-data-files=LICENSE=LICENSE --assume-yes-for-downloads --output-dir=build --run moss.py
Nuitka:WARNING: For application bundles, you ought to specify an icon with '--macos-app-icon'.", otherwise a dock icon may not be present.
Nuitka: Starting Python compilation with Nuitka '2.4.10' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:options-nanny: Note, when using 'pygame', consider using '--macos-create-app-bundle' option. Otherwise high resolution will not be available and a terminal window will
Nuitka-Plugins:options-nanny: open. However for debugging, terminal output is the easiest way to see informative traceback and error information, so launch it from there if possible.
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'unittest' in 'pygame.tests.test_utils.async_sub' (at
Nuitka-Plugins:WARNING: '/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/pygame/tests/test_utils/async_sub.py:16') encountered. It may slow down compilation.
Nuitka-Plugins:WARNING:     Complex topic! More information can be found at https://nuitka.net/info/unwanted-module.html
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 16.0.0).
Nuitka-Scons: Backend linking program with 368 files (no progress information available for this stage).
Nuitka-Scons: Compiled 368 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 368
Nuitka-Reports: Compilation report written to file 'compilation-report.xml'.
Detecting used DLLs: 63.1%|███████████████▊         | 70/111, pygame/_freetype.soTraceback (most recent call last):
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/__main__.py", line 206, in <module>
    main()
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/__main__.py", line 188, in main
    MainControl.main()
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/MainControl.py", line 1155, in main
    _main()
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/MainControl.py", line 1040, in _main
    detectUsedDLLs(
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/freezer/Standalone.py", line 354, in detectUsedDLLs
    _detectUsedDLLs(
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/freezer/Standalone.py", line 259, in _detectUsedDLLs
    used_dll_paths = _detectBinaryDLLs(
                     ^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/freezer/Standalone.py", line 149, in _detectBinaryDLLs
    return detectBinaryPathDLLsMacOS(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/freezer/DllDependenciesMacOS.py", line 95, in detectBinaryPathDLLsMacOS
    _, sub_result = detectBinaryPathDLLsMacOS(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/freezer/DllDependenciesMacOS.py", line 95, in detectBinaryPathDLLsMacOS
    _, sub_result = detectBinaryPathDLLsMacOS(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/freezer/DllDependenciesMacOS.py", line 95, in detectBinaryPathDLLsMacOS
    _, sub_result = detectBinaryPathDLLsMacOS(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  [Previous line repeated 981 more times]
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/freezer/DllDependenciesMacOS.py", line 83, in detectBinaryPathDLLsMacOS
    had_self, resolved_result = _resolveBinaryPathDLLsMacOS(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/freezer/DllDependenciesMacOS.py", line 181, in _resolveBinaryPathDLLsMacOS
    rpaths = _detectBinaryRPathsMacOS(original_dir, binary_filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/freezer/DllDependenciesMacOS.py", line 340, in _detectBinaryRPathsMacOS
    stdout = getOtoolListing(binary_filename)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/utils/SharedLibraries.py", line 282, in getOtoolListing
    return _getOToolCommandOutput("-l", filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/utils/SharedLibraries.py", line 264, in _getOToolCommandOutput
    command = ("otool",) + _getMacOSArchOption() + (otool_option, filename)
                           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/utils/SharedLibraries.py", line 253, in _getMacOSArchOption
    macos_target_arch = getMacOSTargetArch()
                        ^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/Options.py", line 2171, in getMacOSTargetArch
    macos_target_arch = getArchitecture()
                        ^^^^^^^^^^^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/utils/Utils.py", line 283, in getArchitecture
    if getOS() == "Windows":
       ^^^^^^^
  File "/Users/krrt7/miniforge3/envs/nuitka_env/lib/python3.11/site-packages/nuitka/utils/Utils.py", line 24, in getOS
    result = os.uname()[0]
             ^^^^^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object
``` I can reproduce this locally

**Comment by JustRedTTG** [comment] 2024-10-21 12:37
> Thanks for your report

You're welcome!

>this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html
> 
> Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

Still failing as of now on factory branch lmn when fix is pushed or to test

**Comment by kayhayen** [comment] 2024-10-21 12:43
With factory, it ought to tell us, which DLL it was working on

**Comment by kayhayen** [comment] 2024-10-21 12:57
I think we cover pygame in Nuitka-Watch, so this either new, or specific to GitHub Actions, but I guess @KRRT7 you didn't use, was it CPython?

**Comment by JustRedTTG** [comment] 2024-10-21 13:01
> I think we cover pygame in Nuitka-Watch, so this either new, or specific to GitHub Actions, but I guess @KRRT7 you didn't use, was it CPython?

Notice this is `_freetype.cpython-39-darwin.so` ***39** I am guessing refers to python 3.9 maybe you missed something there?
Oh also I use `pygame-ce` in `pygameextra`, perhaps that has something to do with it?

**Comment by kayhayen** [comment] 2024-10-22 10:00
I think for wheels, the name doesn't tell me if you use it in Homebrew or CPython, they both will let you install it, for as long as it's a 3.9 and offering the ABI it think that does. That is why I care, if CPython has it, or not. If it did, I would install it and check it out. As for Homebrew, I do not really have a good chance at reproducing what anybody has as it's rolling release and very dirty installations often.

**Comment by kayhayen** [comment] 2024-10-22 10:11
So, yes, in Nuitka-Watch, it's not happening on macOS (so far). Maybe a PyPI update would be needed, but my suspect would be that a recursion is triggered by an unrecognized self-dependency on something in Homebrew.

```
~/repos/Nuitka-Watch$ git grep _freetype.c | grep macOS
cases/PyGame/opengl-example/result/PyGame-latest/3.10-macOS/compilation-report.xml:  <module name="pygame._freetype" kind="PythonExtensionModule" usage="plugin:implicit-imports" reason="Extension module needed for standalone mode." source_path="${sys.prefix}/lib/python3.10/site-packages/pygame/_freetype.cpython-310-darwin.so" distribution="pygame">
cases/PyGame/opengl-example/result/PyGame-latest/3.10-macOS/compilation-report.xml:  <included_extension name="_freetype.so" dest_path="pygame/_freetype.so" source_path="${sys.prefix}/lib/python3.10/site-packages/pygame/_freetype.cpython-310-darwin.so" package="pygame" ignored="no" reason="used extension module" />
cases/PyGame/opengl-example/result/PyGame-latest/3.11-macOS/compilation-report.xml:  <module name="pygame._freetype" kind="PythonExtensionModule" usage="plugin:implicit-imports" reason="Extension module needed for standalone mode." source_path="${sys.prefix}/lib/python3.11/site-packages/pygame/_freetype.cpython-311-darwin.so" distribution="pygame">
cases/PyGame/opengl-example/result/PyGame-latest/3.11-macOS/compilation-report.xml:  <included_extension name="_freetype.so" dest_path="pygame/_freetype.so" source_path="${sys.prefix}/lib/python3.11/site-packages/pygame/_freetype.cpython-311-darwin.so" package="pygame" ignored="no" reason="used extension module" />
```

I will run a PyPI update for macOS on the specific case right now. But I start to suspect, that it's pre-release software being used that is maybe built even worse than usual. Again I am noticing, that I don't even know, what pygame version you end up having installed. The issue template exists for a reason. Arguably, something in Nuitka-Action needs to make it easy to fill out, but I am way too tolerant again.

**Comment by kayhayen** [comment] 2024-10-22 10:16
```
Nuitka-Plugins:WARNING: anti-bloat: Undesirable import of 'unittest' in            
Nuitka-Plugins:WARNING: 'pygame.tests.test_utils.async_sub' (at
Nuitka-Plugins:WARNING: '/Users/hayen/.local/share/virtualenvs/3.11-macOS-0EIn_UYd/lib/python3.11/site-packages/pygame/tests/test_utils/async_sub.py:16')
Nuitka-Plugins:WARNING: encountered. It may slow down compilation.
```

That is new, seems it includes its tests into compilation now, which is very bad, but when I compare the reports from 2.6.0 and 2.6.1, it doesn't show up as new, so that's probably already there for a while.

**Comment by JustRedTTG** [comment] 2024-10-22 10:20
```
Collecting pygame-ce (from pygameextra==2.0.0a82->-r requirements-macOS.txt (line 3))
  Downloading pygame_ce-2.5.1-cp39-cp39-macosx_11_0_arm64.whl.metadata (11 kB)
```

This the pygame_ce version being installed

**Comment by JustRedTTG** [comment] 2024-10-22 14:34
here's all of them actually
```
PyJWT-2.9.0 appdirs-1.4.4 charset-normalizer-3.4.0 colorama-0.4.6 deprecation-2.1.0 frozendict-2.4.6 idna-3.10 imageio-2.36.0 numpy-2.0.2 packaging-24.1 pillow-10.4.0 pygame-ce-2.5.1 pygameextra-2.0.0a82 pyperclip-1.9.0 python-box-7.2.0 requests-2.32.3 urllib3-2.2.3 websocket-client-1.8.0
```

**Comment by kayhayen** [comment] 2024-10-23 08:37
Interesting, I read up about pygame_ce on the PyPI page, probably just need to copy our example in Nuitka-Watch, and then maybe see your issue, but I don't have the time for it today, but I guess, that should be what I need for input.

**Comment by JustRedTTG** [comment] 2024-10-25 10:12
I did some testing, this is in fact, only an issue with `pygame_ce`, I tried to uninstall it and install `pygame` and both `pygame` version `2.6.1` and `2.5.1` to try and match `pygame_ce==2.5.1` both yielded a successful build. So `pygame_ce` is breaking something here.

**Comment by kayhayen** [comment] 2024-10-29 07:56
I tried this today, and on Linux it was works, adding the case now so I can run it on macOS.

**Comment by kayhayen** [comment] 2024-10-29 10:12
So, I managed indeed to see this fail in the new Nuitka-Watch case and I am debugging it in CPython right now. It feels it should be easy, but I am not seeing the direct cycle, this might be a real cycle, which is very strange.

**Comment by kayhayen** [comment] 2024-10-29 10:39
So this is the extract of a trace output, where I added a level, and chose the descending path only, it seems there is an actual cycle in the DLL dependencies, something bad we have not seen before:

```
otool -L /Library/Frameworks/Python.fra
mework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libharfbuzz.0.dylib 
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libharfbuzz.0.dylib:
        /DLC/pygame/.dylibs/libharfbuzz.0.dylib (compatibility version 61001.0.0, current version 61001.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.120.2)
        @loader_path/libfreetype.6.dylib (compatibility version 27.0.0, current version 27.2.0)
```

and

```
otool -L /Library/Frameworks/Python.fra
mework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libfreetype.6.dylib 
/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/pygame/.dylibs/libfreetype.6.dylib:
        /DLC/pygame/.dylibs/libfreetype.6.dylib (compatibility version 27.0.0, current version 27.2.0)
        @loader_path/libpng16.16.dylib (compatibility version 61.0.0, current version 61.0.0)
        @loader_path/libz.1.3.1.zlib-ng.dylib (compatibility version 1.0.0, current version 1.3.1)
        @loader_path/libharfbuzz.0.dylib (compatibility version 61001.0.0, current version 61001.0.0)
        @loader_path/libbrotlidec.1.1.0.dylib (compatibility version 1.0.0, current version 1.1.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1345.120.2)
```

That's probably a build system mistake that they do there. But I am not to judge, I am to be compatible with whatever buggy DLL dependencies are thrown at Python. The macOS handles so many errors gracefully, of course people make them all. This is still a first.

We would during a DLL dependency scan, have to know the dependencies resolved so far and ignore those. Makes me happy we only cache otool calls and not the processing result.

**Comment by kayhayen** [comment] 2024-10-29 12:35
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by JustRedTTG** [comment] 2024-10-29 17:09
I can confirm that it works. Glad my report was helpful!

**Comment by kayhayen** [comment] 2024-11-16 12:45
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:45 UTC
Labels: bug, develop
