### ISSUE TITLE
Nuitka removes local variable assigned in exception handle only

### ISSUE THREAD

**Issue by uralbash** [Nuitka/Nuitka#2847] opened 2024-05-13 10:01 UTC
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

```
2.2.1
Commercial: None
Python: 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]
Flavor: Debian Python
Executable: /home/user/.cache/pypoetry/virtualenvs/app-ZYa12SXG-py3.11/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.3
Version C compiler: /usr/bin/gcc (gcc 11).
```

- How did you install Nuitka and Python

   > poetry add nuitka@latest

- The specific PyPI names and versions

  > python -m pip freeze
  > Nuitka==2.2.1 

- Also supply a Short, Self Contained, Correct, Example

*test.py*
```

def calculate():
    try:
        basestring
    except Exception:
        basestring = (str, bytes)

    names = "asd"

    if isinstance(names, basestring):
        print("foo")

calculate()
```

run0:

   > python test.py
   > foo

build1:

   > python -m nuitka test.py

run1:

   > ./test.bin
   > foo

build2:

   > python -m nuitka test.py --onefile

run2:

   > ./test.bin
  
```
Traceback (most recent call last):
  File "/tmp/onefile_3196157_1715595054_140575/test.py", line 13, in <module>
    calculate()
    
  File "/tmp/onefile_3196157_1715595054_140575/test.py", line 9, in calculate
    if isinstance(names, basestring):

UnboundLocalError: cannot access local variable 'basestring' where it is not associated with a value

```

*test3.py*
```
def calculate():
    try:
        basestring
    except Exception as e:
        basestring = (str, bytes)

    names = "asd"

    if isinstance(names, basestring):
        print("foo")

calculate()
```
build3:

   > python -m nuitka test3.py --onefile

run3:

   > ./test3.bin
   > foo

**Comment by kayhayen** [comment] 2024-05-13 16:13
I wonder how you can make such a minimal case and still report it as "--onefile" related. I have reproduced it in accelerated mode of course.

**Comment by kayhayen** [comment] 2024-05-13 16:15
Somehow the exception handle is becoming empty with just that statement, and that is of course puzzling. It might be a that an assignment of a constant value is not handled properly there.

**Comment by kayhayen** [comment] 2024-05-13 16:21
So, it says this:

> Nuitka-Optimization: Mini.py:6 : new_statements : Dropped propagated assignment statement to 'basestring'.

pointing to the assignment, but the propagation should end up in the `isinstance` call, and that is not happening, but this is:

> Nuitka-Optimization: Mini.py:10 : new_raise : Variable access of not initialized variable 'basestring'

So the question is, how is that happening.

**Comment by kayhayen** [comment] 2024-05-14 06:36
So, the conditional statement is to blame. When the assignment is propagated, it does so in a branch and then removes the assignment statement, after which the branch becomes empty. As an optimization, a branch that became empty doesn't have its value trace merged because it obviously doesn't do anything. Well, therefore, the effect of the removed assignment is not propagated, adding any other statement there will prevent that from happening. Your as `e` implies a deletion of `e` at the end of the exception handler (the conditional branch in this case), and that is why it doesn't show. 

Removing that optimization is going to fix it. The performance impact is probably minor, as branches that become empty during optimization will be rare. Since `pass` is optimized away directly, in most cases, that won't matter, but what's more important is that we have no way of knowing if it's necessary.

**Comment by kayhayen** [comment] 2024-05-14 07:16
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by uralbash** [comment] 2024-05-15 11:14
Everything works with factory. Thanks!

> $  python -m nuitka --version                                                       
```
2.3rc3                                                                               
Commercial: None                                                                     
Python: 3.11.7 (main, Dec  8 2023, 18:56:58) [GCC 11.4.0]                            
Flavor: Debian Python                                                                
Executable: /home/user/.cache/pypoetry/virtualenvs/app-ZYa12SXG-py3.11/bin/python
OS: Linux                                                                            
Arch: x86_64                                                                         
Distribution: Ubuntu (based on Debian) 22.04.3                                       
Version C compiler: /usr/bin/gcc (gcc 11).                                           
```

**Comment by kayhayen** [comment] 2024-05-16 09:26
Part of the 2.2.2 hotfix I made.

**Closed by kayhayen** 2024-05-16 09:26 UTC
Labels: bug, excellent_report
