### ISSUE TITLE
cannot import gssapi library properly

### ISSUE THREAD

**Issue by Betula-L** [Nuitka/Nuitka#3053] opened 2024-08-08 05:35 UTC
- How to reproduce it? 
  Install library by pip 
  ```
  pip install gssapi
  ```
  Try run import scripts `python test.py`
  ```
  import gssapi.raw.cython_converters
  print("GSSAPI module loaded successfully.")
  ```
  Everything is ok.
  ```
  GSSAPI module loaded successfully.
  ```
  Build script by nuitka
  ```
  nuitka --follow-imports --standalone test.py
  ```
  Run `./test.dist/test.bin`
  ```
   Traceback (most recent call last):
    File "/workspace/test.dist/test.py", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "/workspace/test.dist/gssapi/__init__.py", line 31, in <module gssapi>
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "/workspace/test.dist/gssapi/raw/__init__.py", line 118, in <module gssapi.raw>
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "gssapi/raw/ext_iov_mic.pyx", line 31, in init gssapi.raw.ext_iov_mic
    File "/workspace/test.dist/enum.py", line 429, in __getattr__
    AttributeError: mic_token
    ```

- What's wrong? 
   Nutika do not import library in `_enum_extensions`. 
   It don't work by add `--include-module=gssapi` or `--include-data-dir`
![image](https://github.com/user-attachments/assets/64c4279c-c1d1-4f80-8de9-961bd4bc4c29)
![image](https://github.com/user-attachments/assets/2d4a6c88-40fa-4c1c-82e7-bb541b141dee)
![image](https://github.com/user-attachments/assets/583f21cf-95fd-4cde-849a-a4b26fe63e6e)
   If i copy `_enum_extensions` to ./test.dist/gssapi/raw/, the binary works fine. 

- Nuitka version
```
2.4.5
Commercial: None
Python: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0]
Flavor: Anaconda Python
Executable: /opt/conda/envs/merged/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 20.04.6
Version C compiler: /usr/bin/gcc (gcc 9).
```

**Comment by kayhayen** [comment] 2024-10-19 09:57
So, I can reproduce this even with Ubuntu Python, and I am trying to make sense out of the folder missing, that seems to be modules, so I was using `--include-package=gssapi.raw._enum_extensions` but it doesn't cause it to include the extension modules I think are living there.

``` # removed Python cache files
find /home/hayen/.local/lib/python3.12/site-packages/gssapi/raw/_enum_extensions/
/home/hayen/.local/lib/python3.12/site-packages/gssapi/raw/_enum_extensions/
/home/hayen/.local/lib/python3.12/site-packages/gssapi/raw/_enum_extensions/ext_iov_mic.cpython-312-x86_64-linux-gnu.so
/home/hayen/.local/lib/python3.12/site-packages/gssapi/raw/_enum_extensions/__init__.py
/home/hayen/.local/lib/python3.12/site-packages/gssapi/raw/_enum_extensions/ext_dce.cpython-312-x86_64-linux-gnu.so
```

**Comment by kayhayen** [comment] 2024-10-19 09:58
So, that would be sort of a bug if that option it seems, the compilation report doesn't contain them, and for ignored files, it doesn't say why, but I bet it's only going for Python code. Lets first make that workaround be good, then create package configuration to include them, which probably would work even now, but I like those things to be equally good.

**Comment by kayhayen** [comment] 2024-10-19 10:09
Indeed, when including a package with that option, it was only considering Python files and sub-packages, but not extension module files, so that makes it now work.

**Comment by kayhayen** [comment] 2024-10-19 10:28
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-10-24 18:27
This is part of the current pre-release and will be in 2.5 release.

**Comment by kayhayen** [comment] 2024-11-16 12:48
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:48 UTC
Labels: bug, develop, excellent_report
