### ISSUE TITLE
ModuleNotFoundError: No module named 'aspose.threed.formats'; 'aspose.threed' is not a package

### ISSUE THREAD

**Issue by Puiching-Memory** [Nuitka/Nuitka#2825] opened 2024-04-24 13:49 UTC
Python  3.11.9
Nuitka  2.1.6
aspose-3d  24.2.0

command `python -m nuitka run.py --onefile --jobs=16 --lto=yes`

main code 
```
from aspose.threed import Scene, FileFormat
from aspose.threed.formats import GltfSaveOptions
```

Error reporting
This problem does not occur during the compilation phase, but during the running of the exe phase
command `PS D:\AM\AM_Server> ./run.exe`
```
Traceback (most recent call last):
  File "C:\Users\1138\AppData\Local\Temp\ONEFIL~2\run.py", line 16, in <module>
    import aspose_engine

  File "C:\Users\1138\AppData\Local\Temp\ONEFIL~2\aspose_engine.py", line 3, in <module aspose_engine>
    from aspose.threed.formats import GltfSaveOptions

ModuleNotFoundError: No module named 'aspose.threed.formats'; 'aspose.threed' is not a package
```

**Comment by kayhayen** [comment] 2024-04-24 18:31
The same happens with `aspose.email` so it's not specific to `aspose-3d` distribution, it just wasn't observed before I guess.

**Comment by kayhayen** [comment] 2024-04-24 18:33
It is normal for extension modules to not have `__path__`, e.g. `AttributeError: module 'lxml.etree' has no attribute '__path__'` for lxml, so this must be them setting it, and maybe Nuitka unsettling it.

**Comment by kayhayen** [comment] 2024-04-24 18:45
It seems `__path__` is not set by the extension module, I wonder how Python decides to set it then in its loader.

**Comment by kayhayen** [comment] 2024-04-24 19:06
So, the `no-follow` is applied once has been decided `aspose.email` and only then `aspose.*` is going to be added, which would prevent that, adding `import aspose` at the beginning, will restore that. This is a weakness of the recursion of used modules, that will use a child module, and then its parent from there, and another parent from there, and not the other way around, this will be fixed by considering used module names in descending order, which will allow parent imports to influence child import decisions.

**Comment by kayhayen** [comment] 2024-04-25 09:35
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by Puiching-Memory** [comment] 2024-04-25 10:15
I followed the link to download the factory version.
` nuitka --version`
output is
```
2.2rc5
Commercial: None
Python: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: D:\Python\3119\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: D:\Visual Studio\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).
```

Run the same command
`python -m nuitka run.py --onefile --jobs=16 --lto=yes`

Everything is fine in the compilation phase
```
Nuitka-Options: Used command line options: run.py --onefile --jobs=16 --lto=yes
Nuitka: Starting Python compilation with Nuitka '2.2rc5' on Python '3.11' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 587 files (no progress information available for this stage).
Nuitka-Scons: Compiled 587 C files using clcache with 0 cache hits and 587 cache misses.
Nuitka-Plugins:dll-files: Found 1 file DLLs from cv2 installation.
Nuitka-Plugins:data-files: Included 229 data files due to package data for 'aspose'.
Nuitka-Plugins:data-files: Included 603 data files due to package data directory 'zoneinfo' for 'pytz'.
Nuitka-Plugins:data-files: Included 603 data files due to package data directory '.' for 'tzdata.zoneinfo'.
Nuitka-Postprocessing: Creating single file from dist folder, this may take a while.
Nuitka-Onefile: Running bootstrap binary compilation via Scons.
Nuitka-Scons: Onefile C compiler: cl (cl 14.3).
Nuitka-Scons: Onefile linking program with 1 files (no progress information available for this stage).
Nuitka-Scons: Compiled 1 C files using clcache with 0 cache hits and 1 cache misses.
Nuitka-Onefile: Using compression for onefile payload.
Nuitka-Onefile: Onefile payload compression ratio (26.50%) size 315340208 to 83579998.
Nuitka-Onefile: Keeping onefile build directory 'run.onefile-build'.
Nuitka: Keeping dist folder 'run.dist' for inspection, no need to use it.
Nuitka: Keeping build directory 'run.build'.
Nuitka: Successfully created 'run.exe'
```

Now try running the exe
`PS D:\AM\AM_Server> ./run.exe`

```
Traceback (most recent call last):
  File "C:\Users\1138\AppData\Local\Temp\ONEFIL~2\run.py", line 16, in <module>
    import aspose_engine

  File "C:\Users\1138\AppData\Local\Temp\ONEFIL~2\aspose_engine.py", line 3, in <module aspose_engine>
    from aspose.threed.formats import GltfSaveOptions

ModuleNotFoundError: No module named 'aspose.threed.formats'; 'aspose.threed' is not a package
```

Rummaging through the run.dist folder, I found that the aspose.threed module had been included into the folder. Path: run. Dist/aspose/threed.pyd

run run.exe in the run.dist folder:
`PS D:\AM\AM_Server\run.dist> ./run.exe`

```
Traceback (most recent call last):
  File "D:\AM\AM_SER~1\RUN~1.DIS\run.py", line 16, in <module>
  File "D:\AM\AM_SER~1\RUN~1.DIS\aspose_engine.py", line 3, in <module aspose_engine>
ModuleNotFoundError: No module named 'aspose.threed.formats'; 'aspose.threed' is not a package
```

**Comment by Puiching-Memory** [comment] 2024-04-25 11:06
The temporary solution is to copy all of aspose's files into the project folder.
The code used needs some modification：
```
#import aspose.threed
#import aspose.threed.formats

exec('import aspose.threed')
exec('import aspose.threed.formats')
print('import aspose m',aspose.threed,aspose.threed.formats)
```
I think this will bypass nuitka's processing and import aspose dynamically instead.
The disadvantage is that the aspose library will act as a separate folder and cannot be integrated into a single exe file

**Comment by kayhayen** [comment] 2024-04-25 17:00
So, it seems that I fixed the `__path__` issue, which is an ordering problem of the plugin, and it fixes the more minimal reproducer, but indeed not the original issue, meaning there has to be one more point to apply the fix I guess.

**Comment by kayhayen** [comment] 2024-04-25 17:25
So, what is going on, is that I initially added injection of parent module usages when the usage of the child occurs, but I didn't want to remove the injection for parent module usages that was already there for failure cases, but this forces to make decisions relatively early, so 2 levels of nesting can cause an error now. I will push this outwards and apply to all imports, builtin, hard, fixed, etc. and then it should be good, more invasive that I would like, but obviously need to do that for the "no-follow" Yaml to take effect in all cases.

**Comment by kayhayen** [comment] 2024-04-25 17:50
So, I didn't want to go all the way, but current factory has a the all covering change for all forms of imports, and the workarounds that caused the issue to persist removed, since they are no longer needed. The minimal reproducer given works now as well.

**Comment by kayhayen** [comment] 2024-04-25 17:53
Let me know if this works for you, I need to decide if this is 2.2 or 2.3 material, and if it's not working for you, I don't think I take the risk now.

**Comment by kayhayen** [comment] 2024-04-30 08:34
I made this part of the 2.2 due to the technical debt aspect, delaying it for a bit unfortunately.

**Closed by kayhayen** 2024-04-30 08:34 UTC
Labels: bug, factory
