### ISSUE TITLE
Error pywin32 (win32ui)

### ISSUE THREAD

**Issue by Pro100rus32** [Nuitka/Nuitka#1311] opened 2021-12-12 19:15 UTC
Tested on python 3.10.1 and 3.9.9 with nuitka 0.6.18.3 on Windows 11(x86_64)

Version **pywin32**:
302 - NotWorking (photo1)
300 - Working (but does not support python 3.10)

![image](https://user-images.githubusercontent.com/64806740/145725830-9b5b76a2-ad9d-4a3c-8511-c118acf6e2b1.png)(1)

**Comment by kayhayen** [comment] 2021-12-13 07:54
Not a lof of information in terms of reproducer, please do not skip the issue template.

**Comment by Pro100rus32** [comment] 2021-12-13 13:47
**Code:**
```
import win32api
import win32ui
```

`python -m nuitka --mingw64 --standalone "D:\Test.py"`

**Comment by kayhayen** [comment] 2021-12-14 09:17
I managed to reproduce this one. I too am on 302.

**Comment by Pro100rus32** [comment] 2021-12-14 14:17
**Alas, it doesn't work.** 

```
Problem with statement at D:\TEST\lib\site-packages\win32com\__init__.py:94:
->         import win32com.gen_py

Problem with statement at D:\TEST\lib\site-packages\win32com\__init__.py:93:
->     try:

Problem with statement at D:\TEST\lib\site-packages\win32com\__init__.py:92:
-> if not __gen_path__:

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': 'D:\\TEST\\lib\\site-packages\\win32com\\__init__.py', 'module_name': <ModuleName win32com>, 'code_flags': ''}>'.
PASS 1:  91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 279/306, win32comTraceback (most recent call last):
  File "D:\TEST\lib\site-packages\nuitka\__main__.py", line 135, in <module>
    main()
  File "D:\TEST\lib\site-packages\nuitka\__main__.py", line 121, in main
    MainControl.main()
  File "D:\TEST\lib\site-packages\nuitka\MainControl.py", line 902, in main
    main_module = _createNodeTree(filename=filename)
  File "D:\TEST\lib\site-packages\nuitka\MainControl.py", line 189, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "D:\TEST\lib\site-packages\nuitka\optimizations\Optimization.py", line 350, in optimizeModules
    finished = makeOptimizationPass()
  File "D:\TEST\lib\site-packages\nuitka\optimizations\Optimization.py", line 312, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "D:\TEST\lib\site-packages\nuitka\optimizations\Optimization.py", line 207, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "D:\TEST\lib\site-packages\nuitka\optimizations\Optimization.py", line 103, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "D:\TEST\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 536, in computeModule
    result = module_body.computeStatementsSequence(
  File "D:\TEST\lib\site-packages\nuitka\nodes\StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "D:\TEST\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\TEST\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 581, in computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 912, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "D:\TEST\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\TEST\lib\site-packages\nuitka\nodes\TryNodes.py", line 105, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "D:\TEST\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "D:\TEST\lib\site-packages\nuitka\nodes\AssignNodes.py", line 274, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 594, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "D:\TEST\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1183, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "D:\TEST\lib\site-packages\nuitka\nodes\ImportNodes.py", line 788, in computeExpression
    module_filename = self._attemptFollow(module_name=imported_module_name)
  File "D:\TEST\lib\site-packages\nuitka\nodes\ImportNodes.py", line 698, in _attemptFollow
    module_name, module_filename, self.finding = locateModule(
  File "D:\TEST\lib\site-packages\nuitka\importing\Importing.py", line 675, in locateModule
    assert module_kind is not None, module_filename
AssertionError: C:\Users\andre\AppData\Local\Temp\gen_py\3.9
```

i am use: `pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"`

**I tried to comment out the code. The python script itself works, but the compiled program does not open.**
"...\Lib\site-packages\win32com\__init__.py" | 92*

```
if not __gen_path__:
    #try:
        #import win32com.gen_py

        # hrmph - 3.3 throws: TypeError: '_NamespacePath' object does not support indexing
        # attempting to get __path__[0] - but I can't quickly repro this stand-alone.
        # Work around it by using an iterator.
        #__gen_path__ = next(iter(sys.modules["win32com.gen_py"].__path__))
    #except ImportError:
        # If a win32com\gen_py directory already exists, then we use it
        # (gencache doesn't insist it have an __init__, but our __import__
        # above does!
    #__gen_path__ = os.path.abspath(os.path.join(__path__[0], "gen_py"))
    if not os.path.isdir(__gen_path__):
        # We used to dynamically create a directory under win32com -
        # but this sucks.  If the dir doesn't already exist, we we
        # create a version specific directory under the user temp
        # directory.
        __gen_path__ = os.path.join(
            win32api.GetTempPath(),
            "gen_py",
            "%d.%d" % (sys.version_info[0], sys.version_info[1]),
        )
```

Checked: python 3.9.9 and python 3.10.1

**Comment by Pro100rus32** [comment] 2021-12-14 14:20
**Code:**
`import win32com`

**Comment by kayhayen** [comment] 2021-12-15 10:59
It looks like a different program too, likely an issue with the import changes I am making, I am not aware this can happen, so it will be good to check.

**Comment by kayhayen** [comment] 2021-12-15 11:27
It's attempting to represent a non-existant folder as the one to contain `gen_py`, but with a strange addition, the `3.9`, which makes it hard to accept as a module filename, dots are not welcome there. It seems the code in question also is considering `sys.frozen` which Nuitka doesn't set, and that might be a mistake pywin32 makes, but I am not yet sure of that. 

I like to treat things when I observe them, even if that observation might be due to a bug. First thing is, the pth file puts a `.__path__` that does not exist, which is then unconditionally by Nuitka used as the module location for said package. 

I guess, that's another weakness, Nuitka should filter out non-existant values, as later code will have a hard time to decide if it's file or directory, on the other hand, it will claim the module does not exist, when it does. I might have to add another finding kind, say "pth" and have that, or simply ignore it, but I am guessing, it wants to use that `__path__` later when adding files there, but pth created modules are probably namespace packages, and as a I now learn, their may not have a `__path__` that is available at compile time.

**Comment by kayhayen** [comment] 2021-12-15 11:39
It seems, moving the pth handling out, is good, but I need to check the handling of `finding` values in import nodes, some might be in a need to tolerate it or include it in its handling, although I think having a filename is what is most often wanted.

**Comment by kayhayen** [comment] 2021-12-15 11:48
Ok, now that this is fixed, I have a very strong suspect, that this is all unnecessary, since it just leads to not including the module, and the package init of `win32com` then creates it in memory. In fact, it would seem as if including it from the local compilation could well be an error, but I have no idea about that. They might be and would have been. I guess, my pywin32 is not used, and has nothing in temp therefore, which is why I had this. But you did you.

**Comment by kayhayen** [comment] 2021-12-15 11:52
It seems the frozen using code, does not open the registry and search for things there to offer to be user. I am guessing, that it would be a good idea for standalone, to no do that. @Pro100rus32 any idea if that should be removed?

**Comment by Pro100rus32** [comment] 2021-12-15 17:54
I tested this code:
```
import win32gui
import win32com
import win32con
import win32api
import win32ui
```
**It all working on python 3.9 and python 3.10**

----------------------

The code I commented out above has no effect on the this library in python 3.9 and 3.10 (I did not notice any difference)

It works fine in python, but has the same problem with nuitka.
I'm not sure if it's ok to remove this code, because I don't know what exactly it can affect. (I can't check all functions of the library, I don't have time) I tried several functions, and they worked fine.
![image](https://user-images.githubusercontent.com/64806740/146238383-022b5837-baea-427d-86c3-0b7eeb4511f6.png)


_Can I create a new problem for python 3.10, or do you not accept them yet?_

**Comment by kayhayen** [comment] 2021-12-15 18:32
I think you may not be using the correct code, that is the original error, or maybe I have with fixes since damaged it, as there were a few issues.

**Comment by kayhayen** [comment] 2021-12-15 18:45
You most likely are using the wrong version of Nuitka, this works now.

**Comment by Pro100rus32** [comment] 2021-12-15 19:27
Now everything works, I apologize!

My pycharm seems to be broken))
![image](https://user-images.githubusercontent.com/64806740/146251977-f10e0942-f082-411c-bbc3-ba9790335aa1.png)

**Comment by kayhayen** [comment] 2021-12-15 19:28
@Pro100rus32 you mean it just aborts installing?

**Comment by Pro100rus32** [comment] 2021-12-15 19:54
> @Pro100rus32 you mean it just aborts installing?

Yes!

The version from the factory is not updated if another older version from the factory is installed. I have to uninstall nuitka and reinstall - it's solved my problem.

-------
Reinstalling the environment did not help, the problem seems to be in the installation itself.

**Comment by kayhayen** [comment] 2021-12-16 12:07
Uh oh, maybe that is because `setup.py` started using `nuitka` module.

**Comment by kayhayen** [comment] 2021-12-16 12:08
No actually, I think it's doing it the correct way, using this code:

```
import os
import sys

os.chdir(os.path.dirname(__file__) or ".")
sys.path.insert(0, os.path.abspath(os.getcwd()))

# isort:start
```

That ought to make sure, `nuitka` is loaded from where `setup.py` lives...

**Comment by kayhayen** [comment] 2021-12-16 12:13
But I indeed managed to reproduce this in a Debian python3 created virtualenv. It seems the `-U` is not enough to make it reinstall things, but `--force` will be needed. At least in that case it did install things. I need to re-read docs for `-U` apparently.

**Comment by kayhayen** [comment] 2021-12-16 12:16
Well, since the factory version doesn't change, the second time around, `--force-reinstall` is needed. I will update the factory instructions, this may have hit more people in the past. It at least explains why technical savy people have had been using the wrong code over and over. :)

**Comment by kayhayen** [comment] 2021-12-16 13:18
These changes were touching code that has changed, not doing a hotfix anymore, this will be in the next release.

**Comment by zhusihan-python** [comment] 2021-12-30 03:05
> **Alas, it doesn't work.**
> 
> ```
> Problem with statement at D:\TEST\lib\site-packages\win32com\__init__.py:94:
> ->         import win32com.gen_py
> 
> Problem with statement at D:\TEST\lib\site-packages\win32com\__init__.py:93:
> ->     try:
> 
> Problem with statement at D:\TEST\lib\site-packages\win32com\__init__.py:92:
> -> if not __gen_path__:
> 
> Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': 'D:\\TEST\\lib\\site-packages\\win32com\\__init__.py', 'module_name': <ModuleName win32com>, 'code_flags': ''}>'.
> PASS 1:  91%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████                           | 279/306, win32comTraceback (most recent call last):
>   File "D:\TEST\lib\site-packages\nuitka\__main__.py", line 135, in <module>
>     main()
>   File "D:\TEST\lib\site-packages\nuitka\__main__.py", line 121, in main
>     MainControl.main()
>   File "D:\TEST\lib\site-packages\nuitka\MainControl.py", line 902, in main
>     main_module = _createNodeTree(filename=filename)
>   File "D:\TEST\lib\site-packages\nuitka\MainControl.py", line 189, in _createNodeTree
>     optimizeModules(main_module.getOutputFilename())
>   File "D:\TEST\lib\site-packages\nuitka\optimizations\Optimization.py", line 350, in optimizeModules
>     finished = makeOptimizationPass()
>   File "D:\TEST\lib\site-packages\nuitka\optimizations\Optimization.py", line 312, in makeOptimizationPass
>     changed = optimizeModule(current_module)
>   File "D:\TEST\lib\site-packages\nuitka\optimizations\Optimization.py", line 207, in optimizeModule
>     changed = optimizeCompiledPythonModule(module)
>   File "D:\TEST\lib\site-packages\nuitka\optimizations\Optimization.py", line 103, in optimizeCompiledPythonModule
>     scopes_were_incomplete = module.computeModule()
>   File "D:\TEST\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 536, in computeModule
>     result = module_body.computeStatementsSequence(
>   File "D:\TEST\lib\site-packages\nuitka\nodes\StatementNodes.py", line 163, in computeStatementsSequence
>     new_statement = statement.computeStatementsSequence(trace_collection)
>   File "D:\TEST\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
>     new_statement = trace_collection.onStatement(statement=statement)
>   File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
>     new_statement, change_tags, change_desc = statement.computeStatement(self)
>   File "D:\TEST\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 581, in computeStatement
>     branch_yes_collection.computeBranch(branch=yes_branch)
>   File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 912, in computeBranch
>     result = branch.computeStatementsSequence(trace_collection=self)
>   File "D:\TEST\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
>     new_statement = trace_collection.onStatement(statement=statement)
>   File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
>     new_statement, change_tags, change_desc = statement.computeStatement(self)
>   File "D:\TEST\lib\site-packages\nuitka\nodes\TryNodes.py", line 105, in computeStatement
>     result = tried.computeStatementsSequence(trace_collection=trace_collection)
>   File "D:\TEST\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
>     new_statement = trace_collection.onStatement(statement=statement)
>   File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
>     new_statement, change_tags, change_desc = statement.computeStatement(self)
>   File "D:\TEST\lib\site-packages\nuitka\nodes\AssignNodes.py", line 274, in computeStatement
>     source = trace_collection.onExpression(self.subnode_source)
>   File "D:\TEST\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 594, in onExpression
>     r = expression.computeExpressionRaw(trace_collection=self)
>   File "D:\TEST\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1183, in computeExpressionRaw
>     return self.computeExpression(trace_collection=trace_collection)
>   File "D:\TEST\lib\site-packages\nuitka\nodes\ImportNodes.py", line 788, in computeExpression
>     module_filename = self._attemptFollow(module_name=imported_module_name)
>   File "D:\TEST\lib\site-packages\nuitka\nodes\ImportNodes.py", line 698, in _attemptFollow
>     module_name, module_filename, self.finding = locateModule(
>   File "D:\TEST\lib\site-packages\nuitka\importing\Importing.py", line 675, in locateModule
>     assert module_kind is not None, module_filename
> AssertionError: C:\Users\andre\AppData\Local\Temp\gen_py\3.9
> ```
> 
> i am use: `pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"`
> 
> **I tried to comment out the code. The python script itself works, but the compiled program does not open.** "...\Lib\site-packages\win32com__init__.py" | 92*
> 
> ```
> if not __gen_path__:
>     #try:
>         #import win32com.gen_py
> 
>         # hrmph - 3.3 throws: TypeError: '_NamespacePath' object does not support indexing
>         # attempting to get __path__[0] - but I can't quickly repro this stand-alone.
>         # Work around it by using an iterator.
>         #__gen_path__ = next(iter(sys.modules["win32com.gen_py"].__path__))
>     #except ImportError:
>         # If a win32com\gen_py directory already exists, then we use it
>         # (gencache doesn't insist it have an __init__, but our __import__
>         # above does!
>     #__gen_path__ = os.path.abspath(os.path.join(__path__[0], "gen_py"))
>     if not os.path.isdir(__gen_path__):
>         # We used to dynamically create a directory under win32com -
>         # but this sucks.  If the dir doesn't already exist, we we
>         # create a version specific directory under the user temp
>         # directory.
>         __gen_path__ = os.path.join(
>             win32api.GetTempPath(),
>             "gen_py",
>             "%d.%d" % (sys.version_info[0], sys.version_info[1]),
>         )
> ```
> 
> Checked: python 3.9.9 and python 3.10.1

im using pywin32 == 303 on win10 py39, get this error too, now it works fine after update by
pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"
thanks

**Comment by kayhayen** [comment] 2021-12-30 05:14
Commenting out assertions in Nuitka, really? Why don't people just try the develop version.

**Comment by Pro100rus32** [comment] 2022-01-07 18:26
Code:
import win32gui

Last factory, command:
python -m nuitka --enable-plugin=anti-bloat --onefile --mingw64 "D:\Test.py"

**Test.exe**
```
Traceback (most recent call last):
  File "C:\Users\test\AppData\Local\Temp\ONA028~1\Test.py", line 1, in <module>
ImportError
```

**Comment by kayhayen** [comment] 2022-01-08 07:13
I added all of these now, it seems from a certain folder they should all be affected. Checkout my recent push.

**Comment by kayhayen** [comment] 2022-01-09 16:12
Part of the 0.6.19 release I just made.

**Closed by kayhayen** 2022-01-09 16:12 UTC
Labels: bug
