### ISSUE TITLE
Missing geos_c.dll with Shapely on Windows, and manual solution

### ISSUE THREAD

**Issue by brev-dev** [Nuitka/Nuitka#1004] opened 2021-02-26 10:03 UTC
Shapely has a dependency `geos_c.dll` which isn't picked-up by Nuitka. You can test this with, for example, `from shapely.geometry import LineString`, which will raise an exception if DLL-load failed. The solution is to copy both `geos_c.dll` and `geos.dll` from `[python]\Lib\site-packages\shapely\DLLs` into `[my_program].dist\shapely\DLLs\`. 

The above is with Python 3.8.7 and Shapely 1.7.1.

Finding the solution made me realize how difficult it must be for Nuitka to identify such dependencies itself. Could one ever expect these to be autodetected? If no, do you have any advice on the best way to approach this problem as an end-user, particularly if it crops-up with less-popular packages? Is this what plugins are all about?

For reference, here's how I tracked it down. Previously, I was aware of the dependency and was manually copying `geos_c.dll` to the root of `.dist/` after compilation. However, on a number of recent machines, this "fix" wasn't working. It turns out that this copy of the DLL was never being used: "working" machines were either pulling it directly from python's shapely installation, or potentially from another program that uses it (it's quite common in GIS packages). I found this by:

1. Running [Process Explorer](https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer) with my code on a working machine. This identified which copy of the DLL was actually being used.
2. In the Shapely code, `[python38]\Lib\site-packages\shapely\geos.py` tries to load the DLL around line 170. It searches a path comprising `(egg_dlls, wininst_dlls, original_path)`. One of those first two parameters (I forget which) points to `[shapely_installation]\DLLs` (yes obvious in hindsight, but I'd got myself very confused by this point).
3. I never found where (or if) the shapely code tries to load `geos.dll` (I guess `geos_c.dll` might be doing it directly?). This part was therefore a trial-and error fix: when `geos.dll` was absent, the error message still referenced `geos_c.dll`, which further added to my confusion.

**Comment by kayhayen** [comment] 2021-02-26 13:27
We would have to do a profiling run of the code, and track the `LoadLibrary` call results, and derive from the load paths, an idea, where they might pick up. Sometimes though, code behaves differently and detects "frozen" modes, or needs environment variables, or whatever. But identifying loaded DLLs would already be nice.

Using dependency walker on Windows it's possible to track run time dependencies of DLLs. That's used for the standalone tests to make sure nothing from outside of the distribution folder gets used.

Nuitka finds DLLs used by DLLs using dependency walker, so adding one such DLL would be nice.

So far extra DLL dependencies are handled with `locateDLL` and being hard coded, and in some instances, with run time querying the package after it loaded it, should it have a function to tell. One recent example is e.g. the glfw plugin that got added such functionality, that is typically most robust, but all manual work.

Also people likely these subfolders for DLLs on Windows, which further complicates matters.

However, we clearly lack a clean way to encode your knowledge into a PR directly and immediately. There isn't even a good place for the manual code to live. So far we do this in the implicit imports standard plugin, but that's kind of polluting it.

It's always on the agenda to make yaml config into Nuitka for these things, I guess it's time to do that.

**Comment by kayhayen** [comment] 2022-02-01 13:24
This is a duplicate of another shapely issue that has actual data in it. On factory, the YAML config was added and applied to shapely as a test case, which should then work on all OSes automatically: https://nuitka.net/doc/factory.html

**Closed by kayhayen** 2022-02-01 13:24 UTC
