### ISSUE TITLE
Infinite optimization loop with cv2/skimage

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#887] opened 2020-11-24 10:38 UTC
Let's consider sample program and nuitka call for compilation:
https://gist.github.com/belonesox/271385f97871d0ad3649c3fded368e1c

This results to something similar https://github.com/Nuitka/Nuitka/issues/783
— infinite optimization loop with "Loop has incomplete variable types after".

```
nuitkatest) [stas@stasbox64gb recursion]$ python -m nuitka --version
0.6.10rc9
Python: 3.8.5 (default, Aug 12 2020, 00:00:00) 
Executable: /nuitkatest/bin/python
OS: Linux
Arch: x86_64
```
Actually, nuitka from develop  branch  commit 10612c9745fa124efdf22c469bc08947cb982a33

**Comment by eyeing** [comment] 2020-11-25 01:59
I want to piggy back off this issue, because I haven't had the time to come up with the minimal recipe for replicating different loops.

Basically, I'm seeing more and more cases where loops are occurring with each release; it is now a combination of different PyPI packages installed. When the python code imports some package, and if there are some other error triggering packages that are also installed as part of the PyPI build, the loop will be activated. Worse, this is happening exclusively with a new nuitka release, meaning that code that used to compile on an older version of nuitka, will no longer compile. This has specifically happened each time from 0.6.7, to 0.6.8.4, to  0.6.9rc6 (from dev), to 0.6.9.7, all with other PyPI packages unchanged. I understand each release version addresses some other set of reported issues, but seems to be expanding the scope that the general "loop" issue is affecting the compilation.  

I am going to stay on 0.6.8.4 generally, and specifically for one piece of code migrate to 0.6.9rc6 - 0.6.9rc6 loops on 2 of the codes that works natively in 0.6.8.4; this is my goldilocks zone. 0.6.9.7 causes loops for more than 50% of the cases I try to compile and seem to be triggered by imports of several PyPI packages, and it is impossible to change my python code without them.   

This loop issue requires a fundamental, long term fix; otherwise, the nuitka release regression will need to have thousands of different permutations of PyPI packages and code that loads them in order to catch all of these loop conditions, which just doesn't seem viable.

**Comment by kayhayen** [comment] 2020-11-25 09:07
Nobody has ever demonstrated any loop for 0.6.9 but there were many for 0.6.8 which got fixed. Without reports that are reproducible, I can't do anything. For pandas I think I am seeing the problem, but more on a level of this being too many modules. Come forward with a new issue that makes it reproducible, and I will gladly look into it. Or wait until somebody else does.

Bit creating issues, with no code, has no use to me.

**Comment by belonesox** [comment] 2020-11-25 11:04
>Bit creating issues, with no code, has no use to me.

https://gist.github.com/belonesox/271385f97871d0ad3649c3fded368e1c — Is not OK to reproduce?

Shoud I make completely isolated venv and upload it somewhere?

**Comment by kayhayen** [comment] 2020-11-25 13:43
I did not see that. My bad! I guess, an example, of comment without substrance distracting me from the issue description.

I guess, it's lacking a description what versions these are. Can you add if this the latest versions, or is this on an OS. Wasn't this part of the issue template to ask for the later? I really need a mechanism for people to give me their `pip freeze` of relevant packages. But from stuff from OS packages that doesn't do shit. But if you used pip, I need something like the versions specified.

The loop optimizating should be relatively good, and I am eager to catch reproducible cases of course. There can be so many thinkos, esp. with nested loops.

**Comment by belonesox** [comment] 2020-11-25 14:38
Please, download https://getbox.ispras.ru/index.php/s/VAzbOMmlZ7trG9f , 
unpack, and run ``reproduce-me.sh``

This shoud be portable venv.

**Comment by kayhayen** [comment] 2020-11-25 16:01
Somehow the virtualenv activate is failing on me, but otherwise very nice report @belonesox I will find out what's wrong there, ah yes, it hard codes your home directory, these things are not very movable, but that's easy to overcome certainly. I think I can take it from there.

**Comment by kayhayen** [comment] 2020-11-25 16:07
As an aside, pipenv is in my mind the best tool for the task, rather than virtualenv. These are movable, and updateable in a controlled way, and you can keep the state under version control with hashes. Check it out: https://pypi.org/project/pipenv/

Were I ever to create a tool for automatic bug reporting, I would make it create a pipenv environment definition for it.

**Comment by kayhayen** [comment] 2020-11-25 17:11
Is this what you have @belonesox 

>Nuitka-Optimization:INFO: /home/hayen/test/recursion/venv/lib/python3.8/site-packages/networkx/readwrite/gexf.py:449 : loop_analysis : Loop has incomplete variable types after 1 attempts for 'val_type'.

That is strange, 1 attempt is not exactly a lot. I did include something that makes it stop after it didn't finish, I think maybe 20 attempts, to avoid endless loops. I wonder if that's showing there somehow. If I compiled this file as a sole module, no problem.

So, this is maybe not about looping in one module, a problem we previously had indeed, and that is solved, but a stray optimization message (that is unreasonable, it should say complete, I think) being delivered by what seems to be a potentially already fully optimized module. Were that the case, Nuitka would restart the cycle over and over again, indeed.

For the time being, this is tentative, still need to give it a few wrap arounds, but this is not like pandas, which seems to complete for me, it did the over day, where optimization is just too slow due to working on 1500 modules.

**Comment by kayhayen** [comment] 2020-11-25 17:23
What's even more annoying, is that `val_type` is not in doubt clearly.  And consider this:

```
....
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module 'gexf', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for 'gexf'.
Nuitka-Optimization:INFO: /home/hayen/test/recursion/venv/lib/python3.8/site-packages/networkx/readwrite/gexf.py:449 : loop_analysis : Loop has incomplete variable types after 4 attempts for 'val_type'.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module 'gexf', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for 'gexf'.
Nuitka-Optimization:INFO: /home/hayen/test/recursion/venv/lib/python3.8/site-packages/networkx/readwrite/gexf.py:449 : loop_analysis : Loop has incomplete variable types after 5 attempts for 'mode'.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module 'gexf', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for 'gexf'.
Nuitka-Optimization:INFO: /home/hayen/test/recursion/venv/lib/python3.8/site-packages/networkx/readwrite/gexf.py:449 : loop_analysis : Loop has incomplete variable types after 6 attempts for 'val_type'.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module 'gexf', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for 'gexf'.
Nuitka-Optimization:INFO: /home/hayen/test/recursion/venv/lib/python3.8/site-packages/networkx/readwrite/gexf.py:449 : loop_analysis : Loop has incomplete variable types after 7 attempts for 'val_type'.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module 'gexf', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for 'gexf'.
Nuitka-Optimization:INFO: /home/hayen/test/recursion/venv/lib/python3.8/site-packages/networkx/readwrite/gexf.py:449 : loop_analysis : Loop has complete variable types after 7 attempts.
Nuitka:INFO:Next global optimization pass.
Nuitka:INFO:Optimizing module 'gexf', 0 more modules to go after that.
Nuitka:INFO:Doing module local optimizations for 'gexf'.
Nuitka:INFO: Completed Python level compilation and optimization.
```
So, it's causing a lot of iterations. I dare say, it's going to finish, eventually. It says 7 attempts. Obvious, 7 whole program scans are catastrophic, if there are modules that take time, this one doesn't btw, but that is probably also why Pandas, even with many modules, has no chance to finish.

If I am not mistaken, the "incomplete loop variables" should be handled with an immediate re-attempt. Also because later optimization might well invalidate the start condition of the loop, and cause it to do it again, presumably taking 7 more rounds.

What's mysterious though, is that it's pointing at `mode` once, and `val_type` at other times. Either there is an indetermism there, or something else going on.

But this sounds like exciting discoveries. Maybe "infinite" can be beaten after all.

So this brings down things to a single file reproducer, where we know it could be done in a lot less (global) passes.

**Comment by kayhayen** [comment] 2020-11-29 11:06
Ok, after making the traces nicer, I checked this out, and using as an example, something like an obvious bug appears there, and I think a distinction is lacking:

> Nuitka-Progress:INFO: PASS 1:
> Nuitka-Progress:INFO: PASS 2:
> incomplete <SourceCodeReference to MiniLoopTooManyPasses.py:10> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeUninit None OBJECT>} <-> frozenset({<ShapeTypeUnknown None OBJECT>})
> Nuitka-Optimization:INFO: MiniLoopTooManyPasses.py:10 : loop_analysis : Loop has incomplete variable types after 1 attempts for 'tuple_unpack_2__element_2,tuple_unpack_2__element_3,val_type,val,for_loop_1__iter_value,start,tuple_unpack_1__source_iter,end,for_loop_3__for_iterator,for_loop_3__iter_value,tuple_unpack_2__element_1,attr_id,for_loop_2__for_iterator,tuple_unpack_3__source_iter,for_loop_2__iter_value,tuple_unpack_3__element_1,k,tuple_unpack_3__element_2,tuple_unpack_2__source_iter,tuple_unpack_3__element_3,e,v'.
> Nuitka-Progress:INFO: PASS 3:
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:10> <LocalVariable 'val_type' of 'add_attributes'> : frozenset({<ShapeTypeUnknown None OBJECT>}) <-> frozenset({<ShapeTypeUnknown None OBJECT>})
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:19> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> Nuitka-Progress:INFO: PASS 4:
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:10> <LocalVariable 'val_type' of 'add_attributes'> : frozenset({<ShapeTypeUnknown None OBJECT>}) <-> frozenset({<ShapeTypeUnknown None OBJECT>})
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:19> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:29> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> Nuitka-Progress:INFO: PASS 5:
> incomplete <SourceCodeReference to MiniLoopTooManyPasses.py:10> <LocalVariable 'val_type' of 'add_attributes'> : frozenset({<ShapeTypeUnknown None OBJECT>}) <-> {<ShapeTypeType type OBJECT>, <ShapeTypeUninit None OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:19> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:29> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> Nuitka-Optimization:INFO: MiniLoopTooManyPasses.py:10 : loop_analysis : Loop has incomplete variable types after 4 attempts for 'val_type'.
> Nuitka-Progress:INFO: PASS 6:
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:10> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>, <ShapeTypeUninit None OBJECT>} <-> {<ShapeTypeType type OBJECT>, <ShapeTypeUninit None OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:19> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> Nuitka-Progress:INFO: PASS 7:
> incomplete <SourceCodeReference to MiniLoopTooManyPasses.py:10> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>, <ShapeTypeUninit None OBJECT>} <-> frozenset({<ShapeTypeUnknown None OBJECT>})
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:19> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:29> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> Nuitka-Optimization:INFO: MiniLoopTooManyPasses.py:10 : loop_analysis : Loop has incomplete variable types after 6 attempts for 'val_type'.
> Nuitka-Progress:INFO: PASS 8:
> incomplete <SourceCodeReference to MiniLoopTooManyPasses.py:10> <LocalVariable 'val_type' of 'add_attributes'> : frozenset({<ShapeTypeUnknown None OBJECT>}) <-> {<ShapeTypeType type OBJECT>, <ShapeTypeUninit None OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:19> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:29> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> Nuitka-Optimization:INFO: MiniLoopTooManyPasses.py:10 : loop_analysis : Loop has incomplete variable types after 7 attempts for 'val_type'.
> Nuitka-Progress:INFO: PASS 9:
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:10> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>, <ShapeTypeUninit None OBJECT>} <-> {<ShapeTypeType type OBJECT>, <ShapeTypeUninit None OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:19> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:29> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> Nuitka-Progress:INFO: PASS 10:
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:10> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>, <ShapeTypeUninit None OBJECT>} <-> {<ShapeTypeType type OBJECT>, <ShapeTypeUninit None OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:19> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> complete <SourceCodeReference to MiniLoopTooManyPasses.py:29> <LocalVariable 'val_type' of 'add_attributes'> : {<ShapeTypeType type OBJECT>} <-> {<ShapeTypeType type OBJECT>}
> 

So what is does, is to attempt to find a stable representation of the loop traces for a variable, that's the thing in the sets. And it starts out pretty well, by putting `ShapeTypeUninit` for an unitialized variable. That one ought to stay, because of course, a loop may not iterate at all, therefore not get to the assigment of the value with `ShapeTypeType`.

And there is a mechanism, there a loop restarts its tracing, if the preconditions change. I think the inner loop might have that happen to it, because once it helped form an opinion of the outer loop, it restarts the loop tracing again.

This seems like at least one bug, where the loop tracing seems capable of pretending that after the loop, an uninitalized value is guarantueed to be assigned.

So far I trimmed down the code to this:

```
class GEXFWriter():
    def add_attributes(self, node_or_edge, xml_obj, data, default):
        # Add attrvalues to node or edge
        attvalues = Element("attvalues")
        if len(data) == 0:
            return data
        mode = "static"
        for k, v in data.items():
            # rename generic multigraph key to avoid any name conflict
            if k == "key":
                k = "networkx_key"
            val_type = type(v)
            if val_type not in self.xml_type:
                raise TypeError(f"attribute value type is not allowed: {val_type}")
            if isinstance(v, list):
                # dynamic data
                for val, start, end in v:
                    val_type = type(val)
                    if start is not None or end is not None:
                        mode = "dynamic"
                        self.alter_graph_mode_timeformat(start)
                        self.alter_graph_mode_timeformat(end)
                        break
                attr_id = self.get_attr_id(
                    str(k), self.xml_type[val_type], node_or_edge, default, mode
                )
                for val, start, end in v:
                    e = Element("attvalue")
                    e.attrib["for"] = attr_id
                    e.attrib["value"] = str(val)
                    # Handle nan, inf, -inf differently
                    if val_type == float:
                        if e.attrib["value"] == "inf":
                            e.attrib["value"] = "INF"
                        elif e.attrib["value"] == "nan":
                            e.attrib["value"] = "NaN"
                        elif e.attrib["value"] == "-inf":
                            e.attrib["value"] = "-INF"
                    if start is not None:
                        e.attrib["start"] = str(start)
                    if end is not None:
                        e.attrib["end"] = str(end)
                    attvalues.append(e)
            else:
                # static data
                mode = "static"
                attr_id = self.get_attr_id(
                    str(k), self.xml_type[val_type], node_or_edge, default, mode
                )
                e = Element("attvalue")
                e.attrib["for"] = attr_id
                if isinstance(v, bool):
                    e.attrib["value"] = str(v).lower()
                else:
                    e.attrib["value"] = str(v)
                    # Handle float nan, inf, -inf differently
                    if val_type == float:
                        if e.attrib["value"] == "inf":
                            e.attrib["value"] = "INF"
                        elif e.attrib["value"] == "nan":
                            e.attrib["value"] = "NaN"
                        elif e.attrib["value"] == "-inf":
                            e.attrib["value"] = "-INF"
                attvalues.append(e)
        xml_obj.append(attvalues)
        return data

```

**Comment by kayhayen** [comment] 2020-11-29 12:28
Ok, and the other thing is, module traversal is broken. Functions once seen in a from the first attempt during a global pass, will never be optimized again in subsequent passes, only module level code is considered. That means, the problem is not strictly limited to loops, but they can make it much worse. 

I guess, one possible solution would be to break down to the function level for now, and repeat their optimization until they become stable. That would also avoid looking at all module, while only a part is seeing optimization. But intra module optimization would then not be part of it.

But of course, for now it will be easier, to just make the decision of a function gets visited not depend on it being active, but instead on it being "done in this pass". With that solution, however bad this nested loop iteration is, and I am not sure bug I was talking about is real after looking further into it, the optimization ought to be done in one global pass. Since pass1 is always needed to decide global variables, pass2 ought to be sufficient.

All later passes are reserved for program wide optimization, e.g. when a module is known, and that influence then leaks into it, but that isn't yet implemented.

I noticed another source of optimization as well, that might be a problem. After a global pass, all functions are analysed, and this happens:

> Nuitka-Optimization:INFO: MiniLoopTooManyPasses.py:4 : var_usage : Schedule removal releases of unassigned parameter variable 'node_or_edge'.
> Nuitka-Optimization:INFO: MiniLoopTooManyPasses.py:4 : var_usage : Schedule removal releases of unassigned parameter variable 'default'.

This should happen right when the module is first optimized, and no later, as it can trigger a global pass, which seems to happen.

Right now, I am not sure, Nuitka does all optimization possible, it seems it can stop early, or so it seems now. That is bad, since code generation relies on optimizable cases to not happen. Not sure how real that issue is though.

This seems to be a bag of things, that I can hopefully address this week.

**Comment by kayhayen** [comment] 2020-12-01 19:53
Ok, on factory, I got the change to make sure that functions get visited, which will in turn end loop optimization always within the one pass, Nuitka needs 2 passes minimum, after which it induces automatic parameter removal, which somehow seems to enable more optimization. I will try and see if it's at all possible to get this down to 3 passes, but obviously 10 is much less than 4, and in reality, the most serial optimizing module dominated the compile times, and I think it's more like to be 4 all the way now.

**Comment by kayhayen** [comment] 2020-12-01 19:53
https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment] 2020-12-03 16:08
This is now on the develop branch and will be soon in a stable release.

**Comment by kayhayen** [comment] 2020-12-07 16:41
Released as part of 0.6.10

**Closed by kayhayen** 2020-12-07 16:41 UTC
Labels: bug, develop

**Comment by jyviko** [comment] 2020-12-10 15:15
@belonesox , was this resolved for you? I am running into an infinite loop situation with a combination of cv2 and networkx [#783](url). I am using the 0.6.11rc1 and Python: 3.7.9.

**Comment by belonesox** [comment] 2020-12-10 15:18
Hmm,  I am on current factory branch, commit 09ac6a934a934ddfa9943311cb3707c9ec534528 , and this bug solved for me.

**Comment by belonesox** [comment] 2020-12-13 15:45
> 0.6.10

The bug still reproduced on me, on 0.6.10

```

Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Optimization:INFO: /home/stas/.local/share/virtualenvs/nuitka-recursion-cv2-rzpRaS5s/lib/python3.8/site-packages/scipy/optimize/_lsq/bvls.py:109 : loop_analysis : Loop has incomplete variable types after 1 attempts for 'iteration'.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Optimization:INFO: /home/stas/.local/share/virtualenvs/nuitka-recursion-cv2-rzpRaS5s/lib/python3.8/site-packages/scipy/optimize/_lsq/bvls.py:109 : loop_analysis : Loop has complete variable types after 1 attempts.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis
Nuitka-Optimization:INFO: /home/stas/.local/share/virtualenvs/nuitka-recursion-cv2-rzpRaS5s/lib/python3.8/site-packages/scipy/optimize/_lsq/bvls.py:109 : loop_analysis : Loop has incomplete variable types after 1 attempts for 'iteration'.
Nuitka-Progress:INFO: Not finished with the module due to following change kinds: loop_analysis

```

Pipenv based sample
https://github.com/belonesox/nuitka-recursion-cv2-scipy

**Comment by kayhayen** [comment] 2020-12-13 18:52
It seems that there is another bug that can be triggered, #901 and that just got fixed. That one makes it indetermistic.

**Comment by belonesox** [comment] 2020-12-13 21:01
> It seems that there is another bug that can be triggered, #901 and that just got fixed. That one makes it indetermistic.

I tried commit cb68905ccd81b2dbfb79834c588c427449fde53e immediately after your comment, but 2 hours compilation seems another type of  looping 
```
  456 modules so far
  45 modules so far 
… 
  546 modules so far…
```
Without "--verbose" the log looks like 
[build.log.zip](https://github.com/Nuitka/Nuitka/files/5685429/build.log.zip)

**Comment by belonesox** [comment] 2020-12-13 21:06
Sorry, not looping but very long generation (usually less 20 minutes for the sample), now couple of hours before
```
Nuitka-Progress:INFO: Optimizing module 'report._py3report', 0 more modules to go after that.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Nuitka:INFO: Total memory usage before generating C code: 1.61 GB (1731018752 bytes):
```
