### ISSUE TITLE
Support for scikit-image

### ISSUE THREAD

**Issue by bgallois** [Nuitka/Nuitka#2322] opened 2023-07-11 11:11 UTC
Tested on Linux, macOS and Windows (probable regression from #2103) [compilation_report.txt](https://github.com/Nuitka/Nuitka/files/12013859/compilation_report.txt):
```
Traceback (most recent call last):
  File "/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/YouAndEyePhoto.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/you_and_eye.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/sub_window.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/image_processing.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/skimage/feature/__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "_cascade.pyx", line 18, in init skimage.feature._cascade
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/skimage/transform/__init__.py", line 35, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/skimage/transform/hough_transform.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "_hough_transform.pyx", line 13, in init skimage.transform._hough_transform
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/skimage/draw/__init__.py", line 3, in <module>
  File "/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/lazy_loader/__init__.py", line 245, in attach_stub
ValueError: Cannot load imports from non-existent stub '/home/bgallois/Codes/Codes/You-And-Eye-Photo/YouAndEyePhoto.dist/skimage/draw/__init__.pyi'
```

* Nuitka version:
   ```
    1.7.3
    Commercial: None
    Python: 3.11.3 (main, Jun  5 2023, 09:32:32) [GCC 13.1.1 20230429]
    Flavor: Unknown
    Executable: /home/bgallois/Codes/Codes/You-And-Eye-Photo/venv/bin/python
    OS: Linux
    Arch: x86_64
    Distribution: Arcolinux (based on arch) None
    Version C compiler: /usr/bin/gcc (gcc).

   ```

* How did you install Nuitka and Python: pip installation in a virtual environment.

* The specific PyPI names and versions:
   ```
    autopep8==2.0.2
    certifi==2023.5.7
    chardet==5.1.0
    charset-normalizer==3.1.0
    checksumdir==1.2.0
    idna==3.4
    imageio==2.31.1
    lazy_loader==0.2
    networkx==3.1
    Nuitka==1.7.3
    numpy==1.25.0
    opencv-python-headless==4.7.0.72
    ordered-set==4.1.0
    packaging==23.1
    Pillow==9.5.0
    py-machineid==0.3.0
    pycodestyle==2.10.0
    PySide6==6.5.1.1
    PySide6-Addons==6.5.1.1
    PySide6-Essentials==6.5.1.1
    PyWavelets==1.4.1
    QDarkStyle==3.1
    QtPy==2.3.1
    rawpy==0.18.1
    requests==2.31.0
    scikit-image==0.21.0
    scipy==1.11.1
    sentry-sdk==1.26.0
    shiboken6==6.5.1.1
    tifffile==2023.4.12
    toml==0.10.2
    urllib3==2.0.3
    winregistry==1.1.1
    zstandard==0.21.0
```

* Note if this is a regression: was working with scikit-image==0.20.0 and Nuitka==1.7.3, probably related to #2103

**Comment by kayhayen** [comment] 2023-07-12 06:02
Yes, this one probably needs to be in Nuitka-Watch, every .pyi file added can cause it, and it seems new releases spread it. You didn't provide a reproducer, so I kind of have to guess here, but it's still a good report. I feel like I would have to make a kind of generator that imports all modules of this package in one test case, such that we are sure of coverage anyway.

**Comment by kayhayen** [comment] 2023-07-12 14:35
I made the fix based on your traceback, and it's on factory, however I didn't yet test it myself, but it may already be enough for you.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by bgallois** [comment] 2023-07-12 16:31
This is not working, included a reproducer 
[test.py.txt](https://github.com/Nuitka/Nuitka/files/12030227/test.py.txt)

**Comment by kayhayen** [comment] 2023-07-12 16:35
Interesting, I really have to make that import all test for skimage there, actually --include-package ought to do it. I was going over my sklearn tests, I got 4 of them, one that fork bombed due to no joblib support recently, and the first one was working very nicely, and this is just because of using only a subset of the package I guess.

**Comment by kayhayen** [comment] 2023-07-13 07:59
So, my examples all work with what is on factory though, I added your imports to one of mine, but I actually do a kind of import them all, then walk them all with `--include-package=sklearn` and I also want to make it bloat free and keep it like that at the same time.

```
# nuitka-project: --standalone
# nuitka-project: --noinclude-default-mode=error
# nuitka-project: --include-package=sklearn
# nuitka-project: --nofollow-import-to=sklearn.*.tests
# nuitka-project: --nofollow-import-to=sklearn.tests
```

In an ideal world, where I will have the data center ready to do it, we would then be triggered by PyPI updates and immediately know of any breakage through a package update.

I imaging that anti-bloat is going to cause a few iterations needed here, but I really want to take the fundamental approach here to cover a package like this well for once.

This code is then doing the walk:

```
# For coverage right now.
import sklearn


def walkPackage(package_name, package):
    print("Walk", package)

    for item in pkgutil.iter_modules(package.__path__):
        if item.name == "tests":
            continue

        full_name = "%s.%s" % (package_name, item.name)
        print("Containing", item, full_name)

        importlib.import_module(full_name)
        imported = sys.modules[full_name]
        print(imported)

        if item.ispkg:
            walkPackage(full_name, imported)


walkPackage("sklearn", sklearn)
```

I would expect it to crash on the `.pyi` files that it is lacking. The alternative would be to hardcode this in a plugin, that just does them all, but I like this more.

**Comment by kayhayen** [comment] 2023-07-13 19:49
So this is now solved on factory. With the all including skimage test, the .pyi files are all covered. Of course there was only one more to add, but with Nuitka-Watch, I can now try and monitor this state automatically at some point.

**Comment by kayhayen** [comment] 2023-07-14 13:50
This is part of the hotfix release 1.7.5 that I just made.

**Closed by kayhayen** 2023-07-14 13:50 UTC
Labels: bug, factory
