### ISSUE TITLE
Support one file like PyInstaller.

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#597] opened 2019-12-31 13:51 UTC
for supporting one file you just need to do these:
1. compile the python codes in c codes like now.
2. when use `--standalone`, we pack some `.dll` and `.pyd` files
3. convert packed files into string and add string to above the main app.
4. add a script in c language to above of main app. this script do these:
    a. when i run the app.exe at first it make random folder in temp with _MEIXXXX prefix like _MEID5D5
    b. extract all packed files in the _MEIXXXX folder.
    c. convert `import sys;sys._MEIPASS = <_MEIXXXX address>` to c code and put it in first of main app.
    d. convert `import sys;sys.path.insert(0,sys._MEIPASS` to c code and put it in first of main app.
    e. continue of program...

this is not a sfx! this just make all packages and dependents ready for continue of main app without any problem.

i don't understand c language, if i know it i was send you a PR to support one-file method.
i just send you a suggestion, i hope this works.

**Comment by JorjMcKie** [comment] 2019-12-31 14:23
This is a duplicate of #594.

**Comment by byehack** [comment] 2019-12-31 15:25
> This is a duplicate of #594.

i know. i maked the https://github.com/Nuitka/Nuitka/issues/594 . but now i said to you what should you do for support one-file.

i searched a lot about pyinstaller. and i don't think this is hard work to do my suggestion.

**Comment by JorjMcKie** [comment] 2019-12-31 16:25
This label is not meant for you and me, but to provide more background for someone who has the time to step in here.

**Comment by byehack** [comment] 2019-12-31 18:19
> This label is not meant for you and me, but to provide more background for someone who has the time to step in here.

you don't know c language?
i think doing this work is so easy for who know c language and nuitka project well.

@JorjMcKie delete `duplicate` label and set a `help wanted` label to get helps from others.
Thanks!

**Comment by JorjMcKie** [comment] 2019-12-31 19:00
@kayhayen  - your decision?

**Comment by gioboske** [comment] 2019-12-31 19:03
Sorry if I step in the discussion, I also looked at #594, but I didn't get which is the benefit of such as addition.
As far as I understood, both with the proposed changes and the Nuitka-Utilities script, it is just a matter of manage a self-extracting archive and run the compiled program after extracting some stuff in a temporary directory, isn't it? Maybe I am missing something?

**Comment by JorjMcKie** [comment] 2019-12-31 19:06
@gioboske  - you understood ... at least as much as I did, but maybe more.

**Comment by byehack** [comment] 2019-12-31 20:39
@gioboske yes you right. i also found the https://github.com/Nuitka/Nuitka/issues/230 . i will send new suggestion in there.

**Comment by byehack** [comment] 2019-12-31 20:46
> @kayhayen - your decision?

please read https://github.com/Nuitka/Nuitka/issues/230#issuecomment-569988529 well.
if u want to continue of discussion in https://github.com/Nuitka/Nuitka/issues/230 , you can close this issue

**Comment by kayhayen** [comment] 2020-01-01 16:30
Whenever people say that something is "just" this, and easy, I get warry. These solutions often cause the most headaches in the long run.

We already have the issue on the radar, and this issue seems to contribute nothing of value. Please do not create duplicate issues, the first one was a mistake, the second one annoys me and wasted my time, which is not helping.

I can understand your enthusiasm, but if as a result of the actions from it, you run a risk and damper the one of those who actually do the work, the decision becomes easy. You stop. That said, this is mostly a research heavy topic. I thought I had listed somewhere how py2exe does it. If pyinstaller really works the way you say, that's sad, and makes it uninteresting.

Yours,
Kay

**Closed by kayhayen** 2020-01-01 16:30 UTC
Labels: duplicate
