### ISSUE TITLE
Lib asyncpg dependency missing with --recurse-all

### ISSUE THREAD

**Issue by pedrovelho** [Nuitka/Nuitka#797] opened 2020-07-23 06:57 UTC
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

I am using nixos,

```sh
[nix-shell:~/test_nuitka]$ uname -a
Linux fox 5.4.50 #1-NixOS SMP Tue Jun 30 20:21:55 UTC 2020 x86_64 GNU/Linux
```

``` 
0.6.7
Python: 3.7.6 (default, Dec 18 2019, 19:23:55) 
Executable: /nix/store/vhnb9dk5py14by8rfrb45a0pi1cy4lk9-python3-3.7.6/bin/python3.7
OS: Linux
Arch: x86_64
```

nuitka3 is a wrapper for module nuitka, check it out:
```sh
[nix-shell:~/test_nuitka]$ cat `which nuitka3`
#! /nix/store/hrpvwkjz04s9i4nmli843hyw9z4pwhww-bash-4.4-p23/bin/bash -e
export PATH='/nix/store/vhnb9dk5py14by8rfrb45a0pi1cy4lk9-python3-3.7.6/bin:/nix/store/b795a86gg476d0s6jlrlwsxf56f32nrp-python3.7-Nuitka-0.6.7/bin'${PATH:+':'}$PATH
export PYTHONNOUSERSITE='true'
exec -a "$0" "/nix/store/b795a86gg476d0s6jlrlwsxf56f32nrp-python3.7-Nuitka-0.6.7/bin/.nuitka3-wrapped"  "$@"
```

```
[nix-shell:~/test_nuitka]$ cat /nix/store/b795a86gg476d0s6jlrlwsxf56f32nrp-python3.7-Nuitka-0.6.7/bin/.nuitka3-wrapped
#!/nix/store/vhnb9dk5py14by8rfrb45a0pi1cy4lk9-python3-3.7.6/bin/python3.7
# -*- coding: utf-8 -*-
import sys;import site;import functools;sys.argv[0] = '/nix/store/b795a86gg476d0s6jlrlwsxf56f32nrp-python3.7-Nuitka-0.6.7/bin/nuitka3';functools.reduce(lambda k, p: site.addsitedir(p, k), ['/nix/store/b795a86gg476d0s6jlrlwsxf56f32nrp-python3.7-Nuitka-0.6.7/lib/python3.7/site-packages'], site._init_pathinfo());
import re
import sys
from nuitka.__main__ import main
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(main())
```
* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

Python and dependencies are installed through `nix-shell` with the following expression in `shell.nix` file:

```nix
let pkgs = import <nixpkgs> {};
in pkgs.mkShell {
  buildInputs = [
    pkgs.python37Packages.asyncpg
    pkgs.python37Packages.pip
    pkgs.python37Packages.setuptools
  ];

  shellHook = ''
            alias pip="PIP_PREFIX='$(pwd)/_build/pip_packages' \pip"
            export PYTHONPATH="$(pwd)/_build/pip_packages/lib/python3.7/site-packages:$PYTHONPATH"
            unset SOURCE_DATE_EPOCH
            pip install nuitka
  '';
}
```

* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.

Hello world runs fine but adding `import asyncpg` to hello world already shows the issue.

```python
import asyncpg

def talk(message):
    return "Talk " + message

def main():
    print( talk("Hello World"))

if __name__ == "__main__":
    main()
```

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

Using the file above (1 line `import asyncpg` and 1 line with the print message) the resulting binary from the command
`nuitka3 --recurse-all test.py` is a binary that has an unresolved dependency.

```sh
[nix-shell:~/test_nuitka]$ ./test.bin 
Traceback (most recent call last):
  File "/home/velho/test_nuitka/test.py", line 1, in <module>
    import asyncpg
  File "/nix/store/hfjr98v82w1klxdz71483hncj9wm3lya-python3.7-asyncpg-0.20.1/lib/python3.7/site-packages/asyncpg/__init__.py", line 8, in <module asyncpg>
    from .connection import connect, Connection  # NOQA
  File "/nix/store/hfjr98v82w1klxdz71483hncj9wm3lya-python3.7-asyncpg-0.20.1/lib/python3.7/site-packages/asyncpg/connection.py", line 19, in <module asyncpg.connection>
    from . import connect_utils
  File "/nix/store/hfjr98v82w1klxdz71483hncj9wm3lya-python3.7-asyncpg-0.20.1/lib/python3.7/site-packages/asyncpg/connect_utils.py", line 27, in <module asyncpg.connect_utils>
    from . import protocol
  File "/nix/store/hfjr98v82w1klxdz71483hncj9wm3lya-python3.7-asyncpg-0.20.1/lib/python3.7/site-packages/asyncpg/protocol/__init__.py", line 8, in <module asyncpg.protocol>
    from .protocol import Protocol, Record, NO_TIMEOUT  # NOQA
  File "asyncpg/protocol/protocol.pyx", line 1, in init asyncpg.protocol.protocol
ModuleNotFoundError: No module named 'asyncpg.pgproto.pgproto'
```

If rerun nuitka removing option `--recurse-all` the compilation works:

```
[nix-shell:~/test_nuitka]$ ./test.bin 
Talk Hello World
```

* If this is a regression (used to work in an earlier version of Nuitka),
  please note what you know about that.

I tried also with nuitka 0.6.8.4 having the same result.

**Comment by kayhayen** [comment] 2020-07-23 08:36
Just to be clear, this is happening on the same environment where you compiled, right? If so, I think this is a duplicate of #689 where a mix of included and non-included Python do not work. Currently I have no workaround, and the issue has stalled, but I hope to get at it soon.

**Comment by pedrovelho** [comment] 2020-07-23 12:21
For some tests, like the small one above, I run on the same environment but to be real clear on my real example, which is quite complex, I use nix-build to create a docker image with the compiled bin inside, if I supress recurse-all I get some local dependencies missing. Let me know if I can help you fix these issues or test them.

**Comment by pedrovelho** [comment] 2020-07-23 12:21
I don't know if this helps but if we `git clone --recursive https://github.com/MagicStack/asyncpg && cd asyncpg` and try a simple `python3 -c "import asyncpg"` we see the same error.

```sh
$ python3 -c "import asyncpg"                                                                                                                                                                     ~/asyncpg
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/velho/asyncpg/asyncpg/__init__.py", line 8, in <module>
    from .connection import connect, Connection  # NOQA
  File "/home/velho/asyncpg/asyncpg/connection.py", line 19, in <module>
    from . import connect_utils
  File "/home/velho/asyncpg/asyncpg/connect_utils.py", line 28, in <module>
    from . import protocol
  File "/home/velho/asyncpg/asyncpg/protocol/__init__.py", line 8, in <module>
    from .protocol import Protocol, Record, NO_TIMEOUT  # NOQA
ModuleNotFoundError: No module named 'asyncpg.protocol.protocol'
```

**Comment by kayhayen** [comment] 2020-08-01 09:40
This makes the issue invalid @pedrovelho as Nuitka is not supposed to behave in a way that Python does not.

**Closed by kayhayen** 2020-08-01 09:40 UTC
Labels: bug, needs_example

**Comment by mickours** [comment] 2020-08-04 09:27
After some more investigation on the problem, It seems that the bug is similar to #689.

## Test case
Using this simple test.py file:
```py
import asyncpg
```

Asyncpg installed in /usr/local/lib/python3.7/site-packages/asyncpg

## The bug

Even if the compilation works fine, the `/usr/local/lib/python3.7/site-packages/asyncpg/pgproto/pgproto.cpython-37m-x86_64-linux-gnu.so` was not found at execution time. I've tried to include the module using `--include-module asyncpg.protocol.protocol` but I've got this warning that suggest that Nuitka does not detect the use of that code and refuse to include the module:
```sh
nuitka3 ./test.py --include-module asyncpg.pgproto.pgproto --follow-imports
Nuitka:WARNING:Not recursing to unused 'asyncpg.pgproto.pgproto'.
```

Running ./test.bin leads to `./test.bin` this error: `ModuleNotFoundError: No module named 'asyncpg.protocol.protocol'`

## Workaround

I've found a workaround, I've included the the module using the plugin mechanism:
```sh
nuitka3 ./test.py --follow-imports --include-plugin-directory /usr/local/lib/python3.7/site-packages/asyncpg/pgproto
```
No more error at execution time!

**Comment by mickours** [comment] 2020-08-04 12:56
Maybe the problem comes from the nested import of compiled libraries. Indeed, the `asyncpg.protocol.protocol`, which imports the `asyncpg.pgproto.pgproto` is already a .so library.

**Comment by kayhayen** [comment] 2020-08-06 10:32
But I was under the impression it happens with pure Python, this discussion is about a Nuitka only case?

**Comment by mickours** [comment] 2020-08-06 11:55
In fact, the error in python mentioned [here](https://github.com/Nuitka/Nuitka/issues/797#issuecomment-662975569) is only due to the fact that the package was not installed and thus the C-extensions where not compiled.

The real problem is about Nuitka not being able to detect the use of a module and also preventing to include it manually.
