### ISSUE TITLE
QtWebengineProcess.exe not copied to the dist folder

### ISSUE THREAD

**Issue by ttbilgin** [Nuitka/Nuitka#1291] opened 2021-11-29 10:40 UTC
We are trying to build a PyQt5 application in win10 + python3.9 4 nutika 0.6.17.
In the earlier version (0.6.16) when we use the following arguments
--include-qt-plugins=sensible,styles,sqldrivers --standalone
QtWebengineProcess.exe is copied to the dist folder, however in recent version, it is not copied, therefore executable crashes in windows.

**Comment by ttbilgin** [comment] 2021-11-30 11:44
Here is the example:
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.17.7' on Python '3.9' commercial None.
OS: Microsoft Windows [Version 10.0.19042.1348]

Build command: 
py -m nuitka --enable-plugin=qt-plugins,multiprocessing,numpy --include-qt-plugins=sensible,styles,sqldrivers --standalone brow.py --mingw64

after build complete brow.exe fails with message "Could not find QtWebEngineProcess.exe"

Example:
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *
from PyQt5.QtWebEngineWidgets import *

import sys

class MainWindow(QMainWindow):

    def __init__(self, *args, **kwargs):
        super(MainWindow,self).__init__(*args, **kwargs)

        self.browser = QWebEngineView()
        self.browser.setUrl(QUrl("http://www.google.com"))

        self.setCentralWidget(self.browser)

        self.show()

app = QApplication(sys.argv)
window = MainWindow()

app.exec_()

**Comment by kayhayen** [comment] 2021-11-30 15:27
Works for me with develop, which will be 0.6.18 soon. Since I don't consider PyQt5 well supported before that, I am closing this immediately as this is a duplicate of other issue which cares for this already.

**Closed by kayhayen** 2021-11-30 15:27 UTC
Labels: needs_example
