### ISSUE TITLE
ImportError: Cannot Import Name 'Mat' from 'cv2'

### ISSUE THREAD

**Issue by cemenenkoff** [Nuitka/Nuitka#3174] opened 2024-10-28 06:27 UTC
# Nuitka OpenCV Bug Report

## 1. Version
```yaml
2.4.11
Commercial: None
Python: 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\USER\Documents\python-projects\PROJECT\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).
```
## 3. Project Dependencies
```
Nuitka==2.4.11
numpy==2.1.2
opencv-python==4.10.0.84
```

## 4. Self-Contained Example 1 (Failure)
```python
from cv2 import Mat

def test_function(x: Mat):
    if x:
        msg = "exists"
    else:
        msg = "failed"
    return msg
```

### 4.1 Stack Trace (Compile)
```bash
USER@PC MINGW64 ~/Documents/python-projects/PROJECT (main)
$ python -m nuitka --standalone --follow-imports --include-module=cv2 nuitka_cv2_test.py
Nuitka-Options: Used command line options: --standalone --follow-imports --include-module=cv2 nuitka_cv2_test.py
Nuitka-Options: Following all imports is the default for standalone mode and need not be specified.
Nuitka: Starting Python compilation with Nuitka '2.4.11' on Python '3.10' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.2).
Nuitka-Scons: Backend linking program with 149 files (no progress information available for this stage).
Nuitka-Scons: Compiled 149 C files using clcache with 149 cache hits and 0 cache misses.
Nuitka-Plugins:dll-files: Found 1 file DLLs from cv2 installation.
Nuitka: Keeping build directory 'nuitka_cv2_test.build'.
Nuitka: Successfully created 'nuitka_cv2_test.dist\nuitka_cv2_test.exe'.
(venv)
```

### 4.2 Stack Trace (Run)
```bash
$ nuitka_cv2_test.dist/nuitka_cv2_test.exe
Traceback (most recent call last):
  File "C:\Users\USER\DOCUME~1\PYTHON~1\PROJECT\NUITKA~1.DIS\nuitka_cv2_test.py", line 1, in <module>
ImportError: cannot import name 'Mat' from 'cv2' (C:\Users\USER\DOCUME~1\PYTHON~1\PROJECT\NUITKA~1.DIS\cv2\__init__.py)
(venv)
```

## 5. Self-Contained Example 2 (Success)
```python
# from cv2 import Mat
import cv2
from numpy import ndarray
import time

def test_function(x: ndarray):
    print(cv2.__name__)
    if x:
        msg = "cv2 exists"
    else:
        msg = "failed"
    for i in range(4, 0, -1):
        print(msg)
        print(i)
        time.sleep(1)
    return msg

arr = ndarray(list(range(10)))
test_function(arr)
```

### 5.1 Stack Trace (Compile)
```bash
USER@PC MINGW64 ~/Documents/python-projects/PROJECT (main)
$ python -m nuitka --standalone --follow-imports --include-module=cv2 nuitka_cv2_test.py
Nuitka-Options: Used command line options: --standalone --follow-imports --include-module=cv2 nuitka_cv2_test.py
Nuitka-Options: Following all imports is the default for standalone mode and need not be specified.
Nuitka: Starting Python compilation with Nuitka '2.4.11' on Python '3.10' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.2).
Nuitka-Scons: Backend linking program with 149 files (no progress information available for this stage).
Nuitka-Scons: Compiled 149 C files using clcache with 148 cache hits and 1 cache misses.
Nuitka-Plugins:dll-files: Found 1 file DLLs from cv2 installation.
Nuitka: Keeping build directory 'nuitka_cv2_test.build'.
Nuitka: Successfully created 'nuitka_cv2_test.dist\nuitka_cv2_test.exe'.
(venv)
```

### 5.2 Stack Trace (Run)
```bash
USER@PC MINGW64 ~/Documents/python-projects/PREOJECT (main)
$ nuitka_cv2_test.dist/nuitka_cv2_test.exe
cv2
C:\Users\USER~1\DOCUME~1\PYTHON~1\PREOJECT\NUITKA~1.DIS\nuitka_cv2_test.py:7: DeprecationWarning: The truth value of an empty array is ambiguous. Returning False, but in future this will result in an error. Use `array.size > 0` to check that an array is not empty.
failed
4
failed
3
failed
2
failed
1
(venv)
```

**Comment by kayhayen** [comment] 2024-10-28 11:08
I managed to reproduce this with 3.12 and latest opencv-python from PyPI as well. It seems they have code to scan for submodules based on filesystem, and will only load them if they exist as files, something we need to workaround with package configuration, and I have added that. Seems to be a relatively old issue, since that code goes back to 4.6 of opencv-python at least, but maybe it was less dependent on files.

**Comment by kayhayen** [comment] 2024-10-28 11:08
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-10-28 17:34
The `--include-module=cv2` should not be necessary anymore and doesn't do what you think anyway, that would have been `--include-package=cv2` which would not have worked either.

**Comment by kayhayen** [comment] 2024-10-29 17:09
Part of the current pre-release and will be in 2.5 once released.

**Comment by kayhayen** [comment] 2024-11-16 12:44
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:44 UTC
Labels: bug, develop, excellent_report
