### ISSUE TITLE
'google-cloud-storage' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by bertbarabas** [Nuitka/Nuitka#762] opened 2020-06-24 17:36 UTC
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  python -m nuitka --version

(.venv) C:\dq-verse\google-cloud-test>  python -m nuitka --version
0.6.8.4
Python: 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)]
Executable: C:\dq-verse\google-cloud-test\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

python - from windows installer
nuitka - from pip

* Many times when you get an error from Nuitka, your setup may be so special
  that even a "hello world" program will not work, please try that and report
  it instead.

helloworld program compiles fine.

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.

First:
pip install google-cloud-storage

Then this trivial 2 line program compiles fine but fails with an exception when the exe is run

from google.cloud import storage
print("test completed")

Here is the exception:
```
   (.venv38) C:\dq-verse\google-cloud-test\test.dist>test
   Traceback (most recent call last):
     File "C:\dq-verse\GOOGLE~1\TEST~1.DIS\test.py", line 2, in <module>
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "C:\dq-verse\GOOGLE~1\TEST~1.DIS\google\cloud\storage\__init__.py", line 36, in <module google.cloud.storage>
    File "C:\dq-verse\GOOGLE~1\TEST~1.DIS\pkg_resources\__init__.py", line 481, in get_distribution
    File "C:\dq-verse\GOOGLE~1\TEST~1.DIS\pkg_resources\__init__.py", line 357, in get_provider
    File "C:\dq-verse\GOOGLE~1\TEST~1.DIS\pkg_resources\__init__.py", line 900, in require
    File "C:\dq-verse\GOOGLE~1\TEST~1.DIS\pkg_resources\__init__.py", line 786, in resolve
  pkg_resources.DistributionNotFound: The 'google-cloud-storage' distribution was not found and is required by the application
```

**Comment by BlackRouter** [comment] 2020-07-07 05:58
hi
i check it not problem after compilation , use this command for compile:

`nuitka --recurse-all --standalone --show-progress t3.py `

**Comment by bertbarabas** [comment] 2020-07-07 15:50
Thanks for the suggestion!

I tired:

python -m nuitka --recurse-all --standalone --show-progress --mingw64 test.py

and exactly your command:

nuitka --recurse-all --standalone --show-progress test.py

Both ways compile fine but both times when I try to run the test.exe I still get the same exception/traceback as first reported.

**Comment by pipermerriam** [comment] 2020-07-28 02:06
I'm seeing the same thing with a different library.

The offending line of code is this: https://github.com/ethereum/eth-utils/blob/386863e6b7d95ac5acb11f6ba81619dc88ed6eb9/eth_utils/__init__.py#L112

Using the `--standalone` flag causes the compiled binary to throw the reported exception.

**Comment by kayhayen** [comment] 2020-07-28 08:26
I have actually started to implement this, but it's a duplicate of #779 that is under work, but probably will not be finished for a while.

**Closed by kayhayen** 2020-07-28 08:26 UTC
Labels: duplicate
