### ISSUE TITLE
Problems compiling fitz module

### ISSUE THREAD

**Issue by AFO-UYI** [Nuitka/Nuitka#142] opened 2018-09-19 07:42 UTC
I'm trying compile a PDF reader written in Python 3.7. GUI is with WxPython 4.0.3 and the PDF renderer is PyMuPDF 1.13.20. The Nuitka version is 0.5.33. I run this command on project folder:
`python -m nuitka --windows-disable-console --standalone --recurse-all --icon="the_absolute_directory_to\icons\icon64.ico" init.py`

When i run the command `python init.py` works well. But when I try to compile, this huge traceback... I dont know how to deal with it. I am especially focused by the last lines, which are errors instead of warnings.

The project is the attached zip file, 4 py files 
[pdf reader.zip](https://github.com/kayhayen/Nuitka/files/2395893/pdf.reader.zip)

the traceback:

`Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:48: Cannot find 'PyPDF2' in package 'wx.lib.pdfviewer' as absolute import (tried PyPDF2).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:50: Cannot find 'PyPDF2.pdf' in package 'wx.lib.pdfviewer' as absolute import (tried PyPDF2.pdf).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:51: Cannot find 'PyPDF2.filters' in package 'wx.lib.pdfviewer' as absolute import (tried PyPDF2.filters).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:62: Cannot find 'cairo' in package 'wx.lib.pdfviewer' as absolute import (tried cairo).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:91: Cannot find 'reportlab.pdfbase.pdfmetrics' in package 'wx.lib.pdfviewer' as absolute import (tried reportlab.pdfbase.pdfmetrics).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:91: Cannot find 'reportlab.pdfbase' in package 'wx.lib.pdfviewer' as absolute import (tried reportlab.pdfbase).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:91: Cannot find 'reportlab' in package 'wx.lib.pdfviewer' as absolute import (tried reportlab).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\graphics.py:45: Cannot find 'cairo' in package 'wx.lib' as absolute import (tried cairo).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\__init__.py:58: Cannot find 'cairo' in package 'wx.lib.wxcairo' as absolute import (tried cairo).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\wx_pycairo.py:180: Cannot find 'macholib.MachO' in package 'wx.lib.wxcairo' as absolute import (tried macholib.MachO).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\wx_pycairo.py:180: Cannot find 'macholib' in package 'wx.lib.wxcairo' as absolute import (tried macholib).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\wx_cairocffi.py:34: Cannot find 'cairocffi' in package 'wx.lib.wxcairo' as absolute import (tried cairocffi).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\fitz\fitz.py:27: Cannot find '_fitz' in package 'fitz' as absolute import (tried _fitz).
cl /Foinit.build\module.wx.core.obj /c "init.build\module.wx.core.cpp" /TP /nologo /EHsc /J /Gd /F8388608 /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_WINMAIN_ENTRY_POINT /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=168 /D_NUITKA_MODULE_COUNT=475 /D_NUITKA_EXE /IC:\Users\AFO\AppData\Local\Programs\Python\Python37\include /IC:\Users\AFO\AppData\Local\Programs\Python\Python37\PC /Iinit.build /IC:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\nuitka\build\include /IC:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\nuitka\build\static_src
init.build\module.wx.core.cpp(53161): error C2065: 'locals_wx$core$$$function_124__PixelDataBase___iter__$$$genobj_1__PixelDataBase___iter___1259': identificador no declarado
init.build\module.wx.core.cpp(53298): error C2065: 'locals_wx$core$$$function_124__PixelDataBase___iter__$$$genobj_1__PixelDataBase___iter___1259': identificador no declaradoscons: *** [init.build\module.wx.core.obj] Error 2

E:\Programacion\PycharmProjects\PDF-reader-memory>python -m nuitka --windows-disable-console --standalone --icon="E:\Programacion\PycharmProjects\PDF-reader-memory\icons\icon64.ico" init.py
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:48: Cannot find 'PyPDF2' in package 'wx.lib.pdfviewer' as absolute import (tried PyPDF2).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:50: Cannot find 'PyPDF2.pdf' in package 'wx.lib.pdfviewer' as absolute import (tried PyPDF2.pdf).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:51: Cannot find 'PyPDF2.filters' in package 'wx.lib.pdfviewer' as absolute import (tried PyPDF2.filters).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:62: Cannot find 'cairo' in package 'wx.lib.pdfviewer' as absolute import (tried cairo).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:91: Cannot find 'reportlab.pdfbase.pdfmetrics' in package 'wx.lib.pdfviewer' as absolute import (tried reportlab.pdfbase.pdfmetrics).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:91: Cannot find 'reportlab.pdfbase' in package 'wx.lib.pdfviewer' as absolute import (tried reportlab.pdfbase).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:91: Cannot find 'reportlab' in package 'wx.lib.pdfviewer' as absolute import (tried reportlab).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\graphics.py:45: Cannot find 'cairo' in package 'wx.lib' as absolute import (tried cairo).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\__init__.py:58: Cannot find 'cairo' in package 'wx.lib.wxcairo' as absolute import (tried cairo).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\wx_pycairo.py:180: Cannot find 'macholib.MachO' in package 'wx.lib.wxcairo' as absolute import (tried macholib.MachO).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\wx_pycairo.py:180: Cannot find 'macholib' in package 'wx.lib.wxcairo' as absolute import (tried macholib).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\wx_cairocffi.py:34: Cannot find 'cairocffi' in package 'wx.lib.wxcairo' as absolute import (tried cairocffi).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\fitz\fitz.py:27: Cannot find '_fitz' in package 'fitz' as absolute import (tried _fitz).
cl /Foinit.build\module.wx.core.obj /c "init.build\module.wx.core.cpp" /TP /nologo /EHsc /J /Gd /F8388608 /Ox /MT /D_NUITKA_STANDALONE /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D_NUITKA_WINMAIN_ENTRY_POINT /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=168 /D_NUITKA_MODULE_COUNT=475 /D_NUITKA_EXE /IC:\Users\AFO\AppData\Local\Programs\Python\Python37\include /IC:\Users\AFO\AppData\Local\Programs\Python\Python37\PC /Iinit.build /IC:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\nuitka\build\include /IC:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\nuitka\build\static_src
init.build\module.wx.core.cpp(53161): error C2065: 'locals_wx$core$$$function_124__PixelDataBase___iter__$$$genobj_1__PixelDataBase___iter___1259': identificador no declarado
init.build\module.wx.core.cpp(53298): error C2065: 'locals_wx$core$$$function_124__PixelDataBase___iter__$$$genobj_1__PixelDataBase___iter___1259': identificador no declaradoscons: *** [init.build\module.wx.core.obj] Error 2

E:\Programacion\PycharmProjects\PDF-reader-memory>python -m nuitka --icon="E:\Programacion\PycharmProjects\PDF-reader-memory\icons\icon64.ico" init.py
Nuitka:WARNING:Not recursing to 'wx' (C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=wx (ignore it), --recurse-to=wx (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'Dialogos' (E:\Programacion\PycharmProjects\PDF-reader-memory\Dialogos.py), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=Dialogos (ignore it), --recurse-to=Dialogos (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'PDF_utils' (E:\Programacion\PycharmProjects\PDF-reader-memory\PDF_utils.py), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=PDF_utils (ignore it), --recurse-to=PDF_utils (recurse to it) to change.
Nuitka:WARNING:Not recursing to 'Database' (E:\Programacion\PycharmProjects\PDF-reader-memory\Database.py), please specify --recurse-none (do not warn), --recurse-all (recurse to all), --recurse-not-to=Database (ignore it), --recurse-to=Database (recurse to it) to change.

E:\Programacion\PycharmProjects\PDF-reader-memory>python -m nuitka --recurse-all --icon="E:\Programacion\PycharmProjects\PDF-reader-memory\icons\icon64.ico" init.py
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:48: Cannot find 'PyPDF2' in package 'wx.lib.pdfviewer' as absolute import (tried PyPDF2).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:50: Cannot find 'PyPDF2.pdf' in package 'wx.lib.pdfviewer' as absolute import (tried PyPDF2.pdf).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:51: Cannot find 'PyPDF2.filters' in package 'wx.lib.pdfviewer' as absolute import (tried PyPDF2.filters).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:62: Cannot find 'cairo' in package 'wx.lib.pdfviewer' as absolute import (tried cairo).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:91: Cannot find 'reportlab.pdfbase.pdfmetrics' in package 'wx.lib.pdfviewer' as absolute import (tried reportlab.pdfbase.pdfmetrics).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:91: Cannot find 'reportlab.pdfbase' in package 'wx.lib.pdfviewer' as absolute import (tried reportlab.pdfbase).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\pdfviewer\viewer.py:91: Cannot find 'reportlab' in package 'wx.lib.pdfviewer' as absolute import (tried reportlab).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\graphics.py:45: Cannot find 'cairo' in package 'wx.lib' as absolute import (tried cairo).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\__init__.py:58: Cannot find 'cairo' in package 'wx.lib.wxcairo' as absolute import (tried cairo).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\wx_pycairo.py:180: Cannot find 'macholib.MachO' in package 'wx.lib.wxcairo' as absolute import (tried macholib.MachO).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\wx_pycairo.py:180: Cannot find 'macholib' in package 'wx.lib.wxcairo' as absolute import (tried macholib).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\wx\lib\wxcairo\wx_cairocffi.py:34: Cannot find 'cairocffi' in package 'wx.lib.wxcairo' as absolute import (tried cairocffi).
Nuitka:WARNING:C:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\fitz\fitz.py:27: Cannot find '_fitz' in package 'fitz' as absolute import (tried _fitz).
cl /Foinit.build\module.wx.core.obj /c "init.build\module.wx.core.cpp" /TP /nologo /EHsc /J /Gd /F8388608 /Ox /MT /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_MODULE_COUNT=27 /D_NUITKA_EXE /IC:\Users\AFO\AppData\Local\Programs\Python\Python37\include /IC:\Users\AFO\AppData\Local\Programs\Python\Python37\PC /Iinit.build /IC:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\nuitka\build\include /IC:\Users\AFO\AppData\Roaming\Python\Python37\site-packages\nuitka\build\static_src
init.build\module.wx.core.cpp(53161): error C2065: 'locals_wx$core$$$function_124__PixelDataBase___iter__$$$genobj_1__PixelDataBase___iter___1259': identificador no declarado
init.build\module.wx.core.cpp(53298): error C2065: 'locals_wx$core$$$function_124__PixelDataBase___iter__$$$genobj_1__PixelDataBase___iter___1259': identificador no declaradoscons: *** [init.build\module.wx.core.obj] Error 2`

**Comment by kayhayen** [comment] 2018-09-19 08:28
Hello,

just a few hours ago, I made a pre-release with a fix for a 0.5.33 regression. Make sure to use 0.6.0rc3 instead. I am 100% positive, this is the same issue, therefore closing it, I am going to release that as stable real soon anyway.

Yours,
Kay

**Comment by AFO-UYI** [comment] 2018-09-27 01:10
Ok. I just updated nuitka to the 0.6.0 release and the compilation works perfectly. In other projects everything works fine. In this particular one something curious happens. WxPython to render a PDF in a window uses the modules PyMuPDF or PyPDF2. Use only one of the two modules. I have installed PyMuPDF because PyPDF2 tends to render very badly. I don't know how WxPython will call those modules, but when I interpret the code with CPython I suppose that the PyPDF2 import releases an error that will escape silently with some try-catch. But when it is compiled, the window with the module that tries to import PyPDF2 simply explodes even if it has PyMuPDF. (It also happens with a module called Fitz that I don't have installed, because in my code I never call a command from that module).

I was wondering if there is any way to fix this with the commands. With `python -m nuitka --help` the one I find that can be is `--plugin-disable`. But then I try to see what plugins there are with `--plugin-list` and I get an error about it needs arguments.

Beyond that, incredible work you do with nuitka. Thank you

**Comment by kayhayen** [comment] 2018-09-27 01:30
@AFO-UYI Cool that you appreciate Nuitka. Thanks for pointing out the problem with --plugin-list, however there is not going to be anything for you there.

When you say "explode", I suppose you mean, you get some sort of ImportError or something? I know PyPDF2, used it in day jobs, I don't know about PyMuPDF though. Quiet possibly it has a hidden depdencency on a file or DLL, or extension module.

If you do --python-flag=-v during compilation, you will see output that indicates what Nuitka meta path based imported is importing. Often you can see it fail or crash shortly after Nuitka "denied reponsibility" for a name. You can run the program normally in CPython with -v and get similar output from CPython, and match it.

Can you try and find it yourself maybe?

**Comment by AFO-UYI** [comment] 2018-09-27 02:58
Ok, I've seen some light. I'm going to keep trying things even though what I've found is totally new to me (but this have been really worth to learn). I'll keep looking but I'll tell you what I found.

First of all, yes by "explode" I meant an import error hahaha. The window makes the attempt to be created but instantly closes and the console shows an import error of the modules fitz and PyPDF2. That's logical considering I don't have the modules installed.

With PyCharm I went to look in the file that is imported with wxpython to raise a window with PDF that is `from wx.lib.pdfviewer import pdfViewer` and what I found is very interesting to me.

At the beginning of the pdfViewer class you can find:
```python
try:
    # see http://pythonhosted.org/PyMuPDF - documentation & installation
    import fitz
    mupdf = True
    if VERBOSE: print('pdfviewer using PyMuPDF (GPL)')
except ImportError:
    mupdf = False
    try:
        # see http://pythonhosted.org/PyPDF2
        import PyPDF2
        from PyPDF2 import PdfFileReader
        from PyPDF2.pdf import ContentStream, PageObject
        from PyPDF2.filters import ASCII85Decode, FlateDecode
        if VERBOSE: print('pdfviewer using PyPDF2')
    except ImportError:
        msg = "PyMuPDF or PyPDF2 must be available to use pdfviewer"
        raise ImportError(msg)
```

Apparently in the first try-except wxpython over the PyMuPDF name actually does the import of the fitz module, so I was completely wrong that I did not have fitz installed.  But the strangest thing is that in the PyCharm settings, in the list of modules I have installed, PyMuPDF appears instead of fitz. And if I go to the "site-packages" folder I find a folder called "PyMuPDF-1.13.20.dist-info" but not one called "PyMuPDF". And I also find a folder called "fitz" but not a folder called "fitz.dist-info".

It's very confusing for me.

I guess Niutka gets confused too and doesn't find the module right. When I open python in cmd and do `import PyMuPDF` I get an error. But if I do `import fitz` everything goes well. But I suppose that Niutka would have to indicate that module with some configuration command?

Beyond everything. While I was writing this I was thinking that the import error that raises the console after compiling is in the folder app.dist that creates Nuitka. So I copied and pasted the fitz folder from "site-packages" to "app.dist"... and the app works perfectly.

**Comment by kayhayen** [comment] 2018-09-28 10:59
Two things here, Nuitka is only good for compiling a program in an environment where it will be running. It seems to be the case that PyCharm users have config there, that they cannot access on the command line, that is an issue.

Anyway, I tried to checkout "import fitz" in standalone mode on Python2 on Linux, and it crashed Nuitka to an error in code generation. I did not try Python3 yet, trying to get at that issue first, but I think it will be hidden dependencies, but seems it will be a while until I find it, fitz appears to be *huge* in what it uses.

I am opening this again and changing title to re-use the issue.

Yours,
Kay

**Comment by AFO-UYI** [comment] 2018-09-29 04:05
About PyCharm. Yes, when you make a virtual environment with PyCharm it makes a weird virtual environment. It usually complicates the logic of my workflow so I always put the global interpreter in PyCharm to be able to access with cmd the changes I make with the modules and code, being sure about im doing solid tests.

In fact, if it wasn't for the modules list on PyCharm settings I think it would be difficult to find the strange things in this case. And I think it's worth that I warning you about something, just in case. 

In the list of installable modules offered by PyCharm I find PyMuPDF and Fitz separately. 

PyMuPDF has this github page [https://github.com/rk700/PyMuPDF](https://github.com/rk700/PyMuPDF)
While Fitz has this other page [https://github.com/kastman/fitz](https://github.com/kastman/fitz)

PyMuPDF-fitz can be installed with `pip install pymupdf` (on windows at least). But Fitz-fitz is installed with `pip install fitz`. So, apart from the fact that I have Python 3 and at this moment you saw it with python2, be careful if the behavior of niutka could be different because we are not with the same "fitz".

To have the same name, they are completely different projects. And as I saw, fitz-fitz is only compatible with python2 and seems to be an abandoned module. I'm with python3.7 on windows 10 so I'm obligatorily with PyMuPDF-fitz. The nuitka compilation is completed showing fitz warnings but without errors. Then I just copy and paste the folder fitz from "site-packages" to the "app.dist" and the compiled program starts without problems. Dont looks a elegant solution at this moment, but, ey, it works.

**Comment by kayhayen** [comment] 2018-10-03 10:48
It's one of these swig created modules, I am completely puzzled, as it includes code where an import _fitz is visible, in the swig helper code, but the extension module is not included. 

Couldn't install the one for Python2, but for all I can tell, it should be very similar, the code that fails to lead to _fitz.so is the same as original fitz for Python2, so I doubt there is much change. Will investigate.

**Comment by kayhayen** [comment] 2018-10-03 13:12
ah ok, for Python3 of course, doing "import _fitz" in the "fitz/fitz.py" will not consider it, because it's absolute, that code line is also very probably not hit. For Python2 the relative import by default would find it locally in the package.

**Comment by kayhayen** [comment] 2018-10-03 13:19
Instead, it is using importlib.import_module once will full package name fitz._fitz and once with only _fitz, so there we are.

I guess, adding a simple implicit dependency of "fitz/fitz" to "fitz/_fitz" will do and it does. Adding that kind of import to your program would work as a workaround, but factory now has this fix too:

http://nuitka.net/doc/factory.html

I will also include it in a hotfix 0.6.0.3 once it happens.

Yours,
Kay

**Comment by kayhayen** [comment] 2018-10-05 06:50
I changed my mind on the hotfix side of things, this is now simply in current rc4 and will be part of 0.6.1 then. Closing it now.

**Closed by kayhayen** 2018-10-05 06:50 UTC
Labels: bug, factory
