### ISSUE TITLE
Standalone compilation is missing some sub-modules and sub-packages of the dependencies

### ISSUE THREAD

**Issue by maximilian-galanis** [Nuitka/Nuitka#779] opened 2020-07-07 13:58 UTC
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

`
0.6.8.4
Python: 3.7.7 (default, May  6 2020, 11:45:54) [MSC v.1916 64 bit (AMD64)]
Executable: C:\tools\Anaconda3\envs\nuitka-test\python.exe
OS: Windows
Arch: x86_64
`

* How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
  what is a virtualenv ...), this is very important usually.

Installed in a conda environment with:
`conda create -n nuitka-test python=3.7`
`conda install nuitka -c conda-forge`

* If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
  that demonstrates the issue i.e a small piece of code which reproduces
  the issue and can be run with out any other (or as few as possible)
  external dependencies.
```
# in file test_nuitka_standalone.py
try:
    # with Python 3.8 this is used and it works
    from importlib import metadata
except ImportError:  # use the backported version with Python 3.7
    import importlib_metadata as metadata


def main():
    print("Success!")


if __name__ == "__main__":
    main()
```

I tried a normal standalone comiplation with:
`
python -m nuitka --standalone  .\test_nuitka_standalone.py
`
and
`python -m nuitka --standalone --follow-imports .\test_nuitka_standalone.py`

and also hinted compilation:
`
python .\get-hints.py .\test_nuitka_standalone.py
`
`
python .\nuitka-hints.py .\test_nuitka_standalone.py
`

In both cases, the compilation finishes without errors. However, once I try to run the script, I get the following error:

> Traceback (most recent call last):
>   File "C:\Users\user\Projects\SCANNE~1\nuitka\TEST_N1.DIS\test_nuitka_standalone.py", line 3, in <module>
> ImportError: cannot import name 'metadata' from 'importlib' (unknown location)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "C:\Users\user\Projects\nuitka\TEST_N1.DIS\test_nuitka_standalone.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "C:\Users\user\Projects\nuitka\TEST_N1.DIS\importlib_metadata\__init__.py", line 623, in <module importlib_metadata>
>   File "C:\Users\user\Projects\nuitka\TEST_N1.DIS\importlib_metadata\__init__.py", line 585, in version
>   File "C:\Users\user\Projects\nuitka\TEST_N1.DIS\importlib_metadata\__init__.py", line 558, in distribution
>   File "C:\Users\user\Projects\nuitka\TEST_N1.DIS\importlib_metadata\__init__.py", line 215, in from_name
> importlib_metadata.PackageNotFoundError: No package metadata was found for importlib_metadata

* If this is a regression (used to work in an earlier version of Nuitka),
  please note what you know about that.

I did not try earlier versions of Nuitka. I tried, however, the current release candidate: 0.6.9rc5, which also did not work.

I also encountered this error with some other packages. The package itself was included in the compiled binary, but some sub-packages or sub-modules were missing.

Still not sure if this is indeed a bug in Nuitka, or whether I am missing some command line arguments.

**Comment by jonsomi** [comment] 2020-07-07 14:15
I want to add that the compilation with Nuitka works flawlessly when not attempting a standalone build.

**Comment by kayhayen** [comment] 2020-07-20 18:08
So, I managed to reproduce this, and this seems familiar. I think meta data checking has been tripped over before, but it's interesting to know that 3.8 works, but maybe it just is because it wasn't used, whereas this might be using itself.

It seems to be about `find_distributions` that our meta path based loader doesn't implement yet. I will check if 3.8 uses it too, and then come up with something that might preserve the information saught there. Surely we can interrogate at compile time for the top level packages that we include, what distributions they are.

**Comment by kayhayen** [comment] 2020-07-20 18:09
yep, 3.8 has the same code, but probably it doesn't look up its version using itself due to being inside the standard library now.

**Comment by kayhayen** [comment] 2020-07-28 08:22
I have added `find_distribution` that returns a dist for contained stuff, with version `0.0.0` hardcoded. That seems to satisfy metadata backport about its own version. It will be disfunctionial for anything that wants to make checks. I wonder how to attack this best, maybe disabling the checks would be the more prudent solution, maybe including the dist information for included packages is, but it also seems wasteful. 

Making it optional could lead to hard to debug problems. Probably make it so that the binary gives a `RuntimeError` exception with a message explaining the problem, and ask to enable the plugin that changes it.

**Comment by mlech-reef** [comment] 2021-03-23 16:51
Hi!

Any progress on this one?

For packages that use e.g. `setuptools-scm` and `from importlib.metadata import version` to get the version in a runtime, there is this problem:

```
Traceback (most recent call last):                                                                                                                                                                                 
  File "/home/maciek/Workspace/b2/terraform-provider-b2/python-bindings/provider_tool.dist/provider_tool.py", line 19, in <module>                                                                                 
  File "/home/maciek/Workspace/b2/terraform-provider-b2/python-bindings/provider_tool.dist/b2_terraform/api_wrapper.py", line 13, in <module b2_terraform.api_wrapper>                                             
  File "/home/maciek/Workspace/b2/terraform-provider-b2/python-bindings/provider_tool.dist/b2sdk/__init__.py", line 24, in <module b2sdk>                                                                          
  File "/home/maciek/Workspace/b2/terraform-provider-b2/python-bindings/provider_tool.dist/b2sdk/version.py", line 18, in <module b2sdk.version>                                                                   
  File "/home/maciek/Workspace/b2/terraform-provider-b2/python-bindings/provider_tool.dist/importlib/metadata.py", line 551, in version                                                                            
  File "/home/maciek/Workspace/b2/terraform-provider-b2/python-bindings/provider_tool.dist/importlib/metadata.py", line 524, in distribution                                                                       
  File "/home/maciek/Workspace/b2/terraform-provider-b2/python-bindings/provider_tool.dist/importlib/metadata.py", line 187, in from_name                                                                          
importlib.metadata.PackageNotFoundError: b2sdk
```

Is there any way to work around it now?

Thanks in advance!

**Comment by kayhayen** [comment] 2021-03-24 14:04
There is a plugin `pkg-resources` now, which resolves this for `pkg_resources.get_distribution("xyz").version` at compile time. It's on factory now, and probably could be expanded to cover more things.

**Comment by kayhayen** [comment] 2021-03-24 14:05
As for the real metadata support, that is kind of stuck halfway, the experimental flag can do versions, but nothing else and lies about the concrete value, i.e. doesn't take it from the real thing. I believe resolving it at compile time might be a better approach that being ready to do so at run time.

**Comment by mlech-reef** [comment] 2021-03-24 14:29
Thank you for your short reply.

I'm afraid it won't help me as `importlib.metadata` doesn't use `pkg-resources` and actually intends to replace it.

I know it would be a big change but maybe Nuitka can include dist-info or egg-info into the binary. I don't know how Nuitka's importing works internally, but if you use some path resolver similar to cpython maybe it can be extended?

**Comment by kayhayen** [comment] 2021-03-26 08:06
The approach need not be limited to a specific module. I will make it detect other modules doing similar stuff too. What I am thinking is to add that kind of support. That will in fact lower the run time burden as well, since these calls tend to be expensive.

I started the work you are referring to, and extended it, but it's not finished. And just to get the version number, it's pretty much overkill anyway.

**Comment by kayhayen** [comment] 2021-04-16 11:48
The `pkg-resources` plugin now handles calls to `metadata.version` and `importlib_metadata.version` now on source code level. 

For `from importlib.metadata import version` to work, we need compile time analysis, that I might eventually add, but it's not there right now.

**Comment by MrYacha** [comment] 2021-08-24 20:22
Any updates on it?

**Comment by arkanoid87** [comment] 2022-04-17 01:01
faced same problem here:
```
Traceback (most recent call last):
  File "/home/arkanoid/nuitkatest/launcher.dist/launcher.py", line 2, in <module>
  File "/home/arkanoid/nuitkatest/launcher.dist/streamlit/__init__.py", line 56, in <module streamlit>
  File "/home/arkanoid/nuitkatest/launcher.dist/importlib_metadata/__init__.py", line 1002, in version
  File "/home/arkanoid/nuitkatest/launcher.dist/importlib_metadata/__init__.py", line 975, in distribution
  File "/home/arkanoid/nuitkatest/launcher.dist/importlib_metadata/__init__.py", line 566, in from_name
importlib_metadata.PackageNotFoundError: No package metadata was found for streamlit
```

**Comment by Pirulax** [comment] 2022-04-17 18:17
Yeah, same issue with [aiolimiter](https://github.com/mjpieters/aiolimiter).

**Comment by Pro100rus32** [comment] 2022-04-29 13:40
I also faced this problem.

**Comment by kayhayen** [comment] 2022-04-29 16:24
Basically, the current source based approach is only going so far. But the optimization of Nuitka has become powerful enough to compile time analyze these functions well enough, so they can be removed.

I am not sure what people mean with "this problem". I kind of believe this has worked for me, at least the example, I think using it fails to be recognized on source code level.

**Comment by rwayan** [comment] 2022-06-07 08:01
Problem with statement at d:\ProgramData\Anaconda3\lib\site-packages\jsonschema\__init__.py:53:
->             from importlib import metadata

Problem with statement at d:\ProgramData\Anaconda3\lib\site-packages\jsonschema\__init__.py:52:
->         try:

Problem with statement at d:\ProgramData\Anaconda3\lib\site-packages\jsonschema\__init__.py:43:
->     if name == "__version__":

Problem with statement at d:\ProgramData\Anaconda3\lib\site-packages\jsonschema\__init__.py:42:
-> def __getattr__(name):

Problem with statement at d:\ProgramData\Anaconda3\lib\site-packages\jsonschema\__init__.py:42:
-> def __getattr__(name):

Nuitka:INFO: Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': 'd:\\ProgramData\\Anaconda3\\lib\\site-packages\\jsonschema\\__init__.py', 'module_name': <ModuleName jsonschema>, 'code_flags': ''}>'.
Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\MainControl.py", line 930, in main
    main_module = _createNodeTree(filename=filename)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\MainControl.py", line 202, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\Optimization.py", line 329, in optimizeModules
    finished = makeOptimizationPass()
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\Optimization.py", line 291, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\Optimization.py", line 187, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\Optimization.py", line 98, in optimizeCompiledPythonModule
    scopes_were_incomplete = module.computeModule()
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\ModuleNodes.py", line 537, in computeModule
    trace_collection=self.trace_collection
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\AssignNodes.py", line 274, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 594, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1172, in computeExpressionRaw
    expression = trace_collection.onExpression(sub_expression)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 594, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 1090, in computeExpressionRaw
    trace_collection.onUsedFunction(self.getFunctionBody())
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 352, in onUsedFunction
    function_body.computeFunctionRaw(self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 493, in computeFunctionRaw
    self.computeFunction(trace_collection)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\FunctionNodes.py", line 509, in computeFunction
    trace_collection=trace_collection
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\TryNodes.py", line 105, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 163, in computeStatementsSequence
    new_statement = statement.computeStatementsSequence(trace_collection)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\FrameNodes.py", line 182, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\ConditionalNodes.py", line 581, in computeStatement
    branch_yes_collection.computeBranch(branch=yes_branch)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 949, in computeBranch
    result = branch.computeStatementsSequence(trace_collection=self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\TryNodes.py", line 105, in computeStatement
    result = tried.computeStatementsSequence(trace_collection=trace_collection)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\StatementNodes.py", line 165, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 613, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\AssignNodes.py", line 274, in computeStatement
    source = trace_collection.onExpression(self.subnode_source)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\optimizations\TraceCollections.py", line 594, in onExpression
    r = expression.computeExpressionRaw(trace_collection=self)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\ExpressionBases.py", line 1243, in computeExpressionRaw
    return self.computeExpression(trace_collection=trace_collection)
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\ImportNodes.py", line 1127, in computeExpression
    trace_collection=trace_collection,
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\ImportNodes.py", line 463, in computeExpressionImportName
    is_import=True,
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\ImportNodes.py", line 514, in _computeExpressionAttribute
    source_ref=lookup_node.source_ref,
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\ImportNodes.py", line 406, in __init__
    self, module_name=module_name, source_ref=source_ref
  File "d:\ProgramData\Anaconda3\lib\site-packages\nuitka\nodes\ImportHardNodes.py", line 46, in __init__
    assert self.finding != "not-found", self.module_name
AssertionError: importlib.metadata

nuitka --version
0.8.3
Commercial: None
Python: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: d:\ProgramData\Anaconda3\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10

How Can I passthrough about this, it stops here.

**Comment by kayhayen** [comment] 2022-06-07 08:45
@rwayan posting below unrelated existing issues is a sure fire way to get ignored, open a new one instead

**Comment by rwayan** [comment] 2022-06-08 10:31
> 

code in github is ok, but pip install failed

**Comment by kayhayen** [comment] 2022-06-12 08:11
I am working on `pkg_resources.requires´ and `pkg_resources.get_distribution`, and they add a new fake `Distribution` object at the very least, derived from compile time information. In standalone mode, ".location" becomes `None`, but I doubt applications use it, and it could be made populated too.

With this, the `get_distribition("lxml").version` and `get_distribition("lxml").parsed_version` get compile time optimized it seems, still need to handle the absence case, but that seems workable.

**Comment by kayhayen** [comment] 2023-07-10 09:11
This work has been completed with 1.7 which also adds `--include-distribution-metadata` for those cases, where compile time detection fails, so it ought to be good now.

**Comment by kayhayen** [comment] 2023-07-10 09:29
The streamlit example is not working for me, I googled anotherf, and may have to go with the trivial one. I believe it may need more integration, for which somebody could write a plugin I guess, for I am looking at for a bit, doing anti-bloat work for the `git` module it uses, etc. and to see if it still exposes the bug.

**Comment by kayhayen** [comment] 2023-07-10 09:40
Since the streamlit stuff is kind of a hijacking of the issue, I am not going to track it. The functions used here are well supported for a while now.

**Closed by kayhayen** 2023-07-10 09:40 UTC
Labels: bug

**Comment by kayhayen** [comment] 2023-07-10 13:51
The streamlit example I made actually compiles, but needs a bit more anti-bloat that will go towards 1.8 in all liklihood.
