### ISSUE TITLE
Imports for AppKit and pyautogui libraries not supported

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1416] opened 2022-02-08 13:46 UTC
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

My Requirements:
MACOS Monterey
Python:3.7.3
Nuitka '0.6.19.4'

* How did you install Nuitka and Python

pip

* The specific PyPI names and versions

pyobjc     6.2.1
PyAutoGUI 0.9.50

* Code
import pyautogui
pyautogui.click()

from AppKit import NSWorkspace
active_Window_name = NSWorkspace.sharedWorkspace().activeApplication()['NSApplicationName']

* Note if this is a regression

not tried

Description:
Although compilation works fine with following command:
sudo python3.7 -m nuitka --standalone  webcam2.py

I am getting "Segmentation error 11" for the imports above.(NSWorkspace and pyautogui)

**Comment by kayhayen** [comment] 2022-02-08 16:52
When you have segfault, please run with `--debugger` and provide a callback trace. I am sort of suspecting that it must be compiled with `--macos-disable-console` and `--macos-create-app-bundle` by proxy. Also, due to the many enhancements, please use develop branch. This is assuming that `AppKit` is giving you there, except to things that will fail to load for console applications as they are created by default. This has been an issue with `wx` before which only works in bundle form and no console too.

Nuitka currently has no idea of this (in the code), but it definitely should be added, esp. if this proves to be correct. Seems kind of like an important package for macOS right there.

**Comment by emre84** [comment] 2022-02-08 20:30
Sure, I can do it. next time,  I will add "--debugger" parameter to my nuitka command and add my callback trace(I guess it means my compilation logs) into my issue.

Right, maybe It could be supported for --macos-create-app-bundle and --macos-disable-console parameters but unfortunately, I have to use "--standalone" parameter to deploy my app.

So as I understand, you are planing to add "import AppKit" into nuitka. I am looking forward it.

By the way, pyautogui library has the same issue, I will enhance the title and content of this issue.

**Comment by kayhayen** [comment] 2022-02-09 08:46
Ah, standalone is just modified by `--macos-create-app-bundle`. It is just standalone with a few more files and different structure, and recognized by apple, and then allowed to access the GUI. Command line programs are not. Without being a bundle, you effectively cannot access GUI, and that can segfault things on Apple, since Python is a bundle there all the time.

**Comment by emre84** [comment] 2022-02-09 13:30
Sorry Kay but I cannot get your point. Maybe because of my poor English. 
So as a conclusion, will it be possible to "import AppKit" with --standalone option in the future?

**Comment by kayhayen** [comment] 2022-02-09 16:04
I believe it is right now possible to use it with `--standalone --macos-create-app-bundle --macos-disable-console`. I didn't try it, but I expect that to be the case. I will look at it eventually myself, but I wanted you to confirm my suspect.

**Comment by emre84** [comment] 2022-02-10 08:25
Cool. Now i get it.  I will try it today and let you know. Thanks.

**Comment by emre84** [comment] 2022-02-10 08:52
Hi Kay, unfortunately following command did not work. I got again segmentation error 11 in "from AppKit import NSWorkspace" line. I forgot again to execute it with --debugger parameter. I will restart it and add my compilation log(I guess callback trace means output of my command?) as comment.

Thanks again. 

python3.7 -m nuitka --standalone --macos-create-app-bundle --macos-disable  --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --enable-plugin=pyside2,numpy --python-flag=no_site webcam2.py

**Comment by emre84** [comment] 2022-02-10 08:57
python3.7 -m nuitka --standalone --macos-create-app-bundle --macos-disable --enable-plugin=anti-bloat --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --enable-plugin=pyside2,numpy --python-flag=no_site --debugger webcam2.py

Following warning is popped up after the command above. I hope my command above is not wrong:
Nuitka-Options:WARNING: The '--debugger' option has no effect outside of '--debug' without '--run' option.

I will post the output later

**Comment by kayhayen** [comment] 2022-02-18 19:46
I have tried this myself, finding another imperfection new develop DLL dependency parser. It seems `pyautogui` pip install is pulling quite a bit of macOS specific packages with ObjC bindings. This will be interesting to see how well those work.

**Comment by kayhayen** [comment] 2022-02-18 20:04
Well, starts off with really bad code:

```
try:
    import Quartz
except:
    assert False, "You must first install pyobjc-core and pyobjc: https://pyautogui.readthedocs.io/en/latest/install.html"
```

This broad exception catcher, also gets `KeyboardInterrupt` and what not and is bug hiding.

**Comment by emre84** [comment] 2022-06-20 21:19
Hi Kai, I would be grateful if you could have time to fix this issue. Thanks a lot in advance.

**Comment by kayhayen** [comment] 2022-06-22 07:04
Good point, there is a range of objc bindings, that are not working, this should be on my list of things to solve.

**Comment by emre84** [comment] 2022-09-14 21:03
Hi Kay, just a reminder :)

**Comment by kayhayen** [comment] 2022-09-26 15:27
Shifted to 1.2 because I have doubts this is a quick one.

**Comment by kayhayen** [comment] 2022-11-06 10:38
So this is a duplicate of #1590, and I am going to track it there, but it seems as of 9.0 the pyobjc is now supporting Nuitka as currently on develop or in 1.2, I am checking it out and then making that release.

**Closed by kayhayen** 2022-11-06 10:38 UTC
Labels: bug
