### ISSUE TITLE
When redirecting stderror, the prompt given to input("message") becomes invisible

### ISSUE THREAD

**Issue by SirDank** [Nuitka/Nuitka#2343] opened 2023-07-20 17:26 UTC
Previously Tested on `Python 3.11.3` and `Nuitka 1.6.3` (working as expected)
Everything listed below was done on a clean install of `Python 3.11.4` and `Nuitka 1.7.5`:

```
1.7.5
Commercial: None
Python: 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Program Files\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.36.32532\bin\Hostx64\x64\cl.exe (cl 14.3).
```

* How did you install Nuitka and Python

  `installed with pip without venv`

* flags and log:

```
Nuitka-Options:INFO: Used command line options: --standalone --clang --warn-unusual-code --assume-yes-for-downloads --show-anti-bloat-changes --plugin-enable=pylint-warnings --noinclude-setuptools-mode=nofollow --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow --noinclude-IPython-mode=nofollow --windows-company-name="Dankware Inc." --windows-product-name=bug-test --windows-file-version=69.69.69.69 --windows-product-version=69.69.69.69 --windows-file-description=bug-test --windows-uac-admin --windows-icon-from-ico=dankware.ico --include-data-file=dankware.wav=./ --include-data-file=dankware.ico=./ --windows-force-stderr-spec=bug-test_errors.txt bug-test.py
Nuitka:INFO: Starting Python compilation with Nuitka '1.7.5' on Python '3.11' commercial grade 'not installed'.
Nuitka-Plugins:INFO: anti-bloat: Handling module 'email.utils' with 2 change(s) for: avoid socket module usage.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: clang-cl (clang-cl).
Nuitka-Scons:INFO: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons:INFO: Compiled 6 C files using clcache with 5 cache hits and 1 cache misses.
Nuitka-Postprocessing:INFO: Adding 1 icon(s) from icon file 'dankware.ico'.
Nuitka-Options:INFO: Included data file 'dankware.wav' due to specified data file 'dankware.wav=./' on command line.
Nuitka-Options:INFO: Included data file 'dankware.ico' due to specified data file 'dankware.ico=./' on command line.
Nuitka:INFO: Keeping build directory 'bug-test.build'.
Nuitka:INFO: Successfully created 'bug-test.dist\bug-test.exe'.
```

* issue:

  `input() does not output anything and appears in the errors.txt`

* contents of errors.txt

  `  > Enter a number: `

* sample script: bug-test.py

```py
import time

n = int(input("\n  > Enter a number: "))
print(f"  > Square: {n*n}")
print(f"  > Cube: {n*n*n}")

time.sleep(4)
```

* output:

```
123
  > Square: 15129
  > Cube: 1860867
```

**Comment by kayhayen** [comment] 2023-07-20 17:49
This must be related to our input/output redirection changes. Not sure, how those affect `input`, this will have to be looked into.

**Comment by kayhayen** [comment] 2023-07-21 06:14
The behaviour is identical with `python Mini.py >out.txt` and is due to `input` prompting you on stderr, which then of course is redirected accordingly, so I would say this is to be expected and not a regression in that sense. Letting some stderr messages through that came from C code, in this case Python core, was never a good thing.

**Comment by SirDank** [comment] 2023-07-21 06:27
wait so how do I fix this?

**Comment by kayhayen** [comment] 2023-07-21 06:33
The help however says this:

```
input(prompt=None, /)
    Read a string from standard input.  The trailing newline is stripped.

    The prompt string, if given, is printed to standard output without a
    trailing newline before reading input.

    If the user hits EOF (*nix: Ctrl-D, Windows: Ctrl-Z+Return), raise EOFError.
    On *nix systems, readline is used if available.
```

Not sure if Python is wrong in saying that, but the C code of Python `PyOS_StdioReadline` is using `stderr` for sure, so there is little to do there.

Also, this doesn't help as well:

```
try:
    stderr_saved = sys.stderr
    sys.stderr = sys.stdout

    n = int(input(("\n  > Enter a number: ")))
finally:
    sys.stderr = stderr_saved
```

The Python `sys.stderr` is not being used there.

The only thing, I can tell you there, is that due to limitations, with MinGW64 it is not doing that C level capture, because it is not possible to get a the Python C runtime from outside of it.

What Nuitka could do, is to kind of implement this in the `input` built-in itself. We don't yet do it, and switching out stderr would never be thread-safe, as Python drops the GIL during that time, so that this temporary stderr would be used by another Python thread too, kind of defeating the purpose of capturing the stderr outputs.

The other workaround would be that Nuitka outputs the prompt to standard output itself as well before calling `input` if and only if only stderr is overloaded. I think that sounds like a plan.

**Comment by kayhayen** [comment] 2023-07-21 07:23
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-07-21 07:26
The documentation is wrong for Python3 only, Python2 did output the prompt to stdout.

The "input" built-in is indeed now turned into a dedicated node, with the slight advange of knowing it is going to be a `str`, so it can generate better code. But the main part added is this.

```
#if NUITKA_STDERR_NOT_VISIBLE && PYTHON_VERSION >= 0x300
        PRINT_ITEM(prompt);
#endif
        return CALL_FUNCTION_WITH_SINGLE_ARG(NUITKA_ACCESS_BUILTIN(input), prompt);
```

So we wrap it with an automatic print to stdout. The flag will only be set if stderr is redirected or hidden (`%NONE%` and `%NULL%`) and stdout is not. So that's a very specific workaround. It however looks like a common trap to fall into. If this works, I will probably also put it in a hotfix. Need to check macOS and Linux behaviour still.

**Comment by kayhayen** [comment] 2023-07-21 07:37
Seems only Python2 on Windows did that, macOS and Linux Python2 need that workaround too, but it seems good now.

**Comment by SirDank** [comment] 2023-07-21 18:41
I have tested this out on `Nuitka 1.8rc5`

same test script:

- `  > Enter a number: ` shows up on both the terminal window and the errors.txt file

other main script:

- they only show up in the errors.txt file

**Comment by kayhayen** [comment] 2023-07-22 08:08
@SirDank not sure what you were trying to say there with "other main script", you probably mean to make a note to yourself extract the difference and report that as well?

**Comment by SirDank** [comment] 2023-07-22 08:19
the other script I was talking about is a much bigger and more complicated script (ignore it for now)

I think the issue is being seen on it due to the output being shown on BOTH stdout and stderr on the test script

**Comment by kayhayen** [comment] 2023-07-22 08:25
Yes, that is the solution I made, but now that you mention it, we could of course not have it do that. The duplication is ugly, I will change it accordingly.

**Comment by kayhayen** [comment] 2023-07-24 07:00
This is part of the hotfix release 1.7.6 that I just made.

**Closed by kayhayen** 2023-07-24 07:00 UTC
Labels: bug, factory

**Comment by SirDank** [comment] 2023-07-24 15:01
I have figured out what was causing the error!

updated sample script:
```py

import time
from colorama import Fore, Style, init

init(autoreset=True)

# colorama colours
#reset = Style.RESET_ALL
red = Fore.RED + Style.BRIGHT
white = Fore.WHITE + Style.BRIGHT
green = Fore.GREEN + Style.BRIGHT

n = int(input(f"\n  {red}> {white}Enter a number{red}: " + green))
print(f"  {red}> {white}Square{red}: {green}{n*n}")
print(f"  {red}> {white}Cube{red}: {green}{n*n*n}")

time.sleep(4)
```

Expected Output: (executed via terminal)
<img width="250" alt="image" src="https://github.com/Nuitka/Nuitka/assets/52797753/5f9cddc6-6391-44bc-8a1d-3b19f5216de1">

Actual Output: (executed via nuitka 1.7.6)
<img width="250" alt="image" src="https://github.com/Nuitka/Nuitka/assets/52797753/47380f3c-7f31-4ce8-b51d-c2e57940193e">

errors.txt: empty

**Comment by kayhayen** [comment] 2023-07-24 15:43
@SirDank if there is more issues, please may a new one, and please not that screenshots are not useful at all, but may in fact be normal. Your "terminal" capabilities might be different from what gets open in whatever way you launch Nuitka compiled program.
