### ISSUE TITLE
With pygame compiled widget ValueError from list.insert arguments is not caught as it should

### ISSUE THREAD

**Issue by KevinRodriguez777** [Nuitka/Nuitka#2731] opened 2024-02-29 00:29 UTC
```
2.0.5
Commercial: None
Python: 3.11.7 (tags/v3.11.7:fa7a6f2, Dec  4 2023, 19:24:49) [MSC v.1937 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Divine\Desktop\OSS contributions\nuitka-toxemon\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.39.33519\bin\Hostx64\x64\cl.exe (cl 14.3).
```
standalone build
this is what i managed to boil down the code to
```
import pygame
import pygame_menu
from pygame_menu import themes

pygame.init()
surface = pygame.display.set_mode((600, 400))


def start_the_game():
    mainmenu._open(loading)
    pygame.time.set_timer(update_loading, 30)


mainmenu = pygame_menu.Menu("Welcome", 600, 400, theme=themes.THEME_SOLARIZED)
mainmenu.add.text_input("Name: ", default="username")
mainmenu.add.button("Play", start_the_game)


loading = pygame_menu.Menu("Loading the Game...", 600, 400, theme=themes.THEME_DARK)
loading.add.progress_bar(
    "Progress",
    progressbar_id="1",
    default=0,
    width=200,
)

arrow = pygame_menu.widgets.LeftArrowSelection(arrow_size=(10, 15))

update_loading = pygame.USEREVENT + 0

while True:
    events = pygame.event.get()
    for event in events:
        if event.type == update_loading:
            progress = loading.get_widget("1")
            progress.set_value(progress.get_value() + 1)
            if progress.get_value() == 100:
                pygame.time.set_timer(update_loading, 0)
        if event.type == pygame.QUIT:
            exit()

    if mainmenu.is_enabled():
        mainmenu.update(events)
        mainmenu.draw(surface)
        if mainmenu.get_current().get_selected_widget():
            arrow.draw(surface, mainmenu.get_current().get_selected_widget())

    pygame.display.update()

```

issue will be raise once you click on the "play button" on the screen, it results in the dollowing error

```
Traceback (most recent call last):
  File "C:\Users\Divine\Desktop\OSSCON~1\NU00F8~1\MAIN~1.DIS\main.py", line 43, in <module>
  File "C:\Users\Divine\Desktop\OSSCON~1\NU00F8~1\MAIN~1.DIS\pygame_menu\menu.py", line 2566, in update
  File "C:\Users\Divine\Desktop\OSSCON~1\NU00F8~1\MAIN~1.DIS\pygame_menu\widgets\core\widget.py", line 2762, in update_menu
  File "C:\Users\Divine\Desktop\OSSCON~1\NU00F8~1\MAIN~1.DIS\pygame_menu\widgets\widget\button.py", line 226, in update
  File "C:\Users\Divine\Desktop\OSSCON~1\NU00F8~1\MAIN~1.DIS\pygame_menu\widgets\core\widget.py", line 1260, in apply
  File "C:\Users\Divine\Desktop\OSSCON~1\NU00F8~1\MAIN~1.DIS\pygame_menu\widgets\core\widget.py", line 1588, in get_value
ValueError: Button<"40aa7dcd-4a59-4f5e"> does not accept value

```

**Comment by kayhayen** [comment] 2024-02-29 19:36
For me it's crashing on fonts missing, I am including package data. Also please always include PyPI package names to use.

**Comment by KevinRodriguez777** [comment] 2024-02-29 19:37
> For me it's crashing on fonts missing, I am including package data. Also please always include PyPI package names to use.

ah apologies, i meant to make a PR with the pygame_menu package data, you probably figured it out already

**Comment by KevinRodriguez777** [comment] 2024-02-29 19:38
```yaml
- module-name: "pygame_menu"
  data-files:
    dirs:
      - 'resources'```

**Comment by kayhayen** [comment] 2024-03-01 08:44
Figure, I managed to reproduce it, but the function there is a static raise, question is what is there in standard Python. What kind of UI is that, it seems not Qt, is this homebrew of pygame via say SDL?

**Comment by KevinRodriguez777** [comment] 2024-03-01 13:44
> Figure, I managed to reproduce it, but the function there is a static raise, question is what is there in standard Python. What kind of UI is that, it seems not Qt, is this homebrew of pygame via say SDL?

are you asking if pygame_menu is a homebrew of pygame? as far as i know no, it's built on top of normal pygame to add extra functionality.

**Comment by kayhayen** [comment] 2024-03-01 14:20
For rendering the widgets. It seems it constructs internally when compiled something that will not work, probably due to something missing. I don't know what renders the button and why it would have an on click that statically raises, there must have been something that fails to be present.

**Comment by kayhayen** [comment] 2024-03-04 11:12
Kevin, can you figure out, what kind of object there is in pure Python in pygame_menu there to receive the click event and not complain about it statically. I cannot do that kind of research really well, as I have like zero clue of what objects it constructs. From past experience, it might be using some sort of backends, and depending on availability construct different object trees, must be that kind of thing somehow.

**Comment by Matiiss** [comment] 2024-03-04 13:28
Hello, chiming in from a referral to this issue, it seems the issue might be related to exception handling somewhere in, I presume, `nuitka`. Looking at the `pygame-menu` source code, it appears it is meant to raise a `ValueError`, however, that happens inside a `try/except ValueError` block.

So the call comes down to this bit right here, the `try/except` block
https://github.com/ppizarror/pygame-menu/blob/b00b6ce186f01ccc39fb407c80ac479816c45c3d/pygame_menu/widgets/core/widget.py#L1259-L1262

So, then that calls `self.get_value` which, unless otherwise implemented, simply raises a `ValueError` which is apparently expected behaviour (it is being caught in CPython)
https://github.com/ppizarror/pygame-menu/blob/b00b6ce186f01ccc39fb407c80ac479816c45c3d/pygame_menu/widgets/core/widget.py#L1577-L1588

**Comment by kayhayen** [comment] 2024-03-05 08:41
Thanks for your analysis @Matiiss that is great.

I think I know now, what's going on. Nuitka is recognizing the type to be a list, and optimizes into a list.insert special node, and thinks somehow that it cannot raise.

This contains a lot of false assumptions in `class ExpressionListOperationInsert` right there:

```
    def mayRaiseException(self, exception_type):
        return self.subnode_list_arg.mayRaiseException(exception_type)

    def mayRaiseExceptionOperation(self):
        # TODO: We do not yet have isIndexable from the type shape.
        return (
            self.subnode_item.isExpressionConstantRef()
            and self.subnode_item.isIndexConstant()
        )
```

That is a grave bug. First of all the subnode_item is the second argument, and not the index, which probably is very good at hiding its bug, but that should have been subnode_index. Then of course, subnode_item and subnode_index are neither considered in `mayRaiseException` which makes this totally embarrassing.

I am absolutely to blame here of apparently copy&pasting code for `insert` and not properly adapting it. This will be fixed in 2.1.1 for sure.

**Comment by kayhayen** [comment] 2024-03-05 08:53
Also excuse me for misreading your code, I thought I saw a static raise there, that doesn't exist. That's only explained by Nuitka usually not being caught with errors other than not including something required.

**Comment by kayhayen** [comment] 2024-03-05 09:00
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2024-03-12 14:24
This is part of the 2.1.1 hotfix release I made

**Closed by kayhayen** 2024-03-12 14:24 UTC
Labels: bug, factory, excellent_report
