### ISSUE TITLE
Cannot import  cpython extension modules not found after compilation.

### ISSUE THREAD

**Issue by Aetherbase** [Nuitka/Nuitka#870] opened 2020-10-27 23:32 UTC
* Nuitka version: 0.6.9.4

* installation procedure : using pip

* example to reproduce: 
```
#mytest.py
import regex
```
compile above file using `python3 -m nuitka  --module mytest.py --recurse-all `
after the compilation is completed, import within an interpreter.
```
>>import mytest
```
it will throw an import error as follows.
`ModuleNotFoundError: No module named 'regex._regex'`
upon a lot of research i understood that the extension modules (*.so files) which are dependencies of modules are failing to be imported. how do i resolve this issue? I am unable to find a similar issue raised in this repo. please guide me if i am doing wrong or if u need me to work on something so i can do a PR. thanks.

**Comment by kayhayen** [comment] 2020-10-29 12:56
This is duplicate of an existing issue, although this might be more minimal. I think lxml has the same issue.

Basically, the meta path based loader of Nuitka is responsible for the `regex` package and will not load the extension module, or source files, or bytecode files from the file system, but only included other modules. In the `MetaPathBasedLoader.c` there is functions for all of it, but the relevant parts might be tailored to standalone mode, e.g. `callIntoShlibModule`, which is guarded by an `#ifdef _NUITKA_STANDALONE` and has fixed opinions on filenames, and uses prepared structure to decide names, etc.

Very similar for bytecode, and I still have a source code loader around, that I never added to the repo so far. I absolutely hate that this reproduces the normal loader abilities. But it seems they cannot be used from `importlib` do work on some cases. Or at least I didn't manage that.

**Comment by kayhayen** [comment] 2020-11-02 12:12
So, as indicated, the use of finders didn't work out, but loading them on our own, does in fact work with at least the regex package now on factory branch: https://nuitka.net/doc/factory.html

This loads them, but I noticed that `__file__` and `__spec__` all looked wrong, and this might cause problems to some extension modules, so I might have to refine this.

Loading source or bytecode of not included modules for compiled packages is kind of a corner case and doesn't concern me right now. The more common case is wanting to include all and for extension modules that is not possible, but going to work now.

I wonder, if somehow, these attributes are incompatible for standalone mode already, and will check with tests, to make sure, e.g. we have the file attribute at least correct.

**Comment by kayhayen** [comment] 2020-11-06 18:11
This is solved in the latest pre-release on develop.

**Comment by Aetherbase** [comment] 2020-11-06 19:01
Is the develop version capable of including all extension modules?

**Comment by Aetherbase** [comment] 2020-11-06 19:02
And im sorry for the late reply i didn't expect for the issue to be solved this fast, since i was looking at the issues since months. Thanks a lot for the quick response.

**Comment by ambv** [comment] 2020-12-06 23:46
I managed to work aroud this until 0.6.10 gets released by just copying the compiled extension .so files over to the root directory of the project.

**Comment by kayhayen** [comment] 2020-12-07 10:54
@ambv just as an aside, Nuitka performs extra steps on these to make sure they run on other systems too, that may well break standalone execution, but you may also be lucky.

**Comment by kayhayen** [comment] 2020-12-07 16:49
Released as part of 0.6.10

**Closed by kayhayen** 2020-12-07 16:49 UTC
Labels: bug
