### ISSUE TITLE
pydoc is not built correctly?

### ISSUE THREAD

**Issue by Rayterex** [Nuitka/Nuitka#3105] opened 2024-09-02 21:45 UTC
While I was trying to build project that uses `shotgun_api3` I found this weird bug:
- This example works
```
import pydoc
```
- However, this one doesn't:
```
import pydoc
import xmlrpc
import xmlrpc.client
import xmlrpc.server
```
This is the error message: File "C:\Users\<User>\AppData\Local\Temp\<Tmp>\xmlrpc\server.py", line 721, in <module>
NameError: name 'pydoc' is not defined

I've tried to build project with Nuitka `2.3.10` and `2.4.8` and in both cases executable fails. I've also tried to  add these options:  `--include-module=pydoc`, `--include-module=xmlrpc`, `--include-module=xmlrpc.server`, but I still get same error message

**Comment by KRRT7** [comment] 2024-09-03 02:45
you'll have to use `--noinclude-pydoc-mode=allow` as pydoc is generally considered antibloat by nuitka

**Comment by kayhayen** [comment] 2024-09-03 08:14
I am not happy with the looks of this, I think it defaults to warning, and should not make something not work. Probably a dependency in stdlib that is not recognized and not using use_pydoc or something like that.

**Comment by kayhayen** [comment] 2024-09-28 15:20
This has proper config for all I can tell:

```
- module-name: 'xmlrpc.server' # checksum: 105ff40e
  anti-bloat:
    - replacements_plain:
        'import pydoc': ''
      when: 'not use_pydoc'
```

**Comment by kayhayen** [comment] 2024-09-28 15:24
Our setup here is probably wrong.

```
        if noinclude_pydoc_mode != "allow":
            self.handled_modules["pydoc"] = noinclude_pydoc_mode, "pydoc"
        else:
            self.control_tags["use_pydoc"] = True
```

The default mode is `warning` which is a form of allowing it, yet for tags, it's treated as if it's not allowed, keeping use_pydoc at false.

**Comment by kayhayen** [comment] 2024-09-28 15:51
It contains this 

```
class ServerHTMLDoc(pydoc.HTMLDoc):
    """Class used to generate pydoc HTML document for a server"""
```

So, the base class is causing issues. Not sure, why this doesn't help yet

```
  anti-bloat:
    - description: 'avoid using pydoc'
      replacements_plain:
        'import pydoc': ''
      change_class:
        'ServerHTMLDoc': 'un-usable'
      when: 'not use_pydoc'
```

**Comment by kayhayen** [comment] 2024-09-28 15:52
Having the tag `use_pydoc` except for `allow` is actually as intended btw, so configuration avoids warnings by removing things typically not needed.

**Comment by kayhayen** [comment] 2024-09-28 16:03
Ah, the reason is that it's converted to bytecode from source code, and then `change_class` is ineffective.

**Comment by kayhayen** [comment] 2024-09-30 07:08
So, the anti-bloat plugin now forces `xmlrpc.server` to be compiled and I found a few bugs related to when change_class and change_function are used, and the fact that plugin decisions for stdlib modules were ignored. This is a bigger change, and outside of the scope of what I am willing to do for a hotfix, so this is going to be 2.5 material. I am currently catching up on issues, and might continue hotfixing for a bit longer.

**Comment by kayhayen** [comment] 2024-09-30 07:08
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-10-14 07:39
This is part of the current pre-release.

**Comment by kayhayen** [comment] 2024-11-16 12:48
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:48 UTC
Labels: bug, develop, excellent_report
