### ISSUE TITLE
Is there an option for exclusion.

### ISSUE THREAD

**Issue by byehack** [Nuitka/Nuitka#727] opened 2020-05-25 18:49 UTC
now we have inclusion option:
```
  Control the inclusion of modules and packages:
    --include-package=PACKAGE
                        Include a whole package. Give as a Python namespace,
                        e.g. ``some_package.sub_package`` and Nuitka will then
                        find it and include it and all the modules found below
                        that disk location in the binary or extension module
                        it creates, and make it available for import by the
                        code. Default empty.
    --include-module=MODULE
                        Include a single module. Give as a Python namespace,
                        e.g. ``some_package.some_module`` and Nuitka will then
                        find it and include it in the binary or extension
                        module it creates, and make it available for import by
                        the code. Default empty.
    --include-plugin-directory=MODULE/PACKAGE
                        Include the content of that directory, no matter if
                        it's used by the given main program in a visible form.
                        Overrides all other recursion options. Can be given
                        multiple times. Default empty.
    --include-plugin-files=PATTERN
                        Include into files matching the PATTERN. Overrides all
                        recursion other options. Can be given multiple times.
                        Default empty.
```

but is there anyway for ignore modules??

**Comment by kayhayen** [comment] 2020-05-26 07:37
No. This seems a duplicate of the issue created yesterday and which I transfered to the utilities repo, any reason why you created this new one?

Without the specifity, to request changed behavior, there the no recursion options, where Nuitka will not include a module. Just check help output some more.

**Closed by kayhayen** 2020-05-26 07:37 UTC
Labels: question
