### ISSUE TITLE
Nuitka 0.7.1 cause dnspython broken

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#1446] opened 2022-02-26 08:11 UTC
**Problem**
I updated Nuitka from 0.6.19.7 to 0.7.1. I compiled a new exe using Nuitka 0.7.1 and found dnspython not working properly. Wirdly, exe compiled by 0.6.19.7 works fine. @kayhayen 

**Environment**
Win10 21H2
Python 3.10.2
dnspython 2.2.0
Nuitka 0.6.19.7/0.7.1

**Minimum Reproducible Example**
```Python
from dns import message
import socket

if __name__ == '__main__':
    query = message.make_query('www.google.com', 1).to_wire()
    s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    s.connect(('8.8.8.8',53))
    s.send(query)
    result = s.recv(4096)
    s.close()
    print(message.from_wire(result))
```

**Command**
```
nuitka --mingw64 --standalone --show-progress --include-module=dns --output-dir=C:\Users\home\Desktop\Python\1 C:\Users\home\PycharmProjects\QYashmak\project\test22.py
```

**Output (Python 3.10.2)**
```
id 28601
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
www.google.com. IN A
;ANSWER
www.google.com. 227 IN A 142.250.188.228
;AUTHORITY
;ADDITIONAL
```

**Output (Nuitka 0.6.19.7)**
```
id 57727
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
www.google.com. IN A
;ANSWER
www.google.com. 214 IN A 142.250.72.132
;AUTHORITY
;ADDITIONAL
```

**Output (Nuitka 0.7.1)**
```
id 29417
opcode QUERY
rcode NOERROR
flags QR RD RA
;QUESTION
www.google.com. IN A
;ANSWER
www.google.com. 238 IN A \# 4 80f2f52b
;AUTHORITY
;ADDITIONAL
```

**Comment by kayhayen** [comment] 2022-02-27 13:14
Nuitka doesn't include all binary encodings by default anymore. Seems that one of these is used by dnspython, but it's bug hiding and not erroring out.

**Comment by kayhayen** [comment] 2022-02-27 13:41
I managed to reproduce this, removing the exclusion of automatic binary encoding didn't change a thing, it seems `idna` encoding is actually included explicitly there.

**Comment by kayhayen** [comment] 2022-02-27 13:42
Imports also do not seem to be an issue, standalone Nuitka and pure Python have the same imports failing, only `org` which is probably Jython garbage.

**Comment by kayhayen** [comment] 2022-02-27 13:44
Although, maybe the import tracing is incomplete, I think I saw it request the `.IN` subpackage with `--python-flag=-v`, but this didn't appear there now, suspicious.

**Comment by kayhayen** [comment] 2022-02-27 15:41
This is the code in questions:

```
def get_rdata_class(rdclass, rdtype):
    cls = _rdata_classes.get((rdclass, rdtype))
    if not cls:
        cls = _rdata_classes.get((dns.rdatatype.ANY, rdtype))
        if not cls:
            rdclass_text = dns.rdataclass.to_text(rdclass)
            rdtype_text = dns.rdatatype.to_text(rdtype)
            rdtype_text = rdtype_text.replace('-', '_')
            try:
                mod = import_module('.'.join([_module_prefix,
                                              rdclass_text, rdtype_text]))
                cls = getattr(mod, rdtype_text)
                _rdata_classes[(rdclass, rdtype)] = cls
            except ImportError:
                try:
                    mod = import_module('.'.join([_module_prefix,
                                                  'ANY', rdtype_text]))
                    cls = getattr(mod, rdtype_text)
                    _rdata_classes[(dns.rdataclass.ANY, rdtype)] = cls
                    _rdata_classes[(rdclass, rdtype)] = cls
                except ImportError:
                    pass
    if not cls:
        cls = GenericRdata
        _rdata_classes[(rdclass, rdtype)] = cls
    return cls

```

It's maximally bug hiding. The `_module_prefix` is and, I suspect, we need to include `.ANY`, `.CH` and `.IN`. 

As for import tracing, the question becomes, why `from importlib import import_module` does not call our `__import__` hook, which I thought it would. Maybe something more to hook as well.

**Comment by kayhayen** [comment] 2022-02-27 16:08
The `eventlet` plugin is asking for `dns` to be included as byte code, which apparently has issues with including its parent packages, which is a separate bug or maybe even the bug. Byte code modules are not yet fully as compatible, ironically.

**Comment by kayhayen** [comment] 2022-02-27 16:09
Actually, the implicit dependency is missing, but when added, due to bytecode inclusion, that bug triggers, so they both need to be fixed for this to work. I am hoping to have something for the next hotfix, maybe later today, lets see what CI thinks of it.

**Comment by kayhayen** [comment] 2022-02-27 16:23
The fixes are on factory and are scheduled to be in 0.7.3 too, which I will release soon too. Seems this hasn't worked so far, not a regression as suspected.

**Comment by kayhayen** [comment] 2022-02-27 16:26
The `--include-module=dns` will no longer be necessary, I consider these things bugs. I failed to tell from the changelog since when the `eventlet` plugin has been active.

**Comment by kayhayen** [comment] 2022-02-27 16:34
The `eventlet` change of becoming on by default is as old as `0.6.13`, a year ago. Not sure if the dependency handling for byte code changed at any time to the worse, I don't believe it did, the release you mentioned seems not affected. Anyway, should be better now.

**Comment by kayhayen** [comment] 2022-03-02 17:42
Was released as part of the hotfix.

**Closed by kayhayen** 2022-03-02 17:42 UTC
Labels: bug, factory

**Comment by mzy2240** [comment] 2022-03-06 05:29
I'm encountering this issue even after upgrading to 0.7.3. Any thoughts on this?
![image](https://user-images.githubusercontent.com/18620336/156910536-0a2e2ff5-9c50-4fd0-9ae1-15ff65bf7973.png)

**Comment by kayhayen** [comment] 2022-03-10 07:38
@mzy2240 raise a new issue with full information
