### ISSUE TITLE
not support python3.12 typing syntax

### ISSUE THREAD

**Issue by cole-dda** [Nuitka/Nuitka#3113] opened 2024-09-09 15:55 UTC
Nuitka==2.4.8
python==3.12.5

helloword.py

```python
class A[T]:
    def __init__(self,a:T):
          self.a=a

def main():
     a=A(1)

if __name__=='__main__':
   main()
```

## build
python/bin/nuitka helloworld.py

## run,but raise error:  NameError: name 'T' is not defined
./helloworld.bin

**Comment by kayhayen** [comment] 2024-10-19 09:36
Duplicate of #3005 it seems

**Closed by kayhayen** 2024-10-19 09:36 UTC
