### ISSUE TITLE
OSError: [WinError 110] The system cannot open the device or file specified

### ISSUE THREAD

**Issue by danieltuzes** [Nuitka/Nuitka#934] opened 2021-01-13 20:29 UTC
I have a too-large-to-touch project, where if I use --follow-imports, the compilation fails with `OSError: [WinError 110] The system cannot open the device or file specified`. If I use `--follow-import-to=my.python.files.path`, or don't use any follow import, then the compilation is successful. Binary file is created even upon fail, but won't do anything. (It runds and closes without any stdout.)

## version
0.6.10.5
Python: 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\uname\.conda\envs\project\python.exe
OS: Windows
Arch: x86_64

Installed it with conda install nuitka, which downloaded Nuitka from a corporate repository. I cannot get newer version of it.

## detailed output of the compilation

```
(project) C:\Users\uname\source\repos\project_dir>nuitka main.py --follow-imports
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: C:\Users\uname\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Compiled 810 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit (direct)': 810
Traceback (most recent call last):
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\main.py", line 196, in <module>
    main()
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\main.py", line 189, in main
    MainControl.main()
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\MainControl.py", line 713, in main
    executePostProcessing()
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\PostProcessing.py", line 228, in executePostProcessing
    lang_id=0,
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\utils\WindowsResources.py", line 263, in addResourceToFile
    closeFileWindowsResources(updatehandle)
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\utils\WindowsResources.py", line 182, in _closeFileWindowsResources
    raise ctypes.WinError()
OSError: [WinError 110] The system cannot open the device or file specified.
(project) C:\Users\uname\source\repos\project_dir>
```

**Comment by fleimgruber** [comment] 2021-01-14 07:42
Duplicate of #933.

**Comment by kayhayen** [comment] 2021-01-14 11:05
Yes, duplicate, please let me also know, if this repeats for you after applying the fix described there. I am also adding a retry with a sleep in a loop, giving a warning, that should help those who first encounter the issue.

**Closed by kayhayen** 2021-01-14 11:05 UTC
Labels: duplicate
