### ISSUE TITLE
Nuitka missing implicit dependencies for gevent, bottle

### ISSUE THREAD

**Issue by ratabomb** [Nuitka/Nuitka#1225] opened 2021-09-30 11:03 UTC
trying to compile script like that:
```
import eel
from time import sleep
def qwerty:
    sleep(10)
qwerty()
eel.init("web")
eel.start("index.html", mode="chrome", size=(872, 550))
```

when i run script from python, it works as needed. when i compile script with nuitka, it crashes with this exception -
```
Traceback (most recent call last):
  File "C:\Temp\ONEE8A~1\main.py", line 1, in <module>
    import eel
  File "C:\Temp\ONEE8A~1\eel\__init__.py", line 5, in <module eel>
  File "C:\Temp\ONEE8A~1\gevent\__init__.py", line 86, in <module gevent>
  File "C:\Temp\ONEE8A~1\gevent\_hub_local.py", line 101, in <module gevent._hub_local>
  File "C:\Temp\ONEE8A~1\gevent\_util.py", line 148, in import_c_accel
  File "importlib.py", line 127, in import_module
ModuleNotFoundError: No module named 'gevent._gevent_c_hub_local'
```

nuitka --version response:
```
0.6.16.4
Python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Executable: C:\Python39\python.exe
OS: Windows
Arch: x86_64
```
i tried to reinstall nuitka, gevent (it isnt used directly in script, but seems it is used in eel) and eel, but it didnt help.

**Comment by arktrin** [comment] 2021-09-30 11:33
Looks like #1175 issue.

**Comment by ratabomb** [comment] 2021-09-30 12:19
> Looks like #1175 issue.

i dont think so but sounds convincing, ill try rn

**Comment by arktrin** [comment] 2021-09-30 12:32
@ratabomb , as you can see issue number 1175 is not resolved by now.

**Comment by ratabomb** [comment] 2021-09-30 17:30
> Looks like #1175 issue.

this doesnt work because i am compiling standalone app, and in #1175 there is trouble with not standalone app

**Comment by ratabomb** [comment] 2021-10-01 15:16
just realized that i forgot to add gevent in --plugin-enable, but it didnt help too

**Comment by Geographs** [comment] 2021-10-02 23:46
Similar to another comment I made, you can fix this by doing the following.

1. Copying and pasting the gevent folder (from site-packages) into the main.dist folder
2. Running main.exe
3. Attempting to delete everything in the gevent folder that was just pasted.
4. Pressing skip for all the files that are being used by main.exe

After this, you can use something, such as Enigma Virtual Box, to pack it all into a single file if you are going for that. Also, steps above work for the standalone flag, but it does not work for the onefile flag.

**Comment by ratabomb** [comment] 2021-10-03 06:58
i just noticed that when i try to install gevent and its packages it shows some errors related to c++ build tools, i will download it now

**Comment by ratabomb** [comment] 2021-10-03 14:58
i cant install gevent because of error in compilation lol
i think its bug in gevent itself

**Comment by ratabomb** [comment] 2021-10-10 07:27
i installed gevent correctly but it didnt help too

**Comment by ratabomb** [comment] 2021-10-13 17:23
ok i reinstalled windows, reinstalled python, reinstalled every library but it still shows error `No module named 'gevent._gevent_c_hub_local'`. anyone help pls, i spent 2 weeks for it

**Comment by ratabomb** [comment] 2021-10-16 09:08
@kayhayen help me pls i have a project that doesnt update rn because of this bug

**Comment by ratabomb** [comment] 2021-10-30 12:57
> For now, I recommend to not have anything installed unless necessary, i.e. use a virtualenv with minimal requirements installed, that is always a good idea with Nuitka scalability.

i returned with new bug. again :(
```
Traceback (most recent call last):
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_hash\utils.py", line 54, in load_environment_backend
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_hash\utils.py", line 28, in load_backend
  File "importlib.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'eth_hash.backends.pysha3'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\main.py", line 497, in runtime
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\main.py", line 334, in walletruntime
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\brute.py", line 34, in brute
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_utils\decorators.py", line 18, in _wrapper
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_account\account.py", line 225, in privateKeyToAccount
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_utils\decorators.py", line 18, in _wrapper
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_account\account.py", line 251, in from_key
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_account\signers\local.py", line 37, in __init__
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_keys\datatypes.py", line 237, in to_checksum_address
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_keys\utils\address.py", line 7, in public_key_bytes_to_address
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_utils\crypto.py", line 11, in keccak
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_hash\main.py", line 41, in __call__
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_hash\main.py", line 26, in _hasher_first_run
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_hash\backends\auto.py", line 24, in keccak256
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_hash\backends\auto.py", line 17, in _initialize
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_hash\utils.py", line 17, in auto_choose_backend
  File "C:\Users\Vista\AppData\Local\Temp\ON6A91~1\eth_hash\utils.py", line 59, in load_environment_backend
ImportError: The backend specified in ETH_HASH_BACKEND, 'pysha3', is not installed. Install with `pip install eth-hash[pysha3]`.
```
pip list:
```
aiohttp            3.7.4.post0
asgiref            3.4.1
asn1crypto         1.4.0
async-timeout      3.0.1
attrs              21.2.0
base58             2.1.0
bip32utils         0.3.post4
bit                0.7.2
bitarray           1.2.2
bottle             0.12.19
bottle-websocket   0.2.9
certifi            2021.10.8
cffi               1.14.6
chardet            4.0.0
charset-normalizer 2.0.7
coincurve          15.0.1
colorama           0.4.4
Cython             0.29.24
cytoolz            0.11.0
Django             3.2.8
ecdsa              0.17.0
Eel                0.14.0
eth-abi            2.1.1
eth-account        0.5.6
eth-hash           0.3.2
eth-keyfile        0.5.1
eth-keys           0.3.3
eth-rlp            0.2.1
eth-typing         2.2.2
eth-utils          1.10.0
future             0.18.2
gevent             21.8.0
gevent-websocket   0.10.1
greenlet           1.1.2
hexbytes           0.2.2
idna               3.3
ipfshttpclient     0.8.0a2
jsonschema         3.2.0
keyboard           0.13.5
libsecp256k1       0.1
lru-dict           1.1.7
mnemonic           0.20
multiaddr          0.0.9
multidict          5.2.0
netaddr            0.8.0
Nuitka             0.6.18rc5
parsimonious       0.8.1
pip                21.2.3
playsound          1.3.0
protobuf           3.18.1
pycparser          2.20
pycryptodome       3.11.0
pyparsing          2.4.7
pypiwin32          223
pyrsistent         0.18.0
pysha3             1.0.2
pytz               2021.3
pywin32            302
requests           2.26.0
rlp                2.0.1
setuptools         57.4.0
six                1.16.0
sqlparse           0.4.2
toolz              0.11.1
typing-extensions  3.10.0.2
urllib3            1.26.7
varint             1.0.2
web3               5.24.0
websockets         9.1
whichcraft         0.6.1
yarl               1.7.0
zope.event         4.5.0
zope.interface     5.4.0
```
choosing pycryptodome in eth hash backend returns the same error but with pycryptodome is not installed etc

**Comment by kayhayen** [comment] 2021-10-30 13:00
The Nuitka commercial will do this automatically, you need to `--include-module` or `--include-package` the right thing, then you have a chance, not a bug at all. Dynamic imports like thesee are not baseline for Nuitka to recognize.

**Comment by ratabomb** [comment] 2021-10-30 14:00
> The Nuitka commercial will do this automatically, you need to `--include-module` or `--include-package` the right thing, then you have a chance, not a bug at all. Dynamic imports like thesee are not baseline for Nuitka to recognize.

```
Nuitka-Options:INFO: Used command line options: *********** --include-module=pycryptodome ***************
Nuitka-Options:INFO: Following all imports is the default for onefile mode and need not be specified.
Nuitka-Plugins:WARNING: gevent: Plugin is defined as always enabled.
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.18rc5' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: tk-inter: Injecting pre-module load code for module 'tkinter':
Nuitka-Plugins:INFO: tk-inter:     Need to make sure we set environment variables for TCL.
FATAL: Error, failed to locate module 'pycryptodome' you asked to include.
```
the same with pysha3. required modules exist, i sent pip list in my previous message

**Comment by kayhayen** [comment] 2021-10-30 14:26
I doubt that it's the correct module names, pip names and module names do not match, esp. not those prefixed with "py", you have to figure these out. If you want to see what fails to import at runtime, --python-flag=-v can be sort of helpful.

**Comment by ratabomb** [comment] 2021-10-30 15:02
<img width="112" alt="Снимок экрана 2021-10-30 в 18 01 21" src="https://user-images.githubusercontent.com/75296588/139538516-56b685bf-eae6-4376-8028-fd259cb64bc7.png">
you mean these pyd files?

**Comment by kayhayen** [comment] 2021-10-30 15:10
Looks like `sha3` might be name you are after.

**Comment by ratabomb** [comment] 2021-10-30 15:14
> Looks like `sha3` might be name you are after.

seems it works, thank you

**Comment by kayhayen** [comment] 2021-10-30 17:18
So, this is on develop now, and will be in the next release. I deleted the off topic discussion about eth packages, I will make a page dedicated to it later.

**Comment by kayhayen** [comment] 2021-12-03 07:18
This is part of the 0.6.18 release.

**Comment by kayhayen** [comment] 2021-12-20 11:39
A bug that affects `bottle.ext` has sneaked in before release in a refactoring, so this needs a hotfix

**Comment by ratabomb** [comment] 2021-12-20 11:46
i noticed that if you copy geventwebsocket and bottle_websocket from site_packages to Lib, this error disappears. but when you call eel.start() (starting window itself) it raises an error `No module named 'gevent._gevent_cqueue'`. trying to copy gevent to Lib too results in compiler throwing a very big error, seems associated with libraries (ends with https://pastebin.com/vLFT9phM).

**Comment by kayhayen** [comment] 2021-12-20 11:50
Never copy anything to the dist folder, that is not supported.

**Comment by ratabomb** [comment] 2021-12-20 11:51
ok. i will wait for your official fix bc these crutches aren't working tho

**Comment by kayhayen** [comment] 2021-12-20 13:18
The hotfix/0.6.18.5 branch is a release candidate with the fix. Worked for me equally good, i.e. it fails to load the browser, but that cut it last time.

**Comment by ratabomb** [comment] 2021-12-20 13:38
is fixing it in progress or i already can download fix somewhere?

**Comment by kayhayen** [comment] 2021-12-20 14:06
@ratabomb see my previous comment it's on said branch and will be in the next hotfix unless you claim it's not working

**Comment by kayhayen** [comment] 2021-12-20 17:13
Part of the current hotifx 0.6.18.5 which should appear as packages shortly.

**Closed by kayhayen** 2021-12-20 17:13 UTC
Labels: bug

**Comment by ratabomb** [comment] 2021-12-22 18:47
```
ERROR - Traceback (most recent call last):
  ...........................
  File "C:\Users\Vista\AppData\Local\Temp\ON8B80~1\eth_hash\utils.py", line 19, in auto_choose_backend
  File "C:\Users\Vista\AppData\Local\Temp\ON8B80~1\eth_hash\utils.py", line 73, in choose_available_backend
ImportError: None of these hashing backends are installed: ['pycryptodome', 'pysha3'].
Install with `pip install eth-hash[pycryptodome]`.
```
seems you haven't fixed anything i talked about in this issue... this is on the new 0.6.18.5 release
