### ISSUE TITLE
multiple definition of `Py_GetArgcArgv`

### ISSUE THREAD

**Issue by bonkeydcow** [Nuitka/Nuitka#409] opened 2019-05-30 19:39 UTC
I have this working on windows 10, but I am trying to port to RedHat linux 7.6

my code is the same and I installed the same version of python 3.7.2

 ../nuitka --recurse-all myapp.py
/usr/local/lib/libpython3.7m.a(main.o): In function `Py_GetArgcArgv':
/usr/src/Python-3.7.2/Modules/main.c:3086: multiple definition of `Py_GetArgcArgv'

**Comment by bonkeydcow** [comment] 2019-05-30 20:11
I also tried it without the --recurse-all and specified all my --include-package parameters. Same result.

**Comment by bonkeydcow** [comment] 2019-05-31 16:18
Is there an LD_PRELOAD i should set to get around this?

**Comment by kayhayen** [comment] 2019-05-31 18:24
This is probably using `pyenv` is it? 

Their static link library is unusable, it shouldn't contain `main.c` and they are not cooperative about it, e.g. Anaconda is better at this. Should be issue #95 and you can employ the workaround from there.

Yours,
Kay

**Comment by kayhayen** [comment] 2019-05-31 18:25
Closing, but you are free to provide extra input, esp if my pyenv guess was wrong.

**Closed by kayhayen** 2019-05-31 18:25 UTC
Labels: duplicate

**Comment by bonkeydcow** [comment] 2019-06-03 13:15
I don't know what pyenv is. I have a fresh RHEL install, and it has a python 2.7.5 native install. I added python 3.7.2 with a make altinstall. I have tried first without a virtualenv (it shouldn't need one). I have tried it with a virtualenv as well. I tried the steps in the item you linked, but when I remove main.o, it causes many more errors. I feel stuck. I have re-installed python with a make install, but has had no effect on the problem.

**Comment by bonkeydcow** [comment] 2019-06-03 18:59
I got it to work with PyInstaller.

**Comment by bonkeydcow** [comment] 2019-06-04 20:09
I got it to work, all I had to do was clean up the LD_LIBRARY_PATH. 

export LD_LIBRARY_PATH=/usr/local/lib

**Comment by Gustavo6046** [comment] 2019-08-09 15:42
I am having the same issue, Kay. I'm not using pyenv, either. It doesn't work, even if I don't use virtualenv.

I'm on Python 3.7.4, tried building my game (Yodine); but it probably won't work with a simple module either, given the nature of the error. Do you believe it is possible that the issue is Nuitka attempting to define the function itself? Shouldn't it be able to detect and omit it whenever libpython already has it?

**Comment by kayhayen** [comment] 2019-08-10 10:22
Hello @Gustavo6046 this is most probably from you using `pyenv` which is not supported, but there is a work around described in #95 that seems to be still needed.

If you managed to hack code into `SingleExe.scons` that would solve #95 it would be good. I think a manual workaround is described there too.

**Comment by Gustavo6046** [comment] 2019-08-16 23:07
Again, I have not used `pyenv`. I don't even use pyenv.

**Comment by kayhayen** [comment] 2019-08-18 15:33
@Gustavo6046 can you raise an issue and fill out the template, so I can know what you actually do have?
