### ISSUE TITLE
nuitka can't package "from cuda import cuda, cudart" 

### ISSUE THREAD

**Issue by minwim** [Nuitka/Nuitka#2263] opened 2023-05-31 03:02 UTC
when i use **from cuda import cuda,cudart**
order:
_nuitka --mingw64 --standalone --show-progress --show-memory --nofollow-import-to=cv2,numpy,email,multiprocessing,cuda,PIL --output-dir=out mymain.py_
when i run mymain.exe, it failed.
![image](https://github.com/Nuitka/Nuitka/assets/86920530/31f81655-8e35-415c-a09c-551253fe20a7)

**Comment by kayhayen** [comment] 2023-05-31 10:20
In the template, I have made it clear, that not filling out the issue template is not acceptable. I am closing this kind of report as invalid. The main reason is that I do not want to be left guessing. For you it's easy to erase the issue template and expect me to ask you questions only as necessary, but I cannot do that. I would much rather wait for you to create a new report, fill out the template, or wait for somebody with the necessary skill to do it.

In short: No issue template, no fun. Therefore I am likely just deleting the issue, as it serves as a bad example and detraction for searches.  And even worse, it might keep good reporters from reporting as is this "already known."

Also you are dumb, because what I see is expected behaviour with your command line.

**Closed by kayhayen** 2023-05-31 10:20 UTC
