### ISSUE TITLE
Scons crashes UnicodeDecodeError when trying to decode compiler output

### ISSUE THREAD

**Issue by 625781186** [Nuitka/Nuitka#193] opened 2018-11-06 15:16 UTC
env:
python 3.6.4 32bit;
![image](https://user-images.githubusercontent.com/30521429/48073401-a67bef80-e219-11e8-9655-014bd687aebd.png)

![image](https://user-images.githubusercontent.com/30521429/48073416-b3004800-e219-11e8-8f3e-0c73f1a1c0fb.png)

acctually, I'm use nuitka 0.6.0.6 and Nuitka 0.6.1rc8 all the same error.

![image](https://user-images.githubusercontent.com/30521429/48073445-be537380-e219-11e8-8acf-10f2b1862913.png)

![image](https://user-images.githubusercontent.com/30521429/48073461-c7444500-e219-11e8-9aad-ecd29de8550f.png)

I use `nuitka --standalone --show-progress --show-memory main.py`, 
but show error
```
scons: *** [main.build\module.__main__.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
scons: *** [main.build\__constants.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
cl /Fomain.build\CompiledCellType.obj /c "main.build\CompiledCellType.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_MODULE_COUNT=2 /D_NUITKA_EXE /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\include /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\PC /Imain.build /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\include /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\static_src
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
scons: *** [main.build\__frozen.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
cl /Fomain.build\CompiledFunctionType.obj /c "main.build\CompiledFunctionType.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_MODULE_COUNT=2 /D_NUITKA_EXE /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\include /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\PC /Imain.build /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\include /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\static_src
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
scons: *** [main.build\__helpers.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
scons: *** [main.build\MainProgram.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
cl /Fomain.build\CompiledMethodType.obj /c "main.build\CompiledMethodType.cpp" /TP /nologo /EHsc /J /Gd /Ox /MT /D_NUITKA_SYSFLAG_BYTES_WARNING=0 /D_NUITKA_SYSFLAG_NO_SITE=0 /D_NUITKA_SYSFLAG_VERBOSE=0 /D_NUITKA_SYSFLAG_UTF8=0 /D__NUITKA_NO_ASSERT__ /D_NUITKA_CONSTANTS_FROM_RESOURCE /D_NUITKA_FROZEN=0 /D_NUITKA_MODULE_COUNT=2 /D_NUITKA_EXE /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\include /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\PC /Imain.build /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\include /IC:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\static_src
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
scons: *** [main.build\CompiledCellType.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
scons: *** [main.build\CompiledFunctionType.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
scons: *** [main.build\CompiledMethodType.obj] UnicodeDecodeError : 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
Traceback (most recent call last):
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Node\__init__.py", line 750, in build
    self.get_executor()(self, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 396, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Executor.py", line 127, in execute_action_list
    status = act(*args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1041, in __call__
    show, execute, chdir, executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 1108, in __call__
    return c.__call__(self, target, source, env, *args, **kw)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 709, in __call__
    stat = self.execute(target, source, env, executor=executor)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\inline_copy\bin\..\lib\scons-3.0.1\SCons\Action.py", line 940, in execute
    result = spawn(shell, escape, cmd_line[0], cmd_line, ENV)
  File "C:\Users\Win_Lin\AppData\Local\Programs\Python\Python36-32\lib\site-packages\nuitka\build\SingleExe.scons", line 532, in spawn
    data = data.decode("utf8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 102: invalid continuation byte
```
I dont't know why ...

**Comment by kayhayen** [comment] 2018-11-06 16:17
That is because Windows doesn't typically use UTF-8, can you change that line to use `data = data.decode(sys.stdout.encoding)`. Can you make your Python interpreter dump that too, so we can see it?

You do not have to install Scons on Windows btw, as Nuitka is using a forked version as inline copy for various reasons anyway. Appdirs is OK, but internal fallback is there too. The error is however in the scons file inside Nuitka, so it's unrelated to that.

I believe what triggers this for you and not others, might be using MSVC in a non-English locale. Version output and/or errors or warnings could then be translated, and that is causing issues for Nuitka. Since your profile on Github has characters that are not displayed in my Chrome, also your home directory could be at fault, but `win_lin` looks very innocent to me.

Thanks for your report. Given feedback, I will gladly hotfix this. 

Yours,
Kay

**Comment by 625781186** [comment] 2018-11-06 17:01
> That is because Windows doesn't typically use UTF-8, can you change that line to use `data = data.decode(sys.stdout.encoding)`. Can you make your Python interpreter dump that too, so we can see it?
> 
> You do not have to install Scons on Windows btw, as Nuitka is using a forked version as inline copy for various reasons anyway. Appdirs is OK, but internal fallback is there too. The error is however in the scons file inside Nuitka, so it's unrelated to that.
> 
> I believe what triggers this for you and not others, might be using MSVC in a non-English locale. Version output and/or errors or warnings could then be translated, and that is causing issues for Nuitka. Since your profile on Github has characters that are not displayed in my Chrome, also your home directory could be at fault, but `win_lin` looks very innocent to me.
> 
> Thanks for your report. Given feedback, I will gladly hotfix this.
> 
> Yours,
> Kay

Oh, I using `try:...except:...` found  the cause of the error:
```
scons: *** [main.build\CompiledMethodType.obj] Error 2
b'c:\\users\\win_lin\\appdata\\local\\programs\\python\\python36-32\\include\\pyconfig.h(59): fatal error C1083: \xce\xde\xb7\xa8\xb4\xf2\xbf\xaa\xb0\xfc\xc0\xa8\xce\xc4\xbc\xfe: \xa1\xb0io.h\xa1\xb1: No such file or directory'
```
Convert these to "gbk", it's maen  `Cannot open include file: 'io.h': No such file or directory`.
I'll try solve it.

Thank you.

**Comment by kayhayen** [comment] 2018-11-06 17:10
The missing include file is strange, but yes indeed. Did you try if a mere `sys.stdout.encoding` instead of `utf8` there works in the sense that it's properly decoded then? I would appreciate to have solved that reporting error too. :)

Yours,
Kay

**Comment by 625781186** [comment] 2018-11-06 17:29
> The missing include file is strange, but yes indeed. Did you try if a mere `sys.stdout.encoding` instead of `utf8` there works in the sense that it's properly decoded then? I would appreciate to have solved that reporting error too. :)
> 
> Yours,
> Kay

I tried to use `sys.stdout.encoding`, but this error still occurs.
When my system area in China.
![image](https://user-images.githubusercontent.com/30521429/48081958-404c9800-e22c-11e8-927a-8697c6a5ab04.png)

![image](https://user-images.githubusercontent.com/30521429/48081804-da601080-e22b-11e8-94e3-4aec81f45e89.png)

I use `sys.stdout.encoding` is OK After  change my system area in English, 
![image](https://user-images.githubusercontent.com/30521429/48082089-96b9d680-e22c-11e8-8fa3-ad8338180e76.png)

**Comment by kayhayen** [comment] 2018-12-05 18:20
I think this is mostly resolved, lets close it.

**Closed by kayhayen** 2018-12-05 18:20 UTC
Labels: bug

**Comment by ideogram** [comment] 2022-12-01 15:06
Just a comment: I had a similar problem. It was caused by the use of the  "Masculin Ordinal Indicator" from my Mac keyboard, using it as a degrees symbol in the comments in my code. Worked on Mac, but it made Nuitka fail under Windows. 

Not a bug report, just a warning that even in comments, 'strange' characters might pose a bit of danger.
