### ISSUE TITLE
Unusual behaviour with sys and glob

### ISSUE THREAD

**Issue by plesubc** [Nuitka/Nuitka#1086] opened 2021-05-06 16:53 UTC
I've noticed some odd behaviour with the glob and sys libraries with nuitka where the behaviour is not what is expected, or in this case, absent.

```
python -m nuitka --version
0.6.14.6
Python: 3.8.1 (tags/v3.8.1:1b293b6, Dec 18 2019, 22:39:24) [MSC v.1916 32 bit (Intel)]
Executable: C:\Users\[redacted]\[alsoredacted]\tmp\py_venv\Scripts\python.exe
OS: Windows
Arch: x86
```

nuitka installed using pip in a virtual environment:

`pip install nuitka`

The output of pip freeze is dirt simple:

`Nuitka==0.6.14.6`

This very short, self-contained example demonstrates the issue, a python file called ntest.py:

```
import sys
import glob

print(sys.platform)
print(glob.glob(sys.argv[1]))
```

Imagine a directory underneath it called sample which contains
file1.txt
file2.txt

Expected output (run using straight python):
`python ntest.py samples\*`

```
win32
['samples\\file1.txt', 'samples\\file2.txt']
```
 
Compiling with nuitka:

`python -m nuitka --onefile --windows-product-version=0.0.0.1 --windows-company-name="Testco" ntest.py`

produces ntest.exe as expected with no errors or warnings. The output is short so I'm including it:

```
Nuitka-Options:INFO: Used command line options: --onefile --windows-product-version=0.0.0.1 --windows-company-name=Testco ntest.py
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: C:\Users\[redacted]\AppData\Local\Nuitka\Nuitka\gcc\x86\10.2.0-11.0.0-8.0.0-r5\mingw32\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Compiled 11 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 11
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka:INFO: Running bootstrap binary compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: C:\Users\[redacted]\AppData\Local\Nuitka\Nuitka\gcc\x86\10.2.0-11.0.0-8.0.0-r5\mingw32\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Compiled 1 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 1
Nuitka:INFO: Keeping onefile build directory 'ntest.onefile-build'.
Nuitka:INFO: Keeping dist folder 'ntest.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'ntest.build'.
Nuitka:INFO: Successfully created 'ntest.exe'.`
```

Running the created.exe with the same parameters as the python script produces **no output at all**, as per these two examples.

```
ntest.exe samples\*
ntest.exe samples\*.txt
```

This, however, will produce the expected output:

```
ntest.exe samples\file1.txt
win32
['samples\\file1.txt']
```

**Comment by kayhayen** [comment] 2023-07-13 19:35
There was a time when MinGW64 did globing on its own for command line arguments, this is a duplicate of that bug and has long been solved.

**Closed by kayhayen** 2023-07-13 19:35 UTC

**Comment by kayhayen** [comment] 2023-07-13 19:36
Sorry this took so, actually a good report, but before I want all in of Nuitka, I wasn't capable of keeping up. Right now I am winding down on old issues.
