### ISSUE TITLE
python3.11 list performance with pre-release of Nuitka not fully supporting 3.11 yet

### ISSUE THREAD

**Issue by CJH07170610** [Nuitka/Nuitka#2064] opened 2023-02-16 12:52 UTC
My Env:
system: win11 64bit system.
python: Python 3.11.2
nuitka: version 1.5rc9

Test Script:
```python
# test.py
import time
def test():
    t1 = time.time()
    points = []
    for i in range(1000000):
        points.append([50, 50])
    t2 = time.time()
    print(t2 - t1)
if __name__ == "__main__":
    test()
```
Python Run:

```cmd
python test.py
0.14899992942810059
```

Nuitka Compile:

```cmd
python -m nuitka test.py
```
Run:

```cmd
./test.exe
15.511167764663696
```
The difference in performance is 100 times

**Comment by kayhayen** [comment] 2023-02-16 17:39
That is terrible indeed. If I run this with 3.10, numbers are roughly the same, 0.23s of Python 3.10 vs. 0.22s of Nuitka. I reproduce this with Nuitka. I suspect that e.g. `range` has still bugs. But I don't recall saying that it makes sense to measure 3.11 performance with Nuitka yet. In fact I remember saying the opposite.

I will therefore close this as interesting, but invalid.

**Comment by kayhayen** [comment] 2023-02-18 08:38
One think to add was that the 3.11 performance was not all that different on that machine. I think it was .021s there, so in the same ballpark. The sad thing for me about this, is that inside the loop, the list optimization for append will not be effective, so th actual disappointment is of course that Nuitka should be a lot faster there, but is not (yet). Once I get to loop optimization, I will check it out. The range issue is interesting, but not a priority yet. I tend to believe it is an iteration bug there, that I will figure out eventually.

**Comment by kayhayen** [comment] 2023-02-19 10:54
Changing my mind. I will explore this one, it's after all a rather minimal test case. 

So, lists currently mark valuies written or read in the loop as "unknown", which was done is to prevent optimization based on their value. As a result, 3.10 is slower than it could be, going to 0.19 in performance, if I disable it. The real solution is of course, to mark read values as escaped, i.e. to not trust their values from outside of the loop. Imagine a bool test on the pre-loop empty list, and `list.append` being called to make it non-empty, potentially in branches. I am sure that had been observed to cause issues.

The solution has effectively disabled very much optimization in loops. We have since long introduced "escaped" as a notion, which will prevent forgetting the type shape of the list, and allow us to turn the call of the fixed attribute lookup "append" to `ExpressionListOperationAppend`.

Changing that will help the performance of many things. I do believe however, that the specifc code you are giving could only be improved by one thing. If we had loop analysis that predicts the number of append call, we could predict what to allocate the list to a given size, and then the performance might be a lot better.

Right now I think we are benchmarking some overhead around malloc here. Allocating the list to its final size would be kind of eliminating some of it. There is still `[50, 50]` which for Nuitka I think as a mutable constant has a deep copy specialization. In case of this list, since no other mutable things are contained, a mere `LIST_COPY`  with a prepare list is done, and probably sufficient.

Now for analysing, where the bad thing in 3.11 happens, I guess, first thing is to make this a mere number, and see if that changes things, it takes out the last part out of the equation.

**Comment by kayhayen** [comment] 2023-02-19 11:13
Ok, that is not doing it, although I think we should have an analysis of how much of a difference creating the new list constant each time takes, it has not had any impact to change it to `3`. I also removed the .append call entirely, and the `pass` loop on the xrange is slow. 

Maybe creating long objects has become somehow slow. Nuitka is not good enough to handle discarding iteration like that without producing the objects yet.

```
    for i in range(1000000):
        pass
```

Let along recognizing that this is only a very slow assignment of `i` to a value with no effect, that is then unused, but I digress.

**Comment by kayhayen** [comment] 2023-02-19 11:20
I deleted my last comment, indeed the `LIST_COPY` using line is super expensive on Windows at least. This might be because the memory allocator is not fully optimized for 3.11 yet. When it allocates a new list, it has to do several Windows DLL calls right now. so this might be it. Trying on Linux now, where LTO can migigate that.

**Comment by kayhayen** [comment] 2023-02-19 12:46
So, I think it is because with a loop reduced by 10, it is calling 12 times `PyGC_Collect` which I suppose will get even worse the more objects exist. I think I did that, because I wanted to avoid replicating garbage collector details. But this might be doing way too much, or the call condition is wrong, I will have to check.

**Comment by kayhayen** [comment] 2023-02-20 10:53
So indeed, these garbage collections are the issue. And honestly, they of course have no point really to be done in Python too. But the allocator of Python 3.11 triggers a much lighter one than what Nuitka did as the workaround to not re-implementing half of the Python garbage collector. 

I wonder if Nuitka could get away with not triggering the GC at all or less often, but I don't see much to gain there, probably just delays work to do for later.

**Comment by kayhayen** [comment] 2023-02-20 10:54
I have internally some sort of implementation that mimics stuff done there, but it was very painful to create and is going to bump up the Python core change dependency of Nuitka to a new level. To the point, where I need to worry.

**Comment by kayhayen** [comment] 2023-03-12 12:04
This all is part of the 1.5 release.

**Closed by kayhayen** 2023-03-12 12:04 UTC
