### ISSUE TITLE
Compile fastapi/unicorn failed. I used the latest nuitka 0.6.8.4. I read issues, which say nuitka 0.6.8 should work well on fastapi. 

### ISSUE THREAD

**Issue by hkhk366** [Nuitka/Nuitka#821] opened 2020-08-21 21:05 UTC
Yesterday, I just found this very interesting project nuitka. This is good work to improve the efficiency of python. I tried nuitka on my projects. Most of them work well except the one with fastapi. This may be a silly question. I tried to figure it out myself but failed.

OS: Ubuntu20.04
Fastapi: 0.61.0
Nuitka: 0.6.8.4

I run "python -m nuitka --follow-imports main.py". It successfully generated "main.bin".
When I run main.bin with "sudo ./main.bin". It gave me the following error.

(urlshort_fastapi) hkhk@hkhk-MS-7C37:~/urlshort_fastapi$ sudo ./main.bin 
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Started reloader process [17640] using statreload
Traceback (most recent call last):
  File "/home/hkhk/urlshort_fastapi/main.py", line 339, in <module>
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
  File "/home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/site-packages/uvicorn/main.py", line 356, in run
    supervisor.run()
  File "/home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/site-packages/uvicorn/supervisors/basereload.py", line 41, in run
    self.startup()
  File "/home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/site-packages/uvicorn/supervisors/basereload.py", line 61, in startup
    self.process.start()
  File "/home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 39, in _launch
    from . import resource_tracker
  File "/home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/multiprocessing/resource_tracker.py", line 38, in <module>
    import _posixshmem
ImportError: /home/hkhk/anaconda3/envs/urlshort_fastapi/lib/python3.8/lib-dynload/_posixshmem.cpython-38-x86_64-linux-gnu.so: undefined symbol: shm_unlink

If I run "python -m nuitka --standalone --follow-imports --show-progress --show-scons --show-modules --jobs=15 --include-package=pydantic --include-package=fastapi --include-module=uvicorn.logging --include-module=uvicorn.protocols.http --include-module=uvicorn.loops --include-module=uvicorn.lifespan --include-module=uvicorn.protocols.websockets main.py", it still not working.

hkhk@hkhk-MS-7C37:~/urlshort_fastapi/main.dist$ ./main 
Traceback (most recent call last):
  File "/home/hkhk/urlshort_fastapi/main.dist/importlib/resources.py", line 97, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: '/home/hkhk/urlshort_fastapi/main.dist/certifi/cacert.pem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hkhk/urlshort_fastapi/main.dist/main.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/fastapi/__init__.py", line 7, in <module fastapi>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/fastapi/applications.py", line 3, in <module fastapi.applications>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/fastapi/routing.py", line 8, in <module fastapi.routing>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/fastapi/dependencies/models.py", line 3, in <module fastapi.dependencies.models>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/fastapi/security/__init__.py", line 1, in <module fastapi.security>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/fastapi/security/api_key.py", line 3, in <module fastapi.security.api_key>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/fastapi/openapi/models.py", line 8, in <module fastapi.openapi.models>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/email_validator/__init__.py", line 6, in <module email_validator>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/dns/resolver.py", line 38, in <module dns.resolver>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/dns/query.py", line 40, in <module dns.query>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/requests/__init__.py", line 120, in <module requests>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "/home/hkhk/urlshort_fastapi/main.dist/requests/utils.py", line 40, in <module requests.utils>
  File "/home/hkhk/urlshort_fastapi/main.dist/certifi/core.py", line 37, in where
  File "/home/hkhk/urlshort_fastapi/main.dist/contextlib.py", line 113, in __enter__
  File "/home/hkhk/urlshort_fastapi/main.dist/importlib/resources.py", line 201, in path
  File "/home/hkhk/urlshort_fastapi/main.dist/importlib/resources.py", line 111, in open_binary
FileNotFoundError: 'cacert.pem' resource not found in 'certifi'

It seems that a .so file is not included in the executable file. As a beginner of this library.  I read issues, which say nuitka 0.6.8 should work well on fastapi. I am a little confused what the problem. Can you give me some tips? Thank you.

**Comment by kayhayen** [comment] 2020-08-26 15:29
This is a duplicate of an issue fixed on develop, certific data file missing.

**Closed by kayhayen** 2020-08-26 15:29 UTC
