### ISSUE TITLE
Specifying libusb backend and USB device not detected when compiling with nuitka 

### ISSUE THREAD

**Issue by 01baftb** [Nuitka/Nuitka#2598] opened 2023-12-08 07:24 UTC
My application communicates with a specific device over USB. For Python to detect the device, I have to use https://github.com/pyocd/libusb-package and specify the backend. Below is my sample code: 

```python 
# Content of test_usb_comm.py
import libusb_package # https://github.com/pyocd/libusb-package
import usb.core
import usb.backend.libusb1
libusb1_backend = usb.backend.libusb1.get_backend(find_library=libusb_package.find_library)

def find_my_usb_devices(idVendor=0x0403, idProduct=0x90D9):
    device_list = []
    devices = usb.core.find(find_all=True, idVendor=0x0403, idProduct=0x90D9)
    for dev in devices:
        device_list.append(dev)
    return device_list

print(f'Listed of USB devices with the desired Vendor/Product ID:')
print(find_my_usb_devices(idVendor=0x0403, idProduct=0x90D9))
```

Below is the output when I run the python script: _test_usb_comm.py_.
```
Listed of USB devices with the desired Vendor/Product ID:
[<DEVICE ID 0403:90d9 on Bus 001 Address 008>]
```

**Problem:** After I compile my Python script, _test_usb_comm.py_, to an _test_usb_comm..exe_ file using Nuitka, my USB device is not being detected. I use this command to compile: `python -m nuitka --standalone .\test_usb_comm.py`. Below is the output I get when I run the .exe file. As you can see, my USB device is not detected. 

```
Listed of USB devices with the desired Vendor/Product ID:
[]
```

**Comment by KevinRodriguez777** [comment] 2023-12-08 07:59
Thank you for the report, this will be added to nuitka in a future version, for the moment you can easily support it yourself with the following flag `--user-package-configuration-file=config.yaml` with the following content as your config.yaml
```yaml
- module-name: "libusb_package"
  dlls:
    - from_filenames:
        prefixes:
          - "libusb"
```

**Comment by 01baftb** [comment] 2023-12-08 10:10
> Thank you for the report, this will be added to nuitka in a future version, for the moment you can easily support it yourself with the following flag `--user-package-configuration-file=config.yaml` with the following content as your config.yaml
> 
> ```yaml
> - module-name: "libusb_package"
>   dlls:
>     - from_filenames:
>         prefixes:
>           - "libusb"
> ```

Thank you for quick response. Your solution did fix the issue! However, it only worked for the sample code I posted which is a single file script. For a larger application, where the main application that is being compiled, it did not work. I got it working with a larger application by adding the flags: `--include-package=libusb_package --include-package-data=libusb_package`. 

One question: Do I have to specify the _config.yaml_ file when I am building a package (i.e. https://github.com/Nuitka/Nuitka#use-case-3---package-compilation) instead of a .exe file?

**Comment by KevinRodriguez777** [comment] 2023-12-08 16:15
I would need an minimal reproducible example that fails that config, if you can share it with us please do let us know, 
`--include-package=libusb_package --include-package-data=libusb_package` should have no effect on your larger application since of the way `libusb_package` works, i suspect the issue is somewhere else, namely `pyusb` 
other than that if you have something that works, use it.
as for your question, module mode needs a wheel packaging, and including other peoples packages is not good for wheels, should just depend on libusb and use that uncompiled.
other than that i'm closing this we get an MRE that fails that config.

**Closed by KevinRodriguez777** 2023-12-08 16:15 UTC
