### ISSUE TITLE
Error finding parent package of win32com sub-module on macOS

### ISSUE THREAD

**Issue by emre84** [Nuitka/Nuitka#1833] opened 2022-10-09 04:09 UTC
Environment:
MACOS Monterey
Python:3.7.3
Nuitka 'Nuitka-1.1.3'

How did you install Nuitka and Python
pip

Provide in your issue the Nuitka options used
sudo python3.7 -m nuitka --run --standalone  --enable-plugin=numpy,pyside2 --noinclude-pytest-mode=nofollow --noinclude-setuptools-mode=nofollow --python-flag=no_site main.py

Error during nuitka standalone compilation:
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
PASS 1: 62.6%|███████████████▋         | 683/1091, pkg_resources._vendor.appdirsTraceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/__main__.py", line 138, in <module>
    main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/__main__.py", line 124, in main
    MainControl.main()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/MainControl.py", line 924, in main
    main_module = _createNodeTree(filename=filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/MainControl.py", line 208, in _createNodeTree
    optimizeModules(main_module.getOutputFilename())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 343, in optimizeModules
    finished = makeOptimizationPass()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 297, in makeOptimizationPass
    changed = optimizeModule(current_module)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 188, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 150, in optimizeCompiledPythonModule
    considerUsedModules(module=module, signal_change=signalChange)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/importing/Recursion.py", line 434, in considerUsedModules
    source_ref=source_ref,
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/nuitka/importing/Recursion.py", line 369, in _addParentPackageUsages
    assert parent_package_filename is not None, parent_package_name
AssertionError: win32com

My nuitka --version output:
emres-Air:inference emre$ sudo python3.7 -m nuitka --version
1.1.3
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: Unknown
Executable: /usr/local/bin/python3.7
OS: Darwin
Arch: x86_64

Thanks a lot in advance.

**Comment by emre84** [comment] 2022-10-09 04:15
Note:The same Code was compilable with Nuitka 1.0.5

**Comment by kayhayen** [comment] 2022-10-09 08:40
I wish I had an example code provided with this one. I am noticing, however, that the win32com configuration is lacking constraints on being only done for Win32 OS, which may or may not help.

But I guess, the error message should provide more context. Please try with current factory and report what it says. Should be a different error now, a proper red exit message with information rather than a call stack.

**Comment by emre84** [comment] 2022-10-09 09:43
Hi Kay, Thanks. I will install https://github.com/Nuitka/Nuitka/tree/factory, recompile and I will let you know today. If we cannot get a proper error message. I will try my best to reproduce with a small code part.

**Comment by kayhayen** [comment] 2022-10-09 09:59
I am OK with only the error report, it should have to be revealing enough.

**Comment by emre84** [comment] 2022-10-09 10:01
Error message of https://github.com/Nuitka/Nuitka/tree/factory:
Nuitka-Plugins:WARNING: pyside2: For the standard PySide2 incomplete workarounds
Nuitka-Plugins:WARNING: are applied. For full support:
Nuitka-Plugins:WARNING: https://nuitka.net/pages/pyside2.html
Nuitka:INFO: Starting Python compilation with Nuitka '1.2rc4' on Python '3.7' commercial grade 'not installed'.
Nuitka-Plugins:INFO: pyside2: Injecting post-module load code for module 'PySide2':
Nuitka-Plugins:INFO: pyside2:     Monkey patching classes derived from PySide2 base classes to pass PySide2 checks.
Nuitka-Plugins:INFO: multiprocessing: Injecting pre-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" load environment.
Nuitka-Plugins:INFO: multiprocessing: Injecting post-module load code for module 'multiprocessing':
Nuitka-Plugins:INFO: multiprocessing:     Monkey patching "multiprocessing" for compiled methods.
Nuitka-Plugins:INFO: pyside2: Injecting post-module load code for module 'PySide2.QtCore':
Nuitka-Plugins:INFO: pyside2:     Setting Qt library path to distribution folder. We need to avoid loading target
Nuitka-Plugins:INFO: pyside2:     system Qt plugins, which may be from another Qt version.
Nuitka-Plugins:INFO: pyside2: Unwanted import of 'PyQt5' that conflicts with 'PySide2' encountered, preventing
its use. As a result an "ImportError" might be given at run time. Uninstall it for full compatible
behavior with the uncompiled code to debug it.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest' encountered.  
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.result'
Nuitka-Plugins:WARNING: encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.case'
Nuitka-Plugins:WARNING: encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.suite'
Nuitka-Plugins:WARNING: encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.loader'
Nuitka-Plugins:WARNING: encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.main'
Nuitka-Plugins:WARNING: encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.runner'
Nuitka-Plugins:WARNING: encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.signals'
Nuitka-Plugins:WARNING: encountered.
Nuitka-Plugins:WARNING: anti-bloat: Unwanted import of 'unittest.util'
Nuitka-Plugins:WARNING: encountered.
Nuitka-Plugins:INFO: pkg-resources: Injecting post-module load code for module 'pkg_resources':
Nuitka-Plugins:INFO: pkg-resources:     Registering Nuitka loader with "pkg_resources".
FATAL: Error, failed to local parent package file for 'win32com' parent of 'win32com.shell' (used by pkg_resources._vendor.appdirs) module (not-found)

**Comment by kayhayen** [comment] 2022-10-09 10:08
So, I guess, this ought to be a ridiculously simple reproducer, I will get back to you.

**Comment by kayhayen** [comment] 2022-10-09 10:53
I fail to reproduce it. A report of `--version` with the current factory would be helpful, since it fails to detect the vendor. I tried Anaconda and CPython, is this Homebrew, for which detection got enhanced recently. The pkg_resources fails to list in freeze outputs, not does it have a version by itself. Maybe just attach the file that is equivalent to this  for me: `..../site-packages/pkg_resources/_vendor/appdirs.py`

**Comment by emre84** [comment] 2022-10-09 17:38
I guess this all what you want.
1.2rc4
Commercial: None
Python: 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 16:52:21) 
Flavor: Unknown
Executable: /usr/local/bin/python3.7
OS: Darwin
Arch: x86_64

[appdirs.txt](https://github.com/Nuitka/Nuitka/files/9742218/appdirs.txt)

**Comment by kflathers-chwy** [comment] 2022-10-10 17:40
I am experiencing the same issue on version 1.1.3 and MacOS 11.6.7 (20G630)

**Comment by kayhayen** [comment] 2022-10-11 08:38
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by emre84** [comment] 2022-10-11 10:12
Hi Kay, Thanks a lot. I have already started the compilation with factory. I will let you know the results in a couple of hours. 
But good news: win32com sub-module was failing right at the beginning, with your bug fix, no error popped up after 1 hour yet :)

**Comment by emre84** [comment] 2022-10-12 10:30
Sorry for the delay. I have some Laptop problems that I have not enough space to compile my code. I have to clean some stuff to be able to compile. I will let you know, when the compilation is completed.

**Comment by kayhayen** [comment] 2022-10-13 09:09
@emre I really meant it where I wrote: Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2022-10-13 10:09
The fix that pywin32 related hacks are applied outside of win32 is on the hotfix. Otherwise things like avoiding pywin32 from appdirs entirely are going to be in 1.2 only.

**Comment by emre84** [comment] 2022-10-13 15:06
Compilation works fine. So no win32com error anymore. I am just getting an import error about from cryptography.fernet import Fernet. But I will open an other issue for it.

Thanks a lot.

**Comment by kayhayen** [comment] 2022-11-22 17:05
Part of the 1.2 release that was made a while ago.

**Closed by kayhayen** 2022-11-22 17:05 UTC
Labels: bug, develop
