### ISSUE TITLE
Question: Rename running --onefile executables in windows

### ISSUE THREAD

**Issue by matthj1** [Nuitka/Nuitka#1419] opened 2022-02-10 16:14 UTC
First of all thank you for creating Nuitka, it's a brilliant tool.

I'd like to ask about renaming running executables. I have a python program that I would normally build with pyinstaller. It can self-update by copying itself and changing the name of the running executable to backup. When the system reboots, the new executable runs.

This doesn't seem to work with Nuitka using onefile mode. I get permission denied.

`PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\IEUser\\Desktop\\agent_normal_nuitka\\agent.exe' -> 'C:\\Users\\IEUser\\Desktop\\agent_normal_nuitka\\agent_backup.exe' `

I can see that in Windows, when you use onefile mode, running the executable creates a temporary folder and kicks off a child process that runs the actual program, presumably putting a lock on renaming the parent. Is this correct? Am I correct in assuming because of this, there's no way around the problem of not being able to rename a onefile executable while it's running?

**Comment by kayhayen** [comment] 2022-02-18 10:23
I think running executables on Windows cannot be changed, but always renamed, Windows locks are weak and not from Nuitka there. I am trying it myself, never did that so far. For Nuitka commercial there will be an auto-updating feature, when the executable needs to do it itself, but it's not yet implemented.

I will however be very surprised if that is something that Nuitka managed. Are these binaries signed?

**Comment by kayhayen** [comment] 2022-02-18 10:29
I managed to reproduce this. I have to admit, I have no clue how it's happening. :)

**Comment by kayhayen** [comment] 2022-02-18 10:34
This is definitely no intended, maybe it's because of the parent monitoring indeed. But it could also be a mistake in how the payload is read, and possibly a file is not closed. This will be something to bisect, obviously.

**Comment by kayhayen** [comment] 2022-02-18 11:02
It is fixed on the factory branch, not sure there is a hotfix before 0.7 release, but it would be suitable for that. https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment] 2022-02-20 12:34
This is part of the 0.7 release now.

**Closed by kayhayen** 2022-02-20 12:34 UTC
Labels: bug, factory

**Comment by matthj1** [comment] 2022-02-21 09:44
Thanks for sorting this so quickly, I really appreciate it.
