### ISSUE TITLE
Please provide a way not to include PySide6 python code without using --nofollow-import-to=PySide6

### ISSUE THREAD

**Issue by sherpya** [Nuitka/Nuitka#3263] opened 2024-12-15 15:14 UTC
PySide6 is LGPL-licensed, so the resulting binary should allow for the replacement of PySide6 and Qt6.

I attempted to build using the `--nofollow-import-to=PySide6` option and then copied the PySide6 and shiboken6 directories manually. While this approach works, it introduces a significant issue: you lose dependency tracking.

If I recall correctly, there might be an option to include a module as a Python file without compiling it into the binary. Could you confirm if such an option exists, or suggest an alternative solution to maintain dependency tracking while complying with the LGPL requirements?

**Comment by kayhayen** [comment] 2024-12-16 11:07
This mode of operation is currently unsupported. It might be added, but for now this duplicate of plans to add this.

**Closed by kayhayen** 2024-12-16 11:07 UTC
