### ISSUE TITLE
Extension modules below unworthy namespaces use compiled modules after demotion to bytecode

### ISSUE THREAD

**Issue by rjzak** [Nuitka/Nuitka#500] opened 2019-08-23 18:58 UTC
OS: Ubuntu 18.04.3
Python: 3.7.3 (Anaconda)
Tensorflow: 1.14.0
I started with the script shown in #388. 

    $ python -m nuitka --follow-imports --standalone --plugin-enable=numpy --plugin-enable=tensorflow --plugin-enable=pylint-warnings tftest.py 
    Nuitka:INFO:'tensorflow' plugin: Patched 'running-from-pip' path magic.
    Nuitka:WARNING:Use '--plugin-enable=qt-plugins' for: Inclusion of Qt plugins.
    Problem with statement at /opt/anaconda3/lib/python3.7/site- packages/google/protobuf/__init__.py:1:
    -> # Protocol Buffers - Google's data interchange format

    Nuitka:INFO:Interrupted while working on '<Node 'COMPILED_PYTHON_PACKAGE' with {'filename': '/opt/anaconda3/lib/python3.7/site-packages/google/protobuf/__init__.py', 'package': 'google', 'name': 'protobuf'}>'.
    Traceback (most recent call last):
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/__main__.py", line 184, in <module>
    main()
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/__main__.py", line 177, in main
    MainControl.main()
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/MainControl.py", line 759, in main
    main_module = createNodeTree(filename=filename)
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/MainControl.py", line 141, in createNodeTree
    Optimization.optimize(main_module.getOutputFilename())
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 561, in optimize
    finished = makeOptimizationPass(initial_pass=False)
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 456, in makeOptimizationPass
    changed = optimizeModule(current_module)
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 167, in optimizeModule
    changed = optimizeCompiledPythonModule(module)
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/optimizations/Optimization.py", line 100, in optimizeCompiledPythonModule
    module.computeModule()
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/nodes/ModuleNodes.py", line 514, in computeModule
    trace_collection=self.trace_collection
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/nodes/StatementNodes.py", line 167, in computeStatementsSequence
    new_statement = trace_collection.onStatement(statement=statement)
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 549, in onStatement
    new_statement, change_tags, change_desc = statement.computeStatement(self)
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/nodes/AssignNodes.py", line 261, in computeStatement
    trace_collection.onExpression(self.getAssignSource())
      File "/opt/anaconda3/lib/python3.7/site-packages/nuitka/optimizations/TraceCollections.py", line 525, in onExpression
    parent = expression.parent
    AttributeError: parent

I think it's odd that Nuitka throws a warning about enabling qt-plugins, when Qt isn't being used. The script in #388 simply imports Tensorflow and says "hello world".

**Comment by rjzak** [comment] 2019-08-23 22:05
It seems to be an error with Google's Protocol buffers, specifically how protobuf is imported in the package's `__init__.py`. At first, I thought Nuitka was having a problem with comments. I deleted the comments, and it still can't parse the file. But what remains is:

    if __name__ != '__main__':
      try:
        __import__('pkg_resources').declare_namespace(__name__)
      except ImportError:
        __path__ = __import__('pkgutil').extend_path(__path__, __name__)

**Comment by kayhayen** [comment] 2019-08-24 08:04
Just to address the comments question, they are dropped in the parser, Nuitka never sees them. Some plugins attempt to parse e.g. pylint ones, but this is not relevant normally.

**Comment by kayhayen** [comment] 2019-08-24 08:05
As for the Qt, you wouldn't believe how odd imports are embedded in third party software like this one, and Nuitka cannot tell if it's your wish or not.

**Comment by kayhayen** [comment] 2019-08-24 08:10
I could not immediate reproduce the issue with the snippet given. From the traceback I figure, that the assignment of the `__import__` is the one triggering it, but right now I am clueless as to how it happens. I will try the bigger context of Anaconda now.

**Comment by JorjMcKie** [comment] 2019-08-24 08:21
> I could not immediate reproduce the issue with the snippet given. From the traceback I figure, that the assignment of the __import__ is the one triggering it, but right now I am clueless as to how it happens. I will try the bigger context of Anaconda now.

I compiled a TF test script again, and saw the same issue (``Problem with statement at ...``).
It used to work in an earlier version  - don't currently know which one worked last. A wild guess: something to do with different bytecode handling?
It does not have anything to do with Anaconda environment - my test was a "normal" Python 3.7.4 WIndows 10 environment.

**Comment by JorjMcKie** [comment] 2019-08-24 08:26
> I think it's odd that Nuitka throws a warning about enabling qt-plugins, when Qt isn't being used.

With few exceptions, a source code parser like Nuitka **_cannot_** possibly know which import will eventually never be executed - hence the warning.

But it is irrelevant for this issue anyway.

**Comment by AetherPrior** [comment] 2019-08-24 08:44
Weirdly enough, when I tried to run this on python3, nuitka took a really long time to build, and I was unable to complete the build whatsoever. Does it take a very long time to generate the C code for this?

**Comment by JorjMcKie** [comment] 2019-08-24 08:56
> 
> 
> Weirdly enough, when I tried to run this on python3, nuitka took a really long time to build, and I was unable to complete the build whatsoever. Does it take a very long time to generate the C code for this?

The compile time is practically independent from the size of your script. It depends on the number and size of the packages pulled in. Some of them are simply monsters, especially Tensorflow.

Compile time also goes down after a while, namely when you let Nuitka collect information of the whereabouts of shared libraries (via the caching arguments).
You also can try to restrict the modules being considered by using hinted compilation.

**Comment by kayhayen** [comment] 2019-08-24 11:17
@AetherPrior tensorflow is an incredibly large project, using everything potentially and Nuitka compiles for standalone mode, everything used, which makes it a very bad case.

This however is an optimization error. Nuitka during optimization replaces nodes with other nodes, while visiting it for abstract executing. During that, it tried to execute a node, probably a freshly replaced one, which has no parent, which is considered illegal of course.

Often issues will be about dependencies, other times, about concrete code.

What we would really need, to solve these kinds of issue efficiently, is a collection of the source code that was in use. I am right now installing latest greated Anaconda, and am hoping to reproduce the issue, @JorjMcKie did not, and I might neither, and these things are very annoying, esp. with the proliferation of differences between Python wheels on OSes.

And what can I say, installing Anaconda is not as easy, had to google that `call condabin\conda.bat activate` is what it takes to make it work. In the past, `conda` binary just worked, but they stopped that 2 releases ago it seems.

Yours,
Kay

**Comment by kayhayen** [comment] 2019-08-24 11:19
The optimization bug will be very sensitive to minor source code changes, could be a slightly different version of google buffers. But it will be a general issue for sure. Obviously since it's old, I assmume at least, it will be rare to trigger.

**Comment by kayhayen** [comment] 2019-08-24 11:23
Plus, installing tensorflow in Anaconda moves you away from stale things, changing Anaconda to custom. Probably my fault for not using their environments, but polluting base environment.

I envision a world, where on crash, we iterate the modules loaded, and put together a package with the source code that was loaded, for people to share it potentially. I am OK with this not being the default, most of the time it's not needed and/or overkill.

**Comment by kayhayen** [comment] 2019-08-24 17:35
I managed to reproduce the crash, albeit in "Cython package. I think what they have in common, is the bytecode demotion part. Maybe it's being used despite being converted to bytecode, should be something like that.

**Comment by kayhayen** [comment] 2019-08-24 17:44
I think I recall that `google` is demoted by the Tensorflow plugin if used, and `Cython` is always by default, so strong indications there. Likely a severe regression for one of the last releases or so. Some imports have direct links, most do not. Maybe something is flawed there. But this looks to me as if finalized nodes are used...

**Comment by kayhayen** [comment] 2019-08-24 17:47
Just noticed, when I reduced the test case to `import Cython` that it imports the PyQt5, which is of course severe dependency creep from just that.

**Comment by kayhayen** [comment] 2019-08-24 18:00
And yes, `import Cython` is crashing for me with Anaconda. So that means it has nothing to do with Tensorflow.

**Comment by kayhayen** [comment] 2019-08-24 18:05
Seems it imports `IPython` which includes all the things Python knows, how painful, I just saw `jedi` a Python analysis engine,  `jinja2` of course, `PIL`,  `sphinx`, all the things that use everything, there is a couple of parser generators surely included, in just that.... cryptography... ah the pain...

My goodness, I think we really need to go further than demoting to bytecode, but to fully stub these things to not follow their imports, at least in some cases.

**Comment by kayhayen** [comment] 2019-08-24 18:25
So after first pass is complete (and this really by itself ought to be cached, if the whole reason it's being done is to find the dependencies of that bytecode module to be), it says this:

> Nuitka:INFO:Demoting module 'Cython' to bytecode from 'C:\Users\kayha\Anaconda3_64\lib\site-packages\Cython\__init__.py'.

Later. Note the `module dependency considerations` means it's optimizing bytecode only, which is just to follow its dependencies, which can be compiled or not.

> Nuitka:INFO:PASS 2 ... :
> Nuitka:INFO:Next global optimization pass.
> Nuitka:INFO:Optimizing module '__main__', 17 more modules to go after that.
> Nuitka:INFO:Doing module local optimizations for '__main__'.
> Nuitka:INFO:Optimizing module 'Cython', 20 more modules to go after that.
> Nuitka:INFO:Doing module dependency considerations for 'Cython':


But then, same pass

> Nuitka:INFO:Optimizing module 'Cython.Compiler.Optimize', 81 more modules to go after that.
> Nuitka:INFO:Doing module dependency considerations for 'Cython.Compiler.Optimize':
> Nuitka:INFO:Optimizing module 'traceback', 82 more modules to go after that.
> Nuitka:INFO:Doing module dependency considerations for 'traceback':
> Nuitka:INFO:Optimizing module 'codecs', 81 more modules to go after that.
> Nuitka:INFO:Doing module dependency considerations for 'codecs':
> Nuitka:INFO:Optimizing module 'Cython.Compiler.FusedNode', 80 more modules to go after that.
> Nuitka:INFO:Optimizing module 'Cython', 81 more modules to go after that.
> Nuitka:INFO:Doing module local optimizations for 'Cython'.
> Problem with statement at C:\Users\kayha\Anaconda3_64\lib\site-packages\Cython\__init__.py:1:

Lots of modules were not optimized. Notice how `Cython.Compiler.FusedNode` does not indicate that it's a bytecode module. Something is foul there. Probably the module also ought to realize that it was disabled, and should never enter any level of computation anymore without error, or even be added to the computation for that.

BTW: A proper cache would have to look at all the files in `sys.path` for imports of the module as a key, but it seems to be absolutely worthwhile, so it's only needed once ever to compile Cython with a given Nuitka version.

**Comment by kayhayen** [comment] 2019-08-24 18:28
And I think, I have a strong hint, as to why it's happening, by looking at this:

> find . -iname Fused*
> ./Lib/site-packages/Cython/Compiler/FusedNode.cp37-win_amd64.pyd
> ./Lib/site-packages/Cython/Compiler/FusedNode.py 

The extension module is the one which will be imported (although there is a strong case for not using it of course, rather the bytecode of the python module, but that would be incompatible), and it seems  Nuitka is locking parent packages by module reference rather than by name.

**Comment by kayhayen** [comment] 2019-08-25 08:54
So, the caching of the parent package as an object is of course unnecessary, it's sufficient to let the module registry do that, it's tasked for that.

I have an experimental change on factory branch that ought to be good, but I am on the road right now and cannot test it, but I am pretty confident about it.

**Comment by kayhayen** [comment] 2019-08-25 16:27
I had the chance to try factory, and while it's incredibly slow, it works for me now. The crash is solved, the performance issue, makes me want to look into what people import from `Cython` and make sure, it doesn't escalate by monkey patching its source before compilation, so we do not have the tremendous dependency creep this easily.

**Comment by kayhayen** [comment] 2019-09-20 08:59
Part of the latest pre-release rc6.

**Comment by kayhayen** [comment] 2019-12-27 09:41
Released as part of 0.6.6

**Closed by kayhayen** 2019-12-27 09:41 UTC
Labels: bug, develop

**Comment by kayhayen** [comment] 2020-05-11 15:05
The release 0.6.8 was just made and contains the correction.
