### ISSUE TITLE
ImportError: LoadLibraryEx fails for win32ui.pyd on 64 bit Windows Python

### ISSUE THREAD

**Issue by vi-s** [Nuitka/Nuitka#208] opened 2018-12-17 15:36 UTC
My application compiled without any problems on Nuitka until I imported win32ui as an additional runtime library. The compilation process goes fine, but at runtime, the app errors out and closes immediately, being unable to load the win32ui.pyd file. Below is the stack trace:
```
C:\Users\vikram\Desktop\ms\nuitka\app.dist\app.exe
Traceback (most recent call last):
  File "C:\Users\vikram\Desktop\ms\nuitka\app.dist\app.py", line 75, in <module>
ImportError: LoadLibraryEx 'C:\Users\vikram\Desktop\ms\nuitka\app.dist\win32ui.pyd' failed
```
It's kind of strange and unexplained to me, as the win32ui pyd file is definitely in the dist directory, and it is found, but still throws an import error at runtime. I am also using win32gui module, from the same pywin32 package. I have been able to compile + run the app with no problems just using win32gui at runtime, but somehow importing win32ui ends up causing the error. So I am not pulling in any extra dependency packages, just an extra module from the pywin32 package I have already been using to compile + run successfully. 

To make things all the stranger, the same compiled app exe + dlls that throws the runtime error on one machine, works just fine on another.. I have tried to compile with a cleared cache, but no luck. If anyone has an idea of what's going on I'd be curious to know.

There was a similar issue here, but for a different library (QtWidgets.pyd), linked:
https://github.com/Nuitka/Nuitka/issues/73

I installed Nuitka using pip, and here is the Nuitka version info:
```
0.6.0.6
Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
Executable: C:\Python27\python.exe
OS: Windows
Arch: x86_64
```

**Comment by kayhayen** [comment] 2018-12-24 16:34
So in hunting this down further:

a) PyWin32 requires two DLLs in its SxS configuration. One is the C library, the other is the MFC library of MSVC.

b) Nuitka picks up the one from "pythonwin" which PyWin32 installed.

c) This is the wrong one, it should be the SxS one, although copying it there didn't make it stop complaining, there are likely more DLLs needed.

**Comment by kayhayen** [comment] 2018-12-25 10:17
Interestingly dependencywalker also does report the same error as LoadLibraryEx does, the fact that SxS could not be satisfied, then shows `mfc90.dll` from pythonwin as used.  That is after moving the SxS up in priority as it probably ought to be. Currently it is last.

I really wonder if this means that Dependency Walker is doing more than it is supposed to do, i.e. actually loads the library for a run time analysis, where I am expecting an offline analysis, that would also make thing slow. But that is a separate issue clearly.

I tried to write code that removes SxS config from DLLs, but that didn't immediately succeed. I will now first check if removing the SxS config with Visual Studio works, as it seems a bit tricky.

Also, there seems to be error dialog suppression code in CPython, and better output in the Windows code that loads pyd files. I am going to integrate those. Who knows, if the SxS error goes away then.

Also I need to check if `python.exe` actually does load the one SxS variant of the MFC dll that is in question, or if it also fails, but somehow more silent. Maybe the .pyd file has more of an expectation of a relative path to find things. But my understanding is that SxS error is before any code is to be executed, so that should not be possible.

**Comment by kayhayen** [comment] 2018-12-25 11:06
So removing the SxS config of `win32ui.pyd` with Visual Studio, and it just works. I checked with Anaconda, and there it has SxS config too. 

I really wonder why they include a SxS config that is invalid, seems like an upstream problem right there.

Seems CPython ignored the SxS config somehow and gets away with it, loading the .pyd with no issues. I need to check if error suppression is the issue here.

**Comment by kayhayen** [comment] 2018-12-25 12:00
Ok, this won't be easy, it may be a lot easier to remove all SxS configuration from everything, just automatically. I think the `MSCRT90.DLL` refuses to load without a manifest in the exe file, but apparently not the case for `MFC90.DLL,` so manifests in the standalone distribution ought to not contribute anything. 

It just seemed non trivial to delete resources, there is no tool that does it, it would only replace things, but with a ctypes usage, it should be possible to list all manifest resources, and then to open and modify them, where setting it NULL is going to delete it.

Code for this should be created by imitating this https://github.com/ronreiter/PyRes/blob/master/pyres.py

Not sure how slow the search for SxS config is going to be. And not sure how slow the removal is going to be. It sure wouldn't have to be slow.

Obviously this is only for Python2, for Python3 the MSVC compilers used no longer do this crap.

I am unsure why with 32 bits I am not seeing the issue. Maybe I just happen to have to SxS for it installed and not for 64. It very probably can be ignored that this only happens with certain bits.

Yours,
Kay

**Comment by kayhayen** [comment] 2018-12-25 17:18
I failed to reproduce the issue I had observed with `sys.path` not containing the `.pth` files added, so this was probably a mistake of mine.

**Comment by vi-s** [comment] 2018-12-25 21:52
Hey Kay, 

Happy holidays! Thanks for your research, the issue seems like a strange one indeed.. I think it may just be time to upgrade my project to python 3... I also had some other nasty issues on python2 with default ascii encoding instead of utf8 for ex (which would sometimes throw utf8 decode errors if some of the machine specific resources loaded included non ascii chars), and also tkinter thread safety bugs which are resolved in python3, and now this also seems to be a python2 issue. 

I hadn't anticipated all these bugs in python2 when I decided to roll with it for this project.. but now I know, haha. Will definitely be using python3 going forward. 

Do you know if using python3 with MinGW compiler for nuitka would be ok, or should I be using the msvc compiler with nuitka? Does it make a difference?

**Comment by vi-s** [comment] 2018-12-26 18:54
Hi Kay,

Ok, I understand that the SxS issue is not really related to python2 vs 3 ; rather its the invalid SxS config used during runtime to load the .pyd's by the older MSVC 9.0, if I understand correctly. 

I did just try to run the factory branch compiler on my project, and unfortunately I got the same error ```ImportError: LoadLibraryEx``` , I figure there may be additional complications in my environment that are not immediately obvious. I'm not sure how I would report them though since the error message is the same one that I got before.

**Comment by kayhayen** [comment] 2018-12-26 19:05
Hello there,

if you put --python-flag=-v and search for the ImportError in the output, there will be an indication of which module it is that is failing to load. Just scroll up the "cleanup" mess.

Yours,
Kay

**Comment by vi-s** [comment] 2018-12-26 19:11
Alright, was just able to run it with the extra cl arg, and have pasted the output below:

```
# installing zipimport hook
import zipimport # builtin
# installed zipimport hook
Setup nuitka compiled module/bytecode/shlib importer.
import os # considering responsibility
import os # claimed responsibility (compiled)
Loading os
import errno # considering responsibility
import errno # denied responsibility
import errno # builtin
import nt # considering responsibility
import nt # denied responsibility
import nt # builtin
import ntpath # considering responsibility
import ntpath # claimed responsibility (compiled)
Loading ntpath
import stat # considering responsibility
import stat # claimed responsibility (compiled)
Loading stat
import genericpath # considering responsibility
import genericpath # claimed responsibility (compiled)
Loading genericpath
import warnings # considering responsibility
import warnings # claimed responsibility (compiled)
Loading warnings
import linecache # considering responsibility
import linecache # claimed responsibility (compiled)
Loading linecache
import types # considering responsibility
import types # claimed responsibility (frozen)
Loading types
import types # frozen
import UserDict # considering responsibility
import UserDict # claimed responsibility (compiled)
Loading UserDict
import _abcoll # considering responsibility
import _abcoll # claimed responsibility (compiled)
Loading _abcoll
import abc # considering responsibility
import abc # claimed responsibility (compiled)
Loading abc
import _weakrefset # considering responsibility
import _weakrefset # claimed responsibility (compiled)
Loading _weakrefset
import _weakref # considering responsibility
import _weakref # denied responsibility
import _weakref # builtin
import copy_reg # considering responsibility
import copy_reg # claimed responsibility (frozen)
Loading copy_reg
import copy_reg # frozen
import site # considering responsibility
import site # claimed responsibility (compiled)
Loading site
import traceback # considering responsibility
import traceback # claimed responsibility (compiled)
Loading traceback
import sys # considering responsibility
import sys # denied responsibility
import sys # previously loaded (sys)
import encodings # considering responsibility
import encodings # claimed responsibility (frozen)
Loading encodings
import encodings # frozen package
import encodings.codecs # considering responsibility
import encodings.codecs # denied responsibility
import codecs # considering responsibility
import codecs # claimed responsibility (frozen)
Loading codecs
import codecs # frozen
import _codecs # considering responsibility
import _codecs # denied responsibility
import _codecs # builtin
import encodings.encodings # considering responsibility
import encodings.encodings # denied responsibility
import encodings.aliases # considering responsibility
import encodings.aliases # claimed responsibility (frozen)
Loading encodings.aliases
import encodings.aliases # frozen
import encodings.__builtin__ # considering responsibility
import encodings.__builtin__ # denied responsibility
import encodings.utf_8 # considering responsibility
import encodings.utf_8 # claimed responsibility (frozen)
Loading encodings.utf_8
import encodings.utf_8 # frozen
import pywintypes # considering responsibility
import pywintypes # claimed responsibility (compiled)
Loading pywintypes
import imp # considering responsibility
import imp # denied responsibility
import imp # builtin
import _win32sysloader # considering responsibility
import _win32sysloader # claimed responsibility (compiled)
Loading _win32sysloader
import _win32sysloader # LoadLibraryEx("C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\_win32sysloader.pyd");
Loaded _win32sysloader
import pywintypes # dynamically loaded from C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\pywintypes27.dll
Loaded pywintypes
import win32gui # considering responsibility
import win32gui # claimed responsibility (compiled)
Loading win32gui
import win32gui # LoadLibraryEx("C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\win32gui.pyd");
Loaded win32gui
import win32ui # considering responsibility
import win32ui # claimed responsibility (compiled)
Loading win32ui
import win32ui # LoadLibraryEx("C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\win32ui.pyd");
Traceback (most recent call last):
  File "C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\automsm.py", line 74, in <module>
ImportError: LoadLibraryEx 'C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\win32ui.pyd' failed
```

**Comment by kayhayen** [comment] 2018-12-28 07:01
I think the output shows that you are not using the factory version. I added the tracing of the DLL load error message, which is missing to this mode.

What I have done for this issue, is to create a tool that scans for all SxS packages, and make it run on my CPython 2.7 and Anaconda2 installation, which found 2 more modules with the issue, one of which is in the win32 domain.

I am closing the issue assuming a mistake of yours in trying it out as I could well reproduce it and see it fixed, although now that I think of it, "os.path.normcase()" should be applied to be absolutely sure, I will add that too.

Yours,
Kay

**Closed by kayhayen** 2018-12-28 07:01 UTC
Labels: bug, factory

**Comment by vi-s** [comment] 2018-12-28 21:05
I believe I was using the factory branch, as I cloned a fresh copy from the factory link. I pulled the latest changes from the remote factory branch, and now had my local factory branch at commit: e0b807cae6eb48f53cf782f71f325d9fefad76d7 from 12/28

Still somehow got a similar output as before, pasted the relevant portion:
```
import encodings.utf_8 # frozen
import pywintypes # considering responsibility
import pywintypes # claimed responsibility (compiled)
Loading pywintypes
import imp # considering responsibility
import imp # denied responsibility
import imp # builtin
import _win32sysloader # considering responsibility
import _win32sysloader # claimed responsibility (compiled)
Loading _win32sysloader
import _win32sysloader # LoadLibraryEx("C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\_win32sysloader.pyd");
Loaded _win32sysloader
import pywintypes # dynamically loaded from C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\pywintypes27.dll
Loaded pywintypes
import win32gui # considering responsibility
import win32gui # claimed responsibility (compiled)
Loading win32gui
import win32gui # LoadLibraryEx("C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\win32gui.pyd");
Loaded win32gui
import win32ui # considering responsibility
import win32ui # claimed responsibility (compiled)
Loading win32ui
import win32ui # LoadLibraryEx("C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\win32ui.pyd");
Traceback (most recent call last):
  File "C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\automsm.py", line 74, in <module>
ImportError: LoadLibraryEx 'C:\Users\vikram\Desktop\ms\nuitka\automsm.dist\win32ui.pyd' failed
```
Not sure why that is.. I might be missing something else.
