### ISSUE TITLE
The size of the .exe relative to the pyinstaller is much larger

### ISSUE THREAD

**Issue by ArkadiuszMichalski** [Nuitka/Nuitka#926] opened 2021-01-09 05:07 UTC
Hi, it's normal that Nuitka produce bigger `.exe` file than pyinstaller? I my case I get:
- 21.5 MB (Nuitka)
- 3.58 MB (pyinstaller)

I use different variant, like `--follow-imports`, `--windows-dependency-tool=pefile --experimental=use_pefile_recurse --experimental=use_pefile_fullrecurse`, but not help.

I also try use "Hinted compilation" but still get big exe, reduce only to 20.8 MB. It's normal that compiled code will be larger than what pyinstaller does (it include sources explicitly or use byte code). I wonder what so big was added to this `.exe`, since my source file is only 2.5 KB and instaled lib size is 51MB (where numpy takes 50MB). 

As for the rest of the files I gets a very similar set (from Nuiitka): 
![image](https://user-images.githubusercontent.com/2730894/104083630-86547a80-5240-11eb-95da-552aa481827e.png)

Excluding  `.exe` file I get 52.5MB (Nuitka) vs 49.3 MB (pyinstaller). Is there anything else I can do about it or is it normal for this tool?

**Comment by kayhayen** [comment] 2021-01-10 08:47
Python source code is fundamently smaller than C code. Also Nuitka has a runtime that has a one time overhead. You can save by choosing the right compiler, which is a changing subject, but might be MSVC and latest Nuitka with LTO on both Windows and Linux. The LTO avoids the runtime overhead it seems.

As for the included DLL and extension module files, we are bad with standard library, inclusion of many of these might not be needed, but currently we do not look into standard library yet, so we cannot tell if e.g. the `_uuid.pyd` has actually a chance of being used.

Those flags you are using are partially not even working anymore, but if they are, they are searching for more stuff to include, because due to pefile limitations it doesn't find the things.

I currently don't want to get into standard library with manual tunings, not until the automatic analysis of dependencies also can go there and be fast due to working caching of Nuitka level Python analysis of modules, which we do not have.

So to answer your question, you can try and delete stuff there. For onefile that won't work, as you get no chance to do it, unless you are a plugin. Ok, you can make a Python installation and delete those files from standard library, that is always an option unless Nuitka itself needs them, but it mostly likely does not.

I have heard many times that the size doesn't matter, not sure if that's true. I do semi-care. But it doesn't matter to me enough to warrant a change of plans. It would matter enough if somebody took the effort to help and improve Nuitka caching, but I don't see that happening too soon.

I am most sure this is a duplicate issue though, therefore closing it as it has no actions associated.

Just one last word, chances are that Windows onefile once it compresses, will be smaller than pyinstaller, because it's going to use a more effective compression. That remains to be seen though.

**Closed by kayhayen** 2021-01-10 08:47 UTC
Labels: duplicate

**Comment by ArkadiuszMichalski** [comment] 2021-01-10 16:23
Thanks for the detailed explanation. I started to analyze it more and it seems to me that pyinstaller automatically compresses .exe which is why it takes so little. After compression in a nuitka from 20MB it gets 5MB, still more, but not that much.

I use python as an additional process in a different project, and it is executed frequently. Its size and speed of operation are important to me. I noticed that the .exe compression does not slow down too much, but for example, compressing all files does.

Finally, I noticed that I only use a few things from numpy that can be replaced straight from python. Thanks to this, I got rid of the unnecessary 30MB. Later I will check if it affected the compilation time and the runtime of the .exe.

**Comment by kayhayen** [comment] 2021-01-10 23:55
Can you elaborate more on the numpy bits, that sounds generally useful.

**Comment by ArkadiuszMichalski** [comment] 2021-01-11 00:12
I saw that some package use only two or three method from numpy, but this method exist directly in python, like:
`random.choice(), random.choices(), random.gauss()`. I don't know if numpy is more efficient (especially if you work with large numbers / ranges), but if it doesn't matter then it's worth seeing if you can simply replace them and not use numpy. In my case the entire source is 1MB, where numpy itself takes 50MB, a bit nonsense.

**Comment by kayhayen** [comment] 2021-01-11 01:03
You could also use Pandas, then dependencies would skyrocket even more :)

**Comment by OttomanZ** [comment] 2022-09-13 13:43
@kayhayen Pandas is notorious even in the documentation, that is true, avoid if you can.

**Comment by kayhayen** [comment] 2022-09-21 18:06
I guess, the issue is very outdated, this is before a lot of anti-bloat work was done. We might delete it eventually.
