### ISSUE TITLE
Cannot create standalone executable using setuptools

### ISSUE THREAD

**Issue by daniilS** [Nuitka/Nuitka#3101] opened 2024-08-29 10:40 UTC
<details><summary>python -m nuitka --version</summary>
<p>

```
2.4.8
Commercial: None
Python: 3.12.5 (tags/v3.12.5:ff3bc82, Aug  6 2024, 20:45:27) [MSC v.1940 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\danii\Desktop\nuitka_venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).
```
</p>
</details> 

<details><summary>How did you install Nuitka and Python</summary>
<p>

```
> python -m venv nuitka_venv
> nuitka_venv\Scripts\activate
> pip install nuitka
```

</p>
</details> 

<details><summary>python -m pip list -v</summary>
<p>

```
-------------- ------- ---------------------------------------------------- ---------
example_module 0.0.0   C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages pip
Nuitka         2.4.8   C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages pip
ordered-set    4.1.0   C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages pip
pip            24.2    C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages pip
setuptools     74.0.0  C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages pip
wheel          0.44.0  C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages pip
zstandard      0.23.0  C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages pip
```
</p>
</details> 

### Problem description

Possible regression of #1500: that issue was closed with "This has been dealt with in other issues.", which indicates to me that this should be possible now. However, I am still facing the same issue.

I have a program I want to distribute to end users. It is written as a Python module and uses `setup.py`. It's installed using `pip install example_module` and is then executed using `python -m example_module`. I want to distribute it to end users as a standalone executable, so that it can be run by users without needing to install Python.

Because the project uses `setup.py`, I wanted to use the setuptools method. However, I can't get it to work using the `--standalone` option, as it gives the following error:
```
FATAL: Error, conflicting options, cannot make standalone module, only executable.

Modules are supposed to be imported to an existing Python installation, therefore it
makes no sense to include a Python runtime.
```

My module is only meant to be executed on its own, never imported, so it does make sense to include a Python runtime. Is there a way to make this work using setuptools, or is this not an intended use case, and I should use a different method?

### Minimal reproducible example:
Create the following two files:
<details><summary>\nuitka_example\setup.py</summary>
<p>

```py
import setuptools

setuptools.setup(
    name="example_module",
    packages=["example_module"],
    command_options={"nuitka": {"--standalone": True}},
)

```

</p>
</details> 
<details><summary>\nuitka_example\example_module\__main__.py</summary>
<p>

```py
print("Success!")

```

</p>
</details> 

This works:
```
...\nuitka_example> pip install .
[completes successfully]
...\nuitka_example> python -m example_module
"Success!"
```

Building a wheel works:
```
...\nuitka_example> python setup.py bdist_wheel
[completes succesfully]
```

Building using `bdist_nuitka` doesn't:
```
...\nuitka_example> python setup.py bdist_nuitka
running bdist_nuitka
running build
Nuitka-Wheel: Specified packages: ['example_module'].
Nuitka-Wheel: Specified modules: None.
running build_py
copying example_module\__main__.py -> build\lib\example_module
Nuitka-Wheel: Building: 'example_module' with command '['C:\\Users\\danii\\Desktop\\nuitka_venv\\Scripts\\python.exe', '-m',
Nuitka-Wheel: 'nuitka', '--module', '--enable-plugin=pylint-warnings',
Nuitka-Wheel: '--output-dir=C:\\Users\\danii\\Desktop\\nuitka_example\\build\\lib', '--nofollow-import-to=*.tests',
Nuitka-Wheel: '--remove-output', '--include-package=example_module', '--standalone',
Nuitka-Wheel: 'C:\\Users\\danii\\Desktop\\nuitka_example\\build\\lib\\example_module']'
Nuitka-Options: Used command line options: --module --enable-plugin=pylint-warnings
Nuitka-Options: --output-dir=C:\Users\danii\Desktop\nuitka_example\build\lib --nofollow-import-to=*.tests --remove-output
Nuitka-Options: --include-package=example_module --standalone C:\Users\danii\Desktop\nuitka_example\build\lib\example_module
FATAL: Error, conflicting options, cannot make standalone module, only executable.

Modules are supposed to be imported to an existing Python installation, therefore it
makes no sense to include a Python runtime.
Traceback (most recent call last):
  File "C:\Users\danii\Desktop\nuitka_example\setup.py", line 3, in <module>
    setuptools.setup(
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\setuptools\__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\setuptools\_distutils\dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\setuptools\_distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\wheel\_bdist_wheel.py", line 378, in run
    self.run_command("build")
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\setuptools\_distutils\dist.py", line 972, in run_command
    cmd_obj.run()
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\nuitka\distutils\DistutilCommands.py", line 99, in run
    self._build(os.path.abspath(self.build_lib))
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\nuitka\distutils\DistutilCommands.py", line 335, in _build
    check_call(command, cwd=build_lib)
  File "C:\Users\danii\Desktop\nuitka_venv\Lib\site-packages\nuitka\utils\Execution.py", line 151, in check_call
    subprocess.check_call(*popenargs, **kwargs)
  File "C:\Program Files\Python312\Lib\subprocess.py", line 413, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\danii\\Desktop\\nuitka_venv\\Scripts\\python.exe', '-m', 'nuitka', '--module', '--enable-plugin=pylint-warnings', '--output-dir=C:\\Users\\danii\\Desktop\\nuitka_example\\build\\lib', '--nofollow-import-to=*.tests', '--remove-output', '--include-package=example_module', '--standalone', 'C:\\Users\\danii\\Desktop\\nuitka_example\\build\\lib\\example_module']' returned non-zero exit status 1.
```

**Comment by kayhayen** [comment] 2024-09-28 09:10
That's true, right now this is not supported. We want to add it, and as such this report is a duplicate of another issue that is asking for help with it I think. We might not get to have this unless somebody steps up and does the tooling changing necessary. I personally think, that for wheels the runners should become a multidist binary with launchers automatically unless forbidden, i.e. via specific configuration, it is insisted to have the Python code visible as packages too.

**Closed by kayhayen** 2024-09-28 09:10 UTC
