### ISSUE TITLE
importlib.resources.files do not work with Python 3.10 and standalone

### ISSUE THREAD

**Issue by grgi** [Nuitka/Nuitka#1451] opened 2022-03-01 21:48 UTC
* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python -m nuitka --version
```
0.8rc3
Commercial: None
Python: 3.10.2 (main, Jan 16 2022, 17:11:27) [GCC 11.2.0]
Flavor: Debian Python
Executable: /tmp/venv/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian (based on None) None
```

* How did you install Nuitka and Python

`git clone` of the `develop` branch and install via `pip` into an `venv`.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

Building the following `foo.py` via `python -m nuitka --standalone foo.py`
```
from importlib.resources import files
import nuitka

print(files('nuitka'))
```
Running `/tmp/foo.dist/foo` produces the following output:
```
<importlib._adapters.DegenerateFiles.Path object at 0x7f8005ff2980>
```
but I was expecting 
```
/tmp/foo.dist/nuitka
```
which it does if the same code is compiled with Python 3.9.

**Comment by kayhayen** [comment] 2022-03-11 08:45
This is a weakness, I have added an `ResourceReader` object with initially only `resource_path` and recently I added `open_resource` as well. Strangely the various Python versions, even from vendors, expose usage or not, for these functions in ways, that are hard to grasp. It seems that `files` will be easy to add, though, if it's only a `path` object. 

I am pretty sure, this might be 3.7 or 3.8 or higher issue, but it seems only recently did people pick it up and use it over the older methods.

**Comment by kayhayen** [comment] 2022-03-11 08:54
Also, can you help me with the Distribution output, something is really found there, but not a version, can you paste the contents of `/etc/os-release` and `lsb_release -i -s`, so I can enhance it? In your case it's irrelevant, but generally it often is .

**Comment by grgi** [comment] 2022-03-11 09:14
Sorry, here it `lsb_release -i -s` is just `Debian`. Here is the content of `/etc/os-release`:
```
PRETTY_NAME="Debian GNU/Linux bookworm/sid"
NAME="Debian GNU/Linux"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
Above errors occurred with the distribution own Python packages (Debian testing). However, I got the same error within a CentOS 7 docker container with self compiled Python 3.10.2 while the self-compiled Python 3.9.9 works flawlessly.

**Comment by kayhayen** [comment] 2022-03-11 11:11
Ah, yes `sid`, I didn't have any of that yet. I think, using `/sid` will allow me to detect that. The "based on" output, is another thing, looks silly for Debian proper. Thanks. The `files` will be added once I finally get tests with `open_resource` usage to pass. Once I have something to point you to, I would appreciate if you can see it saying "Sid" for version as well.

**Comment by kayhayen** [comment] 2022-05-15 08:15
The resource reader of Nuitka is now working, but I think for `files` it may not yet be good enough, we need to check it.

**Comment by grgi** [comment] 2022-05-16 07:07
No, `files` still do not work with the `factory` version. However, I'm using the backport package `importlib_resources` as a temporary workaround which seems to work.

**Comment by kayhayen** [comment] 2022-05-17 11:57
Right now I am not aware of anything using `files`. Today I looked into what it takes, and it seems easy enough. Are you using it only to iterate data files of a package, and then directory do `read_bytes` on it, or is this a more complex usage?

**Comment by grgi** [comment] 2022-05-17 16:51
Thanks! Yes, we only iterate the package's data files and most of the time we only need their absolute path.

**Comment by kayhayen** [comment] 2022-06-23 07:23
I have focuses on the `metadata.version` and friends to be properly compile time resolved first, this is in progress, and I hope to have it in 1.0, but it's not realistic as a hotfix to 0.9 release that I just made.

**Comment by kayhayen** [comment] 2022-09-04 17:28
This is working on develop right now and will be in 1.1 release, iteration methods may not be working fully yet though, but access, tests, etc. should be all fine.

**Comment by kayhayen** [comment] 2022-09-25 17:30
This is part of the stable release 1.1 that I just made.

**Comment by grgi** [comment] 2022-09-27 21:21
Unfortunately, it still does not work correctly: Running above example compiled with 1.1 now yields:
```
<nuitka_resource_reader_files for 'nuitka'>
```
rather than the full path which I would expect from a `str` conversion. Also, other `Path`like methods are not working for this instance.

**Comment by kayhayen** [comment] 2022-09-28 06:58
@grgi I see, but I need reproducers for things that are different, like I said, iteration methods are not yet supposed to work, please provide code of other stuff. The `str` stuff, I get, I will add it.

**Comment by kayhayen** [comment] 2022-09-28 07:41
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. I do however appreciate if examples of non-working stuff are given.

**Comment by kayhayen** [comment] 2022-10-02 09:25
This is part of the hotfix release 1.1.1 that I just made.

**Comment by kayhayen** [comment] 2022-10-02 09:25
Since no examples were given, please open a new issue if you come up with one.

**Closed by kayhayen** 2022-10-02 09:25 UTC
Labels: bug, factory, needs_example
