### ISSUE TITLE
Cannot compile psutil - "missing" DLL

### ISSUE THREAD

**Issue by SquarishRectangle** [Nuitka/Nuitka#2155] opened 2023-04-08 19:18 UTC
Version Info:
```
Python: 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\[redacted]\AppData\Local\Programs\Python\Python310\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\HostX64\x64\cl.exe (cl 14.3).
```
Nuitka version `1.5.5` installed via PIP

Issue with psutil version `5.9.4`

Nuitka is working with all other installed packages. Only psutil does not work. 

Code sample:
```
from os import getpid
from psutil import Process

#get pid of console
pid = getpid()
#get process of console
py = Process(pid)
print(py)
```
Attempted compile with command line options: `--standalone --prefer-source-code --output-filename=[exe name] --output-dir=[dir] [file].py`

Resulting error: `FATAL: Error, attempting to include file 'c:\progra~2\un-pse~1\api-ms-win-crt-math-l1-1-0.dll' (Used by 'psutil\_psutil_windows.pyd') that does not exist.`

Aside from the weird directory, the name of the DLL seems to be associated with Visual C++ 2015, which I have verified and reinstalled on my system. From a basic browsing of the psutil source code, _psutil_windows.c doesn't even seem to mention the DLL in question, much less one specifically in this weirdly named directory which leads me to believe it's an issue with Nuitka.

**Comment by SquarishRectangle** [comment] 2023-04-08 21:31
The issue does not exist on version `1.5.4`. Seems like something introduced in the latest release.

**Comment by kayhayen** [comment] 2023-04-09 08:07
There is something in your `PATH` that apparently contained Windows DLLs at some point, and it's picking it up. A bad thing to begin with, but probably mostly limited to you. I do not really know how to protect against that. Reducing `PATH` to the absolutely necessary would be good, but some software may actually require it to be as wide as the default.

We ignore DLLs from the system, and this is not ignored. The caching of DLL dependencies is broken by this "dependency" being removed. The versions of Nuitka use different cache keys, so it can remain reproducible, but a new version ought to be only better.

So, I think when we use a cache, we would have to check that the referenced files do exist, or else discard it. That would solve at least your symptom. Including those DLLs from other applications is not good. But I wonder if it's a mistake of dependency walker to not find them from the OS. At some point, we removed SxS from the scan, because they also got replaced in OS updates. However, we probably should still scan them, and just not include them.

Your 1.5.4 vs. 1.5.4 reporting I have to attribute to confusion and time of removal of that software. The path `'c:\progra~2\un-pse~1` is unintelligible. For reporting, we might want to get back to the long path.

**Comment by kayhayen** [comment] 2023-04-09 08:39
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Since this is a caching bug, and the version number change will be enough I am not sure testing from your side is needed, just use the option to clear that cache and all versions ought to work somewhat. The factory version however, would report the proper long path. I added code to revert short paths which have their benefits internally, to long paths for reporting, and I added it to the reporting and make use of that in the error you have encountered now.

As for the SxS bug, that one I want to have coverage for being sure, they are not included still.

```
commit 0a1345090208e2beae76f645777b3e89c3eb1b5b
Author: Kay Hayen <kay.hayen@gmail.com>
Date:   Sun Oct 9 18:18:41 2022 +0200

    Windows: Do not include DLLs from SxS
    
    * For PyPI packages these are generally unused, and self
      compiled won't be SxS. We can add it back where it turns out needed.
```

Reverting that commit should do, but I want to first have coverage of PyWin32 which I think triggered the inclusion of them, such that we are being sure that they do not come back, because they break on Windows updates. The fix I made now, would also avoid that, because not existing was the issue back then already too.

But with them being in the detection, your program directory would have lost. I am not 100% sure of that, though, because somehow SxS was *after* the scan directories. And it probably should be placed *before* that. Until that fix is in, you will produce a suboptimal distribution at least.

**Comment by kayhayen** [comment] 2023-04-09 16:15
So factory now also has a fix, such that the influence of PATH in this way should not be there anymore. It now scans the SxS first, and then the other scan directories, which will make it find it there, and then it ignores files from the SxS directories. That is a better fix for the commit mentioned.

**Comment by kayhayen** [comment] 2023-04-09 16:15
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-04-09 16:16
I am likely to put the caching improvement and the real fix in the next hotfix, but the UI improvement will be in 1.6 only, but I do not think it needs any tracing anyway.

**Comment by kayhayen** [comment] 2023-04-13 06:37
This is part of the hotfix release 1.5.6 that I just made.

**Closed by kayhayen** 2023-04-13 06:37 UTC
Labels: bug, factory
