### ISSUE TITLE
Deepcopy of compile methods leaks memory (was: Memory leak occurred while using matplotlib qt backend)

### ISSUE THREAD

**Issue by zzqq961** [Nuitka/Nuitka#3121] opened 2024-09-17 08:21 UTC
Nuitka       2.4.8
matplotlib 3.9.2
python      3.11.4
PyQt5        5.15.11
g++          13.1.0
=========================
Problem description：
Running as a Python .py will not result in memory leaks, but converting to an .exe file will result in leaks.

=========================
Nuitka command line：
nuitka --mingw64 --standalone --onefile --show-progress --show-memory --show-modules --plugin-enable=pyqt5 --follow-imports --output-dir=out matplot_test.py

=========================
Code：

import sys, psutil
import copy, random, gc
import matplotlib.pyplot as plt
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from PyQt5.QtCore import QRect, QTimer
from PyQt5.QtWidgets import QApplication, QMainWindow, QWidget, QVBoxLayout

class mytest(QMainWindow):

    def __init__(self, parent=None) -> None:
        super().__init__(parent)

        self._buffer = dict()                                   
        self._timer = QTimer()                                  
        self._timer.timeout.connect(self._timer_ticked)         
        
        self.setWindowTitle('4 test')
        self.resize(650, 300)

        self._sequence_fig = plt.figure()
        self._sequence_fig.patch.set_facecolor('#F0F0F0')
        self._sequence_cvs = FigureCanvas(self._sequence_fig)

        qw = QWidget(self)
        qw.setGeometry(QRect(5, 5, 640, 290))
        qw.setStyleSheet('QWidget {border: 1px solid gray; border-radius: 3px}')
        ly = QVBoxLayout(qw)
        ly.addWidget(self._sequence_cvs)
        qw.setLayout(ly)

        self._buffer['a'] = []
        self._buffer['b'] = []

        self._p = psutil.Process()

        self._timer.start(200)

    def _timer_ticked(self) -> None:
        self._buffer['a'].append(random.random() * 10.0 + 7)
        self._buffer['b'].append(random.random() * 10.0 + 5)
        ax = self._sequence_fig.add_axes([0.06, 0.08, 0.937, 0.92])
        ax.set_facecolor('#FCFCEC')
        ax.plot(self._buffer['a'][-600:], linestyle ='solid', color='#306640', linewidth=1)
        ax.plot(self._buffer['b'][-600:], linestyle ='solid', color='#36729C', linewidth=1)
        self._sequence_cvs.draw()
        self._sequence_cvs.flush_events()
        self._sequence_fig.clear()
        plt.close('all')

        if len(self._buffer['a']) > 620:
            print(self._p.memory_full_info().uss)
            for k in self._buffer:
                a = self._buffer[k][-600:]
                self._buffer[k].clear()
                self._buffer[k] = copy.copy(a)
                a.clear()
            gc.collect()

win = QApplication(sys.argv)
cam = mytest()
cam.show()
sys.exit(win.exec_())

**Comment by jiangbaihe** [comment] 2024-09-27 15:59
![b5dfe4da2f332f4e954706ac955e8e13](https://github.com/user-attachments/assets/c33e255d-bb81-4818-bf36-4cff63017f4e)

是个棘手的问题，折腾了好几天，各种排查，什么法子都试过，搞不定。
It’s a tricky problem. I’ve been struggling with it for several days, trying various troubleshooting methods without success.

最后是用一些不太规范的方式来解决；
In the end, I had to use some unconventional approaches to resolve it.

虽然不太规范，也存在一些限制，不过至少问题解决了。
Although they aren't very standard and come with some limitations, at least the problem is fixed.

这里我已经运行快一天了，没有再泄漏
I’ve been running it for almost a day now without any leaks.

**Comment by zzqq961** [comment] 2024-10-08 11:35
Switching to PyQt6, the situation remains the same.
&nbsp;


Leo&nbsp;Wannta!
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Kay ***@***.***&gt;; 
发送时间: 2024年10月7日(星期一) 晚上11:24
收件人: ***@***.***&gt;; 
抄送: "Leo ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Nuitka/Nuitka] memory leak occurred while using matplotlib (Issue #3121)














 
I don't trust PyQt5 enough to not think it doesn't memory leak (with Nuitka), can you demonstrate it with pure matplotlib as well?

**Comment by kayhayen** [comment] 2024-10-09 11:22
I really like your terminal background, good choice.

**Comment by zzqq961** [comment] 2024-10-09 11:24
A group of very outstanding scientists

**Comment by kayhayen** [comment] 2024-10-09 11:53
So, I reproduce a tiny increase in memory. I guess, we need to isolate now if it's matplotlib, or PyQt6, or even an operation like this that could be doing it. `self._buffer['a'][-600:]`, so far it's not specific.

**Comment by kayhayen** [comment] 2024-10-09 12:01
I have isolated the matplotlib part, the memory usage with Python is pretty unstable for 100 runs. I did see however, in the Qt example, that it was steadily, slowly, increasing indeed, so there might be something, but it seems harder to isolate, probably need to put larger numbers for the figure to see if anything happens there.

**Comment by zzqq961** [comment] 2024-10-09 13:44
Thanks, I'll try in the next few days.

**Comment by kayhayen** [comment] 2024-10-11 08:47
It seems the matplotlib backend calls to draw and clear are losing the memory. This is using PyQt6 and in terms of Python, also the `super()` without arguments, which if it lost a reference, could be harmful in terms of memory. I think I can exclude `super`, we have coverage for that, commenting out these calls makes it loose no memory:

```
#    _sequence_cvs.draw()
#    _sequence_cvs.flush_events()
```

**Comment by kayhayen** [comment] 2024-10-11 08:48
I switched to PySide6, without it changing anything in terms of memory growth, so there is definitely a bug. I have used in the past an approach where we can list the leaked things, and I guess, looking at frames, etc. counts, might make sense here as a first step, but PyQt6 is out of the blame zone.

**Comment by kayhayen** [comment] 2024-10-11 08:59
This is the current reproducer, need of course to ideally shrink it more.

```
import matplotlib.pyplot as plt
import random
from matplotlib.backends.backend_qtagg import FigureCanvasQTAgg as FigureCanvas
import gc
import psutil
_buffer = dict()
_buffer['a'] = []
_buffer['b'] = []

_sequence_fig = plt.figure()
_sequence_fig.patch.set_facecolor('#F0F0F0')
_sequence_cvs = FigureCanvas(_sequence_fig)

_p = psutil.Process()

def f():

    ax = _sequence_fig.add_axes([0.06, 0.08, 0.937, 0.92])
    ax.set_facecolor('#FCFCEC')
    ax.plot(_buffer['a'], linestyle ='solid', color='#306640', linewidth=1)
    ax.plot(_buffer['b'], linestyle ='solid', color='#36729C', linewidth=1)
    _sequence_cvs.draw()
    _sequence_cvs.flush_events()
    _sequence_fig.clear()
    plt.close('all')

    gc.collect()
    return _p.memory_full_info().uss

start = f()

for x in range(600):
    _buffer['a'].append(random.random() * 10.0 + 7)
    _buffer['b'].append(random.random() * 10.0 + 5)

for x in range(100):
    end = f()

    if x % 10 == 0:
        print(end - start)
```

With using `--experimental=report-refcounts` we can see if there are frames, generators, etc. leaking at program end. Hopefully that will reveal something to start looking into what owns it. I might have to also return to covering `super` better.

This is our current coverage, the exception handling is for Python versions, that didn't yet allow super without arguments.

```
class X:
    def __del__(self):
        # Super used to reference leak.
        x = super()

        raise ValueError(1)


def simpleFunction63():
    def superUser():
        X()

    try:
        superUser()
    except Exception:
        pass
```

Not sure if that not loosing references covers more complex method calls. The super object itself, we create it, and may well do that wrong, but it seems properly deleted from this test case.

**Comment by kayhayen** [comment] 2024-10-11 09:04
Using the arguments `--stand --enable-plugin=pyside6 --experimental=report-refcounts` makes it pick PySide6 at runtime, and report something like this with 100 runs:

```
REFERENCE counts at program end:
active | allocated | released
Compiled Functions: 8449 | 87974 | 79525 (module/class ownership may occur)
Compiled Generators: 0 | 78429 | 78429
Compiled Coroutines: 0 | 0 | 0
Compiled Coroutines Wrappers: 0 | 0 | 0
Compiled Coroutines AIter Wrappers: 0 | 0 | 0
Compiled Asyncgen: 0 | 0 | 0
Compiled Asyncgen Wrappers: 0 | 0 | 0
Compiled Asyncgen Asend: 0 | 0 | 0
Compiled Asyncgen Athrow: 0 | 0 | 0
Compiled Frames: 2277 | 76021 | 73744 (cache usage may occur)
Compiled Cells: 2096 | 167612 | 165516 (function ownership may occur)
CACHED counts at program end:
active | allocated | released | hits
Cached Frames: 1327 | 75071 | 73744 | 4617385
```

Compiled functions remaining alive is not a big thing, but compiled frames seem to leak, so it would probably only be a matter of finding out, what kinds of frames remain active at program exit. The 2277 frames still alive seem to be only in part due to caching, there is still 1327 frames, that are not that. I am running now with 200, and I expect to see doubling of the leaked frames maybe.

**Comment by kayhayen** [comment] 2024-10-11 09:06
So this is the 200 result:

```
REFERENCE counts at program end:
active | allocated | released
Compiled Functions: 8449 | 165974 | 157525 (module/class ownership may occur)
Compiled Generators: 0 | 150329 | 150329
Compiled Coroutines: 0 | 0 | 0
Compiled Coroutines Wrappers: 0 | 0 | 0
Compiled Coroutines AIter Wrappers: 0 | 0 | 0
Compiled Asyncgen: 0 | 0 | 0
Compiled Asyncgen Wrappers: 0 | 0 | 0
Compiled Asyncgen Asend: 0 | 0 | 0
Compiled Asyncgen Athrow: 0 | 0 | 0
Compiled Frames: 2277 | 147821 | 145544 (cache usage may occur)
Compiled Cells: 2096 | 323312 | 321216 (function ownership may occur)
CACHED counts at program end:
active | allocated | released | hits
Cached Frames: 1327 | 146871 | 145544 | 9146585
```

So, it seems, we are not finding a leak that way, it's none of the typical offenders.

**Comment by kayhayen** [comment] 2024-10-11 10:42
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by zzqq961** [comment] 2024-10-12 03:49
What a surprise! I am attending a meeting and will give it a try as soon as back.

**Comment by kayhayen** [comment] 2024-10-24 18:25
Part of the 2.4.9 hotfix I made a while ago.

**Closed by kayhayen** 2024-10-24 18:25 UTC
Labels: bug
