### ISSUE TITLE
Nuitka and SKImage/SKlearn — how it should work?

### ISSUE THREAD

**Issue by belonesox** [Nuitka/Nuitka#770] opened 2020-06-28 13:57 UTC
Let's consider minimal «science image processing application»

```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import skimage.feature
import numpy as np
import scipy as sp
print(dir(skimage.feature))
```

A numpy-scipy application we should build it with ``--enable-plugin=numpy --include-scipy`` like
```
python3 -m nuitka --standalone --follow-imports --show-progress --show-modules --show-scons --enable-plugin=numpy --include-scipy --explain-imports wtf.py > build.log 2>&1
```

but executable failed with 
```
ModuleNotFoundError: No module named 'skimage'    
```

I see the problem in ``NumpyPlugin.py`` that tell to nuitka importing 
system to ignore ``skimage`` imports (and did nothing to handle it)

https://github.com/Nuitka/Nuitka/blob/0.6.8.4/nuitka/plugins/standard/NumpyPlugin.py#L316

Similar problem looks with ``sklearn`` see
https://github.com/Nuitka/Nuitka/issues/767

So I solve my problem to dirty fix of ``NumpyPlugin.py``
(obvious fix all lines with skimage/sklearn)
but not sure that is it the right way to fix the bug.

**Comment by kayhayen** [comment] 2020-06-30 08:30
I think hinted compilation kind of meant to have sklearn as a separate supported thing, but never completed it yet. I guess, allowing to include it should be an argument, that defaults to true, and that is just not present yet. I am going to fix that.

**Comment by kayhayen** [comment] 2020-06-30 08:36
The code you point to, looks already correct though. It seems `--include-scipy `measns sklearn is allowed to be included, so this is strange.

**Comment by kayhayen** [comment] 2020-06-30 09:10
Duplicate of #767 lets track it there.

**Closed by kayhayen** 2020-06-30 09:10 UTC
Labels: bug, duplicate
