### ISSUE TITLE
OSError: Can't get source for <compiled_function upcast_masked_softmax at 0x0000023F260966B0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

### ISSUE THREAD

**Issue by ArEnSc** [Nuitka/Nuitka#2570] opened 2023-11-23 20:57 UTC
1.9
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\Tensor\Desktop\awqprototype\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\bin\Hostx64\x64\cl.exe (cl 14.3).
```

from awq import AutoAWQForCausalLM
from transformers import AutoTokenizer, TextStreamer
# use instead pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117 
def main():

    quant_path = r"C:\Users\Tensor\Desktop\awqprototype\dolphin-2.1-mistral-7B-AWQ"
    quant_file = r"model.safetensors"

    # Load model
    model = AutoAWQForCausalLM.from_quantized(quant_path, quant_file, fuse_layers=True)
    tokenizer = AutoTokenizer.from_pretrained(quant_path, trust_remote_code=True)
    streamer = TextStreamer(tokenizer, skip_special_tokens=True)

    # Convert prompt to tokens
    prompt_template = """\
    A chat between a curious user and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the user's questions.

    USER: {prompt}
    ASSISTANT:"""

    tokens = tokenizer(
        prompt_template.format(prompt="How are you today?"), 
        return_tensors='pt'
    ).input_ids.cuda()

    # Generate output
    generation_output = model.generate(
        tokens, 
        streamer=streamer,
        max_new_tokens=512
    )
main()
```

- Provide in your issue the Nuitka options used
```
python -m nuitka --standalone --include-distribution-metadata=jinja2 --include-distribution-metadata=psutil --include-distribution-metadata=torchaudio --include-distribution-metadata=pandas --include-distribution-metadata=torchvision --include-distribution-metadata=torch --include-distribution-metadata=pandas --include-distribution-metadata=openai --report=awq.txt --plugin-enable=anti-bloat --noinclude-unittest-mode=allow --include-distribution-metadata=scipy .\main.py
[awq.txt](https://github.com/Nuitka/Nuitka/files/13453393/awq.txt)
```
  

Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\_sources.py", line 23, in get_source_lines_and_file
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\inspect.py", line 1129, in getsourcelines
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\inspect.py", line 958, in findsource
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\awq\__init__.py", line 2, in <module awq>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\awq\models\__init__.py", line 7, in <module awq.models>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\awq\models\gpt_bigcode.py", line 2, in <module awq.models.gpt_bigcode>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\transformers\models\gpt_bigcode\modeling_gpt_bigcode.py", line 55, in <module transformers.models.gpt_bi  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\jit\_script.py", line 1338, in script
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\jit\frontend.py", line 262, in get_jit_def
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\_sources.py", line 120, in parse_def
  File "C:\Users\Tensor\Desktop\AWQPRO~1\MAIN~1.DIS\torch\_sources.py", line 32, in get_source_lines_and_file
OSError: Can't get source for <compiled_function upcast_masked_softmax at 0x0000023F260966B0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

**Comment by kayhayen** [comment] 2023-11-24 08:54
Generating models in compiled form may not be possible, I think you generate them without Nuitka and deploy the result, don#T you.

**Comment by ArEnSc** [comment] 2023-11-24 18:37
Wierd part about this is we don't do that I am wondering what lines would cause this. Unless the model loader is doing that hmmm

**Comment by ArEnSc** [comment] 2023-11-24 19:30
ok it turns out we might need to ignore any model that has ...
@torch.jit.script on it, since I would guess that nuitka just run the whole hugging face module ? otherwise this makes no sense since, the model we use wouldn't use that big code architecture at all.

**Comment by ArEnSc** [comment] 2023-11-24 20:04
Is there a way to ignore specific folder pathes ? I am thinking about ignoring a lot of the models that exist since for some reason they are included in the compilation and have no impact on the code base if it makes sense

**Comment by kayhayen** [comment] 2023-11-26 11:12
Deleting is most effective and allows you to verify it. Otherwise, yes, there are options for Nuitka that allow to not include modules.

**Comment by kayhayen** [comment] 2023-11-27 09:46
I am not sure about the need to disable the decorator, I recall there is an environment variable that can do it too, and Nuitka used to set it, but it was found too aggressive.

**Comment by kayhayen** [comment] 2023-11-27 09:47
If you are available to do a PR, this can be fixed by adding to the yaml configuration, described here: [https://nuitka.net/doc/nuitka-package-config.html](https://nuitka.net/doc/nuitka-package-config.html)

And here is more of a walk through style post: [https://nuitka.net/posts/nuitka-package-config-kickoff.html](https://nuitka.net/posts/nuitka-package-config-kickoff.html)

Here are a example PRs for other packages:

[#2030](https://github.com/Nuitka/Nuitka/pull/2030) 
[#1993](https://github.com/Nuitka/Nuitka/pull/1993)

**Comment by doradsoft** [comment] 2023-12-02 19:17
So apparently this issue affects us as well, and I'm not sure how to deal with it.
I can share the full reproduce if needed, but it might not be needed as it sounds like a known issue.
One dependent source file contains a function which is decorated with `@torch.jit.script` and therefore the same runtime error that was mentioned in this issue is thrown.
Would appreciate your guidance / fix @kayhayen.

**Comment by kayhayen** [comment] 2023-12-03 09:05
@doradsoft your priority package kicks in here. 

If you have another reproducer, be sure to share it with me. I think this is actually simple stuff. I need to know the module name only, for `timm` we do it like this:

```
- module-name: 'timm'
  implicit-imports:
    - pre-import-code:
        - |
          import os
          if os.environ.get('PYTORCH_JIT') is not None:
            os.environ['PYTORCH_JIT_OLD'] = os.environ.get('PYTORCH_JIT')
          os.environ['PYTORCH_JIT'] = "0"
      when: 'standalone'
    - post-import-code:
        - |
          import os
          if os.environ.get('PYTORCH_JIT_OLD') is None:
            del os.environ['PYTORCH_JIT']
          else:
            os.environ['PYTORCH_JIT'] = os.environ['PYTORCH_JIT_OLD']
            del os.environ['PYTORCH_JIT_OLD']
      when: 'standalone'
```

That allows to load `timm` without the functions becoming JITed on the target machine (only Nuitka compilation), and then work well for people. The module name is of course key there. You could even try it yourself, but I will gladly do it for you.

**Comment by kayhayen** [comment] 2023-12-03 09:11
Seems I made a mistake there @ArEnSc not giving this immediate priority, since you also have that. Anyway, I do not know what `awq` is, can you provide the associated pip freeze for it?

**Comment by kayhayen** [comment] 2023-12-04 11:38
I will need a proper example to make progress here, which of course I would love to have for the next hotfix already.

**Comment by ArEnSc** [comment] 2023-12-04 14:50
@kayhayen 
https://github.com/casper-hansen/AutoAWQ

```
absl-py==0.13.0
aiohttp==3.7.4.post0
alembic==1.9.2
altgraph==0.17
anyio==3.7.0
appdirs==1.4.4
asttokens==2.0.5
astunparse==1.6.3
async-timeout==3.0.1
attrs==21.2.0
audioread==2.1.9
autopep8==1.5.7
azure-ai-formrecognizer==3.2.0
azure-common==1.1.28
azure-core==1.26.2
backcall==0.2.0
backoff==1.11.1
backports.zoneinfo==0.2.1
beartype==0.15.0
beautifulsoup4==4.10.0
boto3==1.17.78
botocore==1.20.78
cachetools==4.2.0
certifi==2020.12.5
cffi==1.14.6
chardet==4.0.0
charset-normalizer==3.0.1
chromadb==0.3.25
click==8.0.1
clickhouse-connect==0.5.25
cloudpickle==2.2.1
colorama==0.4.4
coloredlogs==15.0.1
contourpy==1.0.7
cycler==0.11.0
databricks-cli==0.17.4
debugpy==1.6.0
decorator==5.0.9
deepspeech==0.9.3
dill==0.3.6
distlib==0.3.1
docker==6.0.1
docopt==0.6.2
duckdb==0.8.0
elasticsearch==7.17.8
entrypoints==0.4
exceptiongroup==1.1.1
executing==0.8.3
farm-haystack==1.12.2
fastapi==0.95.2
fastapi-utils==0.2.1
filelock==3.0.12
Flask==2.2.2
flatbuffers==2.0
fonttools==4.38.0
future==0.18.2
gast==0.4.0
gitdb==4.0.10
GitPython==3.1.30
google-api-core==1.25.0
google-auth==1.24.0
google-auth-oauthlib==0.4.4
google-cloud-speech==2.0.1
google-pasta==0.2.0
googleapis-common-protos==1.52.0
greenlet==2.0.1
grpcio==1.34.1
h11==0.12.0
h2==4.0.0
h5py==3.1.0
hnswlib==0.7.0
hpack==4.0.0
httptools==0.5.0
huggingface-hub==0.11.1
humanfriendly==10.0
Hypercorn==0.11.1
hyperframe==6.0.0
idna==2.10
importlib-metadata==5.2.0
importlib-resources==5.10.2
inflect==5.6.0
install==1.3.4
interegular==0.3.2
ipykernel==6.13.0
ipython==8.2.0
isodate==0.6.1
itsdangerous==2.1.2
jarowinkler==1.2.3
jedi==0.18.1
Jinja2==3.1.2
jmespath==0.10.0
joblib==1.2.0
Js2Py==0.71
jsonschema==4.17.3
jupyter-client==7.2.2
jupyter-core==4.10.0
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
keyboard==0.13.5
kiwisolver==1.4.4
langdetect==1.0.9
lark==1.1.7
libcst==0.3.16
librosa==0.8.1
llvmlite==0.36.0
log-symbols==0.0.14
loguru==0.5.3
lxml==4.9.2
lz4==4.3.2
Mako==1.1.3
Markdown==3.3.3
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.3
mlflow==2.1.1
mmh3==3.0.0
monotonic==1.6
more-itertools==9.0.0
mpmath==1.3.0
msrest==0.7.1
multidict==5.1.0
mypy-extensions==0.4.3
nanopq==0.1.10
nest-asyncio==1.5.5
networkx==3.0
nltk==3.8.1
Nuitka==1.9
num2words==0.5.12
numba==0.53.1
numpy==1.22.4
oauthlib==3.1.1
onnxruntime==1.15.0
onnxruntime-gpu==1.11.1
opt-einsum==3.3.0
ordered-set==4.1.0
overrides==7.3.1
packaging==21.0
pandas==1.5.3
parso==0.8.3
pdoc3==0.9.2
pedalboard==0.3.8
pefile==2021.5.24
pickleshare==0.7.5
Pillow==9.2.0
pipwin==0.5.1
pkgutil_resolve_name==1.3.10
pooch==1.4.0
posthog==3.0.1
priority==1.3.0
prompt-toolkit==3.0.29
proto-plus==1.13.0
protobuf==4.21.1
psutil==5.9.0
pure-eval==0.2.2
pyarrow==10.0.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAudio @ file:///C:/Users/Tensor/pipwin/PyAudio-0.2.11-cp38-cp38-win_amd64.whl
pybind11==2.9.2
pycodestyle==2.7.0
pycparser==2.20
pydantic==1.9.1
pydub==0.25.1
Pygments==2.11.2
pyinstaller==4.4
pyinstaller-hooks-contrib==2021.1
pyjsparser==2.7.1
PyJWT==2.6.0
pyparsing==2.4.7
PyPrind==2.11.3
pyreadline3==3.4.1
pyrsistent==0.19.3
PySide2==5.15.2.1
pySmartDL==1.3.4
python-dateutil==2.8.2
python-docx==0.8.11
python-dotenv==1.0.0
pytz==2020.5
pytz-deprecation-shim==0.1.0.post0
pywin32==305
pywin32-ctypes==0.2.0
PyYAML==5.4.1
pyzmq==22.3.0
QtPy==2.3.0
quantulum3==0.8.1
querystring-parser==1.2.4
rank-bm25==0.2.2
rapidfuzz==2.7.0
regex==2022.10.31
requests==2.28.2
requests-oauthlib==1.3.0
resampy==0.2.2
rii==0.2.8
rsa==4.7
Rx==3.2.0
ryven==3.1.1
ryvencore==0.3.1.2
ryvencore-qt==0.3.1.4
s3transfer==0.4.2
sacremoses==0.0.45
scikit-learn==1.2.1
scipy==1.8.1
sentence-transformers==2.2.2
sentencepiece==0.1.97
seqeval==1.2.2
shap==0.41.0
shiboken2==5.15.2.1
six==1.15.0
slicer==0.0.7
smmap==5.0.0
sniffio==1.3.0
SoundFile==0.10.3.post1
soupsieve==2.3.1
spinners==0.0.24
SQLAlchemy==1.4.46
sqlparse==0.4.3
stack-data==0.2.0
starlette==0.27.0
sympy==1.12
tabulate==0.9.0
tenacity==8.2.3
tensorboard==2.5.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow==2.5.0
tensorflow-estimator==2.5.0
tensorflow-gpu==2.5.0
tensorflow-hub==0.12.0
tensorflow-text==2.5.0
termcolor==1.1.0
textdistance==4.5.0
threadpoolctl==2.2.0
tika==2.6.0
tinyaes==1.0.1
tinydb==4.7.0
tokenizers==0.13.2
toml==0.10.2
torch==1.13.1
torchaudio==0.13.1+cu117
torchvision==0.14.1
tornado==6.1
tqdm==4.65.0
traitlets==5.1.1
transformers==4.25.1
twitchAPI==2.3.2
typing-inspect==0.6.0
typing_extensions==4.6.2
tzdata==2021.5
tzlocal==4.1
urllib3==1.26.2
uvicorn==0.22.0
virtualenv==20.4.6
waiting==1.4.1
waitress==2.1.2
watchfiles==0.19.0
watchgod==0.6
wcwidth==0.2.5
webrtcvad==2.0.10
websocket-client==1.1.0
websockets==11.0.3
Werkzeug==2.2.2
win32-setctime==1.0.3
wrapt==1.12.1
wsproto==1.0.0
yarl==1.6.3
zipp==3.11.0
zstandard==0.21.0
```

**Comment by kayhayen** [comment] 2023-12-04 21:00
> AutoAWQ has been merged into 🤗 transformers. Now includes CUDA 12.1 wheels.

So I guess, this is obsolete software now?

**Comment by ArEnSc** [comment] 2023-12-05 00:10
> AutoAWQ

I am not sure exactly, how that works ... I think it's probably a package that installed and uses transformers probably, I think this had to be miscommunicated. Ill double check and ask

**Comment by ArEnSc** [comment] 2023-12-06 00:15
The wording may be a little confusing. I meant that it is integrated into the core of transformers. Transformers rely on AutoAWQ for inference only. It is not going to be archived as a result of this. @kayhayen looks like it's still on! =D

**Comment by doradsoft** [comment] 2023-12-12 15:52
> If you have another reproducer, be sure to share it with me.

```python
from transformers.models.gpt_bigcode.modeling_gpt_bigcode import GPTBigCodeForCausalLM
print(GPTBigCodeForCausalLM.__name__)
```

`python -m nuitka --version`
> 2.0rc4
> Commercial: 2.3.2
> Python: 3.11.6 (main, Oct 19 2023, 12:55:47) [GCC 5.4.0 20160609]
> Flavor: pyenv
> Executable: /root/.pyenv/versions/3.11.6/bin/python
> OS: Linux
> Arch: x86_64
> Distribution: Ubuntu (based on Debian) 16.04.7
> Version C compiler: /usr/lib/ccache/gcc (gcc 5.4.0).

`python -m pip freeze`

> accelerate==0.20.3
> aiohttp==3.8.5
> aiosignal==1.3.1
> async-timeout==4.0.3
> attrs==23.1.0
> backoff==2.2.1
> bitsandbytes==0.41.1
> certifi==2023.7.22
> charset-normalizer==3.2.0
> click==8.1.7
> cmake==3.27.9
> datasets==2.14.5
> Deprecated==1.2.14
> dill==0.3.7
> einops==0.6.1
> filelock==3.12.4
> frozenlist==1.4.0
> fsspec==2023.6.0
> googleapis-common-protos==1.60.0
> grpc-interceptor==0.15.3
> grpcio==1.58.0
> grpcio-reflection==1.58.0
> grpcio-status==1.58.0
> hf_transfer==0.1.3
> huggingface-hub==0.16.4
> idna==3.4
> importlib-metadata==6.11.0
> Jinja2==3.1.2
> lit==17.0.6
> loguru==0.6.0
> MarkupSafe==2.1.3
> mpmath==1.3.0
> multidict==6.0.4
> multiprocess==0.70.15
> networkx==3.1
> Nuitka @ file:///python-packages/Nuitka-commercial-staging.zip#sha256=896ed24303ae5961d08666d14965abb9e
> ca0b3ed2ed54dd36ccff0ac01ca9276
> numpy==1.26.0
> nvidia-cublas-cu11==11.10.3.66
> nvidia-cuda-cupti-cu11==11.7.101
> nvidia-cuda-nvrtc-cu11==11.7.99
> nvidia-cuda-runtime-cu11==11.7.99
> nvidia-cudnn-cu11==8.5.0.96
> nvidia-cufft-cu11==10.9.0.58
> nvidia-curand-cu11==10.2.10.91
> nvidia-cusolver-cu11==11.4.0.1
> nvidia-cusparse-cu11==11.7.4.91
> nvidia-nccl-cu11==2.14.3
> nvidia-nvtx-cu11==11.7.91
> opentelemetry-api==1.21.0
> opentelemetry-exporter-otlp==1.21.0
> opentelemetry-exporter-otlp-proto-common==1.21.0
> opentelemetry-exporter-otlp-proto-grpc==1.21.0
> opentelemetry-exporter-otlp-proto-http==1.21.0
> opentelemetry-instrumentation==0.42b0
> opentelemetry-instrumentation-grpc==0.42b0
> opentelemetry-proto==1.21.0
> opentelemetry-sdk==1.21.0
> opentelemetry-semantic-conventions==0.42b0
> ordered-set==4.1.0
> packaging==23.1
> pandas==2.1.1
> peft==0.4.0
> Pillow==10.0.1
> protobuf==4.24.3
> psutil==5.9.5
> pyarrow==13.0.0
> python-dateutil==2.8.2
> pytz==2023.3.post1
> PyYAML==6.0.1
> regex==2023.8.8
> requests==2.31.0
> safetensors==0.3.3
> scipy==1.11.2
> sentencepiece==0.1.99
> six==1.16.0
> sympy==1.12
> texttable==1.6.7
> tokenizers==0.13.3
> torch==2.0.1
> tqdm==4.66.1
> transformers==4.33.2
> triton==2.0.0
> typer==0.6.1
> typing_extensions==4.8.0
> tzdata==2023.3
> urllib3==2.0.5
> wrapt==1.15.0
> xxhash==3.3.0
> yarl==1.9.2
> zipp==3.17.0
> zstandard==0.22.0

[compilation_report.zip](https://github.com/Nuitka/Nuitka/files/13650225/compilation_report.zip)

**Comment by kayhayen** [comment] 2023-12-16 13:44
@doradsoft I am having success like this: 

> PYTORCH_JIT=0 ./MiniTransformers4.dist/MiniTransformers4.bin 
> GPTBigCodeForCausalLM

Now for Nuitka, there are users that want `torch.jit.trace` to work, while the torch script cannot work without the source code. I need to do more research, but as a workaround, if that's the first thing you do in your program, you will not have that issue.

**Comment by kayhayen** [comment] 2023-12-16 13:44
> import os; os.environ["PYTORCH_JIT"] = "0"

**Comment by doradsoft** [comment] 2023-12-16 20:53
I confirm that for us it's sufficient

**Comment by kayhayen** [comment] 2023-12-17 13:21
@ArEnSc how about you?

I am contemplating what to do now. In the past, Nuitka has globally forced this, but there was a complaint about that breaking valid uses of `torch.jit.trace`, so I guess we need to make it an option of Nuitka for a revived torch plugin, or maybe options for yaml configuration, so once torch is used, it asks for a decision via a generic option style, since having a plugin just for being allowed to do that seems overkill. Alternatively `--force-environment-variable=value` could be checked by `options` in Yaml for presence, and be warned about if not not given.

We will need that until we can actually include the source code in a good way for functions decorated like that. But on target machine JIT seems rough for many setups.

**Comment by ArEnSc** [comment] 2023-12-18 16:23
> @ArEnSc how about you?
> 
> I am contemplating what to do now. In the past, Nuitka has globally forced this, but there was a complaint about that breaking valid uses of `torch.jit.trace`, so I guess we need to make it an option of Nuitka for a revived torch plugin, or maybe options for yaml configuration, so once torch is used, it asks for a decision via a generic option style, since having a plugin just for being allowed to do that seems overkill. Alternatively `--force-environment-variable=value` could be checked by `options` in Yaml for presence, and be warned about if not not given.
> 
> We will need that until we can actually include the source code in a good way for functions decorated like that. But on target machine JIT seems rough for many setups.

absolutely fine with the two options, yaml config works, thanks for your hard work on this!

**Comment by kayhayen** [comment] 2023-12-19 09:20
I mean, does the environment variable make your case work @ArEnSc

**Comment by doradsoft** [comment] 2023-12-20 07:19
@ArEnSc I think Kay meant that you should check with:
```sh
set PYTORCH_JIT=0
./main.exe
```

**Comment by kayhayen** [comment] 2023-12-20 10:31
Yes, it's not actually a change, although factory might have things that you need for this to fully work. The suggestion is to make this into your code now, and for me then once confirmed to find a way to automate this without breaking it for those people do not want that to happen.

**Comment by kayhayen** [comment] 2024-01-12 13:36
Nuitka 2.0 will allow to disable the JIT with a compile time decision. For standalone it suggests to do it, and defaults to false, making this work out of the box.

Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2024-01-22 09:15
It's also on staging of course as a side note for the commercial users.

**Comment by kayhayen** [comment] 2024-01-26 13:26
This is part of the stable release 2.0 that I just made.

**Closed by kayhayen** 2024-01-26 13:26 UTC
Labels: bug, develop
