### ISSUE TITLE
How to solve the find_dotenv AssertionError that occurs when opening an exe after importing selenium.

### ISSUE THREAD

**Issue by c469591** [Nuitka/Nuitka#2761] opened 2024-03-13 01:17 UTC
Hello, I was successful in using nuitka to package it into an exe, but there was an error when starting the exe.
Here is my environment
Python installed using python-3.11.0-amd64.exe
Nuitka installed using this command
pip install nuitka
pip install -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"
Operating System: Win10

Below is the simplified code from my project.

```
import requests
from webdriver_manager.chrome import ChromeDriverManager
from webdriver_manager.microsoft import EdgeChromiumDriverManager
from selenium import webdriver
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
import selenium.common.exceptions
import json

def login():
    print("Please choose a login method:")
    print("1. Log in through the browser and automatically extract cookies")
    choice = input()
    if choice == "1":
        print("Please select a browser:")
        print("1. Google Chrome")
        print("2. Microsoft Edge")
        choice = input()
        if choice == "1":
            option = webdriver.ChromeOptions()
            option.add_experimental_option("detach", True)
            option.add_experimental_option('excludeSwitches', ['enable-logging'])
            driver = webdriver.Chrome(ChromeDriverManager().install(), options=option)
        elif choice == "2":
            option = webdriver.EdgeOptions()
            option.add_experimental_option("detach", True)
            option.add_experimental_option('excludeSwitches', ['enable-logging'])
            driver = webdriver.Edge(EdgeChromiumDriverManager().install(), options=option)
        else:
            return
        print("Please log in to Ximalaya in the pop-up browser; the browser will automatically close upon successful login.")
        driver.get("https://passport.ximalaya.com/page/web/login")
        try:
            WebDriverWait(driver, 300).until(EC.url_to_be("https://www.ximalaya.com/"))
            cookies = driver.get_cookies()
            driver.quit()
        except selenium.common.exceptions.TimeoutException:
            print("Login timed out, automatically returning to the main menu!")
            driver.quit()
            return
        cookie = ""
        for cookie_ in cookies:
            cookie += f"{cookie_['name']}={cookie_['value']}; "
        with open("config.json", "r", encoding="utf-8") as f:
            config = json.load(f)
        config["cookie"] = cookie
        with open("config.json", "w", encoding="utf-8") as f:
            json.dump(config, f)
    else:
        print("Invalid choice, please restart the process.")
        return

if __name__ == '__main__':
    login()

```

The CLI command I used is:

nuitka --standalone --show-memory --show-progress --follow-import-to=need --output-dir=o --nofollow-imports --include-data-file=selenium-manager.exe=selenium-manager.exe test.py

When launching the exe, the following error occurs

```
Traceback (most recent call last):
  File "D:\CODE_T~1\o\TEST~1.DIS\test.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\CODE_T~1\o\TEST~1.DIS\webdriver_manager\chrome.py", line 4, in <module webdriver_manager.chrome>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\CODE_T~1\o\TEST~1.DIS\webdriver_manager\core\download_manager.py", line 5, in <module webdriver_manager.core.download_manager>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\CODE_T~1\o\TEST~1.DIS\webdriver_manager\core\http.py", line 4, in <module webdriver_manager.core.http>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "D:\CODE_T~1\o\TEST~1.DIS\webdriver_manager\core\config.py", line 9, in <module webdriver_manager.core.config>
  File "D:\CODE_T~1\o\TEST~1.DIS\dotenv\main.py", line 346, in load_dotenv
  File "D:\CODE_T~1\o\TEST~1.DIS\dotenv\main.py", line 305, in find_dotenv
AssertionError
```

I noticed that inside the Selenium folder, there is a
selenium-manager.exe
Perhaps it's because it automatically generates a .env file, but I don't know how to resolve the above errors.
thank

**Comment by kayhayen** [comment] 2024-03-13 05:45
@KevinRodriguez777 can you confirm this? dotenv rings a bell though, probably it's complaing about a lack of config file there.

**Comment by KevinRodriguez777** [comment] 2024-03-13 06:15
> @KevinRodriguez777 can you confirm this? dotenv rings a bell though, probably it's complaing about a lack of config file there.

it's failing here https://github.com/theskumar/python-dotenv/blob/d6c0b9638349a7dd605d60ee555ff60421c1a594/src/dotenv/main.py#L302-L306
it's not a config file, it's a problem when using `load_dotenv()`

**Comment by KevinRodriguez777** [comment] 2024-03-13 06:46
i could PR dotenv and do something like this 
```py
if usecwd or _is_interactive() or getattr(sys, 'frozen', False):
        # Should work without __file__, e.g. in REPL or IPython notebook.
        path = os.getcwd()
elif "__compiled__" in globals():
        # For Nuitka compiled programs, use the directory of the main script
        path = os.path.dirname(sys.executable)
```
or we could handle it from the YAML or nuitka side, what do you think?

**Comment by kayhayen** [comment] 2024-03-13 07:59
I think `__compiled__.contained_dir` is the better choice, it works independent of modes, e.g. app bundles, module mode, onefile, etc. and is preferable to manual guessing. I added it only recently.

```
.. important::

   What you should **not** do, is use the current directory
   ``os.getcwd``, or assume that this is the script directory, e.g. with
   paths like ``data/``.

   If you did that, it was never good code. Links, to a program,
   launching from another directory, etc. will all fail in bad ways. Do
   not make assumptions about the directory your program is started
   from.

In case you mean to refer to the location of the ``.dist`` folder for
files that are to reside near the binary, there is
``__compiled__.containing_dir`` that also abstracts all differences with
``--macos-create-app-bundle`` and the ``.app`` folder a having more
nested structure.

.. code:: python

   # This will find a file *near* your app or dist folder
   try:
      open(os.path.join(__compiled__.containing_dir, "user-provided-file.txt"))
   except NameError:
      open(os.path.join(os.path.dirname(sys.argv[0]), "user-provided-file.txt"))
```

What is the original code like from dotenv there?

**Comment by KevinRodriguez777** [comment] 2024-03-13 15:32
```py
        while frame.f_code.co_filename == current_file or not os.path.exists(
            frame.f_code.co_filename
        ):
            assert frame.f_back is not None
            frame = frame.f_back
        frame_filename = frame.f_code.co_filename
        path = os.path.dirname(os.path.abspath(frame_filename))
``` the problem is that it was failing due to this. the source is linked above

**Comment by kayhayen** [comment] 2024-03-14 08:19
Oh, `os.path.exists(...co_filename)` is going to be false a lot for Nuitka. I guess, it wants to find the frame upwards, that lives in a different file.

>>> inspect.getmodule(os.path.basename.__code__)
<module 'posixpath' from '/usr/lib/python3.10/posixpath.py'>

That makes me assume this would be a good replacement:

```
while inspect.getmodule(frame.f_code) is inspect.getmodule(sys._getframe()):
   frame = frame.f_back
```

That is however only beauty I guess.


With the existence check, it probably wants to get rid of import bootstrap ones, which I think are better done with a .startswith() on the module `__name__` maybe. So 

```
not os.path.exists(
            frame.f_code.co_filename
        )
```

could likely be replaced with
```
inspect.getmodule(frame.f_code).startswith("importlib"
```

Multi-line strings are a bit difficult in yaml, but doable with the `|` notation. So far, we use them only for replacement values, but maybe there is an example how to use it for the key in the replacement_plain dict.

**Comment by c469591** [comment] 2024-03-15 14:13
Hello!
Although I don't quite understand what you are discussing, may I ask if my question has already found a solution?
Or what should I do now to solve this problem?
Thank you.

**Comment by artem3k** [comment] 2024-03-16 18:13
Hello!
load_dotenv() -> no work
load_dotenv('.env') -> work

nuitka==2.1.2
python-dotenv~=1.0.1

**Comment by c469591** [comment] 2024-03-17 03:47
hi
@artem3k
Where should I add the judgment code you mentioned? Adding the judgment code as you said in my code will cause errors.
NameError: name 'dotenv_path' is not defined                                                                            
thank

**Comment by kayhayen** [comment] 2024-03-17 11:12
Please allow me to criticize this issue. There are not even pip package names provided, that are required to run the example. When I do it, I get an error like this:

```
  File "C:\Users\kayha\repos\Py2C\Mini2.py", line 28, in login
    driver = webdriver.Edge(EdgeChromiumDriverManager().install(), options=option)
TypeError: WebDriver.__init__() got multiple values for argument 'options'
```

The example is asking choices, I do not want prompts in minimal examples, I want straight out errors, that are unique to the code.

**Comment by kayhayen** [comment] 2024-03-17 11:13
For the dotenv part, I updated our workaround to their new (bad) code. Previously they insisted on package directories to exist (which they do not with compiled code in all cases), and now they want filenames of Python files to exist, which they definitely do not with Nuitka. With that, I am getting the same error when selecting Edge as with the example script.

**Comment by kayhayen** [comment] 2024-03-17 11:13
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by c469591** [comment] 2024-03-18 03:56
Hello, I have used this command to update to the development version.
python -m pip install -U --force-reinstall "https://github.com/Nuitka/Nuitka/archive/factory.zip"
The displayed version is
Successfully installed Nuitka-2.2rc2 ordered-set-4.1.0 zstandard-0.22.0
I use this command to package the exe.
nuitka  --standalone  --show-memory  --show-progress  --follow-import-to=need  --output-dir=o  --nofollow-imports  test.py
An error occurred.
[log.log](https://github.com/Nuitka/Nuitka/files/14630681/log.log)

**Comment by artem3k** [comment] 2024-03-18 05:08
@c469591 Sorry, I misled you. The code above is a snippet from the dotenv code. A temporary solution is simply to specify the path `load_dotenv('.env')`

**Comment by kayhayen** [comment] 2024-03-18 08:55
@c469591 that was a regression of factory, that I fixed only now, please retry

**Comment by kayhayen** [comment] 2024-03-18 08:57
@artem3k with my fix, workarounds should not be necessary anymore, but all forms are supposed to work. Of course, specifying the path indeed avoids the problematic code, but I am not sure your variant does it, anyway, changing the code is never the preferred solution in Nuitka, we want to be 100% compatible with these kind of packages.

**Comment by c469591** [comment] 2024-03-18 10:17
@kayhayen
Succeeded, the exe file can now run normally.
However, the time it takes to package into an exe file is particularly long, taking nearly 10 minutes. Is there a way to shorten the packaging time for exe files?
thank

**Comment by kayhayen** [comment] 2024-03-18 10:23
Yes, but this is not a personal support thread.

**Comment by c469591** [comment] 2024-03-19 02:29
@kayhayen
Could you please tell me if individual support services require the purchase of a subscription? Or where should I inquire about it?
thank

**Comment by kayhayen** [comment] 2024-03-19 08:23
@c469591 https://nuitka.net/doc/commercial.html and there is a form if it doesn't answer your questions

**Comment by kayhayen** [comment] 2024-03-22 08:55
This part of the 2.1.3 release I just made.

**Closed by kayhayen** 2024-03-22 08:55 UTC
Labels: bug, factory

**Comment by JULIALA12** [comment] 2024-05-01 14:30
"When I use this code, it works."
try:
      open(os.path.join(__compiled__.containing_dir, "user-provided-file.txt"))
   except NameError:
      open(os.path.join(os.path.dirname(sys.argv[0]), "user-provided-file.txt"))
  
  "But this code doesn't work."
  try:
      open(os.path.join(__compiled__.containing_dir, "template", "user-provided-file.txt"))
   except NameError:
      open(os.path.join(os.path.dirname(sys.argv[0]), "template", "user-provided-file.txt"))
"In '--onefile' mode for the executable file."
"Please help me. Thank you."
