### ISSUE TITLE
name 'exit' is not defined NameError when compiling with --standalone

### ISSUE THREAD

**Issue by viown** [Nuitka/Nuitka#1214] opened 2021-09-17 06:23 UTC
After compiling and running the following code:
```py
exit(0)
```
I get this error:
```
NameError: name 'exit' is not defined
```
This seems to only occur when compiling with the standalone flag, without it, the program runs fine.

Version:
```
0.6.16.4
Python: 3.9.7 (default, Aug 31 2021, 13:28:12) 
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
```

**Comment by kayhayen** [comment] 2021-09-17 11:42
I indeed managed to reproduce this, and it seems that hard imports are not causing usage, and "site" got added to the list at some point, and then it has the code not embedded, and therefore is not actually modifying the builtins.

**Comment by kayhayen** [comment] 2021-09-17 12:11
I have a suspect, that you may, just like I did, have modified the `site.py` file at some point, which makes it not use the bytecode file, and at least for the configuration I was trying with, 2.7 on Linux, that made it not include it. It may also be another kind of error, which is Python2 specific. When I reverted that, I think I still reproduce it, despite "site" now being included.

**Comment by kayhayen** [comment] 2021-09-19 08:20
Ok, this was really confusing, even for me, there is code in Nuitka that modifies `site.py` on the fly and that is causing it:

```
        # Anaconda3 4.1.2 site.py
        source_code = source_code.replace(
            "def main():", "def main():return\n\nif 0:\n def _unused():"
        )
```

Not sure if it's relevant anymore, but this disabled more than necessary, in fact allmost all that site.py does, turning down the difference between `site` and `no_site` and affected other Python distribution, like e.g. my Debian Python2 where I reproduced your error.

I will be removing and see what happens to Anaconda3 then, and potentially find a better solution. Since this is in special code, it has no traces of happening, but I don't want to clean that part of up, maybe once the anti-bloat plugin is baseline and its engine can be assumed to be available for modification of source.

**Comment by kayhayen** [comment] 2021-09-19 09:35
It's fixed on the factory branch, I could reproduce any need with older Anaconda3 that I still had, and not with current Anaconda3 I installed to test it, so this is probably just fine to remove. Of course it may find issues with site module stuff now, but such is life, the change is on factory branch https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment] 2021-09-19 17:10
This is now on develop branch.

**Comment by viown** [comment] 2021-09-20 04:39
I've tried again from both the factory & develop branch and the issue seems to still persist for me.

**Comment by kayhayen** [comment] 2021-10-03 09:08
This is part of the 0.6.17 release.

**Closed by kayhayen** 2021-10-03 09:08 UTC
Labels: bug, develop
