### ISSUE TITLE
cloudpickle nuitka.NuitkaOptimizationError

### ISSUE THREAD

**Issue by jamesstidard** [Nuitka/Nuitka#159] opened 2018-10-02 15:32 UTC
Hi,

I'm having some issues building a project with a [distributed](https://github.com/dask/distributed) dependency. I'm getting the following error:

```sh
nuitka.Errors.NuitkaOptimizationError: 
This statement does raise but didn't annotate an exception exit.

    <node co_argcount="1" co_filename="/home/super/.local/share/virtualenvs/nuitka_playground-THapz-Nf/lib/python3.7/site-packages/cloudpickle/cloudpickle.py" co_has_closure="False" co_has_stardict="False" co_has_starlist="False" co_is_optimized="True" co_kind="Function" co_kwonlyargcount="0" co_lineno="105" co_name="inner" co_new_locals="True" co_varnames="value,cell" code_flags="" kind="StatementsFrameFunction" line="105">
      <role name="statements" type="list">
        <node kind="StatementExpressionOnly" line="106">
          <role name="expression">
            <node code_name="cloudpickle$cloudpickle$$$function_1__make_cell_set_template_code$$$function_1_inner$$$function_1_lambda" kind="ExpressionFunctionRef" line="106" />
          </role>
        </node>
        <node is_temp="False" kind="StatementAssignmentVariable" line="107" owner="cloudpickle$cloudpickle$$$function_1__make_cell_set_template_code$$$function_1_inner" variable_name="cell">
          <role name="source">
            <node kind="ExpressionVariableRef" line="107" owner="cloudpickle$cloudpickle$$$function_1__make_cell_set_template_code$$$function_1_inner" variable_name="value" />
          </role>
        </node>
        <node kind="StatementReturnNone" line="105" />
      </role>
    </node>
```

Here's the source:

```python
# main.py
import distributed

if __name__ == "__main__":
    client = distributed.Client()
    client.close()
```

and building with `python -m nuitka main.py --follow-imports`

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

   0.6.0.1
   Python: 3.7.0 (default, Oct  2 2018, 15:47:42) 
   Executable: /home/super/.local/share/virtualenvs/nuitka_playground-THapz-Nf/bin/python
   OS: Linux
   Arch: x86_64

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

I used pipenv 2018.7.1 which makes a virtual environment.

Thanks for your time & the project.

**Comment by kayhayen** [comment] 2018-10-02 18:10
Thanks for the report. The XML makes it obvious that function reference in that statement only is retained only because it apparently can raise.

I pushed a fix for that to factory: http://nuitka.net/doc/factory.html

Can you try it. I am a bit uncertain, but I think the assignment statement afterwards doesn't share a problem, or you will now get a crash report with less XML attached. Either way thanks for your report, and forgive me not trying to fully reproduce but let you do it instead.

**Comment by jamesstidard** [comment] 2018-10-02 19:46
Hi @kayhayen, great. Yeah, no problem. I won't have access to a machine until the morning, but I'll check it out then and report back.

Thanks.

**Comment by kayhayen** [comment] 2018-10-03 09:03
Can you retry, should be all perfect now. Factory can be a bit unstable at times, was doing a fixup for another issue that regressed stuff for you.

I actually also made it part of 0.6.0.2 hotfix btw, like I said, not too sure if it's all the fix you need, but definitely a bug that was fixed and a missing optimization at that.

**Comment by jamesstidard** [comment] 2018-10-03 09:38
Ah yeah, I see they are different method calls now "getFullName" and "getFilename". Was reading them both as 'get full name'.

I ran factory 0.6.1rc3 and I no longer get that error. Though, I now get a different one :). Maybe this is related to some other things being changed on the factory branch at the moment.

```sh
Nuitka:WARNING:Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:WARNING:Unresolved '__import__' call at '/home/super/.local/share/virtualenvs/nuitka_playground-THapz-Nf/lib/python3.7/site-packages/cloudpickle/cloudpickle.py:931' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/super/.local/share/virtualenvs/nuitka_playground-THapz-Nf/lib/python3.7/site-packages/cloudpickle/cloudpickle.py:966' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/super/.local/share/virtualenvs/nuitka_playground-THapz-Nf/lib/python3.7/site-packages/cloudpickle/cloudpickle.py:1148' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/super/.local/share/virtualenvs/nuitka_playground-THapz-Nf/lib/python3.7/site-packages/toolz/compatibility.py:39' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/super/.local/share/virtualenvs/nuitka_playground-THapz-Nf/lib/python3.7/site-packages/tornado/util.py:178' may require use of '--include-plugin-directory' or '--include-plugin-files'.
Nuitka:WARNING:Unresolved '__import__' call at '/home/super/.local/share/virtualenvs/nuitka_playground-THapz-Nf/lib/python3.7/site-packages/tornado/util.py:181' may require use of '--include-plugin-directory' or '--include-plugin-files'.
/home/super/.pyenv/versions/3.7.0/lib/libpython3.7m.a(main.o): In function `Py_GetArgcArgv':
/tmp/python-build.20181002154641.10805/Python-3.7.0/Modules/main.c:2711: multiple definition of `Py_GetArgcArgv'
main.build/MainProgram.o:MainProgram.c:(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
scons: *** [main.bin] Error 1
```

Thanks

**Comment by kayhayen** [comment] 2018-10-03 09:47
The linker error is the one from #95 and makes me wonder what version you are using. You didn't put nuitka --version but for that it would now be needed. It's not a CPython I believe, is it?

**Comment by kayhayen** [comment] 2018-10-03 09:53
Ah, I noticed "pyenv" in there. So that is exactly the version that needs manual intervention or the PR implemented to do it automatically. Let me know if you are willing to take it into yourself to automate the procedure described in #95.

Otherwise I consider this issue closed. If you don't want to hack stuff, you will need to switch Python to a supported implementation.

**Closed by kayhayen** 2018-10-03 09:53 UTC
Labels: bug

**Comment by jamesstidard** [comment] 2018-10-03 09:56
Um, I am using CPython 3.7.0 installed via pyenv 1.2.7 (I see in the issue you linked it seems like a similar setup to @niothiel.

Here's the nuitka version output as well for completeness. 

```sh
0.6.1rc3
Python: 3.7.0 (default, Oct  2 2018, 15:47:42) 
Executable: /home/super/.local/share/virtualenvs/nuitka_playground-THapz-Nf/bin/python
OS: Linux
Arch: x86_64
```

I'll take a look at that issue and see where it gets me. Thanks again for quick response / fixes.

**Comment by kayhayen** [comment] 2018-10-03 10:11
Well, it's not the CPython binary distribution, but the CPython source compiled with other flags. No shared library is problematic for Nuitka if the static library is unusable due to "main.o" in there. We could also try and check if they were willing to change it upstream. Otherwise I think pyenv will work nicely or even better for Nuitka due to avoiding the DLL hoops.
