### ISSUE TITLE
"hello world" on macOS Mojave and miniconda - dyld: Library not loaded

### ISSUE THREAD

**Issue by gioboske** [Nuitka/Nuitka#499] opened 2019-08-22 19:10 UTC
Hello all,
first try with miniconda installation of Nuitka, with a simple hello-world script on macOS Mojave.
Here the key info:
- Python and Nuitka version:
```
nuitka: 0.6.5
Python: 3.7.4 (default, Aug 13 2019, 15:17:50) 
OS: Darwin
Arch: x86_64
```
- Tested both with Python3 and Nuitka installed from conda-forge and with Python3 from miniconda main and Nuitka installed from PyPI.

- Compiled with:
`python -m nuitka hello.py`
tried also with `--standalone`

- hello.py source from Nuitka documentation:
```
def talk(message):
    return "Talk " + message

def main():
    print(talk("Hello World"))

if __name__ == "__main__":
    main()
```

- No error at compile time (also checked with `--verbose` and `--show-scons`)

- Always get the following error at runtime:
```
dyld: Library not loaded: @rpath/libpython3.7m.dylib
  Referenced from: /Users/gioboske/dev/nuitka/hello.dist/./hello
  Reason: image not found
Abort trap: 6
```
Am I missing something obvious?
Thank you.

**Comment by kayhayen** [comment] 2019-08-23 06:13
There was a fix in 0.6.5 driven by Travis testing of macOS, with corrupted paths. Can you confirm if in hello.dist there is a file named `libpython3.7m.dylib`. I think there is somebody else working on a PR which fixes up handling of `@` keywords, but that was for specific Qt installations, but maybe hello world is affected with Python3.7 already.

But at least for MiniConda this could be a case of `nuitka.PostProcessing` failing to copy the shared library ner the executable.

Should it be missing, you can verify by not using standalone mode and placing the DLL next to the binary when executing it. If that works, I will know what to do then.

**Comment by gioboske** [comment] 2019-08-23 09:28
Hi Kay,
the library `libpython3.7m.dlyb` is **not included** in hello.dist when compiling with`--standalone` option (I paste below the output of `ls`, maybe it helps).

Unfortunately, the same error persists also without `--standalone` option, manual copying the library next to `hello.bin`.

Let me know if you need some additional info (I'm not a skilled developer, but I'll do my best!).

```
_asyncio.so		_curses.so		_pickle.so		binascii.so
_bisect.so		_curses_panel.so	_posixsubprocess.so	fcntl.so
_blake2.so		_datetime.so		_queue.so		grp.so
_bz2.so			_dbm.so			_random.so		hello
_codecs_cn.so		_decimal.so		_scproxy.so		math.so
_codecs_hk.so		_elementtree.so		_sha3.so		mmap.so
_codecs_iso2022.so	_hashlib.so		_socket.so		pyexpat.so
_codecs_jp.so		_heapq.so		_sqlite3.so		readline.so
_codecs_kr.so		_json.so		_ssl.so			select.so
_codecs_tw.so		_lsprof.so		_struct.so		termios.so
_contextvars.so		_lzma.so		_tkinter.so		unicodedata.so
_crypt.so		_multibytecodec.so	_uuid.so		zlib.so
_csv.so			_multiprocessing.so	array.so
_ctypes.so		_opcode.so		audioop.so
```

**Comment by gioboske** [comment] 2019-10-13 11:51
Any update on this issue?
Looking forward to use Nuitka on my Mac...

**Comment by kayhayen** [comment] 2019-10-17 09:08
@gioboske is that with develop branch, because otherwise you won't have the improvements for macOS then.

**Comment by gioboske** [comment] 2019-10-17 22:05
> @gioboske is that with develop branch, because otherwise you won't have the improvements for macOS then.

Sorry @kayhayen, but I didn't get the point... Do you mean that the issue was resolved in the develop branch of Nuitka? I've installed Nuitka in a conda environment with the following command:
`pip install --no-cache-dir -U "https://github.com/Nuitka/Nuitka/archive/develop.zip"`
and the problem persist.

I saw that the issue was added to the Planned To-Do list, but I'd only like to know if there was some progress or if I can support with some additional test.

Thanks.

**Comment by kayhayen** [comment] 2019-10-18 08:02
@gioboske if you could look into the code in `nuitka.freezer.Standalone` where the `otool` output is handled, can you see how it's not picking up the python DLL right there? This should be pretty easy to debug with print style debugging, and tracking the DLLs.

For macOS on develop, we now have two phases, so at one point, the output is captured, and then resolved later. But maybe it's still flawed. Surely is for your case with Anaconda using something we do not cover yet?

**Comment by gioboske** [comment] 2019-11-22 01:46
Finally, I found some time to debug, following your suggestion to look into the code in `nuitka.freezer.Standalone` for `otool` output.

As far as I understood, nuitka finds no "rpaths" (in `_detectBinaryRPathsMacOS`): while processing the output of `otool -l` on the executable, only the `cmd LC_RPATH` load commands are considered. Unfortunately, no `cmd LC_RPATH` are present in the output of `otoll -l` and `@rpath/libpython3.7m.dylib` only appears as follows:

```
Load command 12
          cmd LC_LOAD_DYLIB
      cmdsize 56
         name /usr/lib/libSystem.B.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 1281.0.0
compatibility version 1.0.0
Load command 13
```

I think this explains why the library is not copied in the dist folder, but I didn't get why the error persists also when compiling without the `--standalone` option, manual copying the library next to `hello.bin`.

@kayhayen, do you have some additional suggestions?

**Comment by gioboske** [comment] 2019-11-22 13:26
**Update**: this issue is definitively related to #516.
Fixed as suggested by @brendanator, by manual copying the shared library `libpython3.7m.dylib` to the `.dist` folder and by adding the `@executable_path` to the executable rpaths with:
```
install_name_tool -add_rpath @executable_path/. hello
```

Anyway, the underlying issue is still there.

**Comment by gioboske** [comment] 2019-11-28 16:40
I am far from an expert in this area, but the only solution I've found to fix the issue is to call `install_name_tool -add_rpath` on the executable, so to add the correct path for `libpython` library.

In `nuitka.PostProcessing.executePostProcessing`the executable path for searching the `libpython` library is updated (lines 68-88). The call to `install_name_tool -add_rpath` is done adding at line 79:
```
callInstallNameToolAddRpath(result_filename, python_lib_path)
```
being `callInstallNameToolAddRpath` a convenient method derived from `nuitka.utils.SharedLibraries.callInstallNameTool`
```
def callInstallNameToolAddRpath(filename, rpath):
    command = ["install_name_tool", "-add_rpath", os.path.join(rpath, '.'), filename]

    with withMadeWritableFileMode(filename):
        result = subprocess.call(command, stdout=subprocess.PIPE)

    if result != 0:
        sys.exit(
            "Error, call to 'install_name_tool' to add rpath failed."
        )
```
The output of `otool -l` on the executable, now includes:
```
Load command 13
          cmd LC_LOAD_DYLIB
      cmdsize 64
         name @executable_path/libpython3.7m.dylib (offset 24)
   time stamp 2 Thu Jan  1 01:00:02 1970
      current version 3.7.0
compatibility version 3.7.0
[...]
Load command 16
          cmd LC_RPATH
      cmdsize 72
         path /Users/gioboske/dev/miniconda3/envs/nuitka-dev/lib/. (offset 12)
```
and `libpython3.7m.dylib` is copied in the dist folder.
However, please note that now the `LC_LOAD_DYLIB` is called on `@executable_path/libpython3.7m.dylib` instead of `@rpath/libpython3.7m.dylib`

@kayhayen: what do you think about this fix?

**Comment by kayhayen** [comment] 2019-11-29 10:27
@gioboske I think that is spot on, Nuitka updates existing rpaths, but there seems to be this case, where it should be added, and would be good indeed. I would very much welcome a PR with this code, can you create one please?

**Comment by kayhayen** [comment] 2019-11-29 10:27
As an aside, I am no expert on these things either, however much I ought to be. :)

**Comment by kayhayen** [comment] 2019-12-27 08:08
Released as 0.6.6

**Closed by kayhayen** 2019-12-27 08:08 UTC
Labels: bug

**Comment by mysakbm** [comment] 2022-08-28 21:58
Hi,
how does it look like with this error? I can confirm it is still there with nuitka 1.0.5, macOS Monteray, 12.5.1., Python 3.9.

**Comment by kayhayen** [comment] 2022-08-29 06:24
@mysakbm posting below existing issues is a surefire way to get ignored
