### ISSUE TITLE
Will Nuitka support version 3.11 new features as soon as possible?

### ISSUE THREAD

**Issue by rainzee** [Nuitka/Nuitka#1856] opened 2022-10-25 11:06 UTC
According to benchmark suite tests, version 3.11 gained an average of 20% performance improvement and it's all free, will our project benefit from these performance improvements? If the new version is supported, how soon is it expected to be released, I just tried to compile in the new version and got an error and looks like the new version is not currently available

**Comment by infinitepower18** [comment] 2022-10-25 15:35
I'm also wondering if it will be possible to compile for ARM64 Windows too, as Python 3.11 is the first version to officially support Windows ARM64.

**Comment by kayhayen** [comment] 2022-10-26 10:21
Many of the improvements of 3.11 are for things that Nuitka already does, so the combined gain might increase, but I don't have any estimates yet. Python 3.11 will of course be supported in the future, but it's not a 24h job to add a new Python version to Nuitka. A lot of internals changed, and as it sometimes the case, I can never know when it will be working as a 3.10 replacement at least, there might always be more that I don't know about yet.

Support me with purchasing subscription of Nuitka commercial if you want: https://nuitka.net/doc/commercial.html#sponsorship

**Comment by kayhayen** [comment] 2022-10-26 10:25
@infinitepower18 I have previously encountered ARM64 Python, and MSVC reports, but the quality was not as good. In theory, there should be nothing holding it back, outside of Scons not setting it up automatically maybe. You will be very welcome to work with me on that, if you are up for a bit of ping/pong reporting, or willing to donate a Surface Laptop to me.

**Comment by h8n71r5t** [comment] 2022-10-26 13:45
@kayhayen Can we start posting Nuitka bugs related to Python 3.11 or it isn't allowed yet?

**Comment by kayhayen** [comment] 2022-10-26 15:04
@h8n71r5t It's not really useful yet, because at this point, everybody will have the same errors, making it not work at all. I will need to announce experimental support for it to be useful.

**Comment by kul-sudo** [comment] 2022-11-02 16:45
I can confirm that there are certain errors during the compilation with Python 3.11. Let's now patiently wait for the developers to update Nuitka so that it can work with Python 3.11.

**Comment by kayhayen** [comment] 2022-12-21 17:09
I have made a posting explaining the process and status, which actually has made big advances:  https://nuitka.net/posts/python311-support.html

**Comment by RyanHope** [comment] 2023-01-31 07:22
so 1.5 is coming and still no 3.11 support?

**Comment by kayhayen** [comment] 2023-01-31 08:03
I actually expect it to be there, have made progress with generators, going to make a new post soon. But 1.5rc coes not yet have the changes, as some refactorings regressed asyncgen for old Python. Life is hard with these things.

**Comment by kayhayen** [comment] 2023-02-05 11:02
So, I have made some good progress the other day. Most basic tests seem to work. It appears the the "current" exception, which was normalized in Python3 so far, no longer is. But Nuitka matched that, and left performance on the table to be compatible, and now has to reverse its stance there. For the time being, `sys.exit()` makes Nuitka crash. And it seems that `next` on compiled generators, i.e. manually through that built-in is doing the same thing maybe. The usage works locally, but afterwards state is corrupted such as to segfault elsewhere. Lets see how hard this will be to track down.

I think I will release 1.5 once 3.11 works on the first level as indicated in my post, and I should make a new post of that tomorrow or so. Had been ill, and spared myself of PR somewhat during that time, but this also feels like substantial progress.

**Comment by kayhayen** [comment] 2023-02-13 13:50
I have updated the roadmap like this:

```
-  Basic tests appear all work now.

-  There is a lack of integration of compiled and uncompiled generators
   with each other, this needs porting still.

-  Attribute lookups for types with a generic one need to update that
   code path, they will be slower in 3.11 until we do that.

-  Execute Python 3.10 test suite in a compatible way with 3.11, so far
   we got to ``test_compile.py`` and are making good progress, solving
   issues one by one, deciding when to do 1.5 release based on when we
   hit a wall there.

-  And and execute Python 3.11 test suite in a compatible way with 3.11

-  MSVC in debug mode hates the Python headers, probably because they can
   not longer be used outside of C11 mode, and C++0x is not compatible enough
   for it. We might have to require newer MSVC and implement C11 mode for the
   new enough Windows SDK that allows it.

```

Pretty certain now that within 1-2 weeks, we will have a 3.11 supporting release that will be largely indistinguishable for 3.10 features and some new things. However, e.g. resource reader files, I fixed today incompatibly through new changes, and there may be some more issues in stock for say metadata, this kind of thing. But it surely feels good. The next pre-release that I will make tomorrow will probably be relatively good for most people. I changed develop to only give a warning, but using before 1.5rc8 or factory cannot be recommended.

At this point, I don't need any reports if your stuff is not working. I will surely want to first get all the failing tests, where issues are easily isolated to work.

**Comment by kayhayen** [comment] 2023-02-24 21:42
It seems the CPython 3.10 test suite is passing for the largest part, and the last major problem was that standalone crashed on Windows.

For performance, attributes are going to be worse now, and there are a couple of TODOs, but at least 3.11 shall become usable.

**Comment by bersbersbers** [comment] 2023-02-25 14:23
> standalone crashed on Windows

I had noticed that, happy to be able to confirm it seems resolved.

(I had not reported it due to your previous comment - I assume you will let people know when issues actually should be reported.)

**Comment by kayhayen** [comment] 2023-02-26 19:27
Actually with 1.5 release, it's good to go I think. Obviously, for 3.11 new features or behavior changes not followed, there won't be support yet. For now, 3.11 will be usable instead of 3.10, as a replacement of that, but not really a 3.11 replacement. I have not executed the new tests of new functionality or changed behaviors.

And indeed, I wasn't going to look e.g. at standalone like first thing, which you as a user of course will. But me of course the base is most critical.

As for performance, I am not happy with the attribute setting/getting stuff not yet being there. I would still recommend 3.10 for now, but I don't feel like 3.11 will not work for the vast majority of you guys now on develop and soon on main. My intent is for 1.6 to be a release that will be almost fully 3.11 compatible.

Some things, e.g. match syntax, or e.g. 3.7 `importlib.resources` are longer running issues, where incrementally things get better, but so far I have not yet looked at 3.11 for crazy new features. But the way I learn the Python changelog is by executing their test suite with Nuitka if you get what I am doing there.

**Comment by kayhayen** [comment] 2023-02-26 19:29
The current onefile issue is blocking me from releasing 1.5 btw, but I hope it's sorted out soon. I was going to release it tomorrow or so, but now only once I know my performance improvements there didn't make things less reliable.

**Comment by kayhayen** [comment] 2023-02-27 11:09
The onefile issue turns out to be not an regression, and is fixed too, so nothing but changelog and generally me reviewing if I forgot something, is what it takes now. I also found that e.g. `importlib.resources` didn't work with my 3.11 tests, but that is also fixed on develop. From here on it seems to be cleanup only.

**Comment by kayhayen** [comment] 2023-02-27 14:44
So current develop is very close to what 1.5 will be. If you find anything there that is not related to 3.11 specific code (like a new PEP being used), reporting against develop will be considered fair game now.

**Comment by kayhayen** [comment] 2023-02-27 14:46
In terms of hotfixing for 3.11 it depends on how much I will find to do once I go over the 3.11 test suite, which naturally will be a bit slower, since randomness, etc. there is always a lot of time spend on cherry-picking changes there, so progress there is slow, and at times, new features or changes are not easy to backport. For 3.11 the develop version may remain the one to use until 1.6 at least, but we will see how much it is.

**Comment by kayhayen** [comment] 2023-03-01 12:56
I am ill right now, therefore delaying the release, just to not get into pressure. Please hammer develop as if it was the release.

**Comment by pauljurczak** [comment] 2023-03-11 00:52
Here is a case when 1.4.7 works fine, despite many warnings, but 1.5rc12 fails. Built in venv with Python 3.10.6 and 3.11.2 respectively. I'm testing the binaries on Ubuntu 22.04 where they were built and with Docker and deb-slim image. Logs attached below.


[nuitka-1.4.7.txt](https://github.com/Nuitka/Nuitka/files/10947042/nuitka-1.4.7.txt)
[nuitka-1.5rc12.txt](https://github.com/Nuitka/Nuitka/files/10947046/nuitka-1.5rc12.txt)

**Comment by kayhayen** [comment] 2023-03-11 05:34
@pauljurczak this is not for reporting via comments in this issue. Running inside docker seems to be the preferred way to compile programs that otherwise would not run, i.e. you probably do not have matplotlib in your Python3.11 there, which is of course obvious if you run it inside the container.

**Comment by pauljurczak** [comment] 2023-03-11 05:48
You are right. There is a mix-up with two virtual environments in the same VSCode projects.

**Comment by kayhayen** [comment] 2023-03-11 08:41
So, the release is going out today. I am therefore modifying the issue. I think it was good to have it as a point to make quick reports. I expect new issues to be created for 3.11 specific reports. Should there continue to be bottom posting of supposed findings with no good report context, I am going to lock it, so content is relevant.

**Comment by kayhayen** [comment] 2023-03-11 08:42
Putting it to 1.6, I believe there are not that many missing features, but since there is no "CPython311" test suite yet, I will not really know. The first step will be to create the test suite following the instructions I have written up in the developer manual.

**Comment by kayhayen** [comment] 2023-03-11 13:24
I don't think it's much more far off than a month to have the full support. Actually my knowledge right now suggests there are barely new features in 3.11 outside of those painful core changes to gain performance. We shall see. I will soon wade my way through the test suite. Also I think I will try and do cross Python version comparisons, to identify, if and where Nuitka falls off, sometimes I might have not noticed degradation. With 1.4 most of those are supposed to be addressed, but who knows.

Full compatibility is the major selling point of Nuitka in my book. So any statement of it not being fully compatible hurts me of course. But there is also #2099 which I will have to deal with.

For performance work, I will mostly let go of it, and rather work on the class scalability stuff, which will get clear from looking at the changelog, why that is so big.

**Comment by rainzee** [comment] 2023-04-28 16:17
Any recent noteworthy developments?

**Comment by gdementen** [comment] 2023-04-28 16:49
AFAIK, @kayhayen is still planning to do it for the 1.6 release. We should just be patient.

**Comment by kayhayen** [comment] 2023-07-04 18:13
Never found this, of course the 1.6 release is out and claims full 3.11 support. In fact, I just made the 1.7 release. The performance for attributes are something to look at in the coming months, I believe we stand a chance that after serious cleanups (we have multiple variations of tp_getattr code forms), there should be a chance that we can improve this part of Python as well. And maybe, who knows, our JIT part in there will be far better or not.

**Closed by kayhayen** 2023-07-04 18:13 UTC
Labels: enhancement, question
