### ISSUE TITLE
Compiling easy install entry points doesn't result in anything useful

### ISSUE THREAD

**Issue by asm0dey** [Nuitka/Nuitka#1151] opened 2021-07-07 07:02 UTC
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  > python -m nuitka --version

```
0.6.16.2
Python: 3.9.6 (default, Jun 30 2021, 10:22:16)
Executable: /home/finkel/work_self/Flexget/bin/python
OS: Linux
Arch: x86_64
```

* How did you install Nuitka and Python

I've install nuitka in pip and python from my distribution, working inside venv

* The specific PyPI names and versions

  > python -m pip freeze

```
aniso8601==9.0.1
APScheduler==3.7.0
attrs==20.3.0
babelfish==0.5.5
beautifulsoup4==4.9.3
Brotli==1.0.9
certifi==2020.12.5
chardet==4.0.0
cheroot==8.5.2
CherryPy==18.6.0
click==7.1.2
colorama==0.4.4
colorclass==2.2.0
deluge-client==1.9.0
feedparser==6.0.8
Flask==1.1.2
Flask-Compress==1.10.1
Flask-Cors==3.0.10
Flask-Login==0.5.0
Flask-RESTful==0.3.9
flask-restx==0.4.0
-e git+git@github.com:Flexget/Flexget.git@ed41e678ac5e5e700cde7c2345b7004d2c1e03ef#egg=FlexGet
greenlet==1.0.0
guessit==3.2.0
html5lib==1.1
idna==2.10
importlib-metadata==4.6.0
itsdangerous==1.1.0
jaraco.classes==3.2.1
jaraco.collections==3.3.0
jaraco.functools==3.3.0
jaraco.text==3.5.0
Jinja2==3.0.1
jsonschema==3.2.0
loguru==0.5.3
MarkupSafe==2.0.0
more-itertools==8.8.0
Nuitka==0.6.16.2
plumbum==1.7.0
portend==2.7.1
progressbar==2.5
psutil==5.8.0
pynzb==0.1.0
pyparsing==2.4.7
pyrsistent==0.17.3
PyRSS2Gen==1.1
python-dateutil==2.8.1
pytz==2021.1
PyYAML==5.4.1
rebulk==3.0.1
requests==2.25.1
rpyc==5.0.1
SCons==4.1.0.post1
sgmllib3k==1.0.0
six==1.15.0
soupsieve==2.2.1
SQLAlchemy==1.4.20
tempora==4.0.2
terminaltables==3.1.0
typing-extensions==3.10.0.0
tzlocal==2.1
urllib3==1.26.4
webencodings==0.5.1
Werkzeug==1.0.1
zc.lockfile==2.0
zipp==3.4.1
zxcvbn-python==4.4.24
```

* Many times when you get an error from Nuitka, your setup may be special

works with following output:

```
Nuitka-Options:INFO: Used command line options: --run some.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.16' on Python '3.9' commercial None.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 12 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'disabled': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 11
Nuitka:INFO: Keeping build directory 'some.build'.
Nuitka:INFO: Successfully created 'some.bin'.
Nuitka:INFO: Launching 'some.bin'.
hello world
```

* Also supply a [Short, Self Contained, Correct, Example](http://sscce.org/)

I'mtrying to build flexget with `nuitka3-run --standalone --onefile --linux-onefile-icon=./256.png --plugin-enable=numpy --plugin-enable=pylint-warnings bin/flexget execute` and getting following output

```
Nuitka-Options:INFO: Used command line options: --run --standalone --onefile --linux-onefile-icon=./256.png --plugin-enable=numpy --plugin-enable=pylint-warnings bin/flexget
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.16' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'tkinter' added '_tkinter'.                                                                                                                
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.                                                                                                                  
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy' added 'numpy.compat,numpy.lib,numpy.linalg,numpy.fft,numpy.polynomial,numpy.random,numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand,numpy.ctypeslib,numpy.ma,numpy.matrixlib'.          
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pycparser.c_parser' added 'pycparser.yacctab,pycparser.lextab'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'scipy._lib' added 'scipy._lib.messagestream'.                                                                                             
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.random' added 'numpy.random._bounded_integers,numpy.random._common,numpy.random._generator,numpy.random._mt19937,numpy.random._pcg64,numpy.random._philox,numpy.random._sfc64,numpy.random.bit_generator,numpy.random.mtrand'.                                                                                                                        
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'numpy.core' added 'numpy.core._dtype_ctypes,numpy.core._multiarray_tests'.                                                                
Nuitka:INFO: Completed Python level compilation and optimization.                                                                                                                                                 
Nuitka:INFO: Generating source code for C backend compiler.                                                                                                                                                       
Nuitka:INFO: Running data composer tool for optimal constant value handling.                                                                                                                                      
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Compiled 160 C files using ccache.                                                                                                                                                             
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'disabled': 1
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 159
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/Grammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3/PatternGrammar3.9.6.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Postprocessing:INFO: Completed onefile creation.
Nuitka:INFO: Keeping dist folder 'flexget.dist' for inspection, no need to use it.
Nuitka:INFO: Keeping build directory 'flexget.build'.
Nuitka:INFO: Successfully created 'flexget.bin'.
Nuitka:INFO: Launching 'flexget.bin'.
Traceback (most recent call last):
File "/tmp/finkel/.mount_flexgeAVwdY2/flexget", line 33, in <module>
File "/tmp/finkel/.mount_flexgeAVwdY2/flexget", line 25, in importlib_load_entry_point
File "/tmp/finkel/.mount_flexgeAVwdY2/importlib/metadata.py", line 77, in load
File "importlib.py", line 127, in import_module
File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 850, in exec_module
File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
File "/home/finkel/work_self/Flexget/flexget/__init__.py", line 10, in <module>
from flexget import log  # noqa
File "/home/finkel/work_self/Flexget/flexget/log.py", line 14, in <module>
import loguru
ModuleNotFoundError: No module named 'loguru'
```

* In your issue the options used

  Ideally use the project feature, so options and example code go alone

  [Nuitka Options in the code](https://nuitka.net/doc/user-manual.html#nuitka-options-in-the-code)

* Note if this is a regression

  If it used to work in an earlier version of Nuitka, please note what you know
  about that.

**Comment by kayhayen** [comment] 2021-07-07 07:17
Can you provide a link to the actual code too?

**Comment by asm0dey** [comment] 2021-07-07 07:39
Oh, of course, I'm sorry

https://github.com/Flexget/Flexget

**Comment by kayhayen** [comment] 2021-11-06 11:35
I did the cloning but I feel this is not minimal enough, since naturally there is no `bin/flexget`. The importing of loguru works. I am suspected, this is about the entry points created, which Nuitka will not see through. There is plenty of work done in this field in the `pkg_resources` plugin, but likely not enough yet. I have at least one other report about this kind of error.

**Comment by asm0dey** [comment] 2021-11-06 11:38
Yeah, I'm sorry I can't provide you with a real minimal reproducer. Of course, flexget is big and complex. But I don't know how to minimize it — I just don't know enough about the whole field.

**Comment by kayhayen** [comment] 2021-11-06 15:25
I am trying it out right now, I think `importlib_load_entry_point` is something that needs handling by nuitka. A naive build just includes nothing but the runner which in term won't find anything, not even the `flexget` top level module which it apparently did for you. What people can also do is `python setup,.py bdist_nuitka` which creates different runners. But I want to get the compilation from installation to work of course too.

**Comment by kayhayen** [comment] 2021-11-06 15:26
So this is the trouble maker:

```
# EASY-INSTALL-ENTRY-SCRIPT: 'FlexGet==3.1.150.dev0','console_scripts','flexget'
import re
import sys

# for compatibility with easy_install; see #2198
__requires__ = 'FlexGet==3.1.150.dev0'

try:
    from importlib.metadata import distribution
except ImportError:
    try:
        from importlib_metadata import distribution
    except ImportError:
        from pkg_resources import load_entry_point


def importlib_load_entry_point(spec, group, name):
    dist_name, _, _ = spec.partition('==')
    matches = (
        entry_point
        for entry_point in distribution(dist_name).entry_points
        if entry_point.group == group and entry_point.name == name
    )
    return next(matches).load()


globals().setdefault('load_entry_point', importlib_load_entry_point)


if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(load_entry_point('FlexGet==3.1.150.dev0', 'console_scripts', 'flexget')())
```

**Comment by kayhayen** [comment] 2021-11-06 15:55
Interestingly `bdist_nuitka` found an obscure bug that affected `lexget.components.series.next_series_episodes`, but it may also be because of recent optimization added, I fixed it for factory branch. Then `bdist_nuitka` works.

**Comment by kayhayen** [comment] 2021-11-06 15:58
Unless I am mistaken, all it takes should be `--include-package=flexget` which I am currently trying out. Should that work, I will derive this from parsing `# EASY-INSTALL-ENTRY-SCRIPT:` in `__main__` modules, that won't be hard and could be added to the `pkg-resources` plugin. Removing the useless distribution, etc. stuff might still be needed though, so maybe it's more a task for `anti-bloat` plugin.

**Comment by kayhayen** [comment] 2021-11-06 17:31
The include is not enough, this is sort of a duplicate, and reproduces your issue. I now understand that I confused binary name and package name, where filename is in the traceback output

```
Traceback (most recent call last):
  File "/home/hayen/test/flexget-issue/flexget.dist/flexget", line 33, in <module>
  File "/home/hayen/test/flexget-issue/flexget.dist/flexget", line 22, in importlib_load_entry_point
  File "/home/hayen/test/flexget-issue/flexget.dist/importlib_metadata/__init__.py", line 967, in distribution
  File "/home/hayen/test/flexget-issue/flexget.dist/importlib_metadata/__init__.py", line 561, in from_name
importlib_metadata.PackageNotFoundError: No package metadata was found for FlexGet
```

So indeed, we need to replace the runner with a simpler version automatically.

**Comment by asm0dey** [comment] 2021-11-06 17:46
Wow, it's a comprehensive analysis! Should we try to loop flexget authors/maintainers in?

**Comment by kayhayen** [comment] 2021-11-06 19:01
I don't think it's anything special for flexget, I guess once it comes to data files, it will be needed for a command line to provide them, but `bdist_nuitka` ought to create a working wheel no problem with factory. It's just very unstable right now due to massive improvements in optimization.

**Comment by asm0dey** [comment] 2021-11-06 20:15
Thank you for your deep dive into the problem!

**Comment by kayhayen** [comment] 2021-11-07 09:08
So this is now working for me on factory branch, with working I mean "python setup.py install" into a virtualenv with Python3.7 (my self compiled Pythons don't do virtualenv without too much manual tweaking unfortunately). I need to checkout what this kind of thing generates for Python2 and what it puts into a `bdist_wheel` which may be yet another thing.

**Comment by kayhayen** [comment] 2021-11-07 09:09
https://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment] 2021-11-07 09:14
Actually installed wheel do not have these strange runners, but the one that Nuitka now compile time generates with only a very minimal difference. For fun, somebody ought to create an entry point with the function named "sys", wheels wouldn't work with that, but it's unlikely to happen in real life.

**Comment by kayhayen** [comment] 2021-11-10 07:36
This is on the develop branch now and will be part of the next stable release.

**Comment by kayhayen** [comment] 2021-12-03 07:20
This is part of the 0.6.18 release.

**Closed by kayhayen** 2021-12-03 07:20 UTC
Labels: bug, develop
