### ISSUE TITLE
File Not Found Error of several python library packages while I run executable app after successful compilation

### ISSUE THREAD

**Issue by MDMohiUddinKhan** [Nuitka/Nuitka#1334] opened 2021-12-21 08:56 UTC
*  Python Version
> python -m nuitka --version
0.6.18.4
Commercial: None
Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\R_K\anaconda3\envs\UI\python.exe
OS: Windows
Arch: x86_64

* How did you install Nuitka and Python
>Installed Python with Conda environment via PyCharm IDE.
Installed Nuitka using:  'pip install nuitka'                    from anaconda prompt

* The specific PyPI names and versions
 > python -m pip freeze
absl-py==1.0.0
altgraph==0.17.2
astunparse==1.6.3
cachetools==4.2.4
certifi==2021.10.8
charset-normalizer==2.0.9
click==7.1.2
flatbuffers==2.0
future==0.18.2
gast==0.4.0
google-auth==2.3.3
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.42.0
h5py==3.6.0
idna==3.3
importlib-metadata==4.8.2
joblib==1.1.0
keras==2.7.0
keras-pos-embd==0.12.0
Keras-Preprocessing==1.1.2
libclang==12.0.0
libpython==0.2
Markdown==3.3.6
Nuitka==0.6.18.4
numpy==1.21.4
oauthlib==3.1.1
opt-einsum==3.3.0
pandas==1.3.5
pefile==2021.9.3
plotly==5.4.0
protobuf==3.19.1
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyinstaller==4.7
pyinstaller-hooks-contrib==2021.4
PyQt5==5.15.4
pyqt5-plugins==5.15.4.2.2
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.0
pyqt5-tools==5.15.4.3.2
PyQtWebEngine==5.15.5
PyQtWebEngine-Qt5==5.15.2
pystache==0.6.0
python-dateutil==2.8.2
python-dotenv==0.19.2
pytz==2021.3
pyuic5-tool==0.0.1
pywin32-ctypes==0.2.0
qt5-applications==5.15.2.2.2
qt5-tools==5.15.2.1.2
requests==2.26.0
requests-oauthlib==1.3.0
rsa==4.8
scikit-learn==1.0.1
scipy==1.7.3
six==1.16.0
static==1.1.1
tenacity==8.0.1
tensorboard==2.7.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorflow-cpu @ https://storage.googleapis.com/tensorflow/windows/cpu/tensorflow_cpu-2.7.0-cp39-cp39-win_amd64.whl
tensorflow-estimator==2.7.0
tensorflow-io-gcs-filesystem==0.22.0
termcolor==1.1.0
threadpoolctl==3.0.0
typing_extensions==4.0.1
urllib3==1.26.7
Werkzeug==2.0.2
wincertstore==0.2
wrapt==1.13.3
zipp==3.6.0

* Many times when you get an error from Nuitka, your setup may be special

  The standalone executable of `print("hello world")` program works perfectly in the aforementioned Conda environment.

* Provide in your issue the Nuitka options used
`
conda install -c conda-forge libpython-static

  python -m nuitka --include-data-dir="E:\my_app\data"=data --follow-imports --enable-plugin=numpy --enable-plugin=pyqt5 --enable-plugin=tensorflow --enable-plugin=torch --include-package=plotly --include-package=keras  --include-package=keras_pos_embd --windows-icon-from-ico=Icon.ico --standalone --static-libpython=no my_app.py

C Compiler used is `mingw64` default download
`

### My Problem-1:
I installed libpython-static, checked with both python-3.6 & python-3.9.7 but that was still showing an Error like the following. That's why I used '--static-libpython=no'
FATAL: Error, usable static libpython is not found for this Python installation. You might be missing required '-dev' packages. Disable with --static-libpython=no" if you don't want to install it.

### My Problem-2:
My app structure has 1 main python script (my_app.py) along with 1 data folder containing 3 PyQt5 qt-design python scripts, 2 `*.joblib` files & a trained neural-network model (`*.h5`).
With the aforementioned command, I compiled my_app successfully, it took around 5 hours to complete.

**While I ran the my_app.exe for the first time, I got the following Error and to resolve that I copied the stated folder to my_app.dist directory from my conda environment Lib>Site Packages & the particular issue is resolved:**
`
(UI) E:\my_app.exe
Traceback (most recent call last):
  File "E:\my_app.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "E:\my_app.dist\sklearn\__init__.py", line 80, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "E:\my_app.dist\sklearn\_distributor_init.py", line 23, in <module>
  File "E:\my_app.dist\ctypes\__init__.py", line 382, in __init__
FileNotFoundError: Could not find module 'E:\my_app.dist\sklearn\.libs\vcomp140.dll' (or one of its dependencies). Try using the full path with constructor syntax.
`

**Now I got too many File not found error from Tensorflow package, so I again copied the entire tensorflow package folder from  my conda environment Lib>Site Packages to the my_app.dist Directory and now getting the following error:**
`
(UI) E:\my_app.exe
Traceback (most recent call last):
  File "E:\my_app.py", line 15, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "E:\my_app.dist\tensorflow\__init__.py", line 481, in <module tensorflow>
AttributeError: module 'tensorflow.python.keras' has no attribute '_load'
`

I located that the error coming from `\tensorflow\__init__.py`:

```
# Do an eager load for Keras' code so that any function/method that needs to
# happen at load time will trigger, eg registration of optimizers in the
# SavedModel registry.
# See b/196254385 for more details.
if hasattr(_current_module, "keras"):
  try:
    keras._load()
  except ImportError:
    pass
```

I searched my entire C drive for _load() function but had not found it, that's why I manually copied the os, sys, six folders from Lib>Site Packages to my_app.dist directory...

**Eventhough I explicitly mentioned `--include-package=plotly --include-package=keras  --include-package=keras_pos_embd`, I don't see these package's folder in the my_app.dist directory. So, I manually copied the keras, keras_pos_embd, os, sys, six folders from anaconda environment Lib>Site Package to my_app.dist Directory. The issue is not resolved & I'm now stucked-in here...**

Actually, I tried 4-5 times compiling the app with Nuitka & failed every time. 
I also tried compiling with 'fbs' & 'PyInstaller'. Executable GUI app using PyInstaller opened perfectly, I could load external data using QFileDialog module perfectly, GUI design & *.wav sound are okey but when it started classifying the Data with neural-network model, the app showed tensorflow/keras file not found error.

I'm building the project for my MEngg Research (Thesis) & that's why I cannot share the code, sorry...
Any help would be highly appreciable... Thanks in advance...

**Comment by MDMohiUddinKhan** [comment] 2021-12-21 09:28
**C Compiler used is `mingw64` default download**

**Comment by kayhayen** [comment] 2021-12-21 12:27
I think `libpython` is the Anaconda package. Current factory says that name. I hope it's correct, please let me know, since my Anaconda setup is too painful to install anything.

For including data files, there are options. Copying folders to the dist folder is not supported and known to not work.

You might want to consider https://nuitka.net/doc/commercial.html to protect your data files by not having them in the filesystem at all.

For including package data, there is an option, the --include-package option is not that, it includes the code.

**Comment by kayhayen** [comment] 2022-04-06 07:27
This is bad report without a reproducer, but Tensorflow and Keras are solved on factory, I am closing it, because there was also no further feedback.

**Closed by kayhayen** 2022-04-06 07:27 UTC
