### ISSUE TITLE
Support for "importlib.resources" should include a resources reader by Nuitka's loader, otherwise temporary files are used

### ISSUE THREAD

**Issue by AlphaLiu** [Nuitka/Nuitka#1321] opened 2021-12-17 14:27 UTC
* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  > python -m nuitka --version

Nuitka :  0.6.19rc5 (also same in 0.6.18.4)
Python: 3.10.1 (also same in 3.9)
Platform: Windows

* How did you install Nuitka and Python

  pip install nuitka

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

```python
import requests
import os


if __name__ == '__main__':
    print("Hello World")
    os.system('pause')
```

* Provide in your issue the Nuitka options used

 nuitka --standalone --onefile .\test.py

* issue

If "import requests" in python file (see above example) and build the exe by nuitka, when run the exe, problem occured:
```
❯ .\test.exe
Traceback (most recent call last):
  File "C:\Users\myname\AppData\Local\Temp\ONEFIL~1\importlib\_common.py", line 89, in _tempfile
  File "C:\Users\myname\AppData\Local\Temp\ONEFIL~1\importlib\abc.py", line 371, in read_bytes
  File "C:\Users\myname\AppData\Local\Temp\ONEFIL~1\importlib\_adapters.py", line 54, in open
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\myname\AppData\Local\Temp\ONEFIL~1\test.py", line 1, in <module>
    import requests
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\myname\AppData\Local\Temp\ONEFIL~1\requests\__init__.py", line 118, in <module requests>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "C:\Users\myname\AppData\Local\Temp\ONEFIL~1\requests\utils.py", line 40, in <module requests.utils>
  File "C:\Users\myname\AppData\Local\Temp\ONEFIL~1\certifi\core.py", line 37, in where
  File "C:\Users\myname\AppData\Local\Temp\ONEFIL~1\contextlib.py", line 135, in __enter__
  File "C:\Users\myname\AppData\Local\Temp\ONEFIL~1\importlib\_common.py", line 95, in _tempfile
PermissionError: [WinError 32] Another program is using this file and the process cannot access it: 'C:\\Users\\myname\\AppData\\Local\\Temp\\tmpzugfk3f4'
```
if i remove the "import requests" line and compiled with nuitka, the exe works.

**Comment by kayhayen** [comment] 2021-12-18 08:13
Actually, the version output should be pasted, it contains more information than you gave.

**Comment by kayhayen** [comment] 2021-12-18 08:15
I wonder if this is a virus scanner again, could well be, but what tempfile could requests possibly need, very strange.

**Comment by kayhayen** [comment] 2021-12-18 08:49
I am unable to reproduce it, unfortunately you didn't tell which requests version you have, therefore I have to guess. But since you tried out develop and 3.10 and 3.9 both as a good reporter should, I will do it for you this one time. ;-)

**Comment by kayhayen** [comment] 2021-12-18 09:25
Seems `certifii` is the offender here, and it's rather strange, `get_path` is asking for the embedded certificate, and then it creates a temporary file, because there is no `reader` and copies the content in there. So, that's horrible of course, and probably the issue here, is that such a `reader` is not detected by `importlib.resources`. Need to check out why that could be, temporary files of the extracted data files is ugly.

This seems to also affect https://nuitka.net/doc/commercial.html as I believe, that's another place to hook for embedded data files to work, one I haven't come across yet.

Luckily the issue seems sporadic, so this is not too urgent.

**Comment by AlphaLiu** [comment] 2021-12-18 12:51
Thank you for replying. 

The requests version info are here:
requests           2.25.1
urllib3            1.24.3

if it could work on your side, could you tell me your requests version? I could try it . Thank you .

**Comment by AlphaLiu** [comment] 2021-12-18 13:19
I uninstalled the python and installed a new one, make a clean enviroment, but still the same.

Package            Version
------------------ ---------
certifi            2021.10.8
charset-normalizer 2.0.9
idna               3.3
Nuitka             0.6.19rc5
pip                21.2.4
requests           2.26.0
setuptools         58.1.0
urllib3            1.26.7

**Comment by kayhayen** [comment] 2021-12-18 13:26
You are you saying, it's reproducible for you?

**Comment by AlphaLiu** [comment] 2021-12-18 13:27
Yes, I can always reproduce it. and in two different PCs.

**Comment by AlphaLiu** [comment] 2021-12-18 13:34
I could use nuitka to package the py files with pyside6, but could not if it import requests. really strange.

**Comment by kayhayen** [comment] 2021-12-18 13:51
And you are saying, you can reproduce it with the example given, right? Or is that just as guess that it might reproduce it too. I am not able to see it. I can guess only that something messes with your temporary file, e.g. a Virus checker. That would in principle be bad anyway, but as I said, with the `reader` provided, no such temporary file would come to exist and the issue would have to go away, but you are very alone with this issue right now. I think I would know if `certifi` always had this.

**Comment by AlphaLiu** [comment] 2021-12-18 14:21
Yes, I can reproduce with the example file. And I had uninstalled my antivirus software...
I would tyr more...

**Comment by kayhayen** [comment] 2021-12-18 14:27
Damn, we are missing something here, but like I said, the solution is of course to not use another code path than regular Python and just take the file from where it was unpacked to. Nuitka really doesn't have much business with file locks from other processes, if you know what I mean: `Another program is using this file and the process cannot access it` I would almost guess it's some kind of race, that you happen to loose with Windows Defender. I will treat this with priority, it seems to spoil things for at least some setups.

**Comment by AlphaLiu** [comment] 2021-12-18 14:39
I am not sure whether it releated with my platform, windows 11.

**Comment by kayhayen** [comment] 2021-12-18 14:55
I really, really need to stop working on issues with deficient issue templates. I am guessing it has new ways of locking files behind the back of the user. Creating a file and then using it, on Windows, it's a pattern that just doesn't work well. However, `nuitka --version` does not yet output the Windows version, so ... :)

**Comment by AlphaLiu** [comment] 2021-12-18 15:11
Good news.  I created a venv with python 3.9.9, used nuitka to build the exe, now it works.

I am not sure what happened. Thank you for helping.

**Comment by kayhayen** [comment] 2021-12-19 07:33
I am assuming it's sporadic, and that doesn't mean it doesn't exist. So far nobody has ever had the issue, and maybe it's more of an optimization, but it clearly also is a robustness issue. Virus scanners do exist after all and might be causing this. Not having the temporary file copied from a temporary file ought to be a very good idea.

**Comment by kayhayen** [comment] 2022-01-17 19:14
For the `certifi` package, `anti-bloat` now does a replacement that makes this go away for the popular package. It seemed to not happen with 3.9, but then 3.10 was crashing different, so it's hard to tell. I will probably push that for the next hotfix, so the feature can be still not implemented for some time.

**Comment by ido50** [comment] 2022-01-18 21:20
I am having the exact same issue with Python 3.10.2, Poetry 1.1.12 on Windows 10 (19042.1466), using both MSVC and MinGW64, and it happens consistently, with or without Windows Defender enabled. Stack trace is exactly the same as for OP.
I have also tried without Poetry (i.e. without a venv), and got the same result.

**Comment by kayhayen** [comment] 2022-01-19 09:01
The fix is here https://nuitka.net/doc/factory.html and coming as a hotfix as well, however it depends on the `anti-bloat` plugin to be enabled with `--enable-plugin=anti-bloat`, on develop that won't be necessary once the hotfix is out.

**Comment by kayhayen** [comment] 2022-01-20 09:23
The workaround was released as part of 0.6.19.4 hotfix release I just made. You have to enable the anti-bloat plugin, that is default in the next release anyway with `--enable-plugin=anti-bloat`. It also had been observed to cause issues on macOS too. The anti-bloat removes the useless usage of resources package for it, because what they are trying to achieve is absolutely not needed with Nuitka, and they have the standard working code as a fallback.

**Comment by kayhayen** [comment] 2022-01-20 09:24
I think the priority of this issue should be considered extremely high, the corruptive nature of the feature working with fallback has been evident. I have seen also very strange tracebacks that indicate programming errors in the traceback with th ".0" release of 3.10, this is very much to be avoided as an issue.

**Comment by kayhayen** [comment] 2022-05-15 07:41
This is on develop branch and will be in 0.8 release

**Comment by kayhayen** [comment] 2022-05-20 14:37
Part of 0.8 release that I just made.

**Closed by kayhayen** 2022-05-20 14:37 UTC
Labels: bug, develop
