### ISSUE TITLE
Manual copying of modules into dist folder is not supported

### ISSUE THREAD

**Issue by needones** [Nuitka/Nuitka#1987] opened 2023-01-09 09:10 UTC
* env
  nuitka:1.3.3
  full Python: python 3.9.13 with Anaconda, 
  Flavor: CPython Official
  Executable: C:\tools\Anaconda3\envs\visage\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C\tools\Nuitka\gcc\x86_64\11.3.0-14.0.3-10.0.0-msvcrt-r3\mingw64\bin\gcc.exe

* pip
  addict==2.4.0
altgraph==0.17.3
asteval==0.9.27
async-generator==1.10
attrs==22.1.0
boltons==21.0.0
Brotli==1.0.9
cairocffi==1.4.0
CairoSVG==2.5.2
certifi @ file:///C:/b/abs_ac29jvt43w/croot/certifi_1665076682579/work/certifi
cffi==1.15.1
chardet==3.0.4
charset-normalizer==2.1.1
click==7.1.2
colorama==0.4.5
commonmark==0.9.1
contourpy==1.0.6
cssselect2==0.7.0
cx-Freeze==6.13.1
cx-Logging==3.1.0
cycler @ file:///C:/Users/need/Downloads/cycler-0.11.0-py3-none-any.whl
Cython==0.29.32
defusedxml==0.7.1
dill==0.3.6
exceptiongroup==1.0.0rc9
Flask-SQLAlchemy==2.5.1
fonttools==4.37.4
funcsigs==1.0.2
future==0.18.2
gevent==22.10.2
grade==3.0.1
greenlet==2.0.1
h11==0.14.0
html2text==2020.1.16
html5lib==1.1
iconify==0.0.103
idna==2.10
importlib-metadata==5.0.0
Jinja2==3.1.2
joblib==1.2.0
jsonschema==4.16.0
kids.cache==0.0.7
kiwisolver==1.4.4
libsass==0.21.0
lief==0.12.3
lmfit==1.0.3
loguru==0.6.0
Markdown==3.4.1
MarkupSafe==2.1.1
matplotlib==3.6.2
minio==7.1.12
mongoengine==0.23.1
mpmath==1.2.1
multiprocess==0.70.14
networkx==2.8.7
Nuitka @ file:///C:/%E8%BF%85%E9%9B%B7%E4%B8%8B%E8%BD%BD/Nuitka-1.3.3.tar.gz
numpy==1.19.5
ordered-set==4.1.0
outcome==1.2.0
packaging==21.3
pandas==1.4.4
pdfkit==1.0.0
pefile==2022.5.30
Pillow==9.2.0
pycparser==2.21
pydyf==0.5.0
Pygments==2.13.0
pyhtml2pdf==0.0.5
pyinstaller==5.0
pyinstaller-hooks-contrib==2022.13
pymongo==3.12.3
pyparsing==3.0.9
pyphen==0.13.0
pyrsistent==0.18.1
PySide6==6.4.0.1
PySide6-Addons==6.4.0.1
PySide6-Essentials==6.4.0.1
PySocks==1.7.1
python-dateutil==2.8.2
python-dotenv==0.21.0
pytz==2022.4
PyVISA==1.11.3
pywin32==305
pywin32-ctypes==0.2.0
PyYAML==6.0
pyzmq==24.0.1
QDarkStyle==3.1
qt-material==2.12
QtPy==2.3.0
qtsass==0.3.2
qutip==4.7.0
railroad==0.5.0
requests==2.28.1
rich==12.6.0
scikit-learn==1.0.2
scipy==1.7.3
selenium==4.5.0
shiboken6==6.4.0.1
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
sympy==1.11.1
threadpoolctl==3.1.0
tinyaes==1.0.4
tinycss2==1.1.1
toolz==0.12.0
tqdm==4.64.1
trio==0.22.0
trio-websocket==0.9.2
typing_extensions==4.4.0
uncertainties==3.1.7
urllib3==1.25.11
weasyprint==56.1
webdriver-manager==3.8.3
webencodings==0.5.1
win32-setctime==1.1.0
wincertstore==0.2
wsproto==1.2.0
zipp==3.8.1
zope.event==4.6
zope.interface==5.5.2
zopfli==0.2.1

* after compiling with this command

  nuitka --mingw64 --standalone --show-progress --show-memory "
              "--enable-plugin=pyside6 --nofollow-import-to=numpy,pandas,zmq,cffi,tkinter,matplotlib,mpl_toolkits,"
              "sympy,scipy,minio,yaml,sklearn,jsonschema,pyvisa,lmfit,qutip,loguru,rich,tqdm,networkx,markdown,"
              "pdfkit,requests,pyrsistent,jinja2,urllib3,zopfli,qtpy,qt_material,pytz,PIL,idna,kiwisolver,"
              "dateutil,pyparsing,packaging,email,http,attr,qdarkstyle,typing_extensions,pymongo,mongoengine,"
              "*.tests,*.example,*.examples,*.__pycache__ --include-module=PySide6.QtOpenGL,bson "
              "--windows-icon-from-ico=./package_data/favicon.ico "
              "--output-dir=build2 ./main_gui.py
* run main_gui.exe
C:\tools\projects\debug\pyqcat-visage\build2\0109_1618>main_gui.exe
Traceback (most recent call last):
  File "C:\tools\projects\debug\PYQCAT~1\build2\0109_1~1\main_gui.py", line 4, in <module>
  File "C:\tools\projects\debug\PYQCAT~1\build2\0109_1~1\pyqcat_visage\backend\backend.py", line 17, in <module pyqcat_visage.backend.backend>
  File "C:\tools\projects\debug\PYQCAT~1\build2\0109_1~1\pyQCat\__init__.py", line 57, in <module pyQCat>
  File "C:\tools\projects\debug\PYQCAT~1\build2\0109_1~1\pyQCat\acquisition\__init__.py", line 27, in <module pyQCat.acquisition>
  File "C:\tools\projects\debug\PYQCAT~1\build2\0109_1~1\pyQCat\acquisition\acquisition.py", line 23, in <module pyQCat.acquisition.acquisition>
  File "C:\tools\projects\debug\pyqcat-visage\build2\0109_1618\matplotlib\pyplot.py", line 60, in <module>
    from matplotlib.figure import Figure, FigureBase, figaspect
  File "C:\tools\projects\debug\pyqcat-visage\build2\0109_1618\matplotlib\figure.py", line 26, in <module>
    from matplotlib import _blocking_input, backend_bases, _docstring, projections
  File "C:\tools\projects\debug\pyqcat-visage\build2\0109_1618\matplotlib\projections\__init__.py", line 58, in <module>
    from mpl_toolkits.mplot3d import Axes3D
ModuleNotFoundError: No module named 'mpl_toolkits.mplot3d'

* Scenario Description

mpl_toolkits are a sub package of matplotlib. Installing a new version of matplotlib will automatically install mpl_toolkits.

mpl_toolkits  is used in a script（as: from mpl_toolkits import axes_grid1）
after compiled, I will copy directories mpl_toolkits and matplotlib and other package to the compiled directory,then run main_gui.exe.will get a errror: No module named 'mpl_toolkits.mplot3d'.

if add "from mpl_toolkits import mplot3d, axisartist, axes_grid1" to main_gui.py, it will be pack mpl_toolkits to main_gui.exe, after compilation, it can be started normally. However, there are some compatibility problems when using matplotlib. For example, using FigureCanvasQTAGg (from matplotlib. backends. backend_qt5agg import FigureCanvasQTAGg) will cause page stuttering.There is no such problem when using source code. 
There is no such problem when I pack mpl_toolkits and matplotlib into  main_gui.exe,but it will cost much time.

**Comment by kayhayen** [comment] 2023-01-09 10:23
Manual copying of modules is not support at all, and not nearly expected to work.

**Comment by kayhayen** [comment] 2023-03-12 18:58
Seems I forgot to close this, will even delete it now, because it has no value, never had a reproducer provided.

**Closed by kayhayen** 2023-03-12 18:58 UTC
Labels: invalid, unsupported
