### ISSUE TITLE
"ELF" error when running compiled Django code

### ISSUE THREAD

**Issue by rroblf01** [Nuitka/Nuitka#3139] opened 2024-10-03 05:58 UTC
OS: Docker python:3.12.7-slim-bookworm
Python version: 3.12.7
Nuitka version: 2.4.8

pip list:
```
root@18007f21e0a5:/djangocompile# python -m pip list -v
Package     Version Location                                Installer
----------- ------- --------------------------------------- ---------
asgiref     3.8.1   /usr/local/lib/python3.12/site-packages pip
Django      5.1.1   /usr/local/lib/python3.12/site-packages pip
gunicorn    23.0.0  /usr/local/lib/python3.12/site-packages pip
Nuitka      2.4.8   /usr/local/lib/python3.12/site-packages pip
ordered-set 4.1.0   /usr/local/lib/python3.12/site-packages pip
packaging   24.1    /usr/local/lib/python3.12/site-packages pip
pip         24.2    /usr/local/lib/python3.12/site-packages pip
sqlparse    0.5.1   /usr/local/lib/python3.12/site-packages pip
zstandard   0.23.0  /usr/local/lib/python3.12/site-packages pip
```

- How did you install Nuitka and Python
```
pip install nuitka
```

- The specific PyPI names and versions
```
pip --version
pip 24.2 from /usr/local/lib/python3.12/site-packages/pip (python 3.12)
```

I created a clean Django project with
django-admin startproject djangocompile

and after compiling it with nuitka, I can use the shell, but I can't run the runserver

```
root@18007f21e0a5:/djangocompile# nuitka manage.py 
Nuitka-Options: Used command line options: manage.py
Nuitka-Options:WARNING: You did not specify to follow or include anything but main program. Check options and make sure that is intended.
Nuitka: Starting Python compilation with Nuitka '2.4.8' on Python '3.12' commercial grade 'not installed'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 12).
Nuitka-Scons: Backend linking program with 7 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka: Keeping build directory 'manage.build'.
Nuitka: Successfully created 'manage.bin'.
root@18007f21e0a5:/djangocompile# ./manage.bin runserver 0.0.0.0:8000
  File "/djangocompile/manage.bin", line 1
    ELF
SyntaxError: source code cannot contain null bytes
root@18007f21e0a5:/djangocompile# ./manage.bin shell
Python 3.12.7 (main, Oct  1 2024, 22:28:49) [GCC 12.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from django.utils import timezone
>>> timezone.now()
datetime.datetime(2024, 10, 3, 5, 49, 22, 844005, tzinfo=datetime.timezone.utc)
```

**Comment by kayhayen** [comment] 2024-10-04 09:40
There is module parameters for Django, that you didn't get errors for, but I did, which is a bit confusing to me. I fixed those up, so it ran without providing the settings module, but obviously won't include anything in that case, and when adding the module parameter, I get this now:

```
Nuitka: Successfully created 'manage.dist/manage.bin'.
Nuitka: Launching 'manage.dist/manage.bin'.
Traceback (most recent call last):
  File "/home/hayen/test/djangocompile/manage.dist/manage.py", line 22, in <module>
  File "/home/hayen/test/djangocompile/manage.dist/manage.py", line 18, in main
  File "/home/hayen/test/djangocompile/manage.dist/django/core/management/__init__.py", line 442, in execute_from_command_line
  File "/home/hayen/test/djangocompile/manage.dist/django/core/management/__init__.py", line 416, in execute
  File "/home/hayen/test/djangocompile/manage.dist/django/__init__.py", line 24, in setup
  File "/home/hayen/test/djangocompile/manage.dist/django/apps/registry.py", line 116, in populate
  File "/home/hayen/test/djangocompile/manage.dist/django/apps/config.py", line 269, in import_models
  File "importlib.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/home/hayen/test/djangocompile/manage.dist/django/contrib/auth/models.py", line 5, in <module django.contrib.auth.models>
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "/home/hayen/test/djangocompile/manage.dist/django/contrib/auth/base_user.py", line 40, in <module django.contrib.auth.base_user>
  File "/home/hayen/test/djangocompile/manage.dist/django/db/models/base.py", line 143, in __new__
  File "/home/hayen/test/djangocompile/manage.dist/django/db/models/base.py", line 371, in add_to_class
  File "/home/hayen/test/djangocompile/manage.dist/django/db/models/options.py", line 231, in contribute_to_class
  File "/home/hayen/test/djangocompile/manage.dist/django/utils/connection.py", line 15, in __getattr__
  File "/home/hayen/test/djangocompile/manage.dist/django/utils/connection.py", line 58, in __getitem__
  File "/home/hayen/test/djangocompile/manage.dist/asgiref/local.py", line 117, in __getattr__
RuntimeError: No active exception to reraise
```

This is a duplicate of an older report, that indeed should be a priority to fix.

**Comment by kayhayen** [comment] 2024-10-04 09:43
Closing this as a duplicate of #2811 as the module parameter is supposed to solve the fact that django changes didn't kick in for you, but maybe it will show once this issue is resolved, but I will keep an eye on that since I will be using it as the test case for that.

It would only happen with Python >3.10 which you are using, so even if I put those module parameter fixes into the 2.4.9 hotfix, without the resolution of that other issue, it's not going to help much.

**Closed by kayhayen** 2024-10-04 09:43 UTC
