### ISSUE TITLE
`zstandard` mandatory in `--onefile` mode

### ISSUE THREAD

**Issue by DervishD** [Nuitka/Nuitka#1444] opened 2022-02-25 12:04 UTC
First of all, sorry for being so noisy but I'm currently testing Python tools to generate executables and so I'm finding these problems rather than looking for them.

* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):
```
0.7.1
Commercial: None
Python: 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\rauln\Desktop\vsm\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```

* How did you install Nuitka and Python

Nuitka installed using `pip install nuitka` on virtualenv.

* The specific PyPI names and versions
```
Nuitka==0.7.1
```
* Many times when you get an error from Nuitka, your setup may be special

 `print('hello world`) fails, too.

* Provide in your issue the Nuitka options used

`python -m nuitka --onefile test.py`

In `--onefile` mode compression is enabled if `zstandard` is available. Not in the virtualenv I set up, but I thought that since that is not mandatory, compilation would work without it. It doesn't, error below:
```
Nuitka-Options:INFO: Used command line options: --onefile test.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.7.1' on Python '3.9' commercial None.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'socket' added '_socket'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'pathlib' added 'ntpath,posixpath'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'importlib.metadata' added 'email'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'locale' added '_bootlocale'.
Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'encodings' added 'encodings.idna,encodings.base64_codec,encodings.hex_codec,encodings.rot_13'.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Backend linking program (no progress information available).
Nuitka-Scons:INFO: Compiled 10 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 10
Nuitka-Postprocessing:INFO: Creating single file from dist folder, this may take a while.
Nuitka-Onefile:INFO: Running bootstrap binary compilation via Scons.
Traceback (most recent call last):
  File "C:\Users\rauln\Desktop\vsm\venv\lib\site-packages\nuitka\__main__.py", line 137, in <module>
    main()
  File "C:\Users\rauln\Desktop\vsm\venv\lib\site-packages\nuitka\__main__.py", line 123, in main
    MainControl.main()
  File "C:\Users\rauln\Desktop\vsm\venv\lib\site-packages\nuitka\MainControl.py", line 974, in main
    packDistFolderToOnefile(dist_dir, binary_filename)
  File "C:\Users\rauln\Desktop\vsm\venv\lib\site-packages\nuitka\freezer\Onefile.py", line 72, in packDistFolderToOnefile
    packDistFolderToOnefileBootstrap(onefile_output_filename, dist_dir)
  File "C:\Users\rauln\Desktop\vsm\venv\lib\site-packages\nuitka\freezer\Onefile.py", line 392, in packDistFolderToOnefileBootstrap
    compressor_python = getCompressorPython()
  File "C:\Users\rauln\Desktop\vsm\venv\lib\site-packages\nuitka\freezer\Onefile.py", line 313, in getCompressorPython
    compressor_python = findInstalledPython(
  File "C:\Users\rauln\Desktop\vsm\venv\lib\site-packages\nuitka\utils\InstalledPythons.py", line 198, in findInstalledPython
    if candidate.checkUsability(
  File "C:\Users\rauln\Desktop\vsm\venv\lib\site-packages\nuitka\utils\InstalledPythons.py", line 79, in checkUsability
    self._exec(code=test_code, context={"catch_print": catch_print})
  File "C:\Users\rauln\Desktop\vsm\venv\lib\site-packages\nuitka\utils\InstalledPythons.py", line 53, in _exec
    exec(code.replace("print", "catch_print"), context)
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'zstandard'
```

I've checked the code and `checkUsability` should just return False instead of throwing an exception, but this may be due to something on my side. Installing `zstandard` on the `virtualenv` solves the issue.

**Comment by kayhayen** [comment] 2022-02-25 13:17
You are correct, this is clearly a bug. The intention is to detect that, but apparently it's not working as intended. Thanks for the report.

**Comment by DervishD** [comment] 2022-02-25 14:17
My pleasure @kayhayen it's the less I can do. I'm liking Nuitka quite a lot, really.

**Comment by kayhayen** [comment] 2022-02-26 09:21
The fix for this is now on factory branch: https://nuitka.net/doc/factory.html it will be in the 0.7.2 hotfix likely

**Comment by joshwolff1** [comment] 2022-02-26 23:47
Same issue - thank you for the post dervishD and thank you for the quick response kayhayen

**Comment by kayhayen** [comment] 2022-03-02 17:44
Part of the current hotfix release.

**Closed by kayhayen** 2022-03-02 17:44 UTC
Labels: bug
