### ISSUE TITLE
QtWebEngineWidgets does implicit imports 

### ISSUE THREAD

**Issue by eeokee** [Nuitka/Nuitka#475] opened 2019-08-01 04:15 UTC
### errors
Traceback (most recent call last):
  File "D:\Workspaces\capital\taoke-client\test.dist\test.py", line 5, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtNetwork'
![image](https://user-images.githubusercontent.com/3079825/62265209-f361bf00-b455-11e9-8dfc-56ef5dbd525a.png)

### env
Windows 10(1903)
Nuitka Stable 0.6.5 x64
Mingw64 8.1(x86_64-win32-seh-rev)
Python 3.7.3 x64
![image](https://user-images.githubusercontent.com/3079825/62265141-84846600-b455-11e9-9294-dee84cc86ca5.png)

### build
C:\Users\eeoke\Envs\taoke\Scripts\python.exe -m nuitka --standalone --plugin-enable=qt-plugins test.py
```
Nuitka:INFO:Injecting plug-in based post load code for module 'PyQt5.QtCore':
Nuitka:INFO:    Setting Qt library path to distribution folder. Need to avoid loading target
Nuitka:INFO:    system Qt plug-ins, which may be from another Qt version.
Nuitka:INFO:Injecting plug-in based pre load code for module 'PyQt5':
Nuitka:INFO:    Adding dist folder to 'PATH' environment variable.
Nuitka:INFO:Copying Qt plug-ins 'iconengines,imageformats,mediaservice,platforms,printsupport' to 'test.dist\PyQt5\qt-plugins'.
Nuitka:INFO:Copying OpenSSL DLLs to 'test.dist'
Nuitka:WARNING:Ignoring conflicting DLLs for 'vcruntime140.dll' and using newest file version.

```
### example
file:test.py
```
# -*- coding: utf-8 -*-
import sys

from PyQt5.QtCore import QUrl
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEngineProfile
from PyQt5.QtWidgets import QApplication, QWidget, QVBoxLayout, QPushButton

class window(QWidget):
    def __init__(self):
        super().__init__()
        self.setup()

    def setup(self):
        self.box = QVBoxLayout(self)
        self.btn_get = QPushButton('click to get cookies')
        self.btn_get.clicked.connect(self.get_cookie)
        self.web = MyWebEngineView()
        self.web.resize(800, 600)
        self.web.load(QUrl("https://www.googles.com"))
        self.box.addWidget(self.btn_get)
        self.box.addWidget(self.web)
        self.web.show()

    def get_cookie(self):
        cookie = self.web.get_cookie()
        print('cookies: ', cookie)

class MyWebEngineView(QWebEngineView):
    def __init__(self, *args, **kwargs):
        super(MyWebEngineView, self).__init__(*args, **kwargs)
        QWebEngineProfile.defaultProfile().cookieStore().cookieAdded.connect(self.onCookieAdd)
        self.cookies = {}

    def onCookieAdd(self, cookie):
        name = cookie.name().data().decode('utf-8')
        value = cookie.value().data().decode('utf-8')
        self.cookies[name] = value

    def get_cookie(self):
        cookie_str = ''
        for key, value in self.cookies.items():
            cookie_str += (key + '=' + value + ';')
        return cookie_str


if __name__ == "__main__":
    app = QApplication(sys.argv)
    w = window()
    w.show()
    sys.exit(app.exec_())
```

**Comment by kayhayen** [comment] 2019-08-04 20:19
Seems `PyQt5.QtWebEngineWidgets` does implicit imports, adding support for them is necessary, and I am currently finding them incrementally. Expect something on factory branch soon.

**Comment by kayhayen** [comment] 2019-08-04 20:22
It seems `QtWebEngineProcess.exe` will still be missing then at run time. We need to figure out, how it is supposed to be located.

**Comment by rimpy-custom** [comment] 2020-01-03 17:06
I have tried to copy-paste QtWebEngineProcess.exe into test.dist next to test.exe and now it gives me next errors: https://i.imgur.com/s79d8SV.png
Strange enough, but my nickname is not "Bob".

**Comment by JorjMcKie** [comment] 2020-01-04 11:31
@kayhayen - I am volunteering to take that one on.

**Comment by JorjMcKie** [comment] 2020-01-06 15:13
I have modified the ``ImplicitImports.py`` module, which makes the example provided above work under Windows - standard Python distributions as well as Anaconda.
Currently cannot test whether that would also work for Linux, but certainly do hope so.
Maybe someone else has an environment at hand.

Anyway, here is the modified plugin for your tests:
[PySidePyQtPlugin.zip](https://github.com/Nuitka/Nuitka/files/4026561/PySidePyQtPlugin.zip)

## Notes
* I have seen the comments about excessive / unnecessary space allocations for locale data.
This mod **_does copy_** those data as well. If really not needed, you can either manually remove the respective subfolder ``dist.PyQt/Qt/translations``, or we might consider a new plugin option.

* PyQt issues some complaint on ``sys.stdout`` concerning, how difficult life is locating those ``*.pak`` files, etc. I have tried a few alternative file locations, but the one suggested by @rimpy-custom (was a big help, thank you!) was the only one which ultimately worked.

Please do let me know your reaction.

**Comment by JorjMcKie** [comment] 2020-01-21 12:26
This bug should be addressed in Nuitka develop 0.6.7rc2.
Can you confirm this?

**Comment by rimpy-custom** [comment] 2020-01-30 11:43
New version 0.6.7 works fine for Windows. Unable to check for linux.

**Comment by JorjMcKie** [comment] 2020-01-30 11:47
Ok, thanks for the feedback.
I suggest we close the issue for now and look at it again when / if problems pop up on other platforms.

**Comment by eeokee** [comment] 2020-01-30 12:10
Ok, thanks

**Comment by rimpy-custom** [comment] 2020-02-01 00:00
I have tried to build a package on linux and got next error:
`/home/paladin/rimpy.dist/QtWebEngineProcess: error while loading shared libraries: libQt5WebEngineCore.so.5: cannot open shared object file: No such file or directory`

libQt5WebEngineCore.so.5 is actually in dist folder, but program do not see it. Looks like other libs not used from dist folder aslo.

ldd ./QtWebEngineProcess
./QtWebEngineProcess: /usr/lib/x86_64-linux-gnu/libQt5Core.so.5: version `Qt_5.13' not found (required by ./QtWebEngineProcess)
	linux-vdso.so.1 (0x00007ffdbe5e0000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f0c2128b000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f0c20b40000)
	libGL.so.1 => /usr/lib/x86_64-linux-gnu/libGL.so.1 (0x00007f0c208b4000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0c20695000)
	libQt5WebEngineCore.so.5 => not found
	libQt5Quick.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5 (0x00007f0c2004c000)
	libQt5WebChannel.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebChannel.so.5 (0x00007f0c1fe2e000)
	libQt5Qml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (0x00007f0c1f831000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f0c1f4a5000)
	libQt5Positioning.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5 (0x00007f0c1f247000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f0c1eebe000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f0c1eb20000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f0c1e908000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f0c1e517000)
	libpng16.so.16 => /usr/lib/x86_64-linux-gnu/libpng16.so.16 (0x00007f0c1e2e5000)
	libharfbuzz.so.0 => /usr/lib/x86_64-linux-gnu/libharfbuzz.so.0 (0x00007f0c1e047000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f0c1de2a000)
	libicui18n.so.60 => /usr/lib/x86_64-linux-gnu/libicui18n.so.60 (0x00007f0c1d989000)
	libicuuc.so.60 => /usr/lib/x86_64-linux-gnu/libicuuc.so.60 (0x00007f0c1d5d2000)
	libdouble-conversion.so.1 => /usr/lib/x86_64-linux-gnu/libdouble-conversion.so.1 (0x00007f0c1d3c1000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f0c1d1bd000)
	libglib-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007f0c1cea6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0c219f4000)
	libGLX.so.0 => /usr/lib/x86_64-linux-gnu/libGLX.so.0 (0x00007f0c1cc75000)
	libGLdispatch.so.0 => /usr/lib/x86_64-linux-gnu/libGLdispatch.so.0 (0x00007f0c1c9bf000)
	libfreetype.so.6 => /usr/lib/x86_64-linux-gnu/libfreetype.so.6 (0x00007f0c1c70b000)
	libgraphite2.so.3 => /usr/lib/x86_64-linux-gnu/libgraphite2.so.3 (0x00007f0c1c4de000)
	libicudata.so.60 => /usr/lib/x86_64-linux-gnu/libicudata.so.60 (0x00007f0c1a935000)
	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007f0c1a6c3000)
	libX11.so.6 => /usr/lib/x86_64-linux-gnu/libX11.so.6 (0x00007f0c1a38b000)
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f0c1a163000)
	libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f0c19f5f000)
	libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f0c19d59000)
	libbsd.so.0 => /lib/x86_64-linux-gnu/libbsd.so.0 (0x00007f0c19b44000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f0c1993c000)

ldd ./rimpy
	linux-vdso.so.1 (0x00007ffccc168000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007fac340eb000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fac33d4d000)
	libpython3.6m.so.1.0 => /home/paladin/rimpy.dist/./libpython3.6m.so.1.0 (0x00007fac336a2000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fac332b1000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fac37494000)
	libexpat.so.1 => /home/paladin/rimpy.dist/./libexpat.so.1 (0x00007fac3307f000)
	libz.so.1 => /home/paladin/rimpy.dist/./libz.so.1 (0x00007fac32e62000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007fac32c43000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007fac32a40000)

**Comment by JorjMcKie** [comment] 2020-02-01 06:01
@rimpy-custom - thanks for that feedback!
I will see to it.

**Comment by rimpy-custom** [comment] 2020-02-01 12:46
I was able to run it but it was a real headache. The problem is when you start moving libs, it looks for libs in other places and that forces you to move other libs. Also it causes you to have a lot of duplicate files. because your main app import module from one directory, but  QtWebEngineProcess needs it in the other.
I gave up to finding out what exactly files needed, so a dirty solution is to copy-paste next folder:
/home/paladin/.local/lib/python3.6/site-packages/PyQt5/Qt/lib
/home/paladin/.local/lib/python3.6/site-packages/PyQt5/Qt/libexec
to
dist/PyQt5/Qt/lib
dist/PyQt5/Qt/libexec

/home/paladin/.local/lib/python3.6/site-packages/PyQt5/Qt/translations/qtwebengine_locales/
to
dist/PyQt5/Qt/libexec/qtwebengine_locales

all content from /home/paladin/.local/lib/python3.6/site-packages/PyQt5/Qt/resources
to 
dist/PyQt5/Qt/libexec

and delete QtWebEngineProcess from dist (because it is now in libexec).

After that I was able to run app as intended. But since my app was working with steam workshop, it crashed every time I opened the site. I had to copy-paste the whole content from "steam-runtime.old/amd64/usr/lib/x86_64-linux-gnu/nss/" to dist also. And finally it worked fine.

**Comment by JorjMcKie** [comment] 2020-02-01 12:50
Okay, got it.
Thanks for these valuable information. I will start changing the Qt Plugin to incorporate this.

**Comment by rimpy-custom** [comment] 2020-02-01 13:00
Sorry for such poor presentation of the material. I am novice in linux and python. Hope that information help.

**Comment by JorjMcKie** [comment] 2020-02-01 13:01
> Sorry for such poor presentation of the material. I am novice in linux and python. Hope that information help.

No worries - it does help! Thanks foryour support!

**Comment by rimpy-custom** [comment] 2020-02-01 13:22
Btw, I have found another solution.
You can copy-paste all content from:
`/home/user56/.local/lib/python3.6/site-packages/PyQt5/Qt/lib/`
to 
`dist` (overwriting all duplicates)

and 
`/home/user56/.local/lib/python3.6/site-packages/PyQt5/Qt/translations/qtwebengine_locales`
to
`dist/qtwebengine_locales`

then in the console go to dist folder and run
`chrpath -r . ./QtWebEngineProcess`
to change rpath.

This second method worked for me too but for my particular situation I still needed to copy-paste the whole content from "/home/user56/.local/share/Steam/ubuntu12_32/steam-runtime.old/amd64/usr/lib/x86_64-linux-gnu/nss/" to dist also. Btw I didn't test compiled files (for both methods) on other machine, I have only one linux machine.

**Comment by rimpy-custom** [comment] 2020-07-26 12:05
After extensive testing to run on Linux you need to execute that script from inside `your_standalone_package.dist` folder:
```
import os
import shutil
import subprocess

root_dir = os.getcwd()
subprocess.call("chrpath -r . ./QtWebEngineProcess", shell = True)
shutil.move(os.path.join(root_dir, "PyQt5", "Qt", "translations", "qtwebengine_locales"), root_dir)
shutil.copy2(os.path.join(os.environ["HOME"], ".local", "lib", "python3.6", "site-packages", "PyQt5", "Qt", "lib", "libQt5Core.so.5"), root_dir)
```
Take into account that `python3.6` in the last code instruction depends on your current version of Python. It may be different.

**Comment by kayhayen** [comment] 2020-07-26 15:30
That seems to something that I can include indeed. Using `chrpath` on included binaries is nothing we do so far. In theory it seems like another entry point. Getting that libQt5Core should then be automatic from DLL resolution.

Very nice, but it will be a bit of structural work to get it straight.

**Comment by rimpy-custom** [comment] 2020-07-26 19:05
Just want to make it clear.
`your_standalone_package.dist` had libQt5Core after nuitka finished building `.dist` folder. It had the same size as `.local/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5` but manually replacing it , solved start up issues. Maybe it is problem in my setup of PyQt or maybe nuitka copied other version, cannot say exactly. But that operation was needed to run compiled program.

In testing I have found that QtWebEngineProcess has rpath = /../libs so by default it needs next structure:
```
libs
your_standalone_package.dist
```
Since nuitka already copied all libs next to QtWebEngineProcess, settings rpath to `.` forces it to load libs from `your_standalone_package.dist`. I am novice in that, but mentioned operations fixed compiled program and made it usable.
Thank you for your time and that great tool!

**Comment by kayhayen** [comment] 2020-07-27 14:46
Not sure why that is, Nuitka does its own chrpath on the libs, which might make them unusable. But you gave a reproducer, so it's probably going to be possible to tell. However, this is probably not immediately.

**Comment by kayhayen** [comment] 2021-12-15 19:12
The Qt webengine support has been perfected with the last release and should be perfect now, for Windows and Linux.

**Closed by kayhayen** 2021-12-15 19:12 UTC
Labels: bug, delayed
