### ISSUE TITLE
Stuck in Pass 1 with "Not finished with the module due to following change kinds: new_expression"

### ISSUE THREAD

**Issue by thesct22** [Nuitka/Nuitka#1953] opened 2022-12-21 17:12 UTC
## Nuitka Version

```
1.4rc1
Commercial: None
Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Soultion-Applications\test\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\cl.exe (cl 14.2).
```

## Modules

```
ansys-api-platform-instancemanagement==1.0.0b3
ansys-platform-instancemanagement==1.0.2
googleapis-common-protos==1.57.0
grpcio==1.51.1
importlib-metadata==5.2.0
Nuitka==1.4rc1
orderedset==2.0.3
protobuf==3.20.3
protoc-gen-swagger==0.1.0
zipp==3.11.0
```

```
pip install ansys-platform-instancemanagement
```

## Command used

```
nuitka --standalone --show-progress .\main.py
```

## Code

```python
import ansys.platform.instancemanagement as pypim
print(pypim.__version__)
```

## Issue

>Used to work in 1.3rc6. Does not work in 1.3rc9.

Continuously shows `Nuitka-Progress:INFO: Not finished with the module due to following change kinds: new_expression` and does not progress.

The import never completes and just goes on printing above statement due to --show-progress. Without --show-progress just stuck in Pass 1.

**Comment by kayhayen** [comment] 2022-12-21 18:04
Looks like a serious regression of 1.3 then, which is now stable release. It's fixed on factory right now, but I am making a 1.3.1 release immediately too.

**Comment by thesct22** [comment] 2022-12-22 15:06
Working on factory 1.4rc2 now. Thanks

**Comment by kayhayen** [comment] 2022-12-22 20:08
Part of the 1.3.1 release I made.

**Closed by kayhayen** 2022-12-22 20:08 UTC
Labels: bug
