### ISSUE TITLE
PySide6 - signal connections of type=`Qt.ConnectionType.QueuedConnection` not working for objects that were moved between different `QThread`s. 

### ISSUE THREAD

**Issue by pavlutom** [Nuitka/Nuitka#2773] opened 2024-03-17 11:40 UTC
- Nuitka version, full Python version, flavor, OS, etc.: 

  > .\venv\Scripts\python -m nuitka --version

```
2.1.2
Commercial: None
Python: 3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Work\experiments\pyside_signal_test\venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.31.31103\bin\Hostx64\x64\cl.exe (cl 14.3).
```
Although I noticed the same issue when using Nuitka 2.0.3, and it is also happening on RHEL, so I don't think the problem is platform-dependent.

- How did you install Nuitka and Python

Nuitka is installed into venv using pip, as well as all the other packages.

- The specific PyPI names and versions

  > python -m pip freeze

```
Nuitka==2.1.2
ordered-set==4.1.0
PySide6==6.6.2
PySide6_Addons==6.6.2
PySide6_Essentials==6.6.2
shiboken6==6.6.2
zstandard==0.22.0
```
The problem was also present when using PySide 6.5.

- Many times when you get an error from Nuitka, your setup may be special

Below I provide the minimal example to reproduce the issue I was able to create. The issue is that when running the code directly, the receiver is invoked as expected after the button is clicked (see output 1), however when compiled with Nuitka, the receiver is not invoked at all (output 2). When not compiled, changing the connection type to either `Qt.ConnectionType.AutoConnection`, `Qt.ConnectionType.DirectConnection` or `Qt.ConnectionType.QueuedConnection` doesn't really matter, the receiver is invoked every time. When compiled, the receiver is invoked only with ``Qt.ConnectionType.DirectConnection`. Honestly, I'm not 100% sure which is the correct behaviour according to the PySide6 docs, but Nuitka is definitely not behaving the same as CPython. Also, I would say this is a regression, behavior with Nuitka 1.9.7 is the same as CPython, which I would expect. The problem started with Nuitka 2.0.0.

The issue only happens when the emitter/receiver object (may or may not be the same object, doesn't matter) is created on a worker thread in a way described by the `create_in_parent_thread` classmethod. When created directly on the main thread, everything seems to work normally.

- Also supply a Short, Self Contained, Correct, Example

Self-contained example:
```python
import sys

from PySide6.QtCore import QThread, QObject, Signal, Qt
from PySide6.QtWidgets import QApplication, QPushButton


def thread_id(thread: QThread) -> str:
    return str(id(thread))[-4:]


def current_thread_id() -> str:
    return thread_id(QThread.currentThread())


class TestObject(QObject):
    bridge: "Bridge"

    test_signal = Signal()

    def __init__(self, parent, bridge: "Bridge"):
        super().__init__(parent)

        self.bridge = bridge
        self.test_signal.connect(self.receiver, Qt.ConnectionType.QueuedConnection)
        print("TestObject thread on creation", thread_id(self.thread()))

    @classmethod
    def create_in_parent_thread(cls, parent: QObject, *args, **kwargs) -> "TestObject":
        inst = cls(None, *args, **kwargs)
        inst.moveToThread(parent.thread())
        inst.setParent(parent)
        return inst

    def emit_signal(self):
        print("---- SENDER", current_thread_id())
        print("TestObject thread on test", thread_id(self.thread()))
        self.test_signal.emit()

    def receiver(self):
        print("---- RECEIVER", current_thread_id())


class LoaderThread(QThread):
    bridge: QObject

    def __init__(self, parent: QObject, bridge: QObject):
        super().__init__(parent)
        self.bridge = bridge

    def run(self):
        self.bridge.test_obj = TestObject.create_in_parent_thread(self.bridge, self.bridge)


class Bridge(QObject):
    test_obj: "TestObject"

    def __init__(self, parent):
        super().__init__(parent)

        print("MAIN THREAD", thread_id(QApplication.instance().thread()))

        thr = LoaderThread(self, self)
        print("LOADER THREAD", thread_id(thr))

        thr.start()

    def on_button(self, *args, **kwargs):
        print("!! button clicked")
        self.test_obj.emit_signal()


if __name__ == "__main__":
    app = QApplication(sys.argv)

    brigge = Bridge(app)

    button = QPushButton("test")
    button.clicked.connect(brigge.on_button)
    button.show()

    app.exec()
```

Test scenario:
- run the program, a window with a single button opens
- click the button
- signal is emitted, receiver should be invoked
- close the window, process finishes with exit-code 0

Output 1 (not compiled, expected behavior); Nuitka<=1.9.7:
```
MAIN THREAD 1248
LOADER THREAD 1440
TestObject thread on creation 1440
!! button clicked
---- SENDER 1248
TestObject thread on test 1248
---- RECEIVER 1248
```
  exit code is 0

Output 2 (compiled with Nuitka, receiver not invoked); Nuitka>=2.0.0:
```
MAIN THREAD 4880
LOADER THREAD 5008
TestObject thread on creation 5008
!! button clicked
---- SENDER 4880
TestObject thread on test 4880
```
  exit code is 0
  
Problem - with Nuitka 2.0.0 and later, the receiver is not invoked.

- Provide in your issue the Nuitka options used

```
.\venv\Scripts\python -m nuitka main.py --standalone --enable-plugin=pyside6
```

- Note if this is a regression

Yes, problem started with version 2.0.0. Version 1.9.7 is working correctly.

**Comment by pavlutom** [comment] 2024-03-17 11:48
BTW, as a workaround, I'm just using `Qt.ConnectionType.DirectConnection` as in many cases it doesn't matter much which one I use. However, in some cases it does, and also the AutoConnection, which is the default value, probably results in QueuedConnection, causing this problem.

That's how I discovered the issue - I was not explicitly stating the connection type, hence using the default value (AutoConnection). After upgrading Nuitka from 1.5.6 to 2.0.3, bugs in my application caused by this issue appeared.

**Comment by kayhayen** [comment] 2024-03-18 13:15
The use of 2.0.3 is strange, but I have to confirm that it's present in develop and probably 2.1.2 as well. I can bisect it, but it seems there is some of the fixes made it it in the meantime required, so it's a bit wonky. This area has seen a bunch of fixes, sometimes with regressions. Nuitka does the default automatically there for type to `AutoConnection`, which is supposed to be the default value, and works for some versions, so hopefully that has nothing to do with it.

**Comment by kayhayen** [comment] 2024-03-18 13:31
So, for bisection this was too hard.

Removing this bit from the package configuration restores your behavior:

```
                      if not slot.im_func.__name__.startswith("_pyside6_workaround_"):
                        slot.im_func.__name__ = "_pyside6_workaround_" + slot.im_func.__name__
```

However, this feels very much needed. I feel stuck in a workaround trap. Apparently the `__name__` is being used by PySide to identify the slot in its base class, and with that failing, I seem to remember, I might have seen code that does then just use what it has. So that workaround cannot remain. However, for names like `update` or `run` it fails to do the proper thing, and then finds the wrong slot.

Renaming it is apparently something that would also have to happen in its class, such that it will then work I will try and explore that option, adding a name to the class, might be the solution for both.

**Comment by kayhayen** [comment] 2024-03-18 13:44
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2024-03-18 13:46
I confused myself with 2.1 vs. 2.0.3 there, you had confirmed it's already bad today. In the 2.0.x series a bunch of hotfixes were made, to address issues like wrong argument names, and the name collision and that causing segfaults if done on just anything, etc. this has been a hot area since 1.9.x days, but I guess, we got all things covered again. This will likely arrive in a hotfix really soon now.

**Comment by pavlutom** [comment] 2024-03-19 14:28
@kayhayen Just tested Nuitka 2.2rc2 (factory), the example is working correctly I think. Thanks for the quick fix! :)

**Comment by kayhayen** [comment] 2024-03-22 08:54
This part of the 2.1.3 release I just made.

**Closed by kayhayen** 2024-03-22 08:54 UTC
Labels: bug, factory, excellent_report
