### ISSUE TITLE
[0.6.9.x] multiprocessing workers crash with access violation

### ISSUE THREAD

**Issue by fireundubh** [Nuitka/Nuitka#867] opened 2020-10-26 01:07 UTC
Something changed between `0.6.8.4` and `0.6.9.1` that causes `multiprocessing` workers to crash with an access violation. These crashes only occur when running the program with a Nuitka-compiled binary. When running through the Python interpreter, the program works correctly.

With Python 3.8.6, I tested all versions in the `0.6.9.x` series. The last working version was `0.6.8.4`.

I was able to capture some crash info with DebugDiag.

![2020-10-25 17_58_53](https://user-images.githubusercontent.com/1261664/97124062-db75fb00-16eb-11eb-84b8-297d316dd462.jpg)

Call | Arg 1 | Arg 2 | Arg 3 | Arg 4
:--- | :--- | :--- | :--- | :---
python38!PyObject_LookupAttr+16 | 0007ffa`9c8ab6b0 | 0000000`00000001 | 35811ec`738ca000 | 0000265`a5ad7558
python38!PyObject_HasAttr+e | 0004978`90ec1c69 | 0000000`00000000 | 0000265`a5ace330 | 0007ff7`8b62662d
pyro+725c | 0000000`00000000 | 0000000`00000000 | 0000000`00000000 | 00000f5`1f9faae9
pyro+19ab97 | 0000265`a5d60d60 | 0000265`a5d60d60 | 0007ffa`9c8a8530 | 0007ffa`9c8aa810
pyro+2b5ba7 | 0000265`a5d60d60 | 0007ffa`9c8a8530 | 0000000`00000645 | 0000000`00000000
pyro+2b662d | 0000265`a5d59950 | 0000265`a5d89860 | 0000265`a5d89860 | 00000f5`1f9fac38
pyro+1cb7a4 | 0000265`a5d914f0 | 0000000`00000000 | 0000000`00000000 | 0000000`00000000
pyro+2b5be9 | 0000265`a5b1a710 | 0000265`a5d76ec0 | 0000265`a5d5af80 | 0000000`00000000
pyro+1ecf09 | 0000000`00000000 | 0007ff7`8b660df0 | 0000000`00000000 | 0000000`00000000
pyro+2bf2e4 | 0000265`a4d2be50 | 0000265`a33a4b30 | 00000f5`1f9fb780 | 0007ffa`9c8a8530
pyro+2bea16 | 0000265`a5a3a930 | 0000265`a5a3b430 | 0000000`00000000 | 0007ff7`8b669708
pyro+2be618 | 0000265`a4d2be50 | 0000265`a4c9bdf0 | 0000265`a5a7bdd0 | 0000265`a5ac8220
python38!PyCFunction_Call+7c | 0000000`00000000 | 00000f5`1f9fb910 | 0007ffa`9c56d048 | 0000265`a5a3b430
python38!PyEval_EvalFrameDefault+3b62 | 0000000`00000002 | 0000265`a5a7bdd0 | 0000000`00000001 | 0000265`a5a7ddf8
python38!PyEval_EvalFrameDefault+1784 | 0007ffa`9c8aae90 | 0000265`a5a7dc40 | 0000000`00000002 | 0000265`a5a095c8
python38!PyEval_EvalFrameDefault+1784 | 0000265`a4c8f9c0 | 0000000`00000002 | 0000000`00000002 | 00000f5`1f9fc0d0
python38!PyFunction_Vectorcall+dd | 0000000`00000000 | 0007ffa`9c551098 | 0007ffa`9c8bc9e0 | 0000000`000000ff
python38!PyObject_CallMethodObjArgs+487 | 0000265`a4cae3a0 | 0007ffa`9c8bc9e0 | 0000265`a31ce570 | 0007ffa`9c8a8880
python38!PyObject_CallMethodIdObjArgs+6c | 0000265`a4c93780 | 0007ffa`9c8bc9e0 | 0000265`a5a3a930 | 0000265`a4c903b0
python38!PyEval_GetBuiltins+111 | 0000000`00000000 | 0000000`00000000 | 0000000`00000000 | 0000265`a5a3a930
python38!PyImport_ImportModuleLevelObject+3da | 0000265`a31ce570 | 0000265`a4c90310 | 00000f5`1f9fc2b0 | 00000f5`1f9fc340
python38!PyContextVar_Set+b1d | 692a1cd`eb3b3400 | 0000265`a4c903b0 | 0007ffa`9c8aae90 | 0000000`00000000
pyro+3331 | 0000265`a5abee50 | 0000000`00000001 | 0000000`00000000 | 0000000`00000000
pyro+2b6e91 | 0000265`a5abee50 | 0000000`00000001 | 0000000`00000001 | 0000000`00000000
pyro+20cc79 | 0000000`00000000 | 0007ff7`8b660fd0 | 0000000`00000000 | 0000000`00000000
pyro+2bf2e4 | 0000265`a4d2be50 | 0000265`a33a4b30 | 00000f5`1f9fccd0 | 0007ffa`9c8a8530
pyro+2bea16 | 0000265`a59e1170 | 0000265`a59dc970 | 0000000`00000000 | 0007ff7`8b669708
pyro+2be618 | 0000265`a4d2be50 | 0000265`a4c9bdf0 | 0000265`a5a09610 | 0000265`a5a3c040
python38!PyCFunction_Call+7c | 0000000`00000000 | 00000f5`1f9fce60 | 0007ffa`9c56d048 | 0000265`a59dc970
python38!PyEval_EvalFrameDefault+3b62 | 0000000`00000002 | 0000265`a5a09610 | 0000000`00000001 | 0000265`a557fdf8
python38!PyEval_EvalFrameDefault+1784 | 0007ffa`9c8aae90 | 0000265`a557fc40 | 0000000`00000002 | 0000265`a57a81e8
python38!PyEval_EvalFrameDefault+1784 | 0000265`a4c8f9c0 | 0000000`00000002 | 0000000`00000002 | 00000f5`1f9fd620
python38!PyFunction_Vectorcall+dd | 0000000`00000000 | 0007ffa`9c551098 | 0007ffa`9c8bc9e0 | 0000000`000000ff
python38!PyObject_CallMethodObjArgs+487 | 0000265`a4cae3a0 | 0007ffa`9c8bc9e0 | 0000265`a31ce570 | 0007ffa`9c8a8880
python38!PyObject_CallMethodIdObjArgs+6c | 0000265`a4c93780 | 0007ffa`9c8bc9e0 | 0000265`a59e1170 | 0000265`a4c903b0
python38!PyEval_GetBuiltins+111 | 0000000`00000000 | 0000000`00000000 | 0000000`00000000 | 0000265`a59e1170
python38!PyImport_ImportModuleLevelObject+3da | 0000265`a31ce570 | 0000265`a4c90310 | 00000f5`1f9fd800 | 00000f5`1f9fd890
python38!PyContextVar_Set+b1d | f1d424f`79605800 | 0000265`a4c903b0 | 0007ffa`9c8aae90 | 0000000`00000000
pyro+3331 | 0000265`a5a29b30 | 0000000`00000001 | 0000000`00000000 | 0000000`00000000
pyro+2b6e91 | 0000265`a5a29b30 | 0000000`00000001 | 0000000`00000001 | 0000265`a4dc4b70
pyro+201691 | 0000000`00000000 | 0007ff7`8b660fb0 | 0000000`00000000 | 0000000`00000000
pyro+2bf2e4 | 0000265`a4d2be50 | 0000265`a33a4b30 | 00000f5`1f9fe230 | 0007ffa`9c8a8530
pyro+2bea16 | 0000265`a57de170 | 0000265`a57d6e20 | 0000000`00000000 | 0007ff7`8b669708
pyro+2be618 | 0000265`a4d2be50 | 0000265`a4c9bdf0 | 0000265`a4dc49f0 | 0000265`a59d69f0
python38!PyCFunction_Call+7c | 0000000`00000000 | 00000f5`1f9fe3c0 | 0007ffa`9c56d048 | 0000265`a57d6e20
python38!PyEval_EvalFrameDefault+3b62 | 0000000`00000002 | 0000265`a4dc49f0 | 0000000`00000001 | 0000265`a58435f8
python38!PyEval_EvalFrameDefault+1784 | 0007ffa`9c8aae90 | 0000265`a5843440 | 0000000`00000002 | 0000265`a4d03be8
python38!PyEval_EvalFrameDefault+1784 | 0000265`a4c8f9c0 | 0000000`00000002 | 0000000`00000002 | 00000f5`1f9feb80
python38!PyFunction_Vectorcall+dd | 0000000`00000000 | 0007ffa`9c551098 | 0007ffa`9c8bc9e0 | 0000000`000000ff
python38!PyObject_CallMethodObjArgs+487 | 0000265`a4cae3a0 | 0007ffa`9c8bc9e0 | 0000265`a31ce570 | 0007ffa`9c8a8880
python38!PyObject_CallMethodIdObjArgs+6c | 0000265`a4c93780 | 0007ffa`9c8bc9e0 | 0000265`a57de170 | 0000265`a4c903b0
python38!PyEval_GetBuiltins+111 | 0000000`00000000 | 0000000`00000000 | 0000000`00000000 | 0000265`a57de170
python38!PyImport_ImportModuleLevelObject+3da | 0000265`a31ce570 | 0000265`a4c90310 | 00000f5`1f9fed60 | 00000f5`1f9fedf0
python38!PyContextVar_Set+b1d | 5deffff`cb7a5000 | 0000265`a4c903b0 | 0007ffa`9c8aae90 | 0000000`00000000
pyro+3331 | 0000000`00000005 | 0000265`a57dcbb0 | 0000265`a57de5e0 | 0000000`00000000
pyro+2b6e91 | 0000000`00000003 | 0000265`a57dcbb0 | 0000265`a57d6e80 | 0000000`00000000
pyro+d5f5 | 0007ff7`8b660090 | 0000265`a57d5e40 | 0000265`a57de130 | 0007ff7`8b660090
pyro+2bf2e4 | 0007ff7`8b646fd8 | 0007ff7`8b62e6df | 0000265`a57d5e40 | 0000000`00000004
pyro+2bea16 | 0000265`a3198790 | 0000000`00000000 | 0000000`00000001 | 0000265`a4d26a30
pyro+2a8e21 | 0000265`a3198790 | 0000000`00000000 | 0000000`00000000 | 0000265`a30300a8
pyro+2c0010 | 0000000`00000000 | 0000000`00000000 | 0000000`00000000 | 0007e11`00000000
kernel32!BaseThreadInitThunk+14 | 0000000`00000000 | 0000000`00000000 | 0000000`00000000 | 0000000`00000000
ntdll!RtlUserThreadStart+21 | 0000000`00000000 | 0000000`00000000 | 0000000`00000000 | 0000000`00000000

![2020-10-25 18_02_39](https://user-images.githubusercontent.com/1261664/97124188-54755280-16ec-11eb-81fa-70a8f88ef585.jpg)

**Comment by kayhayen** [comment] 2020-10-26 11:13
Try this again please with --debug, it seems your stack is missing the debug information from the Nuitka compiled binary.

**Comment by fireundubh** [comment] 2020-10-26 22:36
I ran Nuitka with `--debug` as well as `--debug --unstripped`, but I'm not sure what I'm supposed to see. The dmp looks the same.

If DebugDiag would actually load the python38 PDB, the stack would be more complete, but I'm not sure why it won't.

**Comment by kayhayen** [comment] 2020-10-29 12:49
I am actually more interested in what `pyro.exe` was doing. Ok, you can try the hard way with `--trace-execution`, and past the last lines of the output to the console. It should point us to the Python code that crashes.

**Comment by fireundubh** [comment] 2020-10-31 00:22
Yeah, this *is* the hard way: [pyro-with-multiprocessing-log.zip](https://github.com/Nuitka/Nuitka/files/5468221/pyro-with-multiprocessing-log.zip).

[This is the Python code](https://github.com/fireundubh/pyro/blob/281c2b5760c5b3df47688a8ae5e2eb829a362ed1/pyro/BuildFacade.py#L139) where multiprocessing creates workers:
```python
        elif self.command_count > 0:
            multiprocessing.freeze_support()
            worker_limit = min(self.command_count, self.ppj.options.worker_limit)
            with multiprocessing.Pool(processes=worker_limit,
                                      initializer=BuildFacade._limit_priority) as pool:
                for state in pool.imap(ProcessManager.run_compiler, commands):
                    if state == ProcessState.SUCCESS:
                        self.success_count += 1
                pool.close()
                pool.join()
```
The loop is where processes are crashing. Search for `BuildFacade.py:141` in the log.

From there, I don't understand what's going on. All I know is this branch and Pool works with Nuitka 0.6.8.4 but not 0.6.9.x.

**Comment by kayhayen** [comment] 2020-11-02 13:32
So, this is very interesting. Would you be willing to do a git bisect search with Nuitka git, that would find a guilty commit.

I am most annoyed by the fact, that --debug doesn't find it, but that CPython library crashes. There is only a few instances, where we call the `PyObject_HasAttr()` function. 

a) The attribute check node does, and it is used by complex call helpers, but I don't see `*` or `**` uses there. We probably ought to make our own asserting variant, to catch if this is really it.

b) Python3 classes when being created (the class, not the objects), cause it, but I also don't see this there.

c) The other instance is in importing, the meta path based loader does stuff with checking `__file__` on modules and `__spec__` values, but these seem extremely unlikely to crash.

I am happy with what debug we have off the Python DLL, I am not happy with pyro symbols missing, it somehow seems that when attempting to use the `iter` of `pool.imap(ProcessManager.run_compiler, commands)` it is simply not returning at all, so likely we are not looking at the crash with that code.

What I am going to do now, is to add optimization and checks for our usages of `PyObject_HasAttr` replacing it if a `HAS_ATTR` of our own, that is going to be faster, and makes more checks with `--debug`, so we get it to get an assertion going.

**Comment by kayhayen** [comment] 2020-11-02 14:59
I added the changes to factory branch, which hopefully isn't too unstable, https://nuitka.net/doc/factory.html

**Comment by deajan** [comment] 2020-11-13 10:36
@fireundubh Do you by any chance use the `psutil` module in your code ?

**Comment by fireundubh** [comment] 2020-11-15 02:07
@deajan Yessir.

**Comment by kayhayen** [comment] 2020-11-15 10:31
This is a duplicate of #877 and will be treated in there as it got the better reproducer.

**Closed by kayhayen** 2020-11-15 10:31 UTC
Labels: bug, duplicate
