### ISSUE TITLE
--standalone .exe not doing anything. works fine if not run as --standalone

### ISSUE THREAD

**Issue by jttaggart** [Nuitka/Nuitka#997] opened 2021-02-20 21:17 UTC
Nuitka = 0.612.2
OS = Win 10 64 bit
Python = 3.7
installed in venv with PyCharm

python -m nuitka --windows-disable-console --plugin-enable=multiprocessing --mingw64 SPSS_Data_Editor_v1.0.py

creates .exe which works perfectly.

python -m nuitka --windows-disable-console --plugin-enable=multiprocessing --mingw64 --standalone --plugin-enable=numpy --plugin-enable=qt-plugins SPSS_Data_Editor_v1.0.py

creates .exe in dist folder will dlls, etc. does not do anything when run. no error messages or other output.
what is very strange is when I copied dist folder to another location on my machine and replaced .exe with one generated without --standalone it worked. neither of these attempts worked when I copied to another machine.

**Comment by kayhayen** [comment] 2021-02-20 22:15
Do not disable the console, then you probably get an error, that would be helpful, without console no error can be output.

**Comment by jttaggart** [comment] 2021-02-20 22:44
Got the following:
(DataEditor) C:\Users\johntaggart\Documents\PycharmProjects\DataEditor\SPSS_Data_Editor_v1.0.dist>SPSS_Data_Editor_v1.0.exe
Traceback (most recent call last):
  File "C:\Users\JOHNTA~1\DOCUME~1\PYCHAR~1\DATAED~1\SPSS_D~1.DIS\SPSS_Data_Editor_v1.0.py", line 29, in <module>
  File "C:\Users\JOHNTA~1\DOCUME~1\PYCHAR~1\DATAED~1\SPSS_D~1.DIS\pyreadstat\__init__.py", line 17, in <module pyreadstat>
  File "pyreadstat\pyreadstat.pyx", line 1, in init pyreadstat.pyreadstat
ModuleNotFoundError: No module named 'pyreadstat._readstat_writer'

**Comment by kayhayen** [comment] 2021-02-21 09:38
And now guess what I need next? Hint, it's something you deleted from the issue template. I might be line 29 of your program, which is likely an import, and I need you to confirm it has the same issue. :)

**Comment by jttaggart** [comment] 2021-02-21 16:32
import pyreadstat

No surprise there. As I mentioned, it's all good when not run as --standalone.

**Comment by kayhayen** [comment] 2021-02-21 19:25
It's not about the surprive level, it's about me not having to guess, i.e. knowledge level. When trying this, I got another error, where it wants to import pandas.

**Comment by jttaggart** [comment] 2021-02-21 20:42
I'm using pandas 1.2.2

**Comment by gdementen** [comment] 2021-03-18 12:52
seems to be a duplicate of #980

**Comment by gdementen** [comment] 2021-03-18 12:53
@kayhayen and there is a minimal reproducer there

**Comment by kayhayen** [comment] 2021-03-19 15:26
Yes, this is a duplicate indeed, please follow that issue @jttaggart

**Closed by kayhayen** 2021-03-19 15:26 UTC
Labels: needs_example

**Comment by kayhayen** [comment] 2021-03-19 15:28
Also new option of 0.6.13 or higher allows you to force outputs into files, even when not using console, that is also very helpful for debugging. Look for `--windows-force-stdout-spec` and for tracebacks of course esp. `--windows-force-stderr-spec`
