### ISSUE TITLE
jinja2 used by pyexcelerate, how to tweak anti-bloat?

### ISSUE THREAD

**Issue by math-artist** [Nuitka/Nuitka#1317] opened 2021-12-14 22:36 UTC
```
0.6.18.2
Commercial: None
Python: 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 15:37:01) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: C:\Users\jeans\miniconda3\envs\fresh\python.exe
OS: Windows
Arch: x86_64
```

I am using the anti-bloat plugin to make a standalone.

It does this:
`Nuitka-Plugins:INFO: anti-bloat: Handling module 'jinja2.defaults' with 1 change(s) for: remove jinja2 testing framework.
`

but the library pyexcelerate imports jinja2 like this:
`from jinja2 import Environment, FileSystemLoader`

and this happens at runtime:

```
  File "C:\Users\jeans\project\pyexcelerate\__init__.py", line 1, in <module pyexcelerate>
  File "C:\Users\jeans\project\pyexcelerate\Workbook.py", line 2, in <module pyexcelerate.Workbook>
  File "C:\Users\jeans\project\pyexcelerate\Writer.py", line 7, in <module pyexcelerate.Writer>
  File "C:\Users\jeans\project\jinja2\__init__.py", line 8, in <module jinja2>
  File "C:\Users\jeans\project\jinja2\environment.py", line 27, in <module jinja2.environment>
ImportError: cannot import name 'DEFAULT_TESTS' from 'jinja2.defaults' (C:\Users\jeans\project\jinja2\defaults.py)
```

What would be the easiest way to fix this? Is there a simple way to tell anti-bloat to ignore a module?

**Comment by math-artist** [comment] 2021-12-14 22:52
Or is there an option to specify a different config file for anti-bloat instead of using the one in the plugin folder? 

Is that config file maintained to be universal to most projects, or is it intended to be modified on a per-project basis?

**Comment by kayhayen** [comment] 2021-12-15 13:05
@math-artist good old pyexcelerator, or is this another one? Anyway, Nuitka do not offer per project files there, and what you have there, is precisely why it's not yet on by default. I was going to add tags, like this:

```
  control_tags:
    - "allow_ipython"
```

This disables the exclusion of IPython. There is an option `--noinclude-IPython-mode`, but I suspect, that since it's Jinja itself doing it, I guess it might be a case of a missing import.  Would you have a `pyexcelerate` example that I can use to reproduce this one, it seems the anti-bloat removal may just be incomplete for this one, and I don't think Jinja2.testing is wanted ever. Adding an entry for `jinja2.environment` that does it in a PR would of course be even more welcome.

**Comment by befedo** [comment] 2022-02-04 12:18
Hello,

I've been coming directly from #1321 and have anti bloat enabled (`--enable-plugin=anti-bloat`). The missing `DEFAULT_TESTS` error is the same, when using jinja2:
```{text}
Traceback (most recent call last):
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\app.py", line 5, in <module>
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\dash_auth\__init__.py", line 2, in <module dash_auth>
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\dash_auth\plotly_auth.py", line 9, in <module dash_auth.plotly_auth>
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\flask\__init__.py", line 6, in <module flask>
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\flask\json\__init__.py", line 9, in <module flask.json>
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\jinja2\__init__.py", line 8, in <module jinja2>
  File "C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\jinja2\environment.py", line 27, in <module jinja2.environment>
ImportError: cannot import name 'DEFAULT_TESTS' from 'jinja2.defaults' (C:\Users\nuitka\DOCUME~1\build\app\APP~1.DIS\jinja2\defaults.py)
```
#### Nuitka version
```{text}
> python -mnuitka --version
0.6.19.5
Commercial: None
Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
Flavor: Unknown
Executable: C:\Users\nuitka\Documents\build\app\.env\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
```
#### How did you install Nuitka and Python?

I used the python venv module.

#### Nuitka options used
```{text}
python -m nuitka
  --mingw64
  --standalone
  --enable-plugin=anti-bloat
  --no-prefer-source-code
  --plugin-enable=numpy
  --plugin-enable=pylint-warnings
  ... many include module directives ...
  app.py
```

Is there any workaround to get this resolved?


Thanks for your time and best regards
Befedo

**Comment by kayhayen** [comment] 2022-02-07 12:50
I have pushed a fix to the factory branch. My mistaken, I was overeager with removing test frameworks, even ones that are not really such.

**Comment by kayhayen** [comment] 2022-02-14 09:37
Part of the 0.6.19.7 hotfix I made the other day.

**Closed by kayhayen** 2022-02-14 09:37 UTC
Labels: bug
