### ISSUE TITLE
Compile package which has internal .so files, [PIL]

### ISSUE THREAD

**Issue by salembream** [Nuitka/Nuitka#876] opened 2020-11-01 23:34 UTC
Hi,
```
python3.8
nuitka 0.6.9.4
```

I am trying to build the packages I use as standalone object files ".so".
using this command:
`nuitka3 --module ~/path/to/package --include-package=package_name`
it works fine for simple packages.
### issue
now I want to do the same for `PIL` aka "Pillow" package.
but this package has this file `_imaging.cpython-38-x86_64-linux-gnu.so`.
and the output compiled package `PIL.xxx.so` doesn't has it.

this, makes the PIL to raise an error as the missing file is essential to it.
here is how PIL imports it in a module[file].
`    from . import _imaging as core  `

### trials to fix
i've tried adding it using ` --include-module=PIL._imaging` but it didn't work, nuitka shows warning: `Not recursing to unused 'PIL._imaging'`.
tried to add it as implicit-import [modifying the plugin] but also didn't work.
tried to make PIL directory near `PIL.xxx.so` and put the `_imaging.xxx.so` inside it, put the program didn't see it, as it already found the PIL package I think in a form of .so file.
### question
1- how to make `_imaging.xxx.so` file be embedded inside the compile package ? [I think this not reasonable].
2-  if first question not valid, how to make the my program able run and detect the .so file as if is inside the compiled .so package.

**Comment by kayhayen** [comment] 2020-11-02 12:08
This is potentially a duplicate of #870 which is about to be solved, loading of extension modules that are installed, will now work. Packages cannot embedd other extension modules, but if places in the file system, things are going to work as expected, if the sub package is in a directory of the package name near the compiled package.

**Closed by kayhayen** 2020-11-02 12:08 UTC
Labels: duplicate
