### ISSUE TITLE
patched_disconnect() missing 1 required positional argument: 'receiver'

### ISSUE THREAD

**Issue by srikanthravipati** [Nuitka/Nuitka#2636] opened 2024-01-02 14:08 UTC
1.9.6
Commercial: None
Python: 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\Users\User\AppData\Local\Programs\Python\Python311\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.35.32215\bin\Hostx64\x64\cl.exe (cl 14.3).

PySide6 version: 6.6.1

**Short example:**

```
import sys

from PySide6.QtWidgets import QApplication, QMainWindow, QPushButton

class ApplicationWindow(QMainWindow):
    def __init__(self):
        super(ApplicationWindow, self).__init__()

        self.pushbtn = QPushButton("Click Me!!")
        self.setCentralWidget(self.pushbtn)

    def say_hello(self):
        print("Hello")


if __name__ == "__main__":
    qapp = QApplication()

    app = ApplicationWindow()
    app.pushbtn.clicked.connect(app.say_hello)
    app.pushbtn.clicked.emit()
    app.pushbtn.clicked.disconnect()
    app.show()
    sys.exit(qapp.exec())
```

**Output and Error:**
```
Hello
Traceback (most recent call last):
  File "C:\Users\SRIKAN~1\Desktop\NUITKA~1\TEST_Q~1.DIS\test_qt_nuitka.py", line 23, in <module>
TypeError: patched_disconnect() missing 1 required positional argument: 'receiver'
```

**Built via**

`python.exe -m nuitka --standalone --enable-console --remove-output --no-pyi-file --enable-plugin=pyside6 .\test_qt_nuitka.py`

*Could the issue be missing def for disconnect function without any receiver?*
https://github.com/Nuitka/Nuitka/blob/afcf2e82e65686bff273d6805d47103e163213fe/nuitka/plugins/standard/standard.nuitka-package.config.yml#L3449-L3474

**Comment by kayhayen** [comment] 2024-01-02 15:17
I managed to reproduce this strangely, I didn't see the form of disconnect without arguments so far, apparently receiver is optional indeed.

**Comment by kayhayen** [comment] 2024-01-02 15:17
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by srikanthravipati** [comment] 2024-01-02 15:27
This issue is fixed on the factory branch. Thanks @kayhayen for the prompt fix; much appreciated.

**Comment by kayhayen** [comment] 2024-01-09 07:04
Since for 2.0, the code in question was changed, I decided to avoid the merge conflict. It's on develop and will be in 2.0 only.

**Comment by kayhayen** [comment] 2024-01-26 12:58
This is part of the stable release 2.0 that I just made.

**Closed by kayhayen** 2024-01-26 12:58 UTC
Labels: bug, develop
