### ISSUE TITLE
AssertionError: RootWindow_1__globals

### ISSUE THREAD

**Issue by enaix** [Nuitka/Nuitka#2333] opened 2023-07-15 10:39 UTC
Since 1.7 release, compiling my pyqt6 project now throws an error (1.6.6 version works just fine). At the start of the compilation it throws these lines

```
Nuitka-Optimization:WARNING: Problem at
Nuitka-Optimization:WARNING: '/Users/flynn/src/smartwheel-core/src/smartwheel/__main__.py:192'
Nuitka-Optimization:WARNING: with FunctionDef(name='updateIcons', args=arguments(posonlyargs=[],
Nuitka-Optimization:WARNING: args=[arg(arg='self')], kwonlyargs=[], kw_defaults=[], defaults=[]),
Nuitka-Optimization:WARNING: body=[Expr(value=Call(func=Attribute(value=Attribute(value=Name(id='self',
...
```

and crashes with such traceback:

```
Traceback (most recent call last):
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/__main__.py", line 155, in <module>
    main()
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/__main__.py", line 141, in main
    MainControl.main()
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/MainControl.py", line 1095, in main
    _main()
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/MainControl.py", line 955, in _main
    main_module = _createMainModule()
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/MainControl.py", line 249, in _createMainModule
    Recursion.checkPluginSinglePath(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/importing/Recursion.py", line 350, in checkPluginSinglePath
    _addIncludedModule(module)
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/importing/Recursion.py", line 293, in _addIncludedModule
    checkPluginSinglePath(sub_path, module_package=module.getFullName())
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/importing/Recursion.py", line 340, in checkPluginSinglePath
    module = recurseTo(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/importing/Recursion.py", line 87, in recurseTo
    module = _recurseTo(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/importing/Recursion.py", line 45, in _recurseTo
    module = Building.buildModule(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/Building.py", line 1411, in buildModule
    createModuleTree(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/Building.py", line 1127, in createModuleTree
    module_body = buildParseTree(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/Building.py", line 775, in buildParseTree
    result = buildStatementsNode(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 473, in buildStatementsNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/ReformulationClasses.py", line 401, in buildClassNode
    return buildClassNode3(provider, node, source_ref)
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/ReformulationClasses3.py", line 191, in buildClassNode3
    body = buildFrameNode(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 491, in buildFrameNode
    statements = buildNodeList(provider, nodes, source_ref, allow_none=True)
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 361, in buildNodeList
    entry = buildNode(provider, node, node_source_ref, allow_none)
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/TreeHelpers.py", line 315, in buildNode
    result = build_nodes_args3[kind](
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/ReformulationFunctionStatements.py", line 232, in buildFunctionNode
    return _buildBytecodeOrSourceFunction(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/ReformulationFunctionStatements.py", line 178, in _buildBytecodeOrSourceFunction
    globals_ref, locals_ref, tried, final = wrapEvalGlobalsAndLocals(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/tree/ReformulationExecStatements.py", line 64, in wrapEvalGlobalsAndLocals
    globals_keeper_variable = provider.allocateTempVariable(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/nodes/OutlineNodes.py", line 319, in allocateTempVariable
    return self.provider.allocateTempVariable(
  File "/Users/flynn/src/smartwheel-core/venv2/lib/python3.10/site-packages/nuitka/nodes/NodeBases.py", line 588, in allocateTempVariable
    assert full_name not in self.temp_variables, full_name
AssertionError: RootWindow_1__globals
```

* Nuitka version, full Python version, flavor, OS, etc. as output by *this*
  command.

  > python -m nuitka --version

```
1.8rc5
Commercial: None
Python: 3.10.11 (v3.10.11:7d4cc5aa85, Apr  4 2023, 19:05:19) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /Users/flynn/src/smartwheel-core/venv2/bin/python
OS: Darwin
Arch: arm64
Version C compiler: /usr/bin/clang (clang).
```

* How did you install Nuitka and Python

Installed via pip, checked the development version aswell

* The specific PyPI names and versions

  > python -m pip freeze

```
alabaster==0.7.13
Babel==2.12.1
certifi==2023.5.7
charset-normalizer==3.1.0
contourpy==1.0.7
cycler==0.11.0
darkdetect==0.7.1
docutils==0.20.1
fonttools==4.39.4
idna==3.4
imagesize==1.4.1
Jinja2==3.1.2
kiwisolver==1.4.4
MarkupSafe==2.1.3
matplotlib==3.7.1
Nuitka @ https://github.com/Nuitka/Nuitka/archive/develop.zip#sha256=4efe5ed4f12da729eb3be2cac75755286409406a4d4a30556e608ade6b0a64f7
numpy==1.24.3
ordered-set==4.1.0
packaging==23.1
Pillow==9.5.0
py-midi==2.0.1
Pygments==2.15.1
pynput==1.7.6
pyobjc-core==9.1.1
pyobjc-framework-ApplicationServices==9.1.1
pyobjc-framework-Cocoa==9.1.1
pyobjc-framework-Quartz==9.1.1
pyparsing==3.0.9
PyQt6==6.5.0
PyQt6-Qt6==6.5.0
PyQt6-sip==13.5.1
pyqtdarktheme==2.1.0
pyserial==3.5
python-dateutil==2.8.2
python-rtmidi==1.4.9
requests==2.31.0
six==1.16.0
smartwheel-core @ file:///Users/flynn/src/smartwheel-core
snowballstemmer==2.2.0
Sphinx==7.0.1
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
swcolorpicker==1.4.3
urllib3==2.0.3
zstandard==0.21.0
```

Nuitka options:

```
python -m nuitka --standalone --assume-yes-for-downloads --disable-console --macos-create-app-bundle --macos-app-icon=smartwheel/logo.icns --macos-app-name="smartwheel-core" --macos-app-mode=ui-element --include-module=smartwheel --include-module=smartwheel.actions --include-module=smartwheel.backgrounds --include-module=smartwheel.serialpipe --include-module=smartwheel.settings_handlers --include-module=smartwheel.ui --include-module=smartwheel.ui.internal --enable-plugin=pyqt6 --include-data-dir=PyQt6=PyQt6 --include-data-dir=./smartwheel=smartwheel ./main.py
```

Full log file:

[log.txt](https://github.com/Nuitka/Nuitka/files/12061164/log.txt)

**Comment by kayhayen** [comment] 2023-07-15 14:52
So, this is caused by special handling of `@pyqtSlot()` that was introduced, experimentally, and is intended for PyQt5 compatibility improvements. I was not aware PyQt6 uses that still. So, that needs to be dependent on the PyQt5 plugin being active of course then.

However, it seems the re-formulation for wraping eval is also not robust in some way there, using same temporary variable names, which is not good, and another bug, that makes this visible.

**Comment by kayhayen** [comment] 2023-07-16 16:06
This is the minimal example.

```
# nuitka-project: --enable-plugin=pyqt6

@pyqtSlot()
def updateUi():
    pass

@pyqtSlot()
def updateIcons():
    pass
```

For factory and hotfix plan, I changed this to only have effect with pyqt5 or pyqt6 plugin enabled, so we need to do that.

The fix is that a temp scope is needed, so every `wrapEvalGlobalsAndLocals` which is used for the creation of the uncompiled function there, is separate. I need to audit other uses, maybe it ought to allocate one itself, rather than having is passed.

**Comment by kayhayen** [comment] 2023-07-16 16:46
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by enaix** [comment] 2023-07-16 19:52
Thanks! It is now working as expected, indeed

**Comment by kayhayen** [comment] 2023-07-17 05:38
This was also solved with a rebase of `main` and `develop` branches. For PyPI, it's going to be in 1.7.6 hotfix which is coming soon.

**Closed by kayhayen** 2023-07-17 05:38 UTC
Labels: bug, factory

**Comment by kayhayen** [comment] 2023-07-24 07:08
This is part of the hotfix release 1.7.6 that I just made.
