### ISSUE TITLE
Why am I getting: OSError: [WinError 110] The system cannot open the device or file specified

### ISSUE THREAD

**Issue by danieltuzes** [Nuitka/Nuitka#933] opened 2021-01-13 20:29 UTC
I have a too-large-to-touch project, where if I use --follow-imports, the compilation fails with `OSError: [WinError 110] The system cannot open the device or file specified`. If I use `--follow-import-to=my.python.files.path`, or don't use any follow import, then the compilation is successful. Binary file is created even upon fail, but won't do anything. (It runds and closes without any stdout.)

## version
0.6.10.5
Python: 3.6.12 |Anaconda, Inc.| (default, Sep  9 2020, 00:29:25) [MSC v.1916 64 bit (AMD64)]
Executable: C:\Users\uname\.conda\envs\project\python.exe
OS: Windows
Arch: x86_64

Installed it with conda install nuitka, which downloaded Nuitka from a corporate repository. I cannot get newer version of it.

## detailed output of the compilation

```
(project) C:\Users\uname\source\repos\project_dir>nuitka main.py --follow-imports
Nuitka:INFO: Starting Python compilation.
Nuitka-Plugins:WARNING: Use '--plugin-enable=pylint-warnings' for: Understand PyLint/PyDev annotations for warnings.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating C source code for backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: C:\Users\uname\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Compiled 810 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit (direct)': 810
Traceback (most recent call last):
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\main.py", line 196, in <module>
    main()
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\main.py", line 189, in main
    MainControl.main()
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\MainControl.py", line 713, in main
    executePostProcessing()
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\PostProcessing.py", line 228, in executePostProcessing
    lang_id=0,
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\utils\WindowsResources.py", line 263, in addResourceToFile
    closeFileWindowsResources(updatehandle)
  File "C:\Users\uname\.conda\envs\project\lib\site-packages\nuitka\utils\WindowsResources.py", line 182, in _closeFileWindowsResources
    raise ctypes.WinError()
OSError: [WinError 110] The system cannot open the device or file specified.
(project) C:\Users\uname\source\repos\project_dir>
```

**Comment by fleimgruber** [comment] 2021-01-14 07:43
Consider the respective [section](https://nuitka.net/doc/user-manual.html#windows-errors-with-resources) in the User Manual.

**Comment by kayhayen** [comment] 2021-01-14 08:18
Yes, Windows Defender is most likely cause of this.

Nuitka has no good time to know when it can open the binary and modify it after it was built. The moment `link.exe` closes it, leaves a time Windows, where things may or may not work. What is most difficult, os that the closing of the resources seems to be when the actual permissions are checked.

Disabling Windows Defender on your build stages will help your performance anyway, and is therefore recommened. I wonder, if a loop around that code could help. We opened it with exclusive access already, it's kind of surprising that on close, somebody else can be holding it at all. I guess that kind of firewall might have special rights.

**Comment by danieltuzes** [comment] 2021-01-14 11:51
I cannot modify the firewall settings in the corporate environment nor can I turn off any antivirus. Does it mean I cannot use nuitka with `--follow-imports`?

**Comment by kayhayen** [comment] 2021-01-14 17:41
It's unrelated to those options, it's happening sporadically, basically it is a race. If you try it often enough under different load situations, it might work eventually. What I am trying is to add a retry code in the portion of Nuitka that fails there, do it 5 times, waiting a second, hoping for Windows Defender to unlock the file in the mean time.

But for now, you are indeed stuck with this. Few people have this reproducibly it seems.

**Comment by kayhayen** [comment] 2021-01-18 11:36
Like I said, I changed this to a retry with a warning and that should make this obsolete as a question, as that error won't happen anymore, instead it's an enhancement. Not sure if retry will actually help, but at least error text will output what is to be done.

**Closed by kayhayen** 2021-01-18 11:36 UTC
Labels: enhancement
