### ISSUE TITLE
asyncio has memory leak on exceptions

### ISSUE THREAD

**Issue by levesquejf** [Nuitka/Nuitka#593] opened 2019-12-21 21:09 UTC
Release 0.6.5 fixed some issues when asyncio exceptions were triggered (see #165 & #213). The compiled code no longer throw a `RuntimeError` exception however it looks like it is causing a memory leak. The number of objects reported by `gc.get_objects()` is always increasing (same for the RSS memory of the process).

Tested with 0.6.5 and Python 3.7.5. A complete reproducer is available at https://github.com/levesquejf/nuitka-memleak-on-exceptions.

**Comment by kayhayen** [comment] 2019-12-27 09:56
Thanks for the reproducer, I will look into this with priority, now that the release 0.6.6 is finally out.

**Comment by levesquejf** [comment] 2020-02-06 15:15
@kayhayen Any idea of the timeline for a potential fix on this issue? Thank you.

**Comment by levesquejf** [comment] 2020-03-20 11:50
@kayhayen any updates on this issue? We are using some asyncio libraries that heavily use Exceptions which force us to reload the code very often to avoid any crashes. Thanks.

**Comment by kayhayen** [comment] 2020-04-13 08:48
The example code exhibits the catch and swallow of exception as in #667 and I have actually due to doubts of mine, put this into a reference counting test, albeit with raising FileNotFound error instead of even attempting `shutil.rmtree` and this is what happens:

> -simpleFunction10: FAILED 177867 177966 leaked 99
> +simpleFunction10: FAILED 179053 179185 leaked 132

This indicates, that CPython already leaks references (memory?) here, and only that Nuitka is worse. I am trying to figure out, how to improve the example, to maybe get at the bottom, of where Nuitka is worse. With these references, 33, there might be as you illustrate in the other issue ones, that are heavy memory users.

```
def simpleFunction10():
    async def rmtree(path):
        return await asyncio.get_event_loop().run_in_executor(None, sync_rmtree, path)

    def sync_rmtree(path):
        raise FileNotFoundError

    async def execute():
        try:
            await rmtree("/tmp/test1234.txt")
        except FileNotFoundError:
            pass

        return False

    async def run():
        await execute()

    asyncio.get_event_loop().run_until_complete(run())
```

I might also want to dive into `objdump` which seems useful. In the old days, I had code in the reference count checking, that was finding the objects that are new or have different refcounts, and print them, but that has fallen into disrepair. I have no searched a harder to find reference leak issue in a while. Still trying to trim this down to a point, where CPython is good. Because dissecting Nuitka specific from CPython asyncio bugs is going to be annoyingly hard.

**Comment by kayhayen** [comment] 2020-04-13 09:53
I think, I found two things.

The exception in `execute` causes a *loss* of a reference, leading to corruption later on. I couldn't pin point it going to 0, but it goes from 5->4 and increasing max_rounds from 10 to 30, showed Python crashing at program end. A typical sign of this kind of issue. I wish it could be caught in an assertion, but I am sure, puting the objects in a map prevents that from happening potentially, although disabling that didn't help.

My first angle of attack here, is find where we lack checks about object health before using it, in relation to frame objects.

**Comment by kayhayen** [comment] 2020-04-13 10:00
Another thing is, and that's going to be an invasive change, the coroutine locals contain a reference to the future event, it was awaiting. When then the coroutine exits, there is a cyclic dependency between the future even and the coroutine, but the connection to the stack is missing, so it is not recognizable.

In good old fashion, I have annotated my bug, years ago:

```
static long Nuitka_Coroutine_tp_traverse(struct Nuitka_CoroutineObject *coroutine, visitproc visit, void *arg) {
    // TODO: Identify the impact of not visiting owned objects and/or if it
    // could be NULL instead. The "methodobject" visits its self and module. I
    // understand this is probably so that back references of this function to
    // its upper do not make it stay in the memory. A specific test if that
    // works might be needed.
    return 0;
}
```

To be fair, we didn't previously have variables attached to the generator objects and their alikes, for a long time, until we had `goto generators`. Now, it's available and can be implemented and this should solve the issue.

Obviously the reference loss and corruption is more critical and shall be attacked first.

**Comment by kayhayen** [comment] 2020-04-13 14:26
In attempting to isolate the issue, I found that CPython 3.8 is better than the 3.7 I was using in terms of asyncio and reference leaks. There are none with the aforementioned example, and it's a better basis for searching the bug, so I am using this now. Obviously the bug won't be version specific, there is nearly no change for 3.8 for coroutines.

My attempts at making the then visible reference loss and corruption were in vain so far. I only convinced myself that everything is fine, plus it doesn't occur when the problem is not there, i.e. when the exception is incoming directly from the async function, which is outside of it, and shouldn't affect things.

My only explanation for it then being OK, would be that it happens to annul a reference leak with a loss exactly, which is something I sort of suspect to be happening, since a lot of ground is covered with all stable references with this kind of test already.

So I turned to the other suspect, and think I can falsify the C stack argument. The coroutines don't survive, so they do not matter. I added traces to code generation producing this:

> python3.8 bin/nuitka-run --debug Mini.py 
>
> ASYNC_AWAIT: Enter for await exit <compiled_coroutine object execute at 0x7fffbf98bb80>
> ASYNC_AWAIT: Enter for await exit <compiled_coroutine object rmtree at 0x7fffbf98c0f0>
> ASYNC_AWAIT: Enter for await exit <Future pending cb=[_chain_future.<locals>._call_check_cancel() at /opt/python380/lib/python3.8/asyncio/futures.py:357]>
> YIELD FROM RETURNED :<NULL>
> current_exc=<class 'FileNotFoundError'>|FileNotFoundError() <- context <NULL>|<traceback object at 0x7feaccff4c40>
> Coroutine EXCEPTION EXIT: __main__$$$function_1_rmtree$$$coroutine_1_rmtree
> current_exc=<class 'FileNotFoundError'>|FileNotFoundError() <- context <NULL>|<traceback object at 0x7feaccff4d00>
> YIELD FROM RETURNED :<NULL>
> current_exc=<class 'FileNotFoundError'>|FileNotFoundError() <- context <NULL>|<traceback object at 0x7feaccff4d00>
> Coroutine RETURN EXIT: __main__$$$function_3_execute$$$coroutine_1_execute returning False
> YIELD FROM RETURNED :False
> current_exc=<NULL>|<NULL>|<NULL>
> Coroutine RETURN EXIT: __main__$$$function_4_run$$$coroutine_1_run returning None

What we see, is the code descending into 3 compiled awaits, the last one gets the exception and attaches locals to it (problem point potentially) and that is then caught and supposedly released in the other couroutine with the handler, converted to a return, leaving no exception set.

Around here, one of these things must be happening. Locals are leaked, but that would only the `path`, nothing else is attached, and so that can be ruled out. In fact, I am going to remove that argument, then no values are attached to frames. And then there is frames and tracebacks, sometimes activated and reverted when switching context, and connected and released.

There could be a bug with returning from elsewhere into a coroutine. I know that this has special handling. That would mean, we isolated the issue pretty good. And maybe it also would explain the reference loss to `execute`, which was the frame calling initially, but not the last one to call.

I am going to add enhanced tracing to the traceback and exception handling there, then I think this should become more obvious. Unfortunately Python 3.7 had this change with exceptions, and maybe some mistake is hiding in the abstraction for it too.

**Comment by kayhayen** [comment] 2020-04-17 09:43
I have added more and more traces, and what I found, is that Nuitka is indeed not releasing the coroutine in the middle, and does funny things with exceptions, e.g. 

> _Nuitka_Coroutine_throw2 : Leave with value/exception from sending into ourselves: <compiled_coroutine object run at 0x7fffce58d000> (finished)
> closing=(not closing) 
> return_value=<NULL>
> current_exc=<class 'StopIteration'>|None <- context <class 'AttributeError'>|<NULL>

I am currently hunting these down. There is another one, which I suspect to the the FileNotFoundError in the context:

> _Nuitka_Coroutine_send : Leave with exception set <compiled_coroutine object execute at 0x7fffce58dbb0> (finished)
> current_exc=<class 'StopIteration'>|False <- context <class 'type'>|<NULL>

Notice, in both cases, the StopIteration with and without return values, have an exception attached, that doesn't make sense to have. It probably should have been cleared. This not happening should not be able to cause the issue we look at here, but of course it's not optimal and it muddies the water, so this must go now.

**Comment by kayhayen** [comment] 2020-04-17 10:18
Ok, forget about the last thing, this was only a wrong trace. The exception context was printed for non-exception instances, and using corrupted information that is just not true, actually no context is given as it should.

**Comment by kayhayen** [comment] 2020-04-17 10:48
Ok, I think I made an important observation. The code in `_Nuitka_YieldFromPassExceptionTo` is handed an `exception_type, exception_value, exception_tb` set of arguments. In the code path for generator exit, this gets released or used. For uncompiled generators and coroutines, they get released. But for coroutines and coroutines in wrapper objects, they get passed to `_Nuitka_Coroutine_throw2` the deepest layer of throwing an exception. The default, looks up `throw` and releases too.

So the expectation seems to be that `_Nuitka_Coroutine_throw2` is to release these, but it doesn't do this in all cases. In the case of `GeneratorExit` it takes extra references before handing to `_Nuitka_Coroutine_send`, and returning. Even if `_Nuitka_Coroutine_send` were to consume the arguments, that means `_Nuitka_Coroutine_throw2` did not in this instance.

For uncompiled generators and coroutines being yield from, it does not release the values before throwing them into it. So that's not consistent with the above handling.

Now in the non-GeneratorExit code path, when normalizing an exception class, extra references are taken, so are for exception values raised. In case of bad exception types, nothing is released.

Nothing indicates that any code path releases exception values. Instead using `_Nuitka_Coroutine_send` will in fact consume the exception most of the time. Naturally and disappointly, it doesn't do so in error cases.

This seems very inconsistent. What will need to be done now, is to write function documentations for these C functions that make sure of the obligation. The `FileNotFoundError` being raised should then be traced through the code flow and we should see the reference count adhere to our expectations throughout the calls. Due to it not being used elsewhere, at least temporarily, expectations about references to it can be made into assertions.

Getting rid of these inconsistencies should fix the memory leaks we are seeing and more of course, but I guess, it will also cause headaches with crashes until all are sorted out.

**Comment by kayhayen** [comment] 2020-04-17 13:32
So, after working on these for a bit, purely in the code, auditing all paths, the amount of leaked references droped to only 3, down from 30. Unfortunately the coroutine appears to be still among them, as `tp_dealloc` is not getting called for `execute` coroutine still. 

But surely this feels like progress is being made.

**Comment by kayhayen** [comment] 2020-04-17 15:58
For Python3.6 my CI reports a difference of 2 references only compared to the leaks of the standard Python, which might be a hint of some sorts, as we have a few branches only that are different.

**Comment by kayhayen** [comment] 2020-04-18 10:09
After fixing the inconsistencies, what the "explain" mode seems to indicate is that the event handle of asyncio is not released, as is not the compiled coroutine for `execute`, i.e. the one that catches the exception thrown into it during `await`.

I have no evidence of any tracebacks and frames leaking anymore though. But I believe a frame object of the event ought to still exist, so I am not entirely sure how much I can trust the analysis here, as I don't think the later would exist without a frame associated.

I am therefore going to implement a manual registry for the compile object types, so we can tell about remaining objects at program end in a debug mode.

**Comment by kayhayen** [comment] 2020-04-18 10:12
> python3.8 bin/nuitka-run --debug MiniCoroutineLeak.py
> REFERENCE counts at program end:
> active | allocated | released
> Compiled Coroutines: 1 | 3 | 2
> Compiled Coroutines Wrappers: 1 | 2 | 1
> 
> 

So this is for a single run of the problematic code, indeed the one coroutine is never released, and it's referenced by the wrapper object. I just audited its throw path, which should get the exception passed in with a return value as an exception. Looked unsuspicious to me.

**Comment by kayhayen** [comment] 2020-04-18 11:04
And I extended it some more:

> python3.8 bin/nuitka-run --debug MiniCoroutineLeak.py
> REFERENCE counts at program end:
> active | allocated | released
> Compiled Coroutines: 1 | 3 | 2
> Compiled Coroutines Wrappers: 1 | 2 | 1
> Compiled Coroutines AIter Wrappers: 0 | 0 | 0
> Compiled Frames: 4 | 6 | 2 (cache usage may occur)

The compiled frames, each coroutine object, when entered, creates one and keep it around for the next time, so "3 active" ones are really used for caching purposes, but only 2 are released. So this is evidence of the frame of `execute` not being released, which I will have to confirm with a trace.

This narrows down things by a alot. The best theory right now, because compiled coroutine wrappers are supposedly created and owned by asyncio, that the compiled frame holds a reference to the uncompiled frame that ows it, and thus keeps it all alive.

That theory however, does not fit into the 3 leaked references. That would required only these compiled wrapper, compiled coroutine, and compiled frame to live, and nothing more. However, in explain, I saw that the event handle was in fact also a leaked reference. That would then require losses of references, we are not yet aware of.

Yours,
Kay

**Comment by kayhayen** [comment] 2020-04-19 08:24
So, I have made the effort, to add more assertions basically to everything in coroutines, that does of course not trigger, as it will only with reference losses, that I am still not convinced of.

As a next step, I removed the traceback creation from the exception raise in `sync_rmtree` and the adding of the traceback when publishing to the exception handler in `execute` (which should not be done, since the code there, `pass` won't care about it, a missing optimization and one that is actually relatively important), making sure Nuitka creates zero tracebacks for the example code. Obviously the Python code of `asyncio` will do it though, but not reference our frames for that.

That didn't impact the counts above at all. Next up, I will add counts for the cache usage of the cached frames. When a frame raises an exception, it takes ownership of the compiled frame with it along. Therefore, I think the release count ought to be higher. 

Adding tracing to frame caching will also make it recognizable how well frame caching actually works (I think I only manually traced so far, to make sure it meets expectations and gains performance, frame cache misses are extremely detremental to performance). In our example, 4 frames would have to be cached. We have 1 module and 5 functions we run, explaing the allocation of 6 frames (all functions need it, as neither is trivial). So 2 would not be cached, the function that raises, won't do it. I am unsure if the local handling in `execute` should also forbid the caching, in which case it would meet expectations.

But as interesting as this is as a prediction, let me measure it now. :-)

**Comment by kayhayen** [comment] 2020-04-19 08:52
So, these are the functions that actually release cached frames:

`impl___main__$$$function_2_sync_rmtree`
`__main__$$$function_1_rmtree$$$coroutine_1_rmtree_context`

These are function `sync_rmtree` and `rmtree` coroutine, which both let and exception escape, in which cache, the cache reference is released, allowing the release of the frame. This brings us up to this:

> REFERENCE counts at program end:
> active | allocated | released
> Compiled Coroutines: 1 | 3 | 2
> Compiled Coroutines Wrappers: 1 | 2 | 1
> Compiled Coroutines AIter Wrappers: 0 | 0 | 0
> Compiled Frames: 4 | 6 | 2 (cache usage may occur)
> CACHED counts at program end:
> Cached Frames: 3 | 5 | 2`

This is in line, and means that only expected Nuitka frames a alive after program end (the module frame is not considered to be cached as it's only ran once).

**Comment by kayhayen** [comment] 2020-04-21 07:33
I finally found it, and fixed it on factory, in some cases, the yielded from value was not released, causing the coroutine to be unreleased.

Once that was found, it was revealed that a reference was lost. And running the code more than 30 times was going to crash. Adding more traces, and debug handling, etc. revealed that the type of the object pointed to a return value, and low and behold, the handling of the release or passing on of that value was inconsistent too.

The fixes for this code are on factory right now, which is awaiting to become a pre-release as soon as possible, but ought to be usable right now. What's going to happen there is me fixing in-place operations performance regressions, and a solution for missing optimization discovered by the C compiler, now that Nuitka's loop optimization has become good enough to use C types for indicator variables, but not good enough to optimize away the "del" statements we make out of the removed assignments, for some loop forms.

with this the test case works on Python 3.8 and leaks nothing

**Comment by kayhayen** [comment] 2020-04-21 07:42
With this, an added test case leaks nothing on 3.8, one less reference on 3.7, although I cannot make out why, but it's 98 vs. 99 for 3.7, on 3.6 it's 120 vs 121, and for 3.5 it is the other way around 258 vs. 124.

At this time I believe, that 3.8 is the first non-leaking implementation of asyncio in Python, and that 3.7 has mostly irrelevant leaks, most of them point to the same objects. I would therefore recommend to go to Python 3.8 if you can, but I expect 3.6 and 3.7 to be reasonable now. At least Nuitka is not contributing to it. Specifically there are no differences in compiled coroutines for 3.8 and 3.7 at all , and for 3.6 only in code paths not taken.

I have yet to try out your concrete example. I think I came up with one that covers this and your other issue, but proving that is still open. But for now, I am very much convinced that the code in factory is dramatically more correct only. I will turn those concrete examples soon.

**Comment by levesquejf** [comment] 2020-04-21 12:33
@kayhayen Are you sure the factory build is ok? I still have the issue with my reproducer.

**Comment by kayhayen** [comment] 2020-05-01 10:09
I think we discussed this elsewhere, Python 3.7 leaks anyway, and with Python 3.8 and proper testing of the reference counting, it should be good now.

This is now in the latest pre-release, and will soon be released.

**Comment by levesquejf** [comment] 2020-05-02 02:29
@kayhayen Even with Python 3.8.2 and Nuitka 0.6.8rc6, I still have the memory leak.

With Nuitka: +1606 objects
With CPython: +0 object

**Comment by kayhayen** [comment] 2020-05-02 06:43
Ok, this must be due to using standalone, and that changes the interaction there, I will look into it, adding support for the checker tool for using executables and standalone mode, of course uncompiled vs. compiled coroutines might make a difference somewhere.

**Comment by kayhayen** [comment] 2020-05-03 09:08
I managed to reproduce it in standalone mode, which poses a big problem to me, as it's hard to tell, what part is to blame. I am trying bi-sect strategies, where I will try and compile more and more of the used modules, until I achieve the issue.

Using the new `--experimental=report-refcounts` I can see in the final report, that indeed, compiled coroutines are leaked. The test case was removed of `objdump` and `gc` usage and then with a minimal wrapper, applied to the standalone compilation manually:

```
from MiniCoroutineLeak import main
from nuitka.tools.testing.Common import checkReferenceCount
checkReferenceCount(main)
```

For the tooling, I will need a temporary file like this, or some thought I am toying with, an ability to read a program from `stdin`, but I am too lazy right now. Also standalone mode, it is not good for bi-secting, I am probably going to just try and use `--follow-import` options to get rid of it, as it's really slow for me in terms of turnout.

**Comment by kayhayen** [comment] 2020-05-03 09:50
So, this is without standalone, merely `--follow-imports` does this: (with a single call to `http_call` only, as the warm up is done otherwise)

```
main: FAILED 134110 134833 leaked 723
REFERENCE counts at program end:
active | allocated | released
Compiled Coroutines: 40 | 260 | 220
```

I  wonder, if it would be a good idea, to track alive coroutine objects in a dedicated list, just to be able to output them, or if they shouldn't be discoverable from `gc.get_objects` already.  

Also, the numbers output above are mixed. The leaked refcounts is from the last attempt, before and after counts, fully warmed up, the left over refcounts are from all runs, so it won't be 40 from a single iteration, but from 20 rounds, which is how much it tries to warm up, so this must be read as 2 coroutines per run likely.

**Comment by kayhayen** [comment] 2020-05-03 10:55
Ok, the 2 coroutines leaked are `run` and  `ClientSession._request`, and these should talk directly to another, and I believe use a shortcut to throw, that I ought to investigate. I believe that should work, and `http_call` not leaking itself, seems to be correct, but something is astray for sure.

**Comment by kayhayen** [comment] 2020-05-03 17:24
So, I am trying to reduce the test case further, by modifying the aiohttp source code, to more immediately do it, and to be able to extract the behavior pattern. I was not lucky with assuming it's about the `with` statements and a mere async context manager that raises would do.

**Comment by kayhayen** [comment] 2020-05-04 05:42
I am going down function call by function call and try to raise my own `TypeError` in places, but then the problem of unreleased coroutines is immediately gone. But I am approaching the end of the (long) chain it seems. But this async programming style is killing me, never is done anything at all except creating yet another coroutine and awaiting it. :-)

**Comment by kayhayen** [comment] 2020-05-04 07:56
So, I got down to the very bottom, and it's an exception result of an `asyncio` future. This is then of course returned to the compiled coroutines awaiting it, and there are plentry of them on the stack, yet only the one mentioned before, `_request` fails to be released afterwards.

I am removing its code, in an attempt to isolate the construct that fails, because I believe there must be some specific language in there, that makes it do this, but so far I am failing at that.

**Comment by kayhayen** [comment] 2020-05-04 19:35
So it seems, I made a mistake, when reporting the reference counts, after one change, the leaks went down to only one, and hunting that was pointless, because it was just garbage not yet collected. So I was hunting a ghost there. Obviously the standard reference counting procedure does that, but I was not using that, due to its multiple runs.

**Comment by kayhayen** [comment] 2020-05-06 06:29
I have devised a much better method of tracing, and in that, I can see the objects holding the reference to leak. And in that a `compiled_cell` owned by a context manager object owns the reference to the `_request` method. I then added more levels, and believe, I could show that the compiled cell should be owned by a compiled frame, and probably is garbage not collected.

There appears to be some non-determinism, or it's confusion of mine, but I think it depends on when the garbage collector is run (periodically by CPython) and that in turn on the amount of code and loops in Nuitka code. I cannot really explain why the issue sometimes was not visible when I changed code in aiohttp, but reverted to always when I undid them.

However, adding proper `tp_visit` implementation to coroutines and to frames, I now had full success, and these coroutines got deleted indeed. Both the one for `run` and for `_request`. The first one, I think I saw was owned by the task frame of `asyncio`, which is uncompiled, but couldn't see through the coroutine enough to know it's unused.

Potentially tracebacks are causing these reference count cycles. I now need to see how bad this is in terms of stability. I could easily image, this revealing more bugs in other places. But this comes back to my first thought, that I had when the return was leaking a coroutine, which then turned out to not be the case.

For me, this might mean, the change could shift into a next, albeit quick release. I need to see how much is revealed here. Also, generators and asyncgen need that change too. The former is going to give more test coverage I guess, as it's more common in tests.

I will report back later this week. The good news is, the problem is either solvable or solved. This was really hard. :/

**Comment by kayhayen** [comment] 2020-05-07 08:25
The testing looked very good, and this would only be a problem, where there are existing corruptions, so leaks can hide reference losses. I am expecting to include this in the release that is coming soon, and to make this on factory a pre-release later today.

**Comment by levesquejf** [comment] 2020-05-08 11:43
With Python 3.8.2 and Nuitka 0.6.8rc8, the issue is resolved! I have 6 more `builtins.compiled_frame` compared to native run but it's not increasing when I increase the number of `http_call()` so that's good for me! Good job and thank you @kayhayen, looks like this one was a hard one.

**Comment by kayhayen** [comment] 2020-05-11 15:08
The release 0.6.8 was just made and contains the correction.

**Closed by kayhayen** 2020-05-11 15:08 UTC
Labels: bug, factory
