### ISSUE TITLE
Segmentation Fault when passing class instance as __dict__ to function kwargs

### ISSUE THREAD

**Issue by SpectrumQT** [Nuitka/Nuitka#3242] opened 2024-12-05 18:15 UTC
- Nuitka version (last factory commit: [835a632](https://github.com/Nuitka/Nuitka/commit/835a6327cdef50a411103a56911277df3556ccdd)), full Python version
```
2.6rc6
Commercial: None
Python: 3.13.1 (tags/v3.13.1:0671451, Dec  3 2024, 19:06:28) [MSC v.1942 64 bit (AMD64)]
Flavor: CPython Official
GIL: yes
Executable: C:\Program Files\Python\3.13\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.42.34433\bin\Hostx64\x64\cl.exe (cl 14.3).
```

- How did you install Nuitka and Python
```bat
python -m pip install -U "https://github.com/Nuitka/Nuitka/archive/factory.zip"
```

- `test.py` program code
```py
from dataclasses import dataclass

@dataclass
class DataObject:
    test: bool = False

def test_function(test=False):
    print(f'test_function args: test={test}')

if __name__ == '__main__':
    data_object = DataObject(test=True)
    # Works
    test_function(**{'test': True})
    # Crashes program with segmentation fault
    test_function(**data_object.__dict__)
```

- Nuitka options and build output
```
C:\Test>python -m nuitka test.py --standalone
Nuitka-Options: Used command line options: test.py --standalone
Nuitka: Starting Python compilation with Nuitka '2.6rc6' on Python '3.13' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including 'socket' automatically in order to avoid bloat, but this may cause: can break
Nuitka-Plugins:anti-bloat: calls of 'email.utils.make_msgid()'.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: cl (cl 14.3).
Nuitka-Scons: Backend linking program with 6 files (no progress information available for this stage).
Nuitka-Scons: Compiled 6 C files using clcache with 6 cache hits and 0 cache misses.
Nuitka: Keeping build directory 'test.build'.
Nuitka: Successfully created 'C:\Test\test.dist\test.exe'.
```

- Program output to console
```
C:\Test\test.dist>test.exe
test_function args: test=True
Nuitka: A segmentation fault has occurred. This is highly unusual and can
have multiple reasons. Please check https://nuitka.net/info/segfault.html
for solutions.
```

- Expected program output to console
```
C:\Test\test.dist>test.exe
test_function args: test=True
test_function args: test=True
```

**Comment by kayhayen** [comment] 2024-12-05 20:04
This seems to be an incompatibility with dictionary copying.

> Mini.bin: /home/hayen/repos/Py2C/nuitka/build/static_src/HelpersDictionaries.c:1016: Nuitka_py_get_index_from_order: Assertion `i < (((char *)mp->ma_values)[-2])' failed.

I need to more carefully review the 3.13 changes for dictionaries apparently.

**Comment by kayhayen** [comment] 2024-12-05 20:14
Thanks for the excellent reproducer, I managed to correct this one for factory and it will be in the hotfix coming shortly, this one was a bug for 3.13.0 as well.

**Comment by kayhayen** [comment] 2024-12-06 11:48
This is part of the 2.5.6 hotfix I made the other day.

**Closed by kayhayen** 2024-12-06 11:48 UTC
Labels: bug, excellent_report
