### ISSUE TITLE
No module named 'PyQt5.sip' error when running standalone file.

### ISSUE THREAD

**Issue by BenTearzz** [Nuitka/Nuitka#143] opened 2018-09-19 21:38 UTC
**Version Info:**
Nuitka: 0.5.33
Python: 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
Executable: C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\python.exe
OS: Windows
Arch: x86_64

**Installation Method:**
Downloaded the repo from the developer branch and ran **setup.py**

This is how I ran Nuitka: 
`nuitka --standalone MobilePayAlerts.py --plugin-enable=qt-plugins --show-progress --show-scons`
[compile log.txt](https://github.com/kayhayen/Nuitka/files/2398789/compiling.info.txt)

After Nuitka compiled my script MobilePayAlerts.py, I tried running MobilePayAlerts.exe where it gave me the error 
```
Traceback (most recent call last):
  File "D:\Projects\Python Projects\MobilePayAlerts\MPA\Qt\MobilePayAlerts.dist\MobilePayAlerts.py", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'
```

This is what is at the top of my file:
`from PyQt5 import QtCore, QtGui, QtWidgets`

**Comment by kayhayen** [comment] 2018-09-20 06:38
Hallo Ben,

looks perfect to me. Should totally work. The only thing that strikes is that local path to Python, is  that a virtualenv of normal CPython there, or self compiled, or something? 

And then the importing of "PyQt5.sip" right there, which really will not exist normally. But maybe your PyQt5 is newer than what I have seen so far. Can you do with that standard Python interpreter on the prompt, do "import PyQt5.sip" and "print(PyQt5.sip.__file__)" which would prove that?

I checked, the top level "sip" is included in fact, according to the log, so there is no reason to not find it.

As a workaround, you can also try then --include-module=PyQt5.sip and see if that helps. Looks like a new missing hidden dependency. I would like version information of your PyQt5 there. python -m pip freeze should give you that.

Yours,
Kay

**Comment by BenTearzz** [comment] 2018-09-20 09:45
Hi, the local path to Python was the default install directory when launching the executable setup file from their site. _"C:\Users\Tearzz\AppData\Local\Programs\Python\Python36\python.exe"_

**PyQt5.sip**
I opened the Python interpreter and ran `import PyQt5.sip`, no exceptions made. However, when I ran `print(PyQt5.sip.file)` it returned:
```
Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
AttributeError: module 'PyQt5.sip' has no attribute 'file'
```

**--include-module=PyQt5.sip**
If I try to run Nuitka like so: `nuitka --standalone MobilePayAlerts.py --include-module=PyQt5.sip --plugin-enable=qt-plugins --show-progress --show-scons` 
It returns: `Error, 'sip.pyd' is not a proper python module name.`

**PyQt5 version:**
If I run `python -m pip freeze` it returns these two:
```
PyQt5==5.11.2
PyQt5-sip==4.19.12
```

**Comment by brupelo** [comment] 2018-09-20 11:29
Few clarifications here:

 - If I recall correctly, long time ago [sip](https://www.riverbankcomputing.com/software/sip/download) used to be shipped inside the PyQt5 pypi package but this was changed recently and now sip has become an external PyQt5 dependency, so if you do for instance `pip show PyQt5` you'll see:

    ...
    Requires: PyQt5-sip <------
    ...

PyQt5-sip package contains basically just the sip extension module, ie:

    d:\virtual_envs\py364_32\lib\site-packages\pyqt5\sip.pyd
 
 - Here in github if you want to use underscores on normal text, you need to escape them, I've noticed Kay didn't escape them couple of threads ago, he meant to write this "print(PyQt5.sip.\_\_file\_\_)". If you use the markdown code rendering though you don't need to escape the underscores, ie: `print(PyQt5.sip.__file__)`. 

 - @BenTearzz `file` didn't exists because that's not a module attribute, but if you use \_\_file\_\_ you'll get the path of the sip extension module, ie:

    d:\virtual_envs\py364_32\lib\site-packages\pyqt5\sip.pyd

@BenTearzz One last advice, this report is much better than your last duplicated [one](https://github.com/kayhayen/Nuitka/issues/131) but it'd definitely improve even more if you'd provided the whole information so we can reproduce these type of issues locally without any effort, that'd help to narrow it down faster. It's not necessary for you to share the whole code but just a minimal snippet of few lines so we can test the nuitka specified version on top of it.

This issue is easy enough to solve without any code snippet though but still... it'll be always very helpful to reproduce these type of things locally on top of some minimal code. That's why the template says:

    *  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
       that demonstrates the issue i.e a small piece of code which reproduces
       the issue and can be run with out any other (or as few as possible)
       external dependencies.

Yours,
B.

**Comment by brupelo** [comment] 2018-09-20 11:51
Ooops, in my previous mail I said this issue was easy to solve but I forgot to explain the solution, my bad :/ . So yeah, right now Nuitka isn't copying the new sip.pyd living in `site-packages\PyQt5\sip.pyd` into your `MobilePayAlerts.dist` folder.

@BenTearzz Just to check it works, please copy manually the module from `your\python\Lib\site-packages\PyQt5\sip.pyd`  into `your\path\to\MobilePayAlerts.dist\PyQt5` folder, once you've done that it should run without any problems, please let us know after this the bug has gone, of course this should be done by nuitka itself.

Yours,
B

**Comment by kayhayen** [comment] 2018-09-20 12:00
Where it lives in PyPI, what the separation is I don't really care. The on disk situation is all that matters in a living installation, which is the input. But I think I didn't yet come across as sip below that namespace PyQt5 yet, but always top level. So the implicit dependency asks for "sip" and not "PyQt5.sip".

Regarding `__file__` what @brupelo said, happens a lot to me, switched to Github as issue tracker for real only relatively recently, I would like to know if it is a real ".pyd" behind that, or just an alias, so I would appreciate your output @BenTearzz 

I am not so sure if copying will be enough, as Nuitka has an internal table of modules it feels responsible for, and probably won't even try it. Of course, chances are, the fall back might consider `__path__` and use that and happen to work, but bets are off there.

I will try and fix it for 0.6.0 coming this weekend hopefully.

Yours,
Kay

**Comment by brupelo** [comment] 2018-09-20 12:08
The old sip (ie: 4.19.8) used to live on Lib\site-packages, the newest sip versions (4.19.12) are copied inside Lib\site-packages\PyQt5, which of course, is the correct way to ship it.

**Comment by kayhayen** [comment] 2018-09-20 12:32
@brupelo Dunno, isn't sip used by other things than PyQt5? So does every sip using package now ship its own copy then?

Anyway, got to follow their choices, not question them.

**Comment by BenTearzz** [comment] 2018-09-20 12:33
@brupelo @kayhayen running `print(PyQt5.sip.__file__)` does indeed print the file path which is `...\site-packages\PyQt5\sip.pyd`

In the script I tried to compile I added `import PyQt5.sip` which seems to have fixed the issue. 
I ran Nuitka like this: `nuitka --standalone MobilePayAlerts.py --plugin-enable=qt-plugins --show-progress --show-scons`

**Comment by kayhayen** [comment] 2018-09-20 12:41
@BenTearzz Very good solution. What I normally suggest these days is --include-module=PyQt5.sip as the workaround. However, I appreciate if people not just do that, but also report it, so it can become baseline.

I think that concludes input needed. I will let you know once the fixes are coming.

**Comment by brupelo** [comment] 2018-09-20 12:44
> @brupelo Dunno, isn't sip used by other things than PyQt5? So does every sip using package now ship its own copy then?

Kay, maybe I'm wrong but I recall in the past sip used to ship not only the extension module sip.pyd but also sip.exe and other files, as you probably already know, sip.exe is a similar tool than swig, in fact, if you compile from [sources](https://sourceforge.net/projects/pyqt/files/sip/sip-4.19.12/sip-4.19.12.zip) you'll see the whole stuff sip provides. I used sip few times in the past to create extension modules out of custom c++ code but I didn't really like it very much and nowadays I just use the good old swig :) 

Although I've heard very nice things about pybind11 or clif, this last one from google... But meh, swig does the job pretty well so I'm alright :)

> Anyway, got to follow their choices, not question them.

Oh, yeah, sure sure... Just provided some meta-information more as additional curiosity rather than something necessary to tackle the issue, at this point you already know how to fix this thing, so... ;)

Anyway, all clear so far, so yeah, thanks everyone.

**Comment by kayhayen** [comment] 2018-09-21 06:19
This is now on factory http://nuitka.net/doc/factory.html and will likely be in 0.6.0 which I hope to arrive this weekend.

**Comment by brupelo** [comment] 2018-09-21 14:09
I've tested latest factory and now nuitka is copying correctly boh sip files `site-packages\sip.pyd` and `site-packages\PyQt5\sip.pyd`, i say correct ones cos they match the original checksum, good job.

Btw, I've been able to spot another little bug related to this issue. Take a look to this line [PySidePyQtPlugin.py#L59](https://github.com/kayhayen/Nuitka/blob/develop/nuitka/plugins/standard/PySidePyQtPlugin.py#L59). `libraryPaths` won't always return values, for instance, it can return an empty list.

If that happens you'll get a nice uncaptured crash here [PySidePyQtPlugin.py#L110](https://github.com/kayhayen/Nuitka/blob/develop/nuitka/plugins/standard/PySidePyQtPlugin.py#L110) because... `ValueError: not enough values to unpack (expected 1, got 0)`. So yeah, consider yourself you've been warned ;)

**Comment by kayhayen** [comment] 2018-09-21 14:48
Sure @brupelo but apparently although this is a list, everybody so far only ever had a single library path for Qt there. The unpacking checks it, and surely we will hear from them if it fails. Or who knows, maybe somebody who has that creates the PR, one never knows.

**Comment by brupelo** [comment] 2018-09-21 22:50
@kayhayen Kay, actually that's not a bad strategy at all... and no, not trying to be sarcastic or kidding about, it's true. I've seen few companies out there already applying the principle of "don't fix stuff till users/customers complain and don't waste time trying to anticipate the future being too defensive". And I must to say that motto was working pretty well for them... I guess you can add to the 2 existing python schools of "ask for forgiveness" or "ask for permission" the additional of... "wait till your customers bark about it" ;-D

**Comment by kayhayen** [comment] 2018-09-23 04:51
So this is in the new pre-release now, closing now as release is immanent and not hotfixes will happen for 0.5.33 anymore.

**Closed by kayhayen** 2018-09-23 04:51 UTC
Labels: bug, factory
