### ISSUE TITLE
Error  c_lib_wrap

### ISSUE THREAD

**Issue by monkeycc** [Nuitka/Nuitka#2590] opened 2023-12-03 03:59 UTC
> python -m nuitka --version
```
1.9.3
Commercial: None
Python: 3.8.18 (default, Sep 11 2023, 13:39:12) [MSC v.1916 64 bit (AMD64)]
Flavor: Anaconda Python
Executable: E:\anaconda3\envs\FastDeploy_CPU\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe (cl 14.2).
```

- How did you install Nuitka and Python

`python -m pip install nuitka`

  > python -m pip freeze
```
annotated-types==0.6.0
anyio==3.7.1
asgiref==3.7.2
certifi==2023.11.17
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
dearpygui==1.10.1
exceptiongroup==1.2.0
fastapi==0.104.1
fastdeploy-python==1.0.7
fastdeploy-tools==0.0.5
h11==0.14.0
idna==3.6
Nuitka==1.9.3
numpy==1.24.4
opencv-python==4.8.1.78
ordered-set==4.1.0
pydantic==2.5.2
pydantic_core==2.14.5
PyYAML==6.0.1
requests==2.31.0
sniffio==1.3.0
starlette==0.27.0
tqdm==4.66.1
typing_extensions==4.8.0
urllib3==2.1.0
uvicorn==0.16.0
zstandard==0.22.0

```
---------------------

https://github.com/PaddlePaddle/FastDeploy
`pip install fastdeploy-python -f https://www.paddlepaddle.org.cn/whl/fastdeploy.html
`

```python
import cv2
import fastdeploy.vision as vision

im = cv2.imread("000000014439.jpg")
model = vision.detection.PPYOLOE("ppyoloe_crn_l_300e_coco/model.pdmodel",
                                 "ppyoloe_crn_l_300e_coco/model.pdiparams",
                                 "ppyoloe_crn_l_300e_coco/infer_cfg.yml")

result = model.predict(im)
print(result)

vis_im = vision.vis_detection(im, result, score_threshold=0.5)
cv2.imwrite("vis_image.jpg", vis_im)
```

python -m nuitka --standalone 1.py

c_lib_wrap.py
```python
try:
    from .libs.fastdeploy_main import *
except Exception as e:
    raise RuntimeError(f"FastDeploy initalized failed! Error: {e}")
```

```python
Traceback (most recent call last):
  File "E:\2023_C~1\DB_202~1\DB_FD~1.DIS\fastdeploy\c_lib_wrap.py", line 164, in <module fastdeploy.c_lib_wrap>
ImportError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\2023_C~1\DB_202~1\DB_FD~1.DIS\db_FD.py", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "E:\2023_C~1\DB_202~1\DB_FD~1.DIS\fastdeploy\__init__.py", line 122, in <module fastdeploy>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "E:\2023_C~1\DB_202~1\DB_FD~1.DIS\fastdeploy\c_lib_wrap.py", line 166, in <module fastdeploy.c_lib_wrap>
RuntimeError: FastDeploy initalized failed! Error:
```

---------------------

https://github.com/PaddlePaddle/FastDeploy/issues/2308
FastDeploy 
I also went to submit the question

**Comment by kayhayen** [comment] 2024-07-08 12:07
Since nothing is forthcoming and this cannot be reproduced for several reasons, I am closing this as invalid and will likely delete the issue later.

**Closed by kayhayen** 2024-07-08 12:07 UTC
Labels: enhancement, help wanted
