### ISSUE TITLE
Enhanced yt_dlp configuration to avoid including more than Youtube by default

### ISSUE THREAD

**Issue by kaneryu** [Nuitka/Nuitka#3269] opened 2024-12-19 05:03 UTC
Hey,
I was using yt_dlp in my project just to fetch the download links to youtube videos, but when compiling, it tries to inculde a file with over 15 thousand lines. This is because yt_dlp does not just do youtube, but hundreds of other video download services. This caused the compilation time to be a few hours (maybe, i never ended up waiting more than 30 mins)

I was able to remove all classes not related to youtube from the file, and it works fine. I read in the yaml config docs that if you make a useful change, you should submit a PR, but since this is removing functionality, I decided to ask first. Also, how should I submit the yaml file, if you guys want it?

**Comment by kaneryu** [comment] 2024-12-19 05:05
[nuitka-fix.config.yml.txt](https://github.com/user-attachments/files/18192758/nuitka-fix.config.yml.txt)
The config is above ^, but remove the .txt extention

**Comment by kayhayen** [comment] 2024-12-19 08:36
The module code change probably should be done with replacements, but I guess I can compare with what you changed, or is this actually some sort of new implementation for the module?

**Comment by kayhayen** [comment] 2024-12-19 08:42
I should have read your description to the end first. So this is about not following all kinds of modules right away. We have configuration that just doesn't follow imports, should that be sufficient? This is from the pygame configuration. In one case it's silently ignoring pygame.tests and doesn't include that unless user asks for unittest module to be allowed, in the other, cv2 is not followed, with a message displayed to the user, informing them that they can still enable that.

```
  anti-bloat:
    - no-auto-follow:
        'pygame.tests': 'ignore'
      when: 'not use_unittest'
    - no-auto-follow:
        'cv2': 'camera functionality via OpenCV-Python (cv2)'
```

Can you work off that? Also, it would be nice to have like a hello world yt download example that could be used to test it.

**Comment by kaneryu** [comment] 2024-12-19 13:56
> We have configuration that just doesn't follow imports

The file is required, we can't just not import it -- But at the same time, it does contain hundreds upon hundreds of classes that users most likely will not need (it's called youtube-dl not every-single-website-dl, after all). I don't think that solution you listed (pygame example) would work. However, I will try to rewrite it with replacements instead of copy and pasting the code, if that is an issue.

**Comment by kaneryu** [comment] 2024-12-19 13:56
> Also, it would be nice to have like a hello world yt download example that could be used to test it.

I'll make that in a few minutes. I've actually already tested the yaml with one of my applications successfully already.

**Comment by kayhayen** [comment] 2024-12-19 15:05
Configuration is bound by when conditions. These could be controlled by module parameters if it makes sense. The advantage of not following the imports even with `--follow-imports` is that you can override that by adding explicit follows for the specific modules. I will look at what you come with, and maybe have some sort of module parameter if it makes sense.

But generally the configuration should be one size fits all.

For Django we use parameters like this, which kind of replaces a whole plugin, by making things dependent on even variables determined at runtime. But the parameter can be used in the `when` clauses of all configuration, and could be used to enable or disable specific settings.

```
- module-name: 'django.core.management' # checksum: cb686c29
  parameters:
    - 'name': 'settings-module'
      'values': 'checkModuleName(value)'
  variables:
    setup_code:
      - 'import os, importlib'
      - 'settings = importlib.import_module(os.getenv("PARAMETER_SETTINGS_MODULE")) if os.getenv("PARAMETER_SETTINGS_MODULE") else None'
    declarations:
      'django_installed_apps': 'settings.INSTALLED_APPS if settings else ()'
    environment:
      'PARAMETER_SETTINGS_MODULE': 'get_parameter("settings-module", "")'
  anti-bloat:
    # This makes exceptions to the "*" dependency in the
    # implicit-imports section below.
    - no-follow:
        'django.core.management.commands.test': 'disable tests'
      when: 'not use_pytest'
  implicit-imports:
    - depends:
        - 'django.core.management.commands.*'
        - 'get_parameter("settings-module", ())'
        - '["%s.management.commands.*" % x for x in get_variable("django_installed_apps")]'
        - 'get_variable("django_installed_apps")'

  options:
    checks:
      - description: "Django settings module must be specified with '--module-parameter=django-settings-module=<settings_module_name>'"
        support_info: 'parameter'
        when: 'get_parameter("settings-module", None) is None'
```

But I am not asking that level of quality, since it involves working with unterdocumented functionality that we use only in 3 instances so far. If you make it clear what changes are needed, that will be great already.

**Comment by seproDev** [comment] 2024-12-19 23:05
yt-dlp maintainer here. The name yt-dlp comes from the name the project was forked off "youtube-dl", which itself has its name for historic reason since originally in 2006 it could only downlaod youtube. Right now the vast majority of code and development time is **not** spent on youtube. I know the name is not ideal, but renames are difficult. Just removing everything, but youtube seems very specific to your particular use case.

I am not super familar with Nuitka, but it should be noted that `lazy_extractors.py` can be removed in a regular python environment without issues. Lazy extractors are a way to speed up program startup by not loading all modules, but only the ones that are actually needed.

**Comment by kaneryu** [comment] 2024-12-20 02:18
> yt-dlp maintainer here. The name yt-dlp comes from the name the project was forked off "youtube-dl", which itself has its name for historic reason since originally in 2006 it could only download youtube.

Apologies if I came of as rude in my original reply, I'm nothing but grateful for your work, I do recognize that renames are hard, lol.

> I am not super familar with Nuitka, but it should be noted that `lazy_extractors.py` can be removed in a regular python environment without issues. Lazy extractors are a way to speed up program startup by not loading all modules, but only the ones that are actually needed.

I didn't even think of that! Thanks. I'll rewrite the config with that in mind.

**Comment by kayhayen** [comment] 2024-12-20 10:37
@seproDev glad to have you here, do you see an easy way for a kind of choice of backends to use at compile time, by e.g. not including them, or will that give a runtime error. Because if that is the case, I would simply default to including only what the developer asks to, and otherwise give an error.

With packages that have several optional backends, not loading them at runtime is one goal, not including them at compile time another goal. Lazy loading often clouds the view for static analysis. I guess, ultimately I would have to look at the original code, but you will be better informed, how to perform such surgery with code manipulation or exclusions of modules.

The goal is specifically not against lazy loading, but for not including everything for all compilations. Obviously, if somebody were to package a general purpose binary, they would go with "all" for whatever parameter we provide.

**Comment by bashonly** [comment] 2024-12-20 13:33
Hi, another yt-dlp maintainer here. The `lazy_extractors` module is not committed to the yt-dlp repository. It is generated in our build workflow and included in our PyPI wheels and source distribution. It can be safely disabled/removed just by deleting the `yt_dlp/extractor/lazy_extractors.py` file.

But it sounds like you may be asking about disabling/removing other full extractor modules/classes rather than just the lazy extractors module. This is not supported by yt-dlp since it would be altering how yt-dlp actually works.

**Comment by zak-45** [comment] 2024-12-29 15:56
So, this is really interesting. I like yt-dlp and use it for one of my project. Only the youtube part is required on my side and I can confirm that this take some hours to compile. If you need someone for test, will be happy to help.

**Comment by kaneryu** [comment] 2024-12-31 05:54
@zak-45 
> So, this is really interesting. I like yt-dlp and use it for one of my project. Only the youtube part is required on my side and I can confirm that this take some hours to compile. If you need someone for test, will be happy to help.

You can use my config file in the original post, it works fine.

----

I'm not sure if this should be fixed directly. Would this be a 'plugin' in nuitka if it is added to the main project? The reason why I'm not sure about adding it is that it
- Removes functionality
- Only works for Youtube, and you may also want just one, or multiple, of another service.

**Comment by kayhayen** [comment] 2024-12-31 14:49
Yes, I think it is clear, that any such configuration would have to be based on a module parameter, where the user decides what to enable and what not.

From the looks of it, this module doesn't do much imports, and with scalability work coming that will make it just not slow, the classes that are basically just configuration, and will not pose a problem in the future, so working on this now with workarounds is not all that useful, when Nuitka 2.9 or so will not have this anymore.

**Closed by kayhayen** 2024-12-31 14:49 UTC
Labels: enhancement
