### ISSUE TITLE
Random behavior when overriding standard library module in standalone mode

### ISSUE THREAD

**Issue by zpin** [Nuitka/Nuitka#1211] opened 2021-09-16 06:08 UTC
I was seeing an issue when overriding the "logging" module, the build worked fine under Windows but broke under Linux. While trying to create a minimal program to reproduce the issue I discovered that this issue appears randomly and depends on the ordering of the modules in the __loader.cpp.

Code:
`/home/user/test/test.py`
```
#!/usr/bin/env python
# vim: set fileencoding=utf-8

import logging

if __name__ == '__main__':
    print("L", logging.TRACE)
```

`/home/user/test/logging/__init__.py`
```
TRACE = 5
```

Compiled using:
```
cd /home/user/test/tmp
python3 -m nuitka /home/user/test/test.py --output-dir=nuitka.build --standalone --python-flag=nosite
./nuitka.build/test.dist/test
```
Output:
```
L 5
```

Compiled again using:
```
cd /home/user/test/tmp
python3 -m nuitka /home/user/test/test.py --output-dir=../nuitka.build --standalone --python-flag=nosite
../nuitka.build/test.dist/test
```
Output:
```
Traceback (most recent call last):
  File "/home/user/test/nuitka.build/test.dist/test.py", line 7, in <module>
AttributeError: module 'logging' has no attribute 'TRACE'
```

The diff between the build directories looks like this:

```
diff -ur ../nuitka.build/test.build/__loader.cpp nuitka.build/test.build/__loader.cpp
--- ../nuitka.build/test.build/__loader.cpp     2021-09-16 07:41:24.290647680 +0200
+++ nuitka.build/test.build/__loader.cpp        2021-09-16 07:35:13.324647680 +0200
@@ -479,8 +479,8 @@
     {"lib2to3.refactor", NULL, 409, 20312, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG},
     {"linecache", NULL, 410, 3736, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG},
     {"locale", NULL, 411, 34535, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG},
-    {"logging", NULL, 412, 62340, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG},
     {"logging", modulecode_logging, 0, 0, NUITKA_TRANSLATED_FLAG | NUITKA_PACKAGE_FLAG},
+    {"logging", NULL, 412, 62340, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG | NUITKA_PACKAGE_FLAG},
     {"logging.config", NULL, 413, 22998, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG},
     {"logging.handlers", NULL, 414, 42979, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG},
     {"macpath", NULL, 415, 5754, NUITKA_TRANSLATED_FLAG | NUITKA_BYTECODE_FLAG},
Binary files ../nuitka.build/test.build/__loader.o and nuitka.build/test.build/__loader.o differ
diff -ur ../nuitka.build/test.build/scons-report.txt nuitka.build/test.build/scons-report.txt
--- ../nuitka.build/test.build/scons-report.txt 2021-09-16 07:41:24.975647680 +0200
+++ nuitka.build/test.build/scons-report.txt    2021-09-16 07:35:14.283647680 +0200
@@ -1,6 +1,6 @@
 CC=gcc
 CCACHE_DIR=/home/user/.cache/Nuitka/ccache
-CCACHE_LOGFILE=/home/user/test/nuitka.build/test.build/ccache-18835.txt
+CCACHE_LOGFILE=/home/user/test/tmp/nuitka.build/test.build/ccache-17955.txt
 CCCOM=$CC -o $TARGET -c $CFLAGS $CCFLAGS $_CCCOMCOM $SOURCES
 CFILESUFFIX=.c
 CPPDEFINES=['_NUITKA_STANDALONE', '__NUITKA_NO_ASSERT__', '_NUITKA_CONSTANTS_FROM_INCBIN', '_NUITKA_FROZEN=165', '_NUITKA_EXE']
Binary files ../nuitka.build/test.dist/test and nuitka.build/test.dist/test differ
```

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)
```
0.6.16
Python: 3.7.6 (default, Jan  9 2020, 19:47:33)
Executable: /usr/local/bin/python3
OS: Linux
Arch: x86_64
```

* How did you install Nuitka and Python
  `pip install -U nuitka==0.6.16`

* Note if this is a regression
  I didn't have the issue with 0.6.10 which is the version I upgraded from.
 - 0.6.15: Same issue (random)
 - 0.6.14: Seems to consistently throw the error
 - 0.6.13: Seems to consistently work (always outputs 'L 5')
 The issue seems random on 0.6.16 so it's possible that the above results are not completely accurate. I did try at least 6 compiles on each version, however.

**Comment by kayhayen** [comment] 2021-09-16 11:15
Excellent report, this is of course very bad behaviour, naturally I do not appreciate random outputs at all, so the list is sorted, but only by name. I believe sorting them as well by type should make sense, and we need to make sure that bytecode modules, i.e. frozen standard library goes last.

In an ideal world, we would have proper compilation of standard library too, at least for dependency tracking, and then the bytecode logging module wouldn't be included at all, and there would only be one. Unfortunately we don't have the caching that I would find necessary for that to be done yet, so this needs a solution now.

**Comment by kayhayen** [comment] 2021-09-16 11:32
This is likely a regression, the code did in fact attempt to put first the processed modules, calling them "done", and then the uncompiled modules last. But now this gave a duplication of the result, since at some point, the uncompiled module became also something that is processed. So this broke without noticing.

The next release is immanent, I am am probably not making a new hotfix for 0.6.16.6 out of this, but it will be in 0.6.17 instead.

Right now, factory branch contains the fix: https://nuitka.net/doc/factory.html

**Comment by zpin** [comment] 2021-09-16 13:26
Awesome, that seems to fix it, thank you!

**Comment by kayhayen** [comment] 2021-09-19 17:11
Part of the current pre-release on develop branch.

**Comment by kayhayen** [comment] 2021-10-03 09:09
This is part of the 0.6.17 release.

**Closed by kayhayen** 2021-10-03 09:09 UTC
Labels: bug, develop
