### ISSUE TITLE
PySide6 QTimer.timeout.connect does not work within QMainWidget, but in QApplication

### ISSUE THREAD

**Issue by BasWeg** [Nuitka/Nuitka#1210] opened 2021-09-15 13:05 UTC
Hi,

I've made a PySide6 GUI application with several QTimer objects within widgets.

If I execute the application with python, everything is fine. Also deployed with cx_freeze.

Now I've tried nuitka with following command:
`python.exe -m nuitka --mingw64 --standalone test.py --plugin-enable=pyside6 --plugin-enable=pylint-warnings --follow-imports`

The result does not work, since the methods connected to the timers are not executed. I've made 2 small examples you can find at the end.

* Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

  > python -m nuitka --version
```
0.6.16.4
Python: 3.9.4 (tags/v3.9.4:1f2e308, Apr  6 2021, 13:40:21) [MSC v.1928 64 bit (AMD64)]
Executable: C:\Users\Bad\AppData\Local\Programs\Python\Python39\python.exe
OS: Windows
Arch: x86_64
```

* How did you install Nuitka and Python

 installed via pip. No venv

* The specific PyPI names and versions
  > python -m pip freeze
```
PySide6==6.1.3
```
* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)
Not Working Example QTimer within Widget:
```
#%%
import sys
from PySide6.QtWidgets import QApplication, QMainWindow
from PySide6.QtCore import QTimer

class MainWidget(QMainWindow):
    def __init__(self, parent=None):
        super(MainWidget, self).__init__(parent)
        self.timer = QTimer(self) #self
        self.timer.timeout.connect(self.update)
        self.timer.start(1000)
        self.count = 0

    def update(self):
        self.count += 1
        print ("update ",self.count)
        if self.count >5:
            self.timer.stop()
            self.close()

if __name__ == "__main__":
    app = QApplication(sys.argv)
    mymain = MainWidget()
    mymain.show()
    sys.exit(app.exec())
```

Expected output:
```
>test.exe
update 1
update 2
update 3
update 4
update 5
update 6
```

Working Example - QTimer within QApplication:
```
#%%
import sys
from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QTimer

class MainApp(QApplication):
    def __init__(self, parent=None):
        super(MainApp, self).__init__(parent)
        self.timer = QTimer(self) #self
        self.timer.timeout.connect(self.update)
        self.timer.start(1000)
        self.count = 0

    def update(self):
        self.count += 1
        print ("update",self.count)
        if self.count >5:
            self.timer.stop()
            self.exit()

if __name__ == "__main__":
    app = MainApp(sys.argv)
    sys.exit(app.exec())

```

Any idea?

Best regards
Bastian

**Comment by BasWeg** [comment] 2021-09-15 15:11
I would have not provided this request if both examples would work as they should. I've stripped everything down. Could there be any inference with other installed python modules?

**Comment by BasWeg** [comment] 2021-09-15 15:29
The first example is not working for me under windows and - just tested - linux (ubuntu)

**Comment by kayhayen** [comment] 2021-09-15 15:46
I spend the time, because I can see you are a diligent reporter, but if this wouldn't work, I think I should know. I was also using 3.9 like you are. Maybe you are having a hello world issue of some sorts, maybe you can use a git clone and run this:

`python3.9 bin/compare_with_cpython Mini.py`

and provide the output? That is my script used for testing, and it makes sure to compare outputs and use the same Python, etc.

**Comment by BasWeg** [comment] 2021-09-15 16:30
of course, I can do it.
Mini.py is my example?

**Comment by BasWeg** [comment] 2021-09-15 17:00
OK, here is the result for following example, fresh pyside6 install an different Windows10:

```
PS D:\Projekte\Nuitka> & C:/Users/xxx/AppData/Local/Programs/Python/Python39/python.exe bin/compare_with_cpython ../test1.py
Comparing output of '../test1.py' using 'C:\Users\xxx\AppData\Local\Programs\Python\Python39\python.exe' with flags  ...
********************************************************************************
CPython:
********************************************************************************
update  1
update  2
update  3
update  4
update  5
update  6
 ********************************************************************************
Nuitka:
********************************************************************************
```

Now the QWidget Window is open and it does nothing... Nothing is counted.
After closing the window, the diff is mentioned:
```
Nuitka-Options:INFO: Used command line options: --python-flag=no_warnings --full-compat --verbose-output=../test1.py.optimization.log --show-modules-output=../test1.py.inclusion.log --run ../test1.py
Nuitka:INFO: Starting Python compilation with Nuitka '0.6.17rc8' on Python '3.9' commercial None.
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C level backend compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: C:\Users\xxx\AppData\Local\Nuitka\Nuitka\gcc\x86_64\10.2.0-11.0.0-8.0.0-r5\mingw64\bin\gcc.exe (gcc.exe).
Nuitka-Scons:INFO: Compiled 10 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 10
Nuitka:INFO: Keeping build directory 'test1.build'.
Nuitka:INFO: Successfully created 'test1.exe'.
Nuitka:INFO: Launching 'test1.cmd'.
 --- C:\Users\xxx\AppData\Local\Programs\Python\Python39\python.exe (stdout)
+++ nuitka (stdout)

@@ -1,7 +1 @@

-update  1
-update  2
-update  3
-update  4
-update  5
-update  6

Error, results differed (stdout).
PS D:\Projekte\Nuitka>
```
Instead the Cpython variant opens the window and close is after 6 seconds, counter is shown in the console afterwards. 

The failing example is still the same:
```
#%%
import sys
from PySide6.QtWidgets import QApplication, QMainWindow
from PySide6.QtCore import QTimer

class MainWidget(QMainWindow):
    def __init__(self, parent=None):
        super(MainWidget, self).__init__(parent)
        self.timer = QTimer(self) #self
        self.timer.timeout.connect(self.update)
        self.timer.start(1000)
        self.count = 0

    def update(self):
        self.count += 1
        print ("update ",self.count)
        if self.count >5:
            self.timer.stop()
            self.close()

if __name__ == "__main__":
    app = QApplication(sys.argv)
    mymain = MainWidget()
    mymain.show()
    sys.exit(app.exec())
```

**Comment by BasWeg** [comment] 2021-09-15 17:34
I've updated the testcode using an QLabel instead QMainWindow to have visual feedback.
The counter ticks with 500ms, so its faster ;)
The Qlabel window shows the counter. 

```
#%%
import sys
from PySide6.QtWidgets import QApplication, QLabel, QMainWindow
from PySide6.QtCore import QTimer

class MainWidget(QLabel):
    def __init__(self, parent=None):
        super(MainWidget, self).__init__(parent)
        self.timer = QTimer(self) #self
        self.timer.timeout.connect(self.update)
        self.timer.start(500)
        self.count = 0

    def update(self):
        self.count += 1
        self.setText("update %s"% (self.count))
        print ("update ",self.count)
        if self.count >5:
            self.timer.stop()
            self.close()

if __name__ == "__main__":
    app = QApplication(sys.argv)
    mymain = MainWidget()
    mymain.show()
    sys.exit(app.exec())
```

**Comment by kayhayen** [comment] 2021-09-16 11:39
This does it for me, thank you, but I am totally confused as to what the difference could be. But once I know the bug, maybe I can tell why it was working for me with the other example.

**Comment by BasWeg** [comment] 2021-09-16 11:47
Thank you,
I've just double checked within a fresh installed linux VM (CinnamonMint) if the issue persists. 
I'm somehow glad that the issue now shows up at your system. :)

**Comment by kayhayen** [comment] 2021-09-16 11:47
I checked, and it seems that the `update` function is never called, while `__init__` runs normally. As a `QApplication`, there is no issue for me, but you say there was for you, this might prove useful to explain why it happens.

**Comment by kayhayen** [comment] 2021-09-16 11:56
A search and replace of `update` to `update2` works around the issue. It seems QLabel has a `update` method, and that one is picked over the overload. Question becomes, if this a determistic thing or not. I was using `python -m nuitka --run` so I am having hashes determistic, that's a leftover from Nuitka process. it sets `PYTHONHASHSEED=0` if not already option `-R` is used.

However, the `QApplication` doesn't have an update and sometimes I have executed the failing programs with bash afterwards, so this might be a false lead, although it would have explained different results. It might be a PySide6 issue of resolving the method. The `self.update` apparently is a compiled method object, even when it fails.

I will get in touch with Qt company and it probably needs to be debugged there. Can you confirm or deny that changing the name of the callback works for you?

**Comment by BasWeg** [comment] 2021-09-16 12:06
> I checked, and it seems that the `update` function is never called, while `__init__` runs normally. As a `QApplication`, there is no issue for me, but you say there was for you, this might prove useful to explain why it happens.

No, with "QApplication", there is no issue for me, too. Sorry if my first post was misleading. I'm not an english native speaker.
I've made one "Not Working Example QTimer within Widget:" showing the bug and one working example with QAPplication, which is fine.

**Comment by BasWeg** [comment] 2021-09-16 12:15
I've renamed the method called by timer timeout from `def update(self):` to `def tmr_timeout(self):`.

Now everything is working fine. Thanks! Sorry for your circumstances! That is my first python GUI project, and I've a lot to learn.
Now I need to doublecheck all my files :)

**Comment by kayhayen** [comment] 2021-09-16 13:24
Well, that's of course not right. I am not sure it's a bug of yours, I am pretty sure it's one of ours, Nuitka and/or PySide6 here, but at least you now have a workaround. I cannot work on this right away, but it seems important, and so this will be dealt with eventually.

However, thanks for the good report, and sticking with me on this. :)

**Comment by kayhayen** [comment] 2023-07-10 08:50
We now have a workaround for reference losses in connecting the slots with methods, that's another bug in PySide6 there.

And just doing this, workarounds this bug.

```
                  if func.im_func.__name__ == "update":
                      func.im_func.__name__ = "update_tmr"
```

I wish there was a way to know if a function name causes the issue. But for now, your example works when I add that out of the box.

I also can do this I guess

```
                  if not func.im_func.__name__.startswith("_pyside6_workaround_"):
                      func.im_func.__name__ = "_nuitka_" + func.im_func.__name__
```

That will affect tracebacks, but it will make PySide6 definitely not consider the signature of a base method.

**Comment by kayhayen** [comment] 2023-07-12 07:31
So I put this on develop only, will be in 1.8 release. If any issue is caused by it, I would to catch it before putting it on stable, and it will potentially change behavior of programs.

**Comment by kayhayen** [comment] 2024-01-13 15:52
So this issue is still open, and I find no trace of this being in the release, I am confused now.

**Comment by kayhayen** [comment] 2024-01-13 15:57
Ah, I remember, first of all, the code was not good, doing it multiple times potentially:

```
                  if not receiver.im_func.__name__.startswith("_pyside6_workaround_"):
                      receiver.im_func.__name__ = "_nuitka_" + receiver.im_func.__name__
```

And then Qt was crashing, if you did this to some of their things, but there also never was a reason to do it for non-compiled functions, which it did, so I guess, this can come back in enhanced form for 2.0 then.

**Comment by kayhayen** [comment] 2024-01-13 16:03
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2024-01-22 12:04
This is now on the develop and the commercial staging branch and part of the latest pre-release, will be part of the 2.0 release that will eventually follow.

**Comment by kayhayen** [comment] 2024-01-26 13:27
This is part of the stable release 2.0 that I just made.

**Closed by kayhayen** 2024-01-26 13:27 UTC
Labels: bug, develop, excellent_report
