### ISSUE TITLE
Build fails with pyside6 on module_name.getPackageName

### ISSUE THREAD

**Issue by janvorac** [Nuitka/Nuitka#2664] opened 2024-01-24 08:08 UTC
I'm trying your exe builder on an extremely simple project - a PySide6 simple window with OpenFileDialog and no other functionality (more func will eventually come later). The build fails with the error I pasted below. I'm not sure if it has something to do with my setup - if so, any help will be appreciated. The failed job is here https://github.com/janvorac/lighterOES/actions/runs/7636877504/job/20804683922, feel free to browse the whole repo. 

Thanks for any help!

```
"C:\Program Files\Git\usr\bin\tar.exe" -xf D:/a/_temp/20af7276-e250-4e04-b69f-df8720fa5665/cache.tzst -P -C D:/a/lighterOES/lighterOES --force-local --use-compress-program "zstd -d"
Cache restored successfully
Cache restored from key: Windows-python-3.10-nuitka-64abde58319c52f93cb80f06872172b91046f318
Run set -e
Nuitka-Options:INFO: Used command line options: --onefile --standalone --assume-yes-for-downloads --output-dir=build --script-name=src/main_window.py --enable-plugins=pyside6
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\plugins\Plugins.py", line 82, in withPluginProblemReporting
    yield
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\plugins\Plugins.py", line 123, in _addActivePlugin
    plugin_instance = plugin_class(**plugin_args)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 1419, in __init__
    NuitkaPluginQtBindingsPluginBase.__init__(
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\plugins\standard\PySidePyQtPlugin.py", line 65, in __init__
    self.distribution = getDistributionFromModuleName(self.binding_name)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\utils\Distributions.py", line 212, in getDistributionFromModuleName
    distributions = getDistributionsFromModuleName(module_name)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\nuitka\utils\Distributions.py", line 198, in getDistributionsFromModuleName
    and module_name.getPackageName() is not None
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'getPackageName'
FATAL: pyside6: Plugin issue while working on 'Plugin initialization failed'. Please report the bug with the above traceback included.
Error: Process completed with exit code 1.
```

**Comment by kayhayen** [comment] 2024-01-24 09:02
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by janvorac** [comment] 2024-01-24 11:41
I confirm that when using `factory` version, the error is gone. Now I have a different one - `FATAL: pyside6: Error, failed to locate the PySide6 installation.` but that might be just me wrongly using it. Going to check the docs.

**Comment by kayhayen** [comment] 2024-01-24 12:14
PySide6 works still for me, I also don't see how it would, could of course be 2.0 issues generally.

**Comment by janvorac** [comment] 2024-01-24 12:25
I can confirm that it was my wrong setup. I have successfully built the windows executable now. Thanks for your help!

**Comment by kayhayen** [comment] 2024-01-26 12:56
This is part of the stable release 2.0 that I just made.

**Closed by kayhayen** 2024-01-26 12:56 UTC
Labels: bug, develop

**Comment by Warm7yry** [comment] 2025-07-16 06:02
> I confirm that when using `factory` version, the error is gone. Now I have a different one - `FATAL: pyside6: Error, failed to locate the PySide6 installation.` but that might be just me wrongly using it. Going to check the docs.

How did you solver this problem - `FATAL: pyside6: Error, failed to locate the PySide6 installation.`  I met that, but didnt know how to do

**Comment by kayhayen** [comment] 2025-07-16 19:35
@Warm7yry Posting below closed or unrelated issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made, and I am not going to trace, or remember to check later, or searching for where something was said. Please open new issues for new issues. If the issue is closed, it's not the same even if the symptom looks similar to you.
