### ISSUE TITLE
FileNotFoundError: Shared library with base name 'llama' not found

### ISSUE THREAD

**Issue by p1utoze** [Nuitka/Nuitka#3094] opened 2024-08-26 14:31 UTC
I have a python package used as a CLI application. `llama-cpp-python`'s DLL files (specifically libllama.so) are ignored and included in `dist` folder when I compile the package as standalone distribution but still when I invoke my package as:
```
./mypackage.bin --help
```
I get the error: 
```
  File "/app/mypackage.dist/llama_cpp/llama_cpp.py", line 83, in <module llama_cpp.llama_cpp>
  File "/app/mypackage.dist/llama_cpp/llama_cpp.py", line 74, in _load_shared_library
FileNotFoundError: Shared library with base name 'llama' not found
```
A similar issue has been found with [pyinstaller](abetlen/llama-cpp-python#1475) as well.

- `$ nutika --version`

```
2.4.7
Commercial: None
Python: 3.9.2 (default, Feb 28 2021, 17:03:44) 
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Debian 11
Version C compiler: /usr/bin/gcc (gcc 10).
```
- Installation method:

```
$ pip install nuitka
```

- Seeing the Nutika Configuration page, I edited the `standard.nuitka-package.config.yml` in `plugins/standard`
```
- module-name: 'llama_cpp'
  dlls:
    - from_filenames:
        prefixes: 
          - 'lib'
        suffixes: 
          - 'so'
      dest_path: '.'
      when: 'linux'
```

- These are the flags and arguments passed during standalone distribution mode:
```
$ python3 -m nuitka --clang --standalone /app/mypackage/ --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow --noinclude-IPython-mode=nofollow --noinclude-custom-mode=setuptools:error --follow-imports --noinclude-default-mode=error --nofollow-import-to=numpy.distutils --include-package=mypackage 
```

- Here's the full logs: 
```
Nuitka-Options: Used command line options: --clang --standalone /app/mypackage/
Nuitka-Options: --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow
Nuitka-Options: --noinclude-IPython-mode=nofollow --noinclude-custom-mode=setuptools:error
Nuitka-Options: --follow-imports --noinclude-default-mode=error
Nuitka-Options: --nofollow-import-to=numpy.distutils --include-package=mypackage
Nuitka-Options: Following all imports is the default for standalone mode and need not be specified.
Nuitka: Starting Python compilation with Nuitka '2.4.7' on Python '3.9' commercial grade 'not
Nuitka: installed'.
Nuitka: Using Debian packages for 'pkg_resources'.                                               
Nuitka:WARNING: Standalone with Python package from Debian installation may not be working.
Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/debian-dist-packages.html
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid bloat, but this
Nuitka-Plugins:anti-bloat: may cause: may slow down by using fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.                            
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: clang (clang 11.0.1).
Nuitka-Scons: Backend linking program with 890 files (no progress information available for this
Nuitka-Scons: stage).
Nuitka-Scons: Compiled 889 C files using ccache.
Nuitka-Scons: Cached C files (using ccache) with result 'cache hit': 886
Nuitka-Scons: Cached C files (using ccache) with result 'cache miss': 3
Nuitka-Plugins:dll-files: Found 2 files DLLs from llama_cpp installation.     ----> It clearly detects and adds the files in dist/
Nuitka-Plugins:data-files: Included data file 'certifi/cacert.pem' due to package data for        
Nuitka-Plugins:data-files: 'certifi'.
Nuitka-Plugins:data-files: Included data file 'jaraco/text/Lorem ipsum.txt' due to package data for
Nuitka-Plugins:data-files: 'jaraco.text'.
Nuitka: Keeping build directory 'mypackage.build'.
Nuitka: Successfully created 'mypackage.dist/mypackage.bin'.
```

- My package structure: 
```
mypackage/
----  __init__.py
----  __main__.py
---- other.sub.packages/
```

- I also created a Dockerfile for creating a clean build:
```
# Use an official Python runtime as a parent image
FROM debian:bullseye-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    musl-dev \
    libportaudio2 \
    ffmpeg \
    python3 \
    python3-pip \
    patchelf \
    ccache \
    && rm -rf /var/lib/apt/lists/*

# Create symlink for musl
RUN ln -s /usr/lib/x86_64-linux-musl/libc.so /lib/libc.musl-x86_64.so.1

# Copy the current directory contents into the container at /app
COPY model/ /app/model/
COPY config.yaml /app/
COPY dist/mypackage-3.1.2-py3-none-any.whl /app/mypackage-3.1.2-py3-none-any.whl
COPY simatic/ /app/simatic/
COPY vm_panel_setup.sh /app/
COPY data/ /app/data/
COPY nuitka-custom.txt /app/

# Set environment variable
ENV CONFIG_PATH=/app/config.yaml

# Create cache directory
RUN mkdir .cache

# Install Python dependencies
RUN TMPDIR=.cache CMAKE_ARGS="-DLLAMA_NATIVE=off" pip install llama-cpp-python==0.2.78 --force-reinstall --cache-dir .cache --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cpu
RUN TMPDIR=.cache pip3 install wheel webrtcvad --cache-dir .cache
RUN TMPDIR=.cache pip install numpy==1.26.0 --cache-dir .cache
RUN TMPDIR=.cache pip install mypackage-3.1.2-py3-none-any.whl  --cache-dir .cache --extra-index-url https://download.pytorch.org/whl/cpu --ignore-installed PyYAML
RUN TMPDIR=.cache pip install nltk==3.8.1 --cache-dir .cache
RUN TMPDIR=.cache pip install nuitka --cache-dir .cache

RUN python3 --version

RUN cat nuitka-custom.txt >> /usr/local/lib/python3.9/dist-packages/nuitka/plugins/standard/standard.nuitka-package.config.yml

# Download NLTK data
RUN python3 -m nltk.downloader punkt wordnet stopwords punkt_tab
```

**Comment by luozhengdong** [comment] 2024-08-26 14:32
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by paozhuanis1** [comment] 2024-08-26 14:32
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by kayhayen** [comment] 2024-11-16 15:30
Thanks, looks good to me, although the suffix and dest_path are the default. For fun I am checking if macOS is similar, and it seems to be the case.

**Comment by kayhayen** [comment] 2024-11-16 15:39
No reproducer was given, but `import llama_cpp` is one, no docker file needed at all.

**Comment by kayhayen** [comment] 2024-11-16 15:48
The config seems to be missing the `relative_path` as the PyPI packages have it living below a `lib` folder, and for Windows, there is no real prefix, so the config shouldn't even do that and specify it as empty, which is OK for DLL folders anyway.

**Comment by kayhayen** [comment] 2024-11-16 15:50
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-11-17 08:08
Part of the 2.5.1 hotfix release.

**Closed by kayhayen** 2024-11-17 08:08 UTC
Labels: enhancement, factory, excellent_report
