### ISSUE TITLE
Nuitka takes extremely long time to compile

### ISSUE THREAD

**Issue by hashuser** [Nuitka/Nuitka#1397] opened 2022-01-28 04:57 UTC
Problem: I tried to compile a file, Nuitka spent way more time than I expected, and process bar stuck at 301/301, while CPU utilization is 0%.  After about half hour, I've to use Ctrl-C to manually end the process. To my surprise, after I enter Ctrl-C it magically continue and finish its compiling process. 

**SOFTWARE ENVIRONMENT**
Windows10 21H2
Nuitka 0.6.19.4
Python 3.9.10

**HARDWARE ENVIRONMENT**
Ryzen7 1700
32GB DDR4-2666
SN750 500G

**COMMAND**
```
nuitka --mingw64 --standalone --plugin-enable=multiprocessing --plugin-enable=pyqt5 --plugin-enable=numpy --plugin-enable=tk-inter --include-module=matplotlib.pyplot --output-dir=C:\Users\home\Desktop\Python\1 C:\Users\Home\PycharmProjects\gambling_simulator\main.py
```

**OUT-PUT**
```
Nuitka:INFO: Completed Python level compilation and optimization.
Nuitka:INFO: Generating source code for C backend compiler.
Nuitka:INFO: Running data composer tool for optimal constant value handling.
Nuitka:INFO: Running C compilation via Scons.
Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
Nuitka-Scons:INFO: Running 'C:\\Users\\Home\\AppData\\Local\\Nuitka\\Nuitka\\gcc\\x86_64\\11.2.0-12.0.1-9.0.0-r1\\mingw64\\bin\\gcc.exe -o "C:\\Users\\home\\Desktop\\Python\\1\\MAIN~1.DIS\\main.exe" -fuse-linker-plugin -flto=16 -fpartial-inlining -freorder-functions -Wl,--exclude-all-symbols -Wl,--out-implib,.\\import.lib -municode -O3 -Wl,--stack,9863168 -Wl,--enable-auto-import -s -static-libgcc @".\\@link_input.txt" -LC:\\Users\\home\\AppData\\Local\\Programs\\Python\\Python39\\libs -lm -lpython39' took 1725.83 seconds
Nuitka-Scons:INFO: Compiled 301 C files using ccache.
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 294
Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 7
Nuitka-Plugins:INFO: pyqt5: Including Qt plugins 'iconengines,imageformats,mediaservice,platforms,platformthemes,printsupport,styles' below 'PyQt5\qt-plugins'.
Nuitka-Plugins:INFO: pyqt5: Found 2 files DLLs from 'OpenSSL' PyQt5installation.
Nuitka-Plugins:INFO: numpy: Found 1 file DLLs from '' numpyinstallation.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\Grammar3.9.10.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: data-files: Included data file 'lib2to3\PatternGrammar3.9.10.final.0.pickle' due to package data for 'lib2to3.pgen2'.
Nuitka-Plugins:INFO: matplotlib: Included data dir 'matplotlib\\mpl-data' with 183 files due to: package data for 'matplotlib.
Nuitka-Plugins:INFO: matplotlib: Included data file 'matplotlib\mpl-data\matplotlibrc' due to Updated matplotlib config file with backend to use..
Nuitka:INFO: Keeping build directory 'C:\\Users\\home\\Desktop\\Python\\1\\main.build'.
Nuitka:INFO: Successfully created 'C:\\Users\\home\\Desktop\\Python\\1\\main.dist\\main.exe'.
```

**Code**
```Python
from matplotlib import pyplot
import random
import time
import multiprocessing
import os


class coin():
    def __init__(self,balance,bet_rate,repeat):
        self.balance = balance
        self.bet_rate = bet_rate
        self.repeat = repeat

    def get_probability(self):
        s = time.perf_counter()
        x_axis, y_axis, tasks = [], [], []
        distribution = self.get_tasks_balanced_complexity(1,self.repeat+1,os.cpu_count()-1)
        pool = multiprocessing.Pool(processes=len(distribution))
        for x in distribution:
            tasks.append(pool.apply_async(self.worker,args=(x[0],x[1])))
        pool.close()
        pool.join()
        for x in tasks:
            x_a, y_a = x.get()
            x_axis += x_a
            y_axis += y_a
        e = time.perf_counter()
        print(round(e - s, 2), 's')
        pyplot.plot(x_axis, y_axis, color='#000000')
        pyplot.show()

    def worker(self,start,end):
        x_axis, y_axis = [], []
        for x in range(start,end):
            #print('Worker-'+str(os.getpid())+':',str(round((x-start)/(end-start),2)*100)+'%')
            win = 0
            for y in range(10000):
                balance = self.run_simulation(self.balance, x)
                if balance > self.balance:
                    win += 1
            y_axis.append(win/10000)
            x_axis.append(x)
        return x_axis, y_axis

    def run_simulation(self,balance,repeat):
        for x in range(repeat):
            bet = self.bet_rate * balance
            balance -= bet
            while True:
                R = random.random()
                if R > 0.5:
                    balance += bet * 2
                    break
                elif R < 0.5:
                    break
        return balance

    @staticmethod
    def get_tasks_balanced_complexity(start,end,number):
        task = []
        sum = (start + end - 1) * (end - start) / 2
        complexity = sum / number
        while start < end:
            for x in range(start, end):
                if ((start + x) * (x - start + 1) / 2) / complexity >= 1.0:
                    task.append((start, x))
                    break
                elif ((start + end - 1) * (end - start) / 2) <= complexity:
                    task.append((start, end))
                    break
            if task[-1][0] != task[-1][1]:
                start = task[-1][1]
            else:
                start = task[-1][1] + 1
        print(task)
        return task


if __name__ == '__main__':
    coin(1000,0.05,int(input())).get_probability()
```

**Comment by hashuser** [comment] 2022-01-28 05:19
In addition, is it possible for Nuitka Commercial adding an alternative payment method like Alipay? Card payment is not convenient in all countries.

**Comment by kayhayen** [comment] 2022-01-28 09:05
There are alternatives depending on location. Stripe has informed me that I do not qualify for Alipay, but bank transfer, credit card, Google Pay, Apple Pay ought to all work, unless you use Firefox with an ad blocker, or Javascript blocker of some sorts. I will also accept Paypal if you want to go there.

What see you see there is the final LTO link. Depending on program size, it can explode. Either use develop version or enable the --anti-bloat plugin, it will make numpy and matplotlib compile much less. A swallowed CTRL-C is concerning and should not happen, I will attempt if that's a reproducible thing.

**Comment by kayhayen** [comment] 2022-01-28 09:06
I would try anti-bloat first, then maybe --lto=no, and definitely using MSVC as well, as it's often more scalable.

**Comment by hashuser** [comment] 2022-01-28 12:50
Thank you! I've tried anti-bloat, it has some minor help. In addition, I found I made a huge mistake. CPU utilization is actually not 0%, while a process called ```lto1.exe``` is created. With ```--lto=no```, huge speed up has gain.

**Comment by hashuser** [comment] 2022-01-28 13:19
I also did some research, and I found a thing called ```ThinLTO```, which can significant reduce build time while keeping most advantages of LTO.

**Comment by hashuser** [comment] 2022-01-29 09:08
I first install ```LLVM-13.0.0-win64```, and then I switch compiler to clang.  I found the ```.exe``` produce by clang has similar speed as ```.exe``` produce by mingw64 with LTO off. So I lookuped codes in ```SconsCompilerSettings.py```. In order to investigate what really happened, I add a line of code in line [163](https://github.com/Nuitka/Nuitka/blob/7b4c3f8f1a16ed62eb7d7b067d0a004bc409bfa2/nuitka/build/SconsCompilerSettings.py#L163).
```python
print("gcc", env.gcc_mode, "mingw", env.mingw_mode, "clang", env.clang_mode, "clangcl", env.clangcl_mode, "msvc", env.msvc_mode, "lto", lto_mode)
```
I then rerun Nuitka, and the result is stunning.
```gcc False mingw False clang False clangcl True msvc True lto True```

My question is why both ```env.clangcl_mode``` and ```env.msvc_mode``` is True? Why ```lto_mode``` is True, but LTO seems not working.

**COMMAND**
```
nuitka --clang --standalone --plugin-enable=multiprocessing --plugin-enable=pyqt5 --plugin-enable=numpy --plugin-enable=tk-inter --include-module=matplotlib.pyplot --output-dir=C:\Users\home\Desktop\Python\3 C:\Users\Home\PycharmProjects\gambling_simulator\main.py
```

**Comment by hashuser** [comment] 2022-01-29 09:27
I found env.msvc_mode is first defined in [```Backend.scons```](https://github.com/Nuitka/Nuitka/blob/7b4c3f8f1a16ed62eb7d7b067d0a004bc409bfa2/nuitka/build/Backend.scons#L396)
![image](https://user-images.githubusercontent.com/60065064/151655567-d0740430-1847-4a62-a69e-568da9007c3d.png)

**Comment by kayhayen** [comment] 2022-01-29 09:52
LLVM is not capable of compiling under Windows by itself, it does not have a Windows SDK, but MinGW64 and MSVC do.

The ClangCL can be used with MSVC, and should then be installed via the installer of theirs. The LLVM installation you made, can be used when MSVC is used as well. With `--clang --mingw64` it will use the Clang that is contained in winlibs, and with `--clang --msvc=latest` it will use it with MSVC.

For mosts intents and purposes, ClangCL and Clang are the same as MSVC and gcc with their options, that is apparently one of their goal. So `clang_mode` and `clangcl_mode` are more like sub modes of `msvc_mode` and `gcc_mode`.

Generally, so far, I have not found reasons to use Clang on Windows. Some say it's more scalable, not sure if that's really true though. And since on Windows currently winlibs clang doesn't even to LTO and therefore not PGO, my interest is low. I have however raise an issue with winlibs, and potentially it's going to be fixed in a future release. LTO with winlibs gcc is also relatively new.

**Comment by hashuser** [comment] 2022-01-29 10:05
@kayhayen Thank you very much!

**Comment by kayhayen** [comment] 2022-05-26 18:39
Due to recent anti-bloat work, and I am just doing some more right now on this, it compiled relatively quickly for me. It picks up an installed `tornado` package, not sure if that is necessary.

**Closed** 2022-06-02 08:54 UTC
Labels: enhancement

**Comment by huangxin168** [comment] 2022-08-08 16:26
I also have this problem, and used  --lto=no  to solve it...

**Comment by kayhayen** [comment] 2022-08-08 18:52
@huangxin168 posting below closed issues is a surefire way to get ignored.
