### ISSUE TITLE
Issue when including Pandas library 0.25.3 on Linux

### ISSUE THREAD

**Issue by cvpython** [Nuitka/Nuitka#795] opened 2020-07-22 09:15 UTC
I face to an issue similar to #557.

I have a simple script :
`import pandas as pd`
`print("hello world")`

I try to create an exe with the hinted approach:
`python get-hints.py script.py`
`python nuitka-hints.py script.py`

The compilation successes.
Here are the scripts used for the compilation: [bug_pandas.zip](https://github.com/Nuitka/Nuitka/files/4959000/bug_pandas.zip)

However, at runtime it crashes:
`./hello.dist/hello`
> Traceback (most recent call last):
>   File "bug_pandas/hello.dist/hello.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "bug_pandas/hello.dist/pandas/__init__.py", line 30, in <module pandas>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "bug_pandas/hello.dist/pandas/_libs/__init__.py", line 3, in <module pandas._libs>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "bug_pandas/hello.dist/pandas/_libs/tslibs/__init__.py", line 3, in <module pandas._libs.tslibs>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "pandas/_libs/tslibs/c_timestamp.pxd", line 7, in init pandas._libs.tslibs.conversion
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "pandas/_libs/tslibs/c_timestamp.pyx", line 1, in init pandas._libs.tslibs.c_timestamp
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "pandas/_libs/tslibs/tzconversion.pyx", line 1, in init pandas._libs.tslibs.tzconversion
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "pandas/_libs/tslibs/c_timestamp.pxd", line 7, in init pandas._libs.tslibs.timedeltas
> AttributeError: module 'pandas._libs.tslibs.c_timestamp' has no attribute '_Timestamp'

Here are some information about my configuration:

`python -m nuitka --version`
> 0.6.8.4
> Python: 3.7.6 | packaged by conda-forge | (default, Jun  1 2020, 18:57:50) 
> Executable: anaconda3/envs/exe_pandas/bin/python
> OS: Linux
> Arch: x86_64

`conda list`

> packages in environment at anaconda3/envs/exe_pandas:

> Name                    Version                   Build  Channel
> _libgcc_mutex             0.1                 conda_forge    conda-forge
> _openmp_mutex             4.5                       0_gnu    conda-forge
> ca-certificates           2020.6.24                     0  
> certifi                   2020.6.20                py37_0  
> ld_impl_linux-64          2.34                 h53a641e_7    conda-forge
> libblas                   3.8.0               17_openblas    conda-forge
> libcblas                  3.8.0               17_openblas    conda-forge
> libffi                    3.2.1             he1b5a44_1007    conda-forge
> libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
> libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
> libgomp                   9.2.0                h24d8f2e_2    conda-forge
> liblapack                 3.8.0               17_openblas    conda-forge
> libopenblas               0.3.10          pthreads_hb3c22a3_3    conda-forge
> libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
> ncurses                   6.2                  he1b5a44_1    conda-forge
> nuitka                    0.6.8.4            pyh9f0ad1d_0    conda-forge
> numpy                     1.19.0           py37h8960a57_0    conda-forge
> openssl                   1.1.1g               h7b6447c_0  
> pandas                    0.25.3           py37he6710b0_0  
> pip                       20.1.1                     py_1    conda-forge
> python                    3.7.6           cpython_h8356626_6    conda-forge
> python-dateutil           2.8.1                      py_0    conda-forge
> python_abi                3.7                     1_cp37m    conda-forge
> pytz                      2020.1             pyh9f0ad1d_0    conda-forge
> readline                  8.0                  he28a2e2_2    conda-forge
> setuptools                49.2.0           py37hc8dfbb8_0    conda-forge
> six                       1.15.0             pyh9f0ad1d_0    conda-forge
> sqlite                    3.32.3               hcee41ef_1    conda-forge
> tk                        8.6.10               hed695b0_0    conda-forge
> wheel                     0.34.2                     py_1    conda-forge
> xz                        5.2.5                h516909a_1    conda-forge
> zlib                      1.2.11            h516909a_1006    conda-forge

**Please note that this problem happens only on my ubuntu session.
There is no problem when compiling on windows (with the same version of nuitka and pandas).**

**Comment by kayhayen** [comment] 2020-07-28 08:18
This is a duplicate of #775

**Closed by kayhayen** 2020-07-28 08:18 UTC
