### ISSUE TITLE
Nutika not working with lttbc ImportError: numpy._core.multiarray failed to import

### ISSUE THREAD

**Issue by sistemicorp** [Nuitka/Nuitka#3168] opened 2024-10-24 20:50 UTC
NOTE: I resolved this issue as shown below and posting in case you want to add it to your list of implicit imports.

- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version
```
2.4.9
Commercial: 2.6.3
Python: 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
Flavor: CPython Official
Executable: C:\git\a48-P1150DPGApp\venv312\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 11
Version C compiler: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\Hostx64\x64\cl.exe (cl 14.3).
```

- Provide in your issue the Nuitka options used
```
Nuitka-Options: Used command line options: --remove-output --standalone --msvc=latest --assume-yes-for-downloads --onefile --onefile-tempdir-spec={TEMP}\sistemi\p1150_client --windows-company-name=sistemi
Nuitka-Options: --noinclude-setuptools-mode=nofollow --noinclude-pydoc-mode=nofollow --noinclude-pytest-mode=nofollow --noinclude-unittest-mode=nofollow --follow-import-to=numpy --report=report_winx86_0_10_160.xml
Nuitka-Options: --windows-product-name=p1150_client --windows-file-version=0.10.160 --windows-product-version=0.10.160 --output-filename=p1150_winx86_0_10_160 --include-data-dir=C:\git\a48-P1150DPGApp/assets=assets
Nuitka-Options: p1150_client.py
Nuitka: Starting Python compilation with Nuitka '2.4.9' on Python '3.12' commercial grade '2.6.3'.
```
Note: `--follow-import-to=numpy` was an attempt to fix the error, but this had no effect.

- Output of EXE
```
ModuleNotFoundError: No module named 'numpy'
Traceback (most recent call last):
  File "C:\Users\marti\AppData\Local\Temp\sistemi\P1150_~1\p1150_client.py", line 56, in <module>
    from gui_plots_klass import Plots

  File "C:\Users\marti\AppData\Local\Temp\sistemi\P1150_~1\gui_plots_klass.py", line 14, in <module gui_plots_klass>
    from gui_logger import Logger

  File "C:\Users\marti\AppData\Local\Temp\sistemi\P1150_~1\gui_logger.py", line 10, in <module gui_logger>
    import lttbc

ImportError: numpy._core.multiarray failed to import
```

- Solution
```
- module-name: 'lttbc'
  implicit-imports:
    - depends:
        - 'numpy.core.multiarray'
```
Note: `--follow-import-to=numpy` was removed from the Nuitka args.

**Comment by kayhayen** [comment] 2024-10-25 08:38
Thanks for the report, that's great. I am adding it for the 2.5 release.

**Comment by kayhayen** [comment] 2024-10-29 17:09
Part of the current pre-release and will be in 2.5 once released.

**Comment by zincers** [comment] 2024-11-07 13:33
same error when import `pickle`,
fixed by add implicit-import to `stdlib3.nuitka-package.config.yml`.
python 3.12.7 + nuitka 2.4.11 + numpy 2.1.2

**Comment by kayhayen** [comment] 2024-11-11 14:34
@zincers 

Posting below closed issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made, and I am not going to trace, or remember to check later, or searching for where something was said. Please open new issues for new issues. If the issue is closed, it's not the same even if the symptom looks similar to you.

**Comment by zincers** [comment] 2024-11-13 03:55
@kayhayen  
Thanks for the reminder! I initially thought it was the same problem as this issue and #3140  and would be easy to reproduce, so I just commented here instead of opening a new issue. The solutions for those two issues also worked for me, which made me jump to this conclusion a bit too quickly. But when I dug into it, I realized it was way more complicated than I thought.

The final conclusion is that this issue is due to I was trying to use pickle(Python 3) to load a pkl file generated by Python 2.7.x pickle. To start with, I don't think my issue needs much attention, since Python 2's lifecycle has been over for a while now. I'll show the process of reproducing this issue in case you're interested.


### Reproduction Process
generate_pkl_file.py
```python
#-*- coding:utf-8 -*-

import numpy as np
import pickle
import zlib

original_data = {
    'slice': [0.0, 1.0], 
    'data': {
        "sec1": np.zeros(5), 
        "sec2": np.ones(5), 
    }
}

with open("demo_py2.pkl", 'wb') as fh:
    fh.write(zlib.compress(pickle.dumps(original_data, protocol=2)))
fh.close()
```

Generate two test files(`demo_py2.pkl` and `demo_py3.pkl`) using this script in both Python 2 (for me, 2.7.18) and Python 3 (for me, 3.12.7)environments. Adjust the filenames as needed during the process.


test.py
```python
#-*- coding:utf-8 -*-

# import numpy.core.multiarray
import numpy as np
import pickle
import zlib


final_data = pickle.loads(zlib.decompress(open("demo_py3.pkl", 'rb').read()), encoding='latin1')
print("Python 3:\n", final_data)

final_data = pickle.loads(zlib.decompress(open("demo_py2.pkl", 'rb').read()), encoding='latin1')
print("Python 2:\n", final_data)

```

Compile this script using Nuitka(for me, 2.4.11) with the following command. Please keep `import numpy.core.multiarray` line is commented out

```shell
python -m nuitka --msvc=latest --standalone .\test.py
```


After compiling, run the generated `.\test.dist\test.exe` file to reproduce the issue. The output:

```python
Python 3:
 {'slice': [0.0, 1.0], 'data': {'sec1': array([0., 0., 0., 0., 0.]), 'sec2': array([1., 1., 1., 1., 1.])}}
Traceback (most recent call last):
  File "path\to\test.dist\test.py", line 12, in <module>
ModuleNotFoundError: No module named 'numpy.core.multiarray'
```
By the way, I tested nuitka versions 2.4.8 to 2.4.11 and found that they all have the same output. 
I did not test lower versions because they trigger other warnings, so I stopped there.

### Solution

- Solution 1: 
As mentioned in my previous comment, add `implicit-import` to `path\to\myenv\Lib\site-packages\nuitka\plugins\standard stdlib3.nuitka-package.config.yml`

```yaml
- module-name: 'pickle' # checksum: 167cb032
  implicit-imports:  
    - depends:
      - 'numpy.core.multiarray'
  anti-bloat:        
    - description: 'remove module ability to run as a binary'
      change_function:
        '_test': "'(lambda: None)'"
```

-  Solution 2:
Simply adding the import statement `import numpy.core.multiarray` before `pickle.loads` function should resolve the issue.
This solution meets my requirements, as in my entire project, this function is only used in one specific location, so the impact of this solution is minimal.

**Comment by kayhayen** [comment] 2024-11-13 08:29
@zincers I am not even going to read what you wrote if you don't read what I wrote,  reply once more in this unrelated issue and I will take serious offense

**Comment by kayhayen** [comment] 2024-11-16 12:44
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:44 UTC
Labels: bug, develop, excellent_report
