### ISSUE TITLE
Ubuntu 24.04 Python needs to be supported (was Building xonsh shell with python 3.12: scons backend failure)

### ISSUE THREAD

**Issue by anki-code** [Nuitka/Nuitka#2913] opened 2024-06-09 15:46 UTC
Hello! Thank you for nuitka!
In [xonsh-binary](https://github.com/anki-code/xonsh-binary) project I'm trying to build xonsh shell standalone binary using Nuitka 2.3.1 and Python 3.12 on Ubuntu in docker but faced with "scons backend failure". I read in the [user manual](https://nuitka.net/user-documentation/user-manual.html) - "For Linux, use either the GCC from the system or an installed clang.". And I don't understand the source of the issue because GCC presented in Ubuntu. 
Could you please help me resolve this? Many thanks for your help!

Here is full commands list to repeat:
```xsh
docker run --rm -it ubuntu:24.04 bash
apt update && apt install --yes patchelf python3-full python3-pip gcc make zlib1g-dev git
pip3 install --break-system-packages nuitka zstandard 
pip3 install --break-system-packages 'xonsh[full]' && pip3 uninstall --break-system-packages -y xonsh
cd /
git clone -n https://github.com/xonsh/xonsh && cd xonsh && git checkout 0.15.1
cd /xonsh
nuitka3 --static-libpython=yes --standalone --onefile --onefile-tempdir-spec='%TEMP%/onefile_%PID%_%TIME%' xonsh
```
Result:
```
Nuitka-Scons: Backend C compiler: gcc (gcc 13).
Nuitka-Scons: Backend linking program with 346 files (no progress information available for this
Nuitka-Scons: stage).
/usr/bin/ld: /usr/lib/python3.12/config-3.12-aarch64-linux-gnu/libpython3.12.a(bytearrayobject.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `__stack_chk_guard@@GLIBC_2.17' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/lib/python3.12/config-3.12-aarch64-linux-gnu/libpython3.12.a(bytearrayobject.o)(.text.hot+0x39dc): unresolvable R_AARCH64_ADR_PREL_PG_HI21 relocation against symbol `__stack_chk_guard@@GLIBC_2.17'
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
scons: *** [/xonsh/xonsh.dist/xonsh.bin] Error 1
FATAL: Failed unexpectedly in Scons C backend compilation.

Nuitka:WARNING:     Complex topic! More information can be found at
Nuitka:WARNING: https://nuitka.net/info/scons-backend-failure.html
Nuitka-Reports: Compilation crash report written to file 'nuitka-crash-report.xml'.
```

Report: [nuitka-crash-report.xml.txt](https://github.com/user-attachments/files/15753126/nuitka-crash-report.xml.txt)

**Comment by kayhayen** [comment] 2024-06-10 08:06
You should remove the static-libpython option, it's not working for you I assume and put it to `no`. I think Nuitka might even be doing it automatically for Debian Python to yes, but your flavor is unknown, so that is strange. I have no had any luck with installing a Ubuntu 24.04 in my Virtualbox (won't boot to CPU lockup with latest version of it even), so I might have to resort to running it in a container too, long live `run-nuitka-inside-container`, which I need to check after my latest podman upgrades anyway.

**Comment by kayhayen** [comment] 2024-06-10 08:36
Ah, got it, for Python3.12 from Debian, my check is not going to cut it very well anymore.

```
        with withNoDeprecationWarning():
            try:
                from distutils.dir_util import _multiarch
            except ImportError:
                return False
            else:
                return True
```

I was relying on a long standing Debian patch, that they use for their "multiarch" stuff, which in 3.12 is definitely not exactly there anymore, at least not in `distutils` as that got removed in 3.12, giving the import error we see there.

**Comment by kayhayen** [comment] 2024-06-10 08:47
I managed to reproduce the issue, if I head the information given that static libpython might work, but could give errors. Now I need to figure out how to detect it. From my cursory looks though, Debian Python detected is only used to decide in scons to use LTO mode, which doesn't change things, it might be that Debian Python is no longer usable for static libpython which is a shame as it will incur a performance penalty, so far Debian Python has been relatively good base build.

For perfomance we might start to consider adding something that re-compiles Python from source, but that drops Debian patch level compatibility of course. But I have to think, maybe using -fPIE when creating things is a problem here, but I believe it's normally needed to expose the Python C-API to extension modules, so maybe it's salvagable.

**Comment by kayhayen** [comment] 2024-06-10 09:07
So, disabling PIE gets the error changed, now it is missing symbols, there might be more link libraries needed. I am getting those:

```
/usr/bin/ld: /usr/lib/python3.12/config-3.12-x86_64-linux-gnu/libpython3.12.a(sha2module.o): in function `_sha2_sha512':
(.text+0x2f6): undefined reference to `python_hashlib_Hacl_Hash_SHA2_malloc_512'
```

Many more symbols missing, but all from the same sha2 and it might just be somewhere else.

Turns out, I am stupid, I should fix the detection bug first and foremost, since that symbol is used by the -pic variant once that detection returns `True`.

**Comment by kayhayen** [comment] 2024-06-10 10:50
I currently only have things for Nuitka commercial, but I plan to make it more public, but currently lack the time. I am trying to figure out how to support Debian Python. At least the detection side is solved. 

I think I also figured out, that the hashlib functions there, are supposed to come from, so that is the immediate focus now, to resolve those undefined functions. In general older Debian plus backport might be good.

**Comment by kayhayen** [comment] 2024-06-11 07:05
So, I think Debian/Ubuntu Python 3.12 has a flaw that in that the static link library requires code that is not available, which is really bad bug, but that LTS version. Now do I have hopes they will fix it, no. So basically what I am doing now, is to include the inline copy of hacl from Python into Nuitka, it's ASF2 licensed, so no problem with that and it seems only one file was left one, one that ends up as a link library, so clearly a bug, but I got the workaround now.

**Comment by kayhayen** [comment] 2024-06-11 07:46
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-06-11 11:12
Now that's a bug with my recent match work it seems, I will check it out.

**Comment by kayhayen** [comment] 2024-06-11 11:16
Please retry with latest factory, it's fixed there and thanks for the report.

**Comment by kayhayen** [comment] 2024-06-11 11:28
Also my attempt to include it in the 2.3.3 hotfix should fail, as I think the new inline copy files will not be pip installed, but there is going to be a 2.3.4 for sure anyway.

**Comment by kayhayen** [comment] 2024-06-11 12:51
My remote machine reading skills are unfortunately underdeveloped.

**Comment by kayhayen** [comment] 2024-06-11 12:51
Try compiling with --debug and see if it gives an assertion or so.

**Comment by kayhayen** [comment] 2024-06-20 18:43
For the time being --experimental=allow-c-warnings can be required, this will debug a sub-option of --debug eventually.

**Comment by kayhayen** [comment] 2024-06-20 18:45
It appears you have some kind of corruption bug going on. I would need the backtrace to know more, can you try to run it directly with `--run --debugger` from the compilation.

**Comment by kayhayen** [comment] 2024-06-20 22:34
Today I realized, that the most efficient way to build very portable binaries might be using Anaconda. Once 2.3.8 comes out, it should depend on a C compiler and produce good and portable binaries for Linux in easy mode, provided my dependency on "c-ompiler" actually works.

**Comment by kayhayen** [comment] 2024-06-21 13:33
I quit using Anaconda years ago because conda was slow, but it's acceptable these days, so I don't venture into other tools, I guess they don't make a difference for me anyway.

```
# conda create -n nuitka_install_test
# conda activate nuitka_install_test
# conda install -c conda-forge nuitka
# python -m nuitka --version
2.3.9
Commercial: None
Python: 3.11.9 (main, Apr 19 2024, 16:48:06) [GCC 11.2.0]
Flavor: Anaconda Python
Executable: /home/hayen/anaconda3/envs/nuitka_install_test/bin/python
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 22.04.4
Version C compiler: ~/anaconda3/envs/nuitka_install_test/bin/x86_64-conda-linux-gnu-gcc (x86_64-conda-linux-gnu-gcc 11.2.0).
# python -m nuitka --stand empty.py
# ldd -v empty.dist/empty.bin 
        linux-vdso.so.1 (0x00007ffc9275d000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f8872064000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f8871f7d000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f8871f78000)
        libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f8871f73000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f8871f6e000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f8871d43000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f887207a000)

        Version information:
        empty.dist/empty.bin:
                librt.so.1 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/librt.so.1
                libdl.so.2 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libdl.so.2
                libutil.so.1 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libutil.so.1
                libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
                libpthread.so.0 (GLIBC_2.3.3) => /lib/x86_64-linux-gnu/libpthread.so.0
                libpthread.so.0 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libpthread.so.0
                libpthread.so.0 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libpthread.so.0
                libc.so.6 (GLIBC_2.10) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.9) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.6) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.7) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.3) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libdl.so.2:
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libm.so.6:
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
                libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libpthread.so.0:
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libutil.so.1:
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/librt.so.1:
                libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
                libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6
        /lib/x86_64-linux-gnu/libc.so.6:
                ld-linux-x86-64.so.2 (GLIBC_2.2.5) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
                ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
```

**Comment by kayhayen** [comment] 2024-06-21 13:36
If you look it up, the output is evidence of being built against a CentOS 7 toolchain, in fact, the Anaconda c-compiler on Linux has cos7 in its name in some places.

The new Ubuntu LTS Python build chain seems as broken as it gets. I am not sure there is Anaconda for aarch64, but if there is, Nuitka doesn't yet pick it up automatically. Is there such a thing?

**Comment by kayhayen** [comment] 2024-06-23 11:36
Any input here?

**Comment by kayhayen** [comment] 2024-06-23 12:28
That's the wrong way of building Python for portability, unfortunately. I cannot personally support you here how to do it, but from past experience the libpython coming out of that approach is unusable. I am closing this as a duplicate of the tasks that I already have to public Linux standalone containers for CentOS 8.

**Closed by kayhayen** 2024-06-23 12:28 UTC
Labels: bug, factory

**Comment by kayhayen** [comment] 2024-06-23 12:32
The original report is more to be attributed to newest Ubuntu being unusable with libpython. Due to the lack of version output in the original report I cannot tell if I fixed it or not, but I assume it might be.

**Comment by kayhayen** [comment] 2024-06-24 06:32
Posting below closed issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made, and I am not going to trace, or remember to check later, or searching for where something was said. Please open new issues for new issues. If the issue is closed, it's not the same even if the symptom looks similar to you.
