### ISSUE TITLE
Numpy 1.18 not working with Nuitka

### ISSUE THREAD

**Issue by Barbabela** [Nuitka/Nuitka#736] opened 2020-06-02 22:25 UTC
Hi,

First post here.

I just started with Nuitka but may have found a problem with the new releases of Numpy.

Running WinPython 3.8.2 on Windows (64-bits)
Nuitka 0.6.8.3
Numpy 1.18.4

This issue seems to be related to https://github.com/Nuitka/Nuitka/issues/677 but that link was closed without presenting a solution. Therefore I initiated a new issue. Please be free to merge both issues if they are indeed related.

I created a simple python script called "hello_numpy.py" which is basically the "hello.py" from the User Manual with an "import numpy" call.
```
import numpy
def talk(message):
	return 'Talk ' + message
def main():
	print(talk('Hello World'))
if __name__ == '__main__':
	main()
``` 
I tried to compile with "--enable-plugin=numpy" and "--plugin-enable=numpy" since I found references to both styles (I later checked in the code and they are actually equivalent).

The program was compiled but failed to execute. I identified that at some point, most of DLLs at "numpy/core" where moved to a new folder called "numpy/DLLs". I tryed to modify "NumpyPlugin.py" including the following code at line 88:
```
# second look in numpy/DLLs for binaries
libdir = os.path.join(numpy_dir, "DLLs")
suffix_start = len(libdir) + 1
if os.path.isdir(libdir):
    dlls_pkg = os.listdir(libdir)
    binaries += [[os.path.join(libdir, f), suffix_start] for f in dlls_pkg]
```
This modification allowed the DLLs to be copyed to the "dist" folder as expected which partially solved the issue. However there was a persisting problem with "numpy/random" which was also significantly modified form previous Numpy releases. The problem seems to be a circular import of "BitGenerator" class at module level in "_bit_denerator*.pyd" file at "numpy/random" folder. At this moment I was unable to identify what is wrong. I'll try to look further into this whenever I have some time on the next few days. 
```
Traceback (most recent call last):
  File "C:\_PYTHON\RELEASE\TESTE\HELLO_~1.DIS\hello_numpy.py", line 1, in <module>
    import numpy
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\_PYTHON\RELEASE\TESTE\HELLO_~1.DIS\numpy\__init__.py", line 152, in <module numpy>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\_PYTHON\RELEASE\TESTE\HELLO_~1.DIS\numpy\random\__init__.py", line 181, in <module numpy.random>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "C:\_PYTHON\RELEASE\TESTE\HELLO_~1.DIS\numpy\random\_pickle.py", line 1, in <module numpy.random._pickle>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "_bit_generator.pxd", line 14, in init numpy.random.mtrand
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "_bit_generator.pyx", line 1, in init numpy.random._bit_generator
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "_bit_generator.pxd", line 14, in init numpy.random._common
AttributeError: partially initialized module 'numpy.random._bit_generator' has no attribute 'BitGenerator' (most likely due to a circular import)
```
At the moment I don't use nor intend to use Numpy.random anywhere in my code. So I always have the option to create a broken numpy release by removing any reference to random. But I would really want to avoid that. I hope that someone familiar with both Nuitka and Numpy can propose a better solution.

I'd like to hijack may own post for a slightly related issue. I ended up using Nuitka hinted but it seems to be a problem with the newest release. The detected modules and plugins are loaded by "hinted-mods.py" as a "--user-plugin". It correctly identifies "numpy" and enables it as a plugin. However it fails to activate the "numpy" plugin.  I avoided this by copying the following code on line 555 from "Plugins.py" to line 528:
```
for plugin_class in user_plugins:
     _addActivePlugin(plugin_class, args=True)
```
This forced the user plugins to activate first so when the enabled plugins were activated, "numpy" was already included to the list. For this to work I had to modify the "NumpyPlugin" constructor call to include default values to the parameters:
```
def __init__(self,matplotlib=False, scipy=False):
    ...
```
Nuitka hinted executed with these modifications but I'm unsure if this can lead to some unexpected behavior for a more complex program.

I really liked this tool and hope that these issues can be solved. I'll try to work on this more to identify the possible problem.

Thanks for any help.

**Comment by kayhayen** [comment] 2020-06-03 08:18
Welcome. I hope it's not your last and I do hope it is, your analysis is spot on. The hinted compilation has seemingly not merged a PR of mine yet, that I am not going to now. Can you retry with that, and tell me if it improves things on that end. This has been open for a while, but the maintainers of busy it seems. Hope they don't mind me doing this @deajan and @JorjMcKie as this is too long now, and it can't be much worse.

Nuitka has changed the way plugins are loaded, so it can have proper command line arguments for them too. This was not easy. And in fact, I believe develop version has changes where plugins check if other plugins are loaded, and that wouldn't work with hinted compilation anymore, not sure how much of that might be needed.

Your mini patch from above, I can sort of see, that you have a new `DLL` folder and that's very much likely also the reason, why the NumPy plugin fails to work nowadays.

I looked at the failing module, and it seems a pure C binding from Cython that declares the missing symbol, but I guess, that's maybe how it reacts to no DLL giving it the symbol.

**Comment by kayhayen** [comment] 2020-06-03 08:29
So this is a duplicate, but the better report than #659 which is unsolved. My plan for attacking this is indeed more clear now. Make a dist folder 1.17 and one for 1.18 and see what DLLs we lost/gained, then check out, what's wrong with your code maybe, because it looks like the right idea.

**Comment by kayhayen** [comment] 2020-06-03 11:08
So, I managed to reproduce it on Linux, I like to go there first, as maybe there is indeed some convolution with the DLLs folder on Windows going on. On Linux with 3.8 and 1.17.4 vs. 1.18.4 the only differences were these:

```
 -bit_generator.so
 +_bit_generator.so
```

And that for only extension modules numpy.random there. That's maybe only a naming cleanup, with no impact otherwise.

**Comment by Barbabela** [comment] 2020-06-03 21:24
> So this is a duplicate, but the better report than #659 which is unsolved. My plan for attacking this is indeed more clear now. Make a dist folder 1.17 and one for 1.18 and see what DLLs we lost/gained, then check out, what's wrong with your code maybe, because it looks like the right idea.

I apologize for missing #659. I did a search before solving the DLL folder issue and did not search for the bit_generator again.

I tried to look into Numpy cython code to identify the issue. It seems the problem was introduced when the new class “_pickle” was created and imported before “_common”. The first one calls “bit_generator” which has a BitGenerator class that calls some functions from “_common” and the import breaks. Somehow the normal Numpy execution solves this import issue but when “nuitiking” (?!) the code, it doesn’t. I know a little bit of Cython but since I’m new to how nuitka works, I’m not sure I’ll be of much help until I have more time to have a better look into nuitka documentation. For now I’ll just disable “numpy/random” so I can keep testing nuitka with other packages.

**Comment by kayhayen** [comment] 2020-06-04 06:49
I can confirm indeed that the cyclic import is real. Your analysis is spot on. 

This is an incompatibility of either how extension modules are loaded in Nuitka, there is a 2 phase protocol added in some higher Python version, that we support, but maybe not compatible enough. Or it is again about the `from module import submodule` that imports a module, but not fully compatible.

This is not a hidden dependency, as is often the case with failed imports in packages, but a real incompatibility lurking there. So this is high priority, on the other hand very difficult. As you can imagine, this is very hard to get to the bottom to, esp. as the CPython code is very confusing to me., and the subject is a constantly moving one in Python. I don't really have a spec of how it's supposed to be, the PEPs often describe deltas and then how it's used, is often different too. Time to pity myself. :-)

The numpy 1.17 works for sure though, I think this is entirely new since 1.18 series. It's s shame, but people apparently just downgrade for now and have it all work. So you don't have to hack stuff. No idea, what release was latest there, I just went with a random number to compare distribution files, and it was good. Your Windows DLL issue may also be gone, they probably also changed the layout of files in 1.18 only too.

**Comment by kayhayen** [comment] 2020-06-04 08:24
I found it by looking at CPython code. It puts the module earlier in `sys.modules` and says that avoids a false optimization in its own importing, and when I changed Nuitka to also do this, it appears to work, so I guess, that's the compatible thing to do.

**Comment by Barbabela** [comment] 2020-06-04 14:21
> I found it by looking at CPython code. It puts the module earlier in `sys.modules` and says that avoids a false optimization in its own importing, and when I changed Nuitka to also do this, it appears to work, so I guess, that's the compatible thing to do.

I hope this is the solution. I’m not new to C but I usually loose myself when trying to follow CPython code. I was concerned by your previous message but this was fast :)

I was preparing to downgrade Numpy but it could lead to unforeseen compatibility issues with other packages. It is why I was considering redirecting the random calls to a dummy package for now.

If this solution works, I think I’ll wait for it to be in the development release so I can test is. For now I’m deactivating parts of my code (including the ones that require numpy) for testing (a little feedback: so far very satisfied with Nuitka performance and reduced folder size - a xlwings/pywin32/tkinter solution worked really fast and with only 40MB). I still need to do some adjustments for when the code is __compiled__. So I have plenty to do before activating the Numpy part of the code.

**Comment by kayhayen** [comment] 2020-06-06 09:04
This is part of the 0.6.8.4 release I just made.

**Closed** 2020-06-11 14:11 UTC
Labels: bug, duplicate
