### ISSUE TITLE
ModuleNotFoundError: No module named 'asyncpg.pgproto.pgproto' IN "standalone" 

### ISSUE THREAD

**Issue by bsense-rius** [Nuitka/Nuitka#1420] opened 2022-02-12 10:16 UTC
### **Issue Description**
Compiling and running a simple test.py, that contains a single line of code "import asyncpg", works fine in Use Case 1: python3 -m nuitka --follow-imports test.py.

But after compiling it in Use Case 4 (Program Distribution), without any apparent issues, when I run it fails with the ModuleNotFoundError: No module named 'asyncpg.pgproto.pgproto' error.

Code test.py:
`import asyncpg`

Compilation for Use Case 4 distribution (tried different alternatives) all failing. Each time I run ccache -C to clear cache:
`sudo python3 -m nuitka test.py --standalone`

`sudo python3 -m nuitka test.py --standalone --follow-imports --include-plugin-directory /usr/local/lib/python3.8/dist-packages/asyncpg/pgproto`

As a final remark, in Use case 1 (Program compilation with all modules embedded), if I rename /usr/local/lib/python3.8/dist-packages/asyncpg/pgproto/pgproto.cpython-38-x86_64-linux-gnu.so to a different name, then the program fails to run, **with the very same error that is reported when trying to run the compiled app in standalone mode**. 

Therefore I conclude that **the main issue for the standalone compilation is the lack of processing the pgproto.cpython-38-x86_64-linux-gnu.so  file**. I tried to "force" the plugin directory without success. Is there any "manual" way to make this file to be processed? 

Thanks a lot for this massive and impressive work!

### **Requested Information**

* Nuitka version, full Python version, flavor, OS, etc. as output by this
  command (it does more than you think, and we are adding more all the time):

  > python3 -m nuitka --version
0.6.19.6
Commercial: None
Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
Flavor: Debian Python
Executable: /usr/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu 20.04.2

* How did you install Nuitka and Python
$  python3 -m pip install nuitka

* Did you use pip, anaconda, deb, rpm, from source, git clone, then install into a virtualenv or not, this is very important usually.
I did not use pip 

* The specific PyPI names and versions
N/A

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

Code test.py:
`import asyncpg`

* Provide in your issue the Nuitka options used

> This runs Ok
> `sudo python3 -m nuitka --follow-imports test.py`
> 
> These fail to run
> `sudo python3 -m nuitka test.py --standalone`
> 
> `sudo python3 -m nuitka test.py --standalone --follow-imports --include-plugin-directory /usr/local/lib/python3.8/dist-packages/asyncpg/pgproto`

The compilation output for the --include-plugin-directory showed above returns an apparent correct report:
> Nuitka-Options:INFO: Used command line options: test.py --standalone --follow-imports --include-plugin-directory /usr/                            local/lib/python3.8/dist-packages/asyncpg/pgproto
> Nuitka-Options:INFO: Following all imports is the default for standalone mode and need not be specified.
> Nuitka:INFO: Starting Python compilation with Nuitka '0.6.19.6' on Python '3.8' commercial None.
> Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'curses' added '_curses'.
> Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'ctypes' added '_ctypes'.
> Nuitka-Plugins:INFO: implicit-imports: Implicit dependencies of module 'locale' added '_bootlocale'.
> Nuitka:INFO: Completed Python level compilation and optimization.
> Nuitka:INFO: Generating source code for C backend compiler.
> Nuitka:INFO: Running data composer tool for optimal constant value handling.
> Nuitka:INFO: Running C compilation via Scons.
> Nuitka-Scons:INFO: Backend C compiler: gcc (gcc).
> Nuitka-Scons:INFO: Slow C compilation detected, used 60s so far, this might indicate scalability problems.
> Nuitka-Scons:INFO: Running /usr/bin/gcc -o /home/myself/test -fuse-linker-plugi                            n -flto=4 -fpartial-inlining -freorder-functions -O2 -z noexecstack -Xlinker -export-dynamic -rdynamic -s -Wl,-R,'$ORIGIN' -Wl,-                            -disable-new-dtags -Wl,-b -Wl,binary -Wl,./__constants.bin -Wl,-b -Wl,elf64-x86-64 -Wl,-defsym -Wl,constant_bin_data=_binary____                            _constants_bin_start @"./@link_input.txt -L/usr/lib -ldl -lm /usr/lib/python3.8/config-3.8-x86_64-linux-gnu/libpython3.8-pic.a -                            lz -lm -lutil -lpthread -lexpat took 190.30 seconds
> Nuitka-Scons:INFO: Compiled 31 C files using ccache.
> Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache hit': 30
> Nuitka-Scons:INFO: Cached C files (using ccache) with result 'cache miss': 1
> Nuitka:INFO: Keeping build directory 'test.build'.
> Nuitka:INFO: Successfully created 'test.dist/test'.

**Comment by kayhayen** [comment] 2022-02-12 18:29
This is very confusion at first sight, what do you think that `--include-plugin-directory` is to be used for? If I am not mistaken, it might ignore extension modules. I do see, however, that its description is not making it clear enough that is only to be used for the weak plugin systems, making files importable with `__import__`. You could have turned to `--include-package`, which of course includes too much potentially, and `--include-module` for just the missing one. 

Putting these options first in help has not the effect I am hoping for. Maybe people read long help texts backwards. Possibly a good candidate for being an option that is only allowed after reading something.

Also, `sudo` is not to be used with Nuitka, it does change the environment (on newer Linuxes), and unless you also execute your program with `sudo` and have it working, there is no point. It will not help, but it can be harmful. Nuitka cannot compile a program anymore, should it be dependent on your login in that case.

Anyway, on the factory branch I added the missing implicit imports to `implicit-imports.yml` and then it imports fine.

**Comment by kayhayen** [comment] 2022-02-12 18:30
You can use this or wait for the next release, https://nuitka.net/doc/factory.html

**Comment by bsense-rius** [comment] 2022-02-13 17:09
Thank you! Just by using **`--include-module=asyncpg.pgproto.pgproto `it fixed the issue**. 

In fact, I had also a similar issue with websockets (import websockets ...) that resulted in a runtime error `ModuleNotFoundError: No module named 'websockets.legacy'`. So I just  added a second `--include-module=websockets.legacy`, and fixed that error as well.

So many thanks!

**However I have a couple of questions:**

- I've seen that in the factory version you linked implicit-imports.yml has the cases for asyncpg.pgproto.pgproto etc. Is this file automatically loaded or it has to be called with a modifier?

- Regarding the --include-XXXX options I do not have totally clear the differences between --include-plugin-directory and --include-package. By the description it may seem that by using the --include-plugin-directory, as it takes everything from the directory, it should work although taking files that are of no use. That's why I used --include-plugin-directory instead of --include-package

- --nofollow-import-to, does it make sense for a standalone / onefile  to use this modifier? When does it make sense if we need to have it all included for a "portable" distribution.

Sorry for asking these questions, I understand that you may be short of time. So that's fine if you can't answer.

Thanks again!

NOTE: In my original post I have fixed a left over that was dangling in the first alternative to compile, as a result of bad copy n paste. Regarding sudo, before daring to post here, I tried with and without sudo, without any change in the results.

**Comment by kayhayen** [comment] 2022-02-14 09:35
It's automatically used, the plugin of Nuitka would have to be disabled. I agree the description is not good, and I am going to enhance it, since you are not the first to prefer it, while I hate to see it being used, because of the differences. Of course working with directory paths rather than module names will be inferior by default, since you can get it wrong, and there is a fair bit of knowledge lost in that case, and it doesn't do what people think it does many times.

The `--nofollow-import-to` can make sense to get it of packages that Nuitka includes, but are unused. Examples of that are `setuptools` that packages include, and then do not use, but also can end up importing a thousand other packages easily. The anti-bloat plugin fights known cases of it and warns about it being included. But there will be other things.

Your questions are all valid and good. I am seeing that these things are not easily addressed out of the box. I will get there with time though.

**Comment by kayhayen** [comment] 2022-02-14 09:36
As for websockets, I couldn't see any problem with dependencies. It would be nice if you created a new issue with the reproducer, simple import didn't cut it for me.

**Comment by kayhayen** [comment] 2022-02-14 09:36
This is now on the develop branch, part of the 0.7rc1 prerelease.

**Comment by bsense-rius** [comment] 2022-02-15 08:52
> As for websockets, I couldn't see any problem with dependencies. It would be nice if you created a new issue with the reproducer, simple import didn't cut it for me.

Ok I will try. Certainly the import websockets is not enough to reproduce the missing module. It has to do with the management of the websockets exceptions. Will try to shorten the case that produces the missing module.

Regards

**Comment by kayhayen** [comment] 2022-02-15 10:39
Yes, that would be great. I am aiming at out of the box working software.

**Comment by kayhayen** [comment] 2022-02-20 12:36
This is part of the 0.7 release now.

**Closed by kayhayen** 2022-02-20 12:36 UTC
Labels: develop

**Comment by dibyendumca** [comment] 2022-12-26 06:44
Hello,

I have used the library **'asyncpg'** to prepare a custom class for connecting a PostgreSQL Database and perform SELECT, INSERT, UPDATE, DELETE functionalities for my Database.

When I run the .py script the program runs fine.

I have used **'auto-py-to-exe-2.24.1'** to build **'.exe'** of my '.py' program. 
The executable is built successfully.
**_BUT as and when I try to run the executable, I get the following ERROR as follows_**.....

```
Traceback (most recent call last):
  File "Cxxxxxr.py", line 29, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "Cxxxxxr.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "asyncpg\__init__.py", line 8, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "asyncpg\connection.py", line 23, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "asyncpg\connect_utils.py", line 30, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "asyncpg\protocol\__init__.py", line 9, in <module>
  File "asyncpg\protocol\protocol.pyx", line 1, in init asyncpg.protocol.protocol
ModuleNotFoundError: No module named 'asyncpg.pgproto.pgproto'
[29964] Failed to execute script 'Cxxxxxr' due to unhandled exception!
```
