### ISSUE TITLE
Access violation/segmentation fault waiting for PySide6 signal

### ISSUE THREAD

**Issue by bersbersbers** [Nuitka/Nuitka#2492] opened 2023-10-12 20:26 UTC
Hi, remember the segfault from #2086? Here we go again, with a different one (I think. I hope. I have no idea). I am aware that you do not recommend bundling `pytest`, but doing so allows me to properly test the executables I generate (before potentially re-building it without `pytest`). And it really puts `nuitka` and `PySide6` to a hard test, which maybe you appreciate (or maybe not :D).

I have already spent a day reducing my 5,000+-lines-of-code repository into something that I can post here (that is, < 100 lines, no dependencies except `PySide6`, `pytest`, and `pytest-qt`), and I hope that it may give you some hints in the right direction while I try to reduce further (although it's getting harder).

This happens only with `nuitka`, not when running `pyinstaller` instead, and not when running the code natively. This makes me think nuitka may be to blame. Then again, this happens with `PySide6` v6.5.3 and v6.5.2 but not 6.5.1.1 nor 6.5.1 nor 6.5.0. (The diff between these versions is relatively small, at least on the Python side (https://code.qt.io/cgit/pyside/pyside-setup.git/diff/?id=v6.5.2&id2=v6.5.1.1), but it does have the nth try of fixing the infamous PYSIDE-2299:
https://code.qt.io/cgit/pyside/pyside-setup.git/commit/sources/pyside6/libpyside/signalmanager.cpp?id=afffc5838523595ac1625c5e4ae27b99f7e24557). So maybe it's PySide who is to blame. But it may also be that these kinds of changes just change the memory layout to a degree that it exposes a nuitka bug. I don't know, I hope that tells you something at least.

Here's my code. `raiser` and `fallback` are inspired by https://github.com/Suor/funcy. I was able to change `fallback` to a degree that it would not even call `fun` and still trigger the bug, so I guess those functions are not the core of the issue. But I have a hard time reproducing the issue without them (or `SharedMemory`, for that matter).

`app.py`:
```python
# nuitka-project: --onefile
# nuitka-project: --static-libpython=no
# nuitka-project: --enable-plugin=pyside6
# nuitka-project: --nofollow-import-to=tkinter
# nuitka-project: --noinclude-default-mode=error
# nuitka-project-if: {OS} == "Windows":
#    nuitka-project: --output-filename=crash.exe
# nuitka-project-if: {OS} == "Linux":
#    nuitka-project: --output-filename=crash.bin
# nuitka-project: --output-dir=dist-nuitka
# nuitka-project: --assume-yes-for-downloads
# nuitka-project: --noinclude-pytest-mode=allow
# nuitka-project: --noinclude-unittest-mode=allow
# nuitka-project: --include-package=_pytest
# nuitka-project: --include-package=pytestqt
# nuitka-project: --include-module=PySide6.QtTest
# nuitka-project: --include-module=test.test_crash
# nuitka-project: --nofollow-import-to=doctest
# nuitka-project: --include-data-file=test=test=**/test_*.*

from pathlib import Path

import pytest

pytest.main([Path(__file__).parent.resolve() / "test", "-s"], ["pytestqt.plugin"])
```

`test/test_crash.py`
```python
from multiprocessing.shared_memory import SharedMemory

from PySide6.QtCore import Signal
from PySide6.QtWidgets import QMainWindow, QSpinBox

def raiser(exception):
    def _raiser():
        raise exception

    return _raiser

def fallback(*funcs):
    for func in funcs:
        try:
            return func()
        except Exception:
            pass

class Class:
    def __init__(self, test, resource):
        self.name = f"{test}_{resource}"
        print(f"Class({self.name})")
        self.result = fallback(self.fun1, self.fun2, raiser(ConnectionError))
        print(f"end of Class({self.name})")

    def fun1(self):
        print(f"fun1({self.name})")
        result = SharedMemory(self.name)
        print(f"end of fun1({self.name})")
        return result

    def fun2(self):
        print(f"fun2({self.name})")
        result = SharedMemory(self.name, create=True, size=10)
        print(f"end of fun2({self.name}) return")
        return result

class Window(QMainWindow):
    signal = Signal()

    def __init__(self, test):
        super().__init__()

        self.class_a = Class(test, "A")
        self.class_b = Class(test, "B")
        print("Done with Class")

        self.spin_a = QSpinBox()
        self.spin_b = QSpinBox()

        self.show()
        print("Done with Window")

def test_crash1(qtbot):
    window = Window("crash1")
    qtbot.addWidget(window)
    print("Starting to wait")
    with qtbot.waitSignal(window.signal):
        print("Waiting")
        window.signal.emit()
        print("Done waiting")

def test_crash2(qtbot):
    window = Window("crash2")
    qtbot.addWidget(window)
    print("Starting to wait")
    with qtbot.waitSignal(window.signal):
        print("Waiting")
        window.signal.emit()
        print("Done waiting")
```

For now, I can reproduce this by running
`python -m nuitka app.py && dist-nuitka/crash.bin`

The output is like this (structured a bit more for readability):
```
Class(crash1_A)
fun1(crash1_A)
fun2(crash1_A)
end of fun2(crash1_A) return
end of Class(crash1_A)
Class(crash1_B)
fun1(crash1_B)
fun2(crash1_B)
end of fun2(crash1_B) return
end of Class(crash1_B)
Done with Class
Done with Window

Starting to wait
Waiting
Done waiting

.Class(crash2_A)
fun1(crash2_A)
fun2(crash2_A)
end of fun2(crash2_A) return
end of Class(crash2_A)
Class(crash2_B)
fun1(crash2_B)
fun2(crash2_B)
end of fun2(crash2_B) return
end of Class(crash2_B)
Done with Class
Done with Window

Starting to wait
Waiting
Fatal Python error: Segmentation fault
  File "/tmp/onefile_9297_1697139437_767758/pytestqt/wait_signal.py", line 62 in _cleanup
  File "/tmp/onefile_9297_1697139437_767758/pytestqt/wait_signal.py", line 223 in _cleanup
  File "/tmp/onefile_9297_1697139437_767758/pytestqt/wait_signal.py", line 208 in _quit_loop_by_signal       
  File "/tmp/onefile_9297_1697139437_767758/test/test_crash.py", line 75 in test_crash2
```

- Please check out if the develop version of Nuitka works better for you.

No, bac73eae0090563aa0c19a569cb0486002337661 has the same issue.

- `python -m nuitka --version`

```
1.8.4
Commercial: None
Python: 3.11.6 (main, Oct  6 2023, 21:02:08) [GCC 12.3.0]
Flavor: pyenv
Executable: /home/bers/.pyenv/versions/3.11.6/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 23.04
Version C compiler: /usr/bin/gcc (gcc).
```

- How did you install Nuitka and Python

`pip` and `pyenv`

- `python -m pip freeze`

```
iniconfig==2.0.0
nuitka==1.8.4
ordered-set==4.1.0
packaging==23.2
pluggy==1.3.0
PySide6-Essentials==6.5.2
pytest==7.4.2
pytest-qt==4.2.0
shiboken6==6.5.2
zstandard==0.21.0
```

**Comment by bersbersbers** [comment] 2023-10-12 20:37
I should add that in intermediate (and much longer) versions of the code example above, the stack trace hinted at functions called from `Class.__init__` called from a third test (`test_crash3`). So I guess the exact stack trace is less relevant than the fact that memory seems to be corrupted, and where that corription manifests may be somewhat (seemingly) random.

**Comment by kayhayen** [comment] 2023-10-13 08:31
I actually see a lot of value in what you are doing there using pytest in compilation to convince yourself of correctness. We did that for our PyPI tests as well, which I still have to resurrect.

**Comment by kayhayen** [comment] 2023-10-13 08:55
So, I didn't reproduce it with 6.5.0 indeed, and did with 6.5.3, checking for freelist corruption or something now with `--debug --experimental=disable-freelist-all` lets see what that does.

**Comment by kayhayen** [comment] 2023-10-13 09:01
So, it asserts in `Nuitka_Method_New` when it is being asked to create a method for a function object, that is no more tracked, so we still got corruption going on. Now the point where the reference to it gets lost is of course the thing to find. It might be `qtbot` code there.

**Comment by kayhayen** [comment] 2023-10-13 09:16
So, it happens for `_quit_loop_by_timeout` it seems, which is apparently not connected (added false assertions there), but only disconnected. So, what that code might be doing is disconnect only, and the workaround patches connect to keep a reference such that a disconnect will not corrupt things by releasing it badly. It gives `RuntimeError: Failed to disconnect signal timeout()` but maybe it does loose a reference while doing it. So the reference is not lost when connecting, but when disconnecting, or maybe both.

**Comment by kayhayen** [comment] 2023-10-13 09:20
So, this is it:

qtTestFunction1: PASSED
qtTestFunction2: FAILED 451391 451401 leaked 10
qtTestFunction3: FAILED 451521 451527 leaked 6
qtTestFunction4: MiniRef.bin: /home/hayen/repos/Py2C/nuitka/build/static_src/CompiledMethodType.c:560: Nuitka_Method_New: Assertion `_PyObject_GC_IS_TRACKED(function)' failed.

With MiniRef.py updated to test disconnect only:

```
""" Reference counting tests.

These contain functions that do PySide6 specific things, where we have a suspect
that references may be lost or corrupted. Executing them repeatedly and
checking the reference count is how they are used.
"""

# While we use Nuitka for comparison code, no need to compile that.
# nuitka-project: --follow-imports
# nuitka-project: --nofollow-import-to=nuitka

# nuitka-project: --enable-plugin=pyside6

import sys

from PySide6.QtWidgets import QApplication, QPushButton

from nuitka.tools.testing.Common import executeReferenceChecked

app = QApplication()
button = QPushButton("Call function")

x = 17


def function():
    pass


class C:
    def meth(self):
        pass


def qtTestFunction1():
    button.clicked.connect(function)
    button.clicked.disconnect(function)


def qtTestFunction2():
    c = C()

    button.clicked.connect(c.meth)
    button.clicked.disconnect(c.meth)


global_c = C()


def qtTestFunction3():
    button.clicked.connect(global_c.meth)
    button.clicked.disconnect(global_c.meth)


def qtTestFunction4():
    c = C()

    try:
        button.clicked.disconnect(c.meth)
    except RuntimeError:
        pass




####################################

# These need stderr to be wrapped.
tests_stderr = ()

# Disabled tests
tests_skipped = {}

result = executeReferenceChecked(
    prefix="qtTestFunction",
    names=globals(),
    tests_skipped=tests_skipped,
    tests_stderr=tests_stderr,
)

sys.exit(0 if result else 1)
```

So, I guess, we watch to monkey patch `disconnect` rather than `connect` and that is that.

**Comment by kayhayen** [comment] 2023-10-13 09:28
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working.

**Comment by kayhayen** [comment] 2023-10-13 09:30
Since this requires code to actually ignore a `RuntimeError` I am not necessarily going to panic release a hotfix due to this, but it shows that the workaround was wrong. I changed from patching connect to disconnect, and that works too for old known cases and that new one too. This should solve that one for good. I will included it in a hotfix should there be another one, but I am actually more interested in 1.9 release making right now.

**Comment by bersbersbers** [comment] 2023-10-13 11:22
Thanks for the quick investigations: 11a3d44ab12c706a54e85c21d5161e2983e1bc01 is working indeed!

**Comment by bersbersbers** [comment] 2023-10-13 12:43
While this solves the issue as reported above, I may file a subsequent one next week because I see another segmentation fault when compiling my full project now. Currently, I get fancy exceptions such as
> `NameError`: cannot access free variable 'my_variable' where it is not associated with a value in enclosing scope

(while the same code is working fine in `pyinstaller` as well as natively)

or 
> `AttributeError`: 'list' object has not attribute '__name__'

(which I find particularly concerning).

**Comment by kayhayen** [comment] 2023-10-14 11:01
@bersbersbers you will be welcome to do so

**Comment by bersbersbers** [comment] 2023-10-14 22:38
Done in #2499.

**Comment by kayhayen** [comment] 2023-10-30 13:45
This is now on the develop branch, I didn't have a chance to look at the other issue yet.

**Comment by kayhayen** [comment] 2023-11-23 08:32
Part of the 1.9 release I just made.

**Closed by kayhayen** 2023-11-23 08:32 UTC
Labels: bug, develop, excellent_report

**Comment by bersbersbers** [comment] 2023-11-27 21:56
I would like to record some information that may be relevant later. TLDR: I can still repro this on Windows, and could once on Linux.

On Windows and Linux, I could still reproduce this using PySide6 6.6.0 using nuitka 3b18dd1fd93bbba1489bd64c95da57e2971e2cd7 (from `develop`):

```
2.0rc3
Commercial: None
Python: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
Flavor: Unknown
Executable: c:\Build\project\.venv\Scripts\python.exe
OS: Windows
Arch: x86_64
WindowsRelease: 10
Version C compiler: ~\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc\x86_64\13.2.0-16.0.6-11.0.1-msvcrt-r1\mingw64\bin\gcc.exe (gcc 13.2.0).
```

```
================================================================================= test session starts =================================================================================
platform win32 -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0
PySide6 6.6.0 -- Qt runtime 6.6.0 -- Qt compiled 6.6.0
rootdir: C:\Users\bers\AppData\Local\Temp\onefile_11748_133455857716944103\test
collected 2 items

..\..\..\Users\bers\AppData\Local\Temp\onefile_11748_133455857716944103\test\test_crash.py Class(crash1_A)
fun1(crash1_A)
fun2(crash1_A)
end of fun2(crash1_A) return
end of Class(crash1_A)
Class(crash1_B)
fun1(crash1_B)
fun2(crash1_B)
end of fun2(crash1_B) return
end of Class(crash1_B)
Done with Class
Done with Window
Starting to wait
Waiting
Done waiting
.Class(crash2_A)
fun1(crash2_A)
fun2(crash2_A)
end of fun2(crash2_A) return
end of Class(crash2_A)
Class(crash2_B)
fun1(crash2_B)
fun2(crash2_B)
end of fun2(crash2_B) return
end of Class(crash2_B)
Done with Class
Done with Window
Starting to wait
Windows fatal exception: access violation

Current thread 0x00004850 (most recent call first):
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pytestqt\wait_signal.py", line 193 in connect
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pytestqt\qtbot.py", line 289 in waitSignal
  File "C:\Users\bers\AppData\Local\Temp\onefile_11748_133455857716944103\test\test_crash.py", line 73 in test_crash2
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\python.py", line 194 in pytest_pyfunc_call
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\python.py", line 1792 in runtest
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 169 in pytest_runtest_call
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 262 in <lambda>
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 341 in from_call
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 261 in call_runtest_hook
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 222 in call_and_report
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 133 in runtestprotocol
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\runner.py", line 114 in pytest_runtest_protocol
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\main.py", line 350 in pytest_runtestloop
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\main.py", line 325 in _main
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\main.py", line 271 in wrap_session
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\main.py", line 318 in pytest_cmdline_main
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_callers.py", line 27 in _multicall
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_manager.py", line 106 in _hookexec
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\pluggy\_hooks.py", line 479 in __call__
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\_pytest\config\__init__.py", line 169 in main
  File "C:\Users\bers\AppData\Local\Temp\ONEFIL~1\app.py", line 1 in <module>
```

```
2.0rc3
Commercial: None
Python: 3.11.6 (main, Oct 25 2023, 11:24:35) [GCC 13.2.0]
Flavor: pyenv
Executable: /home/bers/.pyenv/versions/project_3.11/bin/python3
OS: Linux
Arch: x86_64
Distribution: Ubuntu (based on Debian) 23.10
Version C compiler: /usr/bin/gcc (gcc 13).
```

```
================================================================================= test session starts ==================================================================================platform linux -- Python 3.11.6, pytest-7.4.3, pluggy-1.3.0
PySide6 6.6.0 -- Qt runtime 6.6.0 -- Qt compiled 6.6.0
rootdir: /tmp/onefile_14886_1701113179_856301/test
collected 2 items

../../../../tmp/onefile_14886_1701113179_856301/test/test_crash.py Class(crash1_A)
fun1(crash1_A)
fun2(crash1_A)
end of fun2(crash1_A) return
end of Class(crash1_A)
Class(crash1_B)
fun1(crash1_B)
fun2(crash1_B)
end of fun2(crash1_B) return
end of Class(crash1_B)
Done with Class
Done with Window
Starting to wait
Waiting
Done waiting
.Class(crash2_A)
fun1(crash2_A)
fun2(crash2_A)
end of fun2(crash2_A) return
end of Class(crash2_A)
Class(crash2_B)
fun1(crash2_B)
fun2(crash2_B)
end of fun2(crash2_B) return
end of Class(crash2_B)
Done with Class
Done with Window
Starting to wait
Fatal Python error: Segmentation fault

Current thread 0x00007fe817236b80 (most recent call first):
  File "/tmp/onefile_14886_1701113179_856301/pytestqt/wait_signal.py", line 193 in connect
  File "/tmp/onefile_14886_1701113179_856301/pytestqt/qtbot.py", line 289 in waitSignal
  File "/tmp/onefile_14886_1701113179_856301/test/test_crash.py", line 73 in test_crash2
  File "/tmp/onefile_14886_1701113179_856301/_pytest/python.py", line 194 in pytest_pyfunc_call
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_14886_1701113179_856301/_pytest/python.py", line 1792 in runtest
  File "/tmp/onefile_14886_1701113179_856301/_pytest/runner.py", line 169 in pytest_runtest_call
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_14886_1701113179_856301/_pytest/runner.py", line 262 in <lambda>
  File "/tmp/onefile_14886_1701113179_856301/_pytest/runner.py", line 341 in from_call
  File "/tmp/onefile_14886_1701113179_856301/_pytest/runner.py", line 261 in call_runtest_hook
  File "/tmp/onefile_14886_1701113179_856301/_pytest/runner.py", line 222 in call_and_report
  File "/tmp/onefile_14886_1701113179_856301/_pytest/runner.py", line 133 in runtestprotocol
  File "/tmp/onefile_14886_1701113179_856301/_pytest/runner.py", line 114 in pytest_runtest_protocol
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_14886_1701113179_856301/_pytest/main.py", line 350 in pytest_runtestloop
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_14886_1701113179_856301/_pytest/main.py", line 325 in _main
  File "/tmp/onefile_14886_1701113179_856301/_pytest/main.py", line 271 in wrap_session
  File "/tmp/onefile_14886_1701113179_856301/_pytest/main.py", line 318 in pytest_cmdline_main
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_callers.py", line 27 in _multicall
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_manager.py", line 106 in _hookexec
  File "/tmp/onefile_14886_1701113179_856301/pluggy/_hooks.py", line 479 in __call__
  File "/tmp/onefile_14886_1701113179_856301/_pytest/config/__init__.py", line 169 in main
  File "/tmp/onefile_14886_1701113179_856301/app.py", line 1 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, xxsubtype, shiboken6.Shiboken, PySide6.QtCore, PySide6.QtGui, PySide6.QtWidgets, PySide6.QtTest (total: 19)
/tmp/onefile_14886_1701113179_856301/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 4 leaked shared_memory objects to clean up at shutdown
```

> I reported before that 11a3d44ab12c706a54e85c21d5161e2983e1bc01 was working, and that is still true (I tested on Linux). So something must have broken it again. However, while that commit still exists in the repository, it does not belong to any tree, so it is a bit harder to bisect. I then checked a6012a7285175e77be5072efef708c60f226f28c, which is in `develop` and seems to be the same commit essentially - working, too. That calls for a bisect.

So I did the whole bisect on Linux, and up to the latest commit on `develop`, all were good. Luckily, I kept the stack traces above so I can assure myself that I am not crazy, and restarted the whole thing on Windows.

On Windows, I could (and still can) reproduce the issue on Windows using 3b18dd1fd93bbba1489bd64c95da57e2971e2cd7 and e610f04a38c0ed1da78c01003467a6c33ab04a25. (a6012a7285175e77be5072efef708c60f226f28c, which I previously tested on Linux only, gives me 

```
TypeError: '<' not supported between instances of 'NoneType' and 'tuple':    
  File "C:\Build\project\VENV~1\Lib\SITE-P~1\nuitka\build\ONEFIL~1.SCO", line 327:
    setupCCompiler(
  File "c:\Build\project\.venv\Lib\site-packages\nuitka\build\SconsCompilerSettings.py", line 783:
    if env.mingw_mode and env.target_arch == "x86_64" and env.python_version < (3, 12):
FATAL: Error, onefile bootstrap binary build failed.
```
