### ISSUE TITLE
unresponsive bin file on mac

### ISSUE THREAD

**Issue by jefflawr** [Nuitka/Nuitka#2387] opened 2023-08-14 21:35 UTC
Hello, On my mac (osx Ventura 13.4.1), nuitka compiles a small python file to display a tkinter window into a bin file that works fine with this command: 
python3.11 nuitka --enable-plugin=tk-inter  --macos-app-icon=tongue-icon.png --standalone test_nuitka.py 
When I try this same command with my project script, the resulting  bin file seems to execute but never displays the application tkinter window I see with the interpreter. 
Thinking things might need to be more mac-like, I added the –macos-app-bundle and –disable-console options with this command:
python3.11 -m nuitka --enable-plugin=tk-inter --disable-console --macos-create-app-bundle --macos-app-icon=tongue-icon.png --standalone test_nuitka.py
This compile generated a non-functional app file for both my test script and my project script. and produced similar fatal compile errors that seem suspiciously like red herrings (e.g. first error listed refers to “codesign”, which isn't used in either).
Any suggestions welcome on how to get either of these results:
get some result from the unresponsive project code bin file
address  the errors from the second compile command. 
Thanks, Jeff

test_nuitka.py: 
import tkinter as tk
mainWindow = tk.Tk()
mainWindow.geometry("400x100")
mainWindow.title(__file__)
test_frame = tk.Frame(mainWindow)
test_frame.pack()
test_label = tk.Label(test_frame, text="random test text")
test_label.pack()
mainWindow.mainloop()
python3.11 -m nuitka --version 
1.8rc7
Commercial: None
Python: 3.11.4 (v3.11.4:d2340ef257, Jun  6 2023, 19:15:51) [Clang 13.0.0 (clang-1300.0.29.30)]
Flavor: CPython Official
Executable: /Library/Frameworks/Python.framework/Versions/3.11/bin/python3.11
OS: Darwin
Arch: x86_64
Version C compiler: /usr/bin/clang (clang).

How did you install Nuitka and Python
pip install nuitka
python 3.11 – downloaded from https://www.python.org/downloads/macos/

output from
python3.11 -m pip freeze
altgraph==0.17.3
appdirs==1.4.4
audioread==3.0.0
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
contourpy==1.1.0
cycler==0.11.0
decorator==5.1.1
fonttools==4.41.1
idna==3.4
imageio==2.31.1
joblib==1.3.1
kiwisolver==1.4.4
lazy_loader==0.3
librosa==0.10.0.post2
llvmlite==0.40.1
macholib==1.16.2
matplotlib==3.7.2
msgpack==1.0.5
Nuitka==1.7.7
numba==0.57.1
numpy==1.24.4
ordered-set==4.1.0
packaging==23.1
Pillow==10.0.0
pooch==1.6.0
PyAudio==0.2.13
pycparser==2.21
pyparsing==3.0.9
python-dateutil==2.8.2
requests==2.31.0
scikit-learn==1.3.0
scipy==1.11.1
six==1.16.0
soundfile==0.12.1
soxr==0.3.5
threadpoolctl==3.2.0
typing_extensions==4.7.1
urllib3==2.0.4
zstandard==0.21.0

Errors: 
FATAL: Error, call to 'codesign' failed: ['/usr/bin/codesign', '-s', '-', '--force', '--deep', '--preserve-metadata=entitlements', 'test_nuitka.app/Contents/MacOS/test_nuitka', 'test_nuitka.app/Contents/MacOS/_bisect.so', 'test_nuitka.app/Contents/MacOS/_codecs_cn.so', 'test_nuitka.app/Contents/MacOS/_codecs_hk.so', 'test_nuitka.app/Contents/MacOS/_codecs_iso2022.so', 'test_nuitka.app/Contents/MacOS/_codecs_jp.so', 'test_nuitka.app/Contents/MacOS/_codecs_kr.so', 'test_nuitka.app/Contents/MacOS/_codecs_tw.so', 'test_nuitka.app/Contents/MacOS/_contextvars.so', 'test_nuitka.app/Contents/MacOS/_crypt.so', 'test_nuitka.app/Contents/MacOS/_csv.so', 'test_nuitka.app/Contents/MacOS/_datetime.so', 'test_nuitka.app/Contents/MacOS/_dbm.so', 'test_nuitka.app/Contents/MacOS/_heapq.so', 'test_nuitka.app/Contents/MacOS/_json.so', 'test_nuitka.app/Contents/MacOS/_multibytecodec.so', 'test_nuitka.app/Contents/MacOS/_opcode.so', 'test_nuitka.app/Contents/MacOS/_pickle.so', 'test_nuitka.app/Contents/MacOS/_posixsubprocess.so', 'test_nuitka.app/Contents/MacOS/_random.so', 'test_nuitka.app/Contents/MacOS/_sha512.so', 'test_nuitka.app/Contents/MacOS/_struct.so', 'test_nuitka.app/Contents/MacOS/_tkinter.so', 'test_nuitka.app/Contents/MacOS/_typing.so', 'test_nuitka.app/Contents/MacOS/array.so', 'test_nuitka.app/Contents/MacOS/binascii.so', 'test_nuitka.app/Contents/MacOS/fcntl.so', 'test_nuitka.app/Contents/MacOS/grp.so', 'test_nuitka.app/Contents/MacOS/math.so', 'test_nuitka.app/Contents/MacOS/pyexpat.so', 'test_nuitka.app/Contents/MacOS/select.so', 'test_nuitka.app/Contents/MacOS/termios.so', 'test_nuitka.app/Contents/MacOS/unicodedata.so', 'test_nuitka.app/Contents/MacOS/zlib.so', 'test_nuitka.app/Contents/MacOS/Python', 'test_nuitka.app/Contents/MacOS/libtcl8.6.dylib', 'test_nuitka.app/Contents/MacOS/libtk8.6.dylib'] -> b'test_nuitka.app/Contents/MacOS/test_nuitka: bundle format unrecognized, invalid, or unsuitable\nIn subcomponent: /Users/jeffreylawrence/IdeaProjects/test_nuitka/test_nuitka.app/Contents/MacOS/tcl/opt0.4'.

**Comment by kayhayen** [comment] 2023-08-15 07:58
I think this is a duplicate of Tcl not working on macOS, without specifying both --onefile and --macos-create-app-bundle which will create a bundle that has other problems, e.g. cannot preserve entitlements if you specify them.

If you delete the folder `"opt0.4' ` in your Tcl installation you might get away with it. It would be best, to create a DMG file for these, like Python itself is one. It seems apps cannot contain all files that Python gets away with in that installation mode, but I didn't find the time for that yet.

**Comment by kayhayen** [comment] 2023-08-15 08:00
Duplicate of #1568

**Closed by kayhayen** 2023-08-15 08:00 UTC
Labels: bug, duplicate

**Comment by jefflawr** [comment] 2023-08-15 22:46
Hello kayhayen,
Thank you for the quick and helpful response. The --onefile option got me a working binary on Windows for which I am deeply grateful. On mac, it compiled without complaint but the binary launched without actually doing anything (?). I'll check out #1568 solution, though. 
Best, Jeff

**Comment by kayhayen** [comment] 2023-08-16 06:35
Well, it doesn't have a solution unfortunately. But with --onefile, the app bundlings contains these data files inside of it. But deleting the files from the Tcl/Tk in the Python installation and having nothing break seems very likely to work. The later can be tested by running your program successfully still. Alternatively --noinclude-datafile can also be used.
