### ISSUE TITLE
azure.cognitiveservices.speech load error on Debian

### ISSUE THREAD

**Issue by xuanyuxin** [Nuitka/Nuitka#3188] opened 2024-11-11 11:19 UTC
Hi, I encountered an error using libMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory.

The MRE is:
- OS version: Debian GNU/Linux 12 (bookworm)
- Nuitka version: 2.4.11

- How did you install Nuitka and Python: use Docker
```
Python from image
FROM python:3.10-slim
 
pip install nuitka==2.4.11
```

- Nuitka command that I used:
```
python -m nuitka --standalone speech_to_text.py
```
where 
speech_to_text.py:
```
import os, time, re
import azure.cognitiveservices.speech as speechsdk

def recognize_from_microphone():
    # This example requires environment variables named "SPEECH_KEY" and "SPEECH_REGION"
    speech_config = speechsdk.SpeechConfig(subscription='test', region='test')
    # speech_config.speech_recognition_language="en-US"

    # https://learn.microsoft.com/en-us/azure/ai-services/speech-service/how-to-recognize-speech?pivots=programming-language-csharp#change-how-silence-is-handled
    auto_detect_source_language_config = speechsdk.languageconfig.AutoDetectSourceLanguageConfig(languages=["en-US", "de-DE", "zh-CN"])
    # Set the initial silence timeout to 5 seconds
    speech_config.set_property(speechsdk.PropertyId.SpeechServiceConnection_InitialSilenceTimeoutMs, "5000")
    # Set the end silence timeout to 5 seconds
    speech_config.set_property(speechsdk.PropertyId.SpeechServiceConnection_EndSilenceTimeoutMs, "5000")
    # Set the segmentation silence timeout to 3 seconds
    speech_config.set_property(speechsdk.PropertyId.Speech_SegmentationSilenceTimeoutMs, "3000")

    audio_config = speechsdk.audio.AudioConfig(use_default_microphone=True)
    speech_recognizer = speechsdk.SpeechRecognizer(speech_config=speech_config, 
                                                   auto_detect_source_language_config=auto_detect_source_language_config,
                                                   audio_config=audio_config)

    print("Speak into your microphone.")
    speech_recognition_result = speech_recognizer.recognize_once_async().get()

if __name__ == '__main__':
    text = recognize_from_microphone()
```

The error is:
```
Traceback (most recent call last):
  File "/tmp/onefile_575_1731322538_97239/speech_to_text.py", line 2, in <module>
    import azure.cognitiveservices.speech as speechsdk
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/onefile_575_1731322538_97239/azure/cognitiveservices/speech/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/onefile_575_1731322538_97239/azure/cognitiveservices/speech/speech.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "/tmp/onefile_575_1731322538_97239/azure/cognitiveservices/speech/interop.py", line 20, in <module>
  File "/tmp/onefile_575_1731322538_97239/ctypes/__init__.py", line 452, in LoadLibrary
  File "/tmp/onefile_575_1731322538_97239/ctypes/__init__.py", line 374, in __init__
OSError: /tmp/onefile_575_1731322538_97239/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so: cannot open shared object file: No such file or directory
```

- Without "--standalone" it works. 
because the .so file exists at folder /usr/local/lib/python3.10/site-packages/azure/cognitiveservices/speech

- On windows system it also works and able to find the corresponding .dll file.
- Thank you very much!

**Comment by kayhayen** [comment] 2024-11-11 11:56
Did you read the warning that Nuitka output during compilation? It might not be the real issue, but I wonder if you read and considered adhering to it.

**Comment by xuanyuxin** [comment] 2024-11-12 01:49
Thanks for the response. There is no warning during compilation:
```
python -m nuitka --standalone speech_to_text.py
Nuitka-Options: Used command line options: --standalone speech_to_text.py
Nuitka: Starting Python compilation with Nuitka '2.4.11' on Python '3.10' commercial grade 'not installed'.
Nuitka-Plugins:anti-bloat: Not including '_bisect' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka-Plugins:anti-bloat: Not including '_json' automatically in order to avoid bloat, but this may cause: may slow down by using fallback implementation.
Nuitka: Completed Python level compilation and optimization.
Nuitka: Generating source code for C backend compiler.
Nuitka: Running data composer tool for optimal constant value handling.
Nuitka: Running C compilation via Scons.
Nuitka-Scons: Backend C compiler: gcc (gcc 12).
Nuitka-Scons: Backend linking program with 16 files (no progress information available for this stage).
Nuitka-Scons:WARNING: You are not using ccache, re-compilation of identical code will be slower than necessary. Use your OS package manager to install it.
Nuitka: Keeping build directory 'speech_to_text.build'.
Nuitka: Successfully created 'speech_to_text.dist/speech_to_text.bin'.
```

and the dist folder contains no libMicrosoft.CognitiveServices.Speech.core.so:
```
/speech_to_text.dist# ls
_asyncio.so         _codecs_jp.so    _datetime.so  _multibytecodec.so   _queue.so   _socket.so      fcntl.so        libpython3.10.so.1.0  speech_to_text.bin
_blake2.so          _codecs_kr.so    _decimal.so   _multiprocessing.so  _random.so  _ssl.so         grp.so          libssl.so.3           unicodedata.so
_bz2.so             _codecs_tw.so    _hashlib.so   _opcode.so           _sha1.so    _statistics.so  libbz2.so.1.0   math.so               zlib.so
_codecs_cn.so       _contextvars.so  _heapq.so     _pickle.so           _sha256.so  _struct.so      libcrypto.so.3  mmap.so
_codecs_hk.so       _csv.so          _lzma.so      _posixshmem.so       _sha3.so    array.so        libffi.so.8     pyexpat.so
_codecs_iso2022.so  _ctypes.so       _md5.so       _posixsubprocess.so  _sha512.so  binascii.so     liblzma.so.5    select.so
```

**Comment by xuanyuxin** [comment] 2024-11-12 03:33
Solved:
`python -m nuitka --standalone --onefile --include-data-file=/usr/local/lib/python3.10/site-packages/azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so=azure/cognitiveservices/speech/libMicrosoft.CognitiveServices.Speech.core.so speech_to_text.py`

**Comment by kayhayen** [comment] 2024-11-13 13:18
There being no warning is confusing to me, I am getting it myself a lot when I compile with the Debian Python outside of a virtualenv. Maybe your specific image there is not recognized as such, and has a self compiled 3.10, although the paths don't like like that, but I would expect Python 3.12 as the system Python there.

**Comment by kayhayen** [comment] 2024-11-13 13:38
It remains unclear how you installed the azure speech package, did you use apt-get at all there, or only PyPI. I tried it, but I got an error about a missing system library, so I didn't reproduce it yet, can you provide the information needed?

**Comment by kayhayen** [comment] 2024-11-13 13:51
I tried your code example on Windows, no issue, and then because Linux is so annoying on macOS, and I think I saw your issue there. At least the DLL is missing there too, our config seems to be a Windows only configuration so far. On macOS there is also an archive with code to include, but the DLL prefix of "lib" was lacking, so chances are that my next update of factory will be working for you out of the box, and subsequently Nuitka 2.5

**Comment by kayhayen** [comment] 2024-11-13 13:53
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-11-16 12:41
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:41 UTC
Labels: bug, factory

**Comment by xuanyuxin** [comment] 2024-11-20 03:35
Thank you and would like to confirm factory version (nuitika==2.5) works on Debian now.

RUN python -m nuitka --standalone --onefile speech_to_text.py is able to compile and run.
