### ISSUE TITLE
`numpy.lib.recfunctions.structured_to_unstructured`: AttributeError with --standalone

### ISSUE THREAD

**Issue by grgi** [Nuitka/Nuitka#1787] opened 2022-09-13 09:27 UTC
* Nuitka version, full Python version, flavor, OS

```
1.0.6
Commercial: 1.0.0
Python: 3.10.7 (main, Sep  8 2022, 14:34:29) [GCC 12.2.0]
Flavor: Debian Python
Executable: /tmp/nptest/bin/python
OS: Linux
Arch: x86_64
Distribution: Debian sid
```

* How did you install Nuitka and Python

`pip install` of the main branch of Nuitka-commercial (or alternatively the develop branch) into an fresh `venv`.

* The specific PyPI names and versions

```
Nuitka @ file:///tmp/Nuitka-commercial
numpy==1.23.3
ordered-set==4.1.0
```

* Many times when you get an error from Nuitka, your setup may be special

Hello world works fine.

* Also supply a [Short, Self Contained, Correct, Example](https://sscce.org/)

The following example `nptest.py`
```
import numpy as np
from numpy.lib import recfunctions as rfn

if __name__ == '__main__':
    a = np.zeros(4, dtype=[('a', 'i4'), ('b', 'f4,u2'), ('c', 'f4', 2)])
    print(rfn.structured_to_unstructured(a))
```

should produce the following output:
```
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
```

But after compiling standalone via `python -m nuitka --standalone --enable-plugin=numpy nptest.py`, I get the following error:
```
Traceback (most recent call last):
  File "/tmp/nptest/src/nptest.dist/nptest.py", line 7, in <module>
  File "/tmp/nptest/src/nptest.dist/numpy/core/overrides.py", line 180, in public_api
  File "/tmp/nptest/src/nptest.dist/numpy/lib/recfunctions.py", line 975, in structured_to_unstructured
AttributeError: 'NoneType' object has no attribute 'filter'
```

**Comment by kayhayen** [comment] 2022-09-23 07:38
This might be due to using Debian packages, from your freeze output it's clear you ignored that warning it has given you.

**Comment by kayhayen** [comment] 2022-09-23 07:45
Ok, the Debian part is incorrect, I reproduced it on Windows right now, with even relatively old numpy, surprising to see.

**Comment by kayhayen** [comment] 2022-09-23 07:48
Ok, so this a fault of the anti-bloat replacement done for `suppress_warning`, it yields None, whereas apparently some kind of object would be wanted.

**Comment by kayhayen** [comment] 2022-09-23 08:11
This is fixed on https://nuitka.net/doc/factory.html and will be release as part of 1.1 soon.

**Comment by kayhayen** [comment] 2022-09-25 17:15
This is part of the stable release 1.1 that I just made.

**Closed by kayhayen** 2022-09-25 17:15 UTC
Labels: bug, factory, excellent_report
