### ISSUE TITLE
keyring module compatibility

### ISSUE THREAD

**Issue by lowlyocean** [Nuitka/Nuitka#710] opened 2020-05-16 19:07 UTC
Hi Kay, wanted to flag a failure when using keyring module to store user credentials. Running the resulting repro.exe doesn't seem to do anything at all. This is using v0.6.8.1 installed from pip, python version is 3.7.1 which is itself installed via conda 4.5.12. Windows Version 1909 (OS Build 18363.836) and Visual Studio 2015 (v14.0)

The command:
`python -m nuitka --standalone --python-flag=-S --windows-dependency-tool=pefile --plugin-enable=tk-inter --windows-disable-console repro.py`

Contents of repro.py:

```python
#!python3
# -*- coding: utf-8 -*-

import keyring
import traceback

from tkinter import Tk
from tkinter.messagebox import showerror, showinfo
from tkinter.simpledialog import askstring


def main():

    root = Tk()
    root.withdraw()

    user = askstring('repro', 'Username')
    pw = askstring('repro', 'Password')
    keyring.set_password('repro', user, pw)
    pw_fetched = keyring.get_password('repro', user)
    showinfo('repro', pw_fetched)


if __name__ == "__main__":
    try:
        main()
    except:
        showerror('repro', traceback.format_exc())
```

**Comment by lowlyocean** [comment] 2020-05-16 19:13
if I remove `--windows-disable-console` then I can see the following callstack when running repro.exe:
```
  File "C:\Users\danie\PYCHAR~1\repro\REPRO~1.DIS\keyring\__init__.py", line 1, in <module keyring>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\danie\PYCHAR~1\repro\REPRO~1.DIS\keyring\core.py", line 10, in <module keyring.core>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\danie\PYCHAR~1\repro\REPRO~1.DIS\keyring\backend.py", line 13, in <module keyring.backend>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\danie\PYCHAR~1\repro\REPRO~1.DIS\importlib_metadata\__init__.py", line 602, in <module importlib_metadata>
  File "C:\Users\danie\PYCHAR~1\repro\REPRO~1.DIS\importlib_metadata\__init__.py", line 564, in version
  File "C:\Users\danie\PYCHAR~1\repro\REPRO~1.DIS\importlib_metadata\__init__.py", line 537, in distribution
  File "C:\Users\danie\PYCHAR~1\repro\REPRO~1.DIS\importlib_metadata\__init__.py", line 205, in from_name
importlib_metadata.PackageNotFoundError: importlib_metadata
```

**Comment by lowlyocean** [comment] 2020-05-16 19:57
This issue seems related:
https://gitlab.com/python-devs/importlib_metadata/-/issues/71#note_191413098

**Comment by kayhayen** [comment] 2020-05-17 09:53
There is a known problem with the usage of the kind of information talked about there. Often programs only check their versions there, like requirements, but it seems they also might access data files in the package?

Nuitka wants to be compatible with that, but I fear, in the mid term, nobody will pay me for that, and otherwise I lack the time to do it.

**Comment by lowlyocean** [comment] 2020-05-17 17:29
Understood. Submitted an MR to see if my patch (or some version of it) would be accepted to importlib_metadata in the interim. If not at least hopefully it will help future visitors to this issue
https://gitlab.com/python-devs/importlib_metadata/-/merge_requests/120

**Comment by NeoFoxxo** [comment] 2023-07-18 12:40
I solved this issue by importing the libraries it could not find and by adding the `--include-module="win32timezone"` flag @lowlyocean suggested. All the imports I used may not be needed but this results in the script saving credentials correctly and not producing any errors when compiled.

```python
import keyring
import keyring.backends.Windows
import win32cred
import pywintypes
import win32api

keyring.set_keyring(keyring.backends.Windows.WinVaultKeyring())
```

And this was the nuitka command I used:
```nuitka --onefile --include-module="win32timezone" -o "Process" main-individual.py```

**Comment by kayhayen** [comment] 2023-07-19 07:33
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback if this is working is very welcome, just please do not share plans of doing it, but rather confirmations or denials of it working. 

This was now solvable in config, however, the feature has a bug, that reveals on 3.9 at least, that I needed to fix for my test on macOS. I didn't manage to run it at all on Linux. On macOS it fails to access it.

I was using this:

```
# nuitka-project: --standalone

import keyring

user = "Username"
pw = "Password"
keyring.set_password("repro", user, pw)
pw_fetched = keyring.get_password("repro", user)
assert pw_fetched == "Password"
``

Remove the tk stuff that is not relevant. On Windows it worked nicely. Not sure why on macOS it needed something like a permission, but there you go, now it's supposed to work out of the box, probably will hit a hotfix of 1.7 soon.

**Comment by kayhayen** [comment] 2023-07-24 07:06
This is part of the hotfix release 1.7.6 that I just made.

**Closed by kayhayen** 2023-07-24 07:06 UTC
Labels: bug, factory

**Comment by NeoFoxxo** [comment] 2023-09-02 14:22
Is there a way to fix it on MacOS? I currently get this error on Ventura on an M1: 
Build command: ```nuitka --onefile  --macos-create-app-bundle --disable-console -o "Process" process-mac.py```
```
Traceback (most recent call last):
  File "/private/var/folders/37/qd0vs2sx3_z21qqc1gm2p22w0000gn/T/onefile_32015_1693664422_983766/keyring/backends/macOS/__init__.py", line 52, in set_password
  File "/private/var/folders/37/qd0vs2sx3_z21qqc1gm2p22w0000gn/T/onefile_32015_1693664422_983766/keyring/backends/macOS/api.py", line 152, in set_generic_password
  File "/private/var/folders/37/qd0vs2sx3_z21qqc1gm2p22w0000gn/T/onefile_32015_1693664422_983766/keyring/backends/macOS/api.py", line 173, in delete_generic_password
  File "/private/var/folders/37/qd0vs2sx3_z21qqc1gm2p22w0000gn/T/onefile_32015_1693664422_983766/keyring/backends/macOS/api.py", line 115, in raise_for_status
keyring.backends.macOS.api.Error: (-25244, 'Unknown Error')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/var/folders/37/qd0vs2sx3_z21qqc1gm2p22w0000gn/T/onefile_32015_1693664422_983766/process-mac.py", line 86, in <module>
    keyring.set_password("process", "session", credentials)
  File "/private/var/folders/37/qd0vs2sx3_z21qqc1gm2p22w0000gn/T/onefile_32015_1693664422_983766/keyring/core.py", line 61, in set_password
  File "/private/var/folders/37/qd0vs2sx3_z21qqc1gm2p22w0000gn/T/onefile_32015_1693664422_983766/keyring/backends/macOS/__init__.py", line 24, in wrapper
  File "/private/var/folders/37/qd0vs2sx3_z21qqc1gm2p22w0000gn/T/onefile_32015_1693664422_983766/keyring/backends/macOS/__init__.py", line 56, in set_password
keyring.errors.PasswordSetError: Can't store password on keychain: (-25244, 'Unknown Error')
```

**Comment by kayhayen** [comment] 2023-09-02 17:22
@NeoFoxxo Posting below closed issues is a surefire way to get ignored. I am not going to guess without a fresh issue template, what kinds of mistakes and setup you have made, and I am not going to trace, or remember to check later, or searching for where something was said. Please open new issues for new issues. If the issue is closed, it's not the same even if the symptom looks similar to you.
