### ISSUE TITLE
Scons: Doesn't recognize conda-forge/gxx_linux-64 compiler as gcc variant

### ISSUE THREAD

**Issue by mjscosta** [Nuitka/Nuitka#328] opened 2019-04-03 15:30 UTC
*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

   python -m nuitka --version

```
0.6.2
Python: 3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 09:07:38) 
Executable: /home/atritoman/.conda/envs/nuitka-setuptools/bin/python3.6
OS: Linux
Arch: x86_64
```

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

`conda install nuitka -c conda-forge`

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
   that demonstrates the issue i.e a small piece of code which reproduces
   the issue and can be run with out any other (or as few as possible)
   external dependencies.

```
conda create -n nuitka_conda_gcc_test python=3.7 nuitka gxx_linux-64
conda activate nuitka_conda_gcc_test

cat << EOF >> mod.py
print(__file__)
EOF

nuitka --module mod.py
```
output:

```
 nuitka --module mod.py 
AssertionError: x86_64-conda_cos6-linux-gnu-cc:
  File "/home/atritoman/.conda/envs/nuitka-setuptools/lib/python3.6/site-packages/nuitka/build/SingleExe.scons", line 1435:
    assert False, the_cc_name
```

Looking at the code, 
https://github.com/Nuitka/Nuitka/blob/18a0ab3ee7f9f35d8ac5ec967995c6dce731f56d/nuitka/build/SingleExe.scons#L634
https://github.com/Nuitka/Nuitka/blob/18a0ab3ee7f9f35d8ac5ec967995c6dce731f56d/nuitka/build/SingleExe.scons#L1263
https://github.com/Nuitka/Nuitka/blob/18a0ab3ee7f9f35d8ac5ec967995c6dce731f56d/nuitka/build/SingleExe.scons#L1428

is expecting the gcc compiler name in the $CC/$CXX to have `g++` or `gcc` in the name, in some linux distros, `gcc` and `g++` are also name `c++` and `cc`.

the conda-forge compiler, has name `x86_64-conda_cos6-linux-gnu-cc` and `x86_64-conda_cos6-linux-gnu-c++`, hence nuika fails.

**Comment by mjscosta** [comment] 2019-04-03 21:02
tried to fix the issue, by searching so for "cc" and "c++" in the compiler name, but bumped into another issue:

Apparently the SingleExe.scons gives preference to the CC environment variable, after that it performs the compilation, and many warnings are printed by the compiler.

Shouldn't nuitka take preference for the "CXX" compiler environment ?

Warnings:
```
nuitka3 --show-scons mod.py 
Scons command: /home/atritoman/.conda/envs/Nuitka/bin/scons -f /data/development/projects/atritoman/Nuitka/nuitka/build/SingleExe.scons --jobs 4 --warn=no-deprecated --no-site-dir --debug=explain name=mod result_name=mod source_dir=mod.build debug_mode=false python_debug=false unstripped_mode=false module_mode=false full_compat=false experimental= trace_mode=false python_version=3.6 target_arch=x86_64 python_prefix=/home/atritoman/.conda/envs/Nuitka nuitka_src=/data/development/projects/atritoman/Nuitka/nuitka/build nuitka_cache=/home/atritoman/.cache/Nuitka module_count=2 result_exe=mod.bin show_scons=true abiflags=m
scons: Reading SConscript files ...
SCONS:  CC='/home/atritoman/.conda/envs/Nuitka/bin/x86_64-conda_cos6-linux-gnu-cc'
SCONS:  CXX='/home/atritoman/.conda/envs/Nuitka/bin/x86_64-conda_cos6-linux-gnu-c++'
SCONS:  Tools= ['default']
Scons CC 'gcc' version check:
Scons CC 'gcc' version check gives '5.4.0' from '5.4.0'
Initial CC: gcc
Initial CCVERSION: None
Initial CXX: g++
Initial CXXVERSION: None
SCONS:  Picked compiler= /home/atritoman/.conda/envs/Nuitka/bin/x86_64-conda_cos6-linux-gnu-cc
SCONS:  Picked name= x86_64-conda_cos6-linux-gnu-cc
Scons compiler: Using /home/atritoman/.conda/envs/Nuitka/bin/x86_64-conda_cos6-linux-gnu-cc 
Scons CC '/home/atritoman/.conda/envs/Nuitka/bin/x86_64-conda_cos6-linux-gnu-cc' version check:
Scons CC '/home/atritoman/.conda/envs/Nuitka/bin/x86_64-conda_cos6-linux-gnu-cc' version check gives '7.3.0' from '7.3.0'
Scons: Detecting Linux target arch with : ['objdump', '-f', '/home/atritoman/.conda/envs/Nuitka/bin/python']
scons: Told to run compilation on 4 CPUs.
Scons: Launching target: ['mod.bin']
scons: done reading SConscript files.
scons: Building targets ...
scons: building `mod.build/__helpers.o' because it doesn't exist
/home/atritoman/.conda/envs/Nuitka/bin/x86_64-conda_cos6-linux-gnu-cc -o mod.build/__helpers.o -c -fvisibility=hidden -std=c11 -fwrapv -fpartial-inlining -fno-var-tracking -O3 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -I/home/atritoman/.conda/envs/Nuitka/include/python3.6m -I/home/atritoman/.conda/envs/Nuitka/PC -Imod.build -I/data/development/projects/atritoman/Nuitka/nuitka/build/include -I/data/development/projects/atritoman/Nuitka/nuitka/build/static_src mod.build/__helpers.c
cc1: warning: command line option '-std=c++1z' is valid for C++/ObjC++ but not for C
cc1: warning: command line option '-fvisibility-inlines-hidden' is valid for C++/ObjC++ but not for C
scons: building `mod.build/module.__main__.o' because it doesn't exist
/home/atritoman/.conda/envs/Nuitka/bin/x86_64-conda_cos6-linux-gnu-cc -o mod.build/module.__main__.o -c -fvisibility=hidden -std=c11 -fwrapv -fpartial-inlining -fno-var-tracking -O3 -pipe -DNDEBUG -D_FORTIFY_SOURCE=2 -O2 -fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -pipe -D_NUITKA_SYSFLAG_BYTES_WARNING=0 -D_NUITKA_SYSFLAG_NO_SITE=0 -D_NUITKA_SYSFLAG_VERBOSE=0 -D_NUITKA_SYSFLAG_UTF8=0 -D_NUITKA_SYSFLAG_OPTIMIZE=0 -D__NUITKA_NO_ASSERT__ -D_NUITKA_FROZEN=0 -D_NUITKA_MODULE_COUNT=2 -D_NUITKA_EXE -I/home/atritoman/.conda/envs/Nuitka/include/python3.6m -I/home/atritoman/.conda/envs/Nuitka/PC -Imod.build -I/data/development/projects/atritoman/Nuitka/nuitka/build/include -I/data/development/projects/atritoman/Nuitka/nuitka/build/static_src mod.build/module.__main__.c
In file included from mod.build/__helpers.c:4:0:
/data/development/projects/atritoman/Nuitka/nuitka/build/include/nuitka/prelude.h:24:0: warning: "NDEBUG" redefined
 #define NDEBUG
```

**Comment by kayhayen** [comment] 2019-04-04 12:49
Nuitka really wants a C11 compiler. It will use a C++ compiler as a C11 compiler as well, but only as a workaround.

**Comment by kayhayen** [comment] 2019-04-04 13:09
I was using this `CC=$CONDA_BASE_DIR/bin/x86_64-conda_cos6-linux-gnu-gcc`, so there is a `*gcc` binary in the distribution, but I understand you enter an environment where CC is set by `conda activate` pointing to the `*-cc` variant?

I don't have an installation accessible right now, but is that a symlink to the `*-gcc` anyway? We could consider a `realpath` usage. If you confirm that, the `CC` is set by Anaconda environment, we could special case that one, and resolve it to the `gcc` name, and be good. Maybe also simply `gnu-cc` could also be treated like `gcc` there, seems pretty much identical.

What I mean to have, is much like for Anaconda on Windows, a mechanism, where it automatically picks up on the CondaCC, just because you ran Anaconda Python and the C compiler happens to be installed, and then works out of the box.

Anyway, with what I wrote above and current factory branch, it ought to already work when you change the CC value: http://nuitka.net/doc/factory.html

I expect to follow your reproducer given later today, and then maybe just do the minor tweak to add `gnu-cc` for gcc_mode and that `-dumpversion` availability.

Yours,
Kay

**Comment by mjscosta** [comment] 2019-04-04 13:57
> Nuitka really wants a C11 compiler. It will use a C++ compiler as a C11 compiler as well, but only as a workaround.

That means the CXX should be used in preference of CC ?

I've played around with the SingleExe.scons, to give preference to CXX, but that did not worked-out, from what I understood, because the source files are ".c" files, scons will pickup the CC from the configured Environment, so if you'd change the extension (dunno if that makes sense), to ".cpp", then scons would preferably use CXX compiler.

> I was using this CC=$CONDA_BASE_DIR/bin/x86_64-conda_cos6-linux-gnu-gcc, so there is a *gcc binary in the distribution, but I understand you enter an environment where CC is set by conda activate pointing to the *-cc variant?

correct

> I don't have an installation accessible right now, but is that a symlink to the *-gcc anyway? We could consider a realpath usage. If you confirm that, the CC is set by Anaconda environment, we could special case that one, and resolve it to the gcc name, and be good. Maybe also simply gnu-cc could also be treated like gcc there, seems pretty much identical.

you are right, it is a symbolic link:
`.conda/envs/nuitka-setuptools2-test_1/bin/x86_64-conda_cos6-linux-gnu-cc -> x86_64-conda_cos6-linux-gnu-gcc`

Following the discussion from the PR, and your fix proposal, I'd like to mention a few cases it would solve.

consider a scenario, from a cross compilation gcc packages, it suggests a couple more cases would fail.
```
[**********:/work] $ ls -lah $CC 
lrwxrwxrwx 1 root root 7 Feb 25  2015 /usr/bin/x86_64-linux-gnu-gcc -> gcc-4.9
[**********:/work] $ ls -lah $CXX
lrwxrwxrwx 1 root root 7 Feb 25  2015 /usr/bin/x86_64-linux-gnu-g++ -> g++-4.9
[**********:/work] $ 
```

the symlinks have the proper prefix, but if you use realpath or want to use another gcc version, it will fail, because `gcc-4.9` has no `gcc` suffix. 

>```
> -    if os.path.basename(clvar[0]) in ("gcc", "g++", "clang"):
> +    clvar0 = os.path.basename(clvar[0])
> +
> ```
`+`    if clvar0.endswith(("gcc", "g++", "clang")) **or clvar0.startswith(("gcc", "g++", "clang")):**
>```
>          command = list(clvar) + ["-dumpversion"]
>      else:
>          command = list(clvar) + ["--version"]
> ```

**Comment by kayhayen** [comment] 2019-04-04 22:02
The gcc detection using an `in` test series, so `endswith` there very probably an inconsistent idea, going to change to using `in` there too.

The `CXX` (`XX` stands for `++` there) is not supposed to be used except on systems with very old gcc, not relevant here.

The `realpath` would require a path lookup that may or may not be possible, depending on using a full path or just a binary name. I will therefore simply go with the `gnu-cc` name part check, and just make it use `gcc_mode` for those cases too, and of course query version with `-dumpversion`.

**Comment by kayhayen** [comment] 2019-04-09 08:55
So this is on factory for a while, sorry I forgot to mention that:

http://nuitka.net/doc/factory.html

**Comment by kayhayen** [comment] 2019-04-12 06:22
So this is in the latest pre-release, and will be in 0.6.4 eventually.

**Comment by mjscosta** [comment] 2019-04-13 11:17
Hi Kay,
Then if you agree I'll close it.

**Comment by kayhayen** [comment] 2019-06-10 19:35
Release as 0.6.4

**Closed by kayhayen** 2019-06-10 19:35 UTC
Labels: develop, enhancement
