### ISSUE TITLE
Code using postponed evaluation of annotations (PEP 563) is rejected with a SyntaxError

### ISSUE THREAD

**Issue by aw1621107** [Nuitka/Nuitka#188] opened 2018-10-31 23:50 UTC
Nuitka chokes on files that make use of annotations that are only valid with [PEP 563](https://www.python.org/dev/peps/pep-0563/), which was added in Python 3.7. Among other changes, it allows type annotations for methods in a class to use the name of the class in which they were defined. For example, the following is not valid without PEP 563 due to `Foo` not being defined at the point it is used in the type definition:

```python3
class Foo:
    def make_foo() -> Foo:
        return Foo()
```

This is valid in Python 3.7+ when `from __future__ import annotations` is used, and will become the default in Python 4.

*  Nuitka version, full Python version and Platform (Windows, OSX, Linux ...)

```
(ins)awang@sid:/tmp/nuitka$ apt show python3.7
Package: python3.7
Version: 3.7.1-1
<snip>
```
```
(ins)awang@sid:/tmp/nuitka$ python3.7 -m nuitka --version
0.6.1rc7
Python: 3.7.0+ (default, Aug 31 2018, 23:21:37) 
Executable: /home/awang/.cache/pypoetry/virtualenvs/test-py3.7/bin/python3.7
OS: Linux
Arch: x86_64
```

*  How did you install Nuitka and Python (pip, anaconda, deb, rpm, from source,
   what is a virtualenv ...), this is very important usually.

Python was installed using `apt` and Nuitka was installed through `poetry` with the following `pyproject.toml`:

```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = [""]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
nuitka = {git = "https://github.com/Nuitka/Nuitka", branch = "develop"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

```

*  If possible please supply a [Short, Self Contained, Correct, Example](http://sscce.org/)
   that demonstrates the issue i.e a small piece of code which reproduces
   the issue and can be run with out any other (or as few as possible)
   external dependencies.

The following file demonstrates the issue:

```python3
from __future__ import annotations

class Foo:
    def make_foo() -> Foo:
        return Foo()
```
```
(ins)awang@sid:/tmp/nuitka$ python3.7 test.py
(ins)awang@sid:/tmp/nuitka$ echo $?
0
(ins)awang@sid:/tmp/nuitka$ python3.7 -m nuitka test.py
  File "test.py", line 1
    from __future__ import annotations
    ^
SyntaxError: future feature annotations is not defined

Nuitka is very syntax compatible with standard Python. It is currently running
with Python version '3.7', you might want to specify more clearly with the use
of the precise Python interpreter binary and '-m nuitka', e.g. use this
'python2.7 -m nuitka' option, if that's not the one the program expects.
```

**Comment by kayhayen** [comment] 2018-11-01 10:57
Wow, surprising, this also means that CPython tests don't cover it yet:

https://www.python.org/dev/peps/pep-0563/#enabling-the-future-behavior-in-python-3-7

So question is of course, how to check it. I think we should at least print the resulting "__annotations__" of the class, to check it is still a string even there, or resolved in a later step already.

**Comment by kayhayen** [comment] 2018-11-01 11:33
Oh my goodness, this is what I get:

```
>>> s
'from __future__ import annotations\n\nclass Foo:\n    def make_foo() -> Foo:\n        return Foo()\n\nprint(Foo.make_foo.__annotations__)'
```

```
>>> a = ast.parse(s)
>>> ast.dump(a)
"Module(body=[ImportFrom(module='__future__', names=[alias(name='annotations', asname=None)], level=0), ClassDef(name='Foo', bases=[], keywords=[], body=[FunctionDef(name='make_foo', args=arguments(args=[], vararg=None, kwonlyargs=[], kw_defaults=[], kwarg=None, defaults=[]), body=[Return(value=Call(func=Name(id='Foo', ctx=Load()), args=[], keywords=[]))], decorator_list=[], returns=Name(id='Foo', ctx=Load()))], decorator_list=[]), Expr(value=Call(func=Name(id='print', ctx=Load()), args=[Attribute(value=Attribute(value=Name(id='Foo', ctx=Load()), attr='make_foo', ctx=Load()), attr='__annotations__', ctx=Load())], keywords=[]))])"
```

So the effect seems not to be present where it would make sense. Seems CPython undoes the name lookup somehow back to a string, instead of providing a string in the ast tree, it is doing a kind of back translation. Seems that is happening in `_PyAST_ExprAsUnicode` which is a C API function only, not currently exposed to Python, but `ctypes` should help us anyway.

**Comment by kayhayen** [comment] 2018-11-01 15:00
So `_PyAST_ExprAsUnicode` is not an option, the ast nodes are Python objects, but I found another way, namely, using `compile` with the future value enabled, will do it for us, so basically I am injecting the node into an existing node tree that does only `x:1` and then `exec` that one, which only assigns to the `__annotations__` value, which is safe as it can only create a string.

This is then looked up, and used as an `__annotation__`.

I am not sure who should be more ashamed. The designers of this or the hacker that I am, but this works. I am currently only doing it for function arguments and return value. Obviously there is also module and class level assignments, which I will add as well, then this should be good, and it's even good enough for a hotfix I would say, and one is coming shortly anyway.

Yours,
Kay

**Comment by kayhayen** [comment] 2018-11-01 15:52
Will be pushed to factory branch in a couple of minutes.

**Comment by aw1621107** [comment] 2018-11-01 16:56
Wow, that was fast. Thanks!

> Seems CPython undoes the name lookup somehow back to a string, instead of providing a string in the ast tree, it is doing a kind of back translation

The [reference implementation](https://github.com/python/cpython/pull/4390) says that "AST unparsing" was used; I don't know if that has changed since then.

**Comment by kayhayen** [comment] 2018-11-02 08:17
It seems they made a prototype of that AST unparsing as a tool, but I doubt they kept it in sync or are going to, and it's fairly complex code.

My trick works fairly well, and gets at their C code directly, and as used by standard Python. I will create a CPython bug to try and get `ast.unparse` exposed for maybe 3.8, as it could potentially be faster.

**Comment by kayhayen** [comment] 2018-11-02 08:30
So the issue is https://bugs.python.org/issue35143 

Lets hope I was stupid, and it has just escaped my attention, or they add it for 3.8 at least.

**Comment by kayhayen** [comment] 2018-12-05 17:19
This is indeed going to change for 3.8, my workaround is in develop and will be in the next stable release, therefore closing.

**Closed by kayhayen** 2018-12-05 17:19 UTC
Labels: bug, factory
