### ISSUE TITLE
  File "importlib.py", line 126, in import_module ModuleNotFoundError: No module named 'huggingface_hub.repocard'

### ISSUE THREAD

**Issue by ArEnSc** [Nuitka/Nuitka#2375] opened 2023-08-08 07:51 UTC
Upon running the main.exe executable
``` 
File "importlib.py", line 126, in import_module
ModuleNotFoundError: No module named 'huggingface_hub.repocard'
```
Python 3.10.3
Nuitka version 1.7.9

Using Pip3
```python
from transformers import LlamaTokenizer, TextGenerationPipeline
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
import logging

logging.basicConfig(
    format="%(asctime)s %(levelname)s [%(name)s] %(message)s", level=logging.INFO, datefmt="%Y-%m-%d %H:%M:%S"
)
# if need files lmk I will provide links.
quantized_model_dir = r"C:\Users\Tensor\Desktop\TestSentencePiece\Pygmalion-7b-4bit-GPTQ-Safetensors"
model_dir = r"C:\Users\Tensor\Desktop\TestSentencePiece\Pygmalion-7b-4bit-GPTQ-Safetensors"
vocab_file = r"C:\Users\Tensor\Desktop\TestSentencePiece\Pygmalion-7b-4bit-GPTQ-Safetensors\tokenizer.model"
tokenizer_file = r"C:\Users\Tensor\Desktop\TestSentencePiece\Pygmalion-7b-4bit-GPTQ-Safetensors\tokenizer.json"

tokenizer = LlamaTokenizer(vocab_file=vocab_file,tokenizer_file=tokenizer_file,use_fast=True)

examples = [
    tokenizer(
        "auto-gptq is an easy-to-use model quantization library with user-friendly apis, based on GPTQ algorithm."
    )
]
print(tokenizer("auto_gptq is", return_tensors="pt"))

quantize_config = BaseQuantizeConfig(
    bits=4,  # quantize model to 4-bit
    group_size=-1,  # it is recommended to set the value to 128
    desc_act=True,  # set to False can significantly speed up inference but the perplexity may slightly bad
)

model = AutoGPTQForCausalLM.from_quantized(model_name_or_path=model_dir, device="cuda:0",quantize_config=quantize_config,use_safetensors=True,model_basename="Pygmalion-7B-GPTQ-4bit-act-order")

#inference with model.generate
print(tokenizer.decode(model.generate(max_new_tokens=100,**tokenizer("auto_gptq is", return_tensors="pt").to(model.device))[0]))

```

```
python -m nuitka .\Main.py --follow-imports --show-progress --show-scons --show-modules --include-package=setuptools --noinclude-dask-mode=nofollow --noinclude-numba-mode=nofollow --lto=no --standalone --report="gptqfail.txt"
```

**Comment by ArEnSc** [comment] 2023-08-08 07:51
[gptqfail.txt](https://github.com/Nuitka/Nuitka/files/12288720/gptqfail.txt)

**Comment by ArEnSc** [comment] 2023-08-08 07:52
installed this binary in the python virtual environment 
auto_gptq-0.3.2+cu117-cp310-cp310-win_amd64.whl
It seems to failing to pickup huggingface hub.

**Comment by ArEnSc** [comment] 2023-08-08 15:39
@kayhayen just letting you know I have brought support because of your amazing responsiveness on discord and on issues thanks for all your help so far!

**Comment by kayhayen** [comment] 2023-08-09 06:10
@ArEnSc very welcome :)

**Comment by kayhayen** [comment] 2023-08-09 06:20
From the looks of the code, I don't think it can work. I believe similar codes are working, so if you could provide the files referenced, that would be needed @ArEnSc or alternatively a more complete call stack, because I cannot really tell from where it is being used.

**Comment by kayhayen** [comment] 2023-08-10 08:19
How is that different from auto_gptq from https://pypi.org/project/auto-gptq or is it the same?

**Comment by ArEnSc** [comment] 2023-08-10 14:54
> How is that different from auto_gptq from https://pypi.org/project/auto-gptq or is it the same?

It's the same they had a bug that prevented me from installing it via pip =) hahaha it would say torch is not availible despite it being installed related 
https://github.com/PanQiWei/AutoGPTQ/issues/229#issuecomment-1673127300

**Comment by kayhayen** [comment] 2023-08-11 07:44
Ok, I need to be super careful about executing code for obvious reasons. I will try it in a sandbox later today.

**Comment by ArEnSc** [comment] 2023-08-11 13:06
> Ok, I need to be super careful about executing code for obvious reasons. I will try it in a sandbox later today.
Oh right you can get the binaries from here
https://github.com/PanQiWei/AutoGPTQ/releases/tag/v0.4.0

**Comment by ArEnSc** [comment] 2023-08-24 00:20
@kayhayen I realized the code might not work unless you have a gpu of some kind.
```
from transformers import LlamaTokenizer, TextGenerationPipeline
from auto_gptq import AutoGPTQForCausalLM, BaseQuantizeConfig
import logging

logging.basicConfig(
    format="%(asctime)s %(levelname)s [%(name)s] %(message)s", level=logging.INFO, datefmt="%Y-%m-%d %H:%M:%S"
)

quantized_model_dir = "Pygmalion-7b-4bit-GPTQ-Safetensors"
model_basename = "Pygmalion-7B-GPTQ-4bit.act-order"

vocab_file = r"Pygmalion-7b-4bit-GPTQ-Safetensors/tokenizer.model"
tokenizer_file = r"Pygmalion-7b-4bit-GPTQ-Safetensors/tokenizer.json"

tokenizer = LlamaTokenizer(
    vocab_file=vocab_file, tokenizer_file=tokenizer_file, use_fast=True)

examples = [
    tokenizer(
        "auto-gptq is an easy-to-use model quantization library with user-friendly apis, based on GPTQ algorithm."
    )
]
print(tokenizer("auto_gptq is", return_tensors="pt"))

quantize_config = BaseQuantizeConfig(
    bits=4,  # quantize model to 4-bit
    group_size=-1,  # it is recommended to set the value to 128
    desc_act=True,  # set to False can significantly speed up inference but the perplexity may slightly bad
)

model = AutoGPTQForCausalLM.from_quantized(
    quantized_model_dir, device="cuda:0", quantize_config=quantize_config, 
    use_safetensors=True, model_basename=model_basename)

# inference with model.generate

tokenized = tokenizer("auto_gptq is", return_tensors="pt").to(model.device)
print(tokenized)
generated = model.generate(max_new_tokens=100, **tokenized) # It will fail here if successful
print(generated)
print(tokenizer.decode(generated[0]))

```
the code will fail at generated if running on a cpu thanks!

**Comment by doradsoft** [comment] 2023-08-29 17:00
Hey,
I have a much simple reproduce

```python
from datasets import Dataset
Dataset.from_list([{"a":1}])
```

```
main.exe
Traceback (most recent call last):
  File "C:\Users\dorad\AppData\Local\Temp\ONEFIL~1\main.py", line 1, in <module>
    from datasets import Dataset

  File "C:\Users\dorad\AppData\Local\Temp\ONEFIL~1\datasets\__init__.py", line 22, in <module datasets>
  File "C:\Users\dorad\AppData\Local\Temp\ONEFIL~1\datasets\arrow_dataset.py", line 61, in <module datasets.arrow_dataset>
  File "C:\Users\dorad\AppData\Local\Temp\ONEFIL~1\huggingface_hub\__init__.py", line 322, in __getattr__
  File "importlib.py", line 126, in import_module
ModuleNotFoundError: No module named 'huggingface_hub.repocard'
```

**Comment by kayhayen** [comment] 2023-08-30 11:22
Trying the new example right now, finally catching up on this issue.

**Comment by doradsoft** [comment] 2023-09-03 13:15
In parallel to your wonderful investigation and treating,
Is there any workaround that could be applied?

**Comment by kayhayen** [comment] 2023-09-03 15:50
I have been adding support the the .pyi based attach stub recently, and it's not yet finished, but once it is, I will turn to do something for huggingface_hub as well, which seems to force inline the result of the .pyi file. I do not have a workaround yet, but this is what I am working on, give it a few days more, then this will work as well.

**Comment by kayhayen** [comment] 2023-09-08 02:38
So, the .pyi stuff is now working for librosa, and I now need to verify with skimage and sklearn if that works as well, now and allows to remove our package configs.

The problem is that their vendored copy of lazy loader needs  a bit special care to extract the information, but that should be relatively easy.

**Comment by kayhayen** [comment] 2023-09-22 09:17
So, I have done this, but it was now crashing inside of transformers on the line `from huggingface_hub import Repository, list_repo_files` declaring some kind of inconsistency about raised exception happens. This import while being "hard" now would still be able to raise an exception, because the package may still find issues during load, but somehow the annotating and the declaration ahead of time mismatch. This must be a more general issue with the hard imports, that's now facing with these kinds of nodes being used more often. The forward propagation of these 2 hard values may case it, I am not sure now.

**Comment by kayhayen** [comment] 2023-09-27 08:51
So, this is on current factory and staging (commercial variant of factory). For datasets specifically, a bit of configuration was added, so it works now as well. The compilation of it is terribly long unfortunately due to the large amounts of modules being pulled in.

For `huggingface_hub` itself that is now working in that context. Let me know if any of the reproducers given here still fail and in what way, potentially in new issues though, since I want to close this for that issue alone.

**Comment by doradsoft** [comment] 2023-09-28 16:41
I confirm that works for our use case. Thanks @kayhayen.

**Comment by kayhayen** [comment] 2023-09-30 09:38
This is now on develop, about to announce 1.8 and then closing down on 1.9 soon after I hope, not sure how much of 3.12 work I will do before though, lets see.

**Comment by kayhayen** [comment] 2023-11-23 08:35
Part of the 1.9 release I just made.

**Closed by kayhayen** 2023-11-23 08:35 UTC
Labels: bug, develop
