### ISSUE TITLE
Import order affects the compile result when using `faker` and `fastapi` together

### ISSUE THREAD

**Issue by huyz-git** [Nuitka/Nuitka#3183] opened 2024-11-05 02:06 UTC
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

  > python -m nuitka --version

```
2.5rc12
Commercial: None
Python: 3.12.7 (main, Oct  1 2024, 11:15:50) [GCC 14.2.1 20240910]
Flavor: Arch Python
Executable: /home/abc/.virtualenvs/test/bin/python
OS: Linux
Arch: x86_64
Distribution: Arch None
Version C compiler: /usr/bin/gcc (gcc 14.2.1).
```

- How did you install Nuitka and Python

Use `pip install -e .` on `develop` branch (commit 2bd0a4f14) in a virtualenv.

- The specific PyPI names and versions

With a brand new virtualenv, I only run `pip install fastapi faker` and `pip install -e .`, which results the following package installed:
  > python -m pip list -v

```
Package           Version     Editable project location Location                                                 Installer
----------------- ----------- ------------------------- -------------------------------------------------------- ---------
annotated-types   0.7.0                                 /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
anyio             4.6.2.post1                           /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
Faker             30.8.2                                /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
fastapi           0.115.4                               /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
idna              3.10                                  /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
Nuitka            2.5rc12     /home/abc/Repos/Nuitka    /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
ordered-set       4.1.0                                 /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
pip               24.2                                  /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
pydantic          2.9.2                                 /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
pydantic_core     2.23.4                                /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
python-dateutil   2.9.0.post0                           /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
six               1.16.0                                /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
sniffio           1.3.1                                 /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
starlette         0.41.2                                /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
typing_extensions 4.12.2                                /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip
zstandard         0.23.0                                /home/abc/.virtualenvs/test/lib/python3.12/site-packages pip

```

- Also supply a Short, Self Contained, Correct, Example

When using `faker` and `fastapi` together, the import order will affect the compile result. Specifically, if I import `fastapi` before `faker`, `faker` will result an error.

Here are some examples.

When using `faker` only, it works:
```
import faker
_ = faker.Faker(locale="en_US")
```

When using `faker` before `fastapi`, it works:
```
import faker
_ = faker.Faker(locale="en_US")

import fastapi
```

When using `faker` after `fastapi`, it doesn't work:
```
import fastapi

import faker
_ = faker.Faker(locale="en_US")
```
The error is:
```
Traceback (most recent call last):
  File "/tmp/test/test6.dist/test6.py", line 4, in <module>
  File "/tmp/test/test6.dist/faker/proxy.py", line 72, in __init__
  File "/tmp/test/test6.dist/faker/factory.py", line 44, in create
AttributeError: Invalid configuration for faker locale `en_US`
```

For the second and third case, `nuitka` both compiled 845 C files.

The error comes from `faker` package from here:
```
        if locale not in AVAILABLE_LOCALES:
            msg = f"Invalid configuration for faker locale `{locale}`"
            raise AttributeError(msg)
```
while `AVAILABLE_LOCALES` is imported from `.config` which is:
```
from importlib import import_module

from .utils.loading import find_available_locales, find_available_providers

DEFAULT_LOCALE = "en_US"

META_PROVIDERS_MODULES = [
    "faker.providers",
]

PROVIDERS = find_available_providers([import_module(path) for path in META_PROVIDERS_MODULES])

AVAILABLE_LOCALES = find_available_locales(PROVIDERS)
```
Perhaps this issue is somehow related to `importlib`? Since `faker` uses `importlib` to find modules.

- Provide in your issue the Nuitka options used

`python -m nuitka --standalone ./test6.py`

**Comment by kayhayen** [comment] 2024-11-07 15:11
File based module scans are wrong and not successful with Nuitka, but the path for normal Python in list_module ought to work with Nuitka.

If you provided the reports (and maybe compared them yourself), you might get closer to why it happens. I don't see a way other than if `path` is somehow becoming wrong.

**Comment by kayhayen** [comment] 2024-11-07 15:19
It looks to me, as if you believe `.config` is compiled, and then it's not, because it's maybe only implicitly picked up by fastapi, and then has no dependencies resolved. If that's true, this would definitely be a weakness of the `fastapi` support for Nuitka. I am not yet sure how it would cause issues you see though.

**Comment by kayhayen** [comment] 2024-11-11 11:50
I actually think I managed to reproduce this, and then I didn't anymore, after fixing an implicit dependency on attrs for the pydantic schema, not sure what's going on there.

**Comment by kayhayen** [comment] 2024-11-11 12:47
So, what happens is that `sys.frozen` is set for multiprocessing, and remains set. We need multiprocess to handle things differently, but when the plugin kicks in and multiprocessing or anyio is loaded, this gets set and is not removed, and activates code paths that are intended for non-Nuitka, as the later will typically work properly, but certainly not always.

Removing that will be a bigger thing. You can add `del sys.frozen` as a workaround. I have changed the multiprocessing plugin to do that itself, and I will probably want to do it, such that it is not necessary. We can now just modify the source of multiprocessing on the fly to never have this set, but that will be a beauty thing.

Probably a bunch of software has never been compiled without that bug. But as can be seen, also a bunch is compiled without that, since faker is assumed to be working, but anything mixing in multiprocessing usage would have changed that to the worse, and it comes down to import order.

**Comment by kayhayen** [comment] 2024-11-11 13:16
Thanks for your report, this is fixed on the factory branch, which is a development version under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-11-13 13:26
This now on the develop branch and will be part of the 2.5 release.

**Comment by kayhayen** [comment] 2024-11-16 12:43
Part of the 2.5 release I just made.

**Closed by kayhayen** 2024-11-16 12:43 UTC
Labels: bug, develop, excellent_report
