### ISSUE TITLE
Assertion failed after upgrade from 2.4.11 to 2.5.1

### ISSUE THREAD

**Issue by elct9620** [Nuitka/Nuitka#3217] opened 2024-11-24 05:31 UTC
- Nuitka version, full Python version, flavor, OS, etc. as output by *this exact* command.

```
2.5.1
Commercial: None
Python: 3.12.5 (main, Aug  6 2024, 19:08:49) [Clang 16.0.6 ]
Flavor: Unknown
Executable: /Users/elct9620/Workspace/Finlab/quill/.venv/bin/python
OS: Darwin
Arch: arm64
macOSRelease: 15.1.1
Version C compiler: ~/Workspace/Finlab/quill/.devbox/nix/profile/default/bin/clang (clang 16.0.6).
```

- How did you install Nuitka and Python

```
# Setup Python
devbox init
devbox add python@3.12
devbox add poetry
devbox add clang

# Setup Nuitka
poetry add nuitka
```

- The specific PyPI names and versions

```
Package                   Version Location                                                                                         Installer
------------------------- ------- ------------------------------------------------------------------------------------------------ ------------
argon2-cffi               23.1.0  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
argon2-cffi-bindings      21.2.0  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
behave                    1.2.6   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
bottle                    0.13.2  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
cffi                      1.17.1  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
clr-loader                0.2.6   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
docstring-to-markdown     0.15    /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
fugle-trade               1.2.0   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
fugle-trade-core          2.1.0   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
importlib_metadata        8.5.0   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
jedi                      0.19.1  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
keyring                   23.5.0  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
keyrings.cryptfile        1.3.8   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
Nuitka                    2.5.1   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
ordered-set               4.1.0   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
parse                     1.20.2  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
parse_type                0.6.4   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
parso                     0.8.4   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pip                       24.0    /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        pip
pluggy                    1.5.0   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
poetry                    1.8.3   /nix/store/vzr6bly4qcqrqr661gqpfy2mapm8d30l-python3.12-poetry-1.8.3/lib/python3.12/site-packages
proxy_tools               0.1.0   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pycparser                 2.22    /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pycryptodome              3.21.0  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pyobjc-core               10.3.1  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pyobjc-framework-Cocoa    10.3.1  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pyobjc-framework-Quartz   10.3.1  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pyobjc-framework-Security 10.3.1  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pyobjc-framework-WebKit   10.3.1  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
python-lsp-jsonrpc        1.1.2   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
python-lsp-server         1.12.0  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pythonnet                 3.0.4   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
pywebview                 5.3.2   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
ruff                      0.7.4   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
six                       1.16.0  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
typing_extensions         4.12.2  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
ujson                     5.10.0  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
websocket-client          1.8.0   /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
zipp                      3.20.2  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
zstandard                 0.23.0  /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages                        Poetry 1.8.3
```

- Many times when you get an error from Nuitka, your setup may be special

N/A

- Also supply a Short, Self Contained, Correct, Example

1. Install `pywebview`
2. Crewate window via `pywebview`

```py
# nuitka-project: --include-data-dir={MAIN_DIRECTORY}/frontend/dist=frontend
is_compiled = "__compiled__" in globals()

def main():
    if is_compiled:
        # NOTE: Nuitka use __file__ to get data dir path
        index = os.path.join(os.path.dirname(__file__), "frontend/index.html")
        webview.create_window("Quill", index)
        webview.start()
    else:
        webview.create_window("Quill", "http://localhost:5173")
        webview.start(debug=True)


if __name__ == "__main__":
    main()
```

- Provide in your issue the Nuitka options used

```
nuitka main.py --mode=onefile
```

> Without `--mode` still have the same error

- Note if this is a regression

Every time I get this error with `--debug` options

```
Assertion failed: (dk->dk_kind != DICT_KEYS_GENERAL), function Nuitka_PyDictLookupStr, file /Users/elct9620/Workspace/Finlab/quill/.venv/lib/python3.12/site-packages/nuitka/build/static_src/HelpersDictionaries.c, line 1254.
zsh: abort      ./Quill.app/Contents/MacOS/Quill
```

**Comment by kayhayen** [comment] 2024-11-24 09:35
Your example is pretty garbage in my book, missing imports, and being different between compiled and uncompiled code in ways that make no sense (to me).

**Comment by kayhayen** [comment] 2024-11-24 09:42
Made me notice that --mode doesn't cater well to macOS bundles. I got the following error, and as such onefile ought to not be used. I think is definitely something missing there, and this better be resolved soon, since I updated Nuitka-Action to present mode as the default way of specifying what you want.

> FATAL: options-nanny: Error, package 'Foundation' requires '--macos-create-app-bundle' to be used or else it cannot work. 

That said, I am getting a segfault indeed.

**Comment by kayhayen** [comment] 2024-11-24 11:29
So, `Foundation` module violates the rule that only strings are allowed in the module dictionary, and causes the wrong code to be used. When I fix that, it doesn't crash anymore in that code, but for the 3.11 variant of the module variable module value caching code, I am getting assertions, since it expects string dictionaries too, and that's not true for the `AppKit` module apparently.

This is another mess, and we probably will just not attempt any caching for modules being subjected to this. I will check out how 3.11 proper or higher deals with this.

**Comment by kayhayen** [comment] 2024-11-24 12:02
I am confused about whether and how this can be a regression. The module cache code is new, but for 3.12, every module access that is not cached should have triggered it already. However, the report quality is too low to tell how reliable the information is. I think it should have asserted for 3.12 before, but maybe it didn't actually segfault in all cases, and only the module cache did now.

**Comment by kayhayen** [comment] 2024-11-24 12:25
Thanks for your report. This is fixed on the factory branch, which is a development version that is under rapid development. You can try it out by going here: https://nuitka.net/doc/factory.html 

Feedback on whether this is working is very welcome. Please do not share plans to do it; only confirm or deny that it is working.

**Comment by kayhayen** [comment] 2024-11-24 15:43
Part of the 2.5.3 hotfix release.

**Closed by kayhayen** 2024-11-24 15:43 UTC
Labels: bug, factory
