### ISSUE TITLE
CentOS7 with Python3.11  *sorry, unimplemented: non-trivial designated initializers not supported*

### ISSUE THREAD

**Issue by McHill007** [Nuitka/Nuitka#2516] opened 2023-10-26 19:40 UTC
Hi, we are getting the following problem when compiling our project on CentOS7 with Python3.11. Everything works smooth on Ubuntu 22.0.4. 

I can provide the full output if required.

```
Nuitka-Options:INFO: Used command line options: --standalone --onefile --show-scons --assume-yes-for-downloads --output-dir=bin -o project_v13.1.3.bin --enable-console --include-data-files=src/lib/logs/logging.conf=lib/logs/logging.conf --disable-cache=ccache --company-name=Project --file-version=13.1.3 --product-version=13.1.3 src/main.py
```
```
g++ -o static_src/CompiledFunctionType.o -c -fvisibility-inlines-hidden -fvisibility=hidden -fwrapv -pipe -fpartial-inlining -Wno-deprecated-declarations -fno-var-tracking -fcompare-debug-second -O3 -fPIC -D_NUITKA_NON_C11_MODE -D__NUITKA_NO_ASSERT__ -D_NUITKA_STANDALONE -D_NUITKA_ONEFILE_MODE -D_NUITKA_ONEFILE_TEMP_BOOL -D_NUITKA_CONSTANTS_FROM_INCBIN -D_NUITKA_FROZEN=153 -D_NUITKA_EXE -D_NUITKA_PLUGIN_MULTIPROCESSING_ENABLED=1 -I/usr/local/include/python3.11 -I. -I/home/project/.local/lib/python3.11/site-packages/nuitka/build/include -I/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src static_src/CompiledFunctionType.cpp
In file included from /home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorType.c:35:0,
                 from static_src/CompiledFunctionType.cpp:2860:
/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorTypeUncompiledIntegration.c:559:1: sorry, unimplemented: non-trivial designated initializers not supported
 };
 ^
/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorTypeUncompiledIntegration.c:559:1: sorry, unimplemented: non-trivial designated initializers not supported
...
/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorTypeUncompiledIntegration.c: In function 'PyObject* Nuitka_UncompiledGenerator_throw(PyGenObject*, int, PyObject*, PyObject*, PyTracebackObject*)':
/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorTypeUncompiledIntegration.c:1010:1: error: jump to label 'failed_throw' [-fpermissive]
 failed_throw:
 ^
/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorTypeUncompiledIntegration.c:975:14: error:   from here [-fpermissive]
         goto failed_throw;
              ^
/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorTypeUncompiledIntegration.c:978:20: error:   crosses initialization of 'PyThreadState* tstate'
     PyThreadState *tstate = _PyThreadState_GET();
                    ^
/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorTypeUncompiledIntegration.c:1010:1: error: jump to label 'failed_throw' [-fpermissive]
 failed_throw:
 ^
/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorTypeUncompiledIntegration.c:923:22: error:   from here [-fpermissive]
                 goto failed_throw;
                      ^
/home/project/.local/lib/python3.11/site-packages/nuitka/build/static_src/CompiledGeneratorTypeUncompiledIntegration.c:978:20: error:   crosses initialization of 'PyThreadState* tstate'
     PyThreadState *tstate = _PyThreadState_GET();
                    ^
scons: *** [static_src/CompiledFunctionType.o] Error 1
scons: internal stack trace:
  File "/home/project/.local/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Job.py", line 258, in run
    task.execute()
  File "/home/project/.local/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Script/Main.py", line 206, in execute
    SCons.Taskmaster.OutOfDateTask.execute(self)
  File "/home/project/.local/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Taskmaster.py", line 255, in execute
    self.targets[0].build()
  File "/home/project/.local/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Node/__init__.py", line 766, in build
    self.get_executor()(self, **kw)
  File "/home/project/.local/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 397, in __call__
    return _do_execute_map[self._do_execute](self, target, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/project/.local/lib/python3.11/site-packages/nuitka/build/inline_copy/lib/scons-3.1.2/SCons/Executor.py", line 131, in execute_action_list
    raise status    # TODO pylint E0702: raising int not allowed
    ^^^^^^^^^^^^
Nuitka-Scons:INFO: Backend linking program with 443 files (no progress information available for this stage).
scons: building terminated because of errors.
Error: Process completed with exit code 1.
```

> Nuitka version, full Python version, flavor, OS, etc. as output by this command.

```
1.7.10
Commercial: None
Python: 3.11.6 (main, Oct 26 2023, 10:20:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]
Flavor: Unknown
Executable: /usr/bin/python
OS: Linux
Arch: x86_64
Distribution: Centos (based on Fedora) 7
Nuitka-Scons:INFO: The provided gcc is too old, switching to its g++ instead.
Version C compiler: /usr/lib64/ccache/g++ (g++).
```

> The specific PyPI names and versions

```
cachetools==5.3.2
certifi==2023.7.22
charset-normalizer==3.3.1
distro==1.8.0
google-api-core==2.12.0
google-auth==2.23.3
google-cloud-core==2.3.3
google-cloud-storage==2.10.0
google-crc32c==1.5.0
google-resumable-media==2.6.0
googleapis-common-protos==1.61.0
idna==3.4
Nuitka @ git+https://github.com/Nuitka/Nuitka.git/@973ef3c27ff9409f622cb0213341acb52ab096e2
numpy==1.24.3
ordered-set==4.1.0
packaging==23.1
pandas==2.0.2
protobuf==4.24.4
pyasn1==0.5.0
pyasn1-modules==0.3.0
python-dateutil==2.8.2
pytz==2023.3
requests==2.31.0
rsa==4.9
six==1.16.0
tabulate==0.9.0
tinydb==4.8.0
tzdata==2023.3
urllib3==2.0.7
xmltodict==0.13.0
zstandard==0.20.0
```

I found simliar problems for windows with wrong MSVC version but nothing related to linux.

**Comment by kayhayen** [comment] 2023-10-27 07:54
> Nuitka-Scons:INFO: The provided gcc is too old, switching to its g++ instead.

With Python 3.11 this fallback is not supported, since that requires actually C. With new enough gcc however, it will work. We have solved that for our commercial Linux container. I am almost curious how the Python3.11 got compiled there without that. 

> Python: 3.11.6 (main, Oct 26 2023, 10:20:38) [GCC 4.8.5 20150623 (Red Hat 4.8.5-44)]

That should not be possible in my book, unless something changed in the minor releases of 3.11 still.

**Comment by kayhayen** [comment] 2023-10-27 08:12
Checking the changelog, I didn't find it. Just suspect now that that version information is wrong. The issue is, that the actual C11 exclusive syntax being used is "the not implemented" feature mentioned by the C++ compiler, is not part of C++ in any version and probably never will, and it's almost exactly like that in the Python source code, so it wouldn't work with GCC 4 for sure, and not with a C++ compiler.

I am therefore making it an error to attempt to use that compiler, at the time the switch is considered.

**Comment by McHill007** [comment] 2023-10-27 14:53
Thanks for the hint

Python 3.11 requires gcc 4.8
Nuitka seems to require 5.1 (according to documentation as far as I can see)
We will try to update the gcc version 

Looking forward to switch to the commercial version.

**Comment by kayhayen** [comment] 2023-10-30 13:53
This is fixed on the develop branch now, requires newer gcc there too. 

The real reason is that Nuitka uses C11 features, that GCC 4.8 does not have. It might be the case that Python has more luck with what is in GCC 4.8, but I will not do that. So, with that old GCC we use C++ which will never have that feature, since it's not ever going to be syntax-compatible with the specific syntax used there.

This could be solved, but I will not care. I think much rather should people install SCL devtools, e.g. via `devtoolset-9` after installing `centos-release-scl` will do the trick, and gives better results anyway. I have yet to migrate Nuitka RPM package builds away from OBS fully, but once I do, I might make it output the proper instructions per OS.

**Comment by kayhayen** [comment] 2023-11-23 08:30
Part of the 1.9 release I just made.

**Closed by kayhayen** 2023-11-23 08:30 UTC
Labels: develop
